### ISSUE TITLE
Hue bulb does not pair properly and shows up as other device

### ISSUE THREAD

**Issue by ivargj** [Koenkk/zigbee2mqtt#10106]
## What happened
I was trying to pair a Philips Hue E14 bulb, [similar to this one](https://www.zigbee2mqtt.io/devices/929002294203.html). 
At first it failed with an error and showed up as an unknown device. I was running an older version of Zigbee2MQTT, so my first step was to upgrade to 1.22.1. 

After the upgrade, I'm not getting any log entries of "starting interview" or similar, after force removing the unknown device and factory resetting the bulb. Instead, a device appears that does not match the Hue bulb: a [NAMRON ZigBee dimmer 400W](https://www.zigbee2mqtt.io/devices/4512700.html). (I have several of these in my network.) I also manage to find it by touchlink, but it shows up as the same Namron device. 

I find errors like this in the logs: 
`error 2021-12-09 01:37:47: Failed to configure '0x0017880108e9e8b6', attempt 1 (Error: Bind 0x0017880108e9e8b6/1 genOnOff from '0x00124b0014d94b9f/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7))`

I have force removed the device, reset the bulb and tried again several times, with the same result. 

Another thing I have noticed is that the model number on my device is 929002294201, while the one I linked to earlier is 929002294203. (just the last digit different) 

I considered if this could be linked to issue #8670 
due to the lack of pairing/interview entries in the logs. But moving it close to the coordinator does not change the behavior. 

It's similar to issue #3791 with similar error messages, but restarting and replugging the stick does not solve the problem. 

Some considerations: 

- Is there anything else than force removing I should do in order to get it to completely reset and forget about the device? 
- Could it be simply that adding support for the other model number solves it? I guess it should have logged that the device is not supported in that case? 

Any help would be much appreciated! :) 

## What did you expect to happen

Successful pairing, as has happened with all my other Hue bulbs earlier. 

## How to reproduce it (minimal and precise)

Try pairing of the above mentioned device. 

## Debug info
Zigbee2MQTT version: 1.22.1-1
Adapter hardware: CC2531
Adapter firmware version: 20190608

**Comment by ivargj** [comment]
Update: I just tried updating to the latest version of Zigbee2MQTT, and after restarting the system and resetting the bulb I get a slightly different set of symptoms. 

I see the following in the logs: 

`info  2022-01-01 21:18:07: Device '0x0017880108e9e8b6' joined
info  2022-01-01 21:18:08: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x0017880108e9e8b6","ieee_address":"0x0017880108e9e8b6"},"type":"device_joined"}'
info  2022-01-01 21:18:08: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x0017880108e9e8b6"},"type":"device_connected"}'
info  2022-01-01 21:18:08: Starting interview of '0x0017880108e9e8b6'
info  2022-01-01 21:18:08: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x0017880108e9e8b6","ieee_address":"0x0017880108e9e8b6","status":"started"},"type":"device_interview"}'
info  2022-01-01 21:18:08: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x0017880108e9e8b6"},"type":"pairing"}'

error 2022-01-01 21:20:27: Failed to interview '0x0017880108e9e8b6', device has not successfully been paired
info  2022-01-01 21:20:28: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x0017880108e9e8b6","ieee_address":"0x0017880108e9e8b6","status":"failed"},"type":"device_interview"}'
info  2022-01-01 21:20:28: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_failed","meta":{"friendly_name":"0x0017880108e9e8b6"},"type":"pairing"}'
info  2022-01-01 21:20:28: Starting interview of '0x0017880108e9e8b6'
info  2022-01-01 21:20:28: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x0017880108e9e8b6","ieee_address":"0x0017880108e9e8b6","status":"started"},"type":"device_interview"}'
info  2022-01-01 21:20:28: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x0017880108e9e8b6"},"type":"pairing"}'
`

The device now shows up in the GUI as "Not supported" and with "interview completed: False". 

As I understand it, a normal unsupported device will still succeed in pairing?

**Comment by ivargj** [comment]
By the way, I have two Hue-devices that paired flawlessly after this issue occurred, but this bulb is still not pairing. So it doesn't seem to be any problems with pairing in general.
