### ISSUE TITLE
Sending transition to SM323 crashes CC2531 coordinator

### ISSUE THREAD

**Issue by Morphy99** [Koenkk/zigbee2mqtt#10175]
## What happened
When sending transition to a [Samotech ZB Dimmer](https://www.zigbee2mqtt.io/devices/SM323.html) the coordinator locks up and the ZB network goes down. Had some issues with the coordinator going down recently due to being in close proximity to a WiFi router. After moving away with a USB extension cable and changing the router channel away this has been resolved. 

Currently 26 devices are joined. With the majority being Aqara contact sensors and 3 x SM323 dimmers, 1 x IKEA Light bulb and 1 x IKEA outlet as routers.

This appears to be when things go wrong:

```
debug 2021-11-24 14:19:49: Received MQTT message on 'zigbee2mqtt/Light Switch Living Room/set' with data '{"state": "ON", "transition": 5.0, "brightness": 6}'
debug 2021-11-24 14:19:49: Publishing 'set' 'brightness' to 'Light Switch Living Room'
error 2021-11-24 14:19:49: Publish 'set' 'brightness' to 'Light Switch Living Room' failed: 'Error: Command 0x086bd7fffe5d3468/1 genLevelCtrl.moveToLevelWithOnOff({"level":6,"transtime":50}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> AF - dataRequest - {"dstaddr":7752,"destendpoint":1,"srcendpoint":1,"clusterid":8,"transid":39,"options":0,"radius":30,"len":6,"data":{"type":"Buffer","data":[1,22,4,6,50,0]}}' failed with status '(0x02: INVALID_PARAM)' (expected '(0x00: SUCCESS)'))'
debug 2021-11-24 14:19:49: Error: Command 0x086bd7fffe5d3468/1 genLevelCtrl.moveToLevelWithOnOff({"level":6,"transtime":50}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> AF - dataRequest - {"dstaddr":7752,"destendpoint":1,"srcendpoint":1,"clusterid":8,"transid":39,"options":0,"radius":30,"len":6,"data":{"type":"Buffer","data":[1,22,4,6,50,0]}}' failed with status '(0x02: INVALID_PARAM)' (expected '(0x00: SUCCESS)'))
    at Object.func (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:322:27)
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
info  2021-11-24 14:19:49: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'brightness' to 'Light Switch Living Room' failed: 'Error: Command 0x086bd7fffe5d3468/1 genLevelCtrl.moveToLevelWithOnOff({\"level\":6,\"transtime\":50}, {\"sendWhenActive\":false,\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (SREQ '--> AF - dataRequest - {\"dstaddr\":7752,\"destendpoint\":1,\"srcendpoint\":1,\"clusterid\":8,\"transid\":39,\"options\":0,\"radius\":30,\"len\":6,\"data\":{\"type\":\"Buffer\",\"data\":[1,22,4,6,50,0]}}' failed with status '(0x02: INVALID_PARAM)' (expected '(0x00: SUCCESS)'))'","meta":{"friendly_name":"Light Switch Living Room"},"type":"zigbee_publish_error"}'
```
[FULL DEBUG LOG](https://pastebin.com/ZptT7SDf)
## What did you expect to happen
The light switch to accept transition as per the description on the Z2M devices page.
## How to reproduce it (minimal and precise)
In Home Assistant developer tools>services>send:

```
service: light.turn_on
data:
  transition: 5
target:
  entity_id: light.living_room
```
## Debug info
Zigbee2MQTT version: 1.22
Adapter hardware: CC2531
Adapter firmware version: 20201127 (routing fw I think):
`{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20201127,"transportrev":2},"type":"zStack12"}`

I've yet to try flashing firmware, 20211116. Not sure if any of the fixes would address this problem anyway?

SM323 details:
Firmware build date
20200701
Firmware version
3.09

**Comment by Morphy99** [comment]
Still an issue, have got some more logs I need to upload with coordinator debugging enabled. I've tried this after a zzh upgrade and it's no longer an issue so I suspect qty of messages is crashing the coordinator somehow.
