### ISSUE TITLE
Zigbee2Mqtt Crashes with Sengled RGB Lights

### ISSUE THREAD

**Issue by AngellusMortis** [Koenkk/zigbee2mqtt#10174]
## What happened

Zigbee2Mqtt crashes with error `Error: Cluster with name '64531' does not exist`

#### Logs
<details>
```
2021-12-14T13:12:31.741Z zigbee-herdsman:deconz:frameParser write parameter response - parameter id: 33 - status: 0
2021-12-14T13:12:34.359Z zigbee-herdsman:deconz:adapter checking coordinator simple descriptor
2021-12-14T13:12:34.361Z zigbee-herdsman:deconz:driver DATA_REQUEST - destAddr: 0x0 EP:0 SeqNr. 13 request id: 3
2021-12-14T13:12:34.362Z zigbee-herdsman:deconz:frameParser DATA_REQUEST RESPONSE - request id: 3 status: 0
2021-12-14T13:12:34.363Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:34.364Z zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101110
2021-12-14T13:12:34.364Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 1 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:34.366Z zigbee-herdsman:deconz:driver query aps data confirm
2021-12-14T13:12:34.371Z zigbee-herdsman:deconz:driver DATA_CONFIRM - sending data state request - SeqNr. 14
2021-12-14T13:12:34.371Z zigbee-herdsman:deconz:driver query aps data indication
2021-12-14T13:12:34.372Z zigbee-herdsman:deconz:frameParser DATA_CONFIRM RESPONSE - destAddr: 0x0 request id: 3 confirm status: 0
2021-12-14T13:12:34.372Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:34.373Z zigbee-herdsman:deconz:driver query aps data indication
2021-12-14T13:12:34.376Z zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 15
2021-12-14T13:12:34.378Z zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 15 srcAddr: 0x0 destAddr: 0x0 profile id: 0x0 cluster id: 0x8004 lqi: 53
2021-12-14T13:12:34.378Z zigbee-herdsman:deconz:frameParser response payload: 3,0,0,0,24,1,4,1,5,0,1,4,0,0,10,0,25,0,1,5,4,1,0,32,0,0,5,2,5
2021-12-14T13:12:34.378Z zigbee-herdsman:deconz:adapter resolve data request without a transSeq Nr.
2021-12-14T13:12:34.378Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:34.378Z zigbee-herdsman:deconz:adapter RECEIVING SIMPLE_DESCRIPTOR - addr: 0x0 EP:1 inClusters: 0,10,25,1281 outClusters: 1,32,1280,1282
2021-12-14T13:12:34.378Z zigbee-herdsman:deconz:adapter EP: 1
2021-12-14T13:12:34.378Z zigbee-herdsman:deconz:adapter profile ID: 260
2021-12-14T13:12:34.378Z zigbee-herdsman:deconz:adapter device ID: 5
2021-12-14T13:12:34.378Z zigbee-herdsman:deconz:adapter input cluster: 0x0
2021-12-14T13:12:34.378Z zigbee-herdsman:deconz:adapter input cluster: 0xa
2021-12-14T13:12:34.378Z zigbee-herdsman:deconz:adapter input cluster: 0x19
2021-12-14T13:12:34.378Z zigbee-herdsman:deconz:adapter input cluster: 0x501
2021-12-14T13:12:34.378Z zigbee-herdsman:deconz:adapter output cluster: 0x1
2021-12-14T13:12:34.378Z zigbee-herdsman:deconz:adapter output cluster: 0x20
2021-12-14T13:12:34.378Z zigbee-herdsman:deconz:adapter output cluster: 0x500
2021-12-14T13:12:34.378Z zigbee-herdsman:deconz:adapter output cluster: 0x502
2021-12-14T13:12:34.381Z zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 16
2021-12-14T13:12:39.859Z zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101010
2021-12-14T13:12:39.859Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:39.862Z zigbee-herdsman:deconz:driver query aps data indication
2021-12-14T13:12:39.862Z zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 17
2021-12-14T13:12:39.864Z zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 17 srcAddr: 0x7d8f destAddr: 0x0 profile id: 0x104 cluster id: 0xc lqi: 255
2021-12-14T13:12:39.865Z zigbee-herdsman:deconz:frameParser response payload: 24,134,10,85,0,57,246,40,166,67
2021-12-14T13:12:39.866Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":134,"manufacturerCode":null,"commandIdentifier":10},"Payload":[{"attrId":85,"dataType":57,"attrData":332.32000732421875}],"Command":{"ID":10,"name":"report","parameters":[{"name":"attrId","type":33},{"name":"dataType","type":32},{"name":"attrData","type":1000}]}},"address":32143,"endpoint":2,"linkquality":255,"groupID":null,"wasBroadcast":false,"destinationEndpoint":1}'
2021-12-14T13:12:39.869Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:41.360Z zigbee-herdsman:deconz:driver send read device state from queue. seqNr: 18
2021-12-14T13:12:41.363Z zigbee-herdsman:deconz:frameParser device state: 10100010
2021-12-14T13:12:41.364Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:46.184Z zigbee-herdsman:controller:endpoint Command 0x5c0272fffecc1788/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})
2021-12-14T13:12:46.186Z zigbee-herdsman:deconz:adapter zclFrame.payload:
2021-12-14T13:12:46.187Z zigbee-herdsman:deconz:adapter {}
2021-12-14T13:12:46.188Z zigbee-herdsman:deconz:driver DATA_REQUEST - destAddr: 0x24e EP:1 SeqNr. 19 request id: 4
2021-12-14T13:12:46.190Z zigbee-herdsman:deconz:frameParser DATA_REQUEST RESPONSE - request id: 4 status: 0
2021-12-14T13:12:46.190Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:46.279Z zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10100110
2021-12-14T13:12:46.280Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 1 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:46.283Z zigbee-herdsman:deconz:driver query aps data confirm
2021-12-14T13:12:46.289Z zigbee-herdsman:deconz:driver DATA_CONFIRM - sending data state request - SeqNr. 20
2021-12-14T13:12:46.291Z zigbee-herdsman:deconz:frameParser DATA_CONFIRM RESPONSE - destAddr: 0x24e request id: 4 confirm status: 0
2021-12-14T13:12:46.291Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:46.292Z zigbee-herdsman:deconz:adapter sendZclFrameToEndpoint - message send with transSeq Nr.: 3
2021-12-14T13:12:46.408Z zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101010
2021-12-14T13:12:46.408Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:46.411Z zigbee-herdsman:deconz:driver query aps data indication
2021-12-14T13:12:46.411Z zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 21
2021-12-14T13:12:46.413Z zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 21 srcAddr: 0x24e destAddr: 0x0 profile id: 0x104 cluster id: 0x6 lqi: 255
2021-12-14T13:12:46.413Z zigbee-herdsman:deconz:frameParser response payload: 8,3,11,0,0
2021-12-14T13:12:46.414Z zigbee-herdsman:deconz:adapter resolve data request with transSeq Nr.: 3
2021-12-14T13:12:46.415Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false,"reservedBits":0},"transactionSequenceNumber":3,"manufacturerCode":null,"commandIdentifier":11},"Payload":{"cmdId":0,"statusCode":0},"Command":{"ID":11,"name":"defaultRsp","parameters":[{"name":"cmdId","type":32},{"name":"statusCode","type":32}]}},"address":590,"endpoint":1,"linkquality":255,"groupID":null,"wasBroadcast":false,"destinationEndpoint":1}'
2021-12-14T13:12:46.415Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:46.416Z zigbee-herdsman:deconz:adapter response received
2021-12-14T13:12:46.498Z zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101010
2021-12-14T13:12:46.498Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:46.501Z zigbee-herdsman:deconz:driver query aps data indication
2021-12-14T13:12:46.501Z zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 22
2021-12-14T13:12:46.504Z zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 22 srcAddr: 0x24e destAddr: 0x0 profile id: 0x104 cluster id: 0x6 lqi: 255
2021-12-14T13:12:46.505Z zigbee-herdsman:deconz:frameParser response payload: 8,40,10,0,0,16,0
2021-12-14T13:12:46.506Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false,"reservedBits":0},"transactionSequenceNumber":40,"manufacturerCode":null,"commandIdentifier":10},"Payload":[{"attrId":0,"dataType":16,"attrData":0}],"Command":{"ID":10,"name":"report","parameters":[{"name":"attrId","type":33},{"name":"dataType","type":32},{"name":"attrData","type":1000}]}},"address":590,"endpoint":1,"linkquality":255,"groupID":null,"wasBroadcast":false,"destinationEndpoint":1}'
2021-12-14T13:12:46.511Z zigbee-herdsman:controller:endpoint DefaultResponse 0x5c0272fffecc1788/1 6(10, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})
2021-12-14T13:12:46.512Z zigbee-herdsman:deconz:adapter zclFrame.payload:
2021-12-14T13:12:46.513Z zigbee-herdsman:deconz:adapter { cmdId: 10, statusCode: 0 }
2021-12-14T13:12:46.513Z zigbee-herdsman:deconz:adapter no response expected
2021-12-14T13:12:46.513Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:46.517Z zigbee-herdsman:deconz:driver DATA_REQUEST - destAddr: 0x24e EP:1 SeqNr. 23 request id: 5
2021-12-14T13:12:46.519Z zigbee-herdsman:deconz:frameParser DATA_REQUEST RESPONSE - request id: 5 status: 0
2021-12-14T13:12:46.519Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:46.608Z zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10100110
2021-12-14T13:12:46.608Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 1 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:46.611Z zigbee-herdsman:deconz:driver query aps data confirm
2021-12-14T13:12:46.612Z zigbee-herdsman:deconz:driver DATA_CONFIRM - sending data state request - SeqNr. 24
2021-12-14T13:12:46.615Z zigbee-herdsman:deconz:frameParser DATA_CONFIRM RESPONSE - destAddr: 0x24e request id: 5 confirm status: 0
2021-12-14T13:12:46.615Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:46.615Z zigbee-herdsman:deconz:adapter sendZclFrameToEndpoint - message send with transSeq Nr.: 40
2021-12-14T13:12:48.237Z zigbee-herdsman:controller:endpoint Command 0x5c0272fffecc1788/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})
2021-12-14T13:12:48.237Z zigbee-herdsman:deconz:adapter zclFrame.payload:
2021-12-14T13:12:48.238Z zigbee-herdsman:deconz:adapter {}
2021-12-14T13:12:48.239Z zigbee-herdsman:deconz:driver DATA_REQUEST - destAddr: 0x24e EP:1 SeqNr. 25 request id: 6
2021-12-14T13:12:48.242Z zigbee-herdsman:deconz:frameParser DATA_REQUEST RESPONSE - request id: 6 status: 0
2021-12-14T13:12:48.243Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:48.330Z zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10100110
2021-12-14T13:12:48.330Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 1 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:48.335Z zigbee-herdsman:deconz:driver query aps data confirm
2021-12-14T13:12:48.340Z zigbee-herdsman:deconz:driver DATA_CONFIRM - sending data state request - SeqNr. 26
2021-12-14T13:12:48.344Z zigbee-herdsman:deconz:frameParser DATA_CONFIRM RESPONSE - destAddr: 0x24e request id: 6 confirm status: 0
2021-12-14T13:12:48.344Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:48.344Z zigbee-herdsman:deconz:adapter sendZclFrameToEndpoint - message send with transSeq Nr.: 4
2021-12-14T13:12:48.451Z zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101010
2021-12-14T13:12:48.451Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:48.451Z zigbee-herdsman:deconz:driver query aps data indication
2021-12-14T13:12:48.456Z zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 27
2021-12-14T13:12:48.458Z zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 27 srcAddr: 0x24e destAddr: 0x0 profile id: 0x104 cluster id: 0x6 lqi: 255
2021-12-14T13:12:48.458Z zigbee-herdsman:deconz:frameParser response payload: 8,4,11,1,0
2021-12-14T13:12:48.459Z zigbee-herdsman:deconz:adapter resolve data request with transSeq Nr.: 4
2021-12-14T13:12:48.461Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false,"reservedBits":0},"transactionSequenceNumber":4,"manufacturerCode":null,"commandIdentifier":11},"Payload":{"cmdId":1,"statusCode":0},"Command":{"ID":11,"name":"defaultRsp","parameters":[{"name":"cmdId","type":32},{"name":"statusCode","type":32}]}},"address":590,"endpoint":1,"linkquality":255,"groupID":null,"wasBroadcast":false,"destinationEndpoint":1}'
2021-12-14T13:12:48.462Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:48.462Z zigbee-herdsman:deconz:adapter response received
2021-12-14T13:12:48.537Z zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101010
2021-12-14T13:12:48.538Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:48.540Z zigbee-herdsman:deconz:driver query aps data indication
2021-12-14T13:12:48.545Z zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 28
2021-12-14T13:12:48.549Z zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 28 srcAddr: 0x24e destAddr: 0x0 profile id: 0x104 cluster id: 0x6 lqi: 255
2021-12-14T13:12:48.549Z zigbee-herdsman:deconz:frameParser response payload: 8,41,10,0,0,16,1
2021-12-14T13:12:48.551Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false,"reservedBits":0},"transactionSequenceNumber":41,"manufacturerCode":null,"commandIdentifier":10},"Payload":[{"attrId":0,"dataType":16,"attrData":1}],"Command":{"ID":10,"name":"report","parameters":[{"name":"attrId","type":33},{"name":"dataType","type":32},{"name":"attrData","type":1000}]}},"address":590,"endpoint":1,"linkquality":255,"groupID":null,"wasBroadcast":false,"destinationEndpoint":1}'
2021-12-14T13:12:48.554Z zigbee-herdsman:controller:endpoint DefaultResponse 0x5c0272fffecc1788/1 6(10, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})
2021-12-14T13:12:48.554Z zigbee-herdsman:deconz:adapter zclFrame.payload:
2021-12-14T13:12:48.555Z zigbee-herdsman:deconz:adapter { cmdId: 10, statusCode: 0 }
2021-12-14T13:12:48.555Z zigbee-herdsman:deconz:adapter no response expected
2021-12-14T13:12:48.555Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:48.559Z zigbee-herdsman:deconz:driver DATA_REQUEST - destAddr: 0x24e EP:1 SeqNr. 29 request id: 7
2021-12-14T13:12:48.561Z zigbee-herdsman:deconz:frameParser DATA_REQUEST RESPONSE - request id: 7 status: 0
2021-12-14T13:12:48.561Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:48.570Z zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101010
2021-12-14T13:12:48.570Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
2021-12-14T13:12:48.574Z zigbee-herdsman:deconz:driver query aps data indication
2021-12-14T13:12:48.575Z zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 30
2021-12-14T13:12:48.578Z zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 30 srcAddr: 0x474b destAddr: 0x0 profile id: 0x104 cluster id: 0xfc13 lqi: 255
2021-12-14T13:12:48.579Z zigbee-herdsman:deconz:frameParser response payload: 28,96,17,3,10,2,0,16,0
2021-12-14T13:12:48.581Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":true,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":3,"manufacturerCode":4448,"commandIdentifier":10},"Payload":[{"attrId":2,"dataType":16,"attrData":0}],"Command":{"ID":10,"name":"report","parameters":[{"name":"attrId","type":33},{"name":"dataType","type":32},{"name":"attrData","type":1000}]}},"address":18251,"endpoint":1,"linkquality":255,"groupID":null,"wasBroadcast":false,"destinationEndpoint":1}'
2021-12-14T13:12:48.583Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
Error: Cluster with name '64531' does not exist
    at Object.getCluster (/app/node_modules/zigbee-herdsman/src/zcl/utils.ts:66:19)
    at Endpoint.saveClusterAttributeKeyValue (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:242:35)
    at Controller.onZclOrRawData (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:644:26)
    at DeconzAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:135:70)
    at DeconzAdapter.emit (events.js:400:28)
    at DeconzAdapter.checkReceivedDataPayload (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:1134:22)
    at EventEmitter.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:71:78)
    at EventEmitter.emit (events.js:400:28)
    at parseReadReceivedDataResponse (/app/node_modules/zigbee-herdsman/src/adapter/deconz/driver/frameParser.ts:276:23)
    at parseFrame (/app/node_modules/zigbee-herdsman/src/adapter/deconz/driver/frameParser.ts:458:32)
```
</details>

## What did you expect to happen

Some of my Sengled lights cause this error to happen. I have not seems to always be RGB ones. I have had it happen with E12-N1E (RGB BR30), E1G-G8E (RGB strip) and E1F-N5E (RGB Candle). It does _not_ happen with the standard A12 RGB lights (model: E11-N1EA)

## How to reproduce it (minimal and precise)

Steps top repro are inconsistent. Some lights that are causing it some are as simple as turning on the light. Other lights (of the same model), never cause it. I have 2 E12-N1Es that are causing it consistency by just turning them on/off.

## Debug info
Zigbee2MQTT version: 1.22.1
Adapter hardware: Conbee II
Adapter firmware version: 0x26660700

**Comment by Koenkk** [comment]
Can you check if this has already been fixed in the latest dev?  (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by AngellusMortis** [comment]
The HA integration for edge is behind stable: 
![image](https://user-images.githubusercontent.com/490848/146036622-a5397ae9-9fd6-42dd-a70c-361b9dbd57c9.png)

**Comment by Koenkk** [comment]
It is not, it is rebuild after every push to the z2m dev branch:

![image](https://user-images.githubusercontent.com/2892853/146037178-17e2bac6-2816-4233-95cb-887fb6125939.png)

**Comment by AngellusMortis** [comment]
Oh cool. There was no clear indication in HA that it does that. Let me try.

**Comment by AngellusMortis** [comment]
I can confirm it happens on edge as well.

**Comment by Koenkk** [comment]
Can you check if it has been fixed?

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by AngellusMortis** [comment]
It looks like it.
