### ISSUE TITLE
[Problem]: zigbee2mqtt crashloop

### ISSUE THREAD

**Issue by jasonmadigan** [Koenkk/zigbee2mqtt#10343]
### What happened?

I'm setting zigbee2mqtt up again after a long absence with a Tasmotized Sonoff Zbridge.

I'm getting frequent (every minute or so) crashes, with the following error:

```
Error: Unrecognized nodeId:19653
    at Driver.networkIdToEUI64 (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:454:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at EZSPAdapter.processMessage (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:50:33)
[14:43:23] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.1 start
> node index.js
Assertion failed
Assertion failed
Zigbee2MQTT:warn  2021-12-24 14:43:31: Using experimental new availability feature
Error: Unrecognized nodeId:39402
    at Driver.networkIdToEUI64 (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:454:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at EZSPAdapter.processMessage (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:50:33)
[14:43:32] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.1 start
> node index.js
Assertion failed
Assertion failed
Zigbee2MQTT:warn  2021-12-24 14:43:40: Using experimental new availability feature
```S

### What did you expect to happen?

I expected Zigbee2MQTT to remain running

### How to reproduce it (minimal and precise)

Tasmotised Sonoff Zbridge. I have reset this to factory settings recently. The error almost looks like some remnants of an old config _somewhere_. I've removed `/config/zigbee2mqtt`, but no joy.

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

6.7.8.0 build 373

### Adapter

Tasmota Sonoff Zbridge (10.1.0.1)

### Debug log

See above

**Comment by Koenkk** [comment]
Please report this issue here: https://github.com/Koenkk/zigbee-herdsman/issues/319 

The EZSP integration is currently in a very experimental stage without any developers working on it, therefore all issues are gathered in https://github.com/Koenkk/zigbee-herdsman/issues/319
