### ISSUE TITLE
[Problem]: Innr SP234 missing Attributes

### ISSUE THREAD

**Issue by reefland** [Koenkk/zigbee2mqtt#10405]
### What happened?

Device Innr SP234 (https://www.zigbee2mqtt.io/devices/SP_234.html) pairs fine, responds to ON/OFF however none of the power monitoring attributes are reported (they show `null`).

### What did you expect to happen?

Expect to see power monitoring attributes populated. The device state only shows:
```
{
    "linkquality": 96,
    "state": "ON"
}
```

### How to reproduce it (minimal and precise)

pair device / view device state.

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

20210319

### Adapter

SMARTLIGHT Zigbee LAN Adapter CC2652P Model SLZB-05

### Debug log

Toggle OFF/ON log:
```
debug 2021-12-28 08:22:44: Received MQTT message on 'zigbee2mqtt/Living Room TV Stack/set' with data 'OFF'
debug 2021-12-28 08:22:45: Publishing 'set' 'state' to 'Living Room TV Stack'
info  2021-12-28 08:22:45: MQTT publish: topic 'zigbee2mqtt/Living Room TV Stack', payload '{"current":null,"energy":null,"linkquality":54,"power":null,"state":"OFF","voltage":null}'
debug 2021-12-28 08:22:59: Received Zigbee message from 'Living Room TV Stack', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":671180304,"imageType":787,"manufacturerCode":4454}' from endpoint 1 with groupID 0
debug 2021-12-28 08:22:59: Device 'Living Room TV Stack' requested OTA
debug 2021-12-28 08:23:07: Received MQTT message on 'zigbee2mqtt/Living Room TV Stack/set' with data 'ON'
debug 2021-12-28 08:23:07: Publishing 'set' 'state' to 'Living Room TV Stack'
info  2021-12-28 08:23:07: MQTT publish: topic 'zigbee2mqtt/Living Room TV Stack', payload '{"current":null,"energy":null,"linkquality":81,"power":null,"state":"ON","voltage":null}'
```

Pair device log:
```

debug 2021-12-28 08:30:46: Received MQTT message on 'zigbee2mqtt/bridge/request/permit_join' with data '{"device":null,"time":254,"transaction":"zgnoj-8","value":true}'
info  2021-12-28 08:30:46: Zigbee: allowing new devices to join.
info  2021-12-28 08:30:46: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"zgnoj-8"}'
info  2021-12-28 08:31:04: Device '0x84fd27fffe4ae14f' joined
info  2021-12-28 08:31:04: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x84fd27fffe4ae14f","ieee_address":"0x84fd27fffe4ae14f"},"type":"device_joined"}'
info  2021-12-28 08:31:04: Configuring '0x84fd27fffe4ae14f'
info  2021-12-28 08:31:04: MQTT publish: topic 'homeassistant/sensor/0x84fd27fffe4ae14f/power/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"configuration_url":"https://zigbee2mqtt.rich-durso.us/#/device/0x84fd27fffe4ae14f/info","identifiers":["zigbee2mqtt_0x84fd27fffe4ae14f"],"manufacturer":"Innr","model":"Smart plug (SP 234)","name":"0x84fd27fffe4ae14f","sw_version":"2.8"},"device_class":"power","enabled_by_default":true,"entity_category":"diagnostic","name":"0x84fd27fffe4ae14f power","state_class":"measurement","state_topic":"zigbee2mqtt/0x84fd27fffe4ae14f","unique_id":"0x84fd27fffe4ae14f_power_zigbee2mqtt","unit_of_measurement":"W","value_template":"{{ value_json.power }}"}'
info  2021-12-28 08:31:04: MQTT publish: topic 'homeassistant/sensor/0x84fd27fffe4ae14f/current/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"configuration_url":"https://zigbee2mqtt.rich-durso.us/#/device/0x84fd27fffe4ae14f/info","identifiers":["zigbee2mqtt_0x84fd27fffe4ae14f"],"manufacturer":"Innr","model":"Smart plug (SP 234)","name":"0x84fd27fffe4ae14f","sw_version":"2.8"},"device_class":"current","enabled_by_default":false,"entity_category":"diagnostic","name":"0x84fd27fffe4ae14f current","state_class":"measurement","state_topic":"zigbee2mqtt/0x84fd27fffe4ae14f","unique_id":"0x84fd27fffe4ae14f_current_zigbee2mqtt","unit_of_measurement":"A","value_template":"{{ value_json.current }}"}'
info  2021-12-28 08:31:04: MQTT publish: topic 'homeassistant/sensor/0x84fd27fffe4ae14f/voltage/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"configuration_url":"https://zigbee2mqtt.rich-durso.us/#/device/0x84fd27fffe4ae14f/info","identifiers":["zigbee2mqtt_0x84fd27fffe4ae14f"],"manufacturer":"Innr","model":"Smart plug (SP 234)","name":"0x84fd27fffe4ae14f","sw_version":"2.8"},"device_class":"voltage","enabled_by_default":false,"entity_category":"diagnostic","name":"0x84fd27fffe4ae14f voltage","state_class":"measurement","state_topic":"zigbee2mqtt/0x84fd27fffe4ae14f","unique_id":"0x84fd27fffe4ae14f_voltage_zigbee2mqtt","unit_of_measurement":"V","value_template":"{{ value_json.voltage }}"}'
info  2021-12-28 08:31:04: MQTT publish: topic 'homeassistant/switch/0x84fd27fffe4ae14f/switch/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/0x84fd27fffe4ae14f/set","device":{"configuration_url":"https://zigbee2mqtt.rich-durso.us/#/device/0x84fd27fffe4ae14f/info","identifiers":["zigbee2mqtt_0x84fd27fffe4ae14f"],"manufacturer":"Innr","model":"Smart plug (SP 234)","name":"0x84fd27fffe4ae14f","sw_version":"2.8"},"name":"0x84fd27fffe4ae14f","payload_off":"OFF","payload_on":"ON","state_topic":"zigbee2mqtt/0x84fd27fffe4ae14f","unique_id":"0x84fd27fffe4ae14f_switch_zigbee2mqtt","value_template":"{{ value_json.state }}"}'
info  2021-12-28 08:31:04: MQTT publish: topic 'homeassistant/sensor/0x84fd27fffe4ae14f/energy/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"configuration_url":"https://zigbee2mqtt.rich-durso.us/#/device/0x84fd27fffe4ae14f/info","identifiers":["zigbee2mqtt_0x84fd27fffe4ae14f"],"manufacturer":"Innr","model":"Smart plug (SP 234)","name":"0x84fd27fffe4ae14f","sw_version":"2.8"},"device_class":"energy","enabled_by_default":true,"name":"0x84fd27fffe4ae14f energy","state_class":"total_increasing","state_topic":"zigbee2mqtt/0x84fd27fffe4ae14f","unique_id":"0x84fd27fffe4ae14f_energy_zigbee2mqtt","unit_of_measurement":"kWh","value_template":"{{ value_json.energy }}"}'
info  2021-12-28 08:31:04: MQTT publish: topic 'homeassistant/sensor/0x84fd27fffe4ae14f/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"configuration_url":"https://zigbee2mqtt.rich-durso.us/#/device/0x84fd27fffe4ae14f/info","identifiers":["zigbee2mqtt_0x84fd27fffe4ae14f"],"manufacturer":"Innr","model":"Smart plug (SP 234)","name":"0x84fd27fffe4ae14f","sw_version":"2.8"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"0x84fd27fffe4ae14f linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x84fd27fffe4ae14f","unique_id":"0x84fd27fffe4ae14f_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
debug 2021-12-28 08:31:04: Received MQTT message on 'homeassistant/sensor/0x84fd27fffe4ae14f/power/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"configuration_url":"https://zigbee2mqtt.rich-durso.us/#/device/0x84fd27fffe4ae14f/info","identifiers":["zigbee2mqtt_0x84fd27fffe4ae14f"],"manufacturer":"Innr","model":"Smart plug (SP 234)","name":"0x84fd27fffe4ae14f","sw_version":"2.8"},"device_class":"power","enabled_by_default":true,"entity_category":"diagnostic","name":"0x84fd27fffe4ae14f power","state_class":"measurement","state_topic":"zigbee2mqtt/0x84fd27fffe4ae14f","unique_id":"0x84fd27fffe4ae14f_power_zigbee2mqtt","unit_of_measurement":"W","value_template":"{{ value_json.power }}"}'
debug 2021-12-28 08:31:04: Received MQTT message on 'homeassistant/sensor/0x84fd27fffe4ae14f/current/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"configuration_url":"https://zigbee2mqtt.rich-durso.us/#/device/0x84fd27fffe4ae14f/info","identifiers":["zigbee2mqtt_0x84fd27fffe4ae14f"],"manufacturer":"Innr","model":"Smart plug (SP 234)","name":"0x84fd27fffe4ae14f","sw_version":"2.8"},"device_class":"current","enabled_by_default":false,"entity_category":"diagnostic","name":"0x84fd27fffe4ae14f current","state_class":"measurement","state_topic":"zigbee2mqtt/0x84fd27fffe4ae14f","unique_id":"0x84fd27fffe4ae14f_current_zigbee2mqtt","unit_of_measurement":"A","value_template":"{{ value_json.current }}"}'
debug 2021-12-28 08:31:04: Received MQTT message on 'homeassistant/sensor/0x84fd27fffe4ae14f/voltage/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"configuration_url":"https://zigbee2mqtt.rich-durso.us/#/device/0x84fd27fffe4ae14f/info","identifiers":["zigbee2mqtt_0x84fd27fffe4ae14f"],"manufacturer":"Innr","model":"Smart plug (SP 234)","name":"0x84fd27fffe4ae14f","sw_version":"2.8"},"device_class":"voltage","enabled_by_default":false,"entity_category":"diagnostic","name":"0x84fd27fffe4ae14f voltage","state_class":"measurement","state_topic":"zigbee2mqtt/0x84fd27fffe4ae14f","unique_id":"0x84fd27fffe4ae14f_voltage_zigbee2mqtt","unit_of_measurement":"V","value_template":"{{ value_json.voltage }}"}'
debug 2021-12-28 08:31:04: Received MQTT message on 'homeassistant/switch/0x84fd27fffe4ae14f/switch/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"command_topic":"zigbee2mqtt/0x84fd27fffe4ae14f/set","device":{"configuration_url":"https://zigbee2mqtt.rich-durso.us/#/device/0x84fd27fffe4ae14f/info","identifiers":["zigbee2mqtt_0x84fd27fffe4ae14f"],"manufacturer":"Innr","model":"Smart plug (SP 234)","name":"0x84fd27fffe4ae14f","sw_version":"2.8"},"name":"0x84fd27fffe4ae14f","payload_off":"OFF","payload_on":"ON","state_topic":"zigbee2mqtt/0x84fd27fffe4ae14f","unique_id":"0x84fd27fffe4ae14f_switch_zigbee2mqtt","value_template":"{{ value_json.state }}"}'
debug 2021-12-28 08:31:04: Received MQTT message on 'homeassistant/sensor/0x84fd27fffe4ae14f/energy/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"configuration_url":"https://zigbee2mqtt.rich-durso.us/#/device/0x84fd27fffe4ae14f/info","identifiers":["zigbee2mqtt_0x84fd27fffe4ae14f"],"manufacturer":"Innr","model":"Smart plug (SP 234)","name":"0x84fd27fffe4ae14f","sw_version":"2.8"},"device_class":"energy","enabled_by_default":true,"name":"0x84fd27fffe4ae14f energy","state_class":"total_increasing","state_topic":"zigbee2mqtt/0x84fd27fffe4ae14f","unique_id":"0x84fd27fffe4ae14f_energy_zigbee2mqtt","unit_of_measurement":"kWh","value_template":"{{ value_json.energy }}"}'
debug 2021-12-28 08:31:04: Received MQTT message on 'homeassistant/sensor/0x84fd27fffe4ae14f/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"configuration_url":"https://zigbee2mqtt.rich-durso.us/#/device/0x84fd27fffe4ae14f/info","identifiers":["zigbee2mqtt_0x84fd27fffe4ae14f"],"manufacturer":"Innr","model":"Smart plug (SP 234)","name":"0x84fd27fffe4ae14f","sw_version":"2.8"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"0x84fd27fffe4ae14f linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x84fd27fffe4ae14f","unique_id":"0x84fd27fffe4ae14f_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
debug 2021-12-28 08:31:08: Device '0x84fd27fffe4ae14f' announced itself
info  2021-12-28 08:31:08: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x84fd27fffe4ae14f","ieee_address":"0x84fd27fffe4ae14f"},"type":"device_announce"}'
debug 2021-12-28 08:31:10: Retrieving state of '0x84fd27fffe4ae14f' after reconnect
error 2021-12-28 08:31:14: Failed to configure '0x84fd27fffe4ae14f', attempt 2 (Error: Bind 0x84fd27fffe4ae14f/1 genOnOff from '0x00124b0025792438/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7))
debug 2021-12-28 08:31:14: Received Zigbee message from '0x84fd27fffe4ae14f', type 'readResponse', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
info  2021-12-28 08:31:14: Configuring '0x84fd27fffe4ae14f'
info  2021-12-28 08:31:14: MQTT publish: topic 'zigbee2mqtt/0x84fd27fffe4ae14f', payload '{"current":null,"energy":null,"linkquality":96,"power":null,"state":"OFF","voltage":null}'
info  2021-12-28 08:31:15: Successfully configured '0x84fd27fffe4ae14f'
debug 2021-12-28 08:31:23: Received Zigbee message from '0x84fd27fffe4ae14f', type 'read', cluster 'genTime', data '["time"]' from endpoint 1 with groupID 0
debug 2021-12-28 08:31:25: Saving state to file /app/data/state.json
debug 2021-12-28 08:31:50: Received MQTT message on 'zigbee2mqtt/bridge/request/options' with data '{"options":{"advanced":{"log_level":"info"}},"transaction":"zgnoj-9"}'
info  2021-12-28 08:31:50: Succesfully changed options
```

**Comment by reefland** [comment]
Not sure what I did but after a few more tests with pairing, the attributes started to show. Seems only `energy` is not updated now:
```
{
    "current": 0.12,
    "linkquality": 72,
    "power": 8,
    "state": "ON",
    "voltage": 124,
    "energy": null
}
```
I have a handful more of these devices to play with, I'll see if I can reproduce my original issue or not.

**Comment by reefland** [comment]
I've paired 5 devices, not been able to reproduce my original issue.
