### ISSUE TITLE
[Problem]: Updated CC2652P firmware - now get No Network Route (205)

### ISSUE THREAD

**Issue by swcc1197** [Koenkk/zigbee2mqtt#10488]
### What happened?

I flashed the new firmware to my adapter, (CC2652P) and the verify showed that it was successful. After restarting z2m everything will load, however it will not allow me to change power status on my lights. 

### What did you expect to happen?

Lights to turn on/off

### How to reproduce it (minimal and precise)

Try to turn on lights

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20211217

### Adapter

Tube coordinator CR2652P

### Debug log

debug 2022-01-01 11:29:49: Received MQTT message on 'zigbee2mqtt/Wall Sconce/set' with data '{"state":"ON"}'
debug 2022-01-01 11:29:49: Publishing 'set' 'state' to 'Wall Sconce'
error 2022-01-01 11:30:11: Publish 'set' 'state' to 'Wall Sconce' failed: 'Error: Command 0x0017880102e729ea/11 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
debug 2022-01-01 11:30:11: Error: Command 0x0017880102e729ea/11 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))
    at ZStackAdapter.sendZclFrameToEndpointInternal (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:414:23)
    at Queue.executeNext (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
info  2022-01-01 11:30:11: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'Wall Sconce' failed: 'Error: Command 0x0017880102e729ea/11 genOnOff.on({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Data request failed with error: 'No network route' (205))'","meta":{"friendly_name":"Wall Sconce"},"type":"zigbee_publish_error"}'

**Comment by swcc1197** [comment]
Well... even though I had already restarted the coordinator and the service a few times... seemed one more worked after I posted this... so... closing.
