### ISSUE TITLE
[Problem]: SyntaxError: Invalid or unexpected token after upgrading to 1.22.2

### ISSUE THREAD

**Issue by dbotman** [Koenkk/zigbee2mqtt#10724]
### What happened?

```
> zigbee2mqtt@1.22.2 start /opt/zigbee2mqtt
> node index.js

/opt/zigbee2mqtt/node_modules/core-js/modules/es.array.iterator.js:9

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/zigbee2mqtt/node_modules/core-js/es/object/from-entries.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.22.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.22.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-11T18_36_11_934Z-debug.log
```

Output of 2022-01-11T18_36_11_934Z-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.15
3 info using node@v12.22.8
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zigbee2mqtt@1.22.2~prestart: zigbee2mqtt@1.22.2
6 info lifecycle zigbee2mqtt@1.22.2~start: zigbee2mqtt@1.22.2
7 verbose lifecycle zigbee2mqtt@1.22.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle zigbee2mqtt@1.22.2~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/zigbee2mqtt/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle zigbee2mqtt@1.22.2~start: CWD: /opt/zigbee2mqtt
10 silly lifecycle zigbee2mqtt@1.22.2~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle zigbee2mqtt@1.22.2~start: Returned: code: 1  signal: null
12 info lifecycle zigbee2mqtt@1.22.2~start: Failed to exec start script
13 verbose stack Error: zigbee2mqtt@1.22.2 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid zigbee2mqtt@1.22.2
15 verbose cwd /opt/zigbee2mqtt
16 verbose Linux 5.10.63-v7+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.22.8
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error zigbee2mqtt@1.22.2 start: `node index.js`
22 error Exit status 1
23 error Failed at the zigbee2mqtt@1.22.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

### What did you expect to happen?

Start zigbee2mqtt

### How to reproduce it (minimal and precise)

Upgrading from 1.22.1 to 1.22.2

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

>

### Adapter

2530

### Debug log

See above

**Comment by E-M1** [comment]
I have the exact same error after updating to latest version using Python Virtual Environment
