### ISSUE TITLE
Z2M stopping working issue connexion to zigbee-herdsman

### ISSUE THREAD

**Issue by seblang** [Koenkk/zigbee2mqtt#10731]
### What happened?

Z2m report issus with zigbee-herdsman (zigbee-herdsman (0.13.188))

### What did you expect to happen?

Was working yesterday evening, do not work this morning
a restart do not solve the problem

### How to reproduce it (minimal and precise)

do not know

### Zigbee2MQTT version

1.22.2

### Adapter firmware version

20211210

### Adapter

cc2531

### Debug log

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[08:47:04] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[08:47:05] INFO: MQTT available, fetching server detail ...
[08:47:05] INFO: MQTT server settings not configured, trying to auto-discovering ...
[08:47:06] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[08:47:06] INFO: MQTT credentials not configured, trying to auto-discovering ...
[08:47:06] INFO: Configuring'addons' mqtt user
[08:47:06] INFO: Previous config file found, checking backup
[08:47:06] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[08:47:06] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:47:07] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.2 start
> node index.js
Zigbee2MQTT:debug 2022-01-12 08:47:12: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2022-01-12 08:47:12: Logging to console and directory: '/config/zigbee2mqtt/log/2022-01-12.08-47-10' filename: log.txt
Zigbee2MQTT:debug 2022-01-12 08:47:12: Removing old log directory '/config/zigbee2mqtt/log/2022-01-12.08-33-22'
Zigbee2MQTT:info  2022-01-12 08:47:12: Starting Zigbee2MQTT version 1.22.2 (commit #unknown)
Zigbee2MQTT:info  2022-01-12 08:47:12: Starting zigbee-herdsman (0.13.188)
Zigbee2MQTT:debug 2022-01-12 08:47:12: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyACM1"}}'
Zigbee2MQTT:error 2022-01-12 08:47:54: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-01-12 08:47:54: Failed to start zigbee
Zigbee2MQTT:error 2022-01-12 08:47:54: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-01-12 08:47:54: Exiting...
Zigbee2MQTT:error 2022-01-12 08:47:54: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:97:5)`

**Comment by Koenkk** [comment]
Probably your cc2531 crashed, reflashing should fix it.
