### ISSUE TITLE
z2m crashes during OTA update check

### ISSUE THREAD

**Issue by wyager** [Koenkk/zigbee2mqtt#11138]
### What happened?

Tried to check all devices for OTA updates. z2m died

### Zigbee2MQTT version

1.22.2 commit: 1a0a9a6e

### Adapter firmware version

20211217

### Adapter

Tube's PoE adapter

### Debug log

```
Zigbee2MQTT:debug 2022-01-31 01:23:43: Error: Device didn't respond to OTA request
    at requestOTA (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/lib/ota/common.js:196:15)
    at Object.isUpdateAvailable (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/lib/ota/common.js:251:25)
    at OTAUpdate.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/otaUpdate.ts:164:39)
Zigbee2MQTT:info  2022-01-31 01:23:43: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"
id":"0x2c1165fffe03aadd"},"error":"Failed to check if update available for '0x2c1165fffe03aadd' (Device didn't respond to OTA request
)","status":"error","transaction":"i4754-12"}'
Zigbee2MQTT:error 2022-01-31 01:23:43: Failed to check if update available for '0x2c1165fffe03aadd' (Device didn't respond to OTA req
uest)
Zigbee2MQTT:debug 2022-01-31 01:23:43: Error: Device didn't respond to OTA request
    at requestOTA (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/lib/ota/common.js:196:15)
    at Object.isUpdateAvailable (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/lib/ota/common.js:251:25)
    at OTAUpdate.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/otaUpdate.ts:164:39)
Error: Timeout - 47895 - 1 - null - 25 - 1 after 30000ms
    at Timeout._onTimeout (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.22.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.22.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-31T01_23_43_724Z-debug.log
 1: 0x17ae2e0 node::Abort() [/usr/local/bin/node]
 2: 0x1778b70 node::PlatformInit() [/usr/local/bin/node]
 3: 0x1777b35 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags) [/usr/local/bin/node]
Abort trap (core dumped)
 1: 0x17ae2e0 node::Abort() [/usr/local/bin/node]
 2: 0x1778b70 node::PlatformInit() [/usr/local/bin/node]
 3: 0x1777b35 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags) [/usr/local/bin/node]
Abort trap (core dumped)
 1: 0x17ae2e0 node::Abort() [/usr/local/bin/node]
 2: 0x1778b70 node::PlatformInit() [/usr/local/bin/node]
 3: 0x1777b35 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags) [/usr/local/bin/node]
```

**Comment by satter** [comment]
I am running into this issue with Z2M 1.24
It is crashing on upgrade attempt:
```
Mar 20 20:19:08 homie1 npm[51754]: Zigbee2MQTT:debug 2022-03-20 20:19:08: Received MQTT message on 'zigbee2mqtt/bridge/request/device/ota_update/update' with data '{"id":"aqara_tvoc1","transaction":"1790w-3"}'
Mar 20 20:19:08 homie1 npm[51754]: Zigbee2MQTT:info  2022-03-20 20:19:08: Updating 'aqara_tvoc1' to latest firmware
Mar 20 20:19:12 homie1 npm[51754]: Zigbee2MQTT:debug 2022-03-20 20:19:12: Saving state to file /opt/zigbee2mqtt/data/state.json
Mar 20 20:19:41 homie1 npm[51754]: Zigbee2MQTT:debug 2022-03-20 20:19:41: Received Zigbee message from 'aqara_tvoc1', type 'attributeReport', cluster 'genAnalogInput', data '{"presentValue":44}' from endpoint 1 with groupID 0
Mar 20 20:19:41 homie1 npm[51754]: Zigbee2MQTT:info  2022-03-20 20:19:41: MQTT publish: topic 'zigbee2mqtt/aqara_tvoc1', payload '{"battery":100,"humidity":33.84,"last_seen":"2022-03-20T20:19:41+00:00","linkquality":127,"temperature":22.95,"update":{"state":"available"},"voc":44,"voltage":3100}'
Mar 20 20:19:51 homie1 npm[51754]: Zigbee2MQTT:debug 2022-03-20 20:19:51: Updating to latest '0x54ef441000106dca' (lumi.airmonitor.acn01)
Mar 20 20:19:51 homie1 npm[51754]: Zigbee2MQTT:debug 2022-03-20 20:19:51: Using endpoint '1'
Mar 20 20:20:10 homie1 npm[51754]: Zigbee2MQTT:debug 2022-03-20 20:20:10: Received Zigbee message from 'aqara_tvoc1', type 'attributeReport', cluster 'genAnalogInput', data '{"presentValue":79}' from endpoint 1 with groupID 0
Mar 20 20:20:10 homie1 npm[51754]: Zigbee2MQTT:info  2022-03-20 20:20:10: MQTT publish: topic 'zigbee2mqtt/aqara_tvoc1', payload '{"battery":100,"humidity":33.84,"last_seen":"2022-03-20T20:20:10+00:00","linkquality":134,"temperature":22.95,"update":{"state":"available"},"voc":79,"voltage":3100}'
Mar 20 20:20:21 homie1 npm[51754]: Error: Timeout - 59887 - 1 - null - 25 - 1 after 30000ms
Mar 20 20:20:21 homie1 npm[51754]:     at Timeout._onTimeout (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
Mar 20 20:20:21 homie1 npm[51754]:     at listOnTimeout (node:internal/timers:559:17)
Mar 20 20:20:21 homie1 npm[51754]:     at processTimers (node:internal/timers:502:7)
Mar 20 20:20:21 homie1 systemd[1]: zigbee2mqtt.service: Main process exited, code=exited, status=1/FAILURE
Mar 20 20:20:21 homie1 systemd[1]: zigbee2mqtt.service: Failed with result 'exit-code'.
Mar 20 20:20:21 homie1 systemd[1]: zigbee2mqtt.service: Scheduled restart job, restart counter is at 2.
Mar 20 20:20:21 homie1 systemd[1]: Stopped zigbee2mqtt.
Mar 20 20:20:21 homie1 systemd[1]: Started zigbee2mqtt.
Mar 20 20:20:21 homie1 npm[70931]: > zigbee2mqtt@1.24.0 start
Mar 20 20:20:21 homie1 npm[70931]: > node index.js
```

It looks  similar to #10666
