### ISSUE TITLE
old problem with Müller Licht Smart Socket 404017

### ISSUE THREAD

**Issue by strandbein** [Koenkk/zigbee2mqtt#11215]
### What happened?

Hello,
also in version 1.23.0 there is no improvement for this problem: 

_Originally posted by @strandbein in https://github.com/Koenkk/zigbee2mqtt/issues/9152#issuecomment-1029404175_

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

0x26720700

### Adapter

ConBee2

### Debug log

CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2022-02-03 21:47:14: Failed to configure 'Serverschrank Plug', attempt 1 (TypeError: Cannot read property 'bind' of undefined
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:24)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/müller_licht.js:33:29)
    at Configure.configure (/app/lib/extension/configure.ts:115:37)
    at Configure.start (/app/lib/extension/configure.ts:68:24)
    at Controller.callExtensions (/app/lib/controller.ts:315:17)
    at Controller.start (/app/lib/controller.ts:152:9)
    at start (/app/index.js:101:5))
Zigbee2MQTT:error 2022-02-03 21:51:48: Failed to configure 'Serverschrank Plug', attempt 2 (TypeError: Cannot read property 'bind' of undefined
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:24)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/müller_licht.js:33:29)
    at Configure.configure (/app/lib/extension/configure.ts:115:37)
    at EventEmitter.<anonymous> (/app/lib/extension/configure.ts:80:62)
    at EventEmitter.emit (events.js:412:35)
    at EventBus.emitLastSeenChanged (/app/lib/eventBus.ts:45:22)
    at Controller.<anonymous> (/app/lib/zigbee.ts:66:27)
    at Controller.emit (events.js:400:28)
    at Controller.selfAndDeviceEmit (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:481:14)
    at Controller.onZclOrRawData (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:692:18))
Zigbee2MQTT:error 2022-02-03 21:56:47: Failed to configure 'Serverschrank Plug', attempt 3 (TypeError: Cannot read property 'bind' of undefined
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:24)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/müller_licht.js:33:29)
    at Configure.configure (/app/lib/extension/configure.ts:115:37)
    at EventEmitter.<anonymous> (/app/lib/extension/configure.ts:80:62)
    at EventEmitter.emit (events.js:412:35)
    at EventBus.emitLastSeenChanged (/app/lib/eventBus.ts:45:22)
    at Controller.<anonymous> (/app/lib/zigbee.ts:66:27)
    at Controller.emit (events.js:400:28)
    at Controller.selfAndDeviceEmit (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:481:14)
    at Controller.onZclOrRawData (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:692:18))

**Comment by Koenkk** [comment]
Continuing in https://github.com/Koenkk/zigbee2mqtt/issues/9152
