### ISSUE TITLE
Issue with Sonoff USB Zigbee dongle

### ISSUE THREAD

**Issue by guldnerthomas** [Koenkk/zigbee2mqtt#11222]
### What happened?

Hello,

I am trying to migrate from a cc2531 coordinator to the Sonoff USB Zigbee 3.0 (cc2652) but I encounter a problem when I connect the coordinator to my server. I correctly flashed the new firmware keeping the IEEE address of the old coordinator and I get this error when starting Z2M:
Error: Error while opening serialport 'Error: Error: Inappropriate ioctl for device setting custom baud rate of 115200'

Is the flow control button important? I tried in both positions, it does not change anything.
I tried to indicate 115200 in the advanced parameters of the yaml file, it does not change anything.
I also tried to flash it from 2 different machines, with the 3 tools indicated in the documentation.
I'm using an LXC container which hasn't been a problem so far.

Do you have a solution ?

Thanks in advance.

### Zigbee2MQTT version

1.23.0 commit: 6ea61bae

### Adapter firmware version

CC1352P2_CC2652P_launchpad_coordinator_20211217

### Adapter

Sonoff USB Zigbee 3.0

### Debug log

root@Zigbee2MQTT:~# journalctl -u zigbee2mqtt.service -f
-- Journal begins at Tue 2021-11-23 15:40:30 UTC. --
Feb 04 10:29:38 Zigbee2MQTT systemd[1]: zigbee2mqtt.service: Consumed 2.533s CPU time.
Feb 04 10:29:38 Zigbee2MQTT systemd[1]: Started zigbee2mqtt.
Feb 04 10:29:38 Zigbee2MQTT npm[1942]: > zigbee2mqtt@1.23.0 start /opt/zigbee2mqtt
Feb 04 10:29:38 Zigbee2MQTT npm[1942]: > node index.js
Feb 04 10:29:40 Zigbee2MQTT npm[1954]: Zigbee2MQTT:debug 2022-02-04 10:29:40: Loaded state from file /opt/zigbee2mqtt/data/state.json
Feb 04 10:29:40 Zigbee2MQTT npm[1954]: Zigbee2MQTT:info  2022-02-04 10:29:40: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2022-02-04.10-29-39' filename: log.txt
Feb 04 10:29:40 Zigbee2MQTT npm[1954]: Zigbee2MQTT:debug 2022-02-04 10:29:40: Removing old log directory '/opt/zigbee2mqtt/data/log/2022-02-04.10-29-11'
Feb 04 10:29:40 Zigbee2MQTT npm[1954]: Zigbee2MQTT:info  2022-02-04 10:29:40: Starting Zigbee2MQTT version 1.23.0 (commit #6ea61bae)
Feb 04 10:29:40 Zigbee2MQTT npm[1954]: Zigbee2MQTT:info  2022-02-04 10:29:40: Starting zigbee-herdsman (0.14.10)
Feb 04 10:29:40 Zigbee2MQTT npm[1954]: Zigbee2MQTT:debug 2022-02-04 10:29:40: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","databasePath":"/opt/zigbee2mqtt/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/zigbee"}}'
Feb 04 10:29:41 Zigbee2MQTT npm[1954]: Zigbee2MQTT:error 2022-02-04 10:29:41: Error while starting zigbee-herdsman
Feb 04 10:29:41 Zigbee2MQTT npm[1954]: Zigbee2MQTT:error 2022-02-04 10:29:41: Failed to start zigbee
Feb 04 10:29:41 Zigbee2MQTT npm[1954]: Zigbee2MQTT:error 2022-02-04 10:29:41: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Feb 04 10:29:41 Zigbee2MQTT npm[1954]: Zigbee2MQTT:error 2022-02-04 10:29:41: Exiting...
Feb 04 10:29:41 Zigbee2MQTT npm[1954]: Zigbee2MQTT:error 2022-02-04 10:29:41: Error: Error while opening serialport 'Error: Error: Inappropriate ioctl for device setting custom baud rate of 115200'
Feb 04 10:29:41 Zigbee2MQTT npm[1954]:     at SerialPort.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
Feb 04 10:29:41 Zigbee2MQTT npm[1954]:     at SerialPort._error (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
Feb 04 10:29:41 Zigbee2MQTT npm[1954]:     at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
Feb 04 10:29:41 Zigbee2MQTT npm[1942]: npm ERR! code ELIFECYCLE
Feb 04 10:29:41 Zigbee2MQTT npm[1942]: npm ERR! errno 1
Feb 04 10:29:41 Zigbee2MQTT npm[1942]: npm ERR! zigbee2mqtt@1.23.0 start: `node index.js`
Feb 04 10:29:41 Zigbee2MQTT npm[1942]: npm ERR! Exit status 1
Feb 04 10:29:41 Zigbee2MQTT npm[1942]: npm ERR!
Feb 04 10:29:41 Zigbee2MQTT npm[1942]: npm ERR! Failed at the zigbee2mqtt@1.23.0 start script.
Feb 04 10:29:41 Zigbee2MQTT npm[1942]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Feb 04 10:29:41 Zigbee2MQTT npm[1942]: npm ERR! A complete log of this run can be found in:
Feb 04 10:29:41 Zigbee2MQTT npm[1942]: npm ERR!     /root/.npm/_logs/2022-02-04T10_29_41_078Z-debug.log
Feb 04 10:29:41 Zigbee2MQTT systemd[1]: zigbee2mqtt.service: Main process exited, code=exited, status=1/FAILURE
Feb 04 10:29:41 Zigbee2MQTT systemd[1]: zigbee2mqtt.service: Failed with result 'exit-code'.
Feb 04 10:29:41 Zigbee2MQTT systemd[1]: zigbee2mqtt.service: Consumed 2.567s CPU time.
Feb 04 10:29:41 Zigbee2MQTT systemd[1]: zigbee2mqtt.service: Scheduled restart job, restart counter is at 48.

**Comment by guldnerthomas** [comment]
Hi 

I have news :
The dongle works correctly on a VM
So I suspect that something is not working properly between the LXC containers and the dongle.
