### ISSUE TITLE
Support new device breaks off

### ISSUE THREAD

**Issue by lukima61** [Koenkk/zigbee2mqtt#11253]
### Link

https://storage.googleapis.com/wzukusers/user-22742145/documents/78ebecf608bb40bc9d42e1a7011f4700/Nue%20ZigBee%20Blind%20Switch%20Device%20Handler.doc
https://3asmarthome.com

### Database entry

{"id":21,"type":"EndDevice","ieeeAddr":"0x04cf8cdf3c7d256f","nwkAddr":43730,"manufId":4718,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.sen_ill.mgl01","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":262,"inClusterList":[0,1024,3,1],"outClusterList":[3],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.sen_ill.mgl01","manufacturerName":"LUMI","powerSource":3,"zclVersion":3,"appVersion":21,"stackVersion":2,"hwVersion":1,"dateCode":"20191118","swBuildId":"2019\u0000www."}},"genPowerCfg":{"attributes":{"batteryVoltage":31}},"msIlluminanceMeasurement":{"attributes":{"measuredValue":0}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b001f320b70","endpointID":1},{"cluster":1024,"type":"endpoint","deviceIeeeAddress":"0x00124b001f320b70","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":21,"stackVersion":2,"hwVersion":1,"dateCode":"20191118","swBuildId":"2019\u0000www.","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1644101788603,"defaultSendRequestWhen":"immediate"}

### Comments

I have tried to integrate the shutter switch according to the instructions "Support new devices". After creating the JS file and updating the cofiguration.yaml with "external_converters: JS file", I restarted. Unfortunately, the restart of the container fails, because it aborts directly.

===== Logfile after restart abort =====
debug 2022-02-05 22:48:33: Loaded state from file /app/data/state.json
info  2022-02-05 22:48:33: Logging to console and directory: '/app/data/log/2022-02-05.22-48-30' filename: log.txt
debug 2022-02-05 22:48:33: Removing old log directory '/app/data/log/2022-02-05.21-58-21'
info  2022-02-05 22:48:33: Starting Zigbee2MQTT version 1.23.0 (commit #6ea61ba)
info  2022-02-05 22:48:33: Starting zigbee-herdsman (0.14.10)
debug 2022-02-05 22:48:33: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"tcp://192.168.0.10:1775","rtscts":false}}'
error 2022-02-05 22:48:53: Error while starting zigbee-herdsman
error 2022-02-05 22:48:53: Failed to start zigbee
error 2022-02-05 22:48:53: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2022-02-05 22:48:53: Exiting...
error 2022-02-05 22:48:53: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:101:5)

===== /app/node_modules/zigbee-herdsman-converters/devices/3AZB-4C-DE.js =====
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['LXN-2S27LX1.0'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: '3AZB-4C-DE', // Vendor model number, look on the device for a model number
    vendor: '3A Smart Home GmbH', // Vendor of the device (only used for documentation and startup logging)
    description: '3A Zigbee 3.0 Smart Blind Switch', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    fromZigbee: [], // We will add this later
    toZigbee: [], // Should be empty, unless device can be controlled (e.g. lights, switches).
    exposes: [], // Defines what this device exposes, used for e.g. Home Assistant discovery and in the frontend
};

module.exports = definition;

===== configuration.yaml =====
external_converters:
  - 3AZB-4C-DE.js

===== Logfile without external_converters: =====
debug 2022-02-06 00:50:41: Received Zigbee message from 'ROL1', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0
debug 2022-02-06 00:50:41: Skipping message, definition is undefined and still interviewing
debug 2022-02-06 00:50:42: Received Zigbee message from 'ROL1', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 2 with groupID 0
debug 2022-02-06 00:50:42: Skipping message, definition is undefined and still interviewing

**Comment by lukima61** [comment]
@Chaaaaaaaaarlie , no I have not managed to include the shutter switch yet. I have put it on the shelf for now and will tackle it again in the long winter evenings ;-)
