### ISSUE TITLE
Legrand 067774 right switch not working

### ISSUE THREAD

**Issue by adrienvsj** [Koenkk/zigbee2mqtt#11269]
### What happened?

Hi,

I'm using a ConBee 2 and the latest-dev Docker image on the latest Debian for host OS.
For my ConBee 2 I try with the default firmware deCONZ_ConBeeII_0x26660700.bin.GCF and the last one deCONZ_ConBeeII_0x26720700.bin.GCF

I've successfully adopted & operated a single switch Legrand 067773 but both my Legrand 067774 have inoperative right switches (although they are correctly adopted). (Yes I know, I have almost the same problem as https://github.com/Koenkk/zigbee2mqtt/issues/7020)

Any switch provides the expected lines in log :
```
Zigbee2MQTT:info  2022-02-07 00:23:37: Configuring 'Interrupteur double salle de bain'
Zigbee2MQTT:info  2022-02-07 00:23:37: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Interrupteur double salle de bain","ieee_address":"0x0004740000b924fb"},"type":"device_announce"}'
Zigbee2MQTT:info  2022-02-07 00:23:38: MQTT publish: topic 'zigbee2mqtt/Interrupteur double salle de bain', payload '{"action":null,"battery":100,"linkquality":255,"voltage":3100}'
Zigbee2MQTT:info  2022-02-07 00:23:38: MQTT publish: topic 'zigbee2mqtt/Interrupteur double salle de bain', payload '{"action":null,"battery":100,"linkquality":255,"voltage":3100}'
Zigbee2MQTT:info  2022-02-07 00:23:38: MQTT publish: topic 'zigbee2mqtt/Interrupteur double salle de bain', payload '{"action":null,"battery":100,"linkquality":255,"voltage":3100}'
Zigbee2MQTT:info  2022-02-07 00:23:38: MQTT publish: topic 'zigbee2mqtt/Interrupteur double salle de bain', payload '{"action":null,"battery":100,"linkquality":255,"voltage":3100}'
Zigbee2MQTT:info  2022-02-07 00:23:39: MQTT publish: topic 'zigbee2mqtt/Interrupteur double salle de bain', payload '{"action":null,"battery":100,"linkquality":255,"voltage":3100}'
Zigbee2MQTT:info  2022-02-07 00:23:39: MQTT publish: topic 'zigbee2mqtt/Interrupteur double salle de bain', payload '{"action":null,"battery":100,"linkquality":255,"voltage":3100}'
Zigbee2MQTT:error 2022-02-07 00:23:39: Failed to configure 'Interrupteur double salle de bain', attempt 3 (Error: Bind 0x0004740000b924fb/2 genPowerCfg from '0x00212effff07347f/1' failed (Error: status: 130)
    at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:755:19)
    at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:522:13)
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:9)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/legrand.js:149:13)
    at Configure.configure (/app/lib/extension/configure.ts:115:13))
```

In HomeAssistant, I only get the event "on_left"

Here my configuration : 
```
homeassistant: true
frontend:
  port: 8080
  host: 0.0.0.0
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://XXXX
  user: XXXXXXX
  password: XXXXXXXXX
serial:
  port: /dev/ttyACM0
advanced:
  legacy_api: false
  channel: 11
  homeassistant_legacy_triggers: true
devices:
  '0x00158d00045a77e2':
    friendly_name: Bouton lit Adrien
  '0x00158d00067fe78f':
    friendly_name: Bouton lit Coraline
  '0x5c0272fffe285777':
    friendly_name: Prise tablette salon
  '0x60a423fffe52dc36':
    friendly_name: Store bureau
    invert_cover: true
  '0x60a423fffe460021':
    friendly_name: Store chambre
    invert_cover: true
  '0x60a423fffe651236':
    friendly_name: Interrupteur salle de bains
  '0x847127fffef7e1d8':
    friendly_name: Interrupteur toilette
  '0x60a423fffe532b15':
    friendly_name: Store cuisine
    invert_cover: true
  '0x60a423fffe5329e3':
    friendly_name: Store salon gauche
    invert_cover: true
  '0x60a423fffe52dc77':
    friendly_name: Store salon droit
    invert_cover: true
  '0x00158d00042209c9':
    friendly_name: Capteur mouvement couloir / entrée
  '0x0017880106345474':
    friendly_name: Télécommande HUE
  '0x00158d00041fc316':
    friendly_name: Capteur mouvement couloir / salon
  '0x04cf8cdf3c78ae49':
    friendly_name: Capteur luminosité couloir
  '0x00158d00045065aa':
    friendly_name: Capteur température balcon
  '0x00158d00040863ce':
    friendly_name: Capteur température salle de bains
  '0x60a423fffe07cbf6':
    friendly_name: Prise imprimante 3D Prusa
  '0x60a423fffe07eaa6':
    friendly_name: Prise imprimante 3D Alfawise
  '0x842e14fffe579c4d':
    friendly_name: Réglette cuisine
  '0x60a423fffe0e0c9e':
    friendly_name: Guirlande bureau
  '0x00158d0004231f2f':
    friendly_name: Capteur ouverture porte entrée
  '0x00158d00067fe7dd':
    friendly_name: Bouton lumière Prusa i3 MK3S Lumière
  '0x00158d00044f7ec4':
    friendly_name: Capteur température frigo
  '0x00158d0004605330':
    friendly_name: Capteur température cuisine
  '0x0004740000c2c5d2':
    friendly_name: Interrupteur chambre
    legacy: false
  '0x0004740000c402b9':
    friendly_name: Commande départ / arrivée
  '0x0004740000c2c5aa':
    friendly_name: Interrupteur bureau
    legacy: false
  '0x0004740000c2c5d7':
    friendly_name: Interrupteur couloir / salon
    legacy: false
  '0x0004740000c2c5d6':
    friendly_name: Interrupteur couloir / entrée
    legacy: false
  '0x000474000011a32c':
    friendly_name: Interrupteur plafonnier salon / couloir
  '0x000474000011a2e1':
    friendly_name: Interrupteur plafonnier cuisine
  '0x0004740000b924f5':
    friendly_name: Interrupteur double cuisine
  '0x0004740000b924fb':
    friendly_name: Interrupteur double salle de bain
```

For me this error is related to another issue I just created: https://github.com/Koenkk/zigbee2mqtt/issues/11270

Thank you for your help

### What did you expect to happen?

The right and left button should send their commands normally.

### How to reproduce it (minimal and precise)

Configure an Legrand 067774 and press the buttons on the switch.

### Zigbee2MQTT version

 1.23.0-dev commit: 5dd8873

### Adapter firmware version

0x26720700

### Adapter

ConBee2

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/8011434/log.txt)

**Comment by lchabert** [comment]
Hi,

I have the same issue on this device, same errors as written before.

I have also "downgrader" the firmware of the device using one provided by Zigbee-OTA repo, but same result.

We have also errors when we try to enable dimmer or set_if_on functions as well.

```
Zigbee2MQTT:debug 2023-06-25 19:37:05: Received MQTT message on 'zigbee2mqtt/0x0004740000796d5c/set/led_if_on' with data 'OFF'
Zigbee2MQTT:debug 2023-06-25 19:37:05: Publishing 'set' 'led_if_on' to '0x0004740000796d5c'
Zigbee2MQTT:error 2023-06-25 19:37:05: Publish 'set' 'led_if_on' to '0x0004740000796d5c' failed: 'Error: Write 0x0004740000796d5c/1 manuSpecificLegrandDevices({"2":{"value":false,"type":16}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4129,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Zigbee2MQTT:debug 2023-06-25 19:37:05: Error: Write 0x0004740000796d5c/1 manuSpecificLegrandDevices({"2":{"value":false,"type":16}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4129,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:421:28)
    at Endpoint.write (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:490:22)
    at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.js:3936:13)
    at Publish.onMQTTMessage (/app/lib/extension/publish.ts:247:36)
```

Do you have any hint to continue debugging. With the device at home, i can help you with.
