### ISSUE TITLE
INNR OPL 130 C set color_temp_startup not supported

### ISSUE THREAD

**Issue by thecobra666** [Koenkk/zigbee2mqtt#11321]
### What happened?

In the gui there is an option to set the default startup color, but it errors out saying it's not supported. 

### What did you expect to happen?

Set the default startup color.

### Zigbee2MQTT version

1.23.0

### Adapter firmware version

0x26720700

### Adapter

ConBee2/RaspBee2

### Debug log

```
Error Publish 'set' 'color_temp_startup' to 'Lamp tuin 11' failed: 'Error: Write 0x00158d0000fa748d/1 lightingColorCtrl({"startUpColorTemperature":454}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Debug Error: Write 0x00158d0000fa748d/1 lightingColorCtrl({"startUpColorTemperature":454}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28) at Endpoint.write (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:397:22) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:958:13) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:246:36)
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'color_temp_startup' to 'Lamp tuin 11' failed: 'Error: Write 0x00158d0000fa748d/1 lightingColorCtrl({\"startUpColorTemperature\":454}, {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'","meta":{"friendly_name":"Lamp tuin 11"},"type":"zigbee_publish_error"}'
Debug Received Zigbee message from 'Lamp tuin 11', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":671097186,"imageType":1798,"manufacturerCode":4454}' from endpoint 1 with groupID null
Info MQTT publish: topic 'zigbee2mqtt/Lamp tuin 11', payload '{"brightness":254,"color":{"h":34,"hue":34,"s":75,"saturation":75,"x":0.4362,"y":0.4038},"color_mode":"color_temp","color_temp":332,"last_seen":"2022-02-09T08:57:08.725Z","linkquality":255,"state":"OFF"}'
```

**Comment by thecobra666** [comment]
Issue is stil here.
