### ISSUE TITLE
Lidl Silvercrest hacked gateway fails to connect

### ISSUE THREAD

**Issue by 21stce** [Koenkk/zigbee2mqtt#11698]
### What happened?

It doesn't connect, but there is a serial gateway running on the device. 

I flashed the chip (ezsp) too a few weeks ago using the most recently available firmware at the time. 

```
Mar 03 21:39:29 computer zigbee2mqtt[20718]: Zigbee2MQTT:info  2022-03-03 21:39:29: Logging to console and directory: '/var/lib/zigbee2mqtt/log/2022-03-03.21-39-29' filename: log.txt
Mar 03 21:39:29 computer zigbee2mqtt[20718]: Zigbee2MQTT:info  2022-03-03 21:39:29: Starting Zigbee2MQTT version 1.16.2 (commit #unknown)
Mar 03 21:39:29 computer zigbee2mqtt[20718]: Zigbee2MQTT:info  2022-03-03 21:39:29: Starting zigbee-herdsman (0.13.37)
Mar 03 21:39:49 computer zigbee2mqtt[20718]: Zigbee2MQTT:error 2022-03-03 21:39:49: Error while starting zigbee-herdsman
Mar 03 21:39:49 computer zigbee2mqtt[20718]: Zigbee2MQTT:error 2022-03-03 21:39:49: Failed to start zigbee
Mar 03 21:39:49 computer zigbee2mqtt[20718]: Zigbee2MQTT:error 2022-03-03 21:39:49: Exiting...
Mar 03 21:39:49 computer zigbee2mqtt[20718]: Zigbee2MQTT:error 2022-03-03 21:39:49: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
Mar 03 21:39:49 computer zigbee2mqtt[20718]:     at ZStackAdapter.<anonymous> (/nix/store/z6r89w00v9q2p14c5jz3qx5m5v1y36wj-node_zigbee2mqtt-1.16.2/lib/node_modules/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
Mar 03 21:39:49 computer zigbee2mqtt[20718]:     at Generator.throw (<anonymous>)
Mar 03 21:39:49 computer zigbee2mqtt[20718]:     at rejected (/nix/store/z6r89w00v9q2p14c5jz3qx5m5v1y36wj-node_zigbee2mqtt-1.16.2/lib/node_modules/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
Mar 03 21:39:49 computer systemd[1]: zigbee2mqtt.service: Main process exited, code=exited, status=1/FAILURE
Mar 03 21:39:49 computer systemd[1]: zigbee2mqtt.service: Failed with result 'exit-code'.
Mar 03 21:39:49 computer systemd[1]: zigbee2mqtt.service: Consumed 1.076s CPU time, received 268B IP traffic, sent 388B IP traffic.
Mar 03 21:39:49 computer systemd[1]: zigbee2mqtt.service: Scheduled restart job, restart counter is at 16.
```

### What did you expect to happen?

I expected that zigbee2mqtt would just start succesfully and pick up Zigbee traffic, just like HomeAssistant is able to. Please note that I have disabled Home Assistant in order to try zigbee2mqtt.

### How to reproduce it (minimal and precise)

Using NixOS 21.11.git.ed02c2ba038 (Porcupine) on the machine running zigbee2mqtt.

configuration.yaml:

```
devices: devices.yaml
frontend:
  host: 127.0.0.1
  port: 8082
homeassistant: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
permit_join: true
serial:
  port: tcp://192.168.188.113:8888
```

### Zigbee2MQTT version

1.16.2

### Adapter firmware version

Frontend is not available, because it restarts before it reaches that point

### Adapter

I am using the gateway as discussed in this topic:  https://community.home-assistant.io/t/hacking-the-silvercrest-lidl-tuya-smart-home-gateway/270934/82

### Debug log

I don't think this is relevant in this case. Perhaps it's just something as "Your version is too old".

**Comment by 21stce** [comment]
As I suspected, it was just a version issue. 1.23.0 works. 

I will test some additional things and then I will close this one.

**Comment by 21stce** [comment]
The only reason for setting up all of this was to get https://aliexpress.com/item/1005001895935932.html to work, but it doesn't. Some lights do work. 

If someone can *please* explain how to get those to work that would be great (and save a lot of natural gas (!))!

**Comment by 21stce** [comment]
I am already aware of this page: https://www.zigbee2mqtt.io/devices/TV02-Zigbee.html, but the pairing never happens. I don't have a Tuya gateway.

**Comment by 21stce** [comment]
The issue was not installing the unit first. You can't pair without physical installation (which is a design flaw). zigbee2mqtt can't do anything here to help, other than document this behavior.
