### ISSUE TITLE
TS0601_smoke battery low null

### ISSUE THREAD

**Issue by tammeryousef1006** [Koenkk/zigbee2mqtt#11702]
### What happened?

the devices shows only question mark at battery all the time ( ? )
i tried to make battery report percentage but its not working to show the battery is ok

### What did you expect to happen?

i expect to not see question mark and shows the battery is ok all the time

### How to reproduce it (minimal and precise)

no idea

### Zigbee2MQTT version

 1.24.0

### Adapter firmware version

20211217

### Adapter

sonoff zigbee 3.0 usb dongle plus

### Debug log

Configuring 'Smoke Alarm'
Successfully configured 'Smoke Alarm'
MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"Smoke Alarm"},"status":"ok","transaction":"3ma5o-1"}'
MQTT publish: topic 'zigbee2mqtt/Smoke Alarm', payload '{"battery_low":null,"last_seen":1646400531563,"linkquality":153,"smoke":false}'

**Comment by tammeryousef1006** [comment]
Failed to configure '0x5c0272fffec4be19', attempt 1 (Error: Bind 0x5c0272fffec4be19/1 genBasic from '0x00124b00258d435f/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (internal/timers.js:557:17) at processTimers (internal/timers.js:500:7))

**Comment by tammeryousef1006** [comment]
![Capture](https://user-images.githubusercontent.com/62266828/156777016-081ec801-28dd-48d3-b036-4f1319eb078e.PNG)

**Comment by tammeryousef1006** [comment]
still the issue not solved
