### ISSUE TITLE
TS0601 TRV is missing preset 'none' from Heat mode

### ISSUE THREAD

**Issue by a8ree** [Koenkk/zigbee2mqtt#11785]
### What happened?

Other users of the TS0601 TRV using ZHA have an additional mode that is not present in Zigbee2MQTT. That mode is 'heat - none'. Whilst the mode is available in Home Assistant, it isn't in Zigbee2MQTT. When I attempt to use this mode, the following error is generated

```
Error Publish 'set' 'preset' to 'Lounge Door Radiator TRV' failed: 'Error: TRV preset off is not recognized.'
Info MQTT publish: topic 'zigbeehouse/bridge/log', payload '{"message":"Publish 'set' 'preset' to 'Lounge Door Radiator TRV' failed: 'Error: TRV preset off is not recognized.'","meta":{"friendly_name":"Lounge Door Radiator TRV"},"type":"zigbee_publish_error"}'
```

_Originally posted by @a8ree in https://github.com/Koenkk/zigbee2mqtt/issues/5578#issuecomment-1064137116_

### What did you expect to happen?

My understanding is that when this mode is available, the TRV will respond to the set temperature whilst in heat mode

### How to reproduce it (minimal and precise)

Within Home Assistant use the climate entity to switch the mode to 'Heat' and then use the preset 'none'

In Zigbee2MQTT under the exposes tab, the preset for non is missing

### Zigbee2MQTT version

1.24.0

### Adapter firmware version

20201026

### Adapter

zzh!

### Debug log

Received MQTT message on 'zigbeehouse/Lounge Door Radiator TRV/set/away_mode' with data 'OFF'
Debug Publishing 'set' 'away_mode' to 'Lounge Door Radiator TRV'
Debug Received MQTT message on 'zigbeehouse/Lounge Door Radiator TRV/set/preset' with data 'off'
Debug Publishing 'set' 'preset' to 'Lounge Door Radiator TRV'
Error Publish 'set' 'preset' to 'Lounge Door Radiator TRV' failed: 'Error: TRV preset off is not recognized.'
Debug Error: TRV preset off is not recognized. at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:4786:23) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:246:52) at EventEmitter.emit (events.js:412:35) at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:109:22) at MQTT.onMessage (/app/lib/mqtt.ts:122:27) at MqttClient.emit (events.js:400:28) at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:1547:12) at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:535:12) at work (/app/node_modules/mqtt/lib/client.js:438:12) at Writable.writable._write (/app/node_modules/mqtt/lib/client.js:452:5)
Info MQTT publish: topic 'zigbeehouse/bridge/log', payload '{"message":"Publish 'set' 'preset' to 'Lounge Door Radiator TRV' failed: 'Error: TRV preset off is not recognized.'","meta":{"friendly_name":"Lounge Door Radiator TRV"},"type":"zigbee_publish_error"}'
Debug Received Zigbee message from 'Lounge Door Radiator TRV', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,150],"type":"Buffer"},"datatype":2,"dp":2}],"seq":30466}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbeehouse/Lounge Door Radiator TRV', payload '{"auto_lock":null,"away_mode":"OFF","away_preset_days":null,"away_preset_temperature":10,"battery_low":null,"boost_time":null,"child_lock":null,"comfort_temperature":10,"current_heating_setpoint":15,"eco_temperature":10,"force":"open","holidays":[{"hour":6,"minute":0,"temperature":15},{"hour":8,"minute":0,"temperature":15},{"hour":11,"minute":30,"temperature":15},{"hour":12,"minute":30,"temperature":15},{"hour":17,"minute":30,"temperature":15},{"hour":22,"minute":0,"temperature":15}],"holidays_schedule":"06:00/15°C 08:00/15°C 11:30/15°C 12:30/15°C 17:30/15°C 22:00/15°C","linkquality":33,"local_temperature":16,"local_temperature_calibration":null,"max_temperature":23,"min_temperature":10,"position":100,"preset":"schedule","running_state":"heat","system_mode":"heat","update":{"state":"idle"},"update_available":false,"valve_detection":null,"window_detection":"ON","window_detection_params":{"minutes":118,"temperature":28},"workdays":[{"hour":6,"minute":0,"temperature":15},{"hour":8,"minute":0,"temperature":15},{"hour":11,"minute":30,"temperature":15},{"hour":12,"minute":30,"temperature":15},{"hour":17,"minute":30,"temperature":15},{"hour":22,"minute":0,"temperature":15}],"workdays_schedule":"06:00/15°C 08:00/15°C 11:30/15°C 12:30/15°C 17:30/15°C 22:00/15°C"}'
Debug Received Zigbee message from 'Lounge Door Radiator TRV', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":4}],"seq":30722}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbeehouse/Lounge Door Radiator TRV', payload '{"auto_lock":null,"away_mode":"OFF","away_preset_days":null,"away_preset_temperature":10,"battery_low":null,"boost_time":null,"child_lock":null,"comfort_temperature":10,"current_heating_setpoint":15,"eco_temperature":10,"force":"open","holidays":[{"hour":6,"minute":0,"temperature":15},{"hour":8,"minute":0,"temperature":15},{"hour":11,"minute":30,"temperature":15},{"hour":12,"minute":30,"temperature":15},{"hour":17,"minute":30,"temperature":15},{"hour":22,"minute":0,"temperature":15}],"holidays_schedule":"06:00/15°C 08:00/15°C 11:30/15°C 12:30/15°C 17:30/15°C 22:00/15°C","linkquality":33,"local_temperature":16,"local_temperature_calibration":null,"max_temperature":23,"min_temperature":10,"position":100,"preset":"schedule","running_state":"heat","system_mode":"heat","update":{"state":"idle"},"update_available":false,"valve_detection":null,"window_detection":"ON","window_detection_params":{"minutes":118,"temperature":28},"workdays":[{"hour":6,"minute":0,"temperature":15},{"hour":8,"minute":0,"temperature":15},{"hour":11,"minute":30,"temperature":15},{"hour":12,"minute":30,"temperature":15},{"hour":17,"minute":30,"temperature":15},{"hour":22,"minute":0,"temperature":15}],"workdays_schedule":"06:00/15°C 08:00/15°C 11:30/15°C 12:30/15°C 17:30/15°C 22:00/15°C"}'
Debug Received Zigbee message from 'Lounge Door Radiator TRV', type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0,0,0,10],"type":"Buffer"},"datatype":2,"dp":114}],"seq":30978}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbeehouse/Lounge Door Radiator TRV', payload '{"auto_lock":null,"away_mode":"OFF","away_preset_days":null,"away_preset_temperature":10,"battery_low":null,"boost_time":null,"child_lock":null,"comfort_temperature":10,"current_heating_setpoint":15,"eco_temperature":10,"force":"open","holidays":[{"hour":6,"minute":0,"temperature":15},{"hour":8,"minute":0,"temperature":15},{"hour":11,"minute":30,"temperature":15},{"hour":12,"minute":30,"temperature":15},{"hour":17,"minute":30,"temperature":15},{"hour":22,"minute":0,"temperature":15}],"holidays_schedule":"06:00/15°C 08:00/15°C 11:30/15°C 12:30/15°C 17:30/15°C 22:00/15°C","linkquality":33,"local_temperature":16,"local_temperature_calibration":null,"max_temperature":23,"min_temperature":10,"position":100,"preset":"schedule","running_state":"heat","system_mode":"heat","update":{"state":"idle"},"update_available":false,"valve_detection":null,"window_detection":"ON","window_detection_params":{"minutes":118,"temperature":28},"workdays":[{"hour":6,"minute":0,"temperature":15},{"hour":8,"minute":0,"temperature":15},{"hour":11,"minute":30,"temperature":15},{"hour":12,"minute":30,"temperature":15},{"hour":17,"minute":30,"temperature":15},{"hour":22,"minute":0,"temperature":15}],"workdays_schedule":"06:00/15°C 08:00/15°C 11:30/15°C 12:30/15°C 17:30/15°C 22:00/15°C"}'

**Comment by a8ree** [comment]
As a test I installed ZHA and connected the same device. It provided the mode heat and preset none. The TRV operates as expected.


<img width="420" alt="Screenshot 2022-03-10 at 18 09 34" src="https://user-images.githubusercontent.com/16214109/157755112-c25fb13b-4101-44b4-9665-07af568eeeff.png">
<img width="408" alt="Screenshot 2022-03-10 at 18 10 13" src="https://user-images.githubusercontent.com/16214109/157755118-4e092a72-cfe3-4c7e-8754-2d30604aeff7.png">

**Comment by a8ree** [comment]
Is anyone able to help with this?
