### ISSUE TITLE
Error while starting zigbee-herdsman

### ISSUE THREAD

**Issue by phobosdigg** [Koenkk/zigbee2mqtt#11788]
### What happened?

I haven't changed any settings on my Home Assistant for two or three weeks. And yesterday I found out that I can not enter the supervisor menu. After rebooting the raspberry, everything worked successfully except for the Zigbee2MQTT module.

### What did you expect to happen?

I expected a normal start z2m

### How to reproduce it (minimal and precise)

Start Zigbee2MQTT module

### Zigbee2MQTT version

1.24.0-1

### Adapter firmware version

i dont know

### Adapter

usb-Texas_Instruments_CC2538_USB_CDC-if00

### Debug log

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[21:03:58] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[21:04:00] INFO: MQTT available, fetching server detail ...
[21:04:00] INFO: Previous config file found, checking backup
[21:04:00] INFO: Creating backup config in '/share/zigbee2mqtt/.configuration.yaml.bk'
[21:04:00] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:04:02] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.24.0 start
> node index.js
Zigbee2MQTT:debug 2022-03-10 21:04:15: Loaded state from file /share/zigbee2mqtt/state.json
Zigbee2MQTT:info  2022-03-10 21:04:15: Logging to console and directory: '/share/zigbee2mqtt/log/2022-03-10.21-04-10' filename: log.txt
Zigbee2MQTT:debug 2022-03-10 21:04:15: Removing old log directory '/share/zigbee2mqtt/log/2022-03-10.21-00-43'
Zigbee2MQTT:info  2022-03-10 21:04:15: Starting Zigbee2MQTT version 1.24.0 (commit #unknown)
Zigbee2MQTT:info  2022-03-10 21:04:15: Starting zigbee-herdsman (0.14.20)
Zigbee2MQTT:debug 2022-03-10 21:04:15: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/share/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/share/zigbee2mqtt/database.db.backup","databasePath":"/share/zigbee2mqtt/database.db","network":{"channelList":[15],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6755},"serialPort":{"path":"/dev/ttyACM0"}}'
Zigbee2MQTT:error 2022-03-10 21:04:16: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-03-10 21:04:16: Failed to start zigbee
Zigbee2MQTT:error 2022-03-10 21:04:16: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-03-10 21:04:16: Exiting...
Zigbee2MQTT:error 2022-03-10 21:04:16: Error: Coordinator backup is corrupted
    at AdapterBackup.getStoredBackup (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/adapter-backup.ts:44:19)
    at ZnpAdapterManager.determineStrategy (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:134:24)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:63:26)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:101:5)

**Comment by Koenkk** [comment]
Could you try deleting the data/coordinator_backup.json? (this file will be automatically recreated after 1 day)
