### ISSUE TITLE
failed to connect to the adapter

### ISSUE THREAD

**Issue by ede-kowalski** [Koenkk/zigbee2mqtt#11846]
### What happened?

Hi all,

i have issies to connect to my adapter.
It is connected to an RPi4, but i also tried it with my laptop power adapter.
If i use my old stick everything is working fine, but as soon as i am switching to the new adapter (CC2652P with actual FW) it is not working anymore.
It was working in the past, so i was the opinion maybe it is really related to the power adapter. But this is not the case.

Error is: Zigbee2MQTT:error 2022-03-14 18:22:20: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)

Correct port is configured and the user has access to the port (tried the script in FAQ).
Any hints?

Thanks,
Ede

### What did you expect to happen?

Adapter was recognized and Zigbee2mqtt started.

### Zigbee2MQTT version

newest

### Adapter firmware version

20211217

### Adapter

Itead Sonoff 3.0 CC2652P

### Debug log

debug 2022-03-14 18:21:59: Loaded state from file /opt/zigbee2mqtt/data/state.json
info  2022-03-14 18:21:59: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2022-03-14.18-21-57' filename: log.txt
debug 2022-03-14 18:21:59: Removing old log directory '/opt/zigbee2mqtt/data/log/2022-03-14.17-44-46'
info  2022-03-14 18:21:59: Starting Zigbee2MQTT version 1.24.0 (commit #7a2ddf24)
info  2022-03-14 18:21:59: Starting zigbee-herdsman (0.14.20)
debug 2022-03-14 18:21:59: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","databasePath":"/opt/zigbee2mqtt/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_629f0177b0c9eb118855914f1d69213e-if00-port0"}}'
error 2022-03-14 18:22:20: Error while starting zigbee-herdsman
error 2022-03-14 18:22:20: Failed to start zigbee
error 2022-03-14 18:22:20: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2022-03-14 18:22:20: Exiting...
error 2022-03-14 18:22:20: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:58:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:100:27)
    at start (/opt/zigbee2mqtt/index.js:101:5)

**Comment by mickey00001** [comment]
I have the same problem

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[22:48:01] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[22:48:02] INFO: MQTT available, fetching server detail ...
[22:48:03] INFO: Previous config file found, checking backup
[22:48:03] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[22:48:03] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:48:05] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.24.0 start
> node index.js
Zigbee2MQTT:error 2022-03-30 22:50:04: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-03-30 22:50:04: Failed to start zigbee
Zigbee2MQTT:error 2022-03-30 22:50:04: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-03-30 22:50:04: Exiting...
Zigbee2MQTT:error 2022-03-30 22:50:04: TypeError: Cannot read property 'payload' of undefined
    at AdapterNvMemory.deleteItem (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/adapter-nv-memory.ts:147:115)
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:330:9)
    at ZnpAdapterManager.beginRestore (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:296:9)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:80:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:101:5)
[22:50:05] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.24.0 start
> node index.js`

**Comment by FreakErn** [comment]
@ede-kowalski could you do a:

`ls -las /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_629f0177b0c9eb118855914f1d69213e-if00-port0`

and try using the port where this symlink is linked to (eg. /dev/ttyACM0)

And check if this works. If i use the by-id device it does not work for me either.

**Comment by mickey00001** [comment]
> 

It don´t work. The error after i do this, is a little bit different.

`[09:32:22] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.24.0 start
> node index.js
Zigbee2MQTT:error 2022-03-31 09:32:54: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-03-31 09:32:54: Failed to start zigbee
Zigbee2MQTT:error 2022-03-31 09:32:54: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-03-31 09:32:54: Exiting...
Zigbee2MQTT:error 2022-03-31 09:32:54: Error: SRSP - SYS - getExtAddr after 6000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[09:32:55] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.24.0 start
> node index.js
Zigbee2MQTT:error 2022-03-31 09:33:26: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-03-31 09:33:26: Failed to start zigbee
Zigbee2MQTT:error 2022-03-31 09:33:26: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-03-31 09:33:26: Exiting...
Zigbee2MQTT:error 2022-03-31 09:33:26: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:101:5)`

**My config is this:**
`mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.168.178.63:1883
  user: mqtt
  password: *********
serial:
  port: /dev/ttyUSB0`

**Comment by FreakErn** [comment]
Then i think it is a permissions problem. Could you post the result of 
`$ groups`?

You need these three groups to get access to the device as user
```
sudo usermod -a -G uucp $USER
sudo usermod -a -G tty $USER
sudo usermod -a -G dialout $USER
```

**Comment by mickey00001** [comment]
The result of groups:
`root lpadmin`

The result of mqtt
`root@raspidocker:~# id mqtt
uid=1002(mqtt) gid=1002(mqtt) groups=1002(mqtt),5(tty),10(uucp),20(dialout)`

I think the port in the config is correkt because there is no error message like "Error while opening serialport" in the log when i config it with 
`serial:
  port: /dev/ttyUSB0`

The last log:
`[10:48:12] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.24.0 start
> node index.js
Zigbee2MQTT:error 2022-03-31 10:48:57: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-03-31 10:48:57: Failed to start zigbee
Zigbee2MQTT:error 2022-03-31 10:48:57: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-03-31 10:48:57: Exiting...
Zigbee2MQTT:error 2022-03-31 10:48:58: TypeError: Cannot read property 'payload' of undefined
    at AdapterNvMemory.deleteItem (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/adapter-nv-memory.ts:147:115)
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:330:9)
    at ZnpAdapterManager.beginRestore (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:296:9)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:80:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:101:5)`
