### ISSUE TITLE
E11-N1EA causes crash when RGB set, cannot read propeerty 'key' of undefined

### ISSUE THREAD

**Issue by marc-gist** [Koenkk/zigbee2mqtt#1196]
Did you read the FAQ?
https://www.zigbee2mqtt.io/information/FAQ.md

Unsupported device?
No, in list of supported

    /opt/zigbee2mqtt/lib/extension/devicePublish.js:140
            const converter = converters.find((c) => c.key.includes(key));
                                                       ^
    TypeError: Cannot read property 'key' of undefined
        at converters.find (/opt/zigbee2mqtt/lib/extension/devicePublish.js:140:56)
        at Array.find (<anonymous>)
        at keys.forEach (/opt/zigbee2mqtt/lib/extension/devicePublish.js:140:42)
        at Array.forEach (<anonymous>)
        at DevicePublish.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/devicePublish.js:139:14)
        at results.extensions.filter.map (/opt/zigbee2mqtt/lib/controller.js:134:27)
        at Array.map (<anonymous>)
        at Controller.onMQTTMessage (/opt/zigbee2mqtt/lib/controller.js:134:14)
        at MQTT.onMessage (/opt/zigbee2mqtt/lib/mqtt.js:81:18)
        at MqttClient.emit (events.js:189:13)

**Comment by marc-gist** [comment]
sorry should also add above messages

    3/5/2019, 5:25:39 PM Received MQTT message on 'zigbee/device/sengled_rgb_bulb/set' with data '{"state": "ON", "color": {"r": 255, "g": 36, "b": 36}}'
    zigbee2mqtt:info 3/5/2019, 5:25:39 PM Zigbee publish to device '0xb0ce1814000275ca', genOnOff - on - {} -

**Comment by marc-gist** [comment]
Note, also happening for a samsung switch :( same code line

**Comment by marc-gist** [comment]
Updated to dev branch... working now sorry.
