### ISSUE TITLE
interview failed on smart+ switch (osram) AC16716

### ISSUE THREAD

**Issue by Phorze** [Koenkk/zigbee2mqtt#11969]
### What happened?

interview failed on unsupported device, "can not get node descriptor" herdsman logs included.

### Zigbee2MQTT version

1.24

### Adapter firmware version

20201010

### Adapter

CC2538+CC2592

### Debug log

2022-03-28T10:52:28.207Z zigbee-herdsman:controller:device:log Interview - start device '0xf0d1b8000015ea0c'
2022-03-28T10:52:28.207Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":20871,"nwkaddrofinterest":20871}
2022-03-28T10:52:28.207Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,135,81,135,81,35]
2022-03-28T10:52:28.520Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2022-03-28T10:52:28.520Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2022-03-28T10:52:28.520Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2022-03-28T10:52:28.521Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2022-03-28T10:52:28.521Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:52:28.522Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,12,69,202,135,81,12,234,21,0,0,184,209,240,0,0,63]
2022-03-28T10:52:28.522Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,12,69,202,135,81,12,234,21,0,0,184,209,240,0,0,63]
2022-03-28T10:52:28.522Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 12 - 2 - 5 - 202 - [135,81,12,234,21,0,0,184,209,240,0,0] - 63
2022-03-28T10:52:28.522Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - tcDeviceInd - {"nwkaddr":20871,"extaddr":"0xf0d1b8000015ea0c","parentaddr":0}
2022-03-28T10:52:28.522Z zigbee-herdsman:controller:log Device '0xf0d1b8000015ea0c' joined
2022-03-28T10:52:28.522Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:52:28.523Z zigbee-herdsman:controller:log Device '0xf0d1b8000015ea0c' accepted by handler
2022-03-28T10:52:28.523Z zigbee-herdsman:controller:log Not interviewing '0xf0d1b8000015ea0c', completed 'false', in progress 'true'
2022-03-28T10:52:28.526Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,12,69,202,135,81,12,234,21,0,0,184,209,240,0,0,63]
2022-03-28T10:52:28.526Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,12,69,202,135,81,12,234,21,0,0,184,209,240,0,0,63]
2022-03-28T10:52:28.526Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 12 - 2 - 5 - 202 - [135,81,12,234,21,0,0,184,209,240,0,0] - 63
2022-03-28T10:52:28.526Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - tcDeviceInd - {"nwkaddr":20871,"extaddr":"0xf0d1b8000015ea0c","parentaddr":0}
2022-03-28T10:52:28.526Z zigbee-herdsman:controller:log Device '0xf0d1b8000015ea0c' joined
2022-03-28T10:52:28.526Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:52:28.527Z zigbee-herdsman:controller:log Device '0xf0d1b8000015ea0c' accepted by handler
2022-03-28T10:52:28.527Z zigbee-herdsman:controller:log Not interviewing '0xf0d1b8000015ea0c', completed 'false', in progress 'true'
2022-03-28T10:52:28.530Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,12,69,202,135,81,12,234,21,0,0,184,209,240,0,0,63]
2022-03-28T10:52:28.530Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,12,69,202,135,81,12,234,21,0,0,184,209,240,0,0,63]
2022-03-28T10:52:28.530Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 12 - 2 - 5 - 202 - [135,81,12,234,21,0,0,184,209,240,0,0] - 63
2022-03-28T10:52:28.530Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - tcDeviceInd - {"nwkaddr":20871,"extaddr":"0xf0d1b8000015ea0c","parentaddr":0}
2022-03-28T10:52:28.530Z zigbee-herdsman:controller:log Device '0xf0d1b8000015ea0c' joined
2022-03-28T10:52:28.530Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:52:28.530Z zigbee-herdsman:controller:log Device '0xf0d1b8000015ea0c' accepted by handler
2022-03-28T10:52:28.531Z zigbee-herdsman:controller:log Not interviewing '0xf0d1b8000015ea0c', completed 'false', in progress 'true'
2022-03-28T10:52:38.524Z zigbee-herdsman:adapter:zStack:adapter Node descriptor request for '20871' failed (Error: AREQ - ZDO - nodeDescRsp after 10000ms), retry
2022-03-28T10:52:38.524Z zigbee-herdsman:adapter:zStack:adapter Discovering route to 20871
2022-03-28T10:52:38.524Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - extRouteDisc - {"dstAddr":20871,"options":0,"radius":30}
2022-03-28T10:52:38.524Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,69,135,81,0,30,172]
2022-03-28T10:52:38.526Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,69,0,33]
2022-03-28T10:52:38.526Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,69,0,33]
2022-03-28T10:52:38.526Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 69 - [0] - 33
2022-03-28T10:52:38.526Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - extRouteDisc - {"status":0}
2022-03-28T10:52:38.526Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:52:41.530Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":20871,"nwkaddrofinterest":20871}
2022-03-28T10:52:41.531Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,135,81,135,81,35]
2022-03-28T10:52:41.532Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2022-03-28T10:52:41.532Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2022-03-28T10:52:41.532Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2022-03-28T10:52:41.533Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2022-03-28T10:52:41.533Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:52:51.540Z zigbee-herdsman:controller:device:log Interview - quirks check for 'undefined'-'undefined'-'Unknown'
2022-03-28T10:52:51.540Z zigbee-herdsman:controller:device:log Interview - quirks did not match
2022-03-28T10:52:51.540Z zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0xf0d1b8000015ea0c', attempt 1
2022-03-28T10:52:51.540Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":20871,"nwkaddrofinterest":20871}
2022-03-28T10:52:51.540Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,135,81,135,81,35]
2022-03-28T10:52:51.542Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2022-03-28T10:52:51.542Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2022-03-28T10:52:51.542Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2022-03-28T10:52:51.542Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2022-03-28T10:52:51.543Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:52:53.676Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - mgmtPermitJoinReq - {"addrmode":15,"dstaddr":65532,"duration":254,"tcsignificance":0}
2022-03-28T10:52:53.676Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,37,54,15,252,255,254,0,228]
2022-03-28T10:52:53.678Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,54,0,82]
2022-03-28T10:52:53.678Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,54,0,82]
2022-03-28T10:52:53.678Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 54 - [0] - 82
2022-03-28T10:52:53.679Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - mgmtPermitJoinReq - {"status":0}
2022-03-28T10:52:53.679Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:52:53.679Z zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequestExt - {"dstaddrmode":2,"dstaddr":"0x000000000000fffd","destendpoint":242,"dstpanid":0,"srcendpoint":242,"clusterid":33,"transid":15,"options":0,"radius":30,"len":6,"data":{"type":"Buffer","data":[25,16,2,11,254,0]}}
2022-03-28T10:52:53.680Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,26,36,2,2,253,255,0,0,0,0,0,0,242,0,0,242,33,0,15,0,30,6,0,25,16,2,11,254,0,244]
2022-03-28T10:52:53.680Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,69,182,0,0,0,240]
2022-03-28T10:52:53.681Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,69,182,0,0,0,240]
2022-03-28T10:52:53.681Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 5 - 182 - [0,0,0] - 240
2022-03-28T10:52:53.681Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - mgmtPermitJoinRsp - {"srcaddr":0,"status":0}
2022-03-28T10:52:53.681Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:52:53.682Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,100,2,0,103]
2022-03-28T10:52:53.682Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,2,0,103]
2022-03-28T10:52:53.682Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 2 - [0] - 103
2022-03-28T10:52:53.682Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequestExt - {"status":0}
2022-03-28T10:52:53.682Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:52:53.685Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,68,128,0,242,15,58]
2022-03-28T10:52:53.685Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,0,242,15,58]
2022-03-28T10:52:53.685Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [0,242,15] - 58
2022-03-28T10:52:53.685Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":242,"transid":15}
2022-03-28T10:52:53.685Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:53:01.549Z zigbee-herdsman:adapter:zStack:adapter Node descriptor request for '20871' failed (Error: AREQ - ZDO - nodeDescRsp after 10000ms), retry
2022-03-28T10:53:01.549Z zigbee-herdsman:adapter:zStack:adapter Discovering route to 20871
2022-03-28T10:53:01.550Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - extRouteDisc - {"dstAddr":20871,"options":0,"radius":30}
2022-03-28T10:53:01.550Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,69,135,81,0,30,172]
2022-03-28T10:53:01.551Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,69,0,33]
2022-03-28T10:53:01.551Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,69,0,33]
2022-03-28T10:53:01.551Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 69 - [0] - 33
2022-03-28T10:53:01.551Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - extRouteDisc - {"status":0}
2022-03-28T10:53:01.551Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:53:04.556Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":20871,"nwkaddrofinterest":20871}
2022-03-28T10:53:04.556Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,135,81,135,81,35]
2022-03-28T10:53:04.559Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2022-03-28T10:53:04.559Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2022-03-28T10:53:04.559Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2022-03-28T10:53:04.559Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2022-03-28T10:53:04.559Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:53:14.568Z zigbee-herdsman:controller:device:log Interview - quirks check for 'undefined'-'undefined'-'Unknown'
2022-03-28T10:53:14.568Z zigbee-herdsman:controller:device:log Interview - quirks did not match
2022-03-28T10:53:14.568Z zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0xf0d1b8000015ea0c', attempt 2
2022-03-28T10:53:14.569Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":20871,"nwkaddrofinterest":20871}
2022-03-28T10:53:14.569Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,135,81,135,81,35]
2022-03-28T10:53:14.570Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2022-03-28T10:53:14.571Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2022-03-28T10:53:14.571Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2022-03-28T10:53:14.571Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2022-03-28T10:53:14.571Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:53:24.580Z zigbee-herdsman:adapter:zStack:adapter Node descriptor request for '20871' failed (Error: AREQ - ZDO - nodeDescRsp after 10000ms), retry
2022-03-28T10:53:24.580Z zigbee-herdsman:adapter:zStack:adapter Discovering route to 20871
2022-03-28T10:53:24.581Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - extRouteDisc - {"dstAddr":20871,"options":0,"radius":30}
2022-03-28T10:53:24.581Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,69,135,81,0,30,172]
2022-03-28T10:53:24.582Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,69,0,33]
2022-03-28T10:53:24.583Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,69,0,33]
2022-03-28T10:53:24.583Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 69 - [0] - 33
2022-03-28T10:53:24.583Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - extRouteDisc - {"status":0}
2022-03-28T10:53:24.583Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:53:27.584Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":20871,"nwkaddrofinterest":20871}
2022-03-28T10:53:27.584Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,135,81,135,81,35]
2022-03-28T10:53:27.585Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2022-03-28T10:53:27.585Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2022-03-28T10:53:27.585Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2022-03-28T10:53:27.585Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2022-03-28T10:53:27.585Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:53:37.587Z zigbee-herdsman:controller:device:log Interview - quirks check for 'undefined'-'undefined'-'Unknown'
2022-03-28T10:53:37.587Z zigbee-herdsman:controller:device:log Interview - quirks did not match
2022-03-28T10:53:37.587Z zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0xf0d1b8000015ea0c', attempt 3
2022-03-28T10:53:37.588Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":20871,"nwkaddrofinterest":20871}
2022-03-28T10:53:37.588Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,135,81,135,81,35]
2022-03-28T10:53:37.590Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2022-03-28T10:53:37.590Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2022-03-28T10:53:37.590Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2022-03-28T10:53:37.591Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2022-03-28T10:53:37.591Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:53:47.594Z zigbee-herdsman:adapter:zStack:adapter Node descriptor request for '20871' failed (Error: AREQ - ZDO - nodeDescRsp after 10000ms), retry
2022-03-28T10:53:47.594Z zigbee-herdsman:adapter:zStack:adapter Discovering route to 20871
2022-03-28T10:53:47.594Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - extRouteDisc - {"dstAddr":20871,"options":0,"radius":30}
2022-03-28T10:53:47.594Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,69,135,81,0,30,172]
2022-03-28T10:53:47.596Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,69,0,33]
2022-03-28T10:53:47.596Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,69,0,33]
2022-03-28T10:53:47.596Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 69 - [0] - 33
2022-03-28T10:53:47.596Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - extRouteDisc - {"status":0}
2022-03-28T10:53:47.596Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:53:50.599Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":20871,"nwkaddrofinterest":20871}
2022-03-28T10:53:50.600Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,135,81,135,81,35]
2022-03-28T10:53:50.603Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2022-03-28T10:53:50.603Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2022-03-28T10:53:50.603Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2022-03-28T10:53:50.603Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2022-03-28T10:53:50.603Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:54:00.608Z zigbee-herdsman:controller:device:log Interview - quirks check for 'undefined'-'undefined'-'Unknown'
2022-03-28T10:54:00.608Z zigbee-herdsman:controller:device:log Interview - quirks did not match
2022-03-28T10:54:00.608Z zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0xf0d1b8000015ea0c', attempt 4
2022-03-28T10:54:00.608Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":20871,"nwkaddrofinterest":20871}
2022-03-28T10:54:00.613Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,135,81,135,81,35]
2022-03-28T10:54:00.615Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2022-03-28T10:54:00.615Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2022-03-28T10:54:00.615Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2022-03-28T10:54:00.615Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2022-03-28T10:54:00.615Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:54:10.620Z zigbee-herdsman:adapter:zStack:adapter Node descriptor request for '20871' failed (Error: AREQ - ZDO - nodeDescRsp after 10000ms), retry
2022-03-28T10:54:10.620Z zigbee-herdsman:adapter:zStack:adapter Discovering route to 20871
2022-03-28T10:54:10.620Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - extRouteDisc - {"dstAddr":20871,"options":0,"radius":30}
2022-03-28T10:54:10.620Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,69,135,81,0,30,172]
2022-03-28T10:54:10.622Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,69,0,33]
2022-03-28T10:54:10.622Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,69,0,33]
2022-03-28T10:54:10.622Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 69 - [0] - 33
2022-03-28T10:54:10.622Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - extRouteDisc - {"status":0}
2022-03-28T10:54:10.623Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:54:13.627Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":20871,"nwkaddrofinterest":20871}
2022-03-28T10:54:13.627Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,135,81,135,81,35]
2022-03-28T10:54:13.629Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2022-03-28T10:54:13.629Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2022-03-28T10:54:13.629Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2022-03-28T10:54:13.629Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2022-03-28T10:54:13.629Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:54:23.636Z zigbee-herdsman:controller:device:log Interview - quirks check for 'undefined'-'undefined'-'Unknown'
2022-03-28T10:54:23.636Z zigbee-herdsman:controller:device:log Interview - quirks did not match
2022-03-28T10:54:23.636Z zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0xf0d1b8000015ea0c', attempt 5
2022-03-28T10:54:23.636Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":20871,"nwkaddrofinterest":20871}
2022-03-28T10:54:23.636Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,135,81,135,81,35]
2022-03-28T10:54:23.638Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2022-03-28T10:54:23.639Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2022-03-28T10:54:23.639Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2022-03-28T10:54:23.639Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2022-03-28T10:54:23.639Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:54:33.644Z zigbee-herdsman:adapter:zStack:adapter Node descriptor request for '20871' failed (Error: AREQ - ZDO - nodeDescRsp after 10000ms), retry
2022-03-28T10:54:33.644Z zigbee-herdsman:adapter:zStack:adapter Discovering route to 20871
2022-03-28T10:54:33.645Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - extRouteDisc - {"dstAddr":20871,"options":0,"radius":30}
2022-03-28T10:54:33.645Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,69,135,81,0,30,172]
2022-03-28T10:54:33.646Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,69,0,33]
2022-03-28T10:54:33.646Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,69,0,33]
2022-03-28T10:54:33.646Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 69 - [0] - 33
2022-03-28T10:54:33.646Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - extRouteDisc - {"status":0}
2022-03-28T10:54:33.646Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:54:36.648Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":20871,"nwkaddrofinterest":20871}
2022-03-28T10:54:36.648Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,135,81,135,81,35]
2022-03-28T10:54:36.650Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2022-03-28T10:54:36.650Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2022-03-28T10:54:36.650Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2022-03-28T10:54:36.651Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2022-03-28T10:54:36.651Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-03-28T10:54:46.653Z zigbee-herdsman:controller:device:log Interview - quirks check for 'undefined'-'undefined'-'Unknown'
2022-03-28T10:54:46.653Z zigbee-herdsman:controller:device:log Interview - quirks did not match
2022-03-28T10:54:46.653Z zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0xf0d1b8000015ea0c', attempt 6
2022-03-28T10:54:46.653Z zigbee-herdsman:controller:device:log Interview - quirks check for 'undefined'-'undefined'-'Unknown'
2022-03-28T10:54:46.653Z zigbee-herdsman:controller:device:log Interview - quirks did not match
2022-03-28T10:54:46.654Z zigbee-herdsman:controller:device:log Interview - failed for device '0xf0d1b8000015ea0c' with error 'Error: Interview failed because can not get node descriptor ('0xf0d1b8000015ea0c')
    at Device.interviewInternal (/app/node_modules/zigbee-herdsman/src/controller/model/device.ts:553:19)
    at Device.interview (/app/node_modules/zigbee-herdsman/src/controller/model/device.ts:440:13)
    at Controller.onDeviceJoined (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:534:17)'
2022-03-28T10:54:46.656Z zigbee-herdsman:controller:error Interview failed for '0xf0d1b8000015ea0c with error 'Error: Interview failed because can not get node descriptor ('0xf0d1b8000015ea0c')'

**Comment by Phorze** [comment]
Changing from the default zigbee channel 11 to 20 made this adapter work 
[AC10691](https://www.zigbee2mqtt.io/devices/AC10691.html#osram-ac10691)
