### ISSUE TITLE
Devices no longer connected after update to 1.25 (even after rollback to 1.24)

### ISSUE THREAD

**Issue by RazoredRaven** [Koenkk/zigbee2mqtt#12079]
### What happened?

Since updating to 1.25 (even ensuring that the config file is updated [which seems to happen automatically], I've had 90% of my devices stop connecting to my network and show LQI state of "N/A". Even those with an LQI state number do not respond to commands.

### What did you expect to happen?

Devices to be able to keep connected to network.

### How to reproduce it (minimal and precise)

Updated from 1.25.1 and found issue, rollbacked and issue persists.

### Zigbee2MQTT version

1.24.0

### Adapter firmware version

0x26720700

### Adapter

ConBee2/RaspBee2

### Debug log

```
Debug Received MQTT message on 'zigbee2mqtt/Dining Room Lights/set' with data '{"state":"ON"}'
Debug Publishing 'set' 'state' to 'Dining Room Lights'
Error Publish 'set' 'state' to 'Dining Room Lights' failed: 'Error: Command 0x086bd7fffe5d1323/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received)'
Debug Error: Command 0x086bd7fffe5d1323/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received) at DeconzAdapter.sendZclFrameToEndpoint (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:649:23) at Endpoint.sendRequest (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:299:20) at Endpoint.command (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:772:28) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:283:17) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:865:40) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:246:36)
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'Dining Room Lights' failed: 'Error: Command 0x086bd7fffe5d1323/1 genOnOff.on({}, {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received)'","meta":{"friendly_name":"Dining Room Lights"},"type":"zigbee_publish_error"}'

Debug Device 'Bedroom 1 Sensor' announced itself
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Bedroom 1 Sensor","ieee_address":"0x001788010867f082"},"type":"device_announce"}'
Info MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"Bedroom 1 Sensor"},"type":"device_announced"}'

Error Failed to configure 'Bedroom 2 Sensor', attempt 1 (Error: Bind 0x0017880108662b7c/2 genPowerCfg from '0x00212effff07316c/1' failed (waiting for response TIMEOUT) at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:761:19) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:567:13) at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:34:9) at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/philips.js:2007:13) at Configure.configure (/app/lib/extension/configure.ts:115:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:21))
Info MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"Bedroom 2 Sensor"},"error":"Failed to configure (Bind 0x0017880108662b7c/2 genPowerCfg from '0x00212effff07316c/1' failed (waiting for response TIMEOUT))","status":"error","transaction":"oqlrf-1"}'

Zigbee2MQTT:debug 2022-04-05 22:43:53: Received MQTT message on 'zigbee2mqtt/Dining Room Lights/set' with data '{"state": "ON"}'
Zigbee2MQTT:debug 2022-04-05 22:43:53: Publishing 'set' 'state' to 'Dining Room Lights'
Zigbee2MQTT:error 2022-04-05 22:44:54: Publish 'set' 'state' to 'Dining Room Lights' failed: 'Error: Command 0x086bd7fffe5d1323/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received)'
Zigbee2MQTT:debug 2022-04-05 22:44:54: Error: Command 0x086bd7fffe5d1323/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received)
    at DeconzAdapter.sendZclFrameToEndpoint (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:649:23)
    at Endpoint.sendRequest (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:299:20)
    at Endpoint.command (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:772:28)
    at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:283:17)
    at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:865:40)
    at Publish.onMQTTMessage (/app/lib/extension/publish.ts:246:36)
Zigbee2MQTT:info  2022-04-05 22:44:54: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'Dining Room Lights' failed: 'Error: Command 0x086bd7fffe5d1323/1 genOnOff.on({}, {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received)'","meta":{"friendly_name":"Dining Room Lights"},"type":"zigbee_publish_error"}'
```

**Comment by RazoredRaven** [comment]
I tried a lot of things, like rolling back to 1.24, restoring to a backup from 1.24, restarting HA server etc many times before raising this issue.

In case anyone else has the same issue, I _THINK_ what may have helped resolve it was restarting my router, as maybe somehow the bands began overlapping?
