### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by AshtonKem** [Koenkk/zigbee2mqtt#12205]
### What happened?

Restarting Zigbee2Mqtt sometime after updating. It now crashes on startup and will not run.

### How to reproduce it (minimal and precise)

Not entirely sure.

### Zigbee2MQTT version

1.25.0-1

### Adapter firmware version

20210120

### Adapter

zzh!

### Debug log

Zigbee2MQTT:debug 2022-04-17 20:24:18: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6755},"serialPort":{"path":"/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0","rtscts":false}}'
Zigbee2MQTT:error 2022-04-17 20:24:18: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-04-17 20:24:18: Failed to start zigbee
Zigbee2MQTT:error 2022-04-17 20:24:18: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-04-17 20:24:18: Exiting...
Zigbee2MQTT:error 2022-04-17 20:24:18: TypeError: Cannot read property 'length' of null
    at AdapterNvMemory.init (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/adapter-nv-memory.ts:28:42)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:60:9)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller

**Comment by AshtonKem** [comment]
Updating to the latest coordinator firmware, I now get a `(Error: SRSP - SYS - ping after 6000ms)`. Following the official instructions did not fix it.

**Comment by AshtonKem** [comment]
Ah. I had some power outages (server shares a circuit with a power saw) and I think it killed my zzh stick.
