### ISSUE TITLE
new inclusion error

### ISSUE THREAD

**Issue by apages2** [Koenkk/zigbee2mqtt#12355]
### What happened?

Hello,

during an inclusion, zigbee2mqtt returns an error :

Failed to configure '0x00047400007eb962', attempt 1 (Error: Bind 0x00047400007eb962/2 genPowerCfg from '0x00212effff0812bc/1' failed (Error: status: 130) at DeconzAdapter.bind (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:761:19) at Endpoint.bind (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:567:13) at Object.bind (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/lib/reporting.js:34:9) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices/legrand.js:149:13) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:115:13))

which is normal because for this module there is no genPowerCfg on endpoint 2

![2022-05-02 20_43_59-Zigbee2MQTT](https://user-images.githubusercontent.com/12720395/166306396-af35ba3a-28ce-4048-83c5-9eb91e3680c2.jpg)
![2022-05-02 20_44_08-Zigbee2MQTT](https://user-images.githubusercontent.com/12720395/166306410-b1e1158e-6114-4dca-b7ce-6c849dcd51d3.jpg)

### What did you expect to happen?

no error message

### How to reproduce it (minimal and precise)

include a legrand 067774 module.1.25.0

### Zigbee2MQTT version

1.25.0

### Adapter firmware version

0x26720700

### Adapter

ConBee2

### Debug log

Failed to configure '0x00047400007eb962', attempt 1 (Error: Bind 0x00047400007eb962/2 genPowerCfg from '0x00212effff0812bc/1' failed (Error: status: 130) at DeconzAdapter.bind (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:761:19) at Endpoint.bind (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:567:13) at Object.bind (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/lib/reporting.js:34:9) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices/legrand.js:149:13) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:115:13))

**Comment by apages2** [comment]
corrected in PR https://github.com/Koenkk/zigbee-herdsman-converters/pull/4195
