### ISSUE TITLE
Firmware update check might raise an error

### ISSUE THREAD

**Issue by agross** [Koenkk/zigbee2mqtt#12501]
### What happened?

I tried checking for firmware updates using iobroker.zigbee (a lib that uses z2m). I have 42 devices joined.

### What did you expect to happen?

Update check succeeds. Right now it shows, but after 30 secs the adapter crashes with an unhandled exception.

### Zigbee2MQTT version

zigbee-herdsman-0.14.26, zigbee-herdsman-converters 14.0.491

### Adapter firmware version

210210319

### Adapter

CC2652P

### Debug log

```
2022-05-16 12:30:03.497  - error: host.iobroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-05-16 12:30:03.498  - error: host.iobroker Caught by controller[1]: Error: Timeout - 14862 - 2 - null - 25 - 1 after 30000ms
2022-05-16 12:30:03.498  - error: host.iobroker Caught by controller[1]:     at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
2022-05-16 12:30:03.498  - error: host.iobroker Caught by controller[1]:     at listOnTimeout (internal/timers.js:557:17)
2022-05-16 12:30:03.499  - error: host.iobroker Caught by controller[1]:     at processTimers (internal/timers.js:500:7)
2022-05-16 12:30:03.499  - error: host.iobroker Caught by controller[2]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-05-16 12:30:03.499  - error: host.iobroker Caught by controller[2]: Error: Timeout - 62627 - 11 - null - 25 - 1 after 30000ms
2022-05-16 12:30:03.500  - error: host.iobroker Caught by controller[2]:     at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
2022-05-16 12:30:03.500  - error: host.iobroker Caught by controller[2]:     at listOnTimeout (internal/timers.js:557:17)
2022-05-16 12:30:03.500  - error: host.iobroker Caught by controller[2]:     at processTimers (internal/timers.js:500:7)
2022-05-16 12:30:03.501  - error: host.iobroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2
```

**Comment by agross** [comment]
[z2m + iobroker.zigbee.log](https://github.com/Koenkk/zigbee2mqtt/files/8699803/z2m.%2B.iobroker.zigbee.log)
