### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by allenrobberson** [Koenkk/zigbee2mqtt#12664]
### What happened?

When i try to click on sidebar for Z2M i get Bad Gateway.

### What did you expect to happen?

Open Z2M interface

### Zigbee2MQTT version

Zigbee2mqtt Edge

### Adapter firmware version

Latest

### Adapter

sonoff 3+

### Debug log

Home Assistant Core 2022.6.0b3
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

```
[services.d] starting services
[services.d] done.
[14:00:43] INFO: Zigbee Herdsman debug logging enabled
[14:00:45] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.25.1-dev start
> node index.js
(node:358) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'options' of undefined
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:91:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:83:58)
    at start (/app/index.js:109:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:358) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:358) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[14:00:54] INFO: Zigbee Herdsman debug logging enabled
[14:00:55] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.25.1-dev start
> node index.js
(node:442) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'options' of undefined
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:91:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:83:58)
    at start (/app/index.js:109:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:442) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:442) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[14:01:03] INFO: Zigbee Herdsman debug logging enabled
[14:01:05] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.25.1-dev start
> node index.js
(node:526) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'options' of undefined
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:91:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:83:58)
    at start (/app/index.js:109:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:526) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:526) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[14:01:12] INFO: Zigbee Herdsman debug logging enabled
[14:01:14] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.25.1-dev start
> node index.js
(node:610) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'options' of undefined
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:91:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:83:58)
    at start (/app/index.js:109:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:610) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:610) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[14:01:21] INFO: Zigbee Herdsman debug logging enabled
[14:01:23] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.25.1-dev start
> node index.js
(node:694) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'options' of undefined
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:91:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:83:58)
    at start (/app/index.js:109:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:694) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:694) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[14:01:31] INFO: Zigbee Herdsman debug logging enabled
[14:01:33] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.25.1-dev start
> node index.js
(node:778) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'options' of undefined
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:91:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:83:58)
    at start (/app/index.js:109:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:778) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:778) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[14:01:40] INFO: Zigbee Herdsman debug logging enabled
[14:01:42] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.25.1-dev start
> node index.js
(node:862) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'options' of undefined
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:91:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:83:58)
    at start (/app/index.js:109:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:862) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:862) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Koenkk** [comment]
Are you using any external converter?

**Comment by allenrobberson** [comment]
Yes i am. 

![image](https://user-images.githubusercontent.com/67385929/171460514-581b962c-5900-42b7-9531-e3d053786279.png)

**Comment by Koenkk** [comment]
I don't think all external converters are removed: `at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)`, make sure to remove them all.

**Comment by allenrobberson** [comment]
I have solved the problem by uninstalling and reinstalling
