### ISSUE TITLE
Home Assistant 2022.6.6@1.25.2 fails to start

### ISSUE THREAD

**Issue by Rodney-Smith** [Koenkk/zigbee2mqtt#12834]
### What happened?

Doesn't matter if it is 1.25.2 or Edge. They both produce the same error. Nothing changed other than updating Home Assistant and Zigbee2mqtt.

The error just repeats in the log over and over again.

### What did you expect to happen?

I expected zigbee2mqtt to work as it always has.

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

20211217

### Adapter

tubes_zb_gw_cc2652p2

### Debug log

[10:53:59] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.25.2 start
> node index.js
/app/node_modules/zigbee-herdsman-converters/index.js:91
        if (converter.options) {
                      ^
TypeError: Cannot read properties of undefined (reading 'options')
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:91:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:108:18)

**Comment by Rodney-Smith** [comment]
Updated to the latest firmware 20220219 with no change. z2m continues to loop with the error over and over.

**Comment by Rodney-Smith** [comment]
Thank you. Removing the external_converters section from the configuration.yaml file solved the problem.
