### ISSUE TITLE
device causing ver 1.25.2 to crash, when connected to coordinator

### ISSUE THREAD

**Issue by callacomp** [Koenkk/zigbee2mqtt#12898]
### What happened?

Systems been running smoothly for month (HassOS), updated to 1.25.2 (from .1), all seemed ok, it started, devices talking, then I noticed on Lovelace that they were going unavailable every few minutes. I rolled back to previous backup and all working again, left if a week or so, then tried upgrading again. All working but same issue. Been through failed to start stuff, permissions fine, changed to /dev/serial/by-id, etc same issue. Couldn't see anything in logs, enabled herdsman logs. Noticed one device issue, it's a Linkind ZS130000078 keypad. Turned it off, all working, turned it back on and crashes. I've now paired it to a plug rather than directly to the coordinator and it's working fine, not sure if this is related in any way to [this issue](https://github.com/Koenkk/zigbee2mqtt/issues/11681) (at some point I'll setup a sniffer). Somethings changed.

Logs [HERE](https://www.dropbox.com/s/kyktcidnpig9jkn/zig-herds.log?dl=0) when it's connected to coordinator

There is this in the logs, but it starts and devices talk
 zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'

### What did you expect to happen?

Just expected the system to work in the same way as 1.25.1

### How to reproduce it (minimal and precise)

roll back works fine. same issue second time install.

### Zigbee2MQTT version

1.25.2

### Adapter firmware version

20220103

### Adapter

usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Debug log

Point of failure
```
2022-06-21T00:35:10.148Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":205,"endpoint":1,"transid":15}

2022-06-21T00:35:10.148Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []

2022-06-21T00:35:10.149Z zigbee-herdsman:adapter:zStack:adapter Data confirm error (0x680ae2fffee56b41:64454,205,4)

2022-06-21T00:35:10.149Z zigbee-herdsman:controller:endpoint CommandResponse 0x680ae2fffee56b41/1 ssIasAce.panelStatusChanged({"panelstatus":0,"secondsremain":0,"audiblenotif":0,"alarmstatus":0}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))

Error: CommandResponse 0x680ae2fffee56b41/1 ssIasAce.panelStatusChanged({"panelstatus":0,"secondsremain":0,"audiblenotif":0,"alarmstatus":0}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))

    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:414:23)

    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)

[01:35:10] INFO: Zigbee Herdsman debug logging enabled

[01:35:11] INFO: Handing over control to Zigbee2mqtt Core ...

> zigbee2mqtt@1.25.2 start

> node index.js
Zigbee2MQTT:debug 2022-06-21 01:35:15: Loaded state from file /config/zigbee2mqtt/state.json

Zigbee2MQTT:info  2022-06-21 01:35:15: Logging to console and directory: '/config/zigbee2mqtt/log/2022-06-21.01-35-15' filename: log.txt

Zigbee2MQTT:debug 2022-06-21 01:35:15: Removing old log directory '/config/zigbee2mqtt/log/2022-06-21.01-29-48'

Zigbee2MQTT:info  2022-06-21 01:35:15: Starting Zigbee2MQTT version 1.25.2 (commit #unknown)

Zigbee2MQTT:info  2022-06-21 01:35:15: Starting zigbee-herdsman (0.14.34)

Zigbee2MQTT:debug 2022-06-21 01:35:15: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[20],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6755},"serialPort":{"adapter":"zstack","baudRate":115200,"path":"/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_e2d0e75caa29ec1193dbbf9c40c9ce8d-if00-port0","rtscts":false}}'

2022-06-21T00:35:15.584Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'

2022-06-21T00:35:15.586Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,14,0,2,4,6,8,10,12,14],"panID":6755,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[20]},"serialPort":{"baudRate":115200,"rtscts":false,"path":"/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_e2d0e75caa29ec1193dbbf9c40c9ce8d-if00-port0","adapter":"zstack"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'

2022-06-21T00:35:15.587Z zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_e2d0e75caa29ec1193dbbf9c40c9ce8d-if00-port0 and {"baudRate":115200,"rtscts":false,"autoOpen":false}

2022-06-21T00:35:15.597Z zigbee-herdsman:adapter:zStack:znp:log Serialport opened
```

**Comment by Koenkk** [comment]
@callacomp can you check if this has been fixed now?

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by Koenkk** [comment]
Cool, thanks for confirming!

**Comment by GSzabados** [comment]
@Koenkk, has this made to 1.26.0?

**Comment by Koenkk** [comment]
yes

**Comment by GSzabados** [comment]
Thanks for confirming, then I will roll to that one. Cheers!
