### ISSUE TITLE
Configuration is not consistent with adapter state/backup!

### ISSUE THREAD

**Issue by Gadzhi13** [Koenkk/zigbee2mqtt#13109]
### What happened?

Getting "Configuration is not consistent with adapter state/backup!" after a reboot of the host System.

Logs:
`
Zigbee2MQTT:debug 2022-07-12 01:09:34: Loaded state from file /app/data/state.json
Zigbee2MQTT:info  2022-07-12 01:09:34: Logging to console and directory: '/app/data/log/2022-07-12.01-09-34' filename: log.txt
Zigbee2MQTT:debug 2022-07-12 01:09:34: Removing old log directory '/app/data/log/2022-07-12.00-59-13'
Zigbee2MQTT:info  2022-07-12 01:09:34: Starting Zigbee2MQTT version 1.26.0 (commit #cd23aea)
Zigbee2MQTT:info  2022-07-12 01:09:34: Starting zigbee-herdsman (0.14.40)
Zigbee2MQTT:debug 2022-07-12 01:09:34: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyUSB0"}}'
Zigbee2MQTT:error 2022-07-12 01:09:34: Configuration is not consistent with adapter state/backup!
Zigbee2MQTT:error 2022-07-12 01:09:34: - PAN ID: configured=6754, adapter=6754
Zigbee2MQTT:error 2022-07-12 01:09:34: - Extended PAN ID: configured=00124b001cd4e838, adapter=00124b001cd4e838
Zigbee2MQTT:error 2022-07-12 01:09:34: - Network Key: configured=01030507090b0d0f00020406080a0c0d, adapter=01030507090b0d0f00020406080a0c0d
Zigbee2MQTT:error 2022-07-12 01:09:34: - Channel List: configured=11, adapter=11
Zigbee2MQTT:error 2022-07-12 01:09:34: Please update configuration to prevent further issues.
Zigbee2MQTT:error 2022-07-12 01:09:34: If you wish to re-commission your network, please remove coordinator backup at /app/data/coordinator_backup.json.
Zigbee2MQTT:error 2022-07-12 01:09:34: Re-commissioning your network will require re-pairing of all devices!
Zigbee2MQTT:error 2022-07-12 01:09:34: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-07-12 01:09:34: Failed to start zigbee
Zigbee2MQTT:error 2022-07-12 01:09:34: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-07-12 01:09:34: Exiting...
Zigbee2MQTT:error 2022-07-12 01:09:35: Error: startup failed - configuration-adapter mismatch - see logs above for more information
    at ZnpAdapterManager.determineStrategy (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:229:35)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:63:26)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:109:5)
`
    
Ubuntu Server, Z2M running in Docker, adapter recognized in bash. Tried changing Pan ID - no luck. Searched through the closed issues - only found those with mismatches in pan ids, etc. Mine seem to be all okay. Tried updating to 1.26.0 also no luck, was running 1.25.1 before.

Any way to fix it without reflashing the stick?

### Zigbee2MQTT version

1.26.0

### Adapter firmware version

Not starting

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

**Comment by Gadzhi13** [comment]
Found the root cause of the issue: had a separate instance of z2m still starting as a service. Turns out these kinds of issues are also coming when there are several processes trying to access the dongle. Similar issues with people running HA and accidentally installing ZHA.

For anyone having the same issues - try to find if there are any other z2m/zha/any other zigbee dongle consuming services running.
