### ISSUE TITLE
OSRAM	AC03642 SMART+ CLASSIC A 60 TW Bulb color_temp_startup unsupported feature

### ISSUE THREAD

**Issue by patoche83** [Koenkk/zigbee2mqtt#13154]
### What happened?

Set or Get color_temp_startup (Colour temperature after cold power on of this light) from the zigbee2mqtt Device UI reports an error. UNSUPPORTED_FEATURE. 

### What did you expect to happen?

To work since it is marked as supported. 
Setting color temp startup with Conbee 2 stick and Deconz add-on is working.

### How to reproduce it (minimal and precise)

click on any of the possible color temperature options to set the color temp at startup.
Using MQTT Explorer to set or get color_temp_startup does not work either.
Using remember_state: true payload seems to work however. as given in device's page 
[](https://www.zigbee2mqtt.io/devices/AC03642.html)
(https://www.zigbee2mqtt.io/devices/AC03642.html)

![Capture d’écran 2022-07-15 à 10 34 49](https://user-images.githubusercontent.com/16540453/179186106-b142b6f6-3a79-4339-8f52-9cb86c22e8c5.jpg)

### Zigbee2MQTT version

1.26.0-1

### Adapter firmware version

20211217

### Adapter

Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Debug log

debug 2022-07-15 10:35:05: Publishing 'set' 'color_temp_startup' to 'Light Couloir 1'
error 2022-07-15 10:35:05: Publish 'set' 'color_temp_startup' to 'Light Couloir 1' failed: 'Error: Write 0x7cb03eaa00af7fc4/3 lightingColorCtrl({"startUpColorTemperature":250}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
debug 2022-07-15 10:35:05: Error: Write 0x7cb03eaa00af7fc4/3 lightingColorCtrl({"startUpColorTemperature":250}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28)
    at Endpoint.write (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:397:22)
    at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:1009:13)
    at Publish.onMQTTMessage (/app/lib/extension/publish.ts:246:36)

**Comment by patoche83** [comment]
Same behavior as above  for a Lidl exterior light based on this Tuya device [](url) https://www.zigbee2mqtt.io/devices/TS0505A.html#tuya-ts0505a
