### ISSUE TITLE
After updating error related to extensions cause build failure (jszip

### ISSUE THREAD

**Issue by skinkie** [Koenkk/zigbee2mqtt#13310]
### What happened?

On master and dev, and the release npm run build causes the following errors;

```
> zigbee2mqtt@1.26.0-dev build
> tsc && node index.js writehash

lib/extension/bridge.ts:14:19 - error TS2307: Cannot find module 'jszip' or its corresponding type declarations.

14 import JSZip from 'jszip';
                     ~~~~~~~

lib/extension/bridge.ts:608:63 - error TS2341: Property 'meta' is private and only accessible within class 'Endpoint'.

608             for (const [key, data] of Object.entries(endpoint.meta?.scenes || {})) {
                                                                  ~~~~

lib/extension/otaUpdate.ts:129:88 - error TS2345: Argument of type '{ sendWhen: "active" | "immediate"; }' is not assignable to parameter of type 'Options'.
  Object literal may only specify known properties, and 'sendWhen' does not exist in type 'Options'.

129             const result = await endpoint.read('genBasic', ['dateCode', 'swBuildId'], {sendWhen});
                                                                                           ~~~~~~~~

lib/util/logger.ts:7:20 - error TS7016: Could not find a declaration file for module 'rimraf'. '/opt/zigbee2mqtt/node_modules/rimraf/rimraf.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/rimraf` if it exists or add a new declaration (.d.ts) file containing `declare module 'rimraf';`

7 import rimraf from 'rimraf';
                     ~~~~~~~~

lib/zigbee.ts:66:111 - error TS2339: Property 'reason' does not exist on type 'LastSeenChangedPayload'.

66             this.eventBus.emitLastSeenChanged({device: this.resolveDevice(data.device.ieeeAddr), reason: data.reason});
                                                                                                                 ~~~~~~

lib/zigbee.ts:187:30 - error TS2341: Property 'backup' is private and only accessible within class 'Controller'.

187         return this.herdsman.backup();
                                 ~~~~~~


Found 6 errors.
```

### What did you expect to happen?

I expected a working zigbee2mqtt installation.

### How to reproduce it (minimal and precise)

I am using raspbian, having;

nodejs is already the newest version (12.22.12~dfsg-1~deb11u1).
npm is already the newest version (7.5.2+ds-2).

### Zigbee2MQTT version

master

### Adapter firmware version

unknown

### Adapter

0451:16a8 Texas Instruments, Inc. CC2531 ZigBee

### Debug log

```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
1 info using npm@7.5.2
2 info using node@v12.22.12
3 timing config:load:defaults Completed in 10ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 11ms
5 timing config:load:builtin Completed in 12ms
6 timing config:load:cli Completed in 12ms
7 timing config:load:env Completed in 2ms
8 timing config:load:project Completed in 4ms
9 timing config:load:file:/opt/zigbee2mqtt/.npmrc Completed in 2ms
10 timing config:load:user Completed in 2ms
11 timing config:load:file:/etc/npmrc Completed in 2ms
12 timing config:load:global Completed in 2ms
13 timing config:load:cafile Completed in 2ms
14 timing config:load:validate Completed in 4ms
15 timing config:load:setUserAgent Completed in 3ms
16 timing config:load:setEnvs Completed in 6ms
17 timing config:load Completed in 63ms
18 verbose npm-session bca98ddcb9baa744
19 timing npm:load Completed in 123ms
20 timing command:run-script Completed in 57098ms
21 verbose stack Error: command failed
21 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
21 verbose stack     at ChildProcess.emit (events.js:314:20)
21 verbose stack     at maybeClose (internal/child_process.js:1022:16)
21 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
22 verbose pkgid zigbee2mqtt@1.26.0-dev
23 verbose cwd /opt/zigbee2mqtt
24 verbose Linux 5.10.63-v7+
25 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
26 verbose node v12.22.12
27 verbose npm  v7.5.2
28 error code 2
29 error path /opt/zigbee2mqtt
30 error command failed
31 error command sh -c tsc && node index.js writehash
32 verbose exit 2
```

**Comment by skinkie** [comment]
Issue was resolved via `npm i --save-dev @types/rimraf`
