### ISSUE TITLE
[New device support]: Connecte smart socket

### ISSUE THREAD

**Issue by gsolem** [Koenkk/zigbee2mqtt#13395]
### Link

https://en.connecte.no/stikkontakt-semi-flush

### Database entry

{"id":6,"type":"Router","ieeeAddr":"0x540f57fffecf6d79","nwkAddr":25083,"manufId":4098,"manufName":"_TZ3000_5ity3zyu","powerSource":"Mains (single phase)","modelId":"TS0121","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,3,5,4,6,1794,2820,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"modelId":"TS0121","manufacturerName":"_TZ3000_5ity3zyu","powerSource":1,"zclVersion":3,"appVersion":97,"stackVersion":0,"hwVersion":1,"dateCode":""}},"seMetering":{"attributes":{"divisor":100,"multiplier":1,"currentSummDelivered":[0,3]}},"haElectricalMeasurement":{"attributes":{"acVoltageMultiplier":1,"acVoltageDivisor":1,"acCurrentMultiplier":1,"acCurrentDivisor":1000,"acPowerMultiplier":1,"acPowerDivisor":1,"activePower":0,"rmsCurrent":0,"rmsVoltage":240}},"genOnOff":{"attributes":{"onOff":0,"tuyaBacklightMode":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff060ebd","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00212effff060ebd","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00212effff060ebd","endpointID":1},{"cluster":0,"type":"endpoint","deviceIeeeAddress":"0x00212effff060ebd","endpointID":1}],"configuredReportings":[{"cluster":1794,"attrId":0,"minRepIntval":5,"maxRepIntval":3600,"repChange":[1,1]}],"meta":{}}},"appVersion":97,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":821693351},"lastSeen":1659551884720,"defaultSendRequestWhen":"immediate"}

### Comments

Device shows up as Tuya TS0121 plug after pairing:

```
Zigbee Model                 TS0121
Zigbee Manufacturer     _TZ3000_5ity3zyu
```

From log after startup: 
`error 2022-08-03 20:02:23: Failed to configure '0x540f57fffecf6d79', attempt 1 (Error: Read 0x540f57fffecf6d79/1 genOnOff(["onOff","moesStartUpOnOff","tuyaBacklightMode"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28)
    at Endpoint.read (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:480:22)
    at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices/tuya.js:1882:13)
    at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:115:13)
    at Configure.start (/opt/zigbee2mqtt/lib/extension/configure.ts:68:13)
    at Controller.callExtensions (/opt/zigbee2mqtt/lib/controller.ts:315:17)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:154:9)
    at start (/opt/zigbee2mqtt/index.js:109:5))
`

All functionality seem to be there, but the socket is reporting extremely ofter (2-3 times a second) messages like this:

`info  2022-08-03 20:07:00: MQTT publish: topic 'zigbee2mqtt/0x540f57fffecf6d79', payload '{"current":0,"energy":0.03,"indicator_mode":"off","linkquality":255,"power":0,"power_outage_memory":null,"state":"OFF","voltage":238}'`

**Comment by gsolem** [comment]
Issue is still alive (not sure how to remove stale label).
