### ISSUE TITLE
[cc1352p-2] Can't connect to Raspberry pi 2

### ISSUE THREAD

**Issue by Calimerorulez** [Koenkk/zigbee2mqtt#13455]
### What happened?

Hi,

After digging around a couple of hours to solve the infamous:

`Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)`

I still can't connect my (flashed with the most recent FW) cc1352-p.
I've read the troubleshooting, user pi has access to the port:

`test -w /dev/serial/by-id/usb-Texas_Instruments_XDS110__03.00.00.20__Embed_with_CMSIS-DAP_L4300172-if00 && echo success || echo failure`

prints `success`.

Rights are correct:

`lrwxrwxrwx 1 root root 13 Aug  8 14:35 usb-Texas_Instruments_XDS110__03.00.00.20__Embed_with_CMSIS-DAP_L4300172-if00 -> ../../ttyACM0`

Zigbee2MQTT version is the latest (1.27), so I'm out of my options...

Can someone please help me?
Thanks :)

### What did you expect to happen?

Connect to the adapter.

### Zigbee2MQTT version

1.27

### Adapter firmware version

20220219

### Adapter

TI CC1352P-2

### Debug log

```
pi@kerberos:/opt/zigbee2mqtt $ npm start

> zigbee2mqtt@1.27.0 start
> node index.js

Zigbee2MQTT:info  2022-08-08 15:08:02: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2022-08-08.15-08-02' filename: log.txt
Zigbee2MQTT:info  2022-08-08 15:08:02: Starting Zigbee2MQTT version 1.27.0 (commit #a9b8808)
Zigbee2MQTT:info  2022-08-08 15:08:02: Starting zigbee-herdsman (0.14.46)
Zigbee2MQTT:error 2022-08-08 15:08:24: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-08-08 15:08:24: Failed to start zigbee
Zigbee2MQTT:error 2022-08-08 15:08:24: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-08-08 15:08:24: Exiting...
Zigbee2MQTT:error 2022-08-08 15:08:25: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:131:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:58:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:101:27)
    at start (/opt/zigbee2mqtt/index.js:109:5)
```

**Comment by Calimerorulez** [comment]
Little piece of configuration.yaml:

```
serial:
  # Location of CC2531 USB sniffer
  port: /dev/serial/by-id/usb-Texas_Instruments_XDS110__03.00.00.20__Embed_with_CMSIS-DAP_L4300172-if00
```

**Comment by Calimerorulez** [comment]
Ok, I finally managed to fix it myself, I had the TXD and RXD jumpers not shored on the board, because of an experiment in the past. After placing them, the adapter works :)
