### ISSUE TITLE
IKEA Starkvind connected but can't be controlled

### ISSUE THREAD

**Issue by OsiMood** [Koenkk/zigbee2mqtt#13558]
### What happened?

So today I switch my whole Zigbee devices from Deconz to zigbee2MQTT. the goal was to gain control of my newly acquired IKEA Air Purifier Starkvind.
Genral info:
 - Zigbee2MQTT as docker 
 - USB Deconz as /dev/ttyACM0
 - Integrated with Home Assistant 

When I pair my Starkvind, pairing seems successful but after a few seconds:
![image](https://user-images.githubusercontent.com/4088985/184724398-83d31091-de1e-4979-a9c9-5243ea61e17b.png)
and I can not push any action to it:
![image](https://user-images.githubusercontent.com/4088985/184724466-8b395a23-1570-4cfb-9913-4da43e542caf.png)

### Zigbee2MQTT version

1.27.0 commit: a9b8808

### Adapter firmware version

 1.0.033

### Adapter

ConBee2/RaspBee2

### Debug log

2022-08-15 23:53:15Failed to configure '0x540f57fffe1b47f4', attempt 2 (Error: Bind 0x540f57fffe1b47f4/1 manuSpecificIkeaAirPurifier from '0x00212effff04f71a/1' failed (waiting for response TIMEOUT) at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:764:19) at runMicrotasks (<anonymous>) at runNextTicks (node:internal/process/task_queues:61:5) at processTimers (node:internal/timers:499:9) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:567:13) at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:40:9) at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/ikea.js:862:13) at Configure.configure (/app/lib/extension/configure.ts:115:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:21))

**Comment by OsiMood** [comment]
For those having the same issue, I found the solution:
- Pair your Starkvind with Zigbee2MQTT
- 1st pairing will work but will not allow you to interact with the fan
- do NOT remove/unpair the fan
- re-put Zigbee2MQTT and Starkvind in pairing mode
- it seems the rest of the handshake will happen then and allow the device to be fully functional
