### ISSUE TITLE
Failed to pair LIDL HG06337

### ISSUE THREAD

**Issue by BoxedBrain** [Koenkk/zigbee2mqtt#13580]
### What happened?

I am unable to pair. The interview is failing.

### How to reproduce it (minimal and precise)

Try to pair (hold down the button 5s until the led starts blinking)

### Zigbee2MQTT version

 1.27.0-dev commit: 040d2a1

### Adapter firmware version

20210708

### Adapter

Sonoff 3.0 USB Dongle Plus

### Debug log

```Info 2022-08-17 14:59:21Device '0x60a423fffe0552fe' joined
Info 2022-08-17 14:59:21MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x60a423fffe0552fe","ieee_address":"0x60a423fffe0552fe"},"type":"device_joined"}'
Info 2022-08-17 14:59:21MQTT publish: topic 'homeassistant/switch/0x60a423fffe0552fe/switch/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/0x60a423fffe0552fe/set","device":{"identifiers":["zigbee2mqtt_0x60a423fffe0552fe"],"manufacturer":"Lidl","model":"Silvercrest smart plug (EU, CH, FR, BS, DK) (HG06337)","name":"0x60a423fffe0552fe"},"name":"0x60a423fffe0552fe","payload_off":"OFF","payload_on":"ON","state_topic":"zigbee2mqtt/0x60a423fffe0552fe","unique_id":"0x60a423fffe0552fe_switch_zigbee2mqtt","value_template":"{{ value_json.state }}"}'
Info 2022-08-17 14:59:21MQTT publish: topic 'homeassistant/sensor/0x60a423fffe0552fe/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x60a423fffe0552fe"],"manufacturer":"Lidl","model":"Silvercrest smart plug (EU, CH, FR, BS, DK) (HG06337)","name":"0x60a423fffe0552fe"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"0x60a423fffe0552fe linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x60a423fffe0552fe","unique_id":"0x60a423fffe0552fe_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Info 2022-08-17 14:59:21Starting interview of '0x60a423fffe0552fe'
Info 2022-08-17 14:59:21MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x60a423fffe0552fe","ieee_address":"0x60a423fffe0552fe","status":"started"},"type":"device_interview"}'
Debug 2022-08-17 14:59:21Received MQTT message on 'homeassistant/switch/0x60a423fffe0552fe/switch/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/0x60a423fffe0552fe/set","device":{"identifiers":["zigbee2mqtt_0x60a423fffe0552fe"],"manufacturer":"Lidl","model":"Silvercrest smart plug (EU, CH, FR, BS, DK) (HG06337)","name":"0x60a423fffe0552fe"},"name":"0x60a423fffe0552fe","payload_off":"OFF","payload_on":"ON","state_topic":"zigbee2mqtt/0x60a423fffe0552fe","unique_id":"0x60a423fffe0552fe_switch_zigbee2mqtt","value_template":"{{ value_json.state }}"}'
Debug 2022-08-17 14:59:21Received MQTT message on 'homeassistant/sensor/0x60a423fffe0552fe/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x60a423fffe0552fe"],"manufacturer":"Lidl","model":"Silvercrest smart plug (EU, CH, FR, BS, DK) (HG06337)","name":"0x60a423fffe0552fe"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"0x60a423fffe0552fe linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x60a423fffe0552fe","unique_id":"0x60a423fffe0552fe_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Debug 2022-08-17 14:59:29Device '0x60a423fffe0552fe' announced itself
Info 2022-08-17 14:59:29MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x60a423fffe0552fe","ieee_address":"0x60a423fffe0552fe"},"type":"device_announce"}'
Error 2022-08-17 15:00:05Failed to interview '0x60a423fffe0552fe', device has not successfully been paired
Info 2022-08-17 15:00:05MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x60a423fffe0552fe","ieee_address":"0x60a423fffe0552fe","status":"failed"},"type":"device_interview"}'```

**Comment by BoxedBrain** [comment]
After updating Coordinator Version to `20220219` the interview now completes.

But the device is still not working properly:

```
Debug 2022-08-17 16:02:16Received MQTT message on 'zigbee2mqtt/0x60a423fffe0552fe/set' with data '{"state":"OFF"}'
Debug 2022-08-17 16:02:16Publishing 'set' 'state' to '0x60a423fffe0552fe'
Debug 2022-08-17 16:02:27Received MQTT message on 'zigbee2mqtt/bridge/request/device/remove' with data '{"block":false,"force":false,"id":"0x60a423fffe0552fe","transaction":"v9fbh-2"}'
Info 2022-08-17 16:02:27Removing device '0x60a423fffe0552fe' (block: false, force: false)
Error 2022-08-17 16:02:39Publish 'set' 'state' to '0x60a423fffe0552fe' failed: 'Error: Command 0x60a423fffe0552fe/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 38727 - 1 - 16 - 6 - 11 after 10000ms)'
Debug 2022-08-17 16:02:39Error: Command 0x60a423fffe0552fe/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 38727 - 1 - 16 - 6 - 11 after 10000ms) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7)
Error 2022-08-17 16:02:49Request 'zigbee2mqtt/bridge/request/device/remove' failed with error: 'Failed to remove device '0x60a423fffe0552fe' (block: false, force: false) (Error: AREQ - ZDO - mgmtLeaveRsp after 10000ms)'
Debug 2022-08-17 16:02:50Error: Failed to remove device '0x60a423fffe0552fe' (block: false, force: false) (Error: AREQ - ZDO - mgmtLeaveRsp after 10000ms) at Bridge.removeEntity (/app/lib/extension/bridge.ts:563:19) at Bridge.onMQTTMessage (/app/lib/extension/bridge.ts:122:34)
Info 2022-08-17 16:02:50MQTT publish: topic 'zigbee2mqtt/bridge/response/device/remove', payload '{"data":{},"error":"Failed to remove device '0x60a423fffe0552fe' (block: false, force: false) (Error: AREQ - ZDO - mgmtLeaveRsp after 10000ms)","status":"error","transaction":"v9fbh-2"}'
Debug 2022-08-17 16:02:59Received MQTT message on 'zigbee2mqtt/bridge/request/device/remove' with data '{"block":false,"force":true,"id":"0x60a423fffe0552fe","transaction":"v9fbh-3"}'
Info 2022-08-17 16:02:59Removing device '0x60a423fffe0552fe' (block: false, force: true)
Debug 2022-08-17 16:02:59Clearing Home Assistant discovery topic for '0x60a423fffe0552fe'
Info 2022-08-17 16:02:59MQTT publish: topic 'homeassistant/switch/0x60a423fffe0552fe/switch/config', payload 'null'
Info 2022-08-17 16:02:59MQTT publish: topic 'homeassistant/sensor/0x60a423fffe0552fe/linkquality/config', payload 'null'
Info 2022-08-17 16:02:59MQTT publish: topic 'zigbee2mqtt/0x60a423fffe0552fe', payload ''
Info 2022-08-17 16:02:59Successfully removed device '0x60a423fffe0552fe' (block: false, force: true)
Info 2022-08-17 16:02:59MQTT publish: topic 'zigbee2mqtt/bridge/response/device/remove', payload '{"data":{"block":false,"force":true,"id":"0x60a423fffe0552fe"},"status":"ok","transaction":"v9fbh-3"}'
Debug 2022-08-17 16:02:59Received MQTT message on 'homeassistant/switch/0x60a423fffe0552fe/switch/config' with data ''
Debug 2022-08-17 16:02:59Received MQTT message on 'homeassistant/sensor/0x60a423fffe0552fe/linkquality/config' with data ''
Debug 2022-08-17 16:03:20Received MQTT message on 'zigbee2mqtt/bridge/request/permit_join' with data '{"device":null,"time":254,"transaction":"v9fbh-4","value":false}'
Info 2022-08-17 16:03:20Zigbee: disabling joining new devices.
Info 2022-08-17 16:03:20MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":false},"status":"ok","transaction":"v9fbh-4"}'
Debug 2022-08-17 16:03:23Received MQTT message on 'zigbee2mqtt/bridge/request/permit_join' with data '{"device":null,"time":254,"transaction":"v9fbh-5","value":true}'
Info 2022-08-17 16:03:23Zigbee: allowing new devices to join.
Info 2022-08-17 16:03:23MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"v9fbh-5"}'
Warning 2022-08-17 16:03:33Device '0x60a423fffe0552fe' left the network
Info 2022-08-17 16:03:33MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x60a423fffe0552fe","ieee_address":"0x60a423fffe0552fe"},"type":"device_leave"}'
Warning 2022-08-17 16:03:33Device '0x60a423fffe0552fe' left the network
Info 2022-08-17 16:03:33MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x60a423fffe0552fe","ieee_address":"0x60a423fffe0552fe"},"type":"device_leave"}'
Warning 2022-08-17 16:03:33Device '0x60a423fffe0552fe' left the network
Info 2022-08-17 16:03:33MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x60a423fffe0552fe","ieee_address":"0x60a423fffe0552fe"},"type":"device_leave"}'
Info 2022-08-17 16:03:36Device '0x60a423fffe0552fe' joined
Info 2022-08-17 16:03:36MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x60a423fffe0552fe","ieee_address":"0x60a423fffe0552fe"},"type":"device_joined"}'
Info 2022-08-17 16:03:36MQTT publish: topic 'homeassistant/switch/0x60a423fffe0552fe/switch/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/0x60a423fffe0552fe/set","device":{"identifiers":["zigbee2mqtt_0x60a423fffe0552fe"],"manufacturer":"Lidl","model":"Silvercrest smart plug (EU, CH, FR, BS, DK) (HG06337)","name":"0x60a423fffe0552fe"},"name":"0x60a423fffe0552fe","payload_off":"OFF","payload_on":"ON","state_topic":"zigbee2mqtt/0x60a423fffe0552fe","unique_id":"0x60a423fffe0552fe_switch_zigbee2mqtt","value_template":"{{ value_json.state }}"}'
Info 2022-08-17 16:03:36MQTT publish: topic 'homeassistant/sensor/0x60a423fffe0552fe/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x60a423fffe0552fe"],"manufacturer":"Lidl","model":"Silvercrest smart plug (EU, CH, FR, BS, DK) (HG06337)","name":"0x60a423fffe0552fe"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"0x60a423fffe0552fe linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x60a423fffe0552fe","unique_id":"0x60a423fffe0552fe_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Info 2022-08-17 16:03:37Starting interview of '0x60a423fffe0552fe'
Info 2022-08-17 16:03:37MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x60a423fffe0552fe","ieee_address":"0x60a423fffe0552fe","status":"started"},"type":"device_interview"}'
Debug 2022-08-17 16:03:37Received MQTT message on 'homeassistant/switch/0x60a423fffe0552fe/switch/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/0x60a423fffe0552fe/set","device":{"identifiers":["zigbee2mqtt_0x60a423fffe0552fe"],"manufacturer":"Lidl","model":"Silvercrest smart plug (EU, CH, FR, BS, DK) (HG06337)","name":"0x60a423fffe0552fe"},"name":"0x60a423fffe0552fe","payload_off":"OFF","payload_on":"ON","state_topic":"zigbee2mqtt/0x60a423fffe0552fe","unique_id":"0x60a423fffe0552fe_switch_zigbee2mqtt","value_template":"{{ value_json.state }}"}'
Debug 2022-08-17 16:03:37Received MQTT message on 'homeassistant/sensor/0x60a423fffe0552fe/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x60a423fffe0552fe"],"manufacturer":"Lidl","model":"Silvercrest smart plug (EU, CH, FR, BS, DK) (HG06337)","name":"0x60a423fffe0552fe"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"0x60a423fffe0552fe linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x60a423fffe0552fe","unique_id":"0x60a423fffe0552fe_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Debug 2022-08-17 16:03:50Device '0x60a423fffe0552fe' announced itself
Info 2022-08-17 16:03:50MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x60a423fffe0552fe","ieee_address":"0x60a423fffe0552fe"},"type":"device_announce"}'
Debug 2022-08-17 16:03:52Received Zigbee message from '0x60a423fffe0552fe', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"_TZ3000_kdi2o9m6","modelId":"TS011F"}' from endpoint 1 with groupID 0
Debug 2022-08-17 16:03:52Received Zigbee message from '0x60a423fffe0552fe', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 11 with groupID 0
Debug 2022-08-17 16:03:52Received Zigbee message from '0x60a423fffe0552fe', type 'readResponse', cluster 'genBasic', data '{"dateCode":""}' from endpoint 11 with groupID 0
Debug 2022-08-17 16:03:53Received Zigbee message from '0x60a423fffe0552fe', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 11 with groupID 0
Info 2022-08-17 16:03:53Successfully interviewed '0x60a423fffe0552fe', device has successfully been paired
Info 2022-08-17 16:03:53Device '0x60a423fffe0552fe' is supported, identified as: Lidl Silvercrest smart plug (EU, CH, FR, BS, DK) (HG06337)
Info 2022-08-17 16:03:53MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Silvercrest smart plug (EU, CH, FR, BS, DK)","exposes":[{"features":[{"access":7,"description":"On/off state of the switch","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"}],"type":"switch"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"HG06337","options":[],"supports_ota":false,"vendor":"Lidl"},"friendly_name":"0x60a423fffe0552fe","ieee_address":"0x60a423fffe0552fe","status":"successful","supported":true},"type":"device_interview"}'
Info 2022-08-17 16:03:53Configuring '0x60a423fffe0552fe'
Info 2022-08-17 16:03:53Successfully configured '0x60a423fffe0552fe'
```
