### ISSUE TITLE
1.27.2 fails to start when installed from NPM package registry

### ISSUE THREAD

**Issue by rcarmo** [Koenkk/zigbee2mqtt#13974]
### What happened?

I upgraded from 1.22.2 to 1.27.2 and when running `zigbee2mqtt` it fails with the following messages: 

```
web.1 | Zigbee2MQTT:error 2022-09-11 21:36:12: Failed to start zigbee
web.1 | Zigbee2MQTT:error 2022-09-11 21:36:12: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
web.1 | Zigbee2MQTT:error 2022-09-11 21:36:12: Exiting...
web.1 | Zigbee2MQTT:error 2022-09-11 21:36:12: Error: Cannot find module '/home/piku/.piku/envs/zigbee2mqtt/node_modules/zigbee2mqtt/node_modules/zigbee-herdsman/package.json'
```

I install `zigbee2mqtt` by using a `package.json` with this content: 

```json
{
  "dependencies": {
    "zigbee2mqtt": "1.27.2"
  },
  "description": "ZigBee Bridge",
  "name": "home.lan"
}
```

And running `npm install` automatically via a process manager ([piku](https://github.com/piku/piku), which I created). I have been doing this for a while and this is the first time installing `zigbee2mqtt` from NPM fails.

I am running Ubuntu 20.04.1 LTS on a Raspberry Pi 4 with NodeJS 14.x from node source. Several other JS apps are running on this box, installed in the same way, and reverting to 1.22.2 works.

### What did you expect to happen?

I expected herdsman and the like to be automatically deployed via NPM.

### How to reproduce it (minimal and precise)

Running `npm install zigbee2mqtt` on a separate user account and installing a second copy of 1.27.2 fails in the same way:

```
$ npm install zigbee2mqtt

> unix-dgram@2.0.4 install /home/ubuntu/node_modules/unix-dgram
> node-gyp rebuild

make: Entering directory '/home/ubuntu/node_modules/unix-dgram/build'
  CXX(target) Release/obj.target/unix_dgram/src/unix_dgram.o
In file included from ../../nan/nan.h:60,
                 from ../src/unix_dgram.cc:5:
/home/ubuntu/.cache/node-gyp/14.20.0/include/node/node.h:793:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  793 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/ubuntu/.cache/node-gyp/14.20.0/include/node/node.h:827:3: note: in expansion of macro ‘NODE_MODULE_X’
  827 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/unix_dgram.cc:404:1: note: in expansion of macro ‘NODE_MODULE’
  404 | NODE_MODULE(unix_dgram, Initialize)
      | ^~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/unix_dgram.node
  COPY Release/unix_dgram.node
make: Leaving directory '/home/ubuntu/node_modules/unix-dgram/build'

> @serialport/bindings@9.2.8 install /home/ubuntu/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install warn install No prebuilt binaries found (target=14.20.0 runtime=node arch=arm64 libc= platform=linux)
make: Entering directory '/home/ubuntu/node_modules/@serialport/bindings/build'
  CXX(target) Release/obj.target/bindings/src/serialport.o
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/serialport.cpp:78:69: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
   78 |   uv_queue_work(uv_default_loop(), req, EIO_Open, (uv_after_work_cb)EIO_AfterOpen);
      |                                                                     ^~~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Update(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/serialport.cpp:135:71: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  135 |   uv_queue_work(uv_default_loop(), req, EIO_Update, (uv_after_work_cb)EIO_AfterUpdate);
      |                                                                       ^~~~~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Close(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/serialport.cpp:175:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  175 |   uv_queue_work(uv_default_loop(), req, EIO_Close, (uv_after_work_cb)EIO_AfterClose);
      |                                                                      ^~~~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Flush(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/serialport.cpp:215:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  215 |   uv_queue_work(uv_default_loop(), req, EIO_Flush, (uv_after_work_cb)EIO_AfterFlush);
      |                                                                      ^~~~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/serialport.cpp:271:68: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  271 |   uv_queue_work(uv_default_loop(), req, EIO_Set, (uv_after_work_cb)EIO_AfterSet);
      |                                                                    ^~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Get(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/serialport.cpp:316:68: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  316 |   uv_queue_work(uv_default_loop(), req, EIO_Get, (uv_after_work_cb)EIO_AfterGet);
      |                                                                    ^~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE GetBaudRate(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/serialport.cpp:366:76: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  366 |   uv_queue_work(uv_default_loop(), req, EIO_GetBaudRate, (uv_after_work_cb)EIO_AfterGetBaudRate);
      |                                                                            ^~~~~~~~~~~~~~~~~~~~
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/serialport.cpp:412:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  412 |   uv_queue_work(uv_default_loop(), req, EIO_Drain, (uv_after_work_cb)EIO_AfterDrain);
      |                                                                      ^~~~~~~~~~~~~~
../src/serialport.cpp: At global scope:
../src/serialport.cpp:433:28: warning: unnecessary parentheses in declaration of ‘ToParityEnum’ [-Wparentheses]
  433 | SerialPortParity NAN_INLINE(ToParityEnum(const v8::Local<v8::String>& v8str)) {
      |                            ^
../src/serialport.cpp:452:30: warning: unnecessary parentheses in declaration of ‘ToStopBitEnum’ [-Wparentheses]
  452 | SerialPortStopBits NAN_INLINE(ToStopBitEnum(double stopBits)) {
      |                              ^
In file included from ../../../nan/nan.h:60,
                 from ../src/./serialport.h:13,
                 from ../src/serialport.cpp:1:
/home/ubuntu/.cache/node-gyp/14.20.0/include/node/node.h:793:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  793 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/ubuntu/.cache/node-gyp/14.20.0/include/node/node.h:827:3: note: in expansion of macro ‘NODE_MODULE_X’
  827 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/serialport.cpp:486:1: note: in expansion of macro ‘NODE_MODULE’
  486 | NODE_MODULE(serialport, init);
      | ^~~~~~~~~~~
  CXX(target) Release/obj.target/bindings/src/serialport_unix.o
../src/serialport_unix.cpp: In function ‘int setup(int, OpenBaton*)’:
../src/serialport_unix.cpp:179:82: warning: ‘%s’ directive output may be truncated writing up to 1023 bytes into a region of size 1005 [-Wformat-truncation=]
  179 |     snprintf(data->errorString, sizeof(data->errorString), "Error %s Cannot open %s", strerror(errno), data->path);
      |                                                                                  ^~
In file included from /usr/include/stdio.h:867,
                 from ../src/serialport.h:10,
                 from ../src/serialport_unix.cpp:2:
/usr/include/aarch64-linux-gnu/bits/stdio2.h:67:35: note: ‘__builtin___snprintf_chk’ output 20 or more bytes (assuming 1043) into a destination of size 1024
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/serialport_unix.cpp: In function ‘void EIO_Open(uv_work_t*)’:
../src/serialport_unix.cpp:89:84: warning: ‘%s’ directive output may be truncated writing up to 1023 bytes into a region of size 1003 [-Wformat-truncation=]
   89 |     snprintf(data->errorString, sizeof(data->errorString), "Error: %s, cannot open %s", strerror(errno), data->path);
      |                                                                                    ^~
In file included from /usr/include/stdio.h:867,
                 from ../src/serialport.h:10,
                 from ../src/serialport_unix.cpp:2:
/usr/include/aarch64-linux-gnu/bits/stdio2.h:67:35: note: ‘__builtin___snprintf_chk’ output 22 or more bytes (assuming 1045) into a destination of size 1024
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CXX(target) Release/obj.target/bindings/src/poller.o
  CXX(target) Release/obj.target/bindings/src/serialport_linux.o
  SOLINK_MODULE(target) Release/obj.target/bindings.node
  COPY Release/bindings.node
make: Leaving directory '/home/ubuntu/node_modules/@serialport/bindings/build'

> core-js@3.25.1 postinstall /home/ubuntu/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js:
> https://opencollective.com/core-js 
> https://patreon.com/zloirock 
> bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN saveError ENOENT: no such file or directory, open '/home/ubuntu/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/package.json'
npm WARN @rjsf/bootstrap-5@4.2.0 requires a peer of @rjsf/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @rjsf/bootstrap-5@4.2.0 requires a peer of react@>=16 but none is installed. You must install peer dependencies yourself.
npm WARN @rjsf/bootstrap-5@4.2.0 requires a peer of react-bootstrap@^2.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-icons@4.4.0 requires a peer of react@* but none is installed. You must install peer dependencies yourself.
npm WARN ubuntu No description
npm WARN ubuntu No repository field.
npm WARN ubuntu No README data
npm WARN ubuntu No license field.

+ zigbee2mqtt@1.27.2
added 214 packages from 226 contributors and audited 214 packages in 62.034s

25 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ tee .z2m/configuration.yaml
<my config>
$ node node_modules/zigbee2mqtt/cli.js 
Zigbee2MQTT:error 2022-09-11 21:48:58: Failed to start zigbee
Zigbee2MQTT:error 2022-09-11 21:48:58: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-09-11 21:48:58: Exiting...
Zigbee2MQTT:error 2022-09-11 21:48:58: Error: Cannot find module '/home/ubuntu/node_modules/zigbee2mqtt/node_modules/zigbee-herdsman/package.json'
Require stack:
- /home/ubuntu/node_modules/zigbee2mqtt/dist/util/utils.js
- /home/ubuntu/node_modules/zigbee2mqtt/dist/util/settings.js
- /home/ubuntu/node_modules/zigbee2mqtt/index.js
- /home/ubuntu/node_modules/zigbee2mqtt/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at /home/ubuntu/node_modules/zigbee2mqtt/lib/util/utils.ts:80:25
    at Object.getDependencyVersion (/home/ubuntu/node_modules/zigbee2mqtt/lib/util/utils.ts:80:25)
    at Zigbee.start (/home/ubuntu/node_modules/zigbee2mqtt/lib/zigbee.ts:24:30)
    at Controller.start (/home/ubuntu/node_modules/zigbee2mqtt/lib/controller.ts:101:27)
    at start (/home/ubuntu/node_modules/zigbee2mqtt/index.js:109:5)
```

Doing the same for 1.22.2 works. I have not tested intermediate versions.

### Zigbee2MQTT version

1.27.2

### Adapter firmware version

N/A

### Adapter

N/A

### Debug log

N/A since it does not install, see terminal output above.

**Comment by rcarmo** [comment]
After a bit of testing, I've verified `1.25.2` works fine. Whatever broke, it was introduced sometime after that.

**Comment by rcarmo** [comment]
Hello there,

This is still an issue with 1.28. Is the project still being maintained?
