### ISSUE TITLE
Logging to /tmp

### ISSUE THREAD

**Issue by mikkel75** [Koenkk/zigbee2mqtt#1405]
Hi,

I have a problem directing log to /tmp/. I have changed the configuration file to include:

```
advanced:
  log_level: info
  log_directory: /tmp/zigbee2mqtt_%TIMESTAMP%

```

I get this error:

```
hac@hac:~/zigbee2mqtt$ npm start

> zigbee2mqtt@1.2.1 start /home/hac/zigbee2mqtt
> node index.js

  zigbee2mqtt:info 4/11/2019, 9:50:32 AM Logging to directory: '/tmp/zigbee2mqtt_2019-04-11.09-50-32'
/home/hac/zigbee2mqtt/node_modules/rimraf/rimraf.js:313
        throw er
        ^

Error: EACCES: permission denied, scandir '/tmp/systemd-private-3cfe12e41c004db2b6a86e28b8e33470-systemd-resolved.service-oSBYK4'
    at Object.readdirSync (fs.js:785:3)
    at rmkidsSync (/home/hac/zigbee2mqtt/node_modules/rimraf/rimraf.js:341:11)
    at rmdirSync (/home/hac/zigbee2mqtt/node_modules/rimraf/rimraf.js:334:7)
    at Function.rimrafSync [as sync] (/home/hac/zigbee2mqtt/node_modules/rimraf/rimraf.js:304:9)
    at directories.forEach (/home/hac/zigbee2mqtt/lib/util/logger.js:57:16)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/hac/zigbee2mqtt/lib/util/logger.js:55:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.2.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I can see the /tmp/zigbee2mqtt_2019-04-11.09-50-32 directory gets created but is empty.

Any suggestions?

/M

**Comment by BrunoZumba** [comment]
Dude, I spend the whole afternoon struggling with this "... rimraf/rimraf.js:313 throw er".

I just realized what the stupid thing I did.
After I installed zigbee2mqtt for the first time, i run "npm start" with sudo (sudo npm start).

So a LOG directory (/opt/zigbee2mqtt/data/log/2019-04-20.17-21-18/) was created as root:root. After that, everytime I tried to run "npm start" I got this error:

```
  zigbee2mqtt:info 4/20/2019, 5:43:43 PM Logging to directory: '/opt/zigbee2mqtt/data/log/2019-04-20.17-43-42'
/opt/zigbee2mqtt/node_modules/rimraf/rimraf.js:313
        throw er
        ^

Error: EACCES: permission denied, unlink '/opt/zigbee2mqtt/data/log/2019-04-20.17-21-18/log.txt'
    at Object.unlinkSync (fs.js:951:3)
    at rimrafSync (/opt/zigbee2mqtt/node_modules/rimraf/rimraf.js:306:17)
    at /opt/zigbee2mqtt/node_modules/rimraf/rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (/opt/zigbee2mqtt/node_modules/rimraf/rimraf.js:341:26)
    at rmdirSync (/opt/zigbee2mqtt/node_modules/rimraf/rimraf.js:334:7)
    at Function.rimrafSync [as sync] (/opt/zigbee2mqtt/node_modules/rimraf/rimraf.js:304:9)
    at directories.forEach (/opt/zigbee2mqtt/lib/util/logger.js:57:16)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/opt/zigbee2mqtt/lib/util/logger.js:55:17)
```


After I changed this directory ownership to "pi:pi", everything was correct.

So, based on this, I think your problem is related to the ownership of your directory: "/tmp/zigbee2mqtt_2019-04-11.09-50-32".

Hope It helps and hope you solve your problem.

Cheers
