### ISSUE TITLE
Git pull error during update zigbee2mqtt to version 1.28 after upgrading node-js to 16.17.1

### ISSUE THREAD

**Issue by Anjerlaan** [Koenkk/zigbee2mqtt#14496]
### What happened?

@Koenkk,

I wanted to update Z2M to 1.28 on my Raspberry Pi 3b+ with Buster
But it was never updated to 1.28 but stayed on 1.22.2 probably because the pi was still running node-js 12.22.9

Therefor I updated node-js to 16.17.1 succesfully and i also performed the npm rebuild action.

Then I re-tried to update Z2M to 1.28 but I got the error (also) shown in the debug log
```
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
```

I also run `git status` which is alo in the debug log

How can I solve this?

### Zigbee2MQTT version

1.28

### Adapter firmware version

CC2652R_coordinator_20220219.hex

### Adapter

ZZH

### Debug log

https://pastebin.com/4MXtsS6m

**Comment by Anjerlaan** [comment]
So after I performed:
```
git reset --hard HEAD
npm rebuild
sudo reboot
```
Z2M is back to 1.22.2

If I perfom the update to 1.28 I get the following error

```
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
```

Now if I run `npm start` the following error is shown:

pi@Domotica-Pi:/opt/zigbee2mqtt $ npm start

> zigbee2mqtt@1.28.0 start
> node index.js

```
Zigbee2MQTT:error 2022-10-15 15:35:21: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-10-15 15:35:21: Failed to start zigbee
Zigbee2MQTT:error 2022-10-15 15:35:21: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-10-15 15:35:21: Exiting...
Zigbee2MQTT:error 2022-10-15 15:35:21: Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
```

and Z2M is not working untill I run these commands again

```
git reset --hard HEAD
npm rebuild
sudo reboot
``` 

What is going wrong here?
