### ISSUE TITLE
Sengled E1C-NB7 smart plug fails to interview

### ISSUE THREAD

**Issue by phidauex** [Koenkk/zigbee2mqtt#14524]
### What happened?

Sengled [E1C-NB7](https://www.zigbee2mqtt.io/devices/E1C-NB7.html) paired to TubeZB POE coordinator (CC2652P). Pairing appears successful, but interview fails, and device is left connected but nonfunctional. Attempts to switch the device result in a timeout error. LQI value populates, but other field values are `null`.

Tried with two different recently purchased plugs, in a few locations, all less than 15' from the coordinator.

Checked channel energy levels, the selected channel (11) had the lowest energy levels in the range.

Aqara devices and a Sengled bulb are working normally on the network.

### What did you expect to happen?

Device would pair and interview, and then respond to switch commands normally.

### How to reproduce it (minimal and precise)

- Set Z2M to Pairing Allowed.
- Reset Sengled E1C-NB7 in proximity to the coordinator.
- After 5 purple flashes it will attempt to pair.
- After 3 purple flashes it is pairing.
- Z2M identifies the device.
- Interview fails.
- Device is left paired but nonfunctional.

### Zigbee2MQTT version

1.28

### Adapter firmware version

20220928

### Adapter

tubeszb-cc2652-poe-2022

### Debug log

```
2022-10-16T21:35:51.794Z zigbee-herdsman:controller:log Device '0xb0ce1814036bf443' joined
2022-10-16T21:35:51.794Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-16T21:35:51.794Z zigbee-herdsman:controller:log Device '0xb0ce1814036bf443' accepted by handler
2022-10-16T21:35:51.794Z zigbee-herdsman:controller:log Delete device '0xb0ce1814036bf443' joined, undeleting
Zigbee2MQTT:info  2022-10-16 15:35:51: Device '0xb0ce1814036bf443' joined
Zigbee2MQTT:info  2022-10-16 15:35:51: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xb0ce1814036bf443","ieee_address":"0xb0ce1814036bf443"},"type":"device_joined"}'
Zigbee2MQTT:info  2022-10-16 15:35:51: MQTT publish: topic 'homeassistant/switch/0xb0ce1814036bf443/switch/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"},{"topic":"zigbee2mqtt/0xb0ce1814036bf443/availability","value_template":"{{ value_json.state }}"}],"availability_mode":"all","command_topic":"zigbee2mqtt/0xb0ce1814036bf443/set","device":{"identifiers":["zigbee2mqtt_0xb0ce1814036bf443"],"manufacturer":"Sengled","model":"Smart plug with energy tracker (E1C-NB7)","name":"0xb0ce1814036bf443"},"name":"0xb0ce1814036bf443","payload_off":"OFF","payload_on":"ON","state_topic":"zigbee2mqtt/0xb0ce1814036bf443","unique_id":"0xb0ce1814036bf443_switch_zigbee2mqtt","value_template":"{{ value_json.state }}"}'
Zigbee2MQTT:info  2022-10-16 15:35:51: MQTT publish: topic 'homeassistant/sensor/0xb0ce1814036bf443/power/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"},{"topic":"zigbee2mqtt/0xb0ce1814036bf443/availability","value_template":"{{ value_json.state }}"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0xb0ce1814036bf443"],"manufacturer":"Sengled","model":"Smart plug with energy tracker (E1C-NB7)","name":"0xb0ce1814036bf443"},"device_class":"power","enabled_by_default":true,"entity_category":"diagnostic","name":"0xb0ce1814036bf443 power","state_class":"measurement","state_topic":"zigbee2mqtt/0xb0ce1814036bf443","unique_id":"0xb0ce1814036bf443_power_zigbee2mqtt","unit_of_measurement":"W","value_template":"{{ value_json.power }}"}'
Zigbee2MQTT:info  2022-10-16 15:35:51: MQTT publish: topic 'homeassistant/sensor/0xb0ce1814036bf443/energy/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"},{"topic":"zigbee2mqtt/0xb0ce1814036bf443/availability","value_template":"{{ value_json.state }}"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0xb0ce1814036bf443"],"manufacturer":"Sengled","model":"Smart plug with energy tracker (E1C-NB7)","name":"0xb0ce1814036bf443"},"device_class":"energy","enabled_by_default":true,"name":"0xb0ce1814036bf443 energy","state_class":"total_increasing","state_topic":"zigbee2mqtt/0xb0ce1814036bf443","unique_id":"0xb0ce1814036bf443_energy_zigbee2mqtt","unit_of_measurement":"kWh","value_template":"{{ value_json.energy }}"}'
Zigbee2MQTT:info  2022-10-16 15:35:51: MQTT publish: topic 'homeassistant/sensor/0xb0ce1814036bf443/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"},{"topic":"zigbee2mqtt/0xb0ce1814036bf443/availability","value_template":"{{ value_json.state }}"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0xb0ce1814036bf443"],"manufacturer":"Sengled","model":"Smart plug with energy tracker (E1C-NB7)","name":"0xb0ce1814036bf443"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"0xb0ce1814036bf443 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0xb0ce1814036bf443","unique_id":"0xb0ce1814036bf443_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
2022-10-16T21:35:51.850Z zigbee-herdsman:controller:log Device '0xb0ce1814036bf443' is already in database with different networkAddress, updating networkAddress
2022-10-16T21:35:51.851Z zigbee-herdsman:controller:log Interview '0xb0ce1814036bf443' start
Zigbee2MQTT:info  2022-10-16 15:35:51: Starting interview of '0xb0ce1814036bf443'
2022-10-16T21:35:51.879Z zigbee-herdsman:controller:device:log Interview - start device '0xb0ce1814036bf443'
2022-10-16T21:35:51.879Z zigbee-herdsman:controller:device:log Interview - skip node descriptor request for '0xb0ce1814036bf443', already got it
2022-10-16T21:35:51.879Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - activeEpReq - {"dstaddr":16805,"nwkaddrofinterest":16805}
2022-10-16T21:35:51.879Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,5,165,65,165,65,36]
2022-10-16T21:35:51.880Z zigbee-herdsman:controller:log Device '0xb0ce1814036bf443' accepted by handler
2022-10-16T21:35:51.880Z zigbee-herdsman:controller:log Not interviewing '0xb0ce1814036bf443', completed 'false', in progress 'true'
Zigbee2MQTT:info  2022-10-16 15:35:51: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xb0ce1814036bf443","ieee_address":"0xb0ce1814036bf443","status":"started"},"type":"device_interview"}'
2022-10-16T21:35:51.942Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,5,0,97]
2022-10-16T21:35:51.942Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,5,0,97]
2022-10-16T21:35:51.942Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 5 - [0] - 97
2022-10-16T21:35:51.942Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - activeEpReq - {"status":0}
2022-10-16T21:35:51.942Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-16T21:35:52.048Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,13,69,193,165,65,165,65,67,244,107,3,20,24,206,176,142,170]
2022-10-16T21:35:52.048Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,13,69,193,165,65,165,65,67,244,107,3,20,24,206,176,142,170]
2022-10-16T21:35:52.048Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 13 - 2 - 5 - 193 - [165,65,165,65,67,244,107,3,20,24,206,176,142] - 170
2022-10-16T21:35:52.048Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - endDeviceAnnceInd - {"srcaddr":16805,"nwkaddr":16805,"ieeeaddr":"0xb0ce1814036bf443","capabilities":142}
2022-10-16T21:35:52.049Z zigbee-herdsman:controller:log Device announce '0xb0ce1814036bf443'
Zigbee2MQTT:info  2022-10-16 15:35:52: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xb0ce1814036bf443","ieee_address":"0xb0ce1814036bf443"},"type":"device_announce"}'
2022-10-16T21:35:52.079Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-16T21:35:54.822Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,7,69,196,165,65,2,251,207,166,184,74]
2022-10-16T21:35:54.822Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,7,69,196,165,65,2,251,207,166,184,74]
2022-10-16T21:35:54.822Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 7 - 2 - 5 - 196 - [165,65,2,251,207,166,184] - 74
2022-10-16T21:35:54.822Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - srcRtgInd - {"dstaddr":16805,"relaycount":2,"relaylist":[53243,47270]}
2022-10-16T21:35:54.822Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-16T21:35:55.110Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,7,69,196,165,65,2,251,207,166,184,74]
2022-10-16T21:35:55.110Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,7,69,196,165,65,2,251,207,166,184,74]
2022-10-16T21:35:55.111Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 7 - 2 - 5 - 196 - [165,65,2,251,207,166,184] - 74
2022-10-16T21:35:55.111Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - srcRtgInd - {"dstaddr":16805,"relaycount":2,"relaylist":[53243,47270]}
2022-10-16T21:35:55.111Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-16T21:35:56.299Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,5,69,196,180,45,1,166,184,2]
2022-10-16T21:35:56.299Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,5,69,196,180,45,1,166,184,2]
2022-10-16T21:35:56.299Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 5 - 2 - 5 - 196 - [180,45,1,166,184] - 2
2022-10-16T21:35:56.300Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - srcRtgInd - {"dstaddr":11700,"relaycount":1,"relaylist":[47270]}
2022-10-16T21:35:56.300Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-16T21:35:57.813Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,32,68,129,0,0,2,7,180,45,1,1,0,145,0,76,201,63,0,0,12,8,22,10,0,0,37,26,1,0,0,0,0,166,184,28,118]
2022-10-16T21:35:57.813Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,32,68,129,0,0,2,7,180,45,1,1,0,145,0,76,201,63,0,0,12,8,22,10,0,0,37,26,1,0,0,0,0,166,184,28,118]
2022-10-16T21:35:57.813Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 32 - 2 - 4 - 129 - [0,0,2,7,180,45,1,1,0,145,0,76,201,63,0,0,12,8,22,10,0,0,37,26,1,0,0,0,0,166,184,28] - 118
2022-10-16T21:35:57.813Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":1794,"srcaddr":11700,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":145,"securityuse":0,"timestamp":4180300,"transseqnumber":0,"len":12,"data":{"type":"Buffer","data":[8,22,10,0,0,37,26,1,0,0,0,0]}}
2022-10-16T21:35:57.814Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false,"reservedBits":0},"transactionSequenceNumber":22,"manufacturerCode":null,"commandIdentifier":10},"Payload":[{"attrId":0,"dataType":37,"attrData":[0,282]}],"Command":{"ID":10,"name":"report","parameters":[{"name":"attrId","type":33},{"name":"dataType","type":32},{"name":"attrData","type":1000}]}},"address":11700,"endpoint":1,"linkquality":145,"groupID":0,"wasBroadcast":false,"destinationEndpoint":1}'
2022-10-16T21:35:57.817Z zigbee-herdsman:controller:endpoint DefaultResponse 0xb0ce18140015be55/1 1794(10, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})
2022-10-16T21:35:57.817Z zigbee-herdsman:adapter:zStack:adapter sendZclFrameToEndpointInternal 0xb0ce18140015be55:11700/1 (0,0,2)
2022-10-16T21:35:57.817Z zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":11700,"destendpoint":1,"srcendpoint":1,"clusterid":1794,"transid":7,"options":0,"radius":30,"len":5,"data":{"type":"Buffer","data":[24,22,11,10,0]}}
2022-10-16T21:35:57.817Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,15,36,1,180,45,1,1,2,7,7,0,30,5,24,22,11,10,0,165]
2022-10-16T21:35:57.817Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-16T21:35:57.885Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,100,1,0,100,254,3,68,128,0,1,7,193]
2022-10-16T21:35:57.886Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,1,0,100,254,3,68,128,0,1,7,193]
2022-10-16T21:35:57.886Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 1 - [0] - 100
2022-10-16T21:35:57.886Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequest - {"status":0}
2022-10-16T21:35:57.886Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,0,1,7,193]
2022-10-16T21:35:57.886Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [0,1,7] - 193
2022-10-16T21:35:57.886Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":7}
2022-10-16T21:35:57.886Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-16T21:36:01.947Z zigbee-herdsman:controller:device:log Interview - active endpoints request failed for '0xb0ce1814036bf443', attempt 1
2022-10-16T21:36:01.948Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - activeEpReq - {"dstaddr":16805,"nwkaddrofinterest":16805}
2022-10-16T21:36:01.948Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,5,165,65,165,65,36]
2022-10-16T21:36:02.020Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,5,0,97]
2022-10-16T21:36:02.020Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,5,0,97]
2022-10-16T21:36:02.020Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 5 - [0] - 97
2022-10-16T21:36:02.021Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - activeEpReq - {"status":0}
2022-10-16T21:36:02.021Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-16T21:36:12.030Z zigbee-herdsman:controller:device:log Interview - active endpoints request failed for '0xb0ce1814036bf443', attempt 2
2022-10-16T21:36:12.030Z zigbee-herdsman:controller:device:log Interview - quirks check for 'E1C-NB7'-'sengled'-'Router'
2022-10-16T21:36:12.031Z zigbee-herdsman:controller:device:log Interview - quirks did not match
2022-10-16T21:36:12.031Z zigbee-herdsman:controller:device:log Interview - failed for device '0xb0ce1814036bf443' with error 'Error: Interview failed because can not get active endpoints ('0xb0ce1814036bf443')
    at Device.interviewInternal (/app/node_modules/zigbee-herdsman/src/controller/model/device.ts:596:19)
    at Device.interview (/app/node_modules/zigbee-herdsman/src/controller/model/device.ts:445:13)
    at Controller.onDeviceJoined (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:567:17)'
2022-10-16T21:36:12.032Z zigbee-herdsman:controller:error Interview failed for '0xb0ce1814036bf443 with error 'Error: Interview failed because can not get active endpoints ('0xb0ce1814036bf443')'
Zigbee2MQTT:error 2022-10-16 15:36:12: Failed to interview '0xb0ce1814036bf443', device has not successfully been paired
Zigbee2MQTT:info  2022-10-16 15:36:12: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xb0ce1814036bf443","ieee_address":"0xb0ce1814036bf443","status":"failed"},"type":"device_interview"}'
```

**Comment by jerrm** [comment]
I've got 6 of that model plug.   Just got two more last week. I haven't had any issue with pairing. 

Sonoff ZBDongle-P with coordinator version 20220103. 

I know that's not particularly helpful.  Just adding a data point.

**Comment by phidauex** [comment]
Thanks, that is a useful datapoint. Maybe I have a coordinator problem instead of a Z2M problem. At least this proves that the Z2M config file for the device works.

**Comment by jerrm** [comment]
It's zigbee - could be the phase of the moon.

**Comment by phidauex** [comment]
Well, despite the measurements, channel 11 seemed to be part of the problem. I moved to channel 25, and the two units were able to pair up, interview successfully, and now switch. They still do not report power or energy, but I'm going to leave them for a while and see if the network settles. Closing this issue for now, but I'll add any further troubleshooting tips for future searchers.
