### ISSUE TITLE
Stuck at Starting zigbee-herdsman with CC2651P

### ISSUE THREAD

**Issue by algovera** [Koenkk/zigbee2mqtt#14647]
### What happened?

Testing between different chips, everything was okay with efr32, and back to testing CC2652P and got stuck at
Starting zigbee-herdsman.

Switching back to erf32 stick works again, apparently I am not able to use CC2652P anymore.
I have one Sonoff ZBdongle-P and another ETH based hub using CC2652P.

Tried both methods here and still not working
https://www.zigbee2mqtt.io/guide/configuration/zigbee-network.html
https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html#error-coordinator-failed-to-start-probably-the-panid-is-already-in-use-try-a-different-panid-or-channel

**Config**
data_path: /config/z2m_zbdongle_p
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_e8a0b4b0401aec11bab874e5f01c6278-if00-port0
  adapter: zstack
permit_join: true
zigbee_herdsman_debug: true

### What did you expect to happen?

On returning to CC2652P, it should continue to work

### Zigbee2MQTT version

 1.28.0-1 

### Adapter firmware version

Unable to see find, but latest for ZBDongle-P

### Adapter

Sonoff ZBdongle-P, and another no brand from China, both  CC2651P

### Debug log

2022-10-26T02:44:03.990Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,19,1,0,113]
2022-10-26T02:44:03.990Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,19,1,0,113]
2022-10-26T02:44:03.990Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 19 - [1,0] - 113
2022-10-26T02:44:03.990Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvLength - {"length":1}
2022-10-26T02:44:03.990Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-26T02:44:03.990Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":99,"offset":0}
2022-10-26T02:44:03.990Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,99,0,0,0,90]
2022-10-26T02:44:04.003Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,97,28,0,1,0,127]
2022-10-26T02:44:04.003Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,97,28,0,1,0,127]
2022-10-26T02:44:04.003Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 3 - 1 - 28 - [0,1,0] - 127
2022-10-26T02:44:04.003Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":0,"len":1,"value":{"type":"Buffer","data":[0]}}
2022-10-26T02:44:04.003Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-26T02:44:04.004Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvLength - {"id":98}
2022-10-26T02:44:04.004Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,2,33,19,98,0,82]
2022-10-26T02:44:04.010Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,19,16,0,96]
2022-10-26T02:44:04.011Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,19,16,0,96]
2022-10-26T02:44:04.011Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 19 - [16,0] - 96
2022-10-26T02:44:04.011Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvLength - {"length":16}
2022-10-26T02:44:04.011Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-26T02:44:04.011Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":98,"offset":0}
2022-10-26T02:44:04.011Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,98,0,0,0,91]
2022-10-26T02:44:04.021Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,18,97,28,0,16,29,186,124,197,151,139,180,161,162,122,130,209,208,245,74,141,1]
2022-10-26T02:44:04.022Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,18,97,28,0,16,29,186,124,197,151,139,180,161,162,122,130,209,208,245,74,141,1]
2022-10-26T02:44:04.022Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 18 - 3 - 1 - 28 - [0,16,29,186,124,197,151,139,180,161,162,122,130,209,208,245,74,141] - 1
2022-10-26T02:44:04.022Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":0,"len":16,"value":{"type":"Buffer","data":[29,186,124,197,151,139,180,161,162,122,130,209,208,245,74,141]}}
2022-10-26T02:44:04.022Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-26T02:44:04.022Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvLength - {"id":98}
2022-10-26T02:44:04.022Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,2,33,19,98,0,82]
2022-10-26T02:44:04.029Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,19,16,0,96]
2022-10-26T02:44:04.033Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,19,16,0,96]
2022-10-26T02:44:04.033Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 19 - [16,0] - 96
2022-10-26T02:44:04.033Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvLength - {"length":16}
2022-10-26T02:44:04.033Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-26T02:44:04.034Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvWriteExt - {"id":98,"offset":0,"len":16,"value":{"type":"Buffer","data":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13]}}
2022-10-26T02:44:04.034Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,22,33,29,98,0,0,0,16,0,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13,91]
2022-10-26T02:44:04.043Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,97,29,0,125]
2022-10-26T02:44:04.043Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,97,29,0,125]
2022-10-26T02:44:04.044Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 1 - 29 - [0] - 125
2022-10-26T02:44:04.044Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvWriteExt - {"status":0}
2022-10-26T02:44:04.044Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-26T02:44:04.044Z zigbee-herdsman:adapter:zStack:startup:commissioning beginning network commissioning
2022-10-26T02:44:04.045Z zigbee-herdsman:adapter:zStack:znp:SREQ --> APP_CNF - bdbSetChannel - {"isPrimary":1,"channel":2048}
2022-10-26T02:44:04.045Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,47,8,1,0,8,0,0,43]
2022-10-26T02:44:04.051Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,111,8,0,102]
2022-10-26T02:44:04.051Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,111,8,0,102]
2022-10-26T02:44:04.051Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 15 - 8 - [0] - 102
2022-10-26T02:44:04.052Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- APP_CNF - bdbSetChannel - {"status":0}
2022-10-26T02:44:04.052Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-26T02:44:04.052Z zigbee-herdsman:adapter:zStack:znp:SREQ --> APP_CNF - bdbSetChannel - {"isPrimary":0,"channel":0}
2022-10-26T02:44:04.052Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,47,8,0,0,0,0,0,34]
2022-10-26T02:44:04.059Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,111,8,0,102]
2022-10-26T02:44:04.066Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,111,8,0,102]
2022-10-26T02:44:04.077Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 15 - 8 - [0] - 102
2022-10-26T02:44:04.077Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- APP_CNF - bdbSetChannel - {"status":0}
2022-10-26T02:44:04.077Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-26T02:44:04.078Z zigbee-herdsman:adapter:zStack:znp:SREQ --> APP_CNF - bdbStartCommissioning - {"mode":4}
2022-10-26T02:44:04.078Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,1,47,5,4,47]
2022-10-26T02:44:06.547Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,111,5,0,107,254,3,79,128,1,2,4,203]
2022-10-26T02:44:06.547Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,111,5,0,107,254,3,79,128,1,2,4,203]
2022-10-26T02:44:06.547Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 15 - 5 - [0] - 107
2022-10-26T02:44:06.547Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- APP_CNF - bdbStartCommissioning - {"status":0}
2022-10-26T02:44:06.548Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,79,128,1,2,4,203]
2022-10-26T02:44:06.548Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 15 - 128 - [1,2,4] - 203
2022-10-26T02:44:06.548Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- APP_CNF - bdbComissioningNotifcation - {"status":1}
2022-10-26T02:44:06.548Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-26T02:44:06.756Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,69,192,8,140]
2022-10-26T02:44:06.756Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,69,192,8,140]
2022-10-26T02:44:06.756Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 2 - 5 - 192 - [8] - 140
2022-10-26T02:44:06.756Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - stateChangeInd - {"state":8}
2022-10-26T02:44:06.756Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-26T02:44:07.324Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,69,192,8,140,254,3,79,128,8,2,0,198]
2022-10-26T02:44:07.325Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,69,192,8,140,254,3,79,128,8,2,0,198]
2022-10-26T02:44:07.325Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 2 - 5 - 192 - [8] - 140
2022-10-26T02:44:07.325Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - stateChangeInd - {"state":8}
2022-10-26T02:44:07.325Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,79,128,8,2,0,198]
2022-10-26T02:44:07.325Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 15 - 128 - [8,2,0] - 198
2022-10-26T02:44:07.325Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- APP_CNF - bdbComissioningNotifcation - {"status":8}
2022-10-26T02:44:07.325Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2022-10-26T02:44:07.909Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,69,192,0,132,254,3,79,128,8,2,0,198,254,3,79,128,8,2,0,198]
2022-10-26T02:44:07.909Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,69,192,0,132,254,3,79,128,8,2,0,198,254,3,79,128,8,2,0,198]
2022-10-26T02:44:07.909Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 2 - 5 - 192 - [0] - 132
2022-10-26T02:44:07.909Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - stateChangeInd - {"state":0}
2022-10-26T02:44:07.910Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,79,128,8,2,0,198,254,3,79,128,8,2,0,198]
2022-10-26T02:44:07.910Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 15 - 128 - [8,2,0] - 198
2022-10-26T02:44:07.910Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- APP_CNF - bdbComissioningNotifcation - {"status":8}
2022-10-26T02:44:07.910Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,79,128,8,2,0,198]
2022-10-26T02:44:07.910Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 15 - 128 - [8,2,0] - 198
2022-10-26T02:44:07.910Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- APP_CNF - bdbComissioningNotifcation - {"status":8}
2022-10-26T02:44:07.910Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
Zigbee2MQTT:error 2022-10-26 10:45:06: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-10-26 10:45:06: Failed to start zigbee
Zigbee2MQTT:error 2022-10-26 10:45:06: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-10-26 10:45:06: Exiting...
Zigbee2MQTT:error 2022-10-26 10:45:06: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:347:23)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:92:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:109:5)

**Comment by algovera** [comment]
Actually this is resolved after setting a high pan_id


https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html#error-coordinator-failed-to-start-probably-the-panid-is-already-in-use-try-a-different-panid-or-channel

**Comment by algovera** [comment]
Actually this is resolved after setting a high pan_id

https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html#error-coordinator-failed-to-start-probably-the-panid-is-already-in-use-try-a-different-panid-or-channel

**Comment by algovera** [comment]
let me try reflashing and see

**Comment by algovera** [comment]
tried re-flashing and still no luck
can anyone help?

**Comment by Glazzanz** [comment]
Ill add a unhelpful "me too" comment.
