### ISSUE TITLE
TubesZB Coordinator Resource temporarily unavailable Cannot lock port

### ISSUE THREAD

**Issue by OzGav** [Koenkk/zigbee2mqtt#14683]
### What happened?

This was working but as has happened before I did an HAOS upgrade but now Z2M wont start. This has happened before and then appeared to start working again after I downgraded the OS but that may have been coincidental as I have downgraded to HAOS 9.0 again but it is not working.

I have tried `port: /dev/serial/by-id/usb-1a86_TubesZB_971207DO-if00-port0` and `port: /dev/ttyUSB0`

 I have reviewed the troubleshooting here: https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html#error-resource-temporarily-unavailable-cannot-lock-port When I run the command listed there I get nothing:
![image](https://user-images.githubusercontent.com/19848947/198500896-5df898b0-2aa3-4c03-a648-9d3cb5ad844e.png)

If I plug my old CC2531 back in and change the port it works fine.

Here is some more info:
![image](https://user-images.githubusercontent.com/19848947/198501366-b9501d55-d0e7-4de6-9736-8060bec209be.png)

### Zigbee2MQTT version

1.22.0

### Adapter firmware version

Can't get it working to say for sure but it was shipped with the latest version

### Adapter

CC2652P2 based Zigbee to USB Coordinator

### Debug log

[09:31:06] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.0 start
> node index.js
Zigbee2MQTT:debug 2022-10-28 09:31:13: Loaded state from file /share/zigbee2mqtt/state.json
Zigbee2MQTT:info  2022-10-28 09:31:13: Logging to console and directory: '/share/zigbee2mqtt/log/2022-10-28.09-31-10' filename: log.txt
Zigbee2MQTT:debug 2022-10-28 09:31:13: Removing old log directory '/share/zigbee2mqtt/log/2022-10-28.09-25-20'
Zigbee2MQTT:info  2022-10-28 09:31:13: Starting Zigbee2MQTT version 1.22.0 (commit #unknown)
Zigbee2MQTT:info  2022-10-28 09:31:13: Starting zigbee-herdsman (0.13.164)
Zigbee2MQTT:debug 2022-10-28 09:31:13: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/share/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/share/zigbee2mqtt/database.db.backup","databasePath":"/share/zigbee2mqtt/database.db","network":{"channelList":[26],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/serial/by-id/usb-1a86_TubesZB_971207DO-if00-port0"}}'
Zigbee2MQTT:error 2022-10-28 09:31:13: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-10-28 09:31:13: Failed to start zigbee
Zigbee2MQTT:error 2022-10-28 09:31:13: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2022-10-28 09:31:13: Exiting...
Zigbee2MQTT:error 2022-10-28 09:31:13: Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[09:31:14] INFO: Handing over control to Zigbee2mqtt Core ...

**Comment by OzGav** [comment]
Actually looks like it was my Zwave stick. It changed to ttyusb1 but ZWAVE JS UI was still configured for ttyusb0 which the new coordinator wanted to use. So for anyeone in the future if nthere is nothing returned with the ls -l /proc... command then have a think about what else in HA might have the port.
