### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'options')

### ISSUE THREAD

**Issue by misterflop** [Koenkk/zigbee2mqtt#14765]
### What happened?

After the last upgrade 1.28.1-1, Zigbee2MQTT is not starting anymore.

I didn't test with dev branch, but I saw that the release was 4 hours ago.

The log displays this error:

[00:17:21] INFO: Preparing to start...
[00:17:22] INFO: Socat not enabled
[00:17:24] INFO: Starting Zigbee2MQTT...
/app/node_modules/zigbee-herdsman-converters/index.js:91
        if (converter.options) {
                      ^
TypeError: Cannot read properties of undefined (reading 'options')
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:91:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:108:18)

### Zigbee2MQTT version

1.28.1-1

### Adapter firmware version

last

### Adapter

SONOFF ZigBee 3.0 USB Dongle Plus, TI CC2652P Coordinator

**Comment by misterflop** [comment]
Sorry, my fault, you added the support for TZE200_kds0pmmv and my external converter was not working anymore.
I removed it and everything is running fine now.
