### ISSUE TITLE
Schneider Electric - S520530W - None 'state' value returned

### ISSUE THREAD

**Issue by FrancoisGueguen8** [Koenkk/zigbee2mqtt#14774]
### What happened?

I’ve installed this relay switch in Z2M but it seems there is an issue about binding ‘state’ parameters. After a quick check into the source code (zigbee-herdsman-converters), there is maybe a wrong endpoint set into the corresponding function. 

- const endpoint = device.getEndpoint(10);
- await reporting.bind(endpoint, coordinatorEndpoint, ['genOnOff']);

Indeed, there is no such Endpoint 10 in my Z2M frontend (only 1, 21 and 242)

When i tried to reconfigure the device in the frontend, i’ve got this error message
info  2022-11-02 08:51:28: Configuring 'Odace'
error 2022-11-02 08:51:28: Failed to configure 'Odace', attempt 2 (TypeError: Cannot read properties of undefined (reading 'bind')
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:40:24)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/schneider_electric.js:427:29)
    at Configure.configure (/app/lib/extension/configure.ts:115:37)
    at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:32)
    at EventEmitter.emit (node:events:525:35)
    at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:109:22)
    at MQTT.onMessage (/app/lib/mqtt.ts:140:27)
    at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:94:27)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1178:20))

### What did you expect to happen?

The switch should be able to expose his state correctly and the physical button should be able to turn on/off entities in Z2M/HA
On MQTT:
Topic: zigbee2mqtt/Odace/get
I’ve tried to publish on this topic (via node-red) and there is no message coming back

### How to reproduce it (minimal and precise)

Topic: zigbee2mqtt/Odace/get
Payload: {"state": ""}
where Odace is the friendly name of the device

### Zigbee2MQTT version

1.28.1

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee Dongle cc2652 zStack3x0

### Debug log

info  2022-11-02 08:51:28: Configuring 'Odace'
error 2022-11-02 08:51:28: Failed to configure 'Odace', attempt 2 (TypeError: Cannot read properties of undefined (reading 'bind')
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:40:24)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/schneider_electric.js:427:29)
    at Configure.configure (/app/lib/extension/configure.ts:115:37)
    at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:32)
    at EventEmitter.emit (node:events:525:35)
    at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:109:22)
    at MQTT.onMessage (/app/lib/mqtt.ts:140:27)
    at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:94:27)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1178:20))

**Comment by FrancoisGueguen8** [comment]
I've just changed 'const endpoint = device.getEndpoint(10);' into 'const endpoint = device.getEndpoint(1);' (zigbee-herdsman-converters/devices/schneider_electric.js line 427)

And now the swicth is working correctly
