### ISSUE TITLE
UNSUPPORTED_ATTRIBUTE

### ISSUE THREAD

**Issue by mikeg-de** [Koenkk/zigbee2mqtt#15026]
### What happened?

Receiving regular errors in the GUI. The device is yet not integrated i.e. via Node-Red so I can't say with certainty if these are false positives or not.

https://www.amazon.de/gp/product/B09TW36J98/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

Device type: Router
Zigbee Model: TS011F
Zigbee Manufacturer: _TZ3000_cfnprab5
Description: 4 gang switch, with USB
Firmware build date: 20210625
Firmware version: 202+TZZSW25SL102
Manufacturer: [UseeLink](https://www.zigbee2mqtt.io/supported-devices/#v=UseeLink)
Model: [SM-0306E-2W](https://www.zigbee2mqtt.io/devices/SM-0306E-2W.html#useelink-sm-0306e-2w)

### What did you expect to happen?

No error to be thrown

### How to reproduce it (minimal and precise)

Just power on and pair the device

### Zigbee2MQTT version

1.28.2

### Adapter firmware version

20220219

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus, TI CC2652P + CP2102(N)

### Debug log

error 2022-11-16 15:58:57Failed to configure 'Küche Steckdosenleiste', attempt 2 (Error: Read 0x70b3d52b60012032/1 genBasic(["manufacturerName","zclVersion","appVersion","modelId","powerSource",65534], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28) at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:480:22) at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/useelink.js:35:13) at Configure.configure (/app/lib/extension/configure.ts:115:13))

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
