### ISSUE TITLE
Devices not available in zigbee2mqtt

### ISSUE THREAD

**Issue by RogerSero** [Koenkk/zigbee2mqtt#15049]
### What happened?

It seems that zigbee2mqtt works, but the devices become unavailable. You restart is complement, but some time passes and it happens again.

### What did you expect to happen?

I hope everything works fine, this has been happening for a month, before everything worked without problems.

### How to reproduce it (minimal and precise)

After restarting the plugin, some time passes and it happens again (hours).

### Zigbee2MQTT version

1.28.2-1

### Adapter firmware version

6.7.8.0 build 373

### Adapter

sonoff zbridge with tasmota firmware

### Debug log

2022-11-17T08:48:02.132Z zigbee-herdsman:adapter:ezsp:uart --> DATA (4,1,0): 9c00017e00929b35feff142e8401
2022-11-17T08:48:02.133Z zigbee-herdsman:adapter:ezsp:uart --> [41de21a92a2a87296c6ab53184d19310217e]
2022-11-17T08:48:02.134Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (5)
2022-11-17T08:48:03.134Z zigbee-herdsman:adapter:ezsp:uart -!- break waiting (5)
2022-11-17T08:48:03.135Z zigbee-herdsman:adapter:ezsp:uart Can't send DATA frame (4,1,0): 9c00017e00929b35feff142e8401
2022-11-17T08:48:03.135Z zigbee-herdsman:adapter:ezsp:uart ->> DATA (4,1,1): 9c00017e00929b35feff142e8401
2022-11-17T08:48:03.136Z zigbee-herdsman:adapter:ezsp:uart --> [49de21a92a2a87296c6ab53184d19337647e]
2022-11-17T08:48:03.136Z zigbee-herdsman:adapter:ezsp:uart -?- rewaiting (5)
2022-11-17T08:48:04.136Z zigbee-herdsman:adapter:ezsp:uart -!- break rewaiting (5)
2022-11-17T08:48:04.137Z zigbee-herdsman:adapter:ezsp:uart Can't resend DATA frame (4,1,1): 9c00017e00929b35feff142e8401
2022-11-17T08:48:04.140Z zigbee-herdsman:adapter:ezsp:erro Request error Error: Failure send setExtendedTimeout:{"type":"Buffer","data":[156,0,1,126,0,146,155,53,254,255,20,46,132,1]}: Error: Failure send setExtendedTimeout:{"type":"Buffer","data":[156,0,1,126,0,146,155,53,254,255,20,46,132,1]}
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:512:23
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)

**Comment by vignez2991** [comment]
Same issue with CC2652R using 20220219 firmware with Z2M version 1.28.2
