### ISSUE TITLE
Can't togle options/configuration (power_outage_memory) Aqara Smart Plug ZNCZ12LM

### ISSUE THREAD

**Issue by horspiste** [Koenkk/zigbee2mqtt#15111]
### What happened?

The Aqara has multiple configuration options (led_disabled_night,power_outage_memory,auto_off,overload_protection) and they are exposed properly in the "Expose" tab for the device. However when I try to configure them using the Zigbee2mqtt interface I get the following error: (for power_outage_memory). 

Publish 'set' 'power_outage_memory' to 'Prise Chauffe Eau' failed: 'Error: Write 0x00158d0008833818/1 aqaraOpple({"513":{"value":1,"type":16}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'

### How to reproduce it (minimal and precise)

Just click on the true/false switch on the expose tab for the device for any of the configurable options.

### Zigbee2MQTT version

1.28.2

### Adapter firmware version

20220219

### Adapter

tube_zb_gw_cc2652p2_version_2

### Debug log

 2022-11-20 22:09:12Received MQTT message on 'zigbee2mqtt/Prise Chauffe Eau/set' with data '{"power_outage_memory":true}'
Debug 2022-11-20 22:09:12Publishing 'set' 'power_outage_memory' to 'Prise Chauffe Eau'
Error 2022-11-20 22:09:12Publish 'set' 'power_outage_memory' to 'Prise Chauffe Eau' failed: 'Error: Write 0x00158d0008833818/1 aqaraOpple({"513":{"value":1,"type":16}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Debug 2022-11-20 22:09:12Error: Write 0x00158d0008833818/1 aqaraOpple({"513":{"value":1,"type":16}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28) at Endpoint.write (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:397:22) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:2214:17) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:246:36)

**Comment by horspiste** [comment]
I haven’t found a solution yet. On Dec 21, 2022, at 19:02, github-actions[bot] ***@***.***> wrote:﻿
This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 7 days

**Comment by ricerocketjockey** [comment]
I am also having this problem with the same plug.

`Zigbee2MQTT:error 2022-12-22 13:52:04: Publish 'set' 'power_outage_memory' to 'Power' failed: 'Error: Write 0x00158d0008833891/1 aqaraOpple({"513":{"value":1,"type":16}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'`

**Comment by DannyFeliz** [comment]
I have the same issue I also tried with the [mqtt explorer]([MQTT Explorer Addon](https://community.home-assistant.io/t/mqtt-explorer-addon/465758)) and got the same results.

**Comment by thekev** [comment]
Same issue here. I have a zigbee network capture of the error, but it may not be insightful. I have a sonoff hub coming today, and I'll work on capturing the vendor-specific interaction for the feature.

**Comment by thekev** [comment]
I was able to grab a capture. It looks more like the payload of the ZNCZ11LM. I was able to set it by moving `ZNCZ12LM` to line [2158](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/toZigbee.js#L2158) and the switch behaves as expected after power loss. Moving the getter still threw an unsupported attribute error. I didn't capture that transaction from the aqara hub though. I'm not able to put more time into it right now, but I may go for a pull request that covers the full coverage of options.

**Comment by victorstein** [comment]
@thekev is the hero we need not the one we deserve.

**Comment by smos08** [comment]
> I was able to grab a capture. It looks more like the payload of the ZNCZ11LM. I was able to set it by moving `ZNCZ12LM` to line [2158](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/toZigbee.js#L2158) and the switch behaves as expected after power loss. Moving the getter still threw an unsupported attribute error. I didn't capture that transaction from the aqara hub though. I'm not able to put more time into it right now, but I may go for a pull request that covers the full coverage of options.

that would be amazing, thank you

**Comment by handcoding** [comment]
@thekev Can anyone walk me through how to apply the fix that @thekev mentioned? I’m cursed with this same smart plug, and if I could just get the settings to stick, I think I’d be able to use this.

**Comment by hornet-dev** [comment]
I have the same issue, and am willing to help test any changes or provide additional info. Just let me know.

**Comment by DannyFeliz** [comment]
Bot, this issue still exists.

**Comment by handcoding** [comment]
Still present.

**Comment by asapkenzy** [comment]
this issue still exists.

**Comment by ravichowdhury88** [comment]
Is there a plan on getting this resolved ?

**Comment by Koenkk** [comment]
I've added the fix from @thekev , so this should be fixed now

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by thekev** [comment]
Thanks @Koenkk for patching that. I haven't had the will or free time to do a PR.

**Comment by smos08** [comment]
thank you @Koenkk from all of us users

**Comment by DannyFeliz** [comment]
@Koenkk thank you for fixing this 🙏🏻

**Comment by Koenkk** [comment]
Credits go the @thekev , I just integrated the change 😄 

I assume this issue can be closed now.
