### ISSUE TITLE
Innr SP 224 installed_version key raising TypeError in Home Assistant

### ISSUE THREAD

**Issue by RobertD502** [Koenkk/zigbee2mqtt#15290]
### What happened?

After updating to 1.28.3 and 1.28.4 (just now), one of my plugs (Innr SP 224) is causing a TypeError to be raised within Home Assistant.

Home Assistant Log attached below:

```
Logger: homeassistant.util.logging
Source: util/logging.py:168
First occurred: 2:25:14 PM (1 occurrences)
Last logged: 2:25:14 PM

Exception in handle_state_message_received when handling msg on 'zigbee/Kitchen Smart Plug': '{"last_seen":"2022-12-01T14:25:14-05:00","linkquality":72,"state":"ON","update":{"installed_version":"2.1","state":null},"update_available":null}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received if "installed_version" in json_payload: TypeError: argument of type 'float' is not iterable
```

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

20200925

### Adapter

Electrolama

**Comment by Koenkk** [comment]
Fixed by https://github.com/Koenkk/zigbee2mqtt/pull/15369

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
