### ISSUE TITLE
ThirdReality Devices keep reporting OTA update available even though they are up-to-date 

### ISSUE THREAD

**Issue by aatifk** [Koenkk/zigbee2mqtt#15373]
### What happened?

With the new OTA support added for a bunch of ThirdReality sensors and switches in the recent version, the sensors and switches update fine, but even after the update, a "Check for New Updates" results in the device reporting update available. Updating just installs the same firmware version again. In the attached image, the switches have 1.00.12 as the latest firmware, but you can see that one of them that I triggered the update check for for this example, shows an update available. 

![image](https://user-images.githubusercontent.com/115054989/205702049-efd4b686-3b4e-40c7-8ef6-1ed193a67311.png)

### What did you expect to happen?

When firmware is updated, rechecking for updates should not show update available again.

### How to reproduce it (minimal and precise)

Update the ThirdReality Device via OTA update. Once update is finished, do the "Check for New Updates" again and it will show an update is available even though it will just install the same firmware again.

### Zigbee2MQTT version

 1.28.4 commit: 52e545f

### Adapter firmware version

20221102

### Adapter

Sonoff USB Zigbee Dongle Type-P

**Comment by highincolorado** [comment]
I now have 6 Third Reality devices that show needing updates but are apparently at the latest version, also the version for the update just says “newer”.

**Comment by deviantintegral** [comment]
The "newer" bug is fixed in 1.29.0 (and 1.29.1) but I still see the firmware reporting as available even after applying them.

**Comment by stncttr908** [comment]
I am still having this issue as well on 1.29.2. Not a huge deal, just OCD because I like to keep my devices up to date. 💯

**Comment by jpoeppelman1** [comment]
Yeah, this is super confusing.  Hope they can get this resolved.

**Comment by NickM-27** [comment]
In my case it is showing a newer version (.18 instead of .12) however it goes through the update process and then the update is still not applied

**Comment by deviantintegral** [comment]
Still an issue.

**Comment by dronenb** [comment]
> In my case it is showing a newer version (.18 instead of .12) however it goes through the update process and then the update is still not applied

I was having this exact same issue, then I manually tried doing a "Check All" in the UI and it went away. The HA notifications about the updates went away also.

**Comment by Koenkk** [comment]
Can someone provide the debug log when checking for an update?

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

**Comment by deviantintegral** [comment]
Looks like an assertion fails:

```
Mar 18 19:18:59 zigbee2mqtt npm[100723]: Zigbee2MQTT:info  2023-03-18 19:18:59: Updating 'Fireplace' to latest firmware
Mar 18 19:19:01 zigbee2mqtt npm[100723]: Zigbee2MQTT:debug 2023-03-18 19:19:01: Received Zigbee message from 'Fireplace', type 'readResponse', cluster 'genBasic', data '{"swBuildId":"v1.00.12"}' from endpoint 1 with groupID 0
Mar 18 19:19:01 zigbee2mqtt npm[100723]: Zigbee2MQTT:info  2023-03-18 19:19:01: MQTT publish: topic 'zigbee2mqtt/Fireplace', payload '{"battery":null,"last_seen":"2023-03-18T23:19:01.687Z","linkquality":112,"state":"ON","update":{"installed_version":12,"latest_version":18,"state":"available"},"update_available":null,"voltage":2800}'
Mar 18 19:19:01 zigbee2mqtt npm[100723]: Zigbee2MQTT:debug 2023-03-18 19:19:01: Updating to latest '0x282c02bfffe91752' (3RSS009Z)
Mar 18 19:19:01 zigbee2mqtt npm[100723]: Zigbee2MQTT:debug 2023-03-18 19:19:01: Using endpoint '1'
Mar 18 19:19:03 zigbee2mqtt npm[100723]: Zigbee2MQTT:debug 2023-03-18 19:19:03: Received Zigbee message from 'Fireplace', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":12,"imageType":54181,"manufacturerCode":4659}' from endpoint 1 with groupID 0
Mar 18 19:19:03 zigbee2mqtt npm[100723]: Zigbee2MQTT:info  2023-03-18 19:19:03: MQTT publish: topic 'zigbee2mqtt/Fireplace', payload '{"battery":null,"last_seen":"2023-03-18T23:19:03.678Z","linkquality":112,"state":"ON","update":{"installed_version":12,"latest_version":18,"state":"available"},"update_available":null,"voltage":2800}'
Mar 18 19:19:03 zigbee2mqtt npm[100723]: Zigbee2MQTT:debug 2023-03-18 19:19:03: Got OTA request '{"fieldControl":0,"manufacturerCode":4659,"imageType":54181,"fileVersion":12}'
Mar 18 19:19:03 zigbee2mqtt npm[100723]: Zigbee2MQTT:debug 2023-03-18 19:19:03: ZigbeeOTA: downloaded main index
Mar 18 19:19:03 zigbee2mqtt npm[100723]: Zigbee2MQTT:debug 2023-03-18 19:19:03: getNewImage for '0x282c02bfffe91752', meta {"fileVersion":12,"fileSize":146322,"url":"https://tr-zha.s3.amazonaws.com/firmwares/SmartSwitchGen3_Zigbee_PROD_V12_v1.00.12.ota","sha512":"8149d94b41784a822cc412d867bc6d7f27893989715c57924460ee039e2bb3024b8edf124c9d52325dbe7fa0b230d5dff62de4ca87d46120ca6dc42ce6396194"}
Mar 18 19:19:04 zigbee2mqtt npm[100723]: Zigbee2MQTT:debug 2023-03-18 19:19:04: Update of 'Fireplace' failed (AssertionError [ERR_ASSERTION]: No new image available)
Mar 18 19:19:04 zigbee2mqtt npm[100723]: Zigbee2MQTT:info  2023-03-18 19:19:04: MQTT publish: topic 'zigbee2mqtt/Fireplace', payload '{"battery":null,"last_seen":"2023-03-18T23:19:03.678Z","linkquality":112,"state":"ON","update":{"installed_version":12,"latest_version":18,"state":"available"},"update_available":null,"voltage":2800}'
Mar 18 19:19:04 zigbee2mqtt npm[100723]: Zigbee2MQTT:info  2023-03-18 19:19:04: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"Fireplace"},"error":"Update of 'Fireplace' failed (No new image available)","status":"error","transaction":"sj398-1"}'
Mar 18 19:19:04 zigbee2mqtt npm[100723]: Zigbee2MQTT:error 2023-03-18 19:19:04: Update of 'Fireplace' failed (No new image available)
Mar 18 19:19:04 zigbee2mqtt npm[100723]: Zigbee2MQTT:debug 2023-03-18 19:19:04: AssertionError [ERR_ASSERTION]: No new image available
Mar 18 19:19:04 zigbee2mqtt npm[100723]:     at getNewImage (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/lib/ota/common.js:422:5)
Mar 18 19:19:04 zigbee2mqtt npm[100723]:     at runMicrotasks (<anonymous>)
Mar 18 19:19:04 zigbee2mqtt npm[100723]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Mar 18 19:19:04 zigbee2mqtt npm[100723]:     at Object.updateToLatest (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/lib/ota/common.js:282:19)
Mar 18 19:19:04 zigbee2mqtt npm[100723]:     at OTAUpdate.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/otaUpdate.ts:267:41
```

Here's what the OTA in the UI shows. Strangely, one shows no update while the other does:

<img width="1879" alt="image" src="https://user-images.githubusercontent.com/255023/226145146-68cbf8e9-1a38-4582-ac7e-de7c7e0dc25c.png">

**Comment by Koenkk** [comment]
Can you try to:
- stop z2m
- remove the `update` state from the device in `data/state.json`
- start z2m, and see if the issue re-appears again.

If it is fixed now, it was caused by an old z2m bug.

**Comment by jpoeppelman1** [comment]
> Can you try to:
> 
> * stop z2m
> * remove the `update` state from the device in `data/state.json`
> * start z2m, and see if the issue re-appears again.
> 
> If it is fixed now, it was caused by an old z2m bug.

I tried removing the update data from the state file and restart the docker container.  The app just added the update info back into the state json file.  It did not work.

**Comment by deviantintegral** [comment]
I also tried removing the update state, but it worked for me.

**Comment by coolspot18** [comment]
Is there a fix for this? Third Reality devices don't seem to update their firmware state after an update?

**Comment by mininja2131** [comment]
> Is there a fix for this? Third Reality devices don't seem to update their firmware state after an update?

same issue here.

**Comment by gcs8** [comment]
Same issue where the update is failing on the below.

`Firmware version
v1.00.72
Manufacturer
[Third Reality](https://www.zigbee2mqtt.io/supported-devices/#v=Third%20Reality)
Model
[3RSB015BZ](https://www.zigbee2mqtt.io/devices/3RSB015BZ.html#third%2520reality-3rsb015bz)`

**Comment by highincolorado** [comment]
Firmware 1.00.72 got installed on all my shades and ever since they drop off the network constantly. No help from Third Reality and no way I could find to go back to the previous version. Very frustrated. Well today they dropped 1.00.79, installing it now. Fingers are crossed.

**Comment by gcs8** [comment]
Let me know if you figure out the Konami code to get it to take the FW.

**Comment by highincolorado** [comment]
My updates both to 1.00.72 and now to 1.00.76 work. I’m sorry that I can no longer recall what I did last year to make it work but the comment about removing update might have been it. Sorry I don’t have more for you.

**Comment by gcs8** [comment]
Hmm, my Z2M is only about a month old right now. This is what I am seeing atm.

`info 2024-08-27 13:30:29z2m: Updating 'Front Door Blinds' to latest firmware`

`info 2024-08-27 13:30:35z2m: Update of 'Front Door Blinds' at 0.00%`

`info 2024-08-27 13:30:35z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Front Door Blinds', payload '{"battery":100,"linkquality":134,"position":0,"state":"CLOSE","update":{"installed_version":72,"latest_version":76,"progress":0,"state":"updating"},"update_available":null,"voltage":6200}'`

`info 2024-08-27 13:31:05z2m: Update of 'Front Door Blinds' at 0.11%, ≈ 540 minutes remaining`

`info 2024-08-27 13:31:05z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Front Door Blinds', payload '{"battery":100,"linkquality":145,"position":0,"state":"CLOSE","update":{"installed_version":72,"latest_version":76,"progress":0.11,"remaining":32380,"state":"updating"},"update_available":null,"voltage":6200}'`

`info 2024-08-27 13:31:35z2m: Update of 'Front Door Blinds' at 0.11%, ≈ 1014 minutes remaining`

`info 2024-08-27 13:31:35z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Front Door Blinds', payload '{"battery":100,"linkquality":145,"position":0,"state":"CLOSE","update":{"installed_version":72,"latest_version":76,"progress":0.11,"remaining":60856,"state":"updating"},"update_available":null,"voltage":6200}'`

`info 2024-08-27 13:31:40z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Front Door Blinds', payload '{"battery":100,"linkquality":142,"position":0,"state":"CLOSE","update":{"installed_version":72,"latest_version":76,"state":"available"},"update_available":null,"voltage":6200}'`

`info 2024-08-27 13:31:40z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"Front Door Blinds"},"error":"Update of 'Front Door Blinds' failed (Update failed with reason: 'ABORT')","status":"error","transaction":"zhnjc-1"}'`

`error 2024-08-27 13:31:40z2m: Update of 'Front Door Blinds' failed (Update failed with reason: 'ABORT')`

**Comment by gcs8** [comment]
Oh nice, randomly hit update this am and now I am on v1.00.76 for the blinds, I did see in the update notification in HA that it said it was from 2 hours ago? So, maybe someone touched something.

**Comment by pwsh** [comment]
This is still an issue on Zigbee2MQTT [2.8.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/2.8.0) at least with model [3RVS01031Z](https://www.zigbee2mqtt.io/devices/3RVS01031Z.html#third%2520reality-3rvs01031z)

Installed firmware version ID is [v1.00.55](https://github.com/Koenkk/zigbee-OTA/releases) which matches the latest from https://thirdreality.com/release_note/vibration-sensor/ released on 2025-01-16

I did stop z2m and remove the update code from state.json which was as follows. The installed_version and latest_version match up. There is no source listed though. My understanding is they have their list published at [https://tr-zha.s3.amazonaws.com/firmware.json](url)

```
    "0xffffb40e06038df4": {
        "battery": 83.5,
        "vibration": false,
        "tamper": false,
        "battery_low": false,
        "linkquality": 128,
        "voltage": 2900,
        "x_axis": 55,
        "y_axis": -970,
        "z_axis": -596,
        "update": {
            "state": "idle",
            "installed_version": 55,
            "latest_version": 55,
            "latest_source": null,
            "latest_release_notes": null
        }
    },
```

This is the messages coming in the logs with debug logging enabled

```
[2/26/2026, 9:01:26 AM] z2m: Updating 'Sump Pump Vibration' to latest firmware
[2/26/2026, 9:01:26 AM] zh:controller:device: No OTA upgrade image currently available for 0xffffb40e06038df4
[2/26/2026, 9:01:26 AM] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Sump Pump Vibration', payload '{"battery":83.5,"battery_low":false,"linkquality":164,"tamper":false,"update":{"installed_version":55,"latest_release_notes":null,"latest_source":null,"latest_version":55,"state":"idle"},"vibration":false,"voltage":2900,"x_axis":55,"y_axis":-970,"z_axis":-596}'
[2/26/2026, 9:01:26 AM] z2m: No OTA image currently available for 'Sump Pump Vibration'. Unscheduled.
[2/26/2026, 9:01:35 AM] z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Sump Pump Vibration', payload '{"battery":83.5,"battery_low":false,"linkquality":132,"tamper":false,"update":{"installed_version":55,"latest_release_notes":null,"latest_source":null,"latest_version":55,"state":"idle"},"vibration":false,"voltage":2900,"x_axis":55,"y_axis":-970,"z_axis":-596}'

```

I stopped z2m and added in the URLs into the update code

```
    "0xffffb40e06038df4": {
        "battery": 83.5,
        "vibration": false,
        "tamper": false,
        "battery_low": false,
        "linkquality": 128,
        "voltage": 2900,
        "x_axis": 55,
        "y_axis": -970,
        "z_axis": -596,
        "update": {
            "state": "idle",
            "installed_version": 55,
            "latest_version": 55,
            "latest_source": "https://tr-zha.s3.amazonaws.com/firmware/Vibrate_Sensor_PROD_OTA_V55_v1.00.55.ota",
            "latest_release_notes": "https://thirdreality.com/release_note/vibration-sensor/"
        }
    }
```

It picks that up on restart, but then changes to the URL under the github, then wipes that out when it matches the versions

```
[2026-02-26 09:31:25] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Sump Pump Vibration', payload '{"battery":83.5,"battery_low":false,"linkquality":128,"tamper":false,"update":{"installed_version":55,"latest_release_notes":"https://thirdreality.com/release_note/vibration-sensor/","latest_source":"https://tr-zha.s3.amazonaws.com/firmware/Vibrate_Sensor_PROD_OTA_V55_v1.00.55.ota","latest_version":55,"state":"idle"},"vibration":false,"voltage":2900,"x_axis":55,"y_axis":-970,"z_axis":-596}'

[2026-02-26 09:31:27] debug: 	zh:ember:ezsp: ezspIncomingMessageHandler: type=UNICAST apsFrame={"profileId":260,"clusterId":25,"sourceEndpoint":1,"destinationEndpoint":1,"options":320,"groupId":0,"sequence":172} packetInfo:{"senderShortId":12773,"senderLongId":"0xffffffffffffffff","bindingIndex":255,"addressIndex":255,"lastHopLqi":120,"lastHopRssi":-70,"lastHopTimestamp":0} messageContents=01ea01003312abd337000000
[2026-02-26 09:31:27] debug: 	zh:controller: Received payload: clusterID=25, address=12773, groupID=0, endpoint=1, destinationEndpoint=1, wasBroadcast=false, linkQuality=120, frame={"header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":false,"reservedBits":0},"transactionSequenceNumber":234,"commandIdentifier":1},"payload":{"fieldControl":0,"manufacturerCode":4659,"imageType":54187,"fileVersion":55},"command":{"ID":1,"response":2,"parameters":[{"name":"fieldControl","type":24},{"name":"manufacturerCode","type":33},{"name":"imageType","type":33,"max":65471},{"name":"fileVersion","type":35},{"name":"hardwareVersion","type":33,"conditions":[{"type":"bitMaskSet","param":"fieldControl","mask":1}]}],"required":true,"name":"queryNextImageRequest"}}
[2026-02-26 09:31:27] debug: 	z2m: Received Zigbee message from 'Sump Pump Vibration', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":55,"imageType":54187,"manufacturerCode":4659}' from endpoint 1 with groupID 0
[2026-02-26 09:31:27] debug: 	z2m: Device 'Sump Pump Vibration' requested OTA
[2026-02-26 09:31:27] info: 	z2m: Updating 'Sump Pump Vibration' to latest firmware
[2026-02-26 09:31:27] debug: 	zh:controller:device: Checking OTA 0xffffb40e06038df4 upgrade image availability, current={"fieldControl":0,"manufacturerCode":4659,"imageType":54187,"fileVersion":55}
[2026-02-26 09:31:27] debug: 	zh:controller:device: Getting image metadata for 0xffffb40e06038df4...
[2026-02-26 09:31:27] debug: 	zh:controller:device: OTA upgrade image availability for 0xffffb40e06038df4, available={"fileName":"Vibrate_Sensor_PROD_OTA_V55_v1.00.55.ota","fileVersion":55,"fileSize":132610,"url":"https://raw.githubusercontent.com/Koenkk/zigbee-OTA/master/images/ThirdReality/Vibrate_Sensor_PROD_OTA_V55_v1.00.55.ota","imageType":54187,"manufacturerCode":4659,"sha512":"5bd3a87405696100395e93f3f72a512f704c82a1c46775631a4497ffd847d822cb13fdb552213734bac2f46b60027f8939dd793283a2fec60a43e3717afeb502","otaHeaderString":"Telink OTA Sample Usage"}
[2026-02-26 09:31:27] info: 	zh:controller:device: No OTA upgrade image currently available for 0xffffb40e06038df4
[2026-02-26 09:31:27] debug: 	zh:controller:endpoint: CommandResponse 0xffffb40e06038df4/1 genOta.queryNextImageResponse({"status":152}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"reservedBits":0,"writeUndiv":false})
[2026-02-26 09:31:27] debug: 	zh:ember: ~~~> [ZCL to=0xffffb40e06038df4:12773 apsFrame={"profileId":260,"clusterId":25,"sourceEndpoint":1,"destinationEndpoint":1,"options":4352,"groupId":0,"sequence":0} header={"frameControl":{"reservedBits":0,"frameType":1,"direction":1,"disableDefaultResponse":true,"manufacturerSpecific":false},"transactionSequenceNumber":234,"commandIdentifier":2}]
[2026-02-26 09:31:27] debug: 	zh:ember:ezsp: ===> [FRAME: ID=52:"SEND_UNICAST" Seq=34 Len=25]
[2026-02-26 09:31:27] debug: 	zh:ember:uart:ash: ---> [FRAME type=DATA frmTx=2 frmRx=7](ackRx=2)
[2026-02-26 09:31:27] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2026-02-26 09:31:27] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=3](ackRx=2 frmTx=3)
[2026-02-26 09:31:27] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=3 frmNum=7](frmRx=7) Added to rxQueue
[2026-02-26 09:31:27] debug: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=0](ackRx=3)
[2026-02-26 09:31:27] debug: 	zh:ember:ezsp: <=== [FRAME: ID=52:"SEND_UNICAST" Seq=34 Len=7]
[2026-02-26 09:31:27] debug: 	zh:ember:ezsp: ~~~> [SENT type=DIRECT apsSequence=203 messageTag=1 status=OK]
[2026-02-26 09:31:27] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Sump Pump Vibration', payload '{"battery":83.5,"battery_low":false,"linkquality":120,"tamper":false,"update":{"installed_version":55,"latest_release_notes":null,"latest_source":null,"latest_version":55,"state":"idle"},"vibration":false,"voltage":2900,"x_axis":55,"y_axis":-970,"z_axis":-596}'
[2026-02-26 09:31:27] info: 	z2m: No OTA image currently available for 'Sump Pump Vibration'. Unscheduled.
[2026-02-26 09:31:27] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2026-02-26 09:31:27] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=3](ackRx=3 frmTx=3)
[2026-02-26 09:31:27] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=3 frmNum=0](frmRx=0) Added to rxQueue
[2026-02-26 09:31:27] debug: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=1](ackRx=3)
[2026-02-26 09:31:27] debug: 	zh:ember:ezsp: <=== [CBFRAME: ID=63:"MESSAGE_SENT_HANDLER" Seq=34 Len=22]
[2026-02-26 09:31:27] debug: 	zh:ember:ezsp: ezspMessageSentHandler: status=OK type=DIRECT indexOrDestination=12773 apsFrame={"profileId":260,"clusterId":25,"sourceEndpoint":1,"destinationEndpoint":1,"options":4352,"groupId":0,"sequence":203} messageTag=1
[2026-02-26 09:31:30] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2026-02-26 09:31:30] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=3](ackRx=3 frmTx=3)
[2026-02-26 09:31:30] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=3 frmNum=1](frmRx=1) Added to rxQueue
[2026-02-26 09:31:30] debug: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=2](ackRx=3)
[2026-02-26 09:31:30] debug: 	zh:ember:ezsp: <=== [CBFRAME: ID=69:"INCOMING_MESSAGE_HANDLER" Seq=34 Len=34]

```

Then we are back to requesting an update that doesn't exist

```
[2026-02-26 09:41:27] debug: 	z2m: Received Zigbee message from 'Sump Pump Vibration', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":55,"imageType":54187,"manufacturerCode":4659}' from endpoint 1 with groupID 0
[2026-02-26 09:41:27] debug: 	z2m: Device 'Sump Pump Vibration' requested OTA
[2026-02-26 09:41:27] info: 	z2m: Updating 'Sump Pump Vibration' to latest firmware
[2026-02-26 09:41:27] debug: 	zh:controller:device: Checking OTA 0xffffb40e06038df4 upgrade image availability, current={"fieldControl":0,"manufacturerCode":4659,"imageType":54187,"fileVersion":55}
[2026-02-26 09:41:27] debug: 	zh:controller:device: Getting image metadata for 0xffffb40e06038df4...
[2026-02-26 09:41:27] debug: 	zh:controller:device: OTA upgrade image availability for 0xffffb40e06038df4, available={"fileName":"Vibrate_Sensor_PROD_OTA_V55_v1.00.55.ota","fileVersion":55,"fileSize":132610,"url":"https://raw.githubusercontent.com/Koenkk/zigbee-OTA/master/images/ThirdReality/Vibrate_Sensor_PROD_OTA_V55_v1.00.55.ota","imageType":54187,"manufacturerCode":4659,"sha512":"5bd3a87405696100395e93f3f72a512f704c82a1c46775631a4497ffd847d822cb13fdb552213734bac2f46b60027f8939dd793283a2fec60a43e3717afeb502","otaHeaderString":"Telink OTA Sample Usage"}
[2026-02-26 09:41:27] info: 	zh:controller:device: No OTA upgrade image currently available for 0xffffb40e06038df4
[2026-02-26 09:41:27] debug: 	zh:controller:endpoint: CommandResponse 0xffffb40e06038df4/1 genOta.queryNextImageResponse({"status":152}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"reservedBits":0,"writeUndiv":false})
[2026-02-26 09:41:27] debug: 	zh:ember: ~~~> [ZCL to=0xffffb40e06038df4:12773 apsFrame={"profileId":260,"clusterId":25,"sourceEndpoint":1,"destinationEndpoint":1,"options":4352,"groupId":0,"sequence":0} header={"frameControl":{"reservedBits":0,"frameType":1,"direction":1,"disableDefaultResponse":true,"manufacturerSpecific":false},"transactionSequenceNumber":238,"commandIdentifier":2}]
[2026-02-26 09:41:27] debug: 	zh:ember:ezsp: ===> [FRAME: ID=52:"SEND_UNICAST" Seq=155 Len=25]
[2026-02-26 09:41:27] debug: 	zh:ember:uart:ash: ---> [FRAME type=DATA frmTx=3 frmRx=1](ackRx=3)
[2026-02-26 09:41:27] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2026-02-26 09:41:27] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=4](ackRx=3 frmTx=4)
[2026-02-26 09:41:27] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=4 frmNum=1](frmRx=1) Added to rxQueue
[2026-02-26 09:41:27] debug: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=2](ackRx=4)
[2026-02-26 09:41:27] debug: 	zh:ember:ezsp: <=== [FRAME: ID=52:"SEND_UNICAST" Seq=155 Len=7]
[2026-02-26 09:41:27] debug: 	zh:ember:ezsp: ~~~> [SENT type=DIRECT apsSequence=68 messageTag=122 status=OK]
[2026-02-26 09:41:27] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Sump Pump Vibration', payload '{"battery":83.5,"battery_low":false,"linkquality":124,"tamper":false,"update":{"installed_version":55,"latest_release_notes":null,"latest_source":null,"latest_version":55,"state":"idle"},"vibration":false,"voltage":2900,"x_axis":55,"y_axis":-970,"z_axis":-596}'
[2026-02-26 09:41:27] info: 	z2m: No OTA image currently available for 'Sump Pump Vibration'. Unscheduled.
```
```

[2026-02-26 09:46:28] debug: 	z2m: Received Zigbee message from 'Sump Pump Vibration', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":55,"imageType":54187,"manufacturerCode":4659}' from endpoint 1 with groupID 0
[2026-02-26 09:46:28] debug: 	z2m: Device 'Sump Pump Vibration' requested OTA
[2026-02-26 09:46:28] info: 	z2m: Updating 'Sump Pump Vibration' to latest firmware
[2026-02-26 09:46:28] debug: 	zh:controller:device: Checking OTA 0xffffb40e06038df4 upgrade image availability, current={"fieldControl":0,"manufacturerCode":4659,"imageType":54187,"fileVersion":55}
[2026-02-26 09:46:28] debug: 	zh:controller:device: Getting image metadata for 0xffffb40e06038df4...
[2026-02-26 09:46:28] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2026-02-26 09:46:28] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=3](ackRx=3 frmTx=3)
[2026-02-26 09:46:28] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=3 frmNum=6](frmRx=6) Added to rxQueue
[2026-02-26 09:46:28] debug: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=7](ackRx=3)
[2026-02-26 09:46:28] debug: 	zh:ember:ezsp: <=== [CBFRAME: ID=63:"MESSAGE_SENT_HANDLER" Seq=218 Len=22]
[2026-02-26 09:46:28] debug: 	zh:ember:ezsp: ezspMessageSentHandler: status=OK type=DIRECT indexOrDestination=7402 apsFrame={"profileId":260,"clusterId":10,"sourceEndpoint":1,"destinationEndpoint":1,"options":4352,"groupId":0,"sequence":131} messageTag=57
[2026-02-26 09:46:28] debug: 	zh:controller:device: OTA upgrade image availability for 0xffffb40e06038df4, available={"fileName":"Vibrate_Sensor_PROD_OTA_V55_v1.00.55.ota","fileVersion":55,"fileSize":132610,"url":"https://raw.githubusercontent.com/Koenkk/zigbee-OTA/master/images/ThirdReality/Vibrate_Sensor_PROD_OTA_V55_v1.00.55.ota","imageType":54187,"manufacturerCode":4659,"sha512":"5bd3a87405696100395e93f3f72a512f704c82a1c46775631a4497ffd847d822cb13fdb552213734bac2f46b60027f8939dd793283a2fec60a43e3717afeb502","otaHeaderString":"Telink OTA Sample Usage"}
[2026-02-26 09:46:28] info: 	zh:controller:device: No OTA upgrade image currently available for 0xffffb40e06038df4
[2026-02-26 09:46:28] debug: 	zh:controller:endpoint: CommandResponse 0xffffb40e06038df4/1 genOta.queryNextImageResponse({"status":152}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"reservedBits":0,"writeUndiv":false})
[2026-02-26 09:46:28] debug: 	zh:ember: ~~~> [ZCL to=0xffffb40e06038df4:12773 apsFrame={"profileId":260,"clusterId":25,"sourceEndpoint":1,"destinationEndpoint":1,"options":4352,"groupId":0,"sequence":0} header={"frameControl":{"reservedBits":0,"frameType":1,"direction":1,"disableDefaultResponse":true,"manufacturerSpecific":false},"transactionSequenceNumber":241,"commandIdentifier":2}]
[2026-02-26 09:46:28] debug: 	zh:ember:ezsp: ===> [FRAME: ID=52:"SEND_UNICAST" Seq=219 Len=25]
[2026-02-26 09:46:28] debug: 	zh:ember:uart:ash: ---> [FRAME type=DATA frmTx=3 frmRx=7](ackRx=3)
[2026-02-26 09:46:28] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2026-02-26 09:46:28] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=4](ackRx=3 frmTx=4)
[2026-02-26 09:46:28] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=4 frmNum=7](frmRx=7) Added to rxQueue
[2026-02-26 09:46:28] debug: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=0](ackRx=4)
[2026-02-26 09:46:28] debug: 	zh:ember:ezsp: <=== [FRAME: ID=52:"SEND_UNICAST" Seq=219 Len=7]
[2026-02-26 09:46:28] debug: 	zh:ember:ezsp: ~~~> [SENT type=DIRECT apsSequence=132 messageTag=58 status=OK]
[2026-02-26 09:46:28] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Sump Pump Vibration', payload '{"battery":83.5,"battery_low":false,"linkquality":128,"tamper":false,"update":{"installed_version":55,"latest_release_notes":null,"latest_source":null,"latest_version":55,"state":"idle"},"vibration":false,"voltage":2900,"x_axis":55,"y_axis":-970,"z_axis":-596}'
[2026-02-26 09:46:28] info: 	z2m: No OTA image currently available for 'Sump Pump Vibration'. Unscheduled.
```

From what I can gather, the otaUpdate.ts is where this is coming from, but its making that log event because the URL is empty.

[otaUpdate.ts](https://github.com/Koenkk/zigbee2mqtt/blob/b0b02c30b2e58c94043298c14848c90a0f74a24a/lib/extension/otaUpdate.ts#L107)

I haven't dug deep enough yet to figure out why its wiping out the URL after being populated though.
