### ISSUE TITLE
Netvox Z809A smart plug

### ISSUE THREAD

**Issue by clockbrain** [Koenkk/zigbee2mqtt#154]
I've partially added a netvox smart plug.

To restore to factory settings

Step1. Press and hold the Binding Key for 15 seconds. The network indicator will flash green 3 times 
(at the 3rd, the 10th, and the 15th second).

Step2. After releasing the Binding Key, press the Switch Key within 2 seconds. The network indicator
will rapidly flash green. Step3. After fast flashes, Z809A will reboot, and the restore is completed.

 with this devices.js entry

```
    {  
        zigbeeModel: ['Z809AE3R'],
        model: 'Z809AE3R',
        vendor: 'Netvox',
        description: 'Z809A ZigBee measurement and switch socket',
        supports: 'on/off, power measurement',
        fromZigbee: [fz.Z809AE3R_state],
        toZigbee: [tz.onoff],
   },
 ```

and this converter

```
   Z809AE3R_state: {
        cid: 'genOnOff',
        type: 'devChange',
        convert: (model, msg, publish, options) => {
            return {state: msg.data.data['onOff'] === 1 ? 'ON' : 'OFF'};
        },
    },
```

It certainly connects ok and I can switch it on or off via MQTT. I also get a message when it is manually switched however I have no idea how to configure the power measuring capability. Any suggestions on how to proceed?

**Comment by Koenkk** [comment]
Do you get any `WARN: No converter available` with:

```
    {
        zigbeeModel: ['Z809AE3R'],
        model: 'Z809AE3R',
        vendor: 'Netvox',
        description: 'Z809A ZigBee measurement and switch socket',
        supports: 'on/off, power measurement',
        fromZigbee: [fz.Z809AE3R_state],
        toZigbee: [tz.onoff],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 1);
            execute(device, [(cb) => device.report('haElectricalMeasurement', 'rmsVoltage', 10, 60, 1, cb)], callback);
        },
    },
```

**Comment by clockbrain** [comment]
@Koenkk Some progress in receiving the power measurement but it broke somewhere in the code.

```
2018-6-29 18:33:46 DEBUG Using zigbee-shepherd with settings: '{"net":{"panId":6754,"channelList":[11]},"dbPath":"/opt/zigbee2mqtt/data/database.db","sp":{"baudrate":115200,"rtscts":true}}'
2018-6-29 18:33:46 INFO Starting zigbee2mqtt version 0.0.0 (commit #2ba2864)
2018-6-29 18:33:46 INFO Starting zigbee-shepherd
2018-6-29 18:33:47 INFO zigbee-shepherd started
2018-6-29 18:33:47 INFO Currently 2 devices are joined:
2018-6-29 18:33:47 INFO Dimmer (0x0017880103cb42ce): 324131137411 - Philips Hue Dimmer Switch (EndDevice)
2018-6-29 18:33:47 INFO Garden floodlight (0x00137a0000040a80): Z809AE3R - Netvox Z809A ZigBee measurement and switch socket (Router)
2018-6-29 18:33:47 WARN `permit_join` set to  `true` in configuration.yaml.
2018-6-29 18:33:47 WARN Allowing new devices to join.
2018-6-29 18:33:47 WARN Set `permit_join` to `false` once you joined all devices.
2018-6-29 18:33:47 INFO Zigbee: allowing new devices to join.
2018-6-29 18:33:47 INFO Connecting to MQTT server at mqtt://192.168.x.x:1883
2018-6-29 18:33:47 INFO zigbee-shepherd ready
2018-6-29 18:33:47 INFO Connected to MQTT server
2018-6-29 18:33:47 INFO MQTT publish, topic: 'zigbee2mqtt/bridge/state', payload: 'online'
spinlock: false []
2018-6-29 18:33:47 INFO Succesfully configured 0x00137a0000040a80
2018-6-29 18:33:48 DEBUG Recieved zigbee message with data "0x00137a0000040a80"
2018-6-29 18:33:48 DEBUG Recieved zigbee message with data "0x00137a0000040a80"
2018-6-29 18:33:49 DEBUG Recieved zigbee message with data "0x00137a0000040a80"
2018-6-29 18:33:49 DEBUG Recieved zigbee message with data "0x00137a0000040a80"
2018-6-29 18:33:49 DEBUG Recieved zigbee message with data {"cid":"haElectricalMeasurement","data":{"rmsVoltage":242,"rmsCurrent":52,"activePower":9,"powerFactor":73}}
/opt/zigbee2mqtt/lib/controller.js:274
                return c.cid === cid && c.type === message.type;
                         ^

TypeError: Cannot read property 'cid' of undefined
    at mappedModel.fromZigbee.filter (/opt/zigbee2mqtt/lib/controller.js:274:26)
    at Array.filter (<anonymous>)
    at Controller.handleZigbeeMessage (/opt/zigbee2mqtt/lib/controller.js:272:51)
    at Zigbee.handleMessage (/opt/zigbee2mqtt/lib/zigbee.js:153:18)
    at emitOne (events.js:116:13)
    at ZShepherd.emit (events.js:211:7)
    at ZShepherd.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-shepherd/lib/shepherd.js:159:14)
    at emitThree (events.js:136:13)
    at ZShepherd.emit (events.js:217:7)
    at dispatchIncomingMsg (/opt/zigbee2mqtt/node_modules/zigbee-shepherd/lib/components/af.js:669:45)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@0.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-06-29T08_33_49_665Z-debug.log
```

**Comment by clockbrain** [comment]
@Koenkk My bad - works now. I had left out the converter when switching between different setups.

I now get 2 types of No converter available messages.

```
2018-6-29 21:35:18 DEBUG Recieved zigbee message with data {"cid":"haElectricalMeasurement","data":{"rmsVoltage":243,"rmsCurrent":0,"activePower":0,"powerFactor":0}}
2018-6-29 21:35:18 WARN No converter available for 'Z809AE3R' with cid 'haElectricalMeasurement' and type 'attReport'
2018-6-29 21:35:18 WARN Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices.
2018-6-29 21:35:18 DEBUG Recieved zigbee message with data {"cid":"haElectricalMeasurement","data":{"rmsVoltage":243}}
2018-6-29 21:35:18 WARN No converter available for 'Z809AE3R' with cid 'haElectricalMeasurement' and type 'devChange'
2018-6-29 21:35:18 WARN Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices.

```

**Comment by Koenkk** [comment]
I've added the devices/converters to the zigbee-shepherd-converters library. Can you check if everything works? To test:

```bash
cd node_modules
rm -rf zigbee-shepherd-converters
git clone https://github.com/Koenkk/zigbee-shepherd-converters.git -b Z809AE3R
cd zigbee-shepherd-converters
npm install
```

**Comment by clockbrain** [comment]
That patch works. I did notice a 'powerFactor' entry in the log file so by also adding this line to fromZigbee.js

```
                power_factor: msg.data.data['powerFactor'],
```

and this line to devices.js

```
                (cb) => device.report('haElectricalMeasurement', 'powerFactor', 10, 1000, 1, cb),
```

I now get good results

```
2018-6-30 09:03:27 INFO MQTT publish, topic: 'zigbee2mqtt/Garden floodlight', payload: '{"power":2,"current":14,"voltage":238,"power_factor":67}'
2018-6-30 09:03:27 DEBUG Recieved zigbee message with data {"cid":"haElectricalMeasurement","data":{"rmsVoltage":238,"powerFactor":67}}
2018-6-30 09:03:28 DEBUG Recieved zigbee message with data {"cid":"haElectricalMeasurement","data":{"rmsVoltage":238,"rmsCurrent":14,"activePower":2,"powerFactor":67}}
2018-6-30 09:03:28 INFO MQTT publish, topic: 'zigbee2mqtt/Garden floodlight', payload: '{"power":2,"current":14,"voltage":238,"power_factor":67}'
2018-6-30 09:03:29 DEBUG Recieved zigbee message with data {"cid":"haElectricalMeasurement","data":{"rmsVoltage":237,"rmsCurrent":14,"activePower":2,"powerFactor":66}}
2018-6-30 09:03:29 INFO MQTT publish, topic: 'zigbee2mqtt/Garden floodlight', payload: '{"power":2,"current":14,"voltage":237,"power_factor":66}'
2018-6-30 09:03:29 DEBUG Recieved zigbee message with data {"cid":"haElectricalMeasurement","data":{"rmsVoltage":237,"powerFactor":66}}
2018-6-30 09:03:30 DEBUG Recieved zigbee message with data {"cid":"haElectricalMeasurement","data":{"rmsVoltage":237,"rmsCurrent":14,"activePower":2,"powerFactor":66}}
2018-6-30 09:03:30 INFO MQTT publish, topic: 'zigbee2mqtt/Garden floodlight', payload: '{"power":2,"current":14,"voltage":237,"power_factor":66}'
2018-6-30 09:03:33 DEBUG Recieved mqtt message on topic 'zigbee2mqtt/Garden floodlight/set' with data '{ "state": "OFF" }'
2018-6-30 09:03:33 INFO Zigbee publish to '0x00137a0000040a80', genOnOff - off - {} - null
2018-6-30 09:03:33 INFO MQTT publish, topic: 'zigbee2mqtt/Garden floodlight', payload: '{"power":2,"current":14,"voltage":237,"power_factor":66,"state":"OFF"}'
```

thanks.

**Comment by Koenkk** [comment]
Device is officially supported now, thanks!
