### ISSUE TITLE
HA Yellow Coordinator connection dropping on 1.28.4-1

### ISSUE THREAD

**Issue by mdehaas** [Koenkk/zigbee2mqtt#15405]
### What happened?

After updating to Z2M 1.28.4-1 on my Home Assistant Yellow the networks stops processing commands regularly. Sometimes it takes an hour, sometimes is works for about 8 hours and anything in between. The devices are not reported as unavailable as Z2M seems to be working, just the adapter/chip seems cannot be locked. The problem is gone after downgrading/restoring backup to 1.28.2-1

Config in Add-on
```
port: /dev/ttyAMA1
adapter: ezsp
```
Config Items set in Z2M
Baud rate: 115200
RTS / CTS: On
[Source](https://yellow.home-assistant.io/yellow-v1.2-standard/)

I have about 88 devices in the network now.

### What did you expect to happen?

The communication should be stable. This is of course not a USB connected device but connected through UART. I'm not into hardware to that extend but considering the logging this may require a different treatment.

### How to reproduce it (minimal and precise)

For me is was upgrading from 1.28.2-1 to 1.28.4-1

### Zigbee2MQTT version

1.28.4-1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

HA Yellow 1.2 Silicon Labs MGM210P (EZSP v8)

### Debug log

```
2022-12-05T22:10:11.000Z zigbee-herdsman:adapter:ezsp:erro Reset error Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:90:28)
    at SerialPort._error (/app/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/@serialport/stream/lib/index.js:242:12
2022-12-05T22:10:11.001Z zigbee-herdsman:adapter:ezsp:driv Pause 60sec before try 62
2022-12-05T22:10:11.001Z zigbee-herdsman:adapter:ezsp:uart Opening SerialPort with /dev/ttyAMA1 and {"baudRate":115200,"rtscts":true,"autoOpen":false}
2022-12-05T22:10:11.004Z zigbee-herdsman:adapter:ezsp:erro Reset error Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:90:28)
    at SerialPort._error (/app/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/@serialport/stream/lib/index.js:242:12
2022-12-05T22:10:11.004Z zigbee-herdsman:adapter:ezsp:driv Pause 60sec before try 85
2022-12-05T22:10:11.057Z zigbee-herdsman:controller:endpoint Read 0xcc86ecfffe4ea2fa/1 haElectricalMeasurement(["rmsVoltage","rmsCurrent","activePower"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})
2022-12-05T22:10:11.058Z zigbee-herdsman:adapter:ezsp:debg sendZclFrameToEndpointInternal 0xcc86ecfffe4ea2fa:56889/1 (0,0,1)
2022-12-05T22:10:11.059Z zigbee-herdsman:adapter:ezsp:ezsp ==> setExtendedTimeout: {"remoteEui64":{"_value":{"type":"Buffer","data":[204,134,236,255,254,78,162,250]}},"extendedTimeout":true}
2022-12-05T22:10:11.060Z zigbee-herdsman:adapter:ezsp:erro Request error Error: Connection not initialized: Error: Connection not initialized
    at Ezsp.execCommand (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:505:19)
    at Driver.request (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:473:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:460:35)
2022-12-05T22:10:11.061Z zigbee-herdsman:controller:endpoint Read 0xcc86ecfffe4ea2fa/1 haElectricalMeasurement(["rmsVoltage","rmsCurrent","activePower"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)
2022-12-05T22:10:11.397Z zigbee-herdsman:adapter:ezsp:uart Opening SerialPort with /dev/ttyAMA1 and {"baudRate":115200,"rtscts":true,"autoOpen":false}
2022-12-05T22:10:11.399Z zigbee-herdsman:adapter:ezsp:erro Reset error Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:90:28)
    at SerialPort._error (/app/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/@serialport/stream/lib/index.js:242:12
2022-12-05T22:10:11.399Z zigbee-herdsman:adapter:ezsp:driv Pause 60sec before try 108
```

**Comment by mdehaas** [comment]
I have tested DEV today since there where new commits. Crashes with:
```
TypeError: Cannot read properties of undefined (reading 'makeZDOframe')
    at Driver.makeZDOframe (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:625:26)
    at Driver.zdoRequest (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:565:30)
    at EZSPAdapter.nodeDescriptorInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:373:46)
    at Object.func (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:363:43)
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:42)
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:39:22)
```

**Comment by mdehaas** [comment]
Tried latest DEV (1.29.0-dev commit: [4e40c82]) today. Still is stops responding. So I won't be upgrading to 1.29.x for the moment.

```
2023-01-01T16:01:40.164Z zigbee-herdsman:adapter:ezsp:erro Request error Error: Connection not initialized: Error: Connection not initialized
    at Ezsp.execCommand (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:505:19)
    at Driver.request (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:473:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:460:35)
2023-01-01T16:01:40.164Z zigbee-herdsman:controller:endpoint Read 0x84ba20fffe7c25ab/1 haElectricalMeasurement(["rmsVoltage","rmsCurrent","activePower"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)
2023-01-01T16:01:40.168Z zigbee-herdsman:controller:endpoint Read 0x84fd27fffe5f09f6/1 haElectricalMeasurement(["rmsVoltage","rmsCurrent","activePower"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})
2023-01-01T16:01:40.169Z zigbee-herdsman:adapter:ezsp:debg sendZclFrameToEndpointInternal 0x84fd27fffe5f09f6:27426/1 (0,0,1)
2023-01-01T16:01:40.169Z zigbee-herdsman:adapter:ezsp:ezsp ==> setExtendedTimeout: {"remoteEui64":{"_value":{"type":"Buffer","data":[132,253,39,255,254,95,9,246]}},"extendedTimeout":true}
2023-01-01T16:01:40.171Z zigbee-herdsman:adapter:ezsp:erro Request error Error: Connection not initialized: Error: Connection not initialized
    at Ezsp.execCommand (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:505:19)
    at Driver.request (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:473:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:460:35)
2023-01-01T16:01:40.171Z zigbee-herdsman:controller:endpoint Read 0x84fd27fffe5f09f6/1 haElectricalMeasurement(["rmsVoltage","rmsCurrent","activePower"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)
2023-01-01T16:01:40.175Z zigbee-herdsman:controller:endpoint Read 0x84fd27fffe5f0bac/1 haElectricalMeasurement(["rmsVoltage","rmsCurrent","activePower"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})
2023-01-01T16:01:40.175Z zigbee-herdsman:adapter:ezsp:debg sendZclFrameToEndpointInternal 0x84fd27fffe5f0bac:9139/1 (0,0,1)
2023-01-01T16:01:40.176Z zigbee-herdsman:adapter:ezsp:ezsp ==> setExtendedTimeout: {"remoteEui64":{"_value":{"type":"Buffer","data":[132,253,39,255,254,95,11,172]}},"extendedTimeout":true}
2023-01-01T16:01:40.177Z zigbee-herdsman:adapter:ezsp:erro Request error Error: Connection not initialized: Error: Connection not initialized
    at Ezsp.execCommand (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:505:19)
    at Driver.request (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:473:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:460:35)
2023-01-01T16:01:40.177Z zigbee-herdsman:controller:endpoint Read 0x84fd27fffe5f0bac/1 haElectricalMeasurement(["rmsVoltage","rmsCurrent","activePower"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)
2023-01-01T16:01:40.190Z zigbee-herdsman:adapter:ezsp:driv Reset connection. Try 18
2023-01-01T16:01:40.191Z zigbee-herdsman:adapter:ezsp:driv Stop driver
2023-01-01T16:01:40.191Z zigbee-herdsman:adapter:ezsp:ezsp Stop ezsp
2023-01-01T16:01:40.191Z zigbee-herdsman:adapter:ezsp:ezsp Close ezsp
2023-01-01T16:01:40.191Z zigbee-herdsman:adapter:ezsp:driv Close driver
2023-01-01T16:01:40.251Z zigbee-herdsman:controller:endpoint Read 0x540f57fffefdc21e/1 haElectricalMeasurement(["rmsVoltage","rmsCurrent","activePower"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})
2023-01-01T16:01:40.251Z zigbee-herdsman:adapter:ezsp:debg sendZclFrameToEndpointInternal 0x540f57fffefdc21e:14297/1 (0,0,1)
2023-01-01T16:01:40.254Z zigbee-herdsman:adapter:ezsp:erro Request error TypeError: Cannot read properties of undefined (reading 'ezspV'): TypeError: Cannot read properties of undefined (reading 'ezspV')
    at Driver.request (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:467:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:460:35)
2023-01-01T16:01:40.254Z zigbee-herdsman:controller:endpoint Read 0x540f57fffefdc21e/1 haElectricalMeasurement(["rmsVoltage","rmsCurrent","activePower"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)
2023-01-01T16:01:40.261Z zigbee-herdsman:controller:endpoint Read 0xcc86ecfffe35bd18/1 haElectricalMeasurement(["rmsVoltage","rmsCurrent","activePower"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})
2023-01-01T16:01:40.261Z zigbee-herdsman:adapter:ezsp:debg sendZclFrameToEndpointInternal 0xcc86ecfffe35bd18:36160/1 (0,0,1)
2023-01-01T16:01:40.263Z zigbee-herdsman:adapter:ezsp:erro Request error TypeError: Cannot read properties of undefined (reading 'ezspV'): TypeError: Cannot read properties of undefined (reading 'ezspV')
    at Driver.request (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:467:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:460:35)
2023-01-01T16:01:40.263Z zigbee-herdsman:controller:endpoint Read 0xcc86ecfffe35bd18/1 haElectricalMeasurement(["rmsVoltage","rmsCurrent","activePower"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)
2023-01-01T16:01:40.267Z zigbee-herdsman:controller:endpoint Read 0x84fd27fffe5f09e5/1 haElectricalMeasurement(["rmsVoltage","rmsCurrent","activePower"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})
2023-01-01T16:01:40.268Z zigbee-herdsman:adapter:ezsp:debg sendZclFrameToEndpointInternal 0x84fd27fffe5f09e5:11772/1 (0,0,1)
2023-01-01T16:01:40.269Z zigbee-herdsman:adapter:ezsp:erro Request error TypeError: Cannot read properties of undefined (reading 'ezspV'): TypeError: Cannot read properties of undefined (reading 'ezspV')
    at Driver.request (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:467:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:460:35)
2023-01-01T16:01:40.270Z zigbee-herdsman:controller:endpoint Read 0x84fd27fffe5f09e5/1 haElectricalMeasurement(["rmsVoltage","rmsCurrent","activePower"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)
2023-01-01T16:01:41.192Z zigbee-herdsman:adapter:ezsp:uart Opening SerialPort with {"path":"/dev/ttyAMA1","baudRate":115200,"rtscts":true,"autoOpen":false}
2023-01-01T16:01:41.196Z zigbee-herdsman:adapter:ezsp:erro Reset error Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:91:28)
    at SerialPort._error (/app/node_modules/@serialport/stream/dist/index.js:76:22)
    at /app/node_modules/@serialport/stream/dist/index.js:112:18
2023-01-01T16:01:41.197Z zigbee-herdsman:adapter:ezsp:driv Pause 60sec before try 19
2023-01-01T16:01:41.546Z zigbee-herdsman:adapter:ezsp:driv Reset connection. Try 9
2023-01-01T16:01:41.546Z zigbee-herdsman:adapter:ezsp:driv Stop driver
2023-01-01T16:01:41.546Z zigbee-herdsman:adapter:ezsp:ezsp Stop ezsp
2023-01-01T16:01:41.547Z zigbee-herdsman:adapter:ezsp:ezsp Close ezsp
2023-01-01T16:01:41.547Z zigbee-herdsman:adapter:ezsp:driv Close driver
2023-01-01T16:01:41.789Z zigbee-herdsman:controller:endpoint Read 0x84ba20fffe03775f/1 haElectricalMeasurement(["rmsVoltage","rmsCurrent","activePower"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})
2023-01-01T16:01:41.789Z zigbee-herdsman:adapter:ezsp:debg sendZclFrameToEndpointInternal 0x84ba20fffe03775f:51795/1 (0,0,1)
2023-01-01T16:01:41.791Z zigbee-herdsman:adapter:ezsp:erro Request error TypeError: Cannot read properties of undefined (reading 'ezspV'): TypeError: Cannot read properties of undefined (reading 'ezspV')
    at Driver.request (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:467:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:460:35)
2023-01-01T16:01:41.791Z zigbee-herdsman:controller:endpoint Read 0x84ba20fffe03775f/1 haElectricalMeasurement(["rmsVoltage","rmsCurrent","activePower"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)
2023-01-01T16:01:41.972Z zigbee-herdsman:adapter:ezsp:ezsp Time to watchdog ... 1
2023-01-01T16:01:41.972Z zigbee-herdsman:adapter:ezsp:ezsp ==> nop: null
2023-01-01T16:01:42.549Z zigbee-herdsman:adapter:ezsp:uart Opening SerialPort with {"path":"/dev/ttyAMA1","baudRate":115200,"rtscts":true,"autoOpen":false}
2023-01-01T16:01:42.552Z zigbee-herdsman:adapter:ezsp:erro Reset error Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:91:28)
    at SerialPort._error (/app/node_modules/@serialport/stream/dist/index.js:76:22)
    at /app/node_modules/@serialport/stream/dist/index.js:112:18
2023-01-01T16:01:42.552Z zigbee-herdsman:adapter:ezsp:driv Pause 60sec before try 10
2023-01-01T16:01:42.899Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"nop","_id_":5,"_isRequest_":true}
2023-01-01T16:01:42.900Z zigbee-herdsman:adapter:ezsp:uart --> DATA (2,2,0): 7a0005
2023-01-01T16:01:42.900Z zigbee-herdsman:adapter:ezsp:uart --> [223821ad63727e]
2023-01-01T16:01:42.900Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (3)
2023-01-01T16:01:42.901Z zigbee-herdsman:adapter:ezsp:erro Watchdog heartbeat timeout Error: Failure send nop:{"type":"Buffer","data":[121,0,5]}
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:516:23
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
2023-01-01T16:01:42.905Z zigbee-herdsman:adapter:ezsp:uart <-- [2338a1a90c2a5cfb757e]
2023-01-01T16:01:42.905Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (2,3,0): 2338a1a90c2a5cfb757e
2023-01-01T16:01:42.905Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (3)
2023-01-01T16:01:42.905Z zigbee-herdsman:adapter:ezsp:uart --> [83401b7e]
2023-01-01T16:01:42.906Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 7a8001580049
2023-01-01T16:01:42.906Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x1: {"_id_":1,"_cls_":"getLibraryStatus","_isRequest_":false,"status":88}
2023-01-01T16:01:42.906Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (3) success
```
