### ISSUE TITLE
Zigbee2MQTT only receives, cannot send.

### ISSUE THREAD

**Issue by deltaphi** [Koenkk/zigbee2mqtt#15498]
### What happened?

Zigbee2MQTT as Home Assistant Addon, using a Conbee II as a Zigbee Radio.

My setup was working for years, most recently using Zigbee2MQTT 1.28.2 (Addon version 1.28.2-1). Recently, I upgraded  Zigbee2MQTT to 1.28.4 (Addon version 1.28.4-1). Ever since then, Zigbee2MQTT can only receive data from switches and motion sensors, but does not receive anything from actors, lights nor can it send any messages out.

To make this more clear, with a few examples:
* I can still control lights through their respective paired Zigbee switches.
* Home Assistant executes scripts that are triggered by button presses on specific Zigbee switches.
* Zigbee2MQTT permanently reports all lights and actors as being "off". Any attempt to send a command from Zigbee2MQTT (either its own UI or the Home Assitant UI) to a light or actor fails: The light/actor do not change state and the log eventually reports an error:

debug 2022-12-11 21:55:25Received MQTT message on 'zigbee2mqtt/Esstisch/set' with data '{"state":"ON"}'
debug 2022-12-11 21:55:25Publishing 'set' 'state' to 'Esstisch'
error 2022-12-11 21:56:25Publish 'set' 'state' to 'Esstisch' failed: 'Error: Command 0x086bd7fffe5f1503/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received)'

### What did you expect to happen?

I expected that Zigbee2MQTT should be able to successfully send commands to lights and actors.

### How to reproduce it (minimal and precise)

Get Zigbee2MQTT 1.28.4 and a Conbee II. Pair a light bulb with Zigbee2MQTT. Try to switch the light bulb on or off. 

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

0x26720700

### Adapter

Dresden Elektronik Conbee II

### Debug log

Debug Logs stopped on 2022-12-02 - for whatever reason. Below is the output of the Frontend for Log Level Debug.

debug 2022-12-11 21:55:25Received MQTT message on 'zigbee2mqtt/Esstisch/set' with data '{"state":"ON"}'
debug 2022-12-11 21:55:25Publishing 'set' 'state' to 'Esstisch'
debug 2022-12-11 21:55:34Received MQTT message on 'zigbee2mqtt/Spot Fenster/set' with data '{"state":"ON"}'
debug 2022-12-11 21:55:34Publishing 'set' 'state' to 'Spot Fenster'
debug 2022-12-11 21:56:18Received MQTT message on 'homeassistant/sensor/SML-Power-Meter-7738484/battery/config' with data '{"device_class":"voltage","name":"SML-Power-Meter-7738484-Battery","state_topic":"homeassistant/sensor/SML-Power-Meter-7738484/state","json_attributes_topic":"homeassistant/sensor/SML-Power-Meter-7738484/state","unique_id":"SML-Power-Meter-7738484-Battery-ESP","unit_of_measurement":"V","value_template":"{{value_json.battery}}"}'
debug 2022-12-11 21:56:18Received MQTT message on 'homeassistant/sensor/SML-Power-Meter-7738484/energy/config' with data '{"device_class":"energy","name":"SML-Power-Meter-7738484-Energy","state_topic":"homeassistant/sensor/SML-Power-Meter-7738484/state","state_class":"total_increasing","json_attributes_topic":"homeassistant/sensor/SML-Power-Meter-7738484/state","unique_id":"SML-Power-Meter-7738484-Energy-ESP","unit_of_measurement":"kWh","value_template":"{{value_json.total_energy_consumed_kwh}}"}'
debug 2022-12-11 21:56:18Received MQTT message on 'homeassistant/sensor/SML-Power-Meter-7738484/energy-delivered/config' with data '{"device_class":"energy","name":"SML-Power-Meter-7738484-Energy-Delivered","state_topic":"homeassistant/sensor/SML-Power-Meter-7738484/state","state_class":"total_increasing","json_attributes_topic":"homeassistant/sensor/SML-Power-Meter-7738484/state","unique_id":"SML-Power-Meter-7738484-Energy-Delivered-ESP","unit_of_measurement":"kWh","value_template":"{{value_json.total_energy_delivered_kwh}}"}'
debug 2022-12-11 21:56:18Received MQTT message on 'homeassistant/sensor/SML-Power-Meter-7738484/power/config' with data '{"device_class":"power","name":"SML-Power-Meter-7738484-Power","state_topic":"homeassistant/sensor/SML-Power-Meter-7738484/state","json_attributes_topic":"homeassistant/sensor/SML-Power-Meter-7738484/state","unique_id":"SML-Power-Meter-7738484-Power-ESP","unit_of_measurement":"W","value_template":"{{value_json.power}}"}'
debug 2022-12-11 21:56:18Received MQTT message on 'homeassistant/sensor/SML-Power-Meter-7738484/state' with data '{"node":"SML-Power-Meter-7738484","total_energy_consumed_kwh":9124.6474609375,"total_energy_delivered_kwh":34.460601806640625,"battery":3.3809084892272949,"power":326}'
error 2022-12-11 21:56:25Publish 'set' 'state' to 'Esstisch' failed: 'Error: Command 0x086bd7fffe5f1503/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received)'
debug 2022-12-11 21:56:25Error: Command 0x086bd7fffe5f1503/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received) at DeconzAdapter.sendZclFrameToEndpoint (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:658:23) at Endpoint.sendRequest (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:299:20) at Endpoint.command (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:772:28) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:282:17) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:916:32) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:246:36)
info 2022-12-11 21:56:25MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'Esstisch' failed: 'Error: Command 0x086bd7fffe5f1503/1 genOnOff.on({}, {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received)'","meta":{"friendly_name":"Esstisch"},"type":"zigbee_publish_error"}'
error 2022-12-11 21:56:34Publish 'set' 'state' to 'Spot Fenster' failed: 'Error: Command 0x7cb03eaa0a0c21fe/3 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received)'
debug 2022-12-11 21:56:34Error: Command 0x7cb03eaa0a0c21fe/3 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received) at DeconzAdapter.sendZclFrameToEndpoint (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:658:23) at Endpoint.sendRequest (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:299:20) at Endpoint.command (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:772:28) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:282:17) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:246:36)
info 2022-12-11 21:56:34MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'Spot Fenster' failed: 'Error: Command 0x7cb03eaa0a0c21fe/3 genOnOff.on({}, {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received)'","meta":{"friendly_name":"Spot Fenster"},"type":"zigbee_publish_error"}'
debug 2022-12-11 21:56:58Received Zigbee message from 'Wohnzimmerschalter', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":87}' from endpoint 1 with groupID null
info 2022-12-11 21:56:58MQTT publish: topic 'zigbee2mqtt/Wohnzimmerschalter', payload '{"action":null,"battery":43.5,"linkquality":252}'
debug 2022-12-11 21:57:46Saving state to file /config/zigbee2mqtt/state.json
debug 2022-12-11 21:59:35Received Zigbee message from 'Bewegungsmelder Flur OG', type 'commandOnWithTimedOff', cluster 'genOnOff', data '{"ctrlbits":0,"offwaittime":0,"ontime":1800}' from endpoint 1 with groupID 101
info 2022-12-11 21:59:35MQTT publish: topic 'zigbee2mqtt/Bewegungsmelder Flur OG', payload '{"battery":21,"illuminance_above_threshold":false,"linkquality":252,"occupancy":true,"requested_brightness_level":254,"requested_brightness_percent":100,"update":{"installed_version":"2.0.022","state":"idle"},"update_available":false}'
info 2022-12-11 22:00:05MQTT publish: topic 'zigbee2mqtt/Bewegungsmelder Flur OG', payload '{"battery":21,"illuminance_above_threshold":false,"linkquality":252,"occupancy":false,"requested_brightness_level":254,"requested_brightness_percent":100,"update":{"installed_version":"2.0.022","state":"idle"},"update_available":false}'

**Comment by deltaphi** [comment]
Somehow this seems to have resolved itself. My Zigbee stick is back in working order, but I have no idea what fixed it.
