### ISSUE TITLE
Yale YRD226 doesn't lock or unlock.

### ISSUE THREAD

**Issue by XBadPlayerX** [Koenkk/zigbee2mqtt#15708]
### What happened?

After I updated to the latest Zigbee2MQTT, the lock and unlock actions stopped working.
Either in automation or changing the state on the Home Assistant dashboard.
![image](https://user-images.githubusercontent.com/55669616/209242142-030ff03c-09d9-4da4-8e5f-2023c356e5f0.png)
The lock still shows the correct status though.

When I push the button on the Home Assistant dashboard, I get this in the log.
```
debug 2022-12-22 18:34:02: Received MQTT message on 'zigbee2mqtt/Front Door Lock/set' with data 'LOCK'
debug 2022-12-22 18:34:02: Publishing 'set' 'state' to 'Front Door Lock'
```

### What did you expect to happen?

The lock should lock or unlock when an automation calls for it or when I press the button.

### How to reproduce it (minimal and precise)

Try to lock or unlock the door lock or use the automation.

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

20220219

### Adapter

Sonoff Stick

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/10290974/log.txt)

**Comment by XBadPlayerX** [comment]
I just found this in the logs while locking and unlocking manually.
```
error 2022-12-27 08:04:11: Publish 'set' 'state' to 'Front Door Lock' failed: 'Error: Command 0x000d6f000f76c53b/1 closuresDoorLock.lockDoor({"pincodevalue":""}, {"sendWhen":"active","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
debug 2022-12-27 08:04:11: Error: Command 0x000d6f000f76c53b/1 closuresDoorLock.lockDoor({"pincodevalue":""}, {"sendWhen":"active","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23)
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
info  2022-12-27 08:04:11: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'Front Door Lock' failed: 'Error: Command 0x000d6f000f76c53b/1 closuresDoorLock.lockDoor({\"pincodevalue\":\"\"}, {\"sendWhen\":\"active\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Data request failed with error: 'No network route' (205))'","meta":{"friendly_name":"Front Door Lock"},"type":"zigbee_publish_error"}'
```

**Comment by XBadPlayerX** [comment]
I hope there is something new on this.

**Comment by XBadPlayerX** [comment]
Now this lock has fallen completely off the network.
