### ISSUE TITLE
"Failed to connect to the adapter" after apt upgrade 

### ISSUE THREAD

**Issue by OToussaint** [Koenkk/zigbee2mqtt#15740]
### What happened?

Did some upgrade of some packages.
This allowed me to update my containers as well, including zigbee2mqtt
And, now, the log is showing

```
Zigbee2MQTT:error 2022-12-24 15:51:50: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)
```

The adapter is the right one:

```
pi@hassbian:~/IOTstack $ ls -l /dev/serial/by-id
total 0
lrwxrwxrwx 1 root root 13 Dec 24 16:17 usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018E204EE-if00 -> ../../ttyACM0
```

And it is the one in the configuration.yaml file

```
serial:
  port: /dev/ttyACM0
```

The rights are ok, according to the test, made inside a shell in the container:

```
Using '/app/data' as data directory
/app # test -w /dev/ttyACM0 && echo success || echo failure
success
```

### What did you expect to happen?

I expected zigbee2mqtt to work as before

### How to reproduce it (minimal and precise)

I don't know.
Probably one of the packages I've updated?

### Zigbee2MQTT version

1.28.4

### Adapter firmware version

Unknown

### Adapter

Texas Instruments, Inc. CC2531 ZigBee

### Debug log

Using '/app/data' as data directory
Zigbee2MQTT:debug 2022-12-24 15:58:22: Loaded state from file /app/data/state.json
Zigbee2MQTT:info  2022-12-24 15:58:22: Logging to console and directory: '/app/data/log/2022-12-24.15-58-21' filename: log.txt
Zigbee2MQTT:debug 2022-12-24 15:58:22: Removing old log directory '/app/data/log/2022-12-24.15-52-10'
Zigbee2MQTT:info  2022-12-24 15:58:22: Starting Zigbee2MQTT version 1.28.4 (commit #52e545f)
Zigbee2MQTT:info  2022-12-24 15:58:22: Starting zigbee-herdsman (0.14.76)
Zigbee2MQTT:debug 2022-12-24 15:58:22: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyACM0"}}'
Zigbee2MQTT:error 2022-12-24 15:58:44: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-12-24 15:58:44: Failed to start zigbee
Zigbee2MQTT:error 2022-12-24 15:58:44: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-12-24 15:58:44: Exiting...
Zigbee2MQTT:error 2022-12-24 15:58:45: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)

**Comment by OToussaint** [comment]
I restarted from a very old backup

info  2022-12-30 12:07:47: Starting Zigbee2MQTT version 1.21.0 (commit #70891eec)
info  2022-12-30 12:07:47: Starting zigbee-herdsman (0.13.124)

And it was working (using nodejs v12.22.12

Then did a git pull and restart and it was working too with a warning about nodejs v12.22.12

info  2023-01-05 12:26:57: Starting Zigbee2MQTT version 1.29.0 (commit #dddce571)
info  2023-01-05 12:26:57: Starting zigbee-herdsman (0.14.83)

And finally upgraded nodejs to v16.19.0 and it is working.

I don't know what was the issue but consider it as closed I guess.
