### ISSUE TITLE
Interview for eWeLink plug crashes with ezsp adapter

### ISSUE THREAD

**Issue by rccoleman** [Koenkk/zigbee2mqtt#15813]
### What happened?

I attempted to join these smart plugs: https://zigbee.blakadder.com/eWeLink_SWITCH-ZR03.html, which are listed as working with Z2M on that site, to my SkyConnect dongle using the EZSP v9 adapter.  When I do, the interview process quickly crashes Z2M and is left incomplete.  I've tried with both the mainline (1.28.4) and dev (1.28.4-dev) branches with the same results.  This is the log that I get, with some extra unrelated stuff that I didn't want to delete, but you can probably ignore:

```
Zigbee2MQTT:info  2022-12-29 16:19:56: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"aanzt-1"}'
Zigbee2MQTT:debug 2022-12-29 16:19:59: Received MQTT message on 'homeassistant/sensor/weatherflow2mqtt_SK-00001311/rapid_wind/state' with data '{"wind_speed": 1.99, "wind_bearing": 183, "wind_direction": "S"}'
Zigbee2MQTT:debug 2022-12-29 16:20:03: Received MQTT message on 'homeassistant/sensor/weatherflow2mqtt_HB-00004606/status_update/state' with data '{"status": "2022-11-10T19:58:37+00:00"}'
Zigbee2MQTT:debug 2022-12-29 16:20:03: Received MQTT message on 'homeassistant/sensor/weatherflow2mqtt_HB-00004606/status/attributes' with data '{"attribution": "Powered by WeatherFlow2MQTT", "serial_number": "HB-00004606", "rssi": -41, "version": "3.1.4", "reset_flags": ["Brownout reset", "PIN reset", "Power reset"]}'
Zigbee2MQTT:warn  2022-12-29 16:20:11: Device '0x00124b0023b8639d' left the network
Zigbee2MQTT:info  2022-12-29 16:20:11: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00124b0023b8639d","ieee_address":"0x00124b0023b8639d"},"type":"device_leave"}'
Zigbee2MQTT:warn  2022-12-29 16:20:11: Device '0x00124b0023b8639d' left the network
Zigbee2MQTT:info  2022-12-29 16:20:12: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00124b0023b8639d","ieee_address":"0x00124b0023b8639d"},"type":"device_leave"}'
Zigbee2MQTT:debug 2022-12-29 16:20:13: Received MQTT message on 'homeassistant/sensor/weatherflow2mqtt_HB-00004606/status_update/state' with data '{"status": "2022-11-10T19:58:37+00:00"}'
Zigbee2MQTT:debug 2022-12-29 16:20:13: Received MQTT message on 'homeassistant/sensor/weatherflow2mqtt_HB-00004606/status/attributes' with data '{"attribution": "Powered by WeatherFlow2MQTT", "serial_number": "HB-00004606", "rssi": -42, "version": "3.1.4", "reset_flags": ["Brownout reset", "PIN reset", "Power reset"]}'
Zigbee2MQTT:debug 2022-12-29 16:20:14: Received MQTT message on 'homeassistant/sensor/weatherflow2mqtt_SK-00001311/rapid_wind/state' with data '{"wind_speed": 2.21, "wind_bearing": 193, "wind_direction": "SSW"}'
Zigbee2MQTT:info  2022-12-29 16:20:16: Device '0x00124b0023b8639d' joined
Zigbee2MQTT:info  2022-12-29 16:20:16: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00124b0023b8639d","ieee_address":"0x00124b0023b8639d"},"type":"device_joined"}'
Zigbee2MQTT:info  2022-12-29 16:20:16: Starting interview of '0x00124b0023b8639d'
Zigbee2MQTT:info  2022-12-29 16:20:16: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00124b0023b8639d","ieee_address":"0x00124b0023b8639d","status":"started"},"type":"device_interview"}'
TypeError: Cannot read properties of undefined (reading 'toString')
    at EZSPAdapter.processMessage (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:103:49)
    at Driver.emit (node:events:513:28)
    at Driver.handleFrame (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:278:22)
    at Ezsp.emit (node:events:513:28)
    at Ezsp.onFrameReceived (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:303:28)
    at SerialDriver.emit (node:events:513:28)
    at SerialDriver.handleDATA (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:227:14)
    at SerialDriver.onParsed (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:174:22)
    at Parser.emit (node:events:513:28)
    at Parser.parseNext (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/parser.ts:37:26)
```
You can see where I permitted joining, excluded the device, and it tried to rejoin.  I've tried various different sequences to exclude, then permit, then join or unplugging/plugging back in to join, but I get the same result every time.

I also saw [this forum thread](https://community.home-assistant.io/t/popular-zigbee-wall-modules-unsupported/504910) for the same plugs, but they got further than I did probably because they're using a different, non-experimental coordinator.

### What did you expect to happen?

I expected at least to see that the device was unsupported and have the opportunity to add a converter for it.

### How to reproduce it (minimal and precise)

Attempt to join [these devices](https://www.amazon.com/gp/product/B08K45W4LR/ref=ppx_yo_dt_b_asin_title_o06_s00?ie=UTF8&psc=1) and observe that the interview doesn't complete.

### Zigbee2MQTT version

1.28.4 & 1.28.4-dev

### Adapter firmware version

7.1.1.0 build 273

### Adapter

Nabu Casa SkyConnect 1.0 using EZSP v9

### Debug log

Unfortunately the crash doesn't show up in the log, which ends with the interview starting.  But I'm attaching the relevant log anyway.
[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/10322688/log.txt)

**Comment by rccoleman** [comment]
Looks like this may be a dup of https://github.com/Koenkk/zigbee-herdsman/issues/636, but I don't know for sure.

**Comment by rccoleman** [comment]
It's the same thing, so I'm going to close this.  The suggestion there to change `frame.senderEui64` to `frame.sender` also resolves it for me, but I understand that it doesn't sound like the right solution.
