### ISSUE TITLE
[New device support]: Legrand WNAL63 Wireless Dimmer 

### ISSUE THREAD

**Issue by brantmacga** [Koenkk/zigbee2mqtt#15846]
### Link

https://www.legrand.us/wiring-devices/designer-switches-and-outlets/adorne-wireless-smart-dimmer-with-netatmo-white/p/wnal63w1

### Database entry

0x646266fffe61a04b

### Comments

**I've tried creating an external converter for this device using examples of similar devices in the Legrand.js library, but I receive this error when restarting Z2M. This is a wireless dimmer with a single-button on/off toggle, and a raise/lower dimmer paddle. The device I copied from Legrand.js is '067773'; I've previously tried to pair this device with ZHA (unsupported there also) and those clusters in 067773 appear to the the same as this WNAL63**

[14:21:44] INFO: Preparing to start...
[14:21:44] INFO: Socat not enabled
[14:21:46] INFO: Starting Zigbee2MQTT...
/app/dist/util/externally-loaded.js:25
};
 ^
SyntaxError: Unexpected token ';'
    at new Script (node:vm:100:7)
    at createScript (node:vm:265:10)
    at Object.runInNewContext (node:vm:306:10)
    at loadModuleFromText (/app/lib/util/utils.ts:148:8)
    at loadModuleFromFile (/app/lib/util/utils.ts:155:12)
    at Object.getExternalConvertersDefinitions (/app/lib/util/utils.ts:165:25)
    at getExternalConvertersDefinitions.next (<anonymous>)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:12:20)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)

### External converter

```shell
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['Remote dimmer switch'],
    model: 'WNAL63',
    vendor: 'Legrand',
    description: 'Remote dimmer switch',
    fromZigbee: [fz.identify, fz.command_on, fz.command_off, fz.command_toggle, fz.cmd_move, fz.cmd_stop,
            fz.battery], // <-- added here all clusters reported from zigbee
    toZigbee: [], // <-- add here all clusters to send commands to zigbee
    exposes: [e.battery(), e.action(['identify', 'on', 'off', 'toggle', 'brightness_move_up',
            'brightness_move_down', 'brightness_stop'])], // <-- this will define which fields will be exposed in the definition message to configure a front end (e.g. the z2m frontend, Home Assistant, Domoticz)

        meta: {battery: {voltageToPercentage: '3V_2500'}, publishDuplicateTransaction: true},
        onEvent: readInitialBatteryState,
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg', 'genOnOff', 'genLevelCtrl']);
};

module.exports = definition;
```

**Comment by brantmacga** [comment]
So I figured out how to fix the "Syntax Error". 

After that I received this error:
_ReferenceError: readInitialBatteryState is not defined_

I deleted the BatteryState line, and now I get this error:

[14:48:38] INFO: Preparing to start...
[14:48:39] INFO: Socat not enabled
[14:48:41] INFO: Starting Zigbee2MQTT...
/app/node_modules/zigbee-herdsman-converters/index.js:91
        if (converter.options) {
                      ^
TypeError: Cannot read properties of undefined (reading 'options')
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:91:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)


This is what my converter file now looks like:
[14:48:38] INFO: Preparing to start...
[14:48:39] INFO: Socat not enabled
[14:48:41] INFO: Starting Zigbee2MQTT...
/app/node_modules/zigbee-herdsman-converters/index.js:91
        if (converter.options) {
                      ^
TypeError: Cannot read properties of undefined (reading 'options')
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:91:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)

**Comment by brantmacga** [comment]
Well it seems as though I've got it working now. 

I have paired it to Z2M, and I now have it bound to a philips Hue lamp. On/Off works, and level control works. The only thing I don't see working is the batter level. 

But other than that, it works as it should. 

This is my converter .....

### External converter
```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['Remote dimmer switch'],
    model: 'WNAL63',
    vendor: 'Legrand',
    description: 'Remote dimmer switch',
    fromZigbee: [fz.identify, fz.command_on, fz.command_off, fz.command_toggle, fz.battery], // <-- added here all clusters reported from zigbee
    toZigbee: [], // <-- add here all clusters to send commands to zigbee
    exposes: [e.battery(), e.action(['identify', 'on', 'off', 'toggle', 'brightness_move_up',
            'brightness_move_down', 'brightness_stop'])], // <-- this will define which fields will be exposed in the definition message to configure a front end (e.g. the z2m frontend, Home Assistant, Domoticz
};

module.exports = definition;
```

**Comment by brantmacga** [comment]
Here is a little video confirming it working 

https://imgur.com/a/eCyhJBK

**Comment by brantmacga** [comment]
One thing I'm having an issue with is binding it to a group; still working through that before this gets closed.

**Comment by brantmacga** [comment]
Still unsuccessful at group binding with Philips Hue lamps. Whenever I bind to the group, I get a message that it was successful, but it doesn't work. On a side note, I've also been unsuccessful at group binding with the Legrand/Bticino 3577C switch module. 

I tried to add the dimmer switch to my group, and I get a timeout error. 

This is my latest converter where I've copied attributes from other Legrand devices that say group binding is supported. 

### External converter
```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['Remote dimmer switch'],
    model: 'WNAL63',
    vendor: 'Legrand',
    description: 'Remote dimmer switch',
    fromZigbee: [fz.identify, fz.command_on, fz.command_off, fz.command_toggle, fz.battery], // <-- added here all clusters reported from zigbee
    toZigbee: [tz.on_off, tz.light_onoff_brightness], // <-- add here all clusters to send commands to zigbee
    exposes: [e.battery(), e.action(['identify', 'on', 'off', 'toggle', 'brightness_move_up',
            'brightness_move_down', 'brightness_stop'])], // <-- this will define which fields will be exposed in the definition message to configure a front end (e.g. the z2m frontend, Home Assistant, Domoticz
        meta: {battery: {voltageToPercentage: '3V_2500'}, publishDuplicateTransaction: true},
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg', 'genOnOff', 'genLevelCtrl']);
        },
};

module.exports = definition;
```

Here are some of the error messages from the log:

>  2023-01-01 22:57:49MQTT publish: topic 'zigbee2mqtt/bridge/response/group/members/add', payload '{"data":{"device":"0x646266fffe61a04b/1","group":"Pool Bathroom & Pool Lights"},"error":"Failed to add from group (Command 0x646266fffe61a04b/1 genGroups.add({\"groupid\":2,\"groupname\":\"\"}, 
{\"sendWhen\":\"active\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Timeout - 48635 - 1 - 3 - 4 - 0 after 10000ms))","status":"error","transaction":"rktr6-1"}'

> 2023-01-01 22:57:49Failed to add from group (Command 0x646266fffe61a04b/1 genGroups.add({"groupid":2,"groupname":""}, {"sendWhen":"active","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 48635 - 1 - 3 - 4 - 0 after 10000ms))

**Comment by brantmacga** [comment]
I've edited my converter to what i believe should work for group binding, but still unsuccessful. I've tried it with a couple of different Hue lamp groups; I get a message that says on/off and level control successfully binded, but still nothing happens when I use the switch. Here is my latest converter.....

### External converter
```
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const fz = {...require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').fromZigbee};
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const ota = require('zigbee-herdsman-converters/lib/ota');

const readInitialBatteryState = async (type, data, device) => {
    if (['deviceAnnounce'].includes(type)) {
        const endpoint = device.getEndpoint(1);
        const options = {manufacturerCode: 0x1021, disableDefaultResponse: true};
        await endpoint.read('genPowerCfg', ['batteryVoltage'], options);
    }
};

const tzLocal = {
    auto_mode: {
        key: ['auto_mode'],
        convertSet: async (entity, key, value, meta) => {
            const mode = {'off': 0x00, 'auto': 0x02, 'on_override': 0x03};
            const payload = {data: Buffer.from([mode[value]])};
            await entity.command('manuSpecificLegrandDevices3', 'command0', payload);
            return {state: {'auto_mode': value}};
        },
    },
};

module.exports = [
    {
        zigbeeModel: ['Remote dimmer switch'],
        model: 'WNAL63',
        vendor: 'Legrand',
        // led blink RED when battery is low
        description: 'Remote dimmer switch',
        fromZigbee: [fz.identify, fz.command_on, fz.command_off, fz.command_toggle, fz.legacy.cmd_move, fz.legacy.cmd_stop,
            fz.battery],
        exposes: [e.battery(), e.action(['identify', 'on', 'off', 'toggle', 'brightness_move_up',
            'brightness_move_down', 'brightness_stop'])],
        toZigbee: [],
        meta: {battery: {voltageToPercentage: '3V_2500'}, publishDuplicateTransaction: true},
        onEvent: readInitialBatteryState,
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg', 'genOnOff', 'genLevelCtrl']);
        },
    },
];
```

**Comment by brantmacga** [comment]
Discussion on binding issues continued here: https://github.com/Koenkk/zigbee2mqtt/issues/15897
