### ISSUE TITLE
Paul Neuhaus - NLG TW - 'MAC no ack' (233) Error

### ISSUE THREAD

**Issue by yonz2** [Koenkk/zigbee2mqtt#15865]
### What happened?

After installing and pairing three Paul Neuhaus (Neuhaus Lighting Group) Lamps: NLG TW light: (NLG Model Numbers: 2076-18, 2845-1-55, 6118-15), I am not able to control them from Home Assistant (via Zigbee2MQTT)

If I toggle the switch nothing happens. In the Zigbee2MQTT logs I dop see an error: 'MAC no ack' (233).

BTW: I've tried the same with the Sonoff ZBBridge (flashed with Tasmota) with the same results.

The strange thing is that immediately after pairing the Lamps I was able to toggle the lights, but after ca. 5 to 10 minutes it didn't work any more.

### What did you expect to happen?

Being able to toggle / fully control the NLG TW Lights 

### How to reproduce it (minimal and precise)

1: Pair an NLG TW Light
2: Wait ca. 10 minutes
3: Try to control the lamp (turn On or Off)

### Zigbee2MQTT version

1.29.0-dev commit: 4e40c82

### Adapter firmware version

20220219

### Adapter

Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Debug log

System Configuration:
```
Home Assistant 2022.12.8
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest

Zigbee2MQTT version: 1.29.0-dev commit: 4e40c82
Coordinator type: zStack3x0
Coordinator revision: 20220219
Coordinator IEEE Address: 0x00124b002a2e87a3
Coordinator Hardware: Sonoff_Zigbee_3.0_USB_Dongle_Plus
Coordinator Port: dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
``````
Configuration of one of the three NLG TW Lamps (all three exhibit exactly the same behaviour)
```
Friendly name: Esstisch
Description: 
Last seen: N/A
Availability: Disabled
Device type: Router
Zigbee Model: NLG-TW light
Zigbee Manufacturer: Neuhaus Lighting Group
Description: Various tunable white lights (e.g. 8195-55)
Support status: Supported

IEEE Address: 0x90940300e00bfdb0
Network address: 0x51BB
Firmware build date: 20210611
Firmware version: 1.0.6
Manufacturer: Paul Neuhaus
Model: NLG-TW light
Power: Mains
Interview completed: True



```

Startup:
```
Zigbee2MQTT:info  2023-01-01 14:56:35: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"online"}'
Zigbee2MQTT:info  2023-01-01 14:56:35: Started frontend on port 0.0.0.0:8099
Zigbee2MQTT:info  2023-01-01 14:56:35: MQTT publish: topic 'homeassistant/light/0x90940300e00bfdb0/light/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"brightness":true,"brightness_scale":254,"color_mode":true,"command_topic":"zigbee2mqtt/Esstisch/set","device":{"identifiers":["zigbee2mqtt_0x90940300e00bfdb0"],"manufacturer":"Paul Neuhaus","model":"Various tunable white lights (e.g. 8195-55) (NLG-TW light)","name":"Esstisch","sw_version":"1.0.6"},"effect":true,"effect_list":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"max_mireds":370,"min_mireds":153,"name":"Esstisch","schema":"json","state_topic":"zigbee2mqtt/Esstisch","supported_color_modes":["color_temp"],"unique_id":"0x90940300e00bfdb0_light_zigbee2mqtt"}'
Zigbee2MQTT:info  2023-01-01 14:56:35: MQTT publish: topic 'homeassistant/select/0x90940300e00bfdb0/effect/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/Esstisch/set/effect","device":{"identifiers":["zigbee2mqtt_0x90940300e00bfdb0"],"manufacturer":"Paul Neuhaus","model":"Various tunable white lights (e.g. 8195-55) (NLG-TW light)","name":"Esstisch","sw_version":"1.0.6"},"enabled_by_default":false,"icon":"mdi:palette","name":"Esstisch effect","options":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"unique_id":"0x90940300e00bfdb0_effect_zigbee2mqtt"}'
Zigbee2MQTT:info  2023-01-01 14:56:35: MQTT publish: topic 'homeassistant/sensor/0x90940300e00bfdb0/power_on_behavior/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x90940300e00bfdb0"],"manufacturer":"Paul Neuhaus","model":"Various tunable white lights (e.g. 8195-55) (NLG-TW light)","name":"Esstisch","sw_version":"1.0.6"},"enabled_by_default":false,"entity_category":"config","icon":"mdi:power-settings","name":"Esstisch power on behavior","state_topic":"zigbee2mqtt/Esstisch","unique_id":"0x90940300e00bfdb0_power_on_behavior_zigbee2mqtt","value_template":"{{ value_json.power_on_behavior }}"}'
Zigbee2MQTT:info  2023-01-01 14:56:35: MQTT publish: topic 'homeassistant/select/0x90940300e00bfdb0/power_on_behavior/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/Esstisch/set/power_on_behavior","device":{"identifiers":["zigbee2mqtt_0x90940300e00bfdb0"],"manufacturer":"Paul Neuhaus","model":"Various tunable white lights (e.g. 8195-55) (NLG-TW light)","name":"Esstisch","sw_version":"1.0.6"},"entity_category":"config","icon":"mdi:power-settings","name":"Esstisch power on behavior","options":["off","on","toggle","previous"],"state_topic":"zigbee2mqtt/Esstisch","unique_id":"0x90940300e00bfdb0_power_on_behavior_zigbee2mqtt","value_template":"{{ value_json.power_on_behavior }}"}'
Zigbee2MQTT:info  2023-01-01 14:56:35: MQTT publish: topic 'homeassistant/sensor/0x90940300e00bfdb0/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x90940300e00bfdb0"],"manufacturer":"Paul Neuhaus","model":"Various tunable white lights (e.g. 8195-55) (NLG-TW light)","name":"Esstisch","sw_version":"1.0.6"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"Esstisch linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/Esstisch","unique_id":"0x90940300e00bfdb0_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Zigbee2MQTT:info  2023-01-01 14:56:35: MQTT publish: topic 'homeassistant/light/0xab910300e00bfdb0/light/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"brightness":true,"brightness_scale":254,"color_mode":true,"command_topic":"zigbee2mqtt/Stehlampe-Wohnzimmer/set","device":{"identifiers":["zigbee2mqtt_0xab910300e00bfdb0"],"manufacturer":"Paul Neuhaus","model":"Various tunable white lights (e.g. 8195-55) (NLG-TW light)","name":"Stehlampe-Wohnzimmer","sw_version":"1.0.6"},"effect":true,"effect_list":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"max_mireds":370,"min_mireds":153,"name":"Stehlampe-Wohnzimmer","schema":"json","state_topic":"zigbee2mqtt/Stehlampe-Wohnzimmer","supported_color_modes":["color_temp"],"unique_id":"0xab910300e00bfdb0_light_zigbee2mqtt"}'
Zigbee2MQTT:info  2023-01-01 14:56:35: MQTT publish: topic 'homeassistant/select/0xab910300e00bfdb0/effect/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/Stehlampe-Wohnzimmer/set/effect","device":{"identifiers":["zigbee2mqtt_0xab910300e00bfdb0"],"manufacturer":"Paul Neuhaus","model":"Various tunable white lights (e.g. 8195-55) (NLG-TW light)","name":"Stehlampe-Wohnzimmer","sw_version":"1.0.6"},"enabled_by_default":false,"icon":"mdi:palette","name":"Stehlampe-Wohnzimmer effect","options":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"unique_id":"0xab910300e00bfdb0_effect_zigbee2mqtt"}'
Zigbee2MQTT:info  2023-01-01 14:56:35: MQTT publish: topic 'homeassistant/sensor/0xab910300e00bfdb0/power_on_behavior/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0xab910300e00bfdb0"],"manufacturer":"Paul Neuhaus","model":"Various tunable white lights (e.g. 8195-55) (NLG-TW light)","name":"Stehlampe-Wohnzimmer","sw_version":"1.0.6"},"enabled_by_default":false,"entity_category":"config","icon":"mdi:power-settings","name":"Stehlampe-Wohnzimmer power on behavior","state_topic":"zigbee2mqtt/Stehlampe-Wohnzimmer","unique_id":"0xab910300e00bfdb0_power_on_behavior_zigbee2mqtt","value_template":"{{ value_json.power_on_behavior }}"}'
Zigbee2MQTT:info  2023-01-01 14:56:35: MQTT publish: topic 'homeassistant/select/0xab910300e00bfdb0/power_on_behavior/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/Stehlampe-Wohnzimmer/set/power_on_behavior","device":{"identifiers":["zigbee2mqtt_0xab910300e00bfdb0"],"manufacturer":"Paul Neuhaus","model":"Various tunable white lights (e.g. 8195-55) (NLG-TW light)","name":"Stehlampe-Wohnzimmer","sw_version":"1.0.6"},"entity_category":"config","icon":"mdi:power-settings","name":"Stehlampe-Wohnzimmer power on behavior","options":["off","on","toggle","previous"],"state_topic":"zigbee2mqtt/Stehlampe-Wohnzimmer","unique_id":"0xab910300e00bfdb0_power_on_behavior_zigbee2mqtt","value_template":"{{ value_json.power_on_behavior }}"}'
Zigbee2MQTT:info  2023-01-01 14:56:35: MQTT publish: topic 'homeassistant/sensor/0xab910300e00bfdb0/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0xab910300e00bfdb0"],"manufacturer":"Paul Neuhaus","model":"Various tunable white lights (e.g. 8195-55) (NLG-TW light)","name":"Stehlampe-Wohnzimmer","sw_version":"1.0.6"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"Stehlampe-Wohnzimmer linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/Stehlampe-Wohnzimmer","unique_id":"0xab910300e00bfdb0_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'

....

Zigbee2MQTT:info  2023-01-01 14:56:36: MQTT publish: topic 'homeassistant/light/0xe1080400e00bfdb0/light/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"brightness":true,"brightness_scale":254,"color_mode":true,"command_topic":"zigbee2mqtt/Flur/set","device":{"identifiers":["zigbee2mqtt_0xe1080400e00bfdb0"],"manufacturer":"Paul Neuhaus","model":"Various tunable white lights (e.g. 8195-55) (NLG-TW light)","name":"Flur","sw_version":"1.0.6"},"effect":true,"effect_list":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"max_mireds":370,"min_mireds":153,"name":"Flur","schema":"json","state_topic":"zigbee2mqtt/Flur","supported_color_modes":["color_temp"],"unique_id":"0xe1080400e00bfdb0_light_zigbee2mqtt"}'
Zigbee2MQTT:info  2023-01-01 14:56:36: MQTT publish: topic 'homeassistant/select/0xe1080400e00bfdb0/effect/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/Flur/set/effect","device":{"identifiers":["zigbee2mqtt_0xe1080400e00bfdb0"],"manufacturer":"Paul Neuhaus","model":"Various tunable white lights (e.g. 8195-55) (NLG-TW light)","name":"Flur","sw_version":"1.0.6"},"enabled_by_default":false,"icon":"mdi:palette","name":"Flur effect","options":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"unique_id":"0xe1080400e00bfdb0_effect_zigbee2mqtt"}'
Zigbee2MQTT:info  2023-01-01 14:56:36: MQTT publish: topic 'homeassistant/sensor/0xe1080400e00bfdb0/power_on_behavior/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0xe1080400e00bfdb0"],"manufacturer":"Paul Neuhaus","model":"Various tunable white lights (e.g. 8195-55) (NLG-TW light)","name":"Flur","sw_version":"1.0.6"},"enabled_by_default":false,"entity_category":"config","icon":"mdi:power-settings","name":"Flur power on behavior","state_topic":"zigbee2mqtt/Flur","unique_id":"0xe1080400e00bfdb0_power_on_behavior_zigbee2mqtt","value_template":"{{ value_json.power_on_behavior }}"}'
Zigbee2MQTT:info  2023-01-01 14:56:36: MQTT publish: topic 'homeassistant/select/0xe1080400e00bfdb0/power_on_behavior/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/Flur/set/power_on_behavior","device":{"identifiers":["zigbee2mqtt_0xe1080400e00bfdb0"],"manufacturer":"Paul Neuhaus","model":"Various tunable white lights (e.g. 8195-55) (NLG-TW light)","name":"Flur","sw_version":"1.0.6"},"entity_category":"config","icon":"mdi:power-settings","name":"Flur power on behavior","options":["off","on","toggle","previous"],"state_topic":"zigbee2mqtt/Flur","unique_id":"0xe1080400e00bfdb0_power_on_behavior_zigbee2mqtt","value_template":"{{ value_json.power_on_behavior }}"}'
Zigbee2MQTT:info  2023-01-01 14:56:36: MQTT publish: topic 'homeassistant/sensor/0xe1080400e00bfdb0/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0xe1080400e00bfdb0"],"manufacturer":"Paul Neuhaus","model":"Various tunable white lights (e.g. 8195-55) (NLG-TW light)","name":"Flur","sw_version":"1.0.6"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"Flur linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/Flur","unique_id":"0xe1080400e00bfdb0_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Zigbee2MQTT:info  2023-01-01 14:56:36: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"online"}'
Zigbee2MQTT:info  2023-01-01 14:56:36: MQTT publish: topic 'zigbee2mqtt/Esstisch', payload '{"brightness":142,"color_mode":"xy","linkquality":65,"power_on_behavior":null,"state":"ON"}'
Zigbee2MQTT:info  2023-01-01 14:56:36: MQTT publish: topic 'zigbee2mqtt/Stehlampe-Wohnzimmer', payload '{"color_mode":"xy","linkquality":99,"power_on_behavior":null,"state":"ON"}'
Zigbee2MQTT:info  2023-01-01 14:56:36: MQTT publish: topic 'zigbee2mqtt/Flur', payload '{"brightness":255,"color_mode":"xy","linkquality":102,"power_on_behavior":null,"state":"ON"}'
Zigbee2MQTT:info  2023-01-01 14:56:36: Zigbee2MQTT started!
```
Error message when turning off "Esstisch" (Light is currently on)
```
Debug 2023-01-01 17:19:48Received MQTT message on 'zigbee2mqtt/Esstisch/set' with data '{"state":"OFF"}'
Debug 2023-01-01 17:19:48Publishing 'set' 'state' to 'Esstisch'
Error 2023-01-01 17:20:05Publish 'set' 'state' to 'Esstisch' failed: 'Error: Command 0x90940300e00bfdb0/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233))'
Debug 2023-01-01 17:20:05Error: Command 0x90940300e00bfdb0/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)) at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23) at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
```

Error Message when trying to change some attributes (here: "power_on_behavior")
```
Debug 2023-01-01 17:34:04Publishing 'set' 'power_on_behavior' to 'Esstisch'
Error 2023-01-01 17:34:04Publish 'set' 'state' to 'Esstisch' failed: 'Error: Command 0x90940300e00bfdb0/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233))'
Debug 2023-01-01 17:34:04Error: Command 0x90940300e00bfdb0/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)) at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23) at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
Error 2023-01-01 17:34:22Publish 'set' 'state' to 'Esstisch' failed: 'Error: Command 0x90940300e00bfdb0/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233))'
Debug 2023-01-01 17:34:22Error: Command 0x90940300e00bfdb0/1 genOnOff.off({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233)) at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23) at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
```

**Comment by yonz2** [comment]
Update:
I tried to remove/turn-off all other potential sources of interference. All this hat no impact on the NLG Lights.

**Comment by yonz2** [comment]
I just got my Zigbee Sniffer / CC Debugger from China. So I set out to try to see what is happening with my NLG Lamps.

Today I removed one of them from Zigbee2MQTT, shutdown Zigbee2MQTT, reset the lamp, restarted Zigbee2MQTT and then re-joined the Lamp, all captured in Wireshark (via ZBOSS). The Network address of the lamp in question is 0xE086

**After joining the lamp, I'm not able to control it from Home Assistant / Zigbee2MQTT**

Here is the pcap file with the captured packets [NLG-TW-0xE086.pcapng.gz](https://github.com/Koenkk/zigbee2mqtt/files/10420190/NLG-TW-0xE086.pcapng.gz)

Zigbee_pc_keys: (req. to decrypt packets in Wireshark... I think)
```
# This file is automatically generated, DO NOT MODIFY.
"69:98:9C:B9:C5:A1:DB:DF:41:A6:4C:EF:E7:05:91:AF","Normal",""
"5A:69:67:42:65:65:41:6C:6C:69:61:6E:63:65:30:39","Normal",""

```
Zigbee2mqtt UI did display a message as well:
![Screenshot from 2023-01-15 12-57-47](https://user-images.githubusercontent.com/13886257/212540811-d2615f1d-e7cd-4fc9-a3a3-7787ea19e9c6.png)

```

Friendly name: Flur
Description:
Last seen: N/A
Availability: [Disabled](https://www.zigbee2mqtt.io/guide/configuration/device-availability.html#availability-advanced-configuration)
Device type: Router
Zigbee Model: NLG-TW light
Zigb
[NLG-TW-0xE086.pcapng.gz](https://github.com/Koenkk/zigbee2mqtt/files/10420182/NLG-TW-0xE086.pcapng.gz)
ee Manufacturer: Neuhaus Lighting Group
Description: Various tunable white lights (e.g. 8195-55)
Support status: Supported

IEEE Address: 0xe1080400e00bfdb0
Network address: 0xE086
Firmware build date: 20210611
Firmware version:1.0.6
Manufacturer: [Paul Neuhaus](https://www.zigbee2mqtt.io/supported-devices/#v=Paul%20Neuhaus)
Model: [NLG-TW light](https://www.zigbee2mqtt.io/devices/NLG-TW_light.html#paul%2520neuhaus-nlg-tw%2520light)
Power: Mains
Interview completed: True
```
