### ISSUE TITLE
ZB2MQTT 1.4.0 stop after receiving a attReport zigbee msg from a meazon meter

### ISSUE THREAD

**Issue by ccorderod** [Koenkk/zigbee2mqtt#1587]
# Bug Report
## What happened
2019-05-30T18:57:31.438Z zigbee-shepherd:request REQ --> AF:dataRequest, transId: 2
2019-05-30T18:57:31.458Z zigbee-shepherd:request RSP <-- AF:dataRequest, status: 0
2019-05-30T18:57:32.399Z zigbee-shepherd:af dispatchIncomingMsg(): type: incomingMsg, msg: {"groupid":0,"clusterid":1794,"srcaddr":34495,"srcendpoint":10,"dstendpoint":1,"wasbroadcast":0,"linkquality":26,"securityuse":0,"timestamp":9500775,"transseqnumber":0,"len":26,"data":{"type":"Buffer","data":[28,54,17,0,10,3,48,35,0,0,0,0,6,48,35,0,0,0,0,24,64,35,163,1,0,0]}}
2019-05-30T18:57:32.407Z zigbee-shepherd:msgHdlr IND <-- AF:incomingMsg, transId: 0
2019-05-30T18:57:32.408Z zigbee-shepherd:af dispatchIncomingMsg(): type: zclIncomingMsg, msg: {"groupid":0,"clusterid":1794,"srcaddr":34495,"srcendpoint":10,"dstendpoint":1,"wasbroadcast":0,"linkquality":26,"securityuse":0,"timestamp":9500775,"transseqnumber":0,"len":26,"data":{"0":28,"1":54,"2":17,"3":0,"4":10,"5":3,"6":48,"7":35,"8":0,"9":0,"10":0,"11":0,"12":6,"13":48,"14":35,"15":0,"16":0,"17":0,"18":0,"19":24,"20":64,"21":35,"22":163,"23":1,"24":0,"25":0},"zclMsg":{"frameCntl":{"frameType":0,"manufSpec":1,"direction":1,"disDefaultRsp":1},"manufCode":4406,"seqNum":0,"cmdId":"report","payload":[{"attrId":12291,"dataType":35,"attrData":0},{"attrId":12294,"dataType":35,"attrData":0},{"attrId":16408,"dataType":35,"attrData":419}]}}
  zigbee2mqtt:debug 5/30/2019, 8:57:32 PM Received zigbee message of type 'attReport' with data '{"cid":"seMetering","data":{"12291":0,"12294":0,"16408":419}}' of device '101.301.001649' (0x00124b0002cc8261) of endpoint 10
/zigbee2mqtt-1.4.0/lib/extension/deviceReceive.js:109
                if (c.cid === cid) {
                      ^
TypeError: Cannot read property 'cid' of undefined
    at mappedDevice.fromZigbee.filter (/zigbee2mqtt-1.4.0/lib/extension/deviceReceive.js:109:23)
    at Array.filter (<anonymous>)
    at DeviceReceive.onZigbeeMessage (/zigbee2mqtt-1.4.0/lib/extension/deviceReceive.js:105:52)
    at extensions.filter.forEach (/zigbee2mqtt-1.4.0/lib/controller.js:143:31)
    at Array.forEach (<anonymous>)
    at Controller.onZigbeeMessage (/zigbee2mqtt-1.4.0/lib/controller.js:143:14)
    at Zigbee.onMessage (/zigbee2mqtt-1.4.0/lib/zigbee.js:253:18)
    at ZShepherd.emit (events.js:182:13)
    at ZShepherd.<anonymous> (/zigbee2mqtt-1.4.0/node_modules/zigbee-shepherd/lib/shepherd.js:180:14)
    at ZShepherd.emit (events.js:182:13)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.4.0 start: `node index.js`

## What did you expect to happen
Just start the addon and run. 1.3.1 does not show this problem

## How to reproduce it (minimal and precise)
start zigbee2mqtt hassio addon (1.4.0).
As soon as a meazon meter zigbee msg is received:
ERR! Failed at the zigbee2mqtt@1.4.0 start script.

## Debug Info
zigbee2mqtt version: 1.4.0
CC253X firmware version: 20190315 (max_stability rev)

**Comment by ccorderod** [comment]
I found and fixed the crash :-).
zigbee2mqtt hassio add-on container is not updated with latest devices.js and shepherd-converter files.
My zigbee2mqtt configuration had still the zigbee_shepherd_devices option to true, hence the add-on was copying my devices.js file (which includes the meazon meter definitions) into zigbee2mqtt. As the shepherd-converter was not in sync (ie, no meazon meter fromZigBee line on it), the cid property was not defined ... and zigbee2mqtt crashed.
Fix is simple: from the container console, I have updated (ie copied) devices.js and associated shepherd-converter files (last version from @Koenkk on his repo) and voilá.
Hope this will help somebody hitting a similar wall.
