### ISSUE TITLE
Schneider Electric WDE002961 / Elko SmartDim vri MultiWire cannot be controlled from zigbee2mqttt

### ISSUE THREAD

**Issue by henrikeri** [Koenkk/zigbee2mqtt#15905]
### What happened?

It is not possible to control the dimmer from zigbee2mqtt or home assistant. I can only see what changes are physically made on the dimmer. It pairs ok without errors. I have 21 of these and all added correctly, but none are controllable.

![image](https://user-images.githubusercontent.com/35510093/210338234-c2388962-277f-4384-bee9-7bf3982a2509.png)

### What did you expect to happen?

I expected to be able to turn the dimmer on/off and to change brightness from zigbee2mqtt

### How to reproduce it (minimal and precise)

Pair dimmer and attempt to control from zigbee2mqtt

### Zigbee2MQTT version

1.29.0

### Adapter firmware version

0x26720700

### Adapter

Conbee II

### Debug log

```

Debug 2023-01-03 11:06:00Received MQTT message on 'zigbee2mqtt/Taklys Spisestue/set' with data '{"brightness":47}'
Debug 2023-01-03 11:06:00Publishing 'set' 'brightness' to 'Taklys Spisestue'
Info 2023-01-03 11:06:00MQTT publish: topic 'zigbee2mqtt/Taklys Spisestue', payload '{"ballast_maximum_level":null,"ballast_minimum_level":null,"brightness":47,"dimmer_mode":null,"linkquality":255,"state":"ON"}'
Debug 2023-01-03 11:06:06Received MQTT message on 'zigbee2mqtt/Taklys Spisestue/get' with data '{"brightness":""}'
Debug 2023-01-03 11:06:06Publishing get 'get' 'brightness' to 'Taklys Spisestue'
Debug 2023-01-03 11:06:06Received Zigbee message from 'Taklys Spisestue', type 'readResponse', cluster 'genLevelCtrl', data '{}' from endpoint 21 with groupID null
Info 2023-01-03 11:06:06MQTT publish: topic 'zigbee2mqtt/Taklys Spisestue', payload '{"ballast_maximum_level":null,"ballast_minimum_level":null,"dimmer_mode":null,"linkquality":255,"state":"ON"}'
Error 2023-01-03 11:06:06Publish 'get' 'brightness' to 'Taklys Spisestue' failed: 'Error: Read 0x94deb8fffe552491/21 genLevelCtrl(["currentLevel"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Debug 2023-01-03 11:06:06Error: Read 0x94deb8fffe552491/21 genLevelCtrl(["currentLevel"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28) at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:480:22) at Object.convertGet (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:986:17) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:273:21)
Info 2023-01-03 11:06:06MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'get' 'brightness' to 'Taklys Spisestue' failed: 'Error: Read 0x94deb8fffe552491/21 genLevelCtrl([\"currentLevel\"], {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'","meta":{"friendly_name":"Taklys Spisestue"},"type":"zigbee_publish_error"}'
```

Edit: Added screenshot

**Comment by verydrunk** [comment]
U probably need to change the endpoint for onOff and levelCtrl. I noticed that Schneider doesn't like to be consistent in there products.

**Comment by juha077** [comment]
Did you ever figure out the issue? I also have bunch of these dimmers with exactly the same issue? I tried to change the endpoints but did not get anywhere with that.

**Comment by henrikeri** [comment]
Sort of. Not actually solving the underlying issue, but for me they started working if I did a hard reset of z2m

**Comment by The0d-lin** [comment]
I have this exact problem. How did you hard reset zigbee2mqtt? Did you have to reconnect every zigbee device after that?

**Comment by peec** [comment]
Having same problem with my elko paired as WDE002961
