### ISSUE TITLE
GL-C-003P recognised as GL-C-006P + OTA Errors

### ISSUE THREAD

**Issue by Xitro01** [Koenkk/zigbee2mqtt#15919]
### The problem

I have the GL-C-003P (Zigbee 2 Wires CCT / DIM 2IN1 LED Controller Pro), but it is recognized as the GL-C-006P.

The description and picture are not correct in the Zigbee2MQTT database:
- the GL-C-003P is a CCT Pro 2-wire unit,
- the GL-C-006P is a CCT Pro 3-wire unit.

The database says that the 003P is a RGB unit, which it's not.

This is not really a problem, as it works great. But I get OTA errors:
```
Debug 2023-01-03 14:55:51Received MQTT message on 'zigbee2mqtt/bridge/request/device/ota_update/check' with data '{"id":"Keukenblad","transaction":"utrdm-4"}'
Info 2023-01-03 14:55:51Checking if update available for 'Keukenblad'
Info 2023-01-03 14:55:51MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Checking if update available for 'Keukenblad'","meta":{"device":"Keukenblad","status":"checking_if_available"},"type":"ota_update"}'
Debug 2023-01-03 14:55:51Check if update available for '0xa4c1381ebee6316c' (GL-C-006P)
Debug 2023-01-03 14:55:51Using endpoint '1'
Debug 2023-01-03 14:55:51Received Zigbee message from 'Keukenblad', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":268513281,"imageType":5139,"manufacturerCode":4687}' from endpoint 1 with groupID 0
Debug 2023-01-03 14:55:51Got OTA request '{"fieldControl":0,"manufacturerCode":4687,"imageType":5139,"fileVersion":268513281}'
Debug 2023-01-03 14:55:51ZigbeeOTA: downloaded main index
Info 2023-01-03 14:55:51MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Failed to check if update available for 'Keukenblad' (No image available for imageType '5139')","meta":{"device":"Keukenblad","status":"check_failed"},"type":"ota_update"}'
Info 2023-01-03 14:55:51MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"Keukenblad"},"error":"Failed to check if update available for 'Keukenblad' (No image available for imageType '5139')","status":"error","transaction":"utrdm-4"}'
Error 2023-01-03 14:55:51Failed to check if update available for 'Keukenblad' (No image available for imageType '5139')
Debug 2023-01-03 14:55:51Error: No image available for imageType '5139' at getImageMeta (/app/node_modules/zigbee-herdsman-converters/lib/ota/zigbeeOTA.js:113:15) at processTicksAndRejections (node:internal/process/task_queues:96:5) at isNewImageAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:260:18) at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:251:23) at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:205:45)
```

This keeps popping up in my logs every couple of minutes:
```
Debug 2023-01-03 14:55:44Device 'Keukenblad' requested OTA
```

### Zigbee2MQTT version

1.29.0

### Adapter firmware version

20220219

### Adapter

zzh!

### Device info

Firmware: 10051203
Firmware build date: 20220422

**Comment by Xitro01** [comment]
Still an issue.

**Comment by Xitro01** [comment]
bumpetibump

**Comment by wrozwad** [comment]
bump
