### ISSUE TITLE
Sonoff E-dongle keeps disconnecting over and over again

### ISSUE THREAD

**Issue by JacekKac** [Koenkk/zigbee2mqtt#15994]
### What happened?

Since 2 days my adapter is disconnecting and reconnecting again.  Sometimes is changing the TTYUSBx port . I can fix this by putting  /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0, but it'is still disconnecting 

```
[Fri Jan  6 21:28:21 2023] ch341-uart ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[Fri Jan  6 21:28:21 2023] ch341-uart ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[Fri Jan  6 21:28:21 2023] usb 1-1.4: USB disconnect, device number 11
[Fri Jan  6 21:28:21 2023] usb 1-1.4: ch341_read_int_callback - usb_submit_urb failed: -19
[Fri Jan  6 21:28:21 2023] usb 1-1.4: failed to send control message: -19
[Fri Jan  6 21:28:21 2023] ch341-uart ttyUSB0: ch341-uart converter now disconnected from ttyUSB0
[Fri Jan  6 21:28:21 2023] ch341 1-1.4:1.0: device disconnected
[Fri Jan  6 21:28:21 2023] usb 1-1.4: new full-speed USB device number 12 using dwc_otg
[Fri Jan  6 21:28:21 2023] usb 1-1.4: New USB device found, idVendor=1a86, idProduct=7523, bcdDevice=81.34
[Fri Jan  6 21:28:21 2023] usb 1-1.4: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[Fri Jan  6 21:28:21 2023] usb 1-1.4: Product: USB Serial
[Fri Jan  6 21:28:21 2023] ch341 1-1.4:1.0: ch341-uart converter detected
[Fri Jan  6 21:28:21 2023] usb 1-1.4: ch341-uart converter now attached to ttyUSB0
[Fri Jan  6 21:28:51 2023] ch341-uart ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[Fri Jan  6 21:28:51 2023] ch341-uart ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[Fri Jan  6 21:28:51 2023] usb 1-1.4: USB disconnect, device number 12
[Fri Jan  6 21:28:51 2023] usb 1-1.4: failed to send control message: -19
[Fri Jan  6 21:28:51 2023] ch341-uart ttyUSB0: ch341-uart converter now disconnected from ttyUSB0
[Fri Jan  6 21:28:51 2023] ch341 1-1.4:1.0: device disconnected
[Fri Jan  6 21:28:51 2023] usb 1-1.4: new full-speed USB device number 13 using dwc_otg
[Fri Jan  6 21:28:51 2023] usb 1-1.4: New USB device found, idVendor=1a86, idProduct=7523, bcdDevice=81.34
[Fri Jan  6 21:28:51 2023] usb 1-1.4: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[Fri Jan  6 21:28:51 2023] usb 1-1.4: Product: USB Serial
[Fri Jan  6 21:28:51 2023] ch341 1-1.4:1.0: ch341-uart converter detected
[Fri Jan  6 21:28:51 2023] usb 1-1.4: ch341-uart converter now attached to ttyUSB1

```

```
error 2023-01-06 21:43:31: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:58:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:101:27)
    at start (/opt/zigbee2mqtt/index.js:109:5)

```
it seems like more host issue - anyone ? tomorrow i will check with new power source /port/ usb cable 

### What did you expect to happen?

nothing special:)

### How to reproduce it (minimal and precise)

it's repeating every few minutes

### Zigbee2MQTT version

version 1.28.0-dev (commit #e3dcc7b)

### Adapter firmware version

20220301

### Adapter

SONOFF E DONGLE

**Comment by JacekKac** [comment]
1/ power supply new - no more warnings about undervoltage.
2/ uname -r Linux host 5.15.84-v7+ #1613 SMP Thu Jan 5 11:59:48 GMT 2023 armv7l GNU/Linux
3/ todays logs: 

[Sat Jan  7 14:41:49 2023] usb 1-1.4: failed to send control message: -19
[Sat Jan  7 14:41:49 2023] ch341-uart ttyUSB0: ch341-uart converter now disconnected from ttyUSB0
[Sat Jan  7 14:41:49 2023] ch341 1-1.4:1.0: device disconnected
[Sat Jan  7 14:41:50 2023] usb 1-1.4: new full-speed USB device number 5 using dwc_otg
[Sat Jan  7 14:41:50 2023] usb 1-1.4: New USB device found, idVendor=1a86, idProduct=7523, bcdDevice=81.34
[Sat Jan  7 14:41:50 2023] usb 1-1.4: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[Sat Jan  7 14:41:50 2023] usb 1-1.4: Product: USB Serial
[Sat Jan  7 14:41:50 2023] ch341 1-1.4:1.0: ch341-uart converter detected
[Sat Jan  7 14:41:50 2023] usb 1-1.4: ch341-uart converter now attached to ttyUSB0
[Sat Jan  7 16:56:15 2023] ch341-uart ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[Sat Jan  7 16:56:15 2023] ch341-uart ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[Sat Jan  7 16:56:15 2023] usb 1-1.4: USB disconnect, device number 5
[Sat Jan  7 16:56:15 2023] usb 1-1.4: failed to send control message: -19
[Sat Jan  7 16:56:15 2023] ch341-uart ttyUSB0: ch341-uart converter now disconnected from ttyUSB0
[Sat Jan  7 16:56:15 2023] ch341 1-1.4:1.0: device disconnected
[Sat Jan  7 16:56:15 2023] usb 1-1.4: new full-speed USB device number 6 using dwc_otg
[Sat Jan  7 16:56:15 2023] usb 1-1.4: New USB device found, idVendor=1a86, idProduct=7523, bcdDevice=81.34
[Sat Jan  7 16:56:15 2023] usb 1-1.4: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[Sat Jan  7 16:56:15 2023] usb 1-1.4: Product: USB Serial
[Sat Jan  7 16:56:15 2023] ch341 1-1.4:1.0: ch341-uart converter detected
[Sat Jan  7 16:56:15 2023] usb 1-1.4: ch341-uart converter now attached to ttyUSB0
[Sat Jan  7 18:08:37 2023] ch341-uart ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[Sat Jan  7 18:08:37 2023] ch341-uart ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[Sat Jan  7 18:08:37 2023] usb 1-1.4: USB disconnect, device number 6
[Sat Jan  7 18:08:37 2023] usb 1-1.4: failed to send control message: -19
[Sat Jan  7 18:08:37 2023] ch341-uart ttyUSB0: ch341-uart converter now disconnected from ttyUSB0
[Sat Jan  7 18:08:37 2023] ch341 1-1.4:1.0: device disconnected
[Sat Jan  7 18:08:38 2023] usb 1-1.4: new full-speed USB device number 7 using dwc_otg
[Sat Jan  7 18:08:38 2023] usb 1-1.4: New USB device found, idVendor=1a86, idProduct=7523, bcdDevice=81.34
[Sat Jan  7 18:08:38 2023] usb 1-1.4: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[Sat Jan  7 18:08:38 2023] usb 1-1.4: Product: USB Serial
[Sat Jan  7 18:08:38 2023] ch341 1-1.4:1.0: ch341-uart converter detected
[Sat Jan  7 18:08:38 2023] usb 1-1.4: ch341-uart converter now attached to ttyUSB0

raspberry is placed near heating source, but it's working stable (other apps, and host itself, only the usb has a problem 
 vcgencmd measure_temp
temp=53.2'C
