### ISSUE TITLE
cannot add devices/ end points of devices to group

### ISSUE THREAD

**Issue by alamoudimoh** [Koenkk/zigbee2mqtt#15993]
### What happened?

I am trying to create groups in z2m, 

i have 4 switches, each has two end points (left and right) i managed to add the left for each of the switches, however i cannot add the right ones, i tried adding the left first then right, did not work. tried the other way around also did not work 

### What did you expect to happen?

all selected end points to be added

### How to reproduce it (minimal and precise)

1. create group.
2. add first end point
3. add second end point
4. so on

### Zigbee2MQTT version

1.29.1

### Adapter firmware version

0x26660700

### Adapter

ConBee2/RaspBee2

### Debug log

Received MQTT message on 'zigbee2mqtt/bridge/request/group/members/add' with data '{"device":"0x00158d0005d43ceb/right","group":"Kids Switches","transaction":"8ts2o-2"}'
Info 2023-01-06 22:50:05Adding 'Kids Switch 02' to 'Kids Switches'
Debug 2023-01-06 22:50:08Received Zigbee message from 'Master WC Switch', type 'attributeReport', cluster 'aqaraOpple', data '{"223":{"data":[0,35,77,54,18,0,1,35,115,206,0,0,2,35,215,28,0,0,3,35,162,59,0,0,4,33,202,7,5,33,195,2,18,33,4,3,21,33,7,3,6,33,98,0,7,33,2,0,8,33,247,7,9,33,56,19,10,33,0,0,11,33,0,0,19,33,0,0,20,33,0,0],"type":"Buffer"}}' from endpoint 1 with groupID null
Debug 2023-01-06 22:50:08lumi.switch.n3acn3: unknown key 223 with value #M6#s�#�#�;!�!�!!!b!!� !8 !!!!
Debug 2023-01-06 22:50:08lumi.switch.n3acn3: Processed data into payload {}
Debug 2023-01-06 22:50:10Received Zigbee message from 'Master WC Switch', type 'attributeReport', cluster 'aqaraOpple', data '{"223":{"data":[22,33,0,0,23,33,0,0,12,33,10,0,24,33,154,16,30,33,179,1,31,33,49,46,32,33,212,134,34,33,172,167,35,33,0,0,36,32,0,37,35,252,167,59,58,250,33,0,0,251,33,0,0,252,35,0,0,0,0,253,35,0,0,0,0,254,35,128,0,1,0],"type":"Buffer"}}' from endpoint 1 with groupID null
Debug 2023-01-06 22:50:10lumi.switch.n3acn3: unknown key 223 with value !!! !�!�!1. !Ԇ"!��#!$ %#��;:�!�!�#�#�#�
Debug 2023-01-06 22:50:10lumi.switch.n3acn3: Processed data into payload {}
Debug 2023-01-06 22:50:11Error: Command 0x00158d0005869a92/2 genGroups.add({"groupid":20,"groupname":""}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received) at DeconzAdapter.sendZclFrameToEndpoint (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:658:23) at Endpoint.sendRequest (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:299:20) at Endpoint.command (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:772:28) at Endpoint.addToGroup (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:868:9) at Groups.onMQTTMessage (/app/lib/extension/groups.ts:323:21)
Info 2023-01-06 22:50:11MQTT publish: topic 'zigbee2mqtt/bridge/response/group/members/add', payload '{"data":{"device":"0x00158d0005869a92/right","group":"Kids Switches"},"error":"Failed to add from group (Command 0x00158d0005869a92/2 genGroups.add({\"groupid\":20,\"groupname\":\"\"}, {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (no response received))","status":"error","transaction":"8ts2o-1"}'
Error 2023-01-06 22:50:11Failed to add from group (Command 0x00158d0005869a92/2 genGroups.add({"groupid":20,"groupname":""}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received))

**Comment by alamoudimoh** [comment]
@Koenkk your help would be appreciated

**Comment by alamoudimoh** [comment]
@Koenkk , any response would be appreciated.
