### ISSUE TITLE
Interview failed with SNZB-04

### ISSUE THREAD

**Issue by phodina** [Koenkk/zigbee2mqtt#16005]
### What happened?

Hello,
I'm trying to configure the Sonoff Door Sensor SNZB-04. I can see the device in the list of devices.

However, it shows it's not correctly configured. When click on reconfigure it also fails.

I've also tried:
    Force remove device through z2m frontend
    stop z2m
    start z2m
    try to pair device

I don't have other sensors atm but there are people who claim to have it working https://github.com/Koenkk/zigbee2mqtt/issues/13600#issuecomment-1287756456

### What did you expect to happen?

The device is configured correctly and recognized as https://www.zigbee2mqtt.io/devices/SNZB-04.html.

### How to reproduce it (minimal and precise)

Enable paring for z2m and press the switch on the sensor for 5s to se 3 LED flashes.
Then wait and see the configuration fail message in the dashboard.

### Zigbee2MQTT version

1.28.0

### Adapter firmware version

6.10.3-41

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus-E

### Debug log

```
$ zigbee2mqtt
Zigbee2MQTT:debug 2023-01-07 12:12:42: Loaded state from file /home/pethod/.z2m/state.json
Zigbee2MQTT:info  2023-01-07 12:12:42: Logging to console and directory: '/home/pethod/.z2m/log/2023-01-07.12-12-42' filename: log.txt
Zigbee2MQTT:debug 2023-01-07 12:12:42: Removing old log directory '/home/pethod/.z2m/log/2023-01-07.10-03-11'
Zigbee2MQTT:info  2023-01-07 12:12:42: Starting Zigbee2MQTT version 1.28.0 (commit #unknown)
Zigbee2MQTT:info  2023-01-07 12:12:42: Starting zigbee-herdsman (0.14.62)
Zigbee2MQTT:debug 2023-01-07 12:12:42: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/home/pethod/.z2m/coordinator_backup.json","databaseBackupPath":"/home/pethod/.z2m/database.db.backup","databasePath":"/home/pethod/.z2m/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"ezsp","path":"/dev/ttyACM0"}}'
Assertion failed: Command (setValue) returned unexpected state: [object Object]
Assertion failed: Command (setValue) returned unexpected state: [object Object]
Zigbee2MQTT:info  2023-01-07 12:12:45: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2023-01-07 12:12:45: Coordinator firmware version: '{"meta":{"maintrel":"3 ","majorrel":"6","minorrel":"10","product":8,"revision":"6.10.3.0 build 297"},"type":"EZSP v8"}'
Zigbee2MQTT:debug 2023-01-07 12:12:45: Zigbee network parameters: {"channel":11,"extendedPanID":221,"panID":6754}
Zigbee2MQTT:info  2023-01-07 12:12:45: Currently 1 devices are joined:
Zigbee2MQTT:info  2023-01-07 12:12:45: 0x00124b0024ce7007 (0x00124b0024ce7007): SNZB-04 - SONOFF Contact sensor (EndDevice)
Zigbee2MQTT:warn  2023-01-07 12:12:45: `permit_join` set to  `true` in configuration.yaml.
Zigbee2MQTT:warn  2023-01-07 12:12:45: Allowing new devices to join.
Zigbee2MQTT:warn  2023-01-07 12:12:45: Set `permit_join` to `false` once you joined all devices.
Zigbee2MQTT:info  2023-01-07 12:12:45: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2023-01-07 12:12:45: Connecting to MQTT server at mqtt://127.0.0.1
Zigbee2MQTT:debug 2023-01-07 12:12:45: Using MQTT anonymous login
Zigbee2MQTT:info  2023-01-07 12:12:45: Connected to MQTT server
Zigbee2MQTT:info  2023-01-07 12:12:45: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
Zigbee2MQTT:info  2023-01-07 12:12:45: Started frontend on port 0.0.0.0:8080
Zigbee2MQTT:info  2023-01-07 12:12:45: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"unknown","coordinator":{"meta":{"maintrel":"3 ","majorrel":"6","minorrel":"10","product":8,"revision":"6.10.3.0 build 297"},"type":"EZSP v8"},"log_level":"debug","network":{"channel":11,"extendedPanID":221,"panID":6754},"permit_join":true,"version":"1.28.0"}'
Zigbee2MQTT:debug 2023-01-07 12:12:52: Received MQTT message on 'zigbee2mqtt/bridge/request/device/configure' with data '{"id":"0x00124b0024ce7007","transaction":"1tv74-9"}'
Zigbee2MQTT:info  2023-01-07 12:12:52: Configuring '0x00124b0024ce7007'
Zigbee2MQTT:error 2023-01-07 12:12:53: Failed to configure '0x00124b0024ce7007', attempt 1 (Error: Bind 0x00124b0024ce7007/1 genPowerCfg from '0xe0798dfffe718dfc/1' failed (ZdoRequest error)
    at Driver.zdoRequest (/nix/store/dw1byj0i2hals5rinva1bphqzc74sdlp-zigbee2mqtt-1.28.0/lib/node_modules/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:551:19)
    at Object.func (/nix/store/dw1byj0i2hals5rinva1bphqzc74sdlp-zigbee2mqtt-1.28.0/lib/node_modules/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:518:13)
    at Queue.executeNext (/nix/store/dw1byj0i2hals5rinva1bphqzc74sdlp-zigbee2mqtt-1.28.0/lib/node_modules/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32))
Zigbee2MQTT:info  2023-01-07 12:12:53: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"0x00124b0024ce7007"},"error":"Failed to configure (Bind 0x00124b0024ce7007/1 genPowerCfg from '0xe0798dfffe718dfc/1' failed (ZdoRequest error))","status":"error","transaction":"1tv74-9"}'
Zigbee2MQTT:debug 2023-01-07 12:13:03: Received MQTT message on 'zigbee2mqtt/bridge/request/device/configure' with data '{"id":"0x00124b0024ce7007","transaction":"1tv74-10"}'
Zigbee2MQTT:info  2023-01-07 12:13:03: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"0x00124b0024ce7007"},"status":"ok","transaction":"1tv74-10"}'
Zigbee2MQTT:debug 2023-01-07 12:16:27: Received MQTT message on 'zigbee2mqtt/bridge/request/networkmap' with data '{"routes":false,"transaction":"1tv74-11","type":"raw"}'
Zigbee2MQTT:info  2023-01-07 12:16:27: Starting network scan (includeRoutes 'false')
Zigbee2MQTT:debug 2023-01-07 12:16:28: LQI succeeded for 'Coordinator'
Zigbee2MQTT:info  2023-01-07 12:16:28: Network scan finished
Zigbee2MQTT:info  2023-01-07 12:16:28: MQTT publish: topic 'zigbee2mqtt/bridge/response/networkmap', payload '{"data":{"routes":false,"type":"raw","value":{"links":[],"nodes":[{"definition":null,"failed":[],"friendlyName":"Coordinator","ieeeAddr":"0xe0798dfffe718dfc","lastSeen":null,"networkAddress":0,"type":"Coordinator"},{"definition":{"description":"Contact sensor","model":"SNZB-04","supports":"contact, battery_low, battery, voltage, linkquality","vendor":"SONOFF"},"friendlyName":"0x00124b0024ce7007","ieeeAddr":"0x00124b0024ce7007","lastSeen":1673089456102,"manufacturerName":"eWeLink","modelID":"DS01","networkAddress":113,"type":"EndDevice"}]}},"status":"ok","transaction":"1tv74-11"}'
Zigbee2MQTT:debug 2023-01-07 12:17:42: Saving state to file /home/pethod/.z2m/state.json
Zigbee2MQTT:debug 2023-01-07 12:22:42: Saving state to file /home/pethod/.z2m/state.json
Zigbee2MQTT:debug 2023-01-07 12:27:42: Saving state to file /home/pethod/.z2m/state.json
Zigbee2MQTT:debug 2023-01-07 12:32:42: Saving state to file /home/pethod/.z2m/state.json
Zigbee2MQTT:debug 2023-01-07 12:37:42: Saving state to file /home/pethod/.z2m/state.json
```

```
$ mosquitto -v -c mosquitto.conf
1673089964: mosquitto version 1.6.12 starting
1673089964: Config loaded from mosquitto.conf.
1673089964: Opening ipv4 listen socket on port 1883.
1673089964: Opening ipv6 listen socket on port 1883.
1673089964: mosquitto version 1.6.12 running
1673089965: New connection from 127.0.0.1 on port 1883.
1673089965: New client connected from 127.0.0.1 as mqttjs_176cfa0d (p2, c1, k60).
1673089965: Will message specified (7 bytes) (r1, q1).
1673089965: 	zigbee2mqtt/bridge/state
1673089965: Sending CONNACK to mqttjs_176cfa0d (0, 0)
1673089965: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r1, m0, 'zigbee2mqtt/bridge/state', ... (6 bytes))
1673089965: Received SUBSCRIBE from mqttjs_176cfa0d
1673089965: 	zigbee2mqtt/# (QoS 0)
1673089965: mqttjs_176cfa0d 0 zigbee2mqtt/#
1673089965: Sending SUBACK to mqttjs_176cfa0d
1673089965: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r1, m0, 'zigbee2mqtt/bridge/state', ... (6 bytes))
1673089965: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r1, m0, 'zigbee2mqtt/bridge/info', ... (20123 bytes))
1673089965: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/info', ... (20123 bytes))
1673089965: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r1, m0, 'zigbee2mqtt/bridge/devices', ... (2205 bytes))
1673089965: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/devices', ... (2205 bytes))
1673089965: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r1, m0, 'zigbee2mqtt/bridge/groups', ... (2 bytes))
1673089965: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/groups', ... (2 bytes))
1673089965: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r1, m0, 'zigbee2mqtt/bridge/extensions', ... (2 bytes))
1673089965: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/extensions', ... (2 bytes))
1673089965: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (66 bytes))
1673089965: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (66 bytes))
1673089965: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (405 bytes))
1673089965: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (405 bytes))
1673089965: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r1, m0, 'zigbee2mqtt/bridge/config', ... (269 bytes))
1673089965: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/config', ... (269 bytes))
1673089972: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (172 bytes))
1673089972: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (172 bytes))
1673089972: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (61 bytes))
1673089972: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (61 bytes))
1673089973: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (736 bytes))
1673089973: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (736 bytes))
1673089973: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (326 bytes))
1673089973: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (326 bytes))
1673089973: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/response/device/configure', ... (201 bytes))
1673089973: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/response/device/configure', ... (201 bytes))
1673089983: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (173 bytes))
1673089983: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (173 bytes))
1673089983: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (196 bytes))
1673089983: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (196 bytes))
1673089983: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/response/device/configure', ... (75 bytes))
1673089983: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/response/device/configure', ... (75 bytes))
1673090043: Received PINGREQ from mqttjs_176cfa0d
1673090043: Sending PINGRESP to mqttjs_176cfa0d
1673090103: Received PINGREQ from mqttjs_176cfa0d
1673090103: Sending PINGRESP to mqttjs_176cfa0d
1673090163: Received PINGREQ from mqttjs_176cfa0d
1673090163: Sending PINGRESP to mqttjs_176cfa0d
1673090187: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (171 bytes))
1673090187: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (171 bytes))
1673090187: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (74 bytes))
1673090187: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (74 bytes))
1673090188: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (61 bytes))
1673090188: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (61 bytes))
1673090188: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (50 bytes))
1673090188: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (50 bytes))
1673090188: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (770 bytes))
1673090188: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (770 bytes))
1673090188: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/response/networkmap', ... (585 bytes))
1673090188: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/response/networkmap', ... (585 bytes))
1673090248: Received PINGREQ from mqttjs_176cfa0d
1673090248: Sending PINGRESP to mqttjs_176cfa0d
1673090262: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (79 bytes))
1673090262: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (79 bytes))
1673090322: Received PINGREQ from mqttjs_176cfa0d
1673090322: Sending PINGRESP to mqttjs_176cfa0d
1673090382: Received PINGREQ from mqttjs_176cfa0d
1673090382: Sending PINGRESP to mqttjs_176cfa0d
1673090442: Received PINGREQ from mqttjs_176cfa0d
1673090442: Sending PINGRESP to mqttjs_176cfa0d
1673090502: Received PINGREQ from mqttjs_176cfa0d
1673090502: Sending PINGRESP to mqttjs_176cfa0d
1673090562: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (79 bytes))
1673090562: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (79 bytes))
1673090622: Received PINGREQ from mqttjs_176cfa0d
1673090622: Sending PINGRESP to mqttjs_176cfa0d
1673090682: Received PINGREQ from mqttjs_176cfa0d
1673090682: Sending PINGRESP to mqttjs_176cfa0d
1673090742: Received PINGREQ from mqttjs_176cfa0d
1673090742: Sending PINGRESP to mqttjs_176cfa0d
1673090802: Received PINGREQ from mqttjs_176cfa0d
1673090802: Sending PINGRESP to mqttjs_176cfa0d
1673090862: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (79 bytes))
1673090862: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (79 bytes))
1673090922: Received PINGREQ from mqttjs_176cfa0d
1673090922: Sending PINGRESP to mqttjs_176cfa0d
1673090982: Received PINGREQ from mqttjs_176cfa0d
1673090982: Sending PINGRESP to mqttjs_176cfa0d
1673091042: Received PINGREQ from mqttjs_176cfa0d
1673091042: Sending PINGRESP to mqttjs_176cfa0d
1673091102: Received PINGREQ from mqttjs_176cfa0d
1673091102: Sending PINGRESP to mqttjs_176cfa0d
1673091162: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (79 bytes))
1673091162: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (79 bytes))
1673091222: Received PINGREQ from mqttjs_176cfa0d
1673091222: Sending PINGRESP to mqttjs_176cfa0d
1673091282: Received PINGREQ from mqttjs_176cfa0d
1673091282: Sending PINGRESP to mqttjs_176cfa0d
1673091342: Received PINGREQ from mqttjs_176cfa0d
1673091342: Sending PINGRESP to mqttjs_176cfa0d
1673091402: Received PINGREQ from mqttjs_176cfa0d
1673091402: Sending PINGRESP to mqttjs_176cfa0d
1673091462: Received PUBLISH from mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (79 bytes))
1673091462: Sending PUBLISH to mqttjs_176cfa0d (d0, q0, r0, m0, 'zigbee2mqtt/bridge/logging', ... (79 bytes))
1673091522: Received PINGREQ from mqttjs_176cfa0d
1673091522: Sending PINGRESP to mqttjs_176cfa0d
1673091582: Received PINGREQ from mqttjs_176cfa0d
1673091582: Sending PINGRESP to mqttjs_176cfa0d
1673091642: Received PINGREQ from mqttjs_176cfa0d
1673091642: Sending PINGRESP to mqttjs_176cfa0d
```

**Comment by kizio1000** [comment]
I have two of them and couple of other SNZB-xx devices. They all suck (disappear from network, go off-line, etc) Usually it helps to remove battery before repairing. I was reading changelog of z2m v.1.29  and there was info that SNZB devices were fixed, so far I did not noticed any improvement in this aspect after updating to 1.29.1 which has by the way serous problems working with my sonoff E, so I went back to 1.28.4 which sucks at working with SNZB devices...

**Comment by phodina** [comment]
Okay, thanks for the info. I'll try to remove the battery and repair the device. 

Do you have some other brand you'd recommend that's more reliable then?

**Comment by phodina** [comment]
Also I found mention of the issues in this discussion https://github.com/Koenkk/zigbee2mqtt/discussions/10989

**Comment by phodina** [comment]
Got there working for now by inserting some cardboard to push properly the coin cell battery

**Comment by kub3let** [comment]
I just migrated from tasmota2mqtt to zigbee2mqtt.

This is the first sensors that I connected and for some reason no matter what I do it says interview failed.

The battery has good connection, I bend the pins.

Everything is working, it reports open/close instantly and battery is displayed as well, so wondering what interview failed means and whether I should care about it ?
