### ISSUE TITLE
Robbshop Bulb G125 / EcoDim ED-10041

### ISSUE THREAD

**Issue by JamesBlont** [Koenkk/zigbee2mqtt#16045]
### What happened?

The light bulb lost connection to Home Assistant / ZIGBEE2MQTT. While resetting it I get errors.

Failed to configure '0x00158d000539fa08', attempt 1 (Error: DatabaseEntry with ID '9' does not exist at Database.update (/app/node_modules/zigbee-herdsman/src/controller/database.ts:44:19) at Device.save (/app/node_modules/zigbee-herdsman/src/controller/model/device.ts:358:25) at Configure.configure (/app/lib/extension/configure.ts:121:23) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:21))

This white lable bulb is recognized as a Ecodim ED-10041.  Recently there was a change in ZIGBEE2MQTT for this type of bulb but that is creating problems in my case. The bulb (I have 17 of them) are working fine in HA but this one lost connection. Whe I reset it there is a pairing problem

### What did you expect to happen?

Succesvol pair when I reset the bulb.

### Zigbee2MQTT version

1.29.1-1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2

### Debug log

Info 2023-01-09 09:58:47Device '0x00158d000539fa08' joined
Info 2023-01-09 09:58:47MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00158d000539fa08","ieee_address":"0x00158d000539fa08"},"type":"device_joined"}'
Info 2023-01-09 09:58:47MQTT publish: topic 'homeassistant/light/0x00158d000539fa08/light/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"brightness":true,"brightness_scale":254,"color_mode":true,"command_topic":"zigbee2mqtt/0x00158d000539fa08/set","device":{"identifiers":["zigbee2mqtt_0x00158d000539fa08"],"manufacturer":"EcoDim","model":"Zigbee LED filament light dimmable E27, edison ST64, flame 2200K (ED-10041)","name":"0x00158d000539fa08","sw_version":"00.00.01"},"effect":true,"effect_list":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"max_mireds":454,"min_mireds":153,"name":"0x00158d000539fa08","schema":"json","state_topic":"zigbee2mqtt/0x00158d000539fa08","supported_color_modes":["color_temp"],"unique_id":"0x00158d000539fa08_light_zigbee2mqtt"}'
Info 2023-01-09 09:58:47MQTT publish: topic 'homeassistant/select/0x00158d000539fa08/effect/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/0x00158d000539fa08/set/effect","device":{"identifiers":["zigbee2mqtt_0x00158d000539fa08"],"manufacturer":"EcoDim","model":"Zigbee LED filament light dimmable E27, edison ST64, flame 2200K (ED-10041)","name":"0x00158d000539fa08","sw_version":"00.00.01"},"enabled_by_default":false,"icon":"mdi:palette","name":"0x00158d000539fa08 effect","options":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"unique_id":"0x00158d000539fa08_effect_zigbee2mqtt"}'
Info 2023-01-09 09:58:47MQTT publish: topic 'homeassistant/sensor/0x00158d000539fa08/power_on_behavior/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x00158d000539fa08"],"manufacturer":"EcoDim","model":"Zigbee LED filament light dimmable E27, edison ST64, flame 2200K (ED-10041)","name":"0x00158d000539fa08","sw_version":"00.00.01"},"enabled_by_default":false,"entity_category":"config","icon":"mdi:power-settings","name":"0x00158d000539fa08 power on behavior","state_topic":"zigbee2mqtt/0x00158d000539fa08","unique_id":"0x00158d000539fa08_power_on_behavior_zigbee2mqtt","value_template":"{{ value_json.power_on_behavior }}"}'
Info 2023-01-09 09:58:47MQTT publish: topic 'homeassistant/select/0x00158d000539fa08/power_on_behavior/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/0x00158d000539fa08/set/power_on_behavior","device":{"identifiers":["zigbee2mqtt_0x00158d000539fa08"],"manufacturer":"EcoDim","model":"Zigbee LED filament light dimmable E27, edison ST64, flame 2200K (ED-10041)","name":"0x00158d000539fa08","sw_version":"00.00.01"},"entity_category":"config","icon":"mdi:power-settings","name":"0x00158d000539fa08 power on behavior","options":["off","on","toggle","previous"],"state_topic":"zigbee2mqtt/0x00158d000539fa08","unique_id":"0x00158d000539fa08_power_on_behavior_zigbee2mqtt","value_template":"{{ value_json.power_on_behavior }}"}'
Info 2023-01-09 09:58:47MQTT publish: topic 'homeassistant/sensor/0x00158d000539fa08/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x00158d000539fa08"],"manufacturer":"EcoDim","model":"Zigbee LED filament light dimmable E27, edison ST64, flame 2200K (ED-10041)","name":"0x00158d000539fa08","sw_version":"00.00.01"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"0x00158d000539fa08 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x00158d000539fa08","unique_id":"0x00158d000539fa08_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Info 2023-01-09 09:58:47Starting interview of '0x00158d000539fa08'
Info 2023-01-09 09:58:47MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00158d000539fa08","ieee_address":"0x00158d000539fa08","status":"started"},"type":"device_interview"}'
Debug 2023-01-09 09:58:47Received MQTT message on 'homeassistant/light/0x00158d000539fa08/light/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"brightness":true,"brightness_scale":254,"color_mode":true,"command_topic":"zigbee2mqtt/0x00158d000539fa08/set","device":{"identifiers":["zigbee2mqtt_0x00158d000539fa08"],"manufacturer":"EcoDim","model":"Zigbee LED filament light dimmable E27, edison ST64, flame 2200K (ED-10041)","name":"0x00158d000539fa08","sw_version":"00.00.01"},"effect":true,"effect_list":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"max_mireds":454,"min_mireds":153,"name":"0x00158d000539fa08","schema":"json","state_topic":"zigbee2mqtt/0x00158d000539fa08","supported_color_modes":["color_temp"],"unique_id":"0x00158d000539fa08_light_zigbee2mqtt"}'
Debug 2023-01-09 09:58:47Received MQTT message on 'homeassistant/select/0x00158d000539fa08/effect/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/0x00158d000539fa08/set/effect","device":{"identifiers":["zigbee2mqtt_0x00158d000539fa08"],"manufacturer":"EcoDim","model":"Zigbee LED filament light dimmable E27, edison ST64, flame 2200K (ED-10041)","name":"0x00158d000539fa08","sw_version":"00.00.01"},"enabled_by_default":false,"icon":"mdi:palette","name":"0x00158d000539fa08 effect","options":["blink","breathe","okay","channel_change","finish_effect","stop_effect"],"unique_id":"0x00158d000539fa08_effect_zigbee2mqtt"}'
Debug 2023-01-09 09:58:47Received MQTT message on 'homeassistant/sensor/0x00158d000539fa08/power_on_behavior/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x00158d000539fa08"],"manufacturer":"EcoDim","model":"Zigbee LED filament light dimmable E27, edison ST64, flame 2200K (ED-10041)","name":"0x00158d000539fa08","sw_version":"00.00.01"},"enabled_by_default":false,"entity_category":"config","icon":"mdi:power-settings","name":"0x00158d000539fa08 power on behavior","state_topic":"zigbee2mqtt/0x00158d000539fa08","unique_id":"0x00158d000539fa08_power_on_behavior_zigbee2mqtt","value_template":"{{ value_json.power_on_behavior }}"}'
Debug 2023-01-09 09:58:47Received MQTT message on 'homeassistant/select/0x00158d000539fa08/power_on_behavior/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/0x00158d000539fa08/set/power_on_behavior","device":{"identifiers":["zigbee2mqtt_0x00158d000539fa08"],"manufacturer":"EcoDim","model":"Zigbee LED filament light dimmable E27, edison ST64, flame 2200K (ED-10041)","name":"0x00158d000539fa08","sw_version":"00.00.01"},"entity_category":"config","icon":"mdi:power-settings","name":"0x00158d000539fa08 power on behavior","options":["off","on","toggle","previous"],"state_topic":"zigbee2mqtt/0x00158d000539fa08","unique_id":"0x00158d000539fa08_power_on_behavior_zigbee2mqtt","value_template":"{{ value_json.power_on_behavior }}"}'
Debug 2023-01-09 09:58:47Received MQTT message on 'homeassistant/sensor/0x00158d000539fa08/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0x00158d000539fa08"],"manufacturer":"EcoDim","model":"Zigbee LED filament light dimmable E27, edison ST64, flame 2200K (ED-10041)","name":"0x00158d000539fa08","sw_version":"00.00.01"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"0x00158d000539fa08 linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/0x00158d000539fa08","unique_id":"0x00158d000539fa08_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Error 2023-01-09 09:59:07Failed to interview '0x00158d000539fa08', device has not successfully been paired
Info 2023-01-09 09:59:07MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00158d000539fa08","ieee_address":"0x00158d000539fa08","status":"failed"},"type":"device_interview"}'

**Comment by JamesBlont** [comment]
It is working again. The bulb was in pairing mode but not reset. After a correct reset and placing it nearby the controler the bubl was paired in seconds
