### ISSUE TITLE
Error on OTA for OSRAM 4052899926110 LED strip

### ISSUE THREAD

**Issue by nanobra1n** [Koenkk/zigbee2mqtt#16069]
### What happened?

Checking for new firmware for my OSRAM led strip generates the following error message:
```
Error 2023-01-09 16:47:26 Failed to check if update available for 'Desk LED' (No image available for manufacturerCode '4364' imageType '2')
Debug 2023-01-09 16:47:26 AssertionError [ERR_ASSERTION]: No image available for manufacturerCode '4364' imageType '2' at getImageMeta (/app/node_modules/zigbee-herdsman-converters/lib/ota/ledvance.js:17:5) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at isNewImageAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:260:18) at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:251:29) at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:205:45)
```
The front end identifies the Firmware built date as `20160204N****` and the firmware version is empty

### What did you expect to happen?

Either update available or not

### Zigbee2MQTT version

1.29.1

### Adapter firmware version

20221102

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus

**Comment by nanobra1n** [comment]
Issue persists in 1.30.1
