### ISSUE TITLE
[New device support]: LTO003 Philips Hue G125 B22 White Ambiance Filament Bulb

### ISSUE THREAD

**Issue by sdriessens** [Koenkk/zigbee2mqtt#16071]
### Link

https://www.philips-hue.com/en-au/p/hue-white-ambiance-filament-g125-globe---b22-smart-bulb/8719514392939#overview

### Database entry

{"id":3,"type":"Router","ieeeAddr":"0x001788010bf6534c","nwkAddr":34172,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Mains (single phase)","modelId":"LTO003","epList":[11,242],"endpoints":{"11":{"profId":260,"epId":11,"devId":268,"inClusterList":[0,3,4,5,6,8,4096,64515,768],"outClusterList":[25],"clusters":{"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":222,"colorTempPhysicalMax":454}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20221115","swBuildId":"1.101.7","zclVersion":8,"interviewCompleted":true,"meta":{"configured":88764544},"lastSeen":1673306554737,"defaultSendRequestWhen":"immediate"}

### Comments

I tried following the support page and got stuck with a syntax error in the declaration of hueExtend. I copied the hueExtend declaration from here.
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/philips.js

The light is similar to LW003, but has a different fitting.

I also doubled checked syntax and compared mine against this reference, and it seems the same.
https://github.com/Koenkk/zigbee2mqtt/discussions/14250#discussioncomment-3764882

This is the error I received.

/app/data/extension/externally-loaded.js:13
};
 ^
SyntaxError: Unexpected token ';'
    at new Script (node:vm:100:7)
    at createScript (node:vm:265:10)
    at Object.runInNewContext (node:vm:306:10)
    at loadModuleFromText (/app/lib/util/utils.ts:150:8)
    at loadModuleFromFile (/app/lib/util/utils.ts:157:12)
    at Object.getExternalConvertersDefinitions (/app/lib/util/utils.ts:167:25)
    at getExternalConvertersDefinitions.next (<anonymous>)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:12:20)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)

### External converter

```shell
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const ota = require('zigbee-herdsman-converters/lib/ota');
const extendDontUse = require('zigbee-herdsman-converters/lib/extend');

const hueExtend = {
    light_onoff_brightness: (options={}) => ({
        ...extendDontUse.light_onoff_brightness(options),
        ota: ota.zigbeeOTA,
        meta: {turnsOffAtBrightness1: true},
        toZigbee: extendDontUse.light_onoff_brightness(options).toZigbee.concat([
            tzLocal.hue_power_on_behavior, tzLocal.hue_power_on_error,
        ]),
};

const definition = {
    zigbeeModel: ['LTO003'],
    model: '9290024782',
    vendor: 'Philips',
    description: 'Philips Hue G125 B22 White Ambiance Filament Bulb',
    extend: hueExtend.light_onoff_brightness(),
};

module.exports = definition;
```

### Supported color modes

color temperature

### Color temperature range

{"colorTempPhysicalMin":222,"colorTempPhysicalMax":454}

**Comment by sdriessens** [comment]
Thanks very much! Are you able to tell me what I did wrong/how to do it in the future?

I was able to get most things working with the following block, but obviously without the extra hue sauce and customisation. What was my error in syntax?

“””
const extend = require('zigbee-herdsman-converters/lib/extend');

const definition = {
    zigbeeModel: ['LTO003'],
    model: '9290024782',
    vendor: 'Philips',
    description: 'Hue G125 B22 White Ambiance filament bulb',
    extend: extend.light_onoff_brightness_colortemp({colorTempRange: [222, 454]}),
};

module.exports = definition;
“””
