### ISSUE TITLE
Z2M add On Causes HA to become unresponsive, unusable

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#16110]
### What happened?

For some reason when the Z2M add on starts Home Assistant starts to become unresponsive, and eventually restarts on its on or the Loading data screen just sits here spinning.

When I do a hard reboot of HA, i then stop Z2m Add On and HA has goes back be responsive.

### What did you expect to happen?

Well i expected home assistant to not be affected this badly

### How to reproduce it (minimal and precise)

By Starting the Z2M Add On in Home Assistant

### Zigbee2MQTT version

Zigbee2MQTT Edge

### Adapter firmware version

20220219

### Adapter

Sonoff Coordinator P

### Debug log
```
Zigbee2MQTT:debug 12-01-2023 20:24:36: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  12-01-2023 20:24:36: Logging to console and directory: '/config/zigbee2mqtt/log/2023-01-12.20-24-36' filename: log.txt
Zigbee2MQTT:debug 12-01-2023 20:24:36: Removing old log directory '/config/zigbee2mqtt/log/2023-01-12.15-41-54'
Zigbee2MQTT:info  12-01-2023 20:24:36: Starting Zigbee2MQTT version 1.29.1-dev (commit #328b9fb)
Zigbee2MQTT:info  12-01-2023 20:24:36: Starting zigbee-herdsman (0.14.87)
Zigbee2MQTT:debug 12-01-2023 20:24:36: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[25],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyUSB0"}}'
Zigbee2MQTT:error 12-01-2023 20:24:36: Error while starting zigbee-herdsman
Zigbee2MQTT:error 12-01-2023 20:24:36: Failed to start zigbee
Zigbee2MQTT:error 12-01-2023 20:24:36: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 12-01-2023 20:24:36: Exiting...
Zigbee2MQTT:error 12-01-2023 20:24:36: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyUSB0'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/app/node_modules/@serialport/stream/dist/index.js:76:22)
    at /app/node_modules/@serialport/stream/dist/index.js:112:18
```
_No response_

**Comment by cloudbr34k84** [comment]
> ls /dev

unfortunately it seams I have had to complete wipe  my home assistant and start again :( I have only been using HA for 12 months and i think its not a bad thing!
