### ISSUE TITLE
Issue with the addon, or stick?

### ISSUE THREAD

**Issue by odechr** [Koenkk/zigbee2mqtt#16370]
### What happened?

Addon wont start. Have used this before on the same test machine..
I have no idea if the zigbee stick is dead or not?

### Zigbee2MQTT version

1.29.2-1 

### Adapter firmware version

N/A

### Adapter

Electrolama zig-ah-zig-ah!

### Debug log

2023-01-26T14:32:33.211Z zigbee-herdsman:adapter:zStack:startup:strategy determining znp startup strategy
2023-01-26T14:32:33.211Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvLength - {"id":96}
2023-01-26T14:32:33.212Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,2,33,19,96,0,80]
2023-01-26T14:32:33.218Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,19,1,0,113]
2023-01-26T14:32:33.219Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,19,1,0,113]
2023-01-26T14:32:33.219Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 19 - [1,0] - 113
2023-01-26T14:32:33.219Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvLength - {"length":1}
2023-01-26T14:32:33.219Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-01-26T14:32:33.220Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":96,"offset":0}
2023-01-26T14:32:33.220Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,96,0,0,0,89]
2023-01-26T14:32:33.228Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,97,28,0,1,85,42]
2023-01-26T14:32:33.228Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,97,28,0,1,85,42]
2023-01-26T14:32:33.228Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 3 - 1 - 28 - [0,1,85] - 42
2023-01-26T14:32:33.229Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":0,"len":1,"value":{"type":"Buffer","data":[85]}}
2023-01-26T14:32:33.229Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-01-26T14:32:33.231Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvLength - {"id":33}
2023-01-26T14:32:33.232Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,2,33,19,33,0,17]
2023-01-26T14:32:33.239Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,19,116,0,4]
2023-01-26T14:32:33.239Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,19,116,0,4]
2023-01-26T14:32:33.239Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 19 - [116,0] - 4
2023-01-26T14:32:33.239Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvLength - {"length":116}
2023-01-26T14:32:33.239Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-01-26T14:32:33.240Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":33,"offset":0}
2023-01-26T14:32:33.241Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,33,0,0,0,24]
2023-01-26T14:32:33.249Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,118,97,28,0,116,40,5,2,51,15,51,0,30,0,0,0,1,5,1,143,0,7,0,2,13,30,0,0,0,11,0]
2023-01-26T14:32:33.250Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,118,97,28,0,116,40,5,2,51,15,51,0,30,0,0,0,1,5,1,143,0,7,0,2,13,30,0,0,0,11,0]
2023-01-26T14:32:33.252Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [0,0,0,0,0,0,0,0,0,0,98,26,8,0,0,8,0,0,15,15,4,0,1,0,0,0,1,0,0,0,0,179]
2023-01-26T14:32:33.252Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,118,97,28,0,116,40,5,2,51,15,51,0,30,0,0,0,1,5,1,143,0,7,0,2,13,30,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,98,26,8,0,0,8,0,0,15,15,4,0,1,0,0,0,1,0,0,0,0,179]
2023-01-26T14:32:33.254Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [30,165,34,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
2023-01-26T14:32:33.255Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,118,97,28,0,116,40,5,2,51,15,51,0,30,0,0,0,1,5,1,143,0,7,0,2,13,30,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,98,26,8,0,0,8,0,0,15,15,4,0,1,0,0,0,1,0,0,0,0,179,30,165,34,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
2023-01-26T14:32:33.259Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [0,0,0,0,0,0,0,0,0,0,0,0,15,5,0,1,100,10,1,0,0,0,84,19,0,0,251]
2023-01-26T14:32:33.259Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,118,97,28,0,116,40,5,2,51,15,51,0,30,0,0,0,1,5,1,143,0,7,0,2,13,30,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,98,26,8,0,0,8,0,0,15,15,4,0,1,0,0,0,1,0,0,0,0,179,30,165,34,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,5,0,1,100,10,1,0,0,0,84,19,0,0,251]
2023-01-26T14:32:33.260Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 118 - 3 - 1 - 28 - [0,116,40,5,2,51,15,51,0,30,0,0,0,1,5,1,143,0,7,0,2,13,30,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,98,26,8,0,0,8,0,0,15,15,4,0,1,0,0,0,1,0,0,0,0,179,30,165,34,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,5,0,1,100,10,1,0,0,0,84,19,0,0] - 251
2023-01-26T14:32:33.260Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":0,"len":116,"value":{"type":"Buffer","data":[40,5,2,51,15,51,0,30,0,0,0,1,5,1,143,0,7,0,2,13,30,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,98,26,8,0,0,8,0,0,15,15,4,0,1,0,0,0,1,0,0,0,0,179,30,165,34,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,5,0,1,100,10,1,0,0,0,84,19,0,0]}}
2023-01-26T14:32:33.260Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-01-26T14:32:33.266Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvLength - {"id":98}
2023-01-26T14:32:33.266Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,2,33,19,98,0,82]
2023-01-26T14:32:33.277Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,19,16,0,96]
2023-01-26T14:32:33.278Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,19,16,0,96]
2023-01-26T14:32:33.278Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 19 - [16,0] - 96
2023-01-26T14:32:33.278Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvLength - {"length":16}
2023-01-26T14:32:33.278Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-01-26T14:32:33.279Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":98,"offset":0}
2023-01-26T14:32:33.279Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,98,0,0,0,91]
2023-01-26T14:32:33.297Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,18,97,28,0,16,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13,124]
2023-01-26T14:32:33.297Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,18,97,28,0,16,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13,124]
2023-01-26T14:32:33.297Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 18 - 3 - 1 - 28 - [0,16,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13] - 124
2023-01-26T14:32:33.298Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":0,"len":16,"value":{"type":"Buffer","data":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13]}}
2023-01-26T14:32:33.298Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-01-26T14:32:33.299Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvLength - {"id":58}
2023-01-26T14:32:33.299Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,2,33,19,58,0,10]
2023-01-26T14:32:33.306Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,19,17,0,97]
2023-01-26T14:32:33.306Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,19,17,0,97]
2023-01-26T14:32:33.306Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 19 - [17,0] - 97
2023-01-26T14:32:33.306Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvLength - {"length":17}
2023-01-26T14:32:33.307Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-01-26T14:32:33.307Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":58,"offset":0}
2023-01-26T14:32:33.307Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,58,0,0,0,3]
2023-01-26T14:32:33.318Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,19,97,28,0,17,0,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13,124]
2023-01-26T14:32:33.318Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,19,97,28,0,17,0,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13,124]
2023-01-26T14:32:33.319Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 19 - 3 - 1 - 28 - [0,17,0,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13] - 124
2023-01-26T14:32:33.319Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":0,"len":17,"value":{"type":"Buffer","data":[0,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13]}}
2023-01-26T14:32:33.319Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-01-26T14:32:33.320Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvLength - {"id":59}
2023-01-26T14:32:33.320Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,2,33,19,59,0,11]
2023-01-26T14:32:33.327Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,19,17,0,97]
2023-01-26T14:32:33.327Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,19,17,0,97]
2023-01-26T14:32:33.328Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 19 - [17,0] - 97
2023-01-26T14:32:33.328Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvLength - {"length":17}
2023-01-26T14:32:33.328Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-01-26T14:32:33.328Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":59,"offset":0}
2023-01-26T14:32:33.329Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,59,0,0,0,2]
2023-01-26T14:32:33.340Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,19,97,28,0,17,0,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13,124]
2023-01-26T14:32:33.340Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,19,97,28,0,17,0,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13,124]
2023-01-26T14:32:33.340Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 19 - 3 - 1 - 28 - [0,17,0,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13] - 124
2023-01-26T14:32:33.341Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":0,"len":17,"value":{"type":"Buffer","data":[0,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13]}}
2023-01-26T14:32:33.341Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-01-26T14:32:33.353Z zigbee-herdsman:adapter:zStack:startup:strategy (stage-1) adapter is configured
2023-01-26T14:32:33.354Z zigbee-herdsman:adapter:zStack:startup:strategy (stage-2) adapter state does not match configuration
2023-01-26T14:32:33.354Z zigbee-herdsman:adapter:zStack:startup:strategy (stage-3) got adapter backup
2023-01-26T14:32:33.354Z zigbee-herdsman:adapter:zStack:startup:strategy (stage-4) adapter state matches backup
Zigbee2MQTT:error 2023-01-26 15:32:33: Configuration is not consistent with adapter state/backup!
Zigbee2MQTT:error 2023-01-26 15:32:33: - PAN ID: configured=6754, adapter=6754
Zigbee2MQTT:error 2023-01-26 15:32:33: - Extended PAN ID: configured=00124b0022a51eb3, adapter=00124b0022a51eb3
Zigbee2MQTT:error 2023-01-26 15:32:33: - Network Key: configured=01030507090b0d0f00020406080a0c0d, adapter=01030507090b0d0f00020406080a0c0d
Zigbee2MQTT:error 2023-01-26 15:32:33: - Channel List: configured=16, adapter=11
Zigbee2MQTT:error 2023-01-26 15:32:33: Please update configuration to prevent further issues.
Zigbee2MQTT:error 2023-01-26 15:32:33: If you wish to re-commission your network, please remove coordinator backup at /config/zigbee2mqtt/coordinator_backup.json.
Zigbee2MQTT:error 2023-01-26 15:32:33: Re-commissioning your network will require re-pairing of all devices!
Zigbee2MQTT:error 2023-01-26 15:32:33: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-01-26 15:32:33: Failed to start zigbee
Zigbee2MQTT:error 2023-01-26 15:32:33: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-01-26 15:32:33: Exiting...
Zigbee2MQTT:error 2023-01-26 15:32:33: Error: startup failed - configuration-adapter mismatch - see logs above for more information
    at ZnpAdapterManager.determineStrategy (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:229:35)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:63:26)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)

**Comment by Koenkk** [comment]
Open your zigbee2mqtt configuration.yaml from the HA file editor addon and setting the `channel` to `11` should fix it.
