### ISSUE TITLE
EcoDim.07 OTA (No image available for imageType '60')

### ISSUE THREAD

**Issue by Veldkornet** [Koenkk/zigbee2mqtt#16462]
### What happened?

Recently, my [EcoDim.07](https://www.ecobright.nl/zigbee-led-dimmer-draai-0-250w-ecodim-07-zigbee-pro.html) dimmer gained the ability to check for OTA updates. However, everything I check for an update, I get the following error: 
 `No image available for imageType '60'`

The device is currently on firmware 1.01. Originally discussed here: https://github.com/Koenkk/zigbee2mqtt/issues/15279#issuecomment-1370865762
But nothing was done about it.

### Zigbee2MQTT version

1.30.0

### Adapter firmware version

20221220

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

### Debug log

```
Zigbee2MQTT:debug 2023-01-04 13:26:02: Got OTA request '{"fieldControl":0,"manufacturerCode":4714,"imageType":60,"fileVersion":16869200}'
Zigbee2MQTT:debug 2023-01-04 13:26:02: ZigbeeOTA: downloaded main index
Zigbee2MQTT:info  2023-01-04 13:26:02: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"Badkamer Dimmer"},"error":"Failed to check if update available for 'Badkamer Dimmer' (No image available for imageType '60')","status":"error","transaction":"ds6hc-2"}'
Zigbee2MQTT:error 2023-01-04 13:26:02: Failed to check if update available for 'Badkamer Dimmer' (No image available for imageType '60')
Zigbee2MQTT:debug 2023-01-04 13:26:02: Error: No image available for imageType '60'
    at getImageMeta (/app/node_modules/zigbee-herdsman-converters/lib/ota/zigbeeOTA.js:113:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at isNewImageAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:260:18)
    at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:251:23)
    at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:205:45)
```

**Comment by Veldkornet** [comment]
Nope

**Comment by Veldkornet** [comment]
Nope
