### ISSUE TITLE
Bosch 8750001213 interview failed

### ISSUE THREAD

**Issue by davemeier82** [Koenkk/zigbee2mqtt#16517]
### What happened?

I tried to add the Bosch 8750001213 but the interview fails. 

Thanks for your support

### Zigbee2MQTT version

1.30.0

### Adapter firmware version

20221226

### Adapter

slaesh's CC2652RB

### Debug log

2023-02-04T08:39:45.930Z zigbee-herdsman:controller:log Device '0x000d6f00188bcfcf' joined
2023-02-04T08:39:45.930Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-02-04T08:39:45.930Z zigbee-herdsman:controller:log Device '0x000d6f00188bcfcf' accepted by handler
2023-02-04T08:39:45.930Z zigbee-herdsman:controller:log Device '0x000d6f00188bcfcf' is already in database with different networkAddress, updating networkAddress
2023-02-04T08:39:45.932Z zigbee-herdsman:controller:database:log Writing database to '/app/data/database.db'
2023-02-04T08:39:45.987Z zigbee-herdsman:controller:log Interview '0x000d6f00188bcfcf' start
Zigbee2MQTT:info  2023-02-04 09:39:45: Starting interview of '0x000d6f00188bcfcf'
Zigbee2MQTT:info  2023-02-04 09:39:46: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x000d6f00188bcfcf","ieee_address":"0x000d6f00188bcfcf","status":"started"},"type":"device_interview"}'
2023-02-04T08:39:46.009Z zigbee-herdsman:controller:device:log Interview - start device '0x000d6f00188bcfcf'
2023-02-04T08:39:46.010Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":9089,"nwkaddrofinterest":9089}
2023-02-04T08:39:46.010Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,129,35,129,35,35]
2023-02-04T08:39:46.021Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2023-02-04T08:39:46.021Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2023-02-04T08:39:46.021Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2023-02-04T08:39:46.021Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2023-02-04T08:39:46.021Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-02-04T08:39:52.493Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,7,69,196,206,238,2,166,153,35,171,19]
2023-02-04T08:39:52.493Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,7,69,196,206,238,2,166,153,35,171,19]
2023-02-04T08:39:52.493Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 7 - 2 - 5 - 196 - [206,238,2,166,153,35,171] - 19
2023-02-04T08:39:52.493Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - srcRtgInd - {"dstaddr":61134,"relaycount":2,"relaylist":[39334,43811]}
2023-02-04T08:39:52.493Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-02-04T08:39:52.565Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,12,69,202,199,224,207,207,139,24,0,111,13,0,206,238,117]
2023-02-04T08:39:52.565Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,12,69,202,199,224,207,207,139,24,0,111,13,0,206,238,117]
2023-02-04T08:39:52.565Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 12 - 2 - 5 - 202 - [199,224,207,207,139,24,0,111,13,0,206,238] - 117
2023-02-04T08:39:52.565Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - tcDeviceInd - {"nwkaddr":57543,"extaddr":"0x000d6f00188bcfcf","parentaddr":61134}

...

2023-02-04T08:40:05.801Z zigbee-herdsman:controller:log Device '0x000d6f00188bcfcf' joined
2023-02-04T08:40:05.801Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-02-04T08:40:05.801Z zigbee-herdsman:controller:log Device '0x000d6f00188bcfcf' accepted by handler
2023-02-04T08:40:05.801Z zigbee-herdsman:controller:log Device '0x000d6f00188bcfcf' is already in database with different networkAddress, updating networkAddress
2023-02-04T08:40:05.801Z zigbee-herdsman:controller:database:log Writing database to '/app/data/database.db'
2023-02-04T08:40:05.867Z zigbee-herdsman:controller:log Not interviewing '0x000d6f00188bcfcf', completed 'false', in progress 'true'
2023-02-04T08:40:09.061Z zigbee-herdsman:controller:device:log Interview - quirks check for 'undefined'-'undefined'-'Unknown'
2023-02-04T08:40:09.061Z zigbee-herdsman:controller:device:log Interview - quirks did not match
2023-02-04T08:40:09.061Z zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0x000d6f00188bcfcf', attempt 1
2023-02-04T08:40:09.061Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":57543,"nwkaddrofinterest":57543}

...

2023-02-04T13:51:08.798Z zigbee-herdsman:controller:device:log Interview - quirks check for 'undefined'-'undefined'-'Unknown'
2023-02-04T13:51:08.798Z zigbee-herdsman:controller:device:log Interview - quirks did not match
2023-02-04T13:51:08.798Z zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0x000d6f00188bcfcf', attempt 6
2023-02-04T13:51:08.798Z zigbee-herdsman:controller:device:log Interview - quirks check for 'undefined'-'undefined'-'Unknown'
2023-02-04T13:51:08.798Z zigbee-herdsman:controller:device:log Interview - quirks did not match
2023-02-04T13:51:08.871Z zigbee-herdsman:controller:device:log Interview - failed for device '0x000d6f00188bcfcf' with error 'Error: Interview failed because can not get node descriptor ('0x000d6f0
0188bcfcf')
at Device.interviewInternal (/app/node_modules/zigbee-herdsman/src/controller/model/device.ts:554:19)
at Device.interview (/app/node_modules/zigbee-herdsman/src/controller/model/device.ts:444:13)
at Controller.onDeviceJoined (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:567:17)'
2023-02-04T13:51:08.871Z zigbee-herdsman:controller:database:log Writing database to '/app/data/database.db'
2023-02-04T13:51:08.909Z zigbee-herdsman:controller:error Interview failed for '0x000d6f00188bcfcf with error 'Error: Interview failed because can not get node descriptor ('0x000d6f00188bcfcf')'
Zigbee2MQTT:error 2023-02-04 14:51:08: Failed to interview '0x000d6f00188bcfcf', device has not successfully been paired

**Comment by davemeier82** [comment]
`2023-02-04T08:40:05.801Z zigbee-herdsman:controller:log Device '0x000d6f00188bcfcf' joined
2023-02-04T08:40:05.801Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-02-04T08:40:05.801Z zigbee-herdsman:controller:log Device '0x000d6f00188bcfcf' accepted by handler
2023-02-04T08:40:05.801Z zigbee-herdsman:controller:log Device '0x000d6f00188bcfcf' is already in database with different networkAddress, updating networkAddress
2023-02-04T08:40:05.801Z zigbee-herdsman:controller:database:log Writing database to '/app/data/database.db'
2023-02-04T08:40:05.867Z zigbee-herdsman:controller:log Not interviewing '0x000d6f00188bcfcf', completed 'false', in progress 'true'
2023-02-04T08:40:09.061Z zigbee-herdsman:controller:device:log Interview - quirks check for 'undefined'-'undefined'-'Unknown'
2023-02-04T08:40:09.061Z zigbee-herdsman:controller:device:log Interview - quirks did not match
2023-02-04T08:40:09.061Z zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0x000d6f00188bcfcf', attempt 1
2023-02-04T08:40:09.061Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":57543,"nwkaddrofinterest":57543}`

**Comment by davemeier82** [comment]
pairing worked with this: https://github.com/Koenkk/zigbee2mqtt/discussions/15966
