### ISSUE TITLE
Ikea Trådfri Shortcut button OTA update fails

### ISSUE THREAD

**Issue by jarilehtinen** [Koenkk/zigbee2mqtt#16528]
### What happened?

I have two Ikea Trådfri Shortcut buttons (firmware dated 20190715, version 2.3.015) and one Trådfri on/off switch (firmware dated 20190723, version 2.2.010). OTA page says there are firmware update available, but after trying to update, I get an error saying "Device didn't respond to OTA request".

I'm running:
Home Assistant 2023.2.1
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

### Zigbee2MQTT version

1.30.0-1

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 3.0

### Debug log

2023-02-04 19:39:00 Updating to latest '0x84ba20fffea7d307' (TRADFRI SHORTCUT Button)
2023-02-04 19:40:00 Update of '(Device name)' failed (Error: Device didn't respond to OTA request)
2023-02-04 19:40:00 Error: Device didn't respond to OTA request at requestOTA (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:191:15) at Object.updateToLatest (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:279:21) at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:267:41)

**Comment by jarilehtinen** [comment]
This was similar to issue [#15235](https://github.com/Koenkk/zigbee2mqtt/issues/15235). Buttons are in sleep state and need to wake up before update can start. Got one shortcut button and on/off switch to start updating, struggling to get one to wake up. Issue solved.
