### ISSUE TITLE
[New device support]: Legrand 4 scènes with battery   (600091A in France)

### ISSUE THREAD

**Issue by m4sis** [Koenkk/zigbee2mqtt#16624]
### Link

https://www.legrand.fr/pro/catalogue/44196-version-dooxie-with-netatmo/commande-sans-fils-pour-ajout-de-4-scenarios-pour-installation-connectee-dooxie-with-netatmo-blanc-sans-plaque

### Database entry

{"id":16,"type":"EndDevice","ieeeAddr":"0x0004740000834175","nwkAddr":22299,"manufId":4129,"manufName":" Legrand\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","powerSource":"Battery","modelId":" Wireless Scenes Command\u0000\u0000\u0000\u0000\u0000\u0000\u0000","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":6,"inClusterList":[0,3,32,1],"outClusterList":[5,3,0,25],"clusters":{"genBasic":{"attributes":{"appVersion":0}},"genPollCtrl":{"attributes":{"checkinInterval":345600}},"genPowerCfg":{"attributes":{"batteryVoltage":27}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00212effff061a1e","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00212effff061a1e","endpointID":1},{"cluster":5,"type":"endpoint","deviceIeeeAddress":"0x00212effff061a1e","endpointID":1},{"cluster":0,"type":"endpoint","deviceIeeeAddress":"0x00212effff061a1e","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":66,"hwVersion":3,"dateCode":" \u000020200220\u0000\u0000\u0000\u0000\u0000","swBuildId":"001e","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1676136239705,"defaultSendRequestWhen":"active"}

### Comments

hello

I followed this [topic](https://github.com/Koenkk/zigbee-herdsman-converters/pull/5359), but my groupid does not appear in the payload,
I can't do my automation, any idea?

`Debug 2023-02-11 18:44:25Received Zigbee message from '0x0004740000834175', type 'commandRecall', cluster 'genScenes', data '{"groupid":65517,"sceneid":1}' from endpoint 1 with groupID null
Info 2023-02-11 18:44:25Configuring '0x0004740000834175'
Info 2023-02-11 18:44:25MQTT publish: topic 'zigbee2mqtt/0x0004740000834175', payload '{"action":"recall_1_1","battery":40,"linkquality":255,"voltage":2700}'
Info 2023-02-11 18:44:25MQTT publish: topic 'zigbee2mqtt/0x0004740000834175', payload '{"action":"","battery":40,"linkquality":255,"voltage":2700}'
Info 2023-02-11 18:44:25MQTT publish: topic 'zigbee2mqtt/0x0004740000834175/action', payload 'recall_1_1'
Error 2023-02-11 18:44:27Failed to configure '0x0004740000834175', attempt 1 (Error: Bind 0x0004740000834175/1 genOnOff from '0x00212effff061a1e/1' failed (Error: status: 130) at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:768:19) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:567:13) at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:40:9) at Object.configure (/app/data/extension/externally-loaded.js:30:13) at Configure.configure (/app/lib/extension/configure.ts:117:13))`

### External converter

```shell
module.exports = definition;

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const readInitialBatteryState = async (type, data, device) => {
    if (['deviceAnnounce'].includes(type)) {
        const endpoint = device.getEndpoint(1);
        const options = {manufacturerCode: 0x1021, disableDefaultResponse: true};
        await endpoint.read('genPowerCfg', ['batteryVoltage'], options);
    }
};


const definition = {
        zigbeeModel: [' Wireless Scenes Command\u0000\u0000\u0000\u0000\u0000\u0000\u0000'],
        model: 'Wireless Scenes Command',
        vendor: 'Legrand',        
        description: 'Dooxie 4 scenario',
        fromZigbee: [fz.battery, fz.identify, fz.command_recall],
        exposes: [e.battery(), e.action(['identify'])],
        toZigbee: [],
        meta: {multiEndpoint: true, battery: {voltageToPercentage: '3V_2500'}, publishDuplicateTransaction: true},
        onEvent: readInitialBatteryState,
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg', 'genOnOff', 'genLevelCtrl',  'genScenes', 'genBasic', 'genIdentify']);
        },

};

module.exports = definition;
```

**Comment by m4sis** [comment]
impossible to have the information of the group in the payload, a little help please

**Comment by m4sis** [comment]
Sorry to bother you, I've been desperately trying to get my button to work for 6 months.

**Comment by m4sis** [comment]
i have

`Failed` to configure '0x0004740000834175', attempt 2 (Error: Bind 0x0004740000834175/1 genOnOff from '0x00212effff061a1e/1' failed (Error: status: 130) at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:768:19) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:567:13) at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:40:9) at Object.configure (/app/data/extension/externally-loaded.js:30:13) at Configure.configure (/app/lib/extension/configure.ts:117:13))``
