### ISSUE TITLE
error during update

### ISSUE THREAD

**Issue by acaonweb** [Koenkk/zigbee2mqtt#16627]
### What happened?

run update.sh
process stops with this errors
42 verbose stack SystemError [ERR_FS_EISDIR]: Path is a directory: rm returned EISDIR (is$
42 verbose stack     at new SystemError (internal/errors.js:217:5)
42 verbose stack     at new NodeError (internal/errors.js:302:7)
42 verbose stack     at internal/fs/utils.js:718:23
42 verbose stack     at callback (/usr/lib/node_modules/npm/node_modules/graceful-fs/poly$
42 verbose stack     at FSReqCallback.oncomplete (fs.js:193:5)
43 verbose cwd /opt/zigbee2mqtt
44 verbose Linux 5.10.103-v7+
45 verbose node v14.21.1
46 verbose npm  v9.3.0
47 error code ERR_FS_EISDIR
48 error syscall rm
49 error path /opt/zigbee2mqtt/node_modules/.bin
50 error errno 21
51 error Path is a directory: rm returned EISDIR (is a directory) /opt/zigbee2mqtt/node_m$
52 verbose exit 21
53 timing npm Completed in 4365ms
54 verbose code 21
55 error A complete log of this run can be found in:
55 error     /root/.npm/_logs/2023-02-11T19_44_16_669Z-debug-0.log

### What did you expect to happen?

no errors

### How to reproduce it (minimal and precise)

run update.sh

### Zigbee2MQTT version

1.30.0 to 1.30.1

### Adapter firmware version

20220219

### Adapter

zzh! CC2652R Multiprotocol RF Stick

**Comment by acaonweb** [comment]
same error using the procedure written [here](https://www.zigbee2mqtt.io/guide/installation/01_linux.html#for-later-update-zigbee2mqtt-to-the-latest-version)

**Comment by acaonweb** [comment]
resolved giving to all /opt/zigbe2mqtt folder the right user:group
