### ISSUE TITLE
Tuya garage door opener (GDC311ZBQ1) not reporting contact sensor

### ISSUE THREAD

**Issue by grest** [Koenkk/zigbee2mqtt#16656]
### What happened?

I paired garage door opener (GDC311ZBQ1) with a wireless sensor to my HA. Open / close trigger works fine, however the sensor doesn't. Initially it reported to be always true, after re-pairing it became unavailable.
Occasionally it's back again and then disappears. 

It might be also a hardware problem. Has anybody similar issue?

### What did you expect to happen?

I expect garage_door_contact (or any other similar) attribute to report the correct state.

### Zigbee2MQTT version

 1.30.1-1

### Adapter firmware version

 6.10.3.0 build 297

### Adapter

EZSP v8 | Sonoff ZBDongle USB ZigBee 3.0 CC2652P ZigBee2MQTT

### Debug log
Pairing log is as follows. Something in it looks strange - 65503":"�?}+\u0013�?}+e�?}+\u0012�@}+e�@}+\u0012"

```
error 2023-02-13 18:39:41: Failed to configure '0xa4c1389a5096ae12', attempt 1 (Error: Read 0xa4c1389a5096ae12/1 genBasic(["manufacturerName","zclVersion","appVersion","modelId","powerSource",65534], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 65017 - 1 - 50 - 0 - 1 after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7))
info  2023-02-13 18:39:43: Configuring '0xa4c1389a5096ae12'
error 2023-02-13 18:40:03: Failed to configure '0xa4c1389a5096ae12', attempt 2 (Error: Read 0xa4c1389a5096ae12/1 genBasic(["manufacturerName","zclVersion","appVersion","modelId","powerSource",65534], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 11344 - 1 - 51 - 0 - 1 after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7))
info  2023-02-13 18:40:51: Configuring '0xa4c1389a5096ae12'
debug 2023-02-13 18:40:53: Received Zigbee message from '0xa4c1389a5096ae12', type 'readResponse', cluster 'genBasic', data '{"65534":0,"appVersion":70,"manufacturerName":"_TZE200_wfxuhoea","modelId":"TS0601","powerSource":1,"zclVersion":3}' from endpoint 1 with groupID 0
info  2023-02-13 18:40:53: Successfully configured '0xa4c1389a5096ae12'
debug 2023-02-13 18:41:04: Received Zigbee message from '0xa4c1389a5096ae12', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
debug 2023-02-13 18:41:04: Received Zigbee message from '0xa4c1389a5096ae12', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
debug 2023-02-13 18:41:04: Received Zigbee message from '0xa4c1389a5096ae12', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
debug 2023-02-13 18:41:04: Received Zigbee message from '0xa4c1389a5096ae12', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
debug 2023-02-13 18:41:11: Received Zigbee message from '0xa4c1389a5096ae12', type 'attributeReport', cluster 'genBasic', data '{"65506":54,"65508":0,"appVersion":70}' from endpoint 1 with groupID 0
debug 2023-02-13 18:41:11: Received Zigbee message from '0xa4c1389a5096ae12', type 'attributeReport', cluster 'genBasic', data '{"65506":54,"65508":0,"appVersion":70}' from endpoint 1 with groupID 0
debug 2023-02-13 18:41:12: Received Zigbee message from '0xa4c1389a5096ae12', type 'attributeReport', cluster 'genBasic', data '{"65503":"�?}+\u0013�?}+e�?}+\u0012�@}+e�@}+\u0012"}' from endpoint 1 with groupID 0
debug 2023-02-13 18:41:12: Received Zigbee message from '0xa4c1389a5096ae12', type 'attributeReport', cluster 'genBasic', data '{"65503":"�?}+\u0013�?}+e�?}+\u0012�@}+e�@}+\u0012"}' from endpoint 1 with groupID 0
debug 2023-02-13 18:41:23: Received MQTT message on 'zigbee2mqtt/bridge/request/device/rename' with data '{"from":"0xa4c1389a5096ae12","homeassistant_rename":true,"to":"Brama garażowa (z2m)","transaction":"xm8yh-1"}'
info  2023-02-13 18:41:23: MQTT publish: topic 'zigbee2mqtt/0xa4c1389a5096ae12', payload ''
debug 2023-02-13 18:41:23: Refreshing Home Assistant discovery topic for 'Brama garażowa (z2m)'
info  2023-02-13 18:41:23: MQTT publish: topic 'homeassistant/switch/0xa4c1389a5096ae12/switch_trigger/config', payload 'null'
info  2023-02-13 18:41:23: MQTT publish: topic 'homeassistant/binary_sensor/0xa4c1389a5096ae12/garage_door_contact/config', payload 'null'
info  2023-02-13 18:41:23: MQTT publish: topic 'homeassistant/sensor/0xa4c1389a5096ae12/linkquality/config', payload 'null'
info  2023-02-13 18:41:23: MQTT publish: topic 'zigbee2mqtt/Brama garażowa (z2m)', payload '{"garage_door_contact":null,"linkquality":68,"trigger":null}'
info  2023-02-13 18:41:23: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/rename', payload '{"data":{"from":"0xa4c1389a5096ae12","homeassistant_rename":true,"to":"Brama garażowa (z2m)"},"status":"ok","transaction":"xm8yh-1"}'
debug 2023-02-13 18:41:23: Received MQTT message on 'homeassistant/switch/0xa4c1389a5096ae12/switch_trigger/config' with data ''
debug 2023-02-13 18:41:23: Received MQTT message on 'homeassistant/binary_sensor/0xa4c1389a5096ae12/garage_door_contact/config' with data ''
debug 2023-02-13 18:41:23: Received MQTT message on 'homeassistant/sensor/0xa4c1389a5096ae12/linkquality/config' with data ''
info  2023-02-13 18:41:25: MQTT publish: topic 'homeassistant/switch/0xa4c1389a5096ae12/switch_trigger/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/Brama garażowa (z2m)/set/trigger","device":{"identifiers":["zigbee2mqtt_0xa4c1389a5096ae12"],"manufacturer":"TuYa","model":"LoraTap garage door opener with wireless sensor (GDC311ZBQ1)","name":"Brama garażowa (z2m)"},"name":"Brama garażowa (z2m) trigger","payload_off":"false","payload_on":"true","state_topic":"zigbee2mqtt/Brama garażowa (z2m)","unique_id":"0xa4c1389a5096ae12_switch_trigger_zigbee2mqtt","value_template":"{% if value_json.trigger %} true {% else %} false {% endif %}"}'
info  2023-02-13 18:41:25: MQTT publish: topic 'homeassistant/binary_sensor/0xa4c1389a5096ae12/garage_door_contact/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0xa4c1389a5096ae12"],"manufacturer":"TuYa","model":"LoraTap garage door opener with wireless sensor (GDC311ZBQ1)","name":"Brama garażowa (z2m)"},"device_class":"garage_door","name":"Brama garażowa (z2m) garage door contact","payload_off":true,"payload_on":false,"state_topic":"zigbee2mqtt/Brama garażowa (z2m)","unique_id":"0xa4c1389a5096ae12_garage_door_contact_zigbee2mqtt","value_template":"{{ value_json.garage_door_contact }}"}'
info  2023-02-13 18:41:25: MQTT publish: topic 'homeassistant/sensor/0xa4c1389a5096ae12/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0xa4c1389a5096ae12"],"manufacturer":"TuYa","model":"LoraTap garage door opener with wireless sensor (GDC311ZBQ1)","name":"Brama garażowa (z2m)"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"Brama garażowa (z2m) linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/Brama garażowa (z2m)","unique_id":"0xa4c1389a5096ae12_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
info  2023-02-13 18:41:25: MQTT publish: topic 'homeassistant/device_automation/0xa4c1389a5096ae12/action_trigger/config', payload '{"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0xa4c1389a5096ae12"],"manufacturer":"TuYa","model":"LoraTap garage door opener with wireless sensor (GDC311ZBQ1)","name":"Brama garażowa (z2m)"},"payload":"trigger","subtype":"trigger","topic":"zigbee2mqtt/Brama garażowa (z2m)/action","type":"action"}'
debug 2023-02-13 18:41:25: Received MQTT message on 'homeassistant/switch/0xa4c1389a5096ae12/switch_trigger/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"zigbee2mqtt/Brama garażowa (z2m)/set/trigger","device":{"identifiers":["zigbee2mqtt_0xa4c1389a5096ae12"],"manufacturer":"TuYa","model":"LoraTap garage door opener with wireless sensor (GDC311ZBQ1)","name":"Brama garażowa (z2m)"},"name":"Brama garażowa (z2m) trigger","payload_off":"false","payload_on":"true","state_topic":"zigbee2mqtt/Brama garażowa (z2m)","unique_id":"0xa4c1389a5096ae12_switch_trigger_zigbee2mqtt","value_template":"{% if value_json.trigger %} true {% else %} false {% endif %}"}'
debug 2023-02-13 18:41:25: Received MQTT message on 'homeassistant/binary_sensor/0xa4c1389a5096ae12/garage_door_contact/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0xa4c1389a5096ae12"],"manufacturer":"TuYa","model":"LoraTap garage door opener with wireless sensor (GDC311ZBQ1)","name":"Brama garażowa (z2m)"},"device_class":"garage_door","name":"Brama garażowa (z2m) garage door contact","payload_off":true,"payload_on":false,"state_topic":"zigbee2mqtt/Brama garażowa (z2m)","unique_id":"0xa4c1389a5096ae12_garage_door_contact_zigbee2mqtt","value_template":"{{ value_json.garage_door_contact }}"}'
debug 2023-02-13 18:41:25: Received MQTT message on 'homeassistant/sensor/0xa4c1389a5096ae12/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"device":{"identifiers":["zigbee2mqtt_0xa4c1389a5096ae12"],"manufacturer":"TuYa","model":"LoraTap garage door opener with wireless sensor (GDC311ZBQ1)","name":"Brama garażowa (z2m)"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"Brama garażowa (z2m) linkquality","state_class":"measurement","state_topic":"zigbee2mqtt/Brama garażowa (z2m)","unique_id":"0xa4c1389a5096ae12_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
debug 2023-02-13 18:41:25: Received MQTT message on 'homeassistant/device_automation/0xa4c1389a5096ae12/action_trigger/config' with data '{"automation_type":"trigger","device":{"identifiers":["zigbee2mqtt_0xa4c1389a5096ae12"],"manufacturer":"TuYa","model":"LoraTap garage door opener with wireless sensor (GDC311ZBQ1)","name":"Brama garażowa (z2m)"},"payload":"trigger","subtype":"trigger","topic":"zigbee2mqtt/Brama garażowa (z2m)/action","type":"action"}'
debug 2023-02-13 18:41:39: Received Zigbee message from 'Coordinator', type 'commandNotification', cluster 'greenPower', data '{"data":[25,54,2,10,0,0],"type":"Buffer"}' from endpoint 242 with groupID null, ignoring since it is from coordinator
debug 2023-02-13 18:42:13: Received MQTT message on 'zigbee2mqtt/Brama garażowa (z2m)/set/trigger' with data 'false'
debug 2023-02-13 18:42:13: Publishing 'set' 'trigger' to 'Brama garażowa (z2m)'
info  2023-02-13 18:42:13: MQTT publish: topic 'zigbee2mqtt/Brama garażowa (z2m)', payload '{"garage_door_contact":null,"linkquality":68,"trigger":false}'
```
I checked spec in tuya cloud, while being connected through tuya gateway and I got following json. 

`{
  "result": {
    "category": "ckmkzq",
    "functions": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "door_time_1",
        "dp_id": 4,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":10,\"max\":120,\"scale\":0,\"step\":1}"
      },
      {
        "code": "alarm_countdown_1",
        "dp_id": 5,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "door_control_1",
        "dp_id": 6,
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"close\"]}"
      },
      {
        "code": "voice_control_1",
        "dp_id": 11,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "door_state_1",
        "dp_id": 12,
        "type": "Enum",
        "values": "{\"range\":[\"unclosed_time\",\"close_time_alarm\",\"none\"]}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "doorcontact_state",
        "dp_id": 3,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "door_time_1",
        "dp_id": 4,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":10,\"max\":120,\"scale\":0,\"step\":1}"
      },
      {
        "code": "alarm_countdown_1",
        "dp_id": 5,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "door_control_1",
        "dp_id": 6,
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"close\"]}"
      },
      {
        "code": "voice_control_1",
        "dp_id": 11,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "door_state_1",
        "dp_id": 12,
        "type": "Enum",
        "values": "{\"range\":[\"unclosed_time\",\"close_time_alarm\",\"none\"]}"
      }
    ]
  },
  "success": true,
  "t": 1676309704723,
  "tid": "c04f645babc411edbe05a63cfb33a057"
}`

**Comment by grest** [comment]
After restarting the device the garage_door_contact is back, but it's always true.

```
{
    "garage_door_contact": true,
    "linkquality": 120,
    "trigger": false
}
```

**Comment by grest** [comment]
I paired the device using the tuya zigbee gateway and the sensor works fine. So it has to be a problem with the zigbee2mqtt

**Comment by grest** [comment]
I checked spec in tuya cloud and get following json:

`{
  "result": {
    "category": "ckmkzq",
    "functions": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "door_time_1",
        "dp_id": 4,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":10,\"max\":120,\"scale\":0,\"step\":1}"
      },
      {
        "code": "alarm_countdown_1",
        "dp_id": 5,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "door_control_1",
        "dp_id": 6,
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"close\"]}"
      },
      {
        "code": "voice_control_1",
        "dp_id": 11,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "door_state_1",
        "dp_id": 12,
        "type": "Enum",
        "values": "{\"range\":[\"unclosed_time\",\"close_time_alarm\",\"none\"]}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "doorcontact_state",
        "dp_id": 3,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "door_time_1",
        "dp_id": 4,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":10,\"max\":120,\"scale\":0,\"step\":1}"
      },
      {
        "code": "alarm_countdown_1",
        "dp_id": 5,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "door_control_1",
        "dp_id": 6,
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"close\"]}"
      },
      {
        "code": "voice_control_1",
        "dp_id": 11,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "door_state_1",
        "dp_id": 12,
        "type": "Enum",
        "values": "{\"range\":[\"unclosed_time\",\"close_time_alarm\",\"none\"]}"
      }
    ]
  },
  "success": true,
  "t": 1676309704723,
  "tid": "c04f645babc411edbe05a63cfb33a057"
}`

**Comment by grest** [comment]
Solved! https://github.com/Koenkk/zigbee2mqtt/issues/11570#issuecomment-1431837162

**Comment by grest** [comment]
https://github.com/Koenkk/zigbee2mqtt/issues/11570#issuecomment-1431837162
