### ISSUE TITLE
Zigbee2mqtt crashes after plugging a brand new IKEA LED1650r5

### ISSUE THREAD

**Issue by gericho** [Koenkk/zigbee2mqtt#1668]
Hi, When I try to pair the IKEA LED1650r5 the zigbee2mqtt suddenly crashes, I have paired already 10 devices without issue.

my configuration.xml:
```
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
  user: username
  password: password
serial:
  port: /dev/ttyACM0
devices:
  '0x90fd9ffffefabafa':
    friendly_name: scrivania
    retain: false
  '0x000b57fffe89ff60':
    friendly_name: tailandese
    retain: false
  '0xd0cf5efffe24c858':
    friendly_name: camera_grande
    retain: false
  '0x000d6ffffeae1ec8':
    friendly_name: fornello_camera
    retain: false
  '0x90fd9ffffe52adf4':
    friendly_name: telecomando
    retain: false
  '0x000d6ffffedac635':
    friendly_name: fornello_bagno
    retain: false
  '0xd0cf5efffe255288':
    friendly_name: cucina_grande
    retain: false
  '0x000b3cfffef17a6f':
    friendly_name: ingresso
    retain: false
  '0x000b57fffea714ed':
    friendly_name: sopra
    retain: false
  '0x000b57fffe991092':
    friendly_name: sotto
    retain: false
  '0x00158d00022852a5':
    friendly_name: xiaomi_motion
    retain: false
    
groups:
  '1':
    friendly_name: Corridoio
    devices:
      - '0x000b57fffea714ed'
      - '0x000b57fffe991092'
```

Log
```
Jun 24 21:22:03 hassbian npm[2780]:   zigbee2mqtt:info 6/24/2019, 9:22:03 PM New device 'undefined' with address 0x000b57fffebd9502 connected!
Jun 24 21:22:03 hassbian npm[2780]: fs.js:114
Jun 24 21:22:03 hassbian npm[2780]:     throw err;
Jun 24 21:22:03 hassbian npm[2780]:     ^
Jun 24 21:22:03 hassbian npm[2780]: Error: EACCES: permission denied, open '/opt/zigbee2mqtt/data/configuration.yaml'
Jun 24 21:22:03 hassbian npm[2780]:     at Object.openSync (fs.js:443:3)
Jun 24 21:22:03 hassbian npm[2780]:     at Object.writeFileSync (fs.js:1194:35)
Jun 24 21:22:03 hassbian npm[2780]:     at Object.writeYaml (/opt/zigbee2mqtt/lib/util/fs.js:13:8)
Jun 24 21:22:03 hassbian npm[2780]:     at write (/opt/zigbee2mqtt/lib/util/settings.js:113:8)
Jun 24 21:22:03 hassbian npm[2780]:     at writeRead (/opt/zigbee2mqtt/lib/util/settings.js:92:5)
Jun 24 21:22:03 hassbian npm[2780]:     at addDevice (/opt/zigbee2mqtt/lib/util/settings.js:176:5)
Jun 24 21:22:03 hassbian npm[2780]:     at Object.addDevice (/opt/zigbee2mqtt/lib/util/settings.js:344:30)
Jun 24 21:22:03 hassbian npm[2780]:     at DeviceReceive.onZigbeeMessage (/opt/zigbee2mqtt/lib/extension/deviceReceive.js:68:22)
Jun 24 21:22:03 hassbian npm[2780]:     at extensions.filter.forEach (/opt/zigbee2mqtt/lib/controller.js:143:31)
Jun 24 21:22:03 hassbian npm[2780]:     at Array.forEach (<anonymous>)
Jun 24 21:22:03 hassbian npm[2780]: npm ERR! code ELIFECYCLE
Jun 24 21:22:03 hassbian npm[2780]: npm ERR! errno 1
Jun 24 21:22:03 hassbian npm[2780]: npm ERR! zigbee2mqtt@1.4.0 start: `node index.js`
Jun 24 21:22:03 hassbian npm[2780]: npm ERR! Exit status 1
Jun 24 21:22:03 hassbian npm[2780]: npm ERR!
Jun 24 21:22:03 hassbian npm[2780]: npm ERR! Failed at the zigbee2mqtt@1.4.0 start script.
Jun 24 21:22:03 hassbian npm[2780]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Jun 24 21:22:03 hassbian npm[2780]: npm ERR! A complete log of this run can be found in:
Jun 24 21:22:03 hassbian npm[2780]: npm ERR!     /home/pi/.npm/_logs/2019-06-24T19_22_03_817Z-debug.log
Jun 24 21:22:03 hassbian systemd[1]: zigbee2mqtt.service: Main process exited, code=exited, status=1/FAILURE
Jun 24 21:22:03 hassbian systemd[1]: zigbee2mqtt.service: Unit entered failed state.
Jun 24 21:22:03 hassbian systemd[1]: zigbee2mqtt.service: Failed with result 'exit-code'.
Jun 24 21:22:04 hassbian systemd[1]: zigbee2mqtt.service: Service hold-off time over, scheduling restart.
Jun 24 21:22:04 hassbian systemd[1]: Stopped zigbee2mqtt.
Jun 24 21:22:04 hassbian systemd[1]: Starting zigbee2mqtt...
Jun 24 21:22:04 hassbian systemd[1]: Started zigbee2mqtt.
Jun 24 21:22:05 hassbian npm[2841]: > zigbee2mqtt@1.4.0 start /opt/zigbee2mqtt
Jun 24 21:22:05 hassbian npm[2841]: > node index.js
Jun 24 21:22:06 hassbian npm[2841]:   zigbee2mqtt:info 6/24/2019, 9:22:06 PM Logging to directory: '/opt/zigbee2mqtt/data/log/2019-06-24.21-22-06'
Jun 24 21:22:07 hassbian npm[2841]:   zigbee2mqtt:info 6/24/2019, 9:22:07 PM Starting zigbee2mqtt version 1.4.0 (commit #927c4db)
Jun 24 21:22:07 hassbian npm[2841]:   zigbee2mqtt:info 6/24/2019, 9:22:07 PM Starting zigbee-shepherd
Jun 24 21:22:09 hassbian npm[2841]:   zigbee2mqtt:info 6/24/2019, 9:22:09 PM zigbee-shepherd started
Jun 24 21:22:09 hassbian npm[2841]:   zigbee2mqtt:info 6/24/2019, 9:22:09 PM Coordinator firmware version: '20190425'
Jun 24 21:22:09 hassbian npm[2841]:   zigbee2mqtt:info 6/24/2019, 9:22:09 PM Currently 10 devices are joined:

```
**How to reproduce it**
Turn ON the LED1650R5
## Debug Info
zigbee2mqtt version: 1.4.0
CC253X firmware version: CC2531_20190425

**Comment by Koenkk** [comment]
You need to fix the permission on your `configuration.yaml`

```
Error: EACCES: permission denied, open '/opt/zigbee2mqtt/data/configuration.yaml'
```

**Comment by gericho** [comment]
Ok thanks, so the current permission are:

`-rwxr--r-- 1 homeassistant homeassistant 1338 Jun 24 23:01 configuration.yaml`

and needs to be? Thank you very much!

**Comment by Koenkk** [comment]
The user which run zigbee2mqtt should have write access, in case you want to go for the quick and dirty hack: `sudo chmod 777 configuration.yaml`.

**Comment by gericho** [comment]
I have to reopen this, unfortunately the permission keeps changing back to: 

`
-rwxr--r--  1 homeassistant homeassistant  1239 Jun 30 21:36 configuration.yaml`

it changes back after the machine reboots or HA restart, I'm not 100% sure, setting again to 777 is a workaround that works but a fix is welcome.

**Comment by Koenkk** [comment]
There is not much to fix from the zigbee2mqtt side, it's a general linux permission issue. You have to make sure that the user who runs zigbee2mqtt has write access to the file and that others don't change permission on it.

**Comment by gericho** [comment]
thank you!
