### ISSUE TITLE
EZVIZ T1C

### ISSUE THREAD

**Issue by osik110** [Koenkk/zigbee2mqtt#16760]
### Link

https://www.ezviz.com/pl/product/T1C-PIR-Motion-Sensor/41319

### Database entry

{"id":18,"type":"EndDevice","ieeeAddr":"0xa4c138fae09768c7","nwkAddr":19761,"manufId":4451,"manufName":"EZVIZ","powerSource":"Battery","modelId":"CS-T1C-A0-BG\u0000\u0000\u0000\u0000\u0000","epList":[1,0],"endpoints":{"0":{"epId":0,"inClusterList":[],"outClusterList":[],"clusters":{"genPowerCfg":{"attributes":{"batteryPercentageRemaining":200}},"genBasic":{"attributes":{"32769":1}}},"binds":[],"configuredReportings":[],"meta":{}},"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1280,65024],"outClusterList":[25,65024],"clusters":{"65024":{"attributes":{"1":{"type":"Buffer","data":[81,49,51,48,51,56,49,48,49,66,67,77,67,87,85,0]}}},"genBasic":{"attributes":{"appVersion":0,"hwVersion":0}},"ssIasZone":{"attributes":{"iasCieAddr":"0xdc8e95fffe00a22f","zoneState":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":2,"hwVersion":0,"dateCode":"20211214\u0000","zclVersion":3,"interviewCompleted":false,"meta":{},"lastSeen":1676911413440,"defaultSendRequestWhen":"immediate"}

### Comments

Is possible add this ?
In state.json is only this:

        "0xa4c138fae09768c7": {
            "date_code": "20211214\u0000",
            "definition": null,
            "disabled": false,
            "endpoints": {
                "0": {
                    "bindings": [],
                    "clusters": {
                        "input": [],
                        "output": []
                    },
                    "configured_reportings": [],
                    "scenes": []
                },
                "1": {
                    "bindings": [],
                    "clusters": {
                        "input": [
                            "genBasic",
                            "genPowerCfg",
                            "genIdentify",
                            "ssIasZone",
                            "65024"
                        ],
                        "output": [
                            "genOta",
                            "65024"
                        ]
                    },
                    "configured_reportings": [],
                    "scenes": []
                }
            },
            "friendly_name": "czujnik ruchu ezviz",
            "ieee_address": "0xa4c138fae09768c7",
            "interview_completed": false,
            "interviewing": false,
            "manufacturer": "EZVIZ",
            "model_id": "CS-T1C-A0-BG\u0000\u0000\u0000\u0000\u0000",
            "network_address": 19761,
            "power_source": "Battery",
            "supported": false,
            "type": "EndDevice"

**Comment by RaunoVV** [comment]
Stick: CC2652 - Zigstar Lan Gateway

Just got a Ezviz Water Leaksensor and it's not able to complete the interview.
https://www.ezviz.com/product/T10C/42454

Some logs of pairing/interviewing:
`
Received Zigbee message from '0xa4c1384dbcbbfd0d', type 'attributeReport', cluster '65024', data '{"1":{"data":[81,50,56,48,55,52,51,52,56,77,82,89,87,87,67,0],"type":"Buffer"}}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2024-01-02 21:05:46: MQTT publish: topic 'zigbee2mqtt/0xa4c1384dbcbbfd0d', payload '{"last_seen":"2024-01-02T19:05:46.968Z","linkquality":163}'
Zigbee2MQTT:debug 2024-01-02 21:05:46: Device '0xa4c1384dbcbbfd0d' announced itself
Zigbee2MQTT:info  2024-01-02 21:05:47: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0xa4c1384dbcbbfd0d","ieee_address":"0xa4c1384dbcbbfd0d"},"type":"device_announce"}'
Zigbee2MQTT:debug 2024-01-02 21:05:48: Received Zigbee message from '0xa4c1384dbcbbfd0d', type 'attributeReport', cluster '65024', data '{"1":{"data":[81,50,56,48,55,52,51,52,56,77,82,89,87,87,67,0],"type":"Buffer"}}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2024-01-02 21:05:48: Skipping message, still interviewing
Zigbee2MQTT:info  2024-01-02 21:05:48: MQTT publish: topic 'zigbee2mqtt/0xa4c1384dbcbbfd0d', payload '{"last_seen":"2024-01-02T19:05:47.987Z","linkquality":196}'
Zigbee2MQTT:debug 2024-01-02 21:05:48: Received Zigbee message from '0xa4c1384dbcbbfd0d', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200}' from endpoint 0 with groupID 0
Zigbee2MQTT:debug 2024-01-02 21:05:48: Skipping message, still interviewing
Zigbee2MQTT:info  2024-01-02 21:05:48: MQTT publish: topic 'zigbee2mqtt/0xa4c1384dbcbbfd0d', payload '{"last_seen":"2024-01-02T19:05:48.029Z","linkquality":193}'
Zigbee2MQTT:debug 2024-01-02 21:06:03: Received Zigbee message from '0xa4c1384dbcbbfd0d', type 'readResponse', cluster 'genBasic', data '{"modelId":"CS-T10C-A0-BG\u0000\u0000\u0000\u0000"}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2024-01-02 21:06:03: Skipping message, still interviewing
Zigbee2MQTT:info  2024-01-02 21:06:03: MQTT publish: topic 'zigbee2mqtt/0xa4c1384dbcbbfd0d', payload '{"last_seen":"2024-01-02T19:06:03.375Z","linkquality":171}'
Zigbee2MQTT:debug 2024-01-02 21:06:06: Received Zigbee message from '0xa4c1384dbcbbfd0d', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"EZVIZ"}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2024-01-02 21:06:06: Skipping message, still interviewing
Zigbee2MQTT:info  2024-01-02 21:06:06: MQTT publish: topic 'zigbee2mqtt/0xa4c1384dbcbbfd0d', payload '{"last_seen":"2024-01-02T19:06:06.371Z","linkquality":167}'
Zigbee2MQTT:debug 2024-01-02 21:06:09: Received Zigbee message from '0xa4c1384dbcbbfd0d', type 'readResponse', cluster 'genBasic', data '{"powerSource":3}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2024-01-02 21:06:09: Skipping message, still interviewing
Zigbee2MQTT:info  2024-01-02 21:06:09: MQTT publish: topic 'zigbee2mqtt/0xa4c1384dbcbbfd0d', payload '{"last_seen":"2024-01-02T19:06:09.372Z","linkquality":171}'
Zigbee2MQTT:debug 2024-01-02 21:06:12: Received Zigbee message from '0xa4c1384dbcbbfd0d', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2024-01-02 21:06:12: Skipping message, still interviewing
Zigbee2MQTT:info  2024-01-02 21:06:12: MQTT publish: topic 'zigbee2mqtt/0xa4c1384dbcbbfd0d', payload '{"last_seen":"2024-01-02T19:06:12.371Z","linkquality":171}'
Zigbee2MQTT:debug 2024-01-02 21:06:15: Received Zigbee message from '0xa4c1384dbcbbfd0d', type 'readResponse', cluster 'genBasic', data '{"appVersion":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2024-01-02 21:06:15: Skipping message, still interviewing
Zigbee2MQTT:info  2024-01-02 21:06:15: MQTT publish: topic 'zigbee2mqtt/0xa4c1384dbcbbfd0d', payload '{"last_seen":"2024-01-02T19:06:15.373Z","linkquality":171}'
Zigbee2MQTT:debug 2024-01-02 21:06:18: Received Zigbee message from '0xa4c1384dbcbbfd0d', type 'readResponse', cluster 'genBasic', data '{"stackVersion":2}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2024-01-02 21:06:18: Skipping message, still interviewing
Zigbee2MQTT:info  2024-01-02 21:06:18: MQTT publish: topic 'zigbee2mqtt/0xa4c1384dbcbbfd0d', payload '{"last_seen":"2024-01-02T19:06:18.372Z","linkquality":196}'
`

Herdsman debug:
`
2024-01-02T18:14:53.505Z zigbee-herdsman:controller:endpoint Read 0xa4c1384dbcbbfd0d/1 genBasic(["swBuildId"], {"sendWhen":"immediate","timeout":10000,"disableR
esponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSeque
nceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
...
2024-01-02T18:14:53.507Z zigbee-herdsman:controller:device:log Interview - IAS - enrolling '0xa4c1384dbcbbfd0d' endpoint '1'
2024-01-02T18:14:53.508Z zigbee-herdsman:controller:endpoint Read 0xa4c1384dbcbbfd0d/1 ssIasZone(["iasCieAddr","zoneState"], {"sendWhen":"immediate","timeout":1
0000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"tr
ansactionSequenceNumber":null,"writeUndiv":false})
2024-01-02T18:14:53.509Z zigbee-herdsman:adapter:zStack:adapter sendZclFrameToEndpointInternal 0xa4c1384dbcbbfd0d:47730/1 (0,0,1)
2024-01-02T18:14:53.509Z zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":47730,"destendpoint":1,"srcendpoint":1,"clusterid":1280,"tran
sid":11,"options":0,"radius":30,"len":7,"data":{"type":"Buffer","data":[16,9,0,16,0,0,0]}}
2024-01-02T18:14:53.510Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,17,36,1,114,186,1,1,0,5,11,0,30,7,16,9,0,16,0,0,0,226]
2024-01-02T18:14:53.520Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,100,1,0,100]
2024-01-02T18:14:53.520Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,1,0,100]
2024-01-02T18:14:53.520Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 1 - [0] - 100
2024-01-02T18:14:53.520Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequest - {"status":0}
2024-01-02T18:14:53.521Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2024-01-02T18:14:56.480Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,68,128,0,1,11,205]
2024-01-02T18:14:56.480Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,0,1,11,205]
2024-01-02T18:14:56.480Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [0,1,11] - 205
2024-01-02T18:14:56.480Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":11}
2024-01-02T18:14:56.481Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2024-01-02T18:14:56.494Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,40,68,129,0,0,0,5,114,186,1,1,0,134,0,18,210,59,0,0,20,24,9,1,16,0,0,240,231,55,46,
42,0,75,18,0,0,0,0,48,0,114,186,29,209]
2024-01-02T18:14:56.495Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,40,68,129,0,0,0,5,114,186,1,1,0,134,0,18,210,59,0,0,20,24,9,1,16,0,0,240,
231,55,46,42,0,75,18,0,0,0,0,48,0,114,186,29,209]
2024-01-02T18:14:56.495Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 40 - 2 - 4 - 129 - [0,0,0,5,114,186,1,1,0,134,0,18,210,59,0,0,20,24,9,1,16,0,0,24
0,231,55,46,42,0,75,18,0,0,0,0,48,0,114,186,29] - 209
2024-01-02T18:14:56.495Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":1280,"srcaddr":47730,"srcendpoint":1,"dstendpoi
nt":1,"wasbroadcast":0,"linkquality":134,"securityuse":0,"timestamp":3920402,"transseqnumber":0,"len":20,"data":{"type":"Buffer","data":[24,9,1,16,0,0,240,231,5
5,46,42,0,75,18,0,0,0,0,48,0]}}
...
Zigbee2MQTT:debug 2024-01-02 20:14:56: Received Zigbee message from '0xa4c1384dbcbbfd0d', type 'readResponse', cluster 'ssIasZone', data '{"iasCieAddr":"0x00124
b002a2e37e7","zoneState":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2024-01-02 20:14:56: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:info  2024-01-02 20:14:56: MQTT publish: topic 'zigbee2mqtt/0xa4c1384dbcbbfd0d', payload '{"last_seen":"2024-01-02T18:14:56.499Z","linkquality":134}
'
2024-01-02T18:14:56.506Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2024-01-02T18:14:56.507Z zigbee-herdsman:controller:device:log Interview - IAS - before enrolling state: '{"iasCieAddr":"0x00124b002a2e37e7","zoneState":0}'
2024-01-02T18:14:56.508Z zigbee-herdsman:controller:device:log Interview - IAS - not enrolled, enrolling
2024-01-02T18:14:56.510Z zigbee-herdsman:controller:endpoint Write 0xa4c1384dbcbbfd0d/1 ssIasZone({"iasCieAddr":"0x00124b002a2e37e7"}, {"sendWhen":"immediate","
timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode
":null,"transactionSequenceNumber":null,"writeUndiv":false})
2024-01-02T18:14:56.510Z zigbee-herdsman:adapter:zStack:adapter sendZclFrameToEndpointInternal 0xa4c1384dbcbbfd0d:47730/1 (0,0,1)
2024-01-02T18:14:56.512Z zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":47730,"destendpoint":1,"srcendpoint":1,"clusterid":1280,"tran
sid":12,"options":0,"radius":30,"len":14,"data":{"type":"Buffer","data":[16,10,2,16,0,240,231,55,46,42,0,75,18,0]}}
2024-01-02T18:14:56.512Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,24,36,1,114,186,1,1,0,5,12,0,30,14,16,10,2,16,0,240,231,55,46,42,0,75,18,0,15
3]
2024-01-02T18:15:06.012Z zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":47730,"destendpoint":1,"srcendpoint":1,"clusterid":1280,"tran
sid":15,"options":0,"radius":30,"len":7,"data":{"type":"Buffer","data":[16,13,0,16,0,0,0]}}
2024-01-02T18:15:06.012Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,17,36,1,114,186,1,1,0,5,15,0,30,7,16,13,0,16,0,0,0,226]
2024-01-02T18:15:06.023Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,100,1,0,100]
2024-01-02T18:15:06.023Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,1,0,100]
2024-01-02T18:15:06.023Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 1 - [0] - 100
2024-01-02T18:15:06.023Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequest - {"status":0}
2024-01-02T18:15:06.024Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2024-01-02T18:15:13.231Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,68,128,240,1,15,57]
2024-01-02T18:15:13.231Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,240,1,15,57]
2024-01-02T18:15:13.231Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [240,1,15] - 57
2024-01-02T18:15:13.232Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":240,"endpoint":1,"transid":15}
2024-01-02T18:15:13.232Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2024-01-02T18:15:13.232Z zigbee-herdsman:adapter:zStack:adapter Data confirm error (0xa4c1384dbcbbfd0d:47730,240,0)
2024-01-02T18:15:13.233Z zigbee-herdsman:adapter:zStack:adapter Wait 2000ms
2024-01-02T18:15:15.233Z zigbee-herdsman:adapter:zStack:adapter sendZclFrameToEndpointInternal 0xa4c1384dbcbbfd0d:47730/1 (0,1,1)
2024-01-02T18:15:15.234Z zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":47730,"destendpoint":1,"srcendpoint":1,"clusterid":1280,"tran
sid":16,"options":0,"radius":30,"len":7,"data":{"type":"Buffer","data":[16,13,0,16,0,0,0]}}
2024-01-02T18:15:15.235Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,17,36,1,114,186,1,1,0,5,16,0,30,7,16,13,0,16,0,0,0,253]
2024-01-02T18:15:15.246Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,100,1,0,100]
2024-01-02T18:15:15.247Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,1,0,100]
2024-01-02T18:15:15.247Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 1 - [0] - 100
2024-01-02T18:15:15.247Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequest - {"status":0}
2024-01-02T18:15:15.247Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2024-01-02T18:15:23.231Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,68,128,240,1,16,38]
2024-01-02T18:15:23.231Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,240,1,16,38]
2024-01-02T18:15:23.231Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [240,1,16] - 38
2024-01-02T18:15:23.232Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":240,"endpoint":1,"transid":16}
...
2024-01-02T18:15:35.252Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2024-01-02T18:15:45.253Z zigbee-herdsman:adapter:zStack:adapter sendZclFrameToEndpointInternal 0xa4c1384dbcbbfd0d:47730/1 (0,4,1)
2024-01-02T18:15:45.254Z zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":47730,"destendpoint":1,"srcendpoint":1,"clusterid":1280,"tran
sid":19,"options":0,"radius":30,"len":7,"data":{"type":"Buffer","data":[16,13,0,16,0,0,0]}}
2024-01-02T18:15:45.255Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,17,36,1,114,186,1,1,0,5,19,0,30,7,16,13,0,16,0,0,0,254]
2024-01-02T18:15:45.263Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,100,1,0,100]
2024-01-02T18:15:45.264Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,1,0,100]
2024-01-02T18:15:45.264Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 1 - [0] - 100
2024-01-02T18:15:45.264Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequest - {"status":0}
2024-01-02T18:15:45.264Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2024-01-02T18:15:53.232Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,68,128,240,1,19,37]
2024-01-02T18:15:53.232Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,240,1,19,37]
2024-01-02T18:15:53.232Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [240,1,19] - 37
2024-01-02T18:15:53.232Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":240,"endpoint":1,"transid":19}
2024-01-02T18:15:53.233Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2024-01-02T18:15:53.233Z zigbee-herdsman:adapter:zStack:adapter Data confirm error (0xa4c1384dbcbbfd0d:47730,240,4)
2024-01-02T18:15:53.234Z zigbee-herdsman:controller:endpoint Read 0xa4c1384dbcbbfd0d/1 ssIasZone(["iasCieAddr","zoneState"], {"sendWhen":"immediate","timeout":1
0000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"tr
ansactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))
2024-01-02T18:15:53.235Z zigbee-herdsman:controller:device:log Interview - quirks check for 'CS-T10C-A0-BG^@^@^@^@'-'EZVIZ'-'EndDevice'
2024-01-02T18:15:53.236Z zigbee-herdsman:controller:device:log Interview - quirks did not match
2024-01-02T18:15:53.338Z zigbee-herdsman:controller:device:log Interview - failed for device '0xa4c1384dbcbbfd0d' with error 'Error: Read 0xa4c1384dbcbbfd0d/1 s
sIasZone(["iasCieAddr","zoneState"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"dire
ction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with erro
r: 'MAC transaction expired' (240))
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)'
2024-01-02T18:15:53.338Z zigbee-herdsman:controller:database:log Writing database to '/app/data/database.db'
2024-01-02T18:15:53.347Z zigbee-herdsman:controller:error Interview failed for '0xa4c1384dbcbbfd0d with error 'Error: Read 0xa4c1384dbcbbfd0d/1 ssIasZone(["iasC
ieAddr","zoneState"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEn
dpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transac
tion expired' (240))'
Zigbee2MQTT:error 2024-01-02 20:15:53: Failed to interview '0xa4c1384dbcbbfd0d', device has not successfully been paired
`
