### ISSUE TITLE
Error after restart z2m. Tuya TS0121_plug (_TZ3000_3ooaz3ng)

### ISSUE THREAD

**Issue by Enzokot** [Koenkk/zigbee2mqtt#16864]
### What happened?

After restart z2m this error appears with `_TZ3000_3ooaz3ng`:
```
Failed to configure 'Heater socket', attempt 3 (Error: ConfigureReporting 0x842e14fffe5047f5/1 haElectricalMeasurement([{"attribute":"rmsVoltage","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":5}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 1430 - 1 - 38 - 2820 - 7 after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7))
```
Also at this point I can't control the device.

### How to reproduce it (minimal and precise)

Only restart z2m

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

20221226

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus by ITead

### Debug log

```
Failed to configure 'Heater socket', attempt 3 (Error: ConfigureReporting 0x842e14fffe5047f5/1 haElectricalMeasurement([{"attribute":"rmsVoltage","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":5}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 1430 - 1 - 38 - 2820 - 7 after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7))
```

**Comment by Enzokot** [comment]
Like this issue https://github.com/Koenkk/zigbee2mqtt/issues/11179
