### ISSUE TITLE
Smart IR Remote Control - Tuya TS1201 send too big state size

### ISSUE THREAD

**Issue by zen2** [Koenkk/zigbee2mqtt#16996]
### What happened?

I'm not sure it's a problem with zigbee2mqtt or homeassistant.

When using Smart IR Remote Control (Tuya TS1201), I got this log message from homeassistant:

```
2023-03-11 12:06:55.534 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback MQTT._mqtt_handle_message(<paho.mqtt.cl...x7f926997a030>)
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/site-packages/homeassistant/components/mqtt/client.py", line 722, in _mqtt_handle_message
    self._mqtt_data.state_write_requests.process_write_state_requests()
  File "/usr/lib/python3.10/site-packages/homeassistant/components/mqtt/models.py", line 267, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 676, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/lib/python3.10/site-packages/homeassistant/core.py", line 1537, in async_set
    state = State(
  File "/usr/lib/python3.10/site-packages/homeassistant/core.py", line 1186, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.0x385b44fffe37682e_learned_ir_code. State max length is 255 characters.
zigbee2mqtt send device sensor.0x385b44fffe37682e_learned_ir_code](http://xxxxxxxx.local:8123/developer-tools/state#)
```

It appears:
- homeassistant accept only state value size <255 characters.
- homeassistant don't have such limitation for sensor attribute.

I don't know how zigbee2mqtt mqtt messages are interpreted by homeassistant to create device entities but the problem is  related with produced entity like sensor.0x385b44fffe37682e_learned_ir_code that use as state the ir_code that can be more than 255 characters.

Is it fixable on zigbee2mqtt by using learned_ir_code as attribute of another produced entity and not as its own entity/sensor with its own state or that need to be fixed on homeassistant side ?

Another issue with this device: I can put the device in learning state by using  "learn_ir_code":"ON" via mqtt or switch in zigbee2mqtt frontend but that doesn't work if i set to "on" the related entity on homeassistant (switch.0x385b44fffe37682e)

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

20221226

### Adapter

TI LAUNCHXL-CC1352P-2

**Comment by Ruud-cb** [comment]
Still an issue, any workarounds or solutions for this?
