### ISSUE TITLE
[New device support]: TS011F smart controller

### ISSUE THREAD

**Issue by Devligue** [Koenkk/zigbee2mqtt#16992]
### Link

https://sklep.automat-on.pl/Sterownik_ogrzewania_podlogowego_Zigbee_5_stref.html

### Database entry
```
{"id":5,"type":"Router","ieeeAddr":"0xa4c138f1b957e4c9","nwkAddr":33204,"manufId":4417,"manufName":"_TZ3000_j0ktmul1","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1,2,242,3,4,5],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[3,4,5,6,57344,57345,0],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65506":48,"65508":0,"65534":0,"modelId":"TS011F","manufacturerName":"_TZ3000_j0ktmul1","powerSource":1,"zclVersion":3,"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"32768":0,"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1,"moesStartUpOnOff":2,"tuyaBacklightSwitch":1}},"manuSpecificTuya_3":{"attributes":{"powerOnBehavior":2,"switchType":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c3c715","endpointID":242},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c3c715","endpointID":242},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c3c715","endpointID":242}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":266,"inClusterList":[4,5,6,57345],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":1,"onTime":0,"offWaitTime":0}},"manuSpecificTuya_3":{"attributes":{"powerOnBehavior":2}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c3c715","endpointID":242}],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":266,"inClusterList":[4,5,6,57345],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}},"manuSpecificTuya_3":{"attributes":{"powerOnBehavior":2}}},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":266,"inClusterList":[4,5,6,57345],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}},"manuSpecificTuya_3":{"attributes":{"powerOnBehavior":2}}},"binds":[],"configuredReportings":[],"meta":{}},"5":{"profId":260,"epId":5,"devId":266,"inClusterList":[4,5,6,57345],"outClusterList":[],"clusters":{"genOnOff":{"attributes":{"onOff":0,"onTime":0,"offWaitTime":0}},"manuSpecificTuya_3":{"attributes":{"powerOnBehavior":2}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":67,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1678492687167,"defaultSendRequestWhen":"immediate"}
```
### Comments

I tried to follow support new device page but got stuck at the following error:

```
/app/node_modules/zigbee-herdsman-converters/index.js:91
        if (converter.options) {
                      ^
TypeError: Cannot read properties of undefined (reading 'options')
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:91:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)
```

I am not sure what exactly I did wrong.

As a side note, my device actually gets recognized but incorrectly. When connected, it gets added as `TS011F_plug_1`. It seems to share some similarities - for example the switch works (although only for channel 1), and the child lock works.

Please advise

### External converter

```shell
# TS011F_smart_controller.js
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: tuya.fingerprint('TS011F', ['_TZ3000_j0ktmul1']),
    model: 'TS011F_smart_controller',
    vendor: 'AutomatOn',
    description: 'Smart controller - 5 channels',
    toZigbee: extend.switch().toZigbee.concat([tz.tuya_switch_type]),
    fromZigbee: extend.switch().fromZigbee.concat([fz.tuya_switch_type]),
    extend: tuya.extend.switch({
        electricalMeasurements: false,
        powerOutageMemory: false,
        childLock: true,
        endpoints: ['l1', 'l2', 'l3', 'l4', 'l5']
    }),
    exposes: [
        e.switch().withEndpoint('l1'),
        e.switch().withEndpoint('l2'),
        e.switch().withEndpoint('l3'),
        e.switch().withEndpoint('l4'),
        e.switch().withEndpoint('l5'),
        // exposes.presets.switch_type_5(),
    ],
    endpoint: (device) => {
        return {'l1': 1, 'l2': 2, 'l3': 3, 'l4': 4, 'l5': 5};
    },
    meta: {multiEndpoint: true},
    configure: async (device, coordinatorEndpoint, logger) => {
        await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(3), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(4), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(5), coordinatorEndpoint, ['genOnOff']);
        device.powerSource = 'Mains (single phase)';
        device.save();
    },
};

module.exports = definition;
```

**Comment by Devligue** [comment]
After some more trial and error, as well as help from @noclavil we came up with two somewhat working converters, although they are not exactly equivalent. In one the `power_on_behavior` works only globally while in the other I can set it only per endpoint.

There is still some functionality missing in both, but in general the most important settings are present.

I also don't quite understand why for approach 2 to work the endpoints need to be named `l1`, `l2`, ... instead of `ch1`, `ch2`, ...

### Approach 1 - extending tuya
```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    fingerprint: tuya.fingerprint('TS011F', ['_TZ3000_j0ktmul1']),
    // zigbeeModel: ['TS011F'],
    model: 'TS011F_smart_controller',
    vendor: 'AutomatOn',
    description: 'Smart controller - 5 channel',
    extend: tuya.extend.switch({endpoints: ['ch1', 'ch2', 'ch3', 'ch4', 'ch5'], childLock: true}),
    endpoint: (device) => {
        return {'ch1': 1, 'ch2': 2, 'ch3': 3, 'ch4': 4, 'ch5': 5};
    },
    meta: {multiEndpoint: true},
    configure: async (device, coordinatorEndpoint, logger) => {
        await tuya.configureMagicPacket(device, coordinatorEndpoint, logger);
        await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(3), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(4), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(5), coordinatorEndpoint, ['genOnOff']);
        device.save();
    },
};

module.exports = definition;
```

### Approach 2 - copying everything from tuya lib
```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const utils = require('zigbee-herdsman-converters/lib/utils');
const e = exposes.presets;
const ea = exposes.access;

const fzLocal = {
    power_on_behavior: {
        cluster: 'manuSpecificTuya_3',
        type: ['attributeReport', 'readResponse'],
        convert: (model, msg, publish, options, meta) => {
            const attribute = 'powerOnBehavior';
            const lookup = { 0: 'off', 1: 'on', 2: 'previous' };

            if (msg.data.hasOwnProperty(attribute)) {
                const property = utils.postfixWithEndpointName('power_on_behavior', msg, model, meta);
                return { [property]: lookup[msg.data[attribute]] };
            }
        },
    },
    child_lock: {
        cluster: 'genOnOff',
        type: ['attributeReport', 'readResponse'],
        convert: (model, msg, publish, options, meta) => {
            if (msg.data.hasOwnProperty('32768')) {
                const value = msg.data['32768'];
                return { child_lock: value ? 'LOCK' : 'UNLOCK' };
            }
        },
    }
}

const tzLocal = {
    power_on_behavior: {
        key: ['power_on_behavior'],
        convertSet: async (entity, key, value, meta) => {
            value = value.toLowerCase();
            const lookup = { 'off': 0, 'on': 1, 'previous': 2 };
            utils.validateValue(value, Object.keys(lookup));
            const pState = lookup[value];
            await entity.write('manuSpecificTuya_3', { 'powerOnBehavior': pState }, { disableDefaultResponse: true });
            return { state: { power_on_behavior: value } };
        },
        convertGet: async (entity, key, meta) => {
            await entity.read('manuSpecificTuya_3', ['powerOnBehavior']);
        },
    },
    child_lock: {
        key: ['child_lock'],
        convertSet: async (entity, key, value, meta) => {
            await entity.write('genOnOff', { 0x8000: { value: value === 'LOCK', type: 0x10 } });
        },
    }
}

const definition = {
    fingerprint: tuya.fingerprint('TS011F', ['_TZ3000_j0ktmul1']),
    // zigbeeModel: ['TS011F'],
    model: 'TS011F_smart_controller',
    vendor: 'AutomatOn',
    description: 'Smart controller - 5 channel',
    fromZigbee: [fz.on_off, fz.ignore_basic_report, fzLocal.power_on_behavior, fzLocal.child_lock],
    toZigbee: [tz.on_off, tzLocal.power_on_behavior, tzLocal.child_lock],
    exposes: [
        e.child_lock(),
        e.switch().withEndpoint('l1'),
        e.switch().withEndpoint('l2'),
        e.switch().withEndpoint('l3'),
        e.switch().withEndpoint('l4'),
        e.switch().withEndpoint('l5'),
        e.power_on_behavior().withEndpoint('l1'),
        e.power_on_behavior().withEndpoint('l2'),
        e.power_on_behavior().withEndpoint('l3'),
        e.power_on_behavior().withEndpoint('l4'),
        e.power_on_behavior().withEndpoint('l5'),
    ],
    endpoint: (device) => {
        return { 'l1': 1, 'l2': 2, 'l3': 3, 'l4': 4, 'l5': 5 };
    },
    meta: { multiEndpoint: true },
    configure: async (device, coordinatorEndpoint, logger) => {
        await tuya.configureMagicPacket(device, coordinatorEndpoint, logger);
        await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(3), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(4), coordinatorEndpoint, ['genOnOff']);
        await reporting.bind(device.getEndpoint(5), coordinatorEndpoint, ['genOnOff']);
        device.save();
    },
};

module.exports = definition;
```

**Comment by Devligue** [comment]
Closing due to https://github.com/Koenkk/zigbee-herdsman-converters/pull/5579
