### ISSUE TITLE
Moes BHT-002 State max length is 255 characters

### ISSUE THREAD

**Issue by danielszilagyi** [Koenkk/zigbee2mqtt#17005]
### What happened?

Been using some Moeshouse BHT-002 Zigbee thermostats. Have not had this kind of issue, and I cannot connect the issue to any updates or similar. I am using z2m edge. The issue is reported by Home Assistant but I believe the root cause might be corrected in z2m. Removed these thermostats from the network, deleted from HA, removed Mosquitto addon and reconfigured HA MQTT integration before reporting this issue. I have three of them and all set to manual schedule. Issue reappears after pairing.

```
2023-03-11 19:29:06.849 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback MQTT._mqtt_handle_message(<paho.mqtt.cl...x7f99caaa6420>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 693, in _mqtt_handle_message
    self._mqtt_data.state_write_requests.process_write_state_requests()
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 267, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 683, in _async_write_ha_state
    self.hass.states.async_set(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1512, in async_set
    state = State(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1144, in __init__
    raise InvalidStateError(
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.eloszoba_floor_program. State max length is 255 characters.
```

### What did you expect to happen?

I expect the device states to be able to flow into HA without issues

### How to reproduce it (minimal and precise)

Add a Moes BHT-002, check mqtt addon logs after some time.

### Zigbee2MQTT version

1.30.2-dev commit: 61cdda9

### Adapter firmware version

20210210

### Adapter

Tube's ZB PoE

### Debug log

```{
    "child_lock": "UNLOCK",
    "current_heating_setpoint": 19,
    "deadzone_temperature": 1,
    "heat": "OFF",
    "linkquality": 60,
    "local_temperature": 21.5,
    "local_temperature_calibration": -3,
    "max_temperature": 35,
    "max_temperature_limit": 32,
    "preset": "hold",
    "preset_mode": "hold",
    "program": {
        "saturday_p1_hour": 9,
        "saturday_p1_minute": 0,
        "saturday_p1_temperature": 25,
        "saturday_p2_hour": 17,
        "saturday_p2_minute": 0,
        "saturday_p2_temperature": 23,
        "saturday_p3_hour": 21,
        "saturday_p3_minute": 5,
        "saturday_p3_temperature": 23,
        "saturday_p4_hour": 23,
        "saturday_p4_minute": 30,
        "saturday_p4_temperature": 21,
        "sunday_p1_hour": 9,
        "sunday_p1_minute": 0,
        "sunday_p1_temperature": 25,
        "sunday_p2_hour": 22,
        "sunday_p2_minute": 30,
        "sunday_p2_temperature": 25,
        "sunday_p3_hour": 23,
        "sunday_p3_minute": 30,
        "sunday_p3_temperature": 23,
        "sunday_p4_hour": 23,
        "sunday_p4_minute": 59,
        "sunday_p4_temperature": 20,
        "weekdays_p1_hour": 8,
        "weekdays_p1_minute": 30,
        "weekdays_p1_temperature": 26,
        "weekdays_p2_hour": 10,
        "weekdays_p2_minute": 30,
        "weekdays_p2_temperature": 22,
        "weekdays_p3_hour": 12,
        "weekdays_p3_minute": 30,
        "weekdays_p3_temperature": 23.5,
        "weekdays_p4_hour": 23,
        "weekdays_p4_minute": 30,
        "weekdays_p4_temperature": 21
    },
    "running_state": "idle",
    "sensor": "AL",
    "system_mode": "heat",
    "device": {
        "applicationVersion": 65,
        "dateCode": "",
        "friendlyName": "Eloszoba_Floor",
        "hardwareVersion": 1,
        "ieeeAddr": "0x50325ffffe289f0c",
        "manufacturerID": 4098,
        "manufacturerName": "_TZE200_aoclfnxz",
        "model": "BHT-002-GCLZB",
        "networkAddress": 53406,
        "powerSource": "Mains (single phase)",
        "stackVersion": 0,
        "type": "Router",
        "zclVersion": 3
    },
    "min_temperature_limit": null
}```

**Comment by Koenkk** [comment]
Duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/16460
