### ISSUE TITLE
Centralite plug does not support `power_on_behavior`

### ISSUE THREAD

**Issue by ptr727** [Koenkk/zigbee2mqtt#17006]
### What happened?

I purchased a [Centralite](https://www.zigbee2mqtt.io/devices/4200-C.html#centralite-4200-c) plug because the docs said it supports `power_on_behavior`.
Turns out it [also](https://github.com/Koenkk/zigbee2mqtt/issues/16941) does not support `power_on_behavior`

```
2023-03-11 11:34:21MQTT publish: topic 'zigbee2mqtt/Centralite-Plug-CC9CEB', payload '{"device":{"dateCode":"","friendlyName":"Centralite-Plug-CC9CEB","hardwareVersion":0,"ieeeAddr":"0x5c0272fffecc9ceb","manufacturerID":4174,"manufacturerName":"Centralite Systems","model":"4200-C","networkAddress":45017,"powerSource":"Unknown","stackVersion":0,"type":"Router","zclVersion":2},"last_seen":"2023-03-11T19:34:13.878Z","linkquality":123,"power_on_behavior":null,"state":"OFF"}'
Error 2023-03-11 11:34:21Publish 'set' 'power_on_behavior' to 'Centralite-Plug-CC9CEB' failed: 'Error: Write 0x5c0272fffecc9ceb/1 genOnOff({"startUpOnOff":255}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Debug 2023-03-11 11:34:21Error: Write 0x5c0272fffecc9ceb/1 genOnOff({"startUpOnOff":255}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28) at Endpoint.write (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:397:22) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:117:13) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:247:36)
Info 2023-03-11 11:34:21MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'power_on_behavior' to 'Centralite-Plug-CC9CEB' failed: 'Error: Write 0x5c0272fffecc9ceb/1 genOnOff({\"startUpOnOff\":255}, {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'","meta":{"friendly_name":"Centralite-Plug-CC9CEB"},"type":"zigbee_publish_error"}'
```

```json
{
    "device": {
        "dateCode": "",
        "friendlyName": "Centralite-Plug-CC9CEB",
        "hardwareVersion": 0,
        "ieeeAddr": "0x5c0272fffecc9ceb",
        "manufacturerID": 4174,
        "manufacturerName": "Centralite Systems",
        "model": "4200-C",
        "networkAddress": 45017,
        "powerSource": "Unknown",
        "stackVersion": 0,
        "type": "Router",
        "zclVersion": 2
    },
    "last_seen": "2023-03-11T19:42:32.334Z",
    "linkquality": 131,
    "power_on_behavior": null,
    "state": "OFF"
}
```

### What did you expect to happen?

Documentation was accurate and plug did support `power_on_behavior`

### How to reproduce it (minimal and precise)

Try to configure power on behavior, get error.

### Zigbee2MQTT version

1.30.2 commit: cdf62ea

### Adapter firmware version

20221226

### Adapter

tubes ethernet

### Debug log

[z2mlog.log](https://github.com/Koenkk/zigbee2mqtt/files/10949308/z2mlog.log)

**Comment by Koenkk** [comment]
Disabled it!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
