### ISSUE TITLE
Aqara Pet Feeder Can Not Apply Changes To Schedule + Error When Reconfigure 

### ISSUE THREAD

**Issue by beeinaboats** [Koenkk/zigbee2mqtt#17077]
### What happened?

Whenever I try to update the schedule part of the settings for the aqara pet feeder, the apply option never allows me to click it. Like it won't become a clickable button despite having made changes.

I attempted to reconfigure but got an error. Logs show this is the error I got in its entirety: 

> RangeError: Attempt to access memory outside buffer bounds at new NodeError (node:internal/errors:387:5) at boundsError (node:internal/buffer:84:11) at Buffer.readUInt8 (node:internal/buffer:252:5) at /app/node_modules/zigbee-herdsman-converters/devices/xiaomi.js:167:51 at Array.forEach (<anonymous>) at Object.convert (/app/node_modules/zigbee-herdsman-converters/devices/xiaomi.js:163:38) at Receive.onDeviceMessage (/app/lib/extension/receive.ts:143:51) at EventEmitter.emit (node:events:525:35) at EventBus.emitDeviceMessage (/app/lib/eventBus.ts:102:22) at Controller.<anonymous> (/app/lib/zigbee.ts:106:27) 

### What did you expect to happen?

I expected the apply button to become clickable after having update the time / feeding amount in the schedule section of the pet feeder settings. Also no error when reconfigure 

### How to reproduce it (minimal and precise)

Update the feed size / time in the schedule part of the settings. Or try to reconfigure the device. 

I have tried removing the device and re adding to no avail.

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

20210708

### Adapter

ZBDongle-P

### Debug log

Info 2023-03-18 23:02:06Configuring 'pet feeder'
Debug 2023-03-18 23:02:06Received Zigbee message from 'pet feeder', type 'readResponse', cluster 'aqaraOpple', data '{"65521":{"data":[49,50,51],"type":"Buffer"}}' from endpoint 1 with groupID 0
Error 2023-03-18 23:02:06Exception while calling fromZigbee converter: Attempt to access memory outside buffer bounds}
Debug 2023-03-18 23:02:06RangeError: Attempt to access memory outside buffer bounds at new NodeError (node:internal/errors:387:5) at boundsError (node:internal/buffer:84:11) at Buffer.readUInt8 (node:internal/buffer:252:5) at /app/node_modules/zigbee-herdsman-converters/devices/xiaomi.js:167:51 at Array.forEach (<anonymous>) at Object.convert (/app/node_modules/zigbee-herdsman-converters/devices/xiaomi.js:163:38) at Receive.onDeviceMessage (/app/lib/extension/receive.ts:143:51) at EventEmitter.emit (node:events:525:35) at EventBus.emitDeviceMessage (/app/lib/eventBus.ts:102:22) at Controller.<anonymous> (/app/lib/zigbee.ts:106:27)
Info 2023-03-18 23:02:06Successfully configured 'pet feeder'
Info 2023-03-18 23:02:06MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"pet feeder"},"status":"ok","transaction":"8bajo-6"}'

**Comment by johnson7827** [comment]
I'm running into the same issue.
Additionally, when I make a change it dispenses even if its to turn off the LED and then the change does nothing.
Do you find a resolution?

I'm on zigbee2mqtt 1.32.1-1

**Directly from the Log, the payload looks correct.**

[254,38,68,129,0,0,192,252,9,147,1,1,0,171,0,4,29,105,0,0,18,28,95,17,43,10,241,255,65,9,0,5,179]
2023-07-12T01:17:01.682Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [14,92,0,85,1,2,9,147,29,140]
2023-07-12T01:17:01.682Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,38,68,129,0,0,192,252,9,147,1,1,0,171,0,4,29,105,0,0,18,28,95,17,43,10,241,255,65,9,0,5,179,14,92,0,85,1,2,9,147,29,140]
2023-07-12T01:17:01.682Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 38 - 2 - 4 - 129 - [0,0,192,252,9,147,1,1,0,171,0,4,29,105,0,0,18,28,95,17,43,10,241,255,65,9,0,5,179,14,92,0,85,1,2,9,147,29] - 140
2023-07-12T01:17:01.683Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":64704,"srcaddr":37641,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":171,"securityuse":0,"timestamp":6888708,"transseqnumber":0,"len":18,"data":{"type":"Buffer","data":[28,95,17,43,10,241,255,65,9,0,5,179,14,92,0,85,1,2]}}
2023-07-12T01:17:01.683Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":true,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":43,"manufacturerCode":4447,"commandIdentifier":10},"Payload":[{"attrId":65521,"dataType":65,"attrData":{"type":"Buffer","data":[0,5,179,14,92,0,85,1,2]}}],"Command":{"ID":10,"name":"report","parameters":[{"name":"attrId","type":33},{"name":"dataType","type":32},{"name":"attrData","type":1000}]}},"address":37641,"endpoint":1,"linkquality":171,"groupID":0,"wasBroadcast":false,"destinationEndpoint":1}'
2023-07-12T01:17:01.684Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
Zigbee2MQTT:info  2023-07-11 18:17:01: MQTT publish: topic 'zigbee2mqtt/Betty's Food Dispenser', payload '{"child_lock":"UNLOCK","error":false,"feed":"","feeding_size":1,"feeding_source":"remote","led_indicator":"OFF","linkquality":171,"mode":"manual","portion_weight":8,"portions_per_day":49,"schedule":[{"days":"everyday","hour":9,"minute":0,"size":1},{"days":"everyday","hour":13,"minute":0,"size":1},{"days":"everyday","hour":19,"minute":0,"size":1}],"serving_size":2,"update":{"installed_version":9761,"latest_version":9761,"state":"idle"},"update_available":null,"weight_per_day":392}'
