### ISSUE TITLE
Zigbee2mqtt stopped suddenly with 'Configuration is not consistent with adapter state/backup!' but no inconsistency in the logs

### ISSUE THREAD

**Issue by kkarolk** [Koenkk/zigbee2mqtt#17155]
### What happened?

Hi,
everything was fine with my zigbee2mqtt until one morning it stopped working. There was no updates, configuration changes etc. It just stopped working out of the blue. PAN ID, Network key, channel looks good from the log pov.

Interesting part in the log:
**2023-03-27T06:17:25.474Z zigbee-herdsman:adapter:zStack:startup:strategy (stage-2) adapter state does not match configuration**
2023-03-27T06:17:25.474Z zigbee-herdsman:adapter:zStack:startup:strategy (stage-3) got adapter backup
2023-03-27T06:17:25.474Z zigbee-herdsman:adapter:zStack:startup:strategy (stage-4) adapter state matches backup
Zigbee2MQTT:error 2023-03-27 08:17:25: Configuration is not consistent with adapter state/backup!
**Zigbee2MQTT:error 2023-03-27 08:17:25: - PAN ID: configured=6754, adapter=6754**
**Zigbee2MQTT:error 2023-03-27 08:17:25: - Extended PAN ID: configured=00124b0018eb4961, adapter=00124b0018eb4961**
**Zigbee2MQTT:error 2023-03-27 08:17:25: - Network Key: configured=01030507090b0d0f01020306070a0c0d, adapter=01030507090b0d0f01020306070a0c0d**
**Zigbee2MQTT:error 2023-03-27 08:17:25: - Channel List: configured=11, adapter=11**
Zigbee2MQTT:error 2023-03-27 08:17:25: Please update configuration to prevent further issues.

### Zigbee2MQTT version

1.30.2-1

### Adapter firmware version

cannot check

### Adapter

cc2538

### Debug log

2023-03-27T06:17:25.397Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvLength - {"id":130}
2023-03-27T06:17:25.399Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,2,33,19,130,0,178]
2023-03-27T06:17:25.401Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,19,24,0,104]
2023-03-27T06:17:25.401Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,19,24,0,104]
2023-03-27T06:17:25.401Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 19 - [24,0] - 104
2023-03-27T06:17:25.401Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvLength - {"length":24}
2023-03-27T06:17:25.402Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-03-27T06:17:25.403Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":130,"offset":0}
2023-03-27T06:17:25.403Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,130,0,0,0,187]
2023-03-27T06:17:25.404Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,26,97,28,0,24,0,56,14,177,98,17,191,15,96,173,47,177,19,218,77,70,4,0,0,0,209,134,127,0,134]
2023-03-27T06:17:25.405Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,26,97,28,0,24,0,56,14,177,98,17,191,15,96,173,47,177,19,218,77,70,4,0,0,0,209,134,127,0,134]
2023-03-27T06:17:25.405Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 26 - 3 - 1 - 28 - [0,24,0,56,14,177,98,17,191,15,96,173,47,177,19,218,77,70,4,0,0,0,209,134,127,0] - 134
2023-03-27T06:17:25.406Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":0,"len":24,"value":{"type":"Buffer","data":[0,56,14,177,98,17,191,15,96,173,47,177,19,218,77,70,4,0,0,0,209,134,127,0]}}
2023-03-27T06:17:25.406Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-03-27T06:17:25.408Z zigbee-herdsman:adapter:zStack:startup:strategy determining znp startup strategy
2023-03-27T06:17:25.409Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvLength - {"id":96}
2023-03-27T06:17:25.409Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,2,33,19,96,0,80]
2023-03-27T06:17:25.411Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,19,1,0,113]
2023-03-27T06:17:25.411Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,19,1,0,113]
2023-03-27T06:17:25.412Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 19 - [1,0] - 113
2023-03-27T06:17:25.412Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvLength - {"length":1}
2023-03-27T06:17:25.412Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-03-27T06:17:25.413Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":96,"offset":0}
2023-03-27T06:17:25.413Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,96,0,0,0,89]
2023-03-27T06:17:25.416Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,97,28,0,1,85,42]
2023-03-27T06:17:25.416Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,97,28,0,1,85,42]
2023-03-27T06:17:25.416Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 3 - 1 - 28 - [0,1,85] - 42
2023-03-27T06:17:25.418Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":0,"len":1,"value":{"type":"Buffer","data":[85]}}
2023-03-27T06:17:25.418Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-03-27T06:17:25.421Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvLength - {"id":33}
2023-03-27T06:17:25.422Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,2,33,19,33,0,17]
2023-03-27T06:17:25.425Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,19,116,0,4]
2023-03-27T06:17:25.425Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,19,116,0,4]
2023-03-27T06:17:25.425Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 19 - [116,0] - 4
2023-03-27T06:17:25.425Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvLength - {"length":116}
2023-03-27T06:17:25.426Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-03-27T06:17:25.427Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":33,"offset":0}
2023-03-27T06:17:25.428Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,33,0,0,0,24]
2023-03-27T06:17:25.431Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,118,97,28,0,116,62,5,2,81,20,81,0,100,0,0,0,1,5,1,143,0,7,0,2,13,30,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,98,26,8,0,0,8,0,0,15,15,4,0,1,0,0,0,1,0,0,0,0,97,73,235,24,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,60,12,0,1,120,10,1,0,0,0,0,0,0,0,28]
2023-03-27T06:17:25.432Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,118,97,28,0,116,62,5,2,81,20,81,0,100,0,0,0,1,5,1,143,0,7,0,2,13,30,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,98,26,8,0,0,8,0,0,15,15,4,0,1,0,0,0,1,0,0,0,0,97,73,235,24,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,60,12,0,1,120,10,1,0,0,0,0,0,0,0,28]
2023-03-27T06:17:25.432Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 118 - 3 - 1 - 28 - [0,116,62,5,2,81,20,81,0,100,0,0,0,1,5,1,143,0,7,0,2,13,30,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,98,26,8,0,0,8,0,0,15,15,4,0,1,0,0,0,1,0,0,0,0,97,73,235,24,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,60,12,0,1,120,10,1,0,0,0,0,0,0,0] - 28
2023-03-27T06:17:25.433Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":0,"len":116,"value":{"type":"Buffer","data":[62,5,2,81,20,81,0,100,0,0,0,1,5,1,143,0,7,0,2,13,30,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,98,26,8,0,0,8,0,0,15,15,4,0,1,0,0,0,1,0,0,0,0,97,73,235,24,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,60,12,0,1,120,10,1,0,0,0,0,0,0,0]}}
2023-03-27T06:17:25.433Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-03-27T06:17:25.439Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvLength - {"id":98}
2023-03-27T06:17:25.439Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,2,33,19,98,0,82]
2023-03-27T06:17:25.442Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,19,16,0,96]
2023-03-27T06:17:25.442Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,19,16,0,96]
2023-03-27T06:17:25.442Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 19 - [16,0] - 96
2023-03-27T06:17:25.443Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvLength - {"length":16}
2023-03-27T06:17:25.444Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-03-27T06:17:25.445Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":98,"offset":0}
2023-03-27T06:17:25.445Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,98,0,0,0,91]
2023-03-27T06:17:25.448Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,18,97,28,0,16,56,14,177,98,17,191,15,96,173,47,177,19,218,77,70,4,174]
2023-03-27T06:17:25.448Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,18,97,28,0,16,56,14,177,98,17,191,15,96,173,47,177,19,218,77,70,4,174]
2023-03-27T06:17:25.448Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 18 - 3 - 1 - 28 - [0,16,56,14,177,98,17,191,15,96,173,47,177,19,218,77,70,4] - 174
2023-03-27T06:17:25.449Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":0,"len":16,"value":{"type":"Buffer","data":[56,14,177,98,17,191,15,96,173,47,177,19,218,77,70,4]}}
2023-03-27T06:17:25.449Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-03-27T06:17:25.450Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvLength - {"id":58}
2023-03-27T06:17:25.451Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,2,33,19,58,0,10]
2023-03-27T06:17:25.452Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,19,17,0,97]
2023-03-27T06:17:25.452Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,19,17,0,97]
2023-03-27T06:17:25.452Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 19 - [17,0] - 97
2023-03-27T06:17:25.452Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvLength - {"length":17}
2023-03-27T06:17:25.453Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-03-27T06:17:25.453Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":58,"offset":0}
2023-03-27T06:17:25.453Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,58,0,0,0,3]
2023-03-27T06:17:25.455Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,19,97,28,0,17,0,1,3,5,7,9,11,13,15,1,2,3,6,7,10,12,13,117]
2023-03-27T06:17:25.455Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,19,97,28,0,17,0,1,3,5,7,9,11,13,15,1,2,3,6,7,10,12,13,117]
2023-03-27T06:17:25.455Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 19 - 3 - 1 - 28 - [0,17,0,1,3,5,7,9,11,13,15,1,2,3,6,7,10,12,13] - 117
2023-03-27T06:17:25.456Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":0,"len":17,"value":{"type":"Buffer","data":[0,1,3,5,7,9,11,13,15,1,2,3,6,7,10,12,13]}}
2023-03-27T06:17:25.456Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-03-27T06:17:25.457Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvLength - {"id":59}
2023-03-27T06:17:25.457Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,2,33,19,59,0,11]
2023-03-27T06:17:25.458Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,19,17,0,97]
2023-03-27T06:17:25.459Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,19,17,0,97]
2023-03-27T06:17:25.459Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 19 - [17,0] - 97
2023-03-27T06:17:25.459Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvLength - {"length":17}
2023-03-27T06:17:25.459Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-03-27T06:17:25.459Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":59,"offset":0}
2023-03-27T06:17:25.460Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,59,0,0,0,2]
2023-03-27T06:17:25.462Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,19,97,28,0,17,0,1,3,5,7,9,11,13,15,1,2,3,6,7,10,12,13,117]
2023-03-27T06:17:25.462Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,19,97,28,0,17,0,1,3,5,7,9,11,13,15,1,2,3,6,7,10,12,13,117]
2023-03-27T06:17:25.462Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 19 - 3 - 1 - 28 - [0,17,0,1,3,5,7,9,11,13,15,1,2,3,6,7,10,12,13] - 117
2023-03-27T06:17:25.462Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":0,"len":17,"value":{"type":"Buffer","data":[0,1,3,5,7,9,11,13,15,1,2,3,6,7,10,12,13]}}
2023-03-27T06:17:25.463Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-03-27T06:17:25.474Z zigbee-herdsman:adapter:zStack:startup:strategy (stage-1) adapter is configured
2023-03-27T06:17:25.474Z zigbee-herdsman:adapter:zStack:startup:strategy (stage-2) adapter state does not match configuration
2023-03-27T06:17:25.474Z zigbee-herdsman:adapter:zStack:startup:strategy (stage-3) got adapter backup
2023-03-27T06:17:25.474Z zigbee-herdsman:adapter:zStack:startup:strategy (stage-4) adapter state matches backup
Zigbee2MQTT:error 2023-03-27 08:17:25: Configuration is not consistent with adapter state/backup!
Zigbee2MQTT:error 2023-03-27 08:17:25: - PAN ID: configured=6754, adapter=6754
Zigbee2MQTT:error 2023-03-27 08:17:25: - Extended PAN ID: configured=00124b0018eb4961, adapter=00124b0018eb4961
Zigbee2MQTT:error 2023-03-27 08:17:25: - Network Key: configured=01030507090b0d0f01020306070a0c0d, adapter=01030507090b0d0f01020306070a0c0d
Zigbee2MQTT:error 2023-03-27 08:17:25: - Channel List: configured=11, adapter=11
Zigbee2MQTT:error 2023-03-27 08:17:25: Please update configuration to prevent further issues.
Zigbee2MQTT:error 2023-03-27 08:17:25: If you wish to re-commission your network, please remove coordinator backup at /config/zigbee2mqtt/coordinator_backup.json.
Zigbee2MQTT:error 2023-03-27 08:17:25: Re-commissioning your network will require re-pairing of all devices!
Error: startup failed - configuration-adapter mismatch - see logs above for more information
    at ZnpAdapterManager.determineStrategy (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:229:35)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:63:26)

**Comment by jonrasp** [comment]
This looks similar issue.
https://github.com/Koenkk/zigbee2mqtt/issues/17179
I resolved it by changing the pan id, extended pan id, and network key. This was as a last resort as I had to re-pair all of my zigbee devices afterwards.
