### ISSUE TITLE
startup failed - configuration-adapter mismatch

### ISSUE THREAD

**Issue by jonrasp** [Koenkk/zigbee2mqtt#17179]
### What happened?

Z2M in docker container on a RPi4.   
Latest Z2M container. RPi running Raspbian
SLZB-06 zigbee/ethernet gateway, connected via ethernet.
Has been running without issue for a couple of months.
Had a router outage, Z2M stopped working, now starts with the log below.

Have restarted Z2M, restarted Pi, recreated Z2M from same image. Recreated from new image. No change.

### What did you expect to happen?

Z2M to run without error

### How to reproduce it (minimal and precise)

Start or recreate Z2M from same image, or with new image

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

0.9.9 (latest)

### Adapter

SLZB-06 zigbee/ethernet gateway

### Debug log

```
Using '/app/data' as data directory

Zigbee2MQTT:debug 2023-03-29 21:52:08: Loaded state from file /app/data/state.json

Zigbee2MQTT:info  2023-03-29 21:52:08: Logging to console and directory: '/app/data/log/2023-03-29.21-52-08' filename: log.txt

Zigbee2MQTT:debug 2023-03-29 21:52:08: Removing old log directory '/app/data/log/2023-03-29.21-49-00'

Zigbee2MQTT:info  2023-03-29 21:52:08: Starting Zigbee2MQTT version 1.30.2 (commit #cdf62ea)

Zigbee2MQTT:info  2023-03-29 21:52:08: Starting zigbee-herdsman (0.14.96)

Zigbee2MQTT:debug 2023-03-29 21:52:08: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"baudRate":115200,"path":"tcp://192.168.0.48:6638"}}'

Zigbee2MQTT:error 2023-03-29 21:52:10: Configuration is not consistent with adapter state/backup!

Zigbee2MQTT:error 2023-03-29 21:52:10: - PAN ID: configured=6754, adapter=6754

Zigbee2MQTT:error 2023-03-29 21:52:10: - Extended PAN ID: configured=00124b0026d14762, adapter=00124b0026d14762

Zigbee2MQTT:error 2023-03-29 21:52:10: - Network Key: configured=01030507090b0d0f00020406080a0c0d, adapter=01030507090b0d0f00020406080a0c0d

Zigbee2MQTT:error 2023-03-29 21:52:10: - Channel List: configured=11, adapter=11

Zigbee2MQTT:error 2023-03-29 21:52:10: Please update configuration to prevent further issues.

Zigbee2MQTT:error 2023-03-29 21:52:10: If you wish to re-commission your network, please remove coordinator backup at /app/data/coordinator_backup.json.

Zigbee2MQTT:error 2023-03-29 21:52:10: Re-commissioning your network will require re-pairing of all devices!

Zigbee2MQTT:error 2023-03-29 21:52:10: Error while starting zigbee-herdsman

Zigbee2MQTT:error 2023-03-29 21:52:10: Failed to start zigbee

Zigbee2MQTT:error 2023-03-29 21:52:10: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions

Zigbee2MQTT:error 2023-03-29 21:52:10: Exiting...

Zigbee2MQTT:error 2023-03-29 21:52:10: Error: startup failed - configuration-adapter mismatch - see logs above for more information

    at ZnpAdapterManager.determineStrategy (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:229:35)

    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:63:26)

    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)

    at Zigbee.start (/app/lib/zigbee.ts:58:27)

    at Controller.start (/app/lib/controller.ts:101:27)

    at start (/app/index.js:107:5)
```

**Comment by jonrasp** [comment]
After reading
https://github.com/Koenkk/zigbee2mqtt/issues/10858
I modified the pan id, extended pan id and network key. My system now works, though from the error messages in the log, it's not clear to me why this stopped working, and now works again.

**Comment by Koenkk** [comment]
Fixed now thanks to @gneely74 !

> Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now and in the next release which is every 1st of the month.
