### ISSUE TITLE
Aqara SRTS-A01 - OTA update issue - map is not a function

### ISSUE THREAD

**Issue by LoonyWarrior** [Koenkk/zigbee2mqtt#17171]
### What happened?

Hi, I'm getting error when I try OTA update for Aqara SRTS-A01, I have three of them and it's same for all. Strangely enough, I can see that it's working for others but I couldn't find any misconfiguration. (I can not confirm if OTA works for other devices, those are the only one that I have and support OTA)

Error message is: **map is not a function**

SRTS-A01 firmware: 0.0.0_0825 

### Zigbee2MQTT version

1.30.2 commit: cdf62ea

### Adapter firmware version

7.1.1.0 build 273

### Adapter

EZSP v9

### Debug log

debug 2023-03-28 23:40:29Received MQTT message on 'home/bridge/request/device/ota_update/check' with data '{"id":"bathroom/trv","transaction":"1tmdh-3"}'
info 2023-03-28 23:40:29Checking if update available for 'bathroom/trv'
debug 2023-03-28 23:40:29Check if update available for '0x54ef4410005ab641' (lumi.airrtc.agl001)
debug 2023-03-28 23:40:29Using endpoint '1'
debug 2023-03-28 23:40:30Received Zigbee message from 'bathroom/trv', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":25,"imageType":5017,"manufacturerCode":4447}' from endpoint 1 with groupID 0
debug 2023-03-28 23:40:30Got OTA request '{"fieldControl":0,"manufacturerCode":4447,"imageType":5017,"fileVersion":25}'
debug 2023-03-28 23:40:30ZigbeeOTA: downloaded main index
debug 2023-03-28 23:40:30ZigbeeOTA: Loading override index https://github.com/Koenkk/zigbee-OTA/blob/master/index.json
info 2023-03-28 23:40:31MQTT publish: topic 'home/bridge/response/device/ota_update/check', payload '{"data":{"id":"bathroom/trv"},"error":"Failed to check if update available for 'bathroom/trv' (localIndex.concat(...).map is not a function)","status":"error","transaction":"1tmdh-3"}'
error 2023-03-28 23:40:31Failed to check if update available for 'bathroom/trv' (localIndex.concat(...).map is not a function)
debug 2023-03-28 23:40:31TypeError: localIndex.concat(...).map is not a function at getIndex (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/lib/ota/zigbeeOTA.js:91:41) at processTicksAndRejections (node:internal/process/task_queues:95:5) at getImageMeta (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/lib/ota/zigbeeOTA.js:102:20) at isNewImageAvailable (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/lib/ota/common.js:260:18) at Object.isUpdateAvailable (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/lib/ota/common.js:251:29) at OTAUpdate.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/otaUpdate.ts:203:45)
debug 2023-03-28 23:40:34Saving state to file /opt/zigbee2mqtt/data/state.json

**Comment by LoonyWarrior** [comment]
I figured it out few moments after I posted this ticket. Issue was the link for the index file. I used link from documentation "https://github.com/Koenkk/zigbee-OTA/blob/master/index.json" but I should use RAW version of that file "https://raw.githubusercontent.com/Koenkk/zigbee-OTA/master/index.json"

How I got in this situation:
I'm new with zigbee and my first and only device month ago was Sonoff ZBMINI and I was simply tring to update it with OTA, it doesn't matter that it can't be done. While doing this I changed the link for index file and overrided the default one. Then, when I was done, I tried to remove the link but the frontend does not allow this, so I had to keep some value there and that was the moment I used the link from documentation.

So it was definitely my fault, but if I may, I have two suggestions for improvement.

1. User should be able to remove the override option from the frontend
2. Error message should state that there is a issue with index file format ("map is not a function" isn't telling me that)
3. ...and it would be great to mention in documentation that you have to use RAW format
