### ISSUE TITLE
_TZ3000_5ajpkyq6 - Smart light switch - 4 gang with neutral wire

### ISSUE THREAD

**Issue by TeHashX** [Koenkk/zigbee2mqtt#17188]
### What happened?

I just added the switch ZWSM16-B4 and seen as TS0004 https://www.aliexpress.com/item/1005005245990658.html
I have 3 issues:
1 - when I try to change "power_on_behavior" I get error:

<img width="752" alt="Screenshot 2023-03-30 190043" src="https://user-images.githubusercontent.com/1405188/228896261-9a6cafe3-6785-4b87-a2db-4b8ac565b18e.png">

2 - With smart life app, the switch supports 3 type of switches: toggle, toggle syncronous and momentary
Can be enabled in Z2M frontend?
![Screenshot_20230329-170930](https://user-images.githubusercontent.com/1405188/228893942-cd77ad34-4419-4dde-9c94-956b3b0924f2.png)

3 - If I toggle on/off the physical switch for 5 times, will leave the network and I have to repair, not sure if this behaviour can be disabled from Z2M or changing firmware only.

### What did you expect to happen?

At least point 1 and 2 to be fixed if possible.

### Zigbee2MQTT version

1.30.2

### Adapter firmware version

'{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20221226,"transportrev":2},"type":"zStack3x0"}'

### Adapter

ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Debug log

`Debug 2023-03-30 18:34:15Received MQTT message on 'zigbee2mqtt/0xa4c138eed0915397/set' with data '{"power_on_behavior_l1":"previous"}'
Debug 2023-03-30 18:34:15Publishing 'set' 'power_on_behavior' to '0xa4c138eed0915397'
Info 2023-03-30 18:34:17MQTT publish: topic 'zigbee2mqtt/0xa4c138eed0915397', payload '{"last_seen":"2023-03-30T18:34:17+03:00","linkquality":94,"power_on_behavior_l1":null,"power_on_behavior_l2":null,"power_on_behavior_l3":null,"power_on_behavior_l4":null,"state_l1":"OFF","state_l2":"OFF","state_l3":"OFF","state_l4":"OFF"}'
Error 2023-03-30 18:34:17Publish 'set' 'power_on_behavior' to '0xa4c138eed0915397' failed: 'Error: Write 0xa4c138eed0915397/1 manuSpecificTuya_3({"powerOnBehavior":2}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Debug 2023-03-30 18:34:17Error: Write 0xa4c138eed0915397/1 manuSpecificTuya_3({"powerOnBehavior":2}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28) at Endpoint.write (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:397:22) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/devices/tuya.js:143:13) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:247:36)`

**Comment by TeHashX** [comment]
Bump
