### ISSUE TITLE
IPv6 to IPv4 fallback for OTA downloads

### ISSUE THREAD

**Issue by satter** [Koenkk/zigbee2mqtt#17207]
### What happened?

I have half-broken IPv6 connectivity which breaks OTA downloads for Tyua devices

Hostname `images.tuyaeu.com` has both v4 and v6 records, but v6 is timing out from my z2m host
```
Apr 01 09:20:57 homie1 npm[1315400]: Zigbee2MQTT:info  2023-04-01 09:20:57: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"kitchen/tuya_plug2"},"error":"Update of 'kitchen/tuya_plug2' failed (connect ETIMEDOUT 2600:9000:2368:8600:11:c26f:be40:93a1:443)","status":"error","transaction":"68kgc-5"}'
Apr 01 09:20:57 homie1 npm[1315400]: Zigbee2MQTT:error 2023-04-01 09:20:57: Update of 'kitchen/tuya_plug2' failed (connect ETIMEDOUT 2600:9000:2368:8600:11:c26f:be40:93a1:443)
Apr 01 09:20:57 homie1 npm[1315400]: Zigbee2MQTT:debug 2023-04-01 09:20:57: Error: connect ETIMEDOUT 2600:9000:2368:8600:11:c26f:be40:93a1:443
Apr 01 09:20:57 homie1 npm[1315400]:     at Function.AxiosError.from (/opt/zigbee2mqtt/node_modules/axios/lib/core/AxiosError.js:89:14)
Apr 01 09:20:57 homie1 npm[1315400]:     at RedirectableRequest.handleRequestError (/opt/zigbee2mqtt/node_modules/axios/lib/adapters/http.js:577:25)
Apr 01 09:20:57 homie1 npm[1315400]:     at RedirectableRequest.emit (node:events:513:28)
Apr 01 09:20:57 homie1 npm[1315400]:     at ClientRequest.eventHandlers.<computed> (/opt/zigbee2mqtt/node_modules/follow-redirects/index.js:14:24)
Apr 01 09:20:57 homie1 npm[1315400]:     at ClientRequest.emit (node:events:513:28)
Apr 01 09:20:57 homie1 npm[1315400]:     at TLSSocket.socketErrorListener (node:_http_client:502:9)
Apr 01 09:20:57 homie1 npm[1315400]:     at TLSSocket.emit (node:events:513:28)
Apr 01 09:20:57 homie1 npm[1315400]:     at emitErrorNT (node:internal/streams/destroy:151:8)
Apr 01 09:20:57 homie1 npm[1315400]:     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
Apr 01 09:20:57 homie1 npm[1315400]:     at processTicksAndRejections (node:internal/process/task_queues:82:21)
```
When I block IPv6 on the router with reject-admin-prohibiter or reject-no-route then z2m fails instantly:

```
Apr 01 09:09:53 homie1 npm[1315400]: Zigbee2MQTT:debug 2023-04-01 09:09:53: Received MQTT message on 'zigbee2mqtt/bridge/request/device/ota_update/update' with data '{"id":"kitchen/tuya_plug2","transaction":"68kgc-3"}'
Apr 01 09:09:53 homie1 npm[1315400]: Zigbee2MQTT:info  2023-04-01 09:09:53: Updating 'kitchen/tuya_plug2' to latest firmware
Apr 01 09:09:53 homie1 npm[1315400]: Zigbee2MQTT:debug 2023-04-01 09:09:53: Received Zigbee message from 'kitchen/tuya_plug2', type 'readResponse', cluster 'genBasic', data '{"dateCode":""}' from endpoint 1 with groupID 0
Apr 01 09:09:53 homie1 npm[1315400]: Zigbee2MQTT:info  2023-04-01 09:09:53: MQTT publish: topic 'zigbee2mqtt/kitchen/tuya_plug2', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","last_seen":"2023-04-01T09:09:53+00:00","linkquality":83,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"state":"available"},"voltage":210}'
Apr 01 09:09:53 homie1 npm[1315400]: Zigbee2MQTT:debug 2023-04-01 09:09:53: Updating to latest '0xa4c138f4cf1556ed' (TS011F)
Apr 01 09:09:53 homie1 npm[1315400]: Zigbee2MQTT:debug 2023-04-01 09:09:53: Using endpoint '1'
Apr 01 09:09:53 homie1 npm[1315400]: Zigbee2MQTT:debug 2023-04-01 09:09:53: Received Zigbee message from 'kitchen/tuya_plug2', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":77,"imageType":54179,"manufacturerCode":4417}' from endpoint 1 with groupID 0
Apr 01 09:09:53 homie1 npm[1315400]: Zigbee2MQTT:info  2023-04-01 09:09:53: MQTT publish: topic 'zigbee2mqtt/kitchen/tuya_plug2', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","last_seen":"2023-04-01T09:09:53+00:00","linkquality":80,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"state":"available"},"voltage":210}'
Apr 01 09:09:53 homie1 npm[1315400]: Zigbee2MQTT:debug 2023-04-01 09:09:53: Got OTA request '{"fieldControl":0,"manufacturerCode":4417,"imageType":54179,"fileVersion":77}'
Apr 01 09:09:53 homie1 npm[1315400]: Zigbee2MQTT:debug 2023-04-01 09:09:53: Update of 'kitchen/tuya_plug2' failed (Error: connect EHOSTUNREACH 2606:50c0:8003::154:443)
Apr 01 09:09:53 homie1 npm[1315400]: Zigbee2MQTT:info  2023-04-01 09:09:53: MQTT publish: topic 'zigbee2mqtt/kitchen/tuya_plug2', payload '{"child_lock":"UNLOCK","current":0,"energy":0,"indicator_mode":"off/on","last_seen":"2023-04-01T09:09:53+00:00","linkquality":80,"power":0,"power_outage_memory":"restore","state":"OFF","update":{"installed_version":77,"latest_version":192,"state":"available"},"voltage":210}'
Apr 01 09:09:53 homie1 npm[1315400]: Zigbee2MQTT:info  2023-04-01 09:09:53: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"kitchen/tuya_plug2"},"error":"Update of 'kitchen/tuya_plug2' failed (connect EHOSTUNREACH 2606:50c0:8003::154:443)","status":"error","transaction":"68kgc-3"}'
Apr 01 09:09:53 homie1 npm[1315400]: Zigbee2MQTT:error 2023-04-01 09:09:53: Update of 'kitchen/tuya_plug2' failed (connect EHOSTUNREACH 2606:50c0:8003::154:443)
Apr 01 09:09:53 homie1 npm[1315400]: Zigbee2MQTT:debug 2023-04-01 09:09:53: Error: connect EHOSTUNREACH 2606:50c0:8003::154:443
Apr 01 09:09:53 homie1 npm[1315400]:     at Function.AxiosError.from (/opt/zigbee2mqtt/node_modules/axios/lib/core/AxiosError.js:89:14)
Apr 01 09:09:53 homie1 npm[1315400]:     at RedirectableRequest.handleRequestError (/opt/zigbee2mqtt/node_modules/axios/lib/adapters/http.js:577:25)
Apr 01 09:09:53 homie1 npm[1315400]:     at RedirectableRequest.emit (node:events:513:28)
Apr 01 09:09:53 homie1 npm[1315400]:     at ClientRequest.eventHandlers.<computed> (/opt/zigbee2mqtt/node_modules/follow-redirects/index.js:14:24)
Apr 01 09:09:53 homie1 npm[1315400]:     at ClientRequest.emit (node:events:513:28)
Apr 01 09:09:53 homie1 npm[1315400]:     at TLSSocket.socketErrorListener (node:_http_client:502:9)
Apr 01 09:09:53 homie1 npm[1315400]:     at TLSSocket.emit (node:events:513:28)
Apr 01 09:09:53 homie1 npm[1315400]:     at emitErrorNT (node:internal/streams/destroy:151:8)
Apr 01 09:09:53 homie1 npm[1315400]:     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
Apr 01 09:09:53 homie1 npm[1315400]:     at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### What did you expect to happen?

I expected z2m to fallback from ipv6 to ipv4 addresses if v6 returning error, as wget would do:
```
~# wget https://images.tuyaeu.com/smart/firmware/upgrade/20220907/1662545193-oem_zg_tl8258_plug_OTA_3.0.0.bin
--2023-04-01 09:33:08--  https://images.tuyaeu.com/smart/firmware/upgrade/20220907/1662545193-oem_zg_tl8258_plug_OTA_3.0.0.bin
Resolving images.tuyaeu.com (images.tuyaeu.com)... 2600:9000:2368:a400:11:c26f:be40:93a1, 2600:9000:2368:8600:11:c26f:be40:93a1, 2600:9000:2368:bc00:11:c26f:be40:93a1, ...
Connecting to images.tuyaeu.com (images.tuyaeu.com)|2600:9000:2368:a400:11:c26f:be40:93a1|:443... failed: Network is unreachable.
Connecting to images.tuyaeu.com (images.tuyaeu.com)|2600:9000:2368:8600:11:c26f:be40:93a1|:443... failed: Network is unreachable.
Connecting to images.tuyaeu.com (images.tuyaeu.com)|2600:9000:2368:bc00:11:c26f:be40:93a1|:443... failed: Network is unreachable.
Connecting to images.tuyaeu.com (images.tuyaeu.com)|2600:9000:2368:3c00:11:c26f:be40:93a1|:443... failed: Network is unreachable.
Connecting to images.tuyaeu.com (images.tuyaeu.com)|2600:9000:2368:fc00:11:c26f:be40:93a1|:443... failed: Network is unreachable.
Connecting to images.tuyaeu.com (images.tuyaeu.com)|2600:9000:2368:3e00:11:c26f:be40:93a1|:443... failed: Network is unreachable.
Connecting to images.tuyaeu.com (images.tuyaeu.com)|2600:9000:2368:cc00:11:c26f:be40:93a1|:443... failed: Network is unreachable.
Connecting to images.tuyaeu.com (images.tuyaeu.com)|2600:9000:2368:2000:11:c26f:be40:93a1|:443... failed: Network is unreachable.
Connecting to images.tuyaeu.com (images.tuyaeu.com)|108.156.22.109|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 307682 (300K) [application/octet-stream]
Saving to: ‘1662545193-oem_zg_tl8258_plug_OTA_3.0.0.bin.2’

1662545193-oem_zg_tl8258_plug_OTA_3.0.0.bin.2      100%[================================================================================================================>] 300.47K  --.-KB/s    in 0.02s

2023-04-01 09:33:10 (13.6 MB/s) - ‘1662545193-oem_zg_tl8258_plug_OTA_3.0.0.bin.2’ saved [307682/307682]
```

### How to reproduce it (minimal and precise)

1. Start z2m on host with ipv6 connectivity but with `images.tuyaeu.com` unreachable
2. Start OTA update for Tuya device
3. Wait for ipv6 connectivity error

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

20221226

### Adapter

Sonoff USB Dongle plus

**Comment by fir3drag0n** [comment]
Same problem. Is there a solution?
