### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by itajackass** [Koenkk/zigbee2mqtt#1727]
I'm on latest HA version installed on raspbian and latest zigbee2mqtt version. 

After a big times my aqara sensor show me always same temperature (retain true) , i checked zigbee2mqtt functionality. 

I get into opt/zigbee2mqtt folder and type:

Npm start

I get this error on module deep-diff. No info on google search :(. Anyone with same problem? 

> zigbee2mqtt@1.4.0 start /opt/zigbee2mqtt
> node index.js

  zigbee2mqtt:info 2019-7-13 4:14:34 PM Logging to directory: '/opt/zigbee2mqtt/data/log/2019-07-13.16-14-34'
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'deep-diff'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/zigbee2mqtt/lib/extension/groups.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.4.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-07-13T14_14_35_608Z-debug.log

**Comment by Koenkk** [comment]
In `/opt/zigbee2mqtt`, execute `rm -rf node_modules && npm install`.
