### ISSUE TITLE
Exception while calling fromZigbee converter: Cannot read properties of undefined (reading 'split')}

### ISSUE THREAD

**Issue by yolkhovyy** [Koenkk/zigbee2mqtt#17480]
### What happened?

IKEA E2001/E2002 added and works fine, an exception occurs. 

### What did you expect to happen?

No exceptions in the log

### How to reproduce it (minimal and precise)

Add IKEA E2001/E2002, observe logs

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

20211115

### Adapter

cc2531

### Debug log

zigbee2mqtt  | Zigbee2MQTT:error 2023-04-28 02:19:09: Exception while calling fromZigbee converter: Cannot read properties of undefined (reading 'split')}
zigbee2mqtt  | Zigbee2MQTT:error 2023-04-28 02:19:09: Failed to configure 'room_rc', attempt 1 (TypeError: Cannot read properties of undefined (reading 'split')
zigbee2mqtt  |     at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/ikea.js:757:52)
zigbee2mqtt  |     at Configure.configure (/app/lib/extension/configure.ts:117:37)
zigbee2mqtt  |     at EventEmitter.<anonymous> (/app/lib/extension/configure.ts:82:62)
zigbee2mqtt  |     at EventEmitter.emit (node:events:525:35)
zigbee2mqtt  |     at EventBus.emitLastSeenChanged (/app/lib/eventBus.ts:52:22)
zigbee2mqtt  |     at Controller.<anonymous> (/app/lib/zigbee.ts:66:27)
zigbee2mqtt  |     at Controller.emit (node:events:513:28)
zigbee2mqtt  |     at Controller.selfAndDeviceEmit (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:515:14)
zigbee2mqtt  |     at Controller.onZclOrRawData (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:727:18)
zigbee2mqtt  |     at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:144:70))

**Comment by yolkhovyy** [comment]
This worked
