### ISSUE TITLE
Issue with Zigbee2mqtt install

### ISSUE THREAD

**Issue by Deblen** [Koenkk/zigbee2mqtt#1749]
# Bug Report
 zigbee2mqtt:info 7/17/2019, 8:50:22 PM Zigbee: allowing new devices to join.
  zigbee2mqtt:info 7/17/2019, 8:50:22 PM Connecting to MQTT server at mqtt://192.168.3.10:8123
  zigbee2mqtt:info 7/17/2019, 8:50:22 PM zigbee-shepherd ready
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: Not supported
    at Parser._parsePayload (/zigbee2mqtt-1.4.0/node_modules/mqtt-packet/parser.js:130:25)
    at Parser.parse (/zigbee2mqtt-1.4.0/node_modules/mqtt-packet/parser.js:37:48)
    at Writable.writable._write (/zigbee2mqtt-1.4.0/node_modules/mqtt/lib/client.js:301:12)
    at doWrite (/zigbee2mqtt-1.4.0/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/zigbee2mqtt-1.4.0/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/zigbee2mqtt-1.4.0/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:693:20)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
Emitted 'error' event at:
    at Parser.emit (events.js:198:13)
    at Parser._emitError (/zigbee2mqtt-1.4.0/node_modules/mqtt-packet/parser.js:373:8)
    at Parser._parsePayload (/zigbee2mqtt-1.4.0/node_modules/mqtt-packet/parser.js:130:14)
    at Parser.parse (/zigbee2mqtt-1.4.0/node_modules/mqtt-packet/parser.js:37:48)
    [... lines matching original stack trace ...]
    at Socket.emit (events.js:198:13)
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.4.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-17T11_20_22_512Z-debug.log
2019-07-17T20:50:25: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-07-17T20:50:25: PM2 log: App [npm:0] starting in -fork mode-
2019-07-17T20:50:25: PM2 log: App [npm:0] online
> zigbee2mqtt@1.4.0 start /zigbee2mqtt-1.4.0
> node index.js

## What did you expect to happen
Connect to zigbbee Xiamo Aqura's
## Debug Info
zigbee2mqtt version:
CC253X firmware version:

**Comment by Deblen** [comment]
I now have it working,
I had :8123 at the end of my broker address, removed it, now working.

Deblen
