### ISSUE TITLE
Zigbee2MQTT Crashed: TuYa TS0215A_sos switch Timeout Problem

### ISSUE THREAD

**Issue by GodDracula** [Koenkk/zigbee2mqtt#17601]
### What happened?

After i have pressed  TuYa TS0215A_sos switch for serveral times, the Zigbee2MQTT just Crashed on Error:{"frameId":"stackStatusHandler","sequence":null} after 10000ms
at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
at listOnTimeout (node:internal/timers:569:17)
at processTimers (node:internal/timers:512:7)
How can i solve the problem?Help!!

### What did you expect to happen?

I expected the  Zigbee2MQTT won't crash

### How to reproduce it (minimal and precise)

Just press  TuYa TS0215A_sos switch for serveral times quickly  the Zigbee2MQTT crashed

### Zigbee2MQTT version

1.30.3

### Adapter firmware version

6.7.9.0 build 405

### Adapter

EZSP v8

### Debug log

2023-05-08 15:36:06 Error: {"frameId":"stackStatusHandler","sequence":null} after 10000ms
2023-05-08 15:36:06     at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
2023-05-08 15:36:06     at listOnTimeout (node:internal/timers:569:17)
2023-05-08 15:36:06     at processTimers (node:internal/timers:512:7)

**Comment by GodDracula** [comment]
mqttjs:client _handlePublish: qos 0 +1ms
  mqttjs:client work :: getting next packet in queue +0ms
  mqttjs:client work :: packet pulled from queue +0ms
  mqttjs:client _handlePacket :: emitting packetreceive +1ms
  mqttjs:client _handlePublish: packet Packet { cmd: 'publish', retain: false, qos: 0, dup: false, length: 198, topic: 'zigbee2mqtt/bridge/logging', payload: <Buffer 7b 22 6c 65 76 65 6c 22 3a 22 69 6e 66 6f 22 2c 22 6d 65 73 73 61 67 65 22 3a 22 4d 51 54 54 20 70 75 62 6c 69 73 68 3a 20 74 6f 70 69 63 20 27 7a 69 ... 120 more bytes> } +0ms
  mqttjs:client _handlePublish: qos 0 +0ms
  mqttjs:client work :: getting next packet in queue +1ms
  mqttjs:client work :: packet pulled from queue +0ms
  mqttjs:client _handlePacket :: emitting packetreceive +0ms
  mqttjs:client _handlePublish: packet Packet { cmd: 'publish', retain: false, qos: 0, dup: false, length: 99, topic: 'zigbee2mqtt/0xa4c138d79f52c2fc', payload: <Buffer 7b 22 61 63 74 69 6f 6e 22 3a 22 65 6d 65 72 67 65 6e 63 79 22 2c 22 62 61 74 74 65 72 79 22 3a 38 2c 22 6c 69 6e 6b 71 75 61 6c 69 74 79 22 3a 32 32 ... 17 more bytes> } +0ms
  mqttjs:client _handlePublish: qos 0 +1ms
  zigbee-herdsman:adapter:ezsp:uart --> Error: Error: {"sequence":1} after 2000ms +9s
  zigbee-herdsman:adapter:ezsp:uart -!- break rewaiting (1) +1ms
  zigbee-herdsman:adapter:ezsp:uart Can't resend DATA frame (0,1,1): 7800017e00fcc2529fd738c1a401 +0ms
  zigbee-herdsman:adapter:ezsp:driv Reset connection. Try 0 +2m
  zigbee-herdsman:adapter:ezsp:driv Stop driver +0ms
  zigbee-herdsman:adapter:ezsp:ezsp Stop ezsp +9s
  zigbee-herdsman:adapter:ezsp:erro Request error Error: Failure send setExtendedTimeout:{"type":"Buffer","data":[120,0,1,126,0,252,194,82,159,215,56,193,164,1]}: Error: Failure send setExtendedTimeout:{"type":"Buffer","data":[120,0,1,126,0,252,194,82,159,215,56,193,164,1]}
  zigbee-herdsman:adapter:ezsp:erro     at D:\Project\zigbee2mqtt-1.30.4\node_modules\zigbee-herdsman\src\adapter\ezsp\driver\ezsp.ts:562:23
  zigbee-herdsman:adapter:ezsp:erro     at Queue.executeNext (D:\Project\zigbee2mqtt-1.30.4\node_modules\zigbee-herdsman\src\utils\queue.ts:32:32) +0ms      
  zigbee-herdsman:adapter:ezsp:debg sendZclFrameToEndpointInternal 0xa4c138d79f52c2fc:16631/1 (0,0,5) +9s
  zigbee-herdsman:adapter:ezsp:ezsp ==> setExtendedTimeout: {"remoteEui64":{"_value":{"type":"Buffer","data":[164,193,56,215,159,82,194,252]}},"extendedTimeout":true} +24ms
  zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"setExtendedTimeout","_id_":126,"_isRequest_":true,"remoteEui64":{"_value":{"type":"Buffer","data":[164,193,56,215,159,82,194,252]}},"extendedTimeout":true} +1ms
  zigbee-herdsman:adapter:ezsp:uart --> DATA (1,1,0): 7900017e00fcc2529fd738c1a401 +26ms
  zigbee-herdsman:adapter:ezsp:uart --> [7d313b21a92a2ae9700b0b9d1d6bf19342b27e] +9s
  zigbee-herdsman:adapter:ezsp:uart -?- waiting (2) +1ms
  zigbee-herdsman:controller:endpoint DefaultResponse 0xa4c138d79f52c2fc/1 1281(2, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error) +0ms
  zigbee-herdsman:controller:device:error Default response to 0xa4c138d79f52c2fc failed +0ms

**Comment by GodDracula** [comment]
How can i solve the problem?Help
