### ISSUE TITLE
OTA fails for Xiaomi SP-EUC01

### ISSUE THREAD

**Issue by KimCarlsen** [Koenkk/zigbee2mqtt#17619]
### What happened?

iCheck for update tells that there is a new firmware available. (firmware build date: 12-06-2021) 
when clicking update and ok, it state no new image available

### What did you expect to happen?

to be updated or not showing there are updates

### Zigbee2MQTT version

1.30.4

### Adapter firmware version

20220219

### Adapter

Sonoff CC2652P

### Debug log

error 2023-05-09 18:31:08: Update of 'xxx' failed (No new image available)
debug 2023-05-09 18:31:08: AssertionError [ERR_ASSERTION]: No new image available
    at getNewImage (D:\Z2M\node_modules\zigbee-herdsman-converters\lib\ota\common.js:422:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.updateToLatest (D:\Z2M\node_modules\zigbee-herdsman-converters\lib\ota\common.js:282:19)
    at OTAUpdate.onMQTTMessage (D:\Z2M\lib\extension\otaUpdate.ts:257:21)

**Comment by KimCarlsen** [comment]
Still an issue in 1.31.0

**Comment by KimCarlsen** [comment]
Still an issue in1.32.1
