### ISSUE TITLE
Exception while calling fromZigbee converter: Cannot use 'in' operator to search for 'power' in undefined}

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#17666]
### What happened?

Exception while calling fromZigbee converter: Cannot use 'in' operator to search for 'power' in undefined}
debug 13-05-2023 13:55:26: TypeError: Cannot use 'in' operator to search for 'power' in undefined
    at Object.convert (/app/node_modules/zigbee-herdsman-converters/devices/tuya.js:906:29)
    at Receive.onDeviceMessage (/app/lib/extension/receive.ts:150:51)
    at EventEmitter.emit (node:events:525:35)
    at EventBus.emitDeviceMessage (/app/lib/eventBus.ts:102:22)
    at Controller.<anonymous> (/app/lib/zigbee.ts:106:27)
    at Controller.emit (node:events:513:28)
    at Controller.selfAndDeviceEmit (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:515:14)
    at Controller.onZclOrRawData (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:726:18)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:144:70)
    at ZStackAdapter.emit (node:events:513:28)

### What did you expect to happen?

i have added an converter to my config file

### Zigbee2MQTT version

 1.30.4-dev commit: 3085608

### Adapter firmware version

20221226

### Adapter

Zigbee ESP32GW (Zigstar)

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/11468809/log.txt)

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
