### ISSUE TITLE
Zigbee2MQTT:error 15-05-2023 23:09:40: TypeError: Cannot read properties of null (reading 'key')

### ISSUE THREAD

**Issue by cloudbr34k84** [Koenkk/zigbee2mqtt#17688]
### What happened?

who knows again!

### Zigbee2MQTT version

1.30.4-1

### Adapter firmware version

zStack3x0

### Adapter

Zigbee ESP32GW (Zigstar)

### Debug log

debug 15-05-2023 23:08:49: Loaded state from file /config/zigbee2mqtt/state.json
info  15-05-2023 23:08:49: Logging to console and directory: '/config/zigbee2mqtt/data/log/2023-05-15.23-08-49' filename: log.txt
debug 15-05-2023 23:08:49: Removing old log directory '/config/zigbee2mqtt/data/log/2023-05-15.22-49-34'
info  15-05-2023 23:08:49: Starting Zigbee2MQTT version 1.30.4 (commit #unknown)
info  15-05-2023 23:08:49: Starting zigbee-herdsman (0.14.111)
debug 15-05-2023 23:08:49: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[26],"extendedPanID":[1,2,3,4,5,6,7,8],"networkKey":"HIDDEN","panID":48739},"serialPort":{"path":"tcp://192.168.68.103:6638"}}'
error 15-05-2023 23:09:40: Error while starting zigbee-herdsman
error 15-05-2023 23:09:40: Failed to start zigbee
error 15-05-2023 23:09:40: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 15-05-2023 23:09:40: Exiting...
error 15-05-2023 23:09:40: TypeError: Cannot read properties of null (reading 'key')
    at ZnpAdapterManager.determineStrategy (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:153:64)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:63:26)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)

**Comment by mzagula78** [comment]
Iam getting same problem on latest versions. Any idea what the solution was?
TypeError: Cannot read properties of null (reading 'key')

**Comment by mzagula78** [comment]
team, How to fix it?
[2025-02-07 00:04:25] info: 	z2m: Logging to console, file (filename: log.log)
[2025-02-07 00:04:25] info: 	z2m: Starting Zigbee2MQTT version 2.1.1 (commit #unknown)
[2025-02-07 00:04:25] info: 	z2m: Starting zigbee-herdsman (3.2.5)
[2025-02-07 00:04:25] info: 	zh:zstack:znp: Opening SerialPort with {"path":"/dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0","baudRate":115200,"rtscts":false,"autoOpen":false}
[2025-02-07 00:04:25] info: 	zh:zstack:znp: Serialport opened
[2025-02-07 00:04:25] error: 	z2m: Error while starting zigbee-herdsman
[2025-02-07 00:04:25] error: 	z2m: Failed to start zigbee-herdsman
[2025-02-07 00:04:25] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start_crashes-runtime.html for possible solutions
[2025-02-07 00:04:25] error: 	z2m: Exiting...
[2025-02-07 00:04:25] error: 	z2m: TypeError: Cannot read properties of null (reading 'key')
    at ZnpAdapterManager.determineStrategy (/app/node_modules/.pnpm/zigbee-herdsman@3.2.5/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:154:64)
    at ZnpAdapterManager.start (/app/node_modules/.pnpm/zigbee-herdsman@3.2.5/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:62:26)
    at ZStackAdapter.start (/app/node_modules/.pnpm/zigbee-herdsman@3.2.5/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:158:16)
    at Controller.start (/app/node_modules/.pnpm/zigbee-herdsman@3.2.5/node_modules/zigbee-herdsman/src/controller/controller.ts:136:29)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:142:13)
    at start (/app/index.js:161:5)
