### ISSUE TITLE
Acova Percale2 : timeout on get/set actions

### ISSUE THREAD

**Issue by PEGARifrouf** [Koenkk/zigbee2mqtt#17713]
### What happened?

On Acova Percale2, the device can be used normally during a few minutes to a couple hours after pairing it or reparing it but after a while it does not responds any more.
When setting a new temperature setpoint, a timeout error occurs leading to no change at all to the HVAC.

The device still reports his linkquality.

### What did you expect to happen?

Be able to send command to the hvac any time after the pairing.

### How to reproduce it (minimal and precise)

Pair the device.
Device has joined the nework
Wait for a few minutes to a few hours
All commands leads to timeout

### Zigbee2MQTT version

1.30.4

### Adapter firmware version

20221226

### Adapter

SMLIGHT SLZB-06 (CC2652P)

### Debug log

`Debug 2023-05-17 21:58:07Received MQTT message on 'zigbee2mqtt_bureau/Chauffage bureau/get' with data '{"occupied_heating_setpoint":""}'
Debug 2023-05-17 21:58:07Publishing get 'get' 'occupied_heating_setpoint' to 'Chauffage bureau'
Error 2023-05-17 21:58:16Publish 'set' 'occupied_heating_setpoint' to 'Chauffage bureau' failed: 'Error: Write 0x5c0272fffe638238/1 hvacThermostat({"occupiedHeatingSetpoint":1600}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
Debug 2023-05-17 21:58:16Error: Write 0x5c0272fffe638238/1 hvacThermostat({"occupiedHeatingSetpoint":1600}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205)) at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
Info 2023-05-17 21:58:16MQTT publish: topic 'zigbee2mqtt_bureau/bridge/log', payload '{"message":"Publish 'set' 'occupied_heating_setpoint' to 'Chauffage bureau' failed: 'Error: Write 0x5c0272fffe638238/1 hvacThermostat({\"occupiedHeatingSetpoint\":1600}, {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Data request failed with error: 'No network route' (205))'","meta":{"friendly_name":"Chauffage bureau"},"type":"zigbee_publish_error"}'
Error 2023-05-17 21:58:40Publish 'get' 'occupied_heating_setpoint' to 'Chauffage bureau' failed: 'Error: Read 0x5c0272fffe638238/1 hvacThermostat(["occupiedHeatingSetpoint"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
Debug 2023-05-17 21:58:40Error: Read 0x5c0272fffe638238/1 hvacThermostat(["occupiedHeatingSetpoint"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205)) at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
Info 2023-05-17 21:58:40MQTT publish: topic 'zigbee2mqtt_bureau/bridge/log', payload '{"message":"Publish 'get' 'occupied_heating_setpoint' to 'Chauffage bureau' failed: 'Error: Read 0x5c0272fffe638238/1 hvacThermostat([\"occupiedHeatingSetpoint\"], {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Data request failed with error: 'No network route' (205))'","meta":{"friendly_name":"Chauffage bureau"},"type":"zigbee_publish_error"}'`

**Comment by PEGARifrouf** [comment]
I have change the zigbee Channel After another device starts to timeout. Seems to work fine, ok for 30h.

**Comment by PEGARifrouf** [comment]
Issue solved by changing Channel from 11 to 25
