### ISSUE TITLE
error connecting Xiaomi switch 

### ISSUE THREAD

**Issue by serge707** [Koenkk/zigbee2mqtt#1772]
Hello @Koenkk.
One of my devices is not connecting to Homeassistant after update.
Aqara double key wired wall switch (QBKG03LM). 
Other devices, including Xiaomi are connected correctly.
Homeassistant problem or zigbee2mqtt, or another?
Log: 
```
2019-07-23 06:08:59 ERROR (MainThread) [homeassistant.components.mqtt.switch] Exception in async_discover when dispatching 'mqtt_discovery_new_switch_mqtt': ({'payload_off': 'OFF', 'payload_on': 'ON', 'value_template': '{{ value_json.state_left }}', 'command_topic': 'zigbee2mqtt/0x00158d00021608a7/left/set', 'command_topic_prefix': 'left', 'state_topic': 'zigbee2mqtt/0x00158d00021608a7', 'name': '0x00158d00021608a7_switch_left', 'unique_id': '0x00158d00021608a7_switch_left_zigbee2mqtt', 'device': {'identifiers': 'zigbee2mqtt_0x00158d00021608a7', 'name': '0x00158d00021608a7', 'sw_version': 'Zigbee2mqtt 1.1.1', 'model': 'Aqara double key wired wall switch (QBKG03LM)', 'manufacturer': 'Xiaomi'}, 'availability_topic': 'zigbee2mqtt/bridge/state', 'platform': 'mqtt'},)
 Traceback (most recent call last):
   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/mqtt/switch.py", line 59, in async_discover
     config = PLATFORM_SCHEMA(discovery_payload)
   File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 254, in __call__
     return self._compiled([], data)
   File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 551, in validate_dict
     return base_validate(path, iteritems(data), out)
   File "/srv/homeassistant/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 414, in validate_mapping
     raise er.MultipleInvalid(errors)
 voluptuous.error.MultipleInvalid: extra keys not allowed @ data['command_topic_prefix']
```
On zigbee2mqtt log:
```
Jul 23 06:20:40 hassbian npm[6848]:   zigbee2mqtt:info 7/23/2019, 6:20:40 AM MQTT publish: topic 'homeassistant/switch/0x00158d00021608a7/switch_right/config', payload '{"payload_off":"OFF","payload_on":"ON","value_template":"{{ value_json.state_right }}","command_topic":"zigbee2mqtt/0x00158d00021608a7/right/set","command_topic_prefix":"right","state_topic":"zigbee2mqtt/0x00158d00021608a7","name":"0x00158d00021608a7_switch_right","unique_id":"0x00158d00021608a7_switch_right_zigbee2mqtt","device":{"identifiers":"zigbee2mqtt_0x00158d00021608a7","name":"0x00158d00021608a7","sw_version":"Zigbee2mqtt 1.1.1","model":"Aqara double key wired wall switch (QBKG03LM)","manufacturer":"Xiaomi"},"availability_topic":"zigbee2mqtt/bridge/state"}'
```
And
```
Jul 23 06:31:40 hassbian npm[6848]:   zigbee2mqtt:debug 7/23/2019, 6:31:40 AM Successfully pinged 0x00158d00021608a7
```

**Comment by patrul** [comment]
Not the same but maybe related. These kind of Xiaomi switches are giving me errors:

```
  zigbee2mqtt:error 7/24/2019, 7:35:38 PM Zigbee publish to device 'Pulsador_salon_pared', genTime - readRsp - [{"attrId":0,"status":0,"attrData":617308532,"dataType":226}] - {"direction":1,"seqNum":0,"disDefaultRsp":1} - 1 failed with error Error: AF data request fails, status code: 205. No network route. Please confirm that the device has (re)joined the network.
  zigbee2mqtt:error 7/24/2019, 7:38:48 PM Zigbee publish to device 'Pulsador_salon_pared', genTime - readRsp - [{"attrId":0,"status":0,"attrData":617308723,"dataType":226}] - {"direction":1,"seqNum":4,"disDefaultRsp":1} - 1 failed with error Error: AF data request fails, status code: 205. No network route. Please confirm that the device has (re)joined the network.
  zigbee2mqtt:error 7/24/2019, 7:39:35 PM Zigbee publish to device 'Pulsador_despacho_pared', genTime - readRsp - [{"attrId":0,"status":0,"attrData":617308757,"dataType":226}] - {"direction":1,"seqNum":131,"disDefaultRsp":1} - 1 failed with error Error: AF data request fails, status code: 183. APS no ack.
```

Both are the same type of switch (QBKG03LM).
