### ISSUE TITLE
ZigBee2MQTT zigbee-herdsman Fails to start [Error: SRSP - SYS - getExtAddr after 6000ms]

### ISSUE THREAD

**Issue by OmegaLeWolf** [Koenkk/zigbee2mqtt#17732]
### What happened?

I am currently working on a small project to test various devices using the Mosquitto service as well as the ZigBee2MQTT. We initially installed the service and ZigBee2MQTT on a Debian installation with no issues but recently, after finishing a Home Assistant install and messing around with NodeRed we tried starting ZigBee2MQTT and it failed to start, displaying the following error. 

`Zigbee2MQTT:error 2023-05-19 12:48:39: Error: SRSP - SYS - getExtAddr after 6000ms`

We've gone through various websites and not found any solutions. Any help would be greatly appreciated.

Additional Troubleshooting Information
Attempting to solve the issue I attempted to run `dmesg | grep tty` to look at the USB ports and came up with this

`[    6.063929] usb 1-1.1: cp210x converter now attached to ttyUSB0
[ 6093.179744] cp210x ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[ 6093.180208] cp210x ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[ 6093.273931] cp210x ttyUSB0: failed set request 0x7 status: -19
[ 6093.273965] cp210x ttyUSB0: failed set request 0x12 status: -19
[ 6093.273982] cp210x ttyUSB0: failed set request 0x0 status: -19
[ 6093.274549] cp210x ttyUSB0: cp210x converter now disconnected from ttyUSB0
[ 6096.432694] usb 1-1.2: cp210x converter now attached to ttyUSB0
[ 6256.905483] cp210x ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[ 6256.905894] cp210x ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[ 6257.028788] cp210x ttyUSB0: failed set request 0x7 status: -19
[ 6257.028821] cp210x ttyUSB0: failed set request 0x12 status: -19
[ 6257.028838] cp210x ttyUSB0: failed set request 0x0 status: -19
[ 6257.029399] cp210x ttyUSB0: cp210x converter now disconnected from ttyUSB0
[ 6261.676378] usb 1-1.4: cp210x converter now attached to ttyUSB0
[ 6328.132905] cp210x ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[ 6328.133370] cp210x ttyUSB0: usb_serial_generic_read_bulk_callback - urb stopped: -32
[ 6328.307182] cp210x ttyUSB0: failed set request 0x7 status: -19
[ 6328.307216] cp210x ttyUSB0: failed set request 0x12 status: -19
[ 6328.307233] cp210x ttyUSB0: failed set request 0x0 status: -19
[ 6328.307792] cp210x ttyUSB0: cp210x converter now disconnected from ttyUSB0
[ 6363.758764] usb 1-1.1: cp210x converter now attached to ttyUSB0`

As well, `ls -l /dev/serial/by-id` displayed directory not found.

### What did you expect to happen?

For ZigBee2MQTT to start.

### How to reproduce it (minimal and precise)

Install ZigBee2MQTT
Install MQTT Service
Install Home Assistant (Core)
Install NodeRed

Attempt to start ZigBee2MQTT

### Zigbee2MQTT version

1.30.4

### Adapter firmware version

3.0

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus - SONOFF Zigbee 3.0 USB Dongle Plus

### Debug log

`info  2023-05-19 13:00:16: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2023-05-19.13-00-16' filename: log.txt
info  2023-05-19 13:00:16: Starting Zigbee2MQTT version 1.30.4 (commit #fb60dee)
info  2023-05-19 13:00:16: Starting zigbee-herdsman (0.14.111)
error 2023-05-19 13:00:37: Error while starting zigbee-herdsman
error 2023-05-19 13:00:37: Failed to start zigbee
error 2023-05-19 13:00:37: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2023-05-19 13:00:37: Exiting...
error 2023-05-19 13:00:37: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:58:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:101:27)
    at start (/opt/zigbee2mqtt/index.js:107:5)
`

**Edit**

The Error has now been replaced with 
`Zigbee2MQTT:error 2023-05-19 16:13:28: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)`
We now believe the issue is due to a lack of communication between the kernel and the USB Dongle, and not the Dongle on it's own. Despite this, we'd greatly appreciate some help or indications on how to resolve this. Thank you!

**Comment by OmegaLeWolf** [comment]
I figured it out! I've been working on it for the past 5 hours with another colleague and he determined that another process was possibly running and interrupting the communication. We checked and indeed, that was the issue!

**Error Solution**

Used to determine what process is using the tty port we needed. (In our case /dev/ttyUSB0)
`sudo lsof | grep tty` 

From the output of that command we ran:
`sudo kill {process id}`
to kill any process that was using the port.

We then ran the service as normal with no further issues.
