### ISSUE TITLE
Z2M won't start and several errors

### ISSUE THREAD

**Issue by schumi2004** [Koenkk/zigbee2mqtt#17817]
### What happened?

Since i'm having performance issues with my Conbee2 stick i bought a Sonoff ZBDongle-P, flashd it with coordinator software and plugged it my system. (I'm using Proxmox to run HA (2023.5.4))
The stick is mounted correctly and can be seen in HA.

Installed Z2M enabled debug after it failed starting on first attempt and noticd several errors on log.
Afterwards i followed all the troubleshooting steps without luck.
It has write access, stick is visable on system but still Z2M won't start.
Also removed other USB devices attached to the system and disabled integrations/addons that possibly could have affect on this.

### What did you expect to happen?

A working environment

### How to reproduce it (minimal and precise)

Started from scratch with Z2M, MQTT broker was already available.
Disabled all Deconz addons/integrations.

### Zigbee2MQTT version

1.30.4-1

### Adapter firmware version

20221226

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

### Debug log

[14:48:22] INFO: Preparing to start...
[14:48:23] INFO: Socat not enabled
[14:48:23] INFO: Zigbee Herdsman debug logging enabled
[14:48:23] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:debug 2023-05-28 14:48:25: Can't load state from file /config/zigbee2mqtt/state.json (doesn't exist)
Zigbee2MQTT:info  2023-05-28 14:48:25: Logging to console and directory: '/config/zigbee2mqtt/log/2023-05-28.14-48-25' filename: log.txt
Zigbee2MQTT:info  2023-05-28 14:48:25: Starting Zigbee2MQTT version 1.30.4 (commit #unknown)
Zigbee2MQTT:info  2023-05-28 14:48:25: Starting zigbee-herdsman (0.14.111)
Zigbee2MQTT:debug 2023-05-28 14:48:25: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyUSB0"}}'
2023-05-28T12:48:25.924Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2023-05-28T12:48:25.925Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/ttyUSB0"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2023-05-28T12:48:25.926Z zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with {"path":"/dev/ttyUSB0","baudRate":115200,"rtscts":false,"autoOpen":false}
2023-05-28T12:48:25.934Z zigbee-herdsman:adapter:zStack:znp:log Serialport opened

<lots of data>

2023-05-28T12:48:39.943Z zigbee-herdsman:adapter:zStack:unpi:parser --> error Error: Invalid checksum
    at Function.fromBuffer (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/unpi/frame.ts:48:19)
    at Parser.parseNext (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/unpi/parser.ts:43:41)
    at Parser._transform (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/unpi/parser.ts:19:14)
    at Parser.Transform._write (node:internal/streams/transform:205:23)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at Parser.Writable.write (node:internal/streams/writable:336:10)
    at SerialPort.ondata (node:internal/streams/readable:754:22)
    at SerialPort.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
2023-05-28T12:48:39.943Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
Zigbee2MQTT:error 2023-05-28 14:48:45: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-05-28 14:48:45: Failed to start zigbee
Zigbee2MQTT:error 2023-05-28 14:48:45: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-05-28 14:48:45: Exiting...
Zigbee2MQTT:error 2023-05-28 14:48:46: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)

**Comment by schumi2004** [comment]
Turns out there was a conflict with a other USB device, no idea what happend but issue is resolved now.
