### ISSUE TITLE
start failed with status '(0xb2: APS_TABLE_FULL)' 

### ISSUE THREAD

**Issue by silvioped** [Koenkk/zigbee2mqtt#17845]
### What happened?

After upgrade of latest hassos (10.2) the add-on doesn't start

### What did you expect to happen?

to start

### Zigbee2MQTT version

1.30.4-1

### Adapter firmware version

cannot retrieve now

### Adapter

ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Debug log

[10:44:46] INFO: Preparing to start...
[10:44:47] INFO: Socat not enabled
[10:44:49] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:debug 2023-05-31 10:44:57: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2023-05-31 10:44:57: Logging to console and directory: '/config/zigbee2mqtt/log/2023-05-31.10-44-57' filename: log.txt
Zigbee2MQTT:debug 2023-05-31 10:44:57: Removing old log directory '/config/zigbee2mqtt/log/2023-05-31.10-33-31'
Zigbee2MQTT:info  2023-05-31 10:44:57: Starting Zigbee2MQTT version 1.30.4 (commit #unknown)
Zigbee2MQTT:info  2023-05-31 10:44:57: Starting zigbee-herdsman (0.14.111)
Zigbee2MQTT:debug 2023-05-31 10:44:57: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[9,8,7,6,5,4,3,2],"networkKey":"HIDDEN","panID":6753},"serialPort":{"path":"/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_8e4d0e8c0xx2ec11b69e20cxx30c07-if00-port0"}}'
Zigbee2MQTT:error 2023-05-31 10:44:58: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-05-31 10:44:58: Failed to start zigbee
Zigbee2MQTT:error 2023-05-31 10:44:58: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-05-31 10:44:58: Exiting...
Zigbee2MQTT:error 2023-05-31 10:44:58: Error: SREQ '--> ZDO - extAddGroup - {"endpoint":242,"groupid":2948,"namelen":0,"groupname":[]}' failed with status '(0xb2: APS_TABLE_FULL)' (expected '(0x00: SUCCESS)')
    at Object.func (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:322:27)
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)

**Comment by silvioped** [comment]
Solved setting this in the z2m configuration.yaml:
mqtt:
     version: 5
