### ISSUE TITLE
dev build ddcab827 breaks Tuya plug TS011F _TZ3000_dpo1ysak

### ISSUE THREAD

**Issue by okastl** [Koenkk/zigbee2mqtt#17866]
### What happened?

Updated to
"HEAD is now at ddcab827 Update zigbee-herdsman-converters to 15.14.1 (#17859)"

Starting z2m causes this crash:

```
zigbee-herdsman:controller:endpoint Read 0x540f57fffe1671ad/1 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) +0ms
  zigbee-herdsman:adapter:zStack:adapter sendZclFrameToEndpointInternal 0x540f57fffe1671ad:48656/1 (0,0,1) +4s
  zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":48656,"destendpoint":1,"srcendpoint":1,"clusterid":0,"transid":2,"options":0,"radius":30,"len":5,"data":{"type":"Buffer","data":[16,3,0,0,0]}} +253ms
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,15,36,1,16,190,1,1,0,0,2,0,30,5,16,3,0,0,0,142] +252ms
Error: 'measurement_poll_interval' is not a number, got number (60)
    at assertNumber (D:\NB\z2m\zigbee2mqtt\node_modules\zigbee-herdsman-converters\src\lib\utils2.ts:6:42)
    at Object.onEventMeasurementPoll (D:\NB\z2m\zigbee2mqtt\node_modules\zigbee-herdsman-converters\src\lib\tuya.ts:84:21)
    at Object.onEvent (D:\NB\z2m\zigbee2mqtt\node_modules\zigbee-herdsman-converters\src\devices\tuya.ts:2747:18)
    at OnEvent.callOnEvent (D:\NB\z2m\zigbee2mqtt\lib\extension\onEvent.ts:47:37)
    at OnEvent.start (D:\NB\z2m\zigbee2mqtt\lib\extension\onEvent.ts:10:18)
    at Controller.callExtensions (D:\NB\z2m\zigbee2mqtt\lib\controller.ts:319:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Controller.start (D:\NB\z2m\zigbee2mqtt\lib\controller.ts:153:9)
    at start (D:\NB\z2m\zigbee2mqtt\index.js:107:5)
```

### What did you expect to happen?

It should work like before

### Zigbee2MQTT version

1.31.0-dev

### Adapter firmware version

20230507

### Adapter

Sonoff P

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
