### ISSUE TITLE
1.31.0-dev commit: 80aa2112 regression with Tuya TS011F _TZ3000_dpo1ysak

### ISSUE THREAD

**Issue by okastl** [Koenkk/zigbee2mqtt#17880]
### What happened?

Zigbee Modell TS011F Zigbee Hersteller _TZ3000_dpo1ysak
After updating to 1.31.0-dev commit: [80aa2112](https://github.com/Koenkk/zigbee2mqtt/commit/80aa2112)
Setting indicator_mode, power_outage_memory and child_lock will throw errors.

```
Received MQTT message on 'zigbee2mqtt/Tuya/set' with data '{"indicator_mode":"off"}'
Debug 2023-06-02 17:08:55Publishing 'set' 'indicator_mode' to 'Tuya'
Error 2023-06-02 17:08:55Publish 'set' 'indicator_mode' to 'Tuya' failed: 'Error: Expected one of: off, off/on, on/off, on, got: 'off''
Debug 2023-06-02 17:08:55Error: Expected one of: off, off/on, on/off, on, got: 'off' at getFromLookup (D:\NB\z2m\zigbee2mqtt\node_modules\zigbee-herdsman-converters\src\lib\utils2.ts:12:24) at Object.convertSet (D:\NB\z2m\zigbee2mqtt\node_modules\zigbee-herdsman-converters\src\lib\tuya.ts:719:52) at Publish.onMQTTMessage (D:\NB\z2m\zigbee2mqtt\lib\extension\publish.ts:247:52) at EventEmitter.emit (node:events:525:35) at EventBus.emitMQTTMessage (D:\NB\z2m\zigbee2mqtt\lib\eventBus.ts:109:22) at MQTT.onMessage (D:\NB\z2m\zigbee2mqtt\lib\mqtt.ts:140:27) at WebSocket.<anonymous> (D:\NB\z2m\zigbee2mqtt\lib\extension\frontend.ts:126:27) at WebSocket.emit (node:events:513:28) at Receiver.receiverOnMessage (D:\NB\z2m\zigbee2mqtt\node_modules\ws\lib\websocket.js:1184:20) at Receiver.emit (node:events:513:28)

 2023-06-02 17:11:43MQTT publish: topic 'zigbee2mqtt/Tuya', payload '{"child_lock":"LOCK","current":0,"energy":0,"indicator_mode":"off/on","last_seen":1685718703372,"linkquality":196,"power":0,"power_outage_memory":"on","state":"OFF","update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null,"voltage":231}'
Debug 2023-06-02 17:11:43Received Zigbee message from 'Tuya', type 'attributeReport', cluster 'genOnOff', data '{"tuyaBacklightMode":1}' from endpoint 1 with groupID 0
Error 2023-06-02 17:11:43Exception while calling fromZigbee converter: 'Expected string got: '1' (number)' is not a string, got number (1)}
Debug 2023-06-02 17:11:43Error: 'Expected string got: '1' (number)' is not a string, got number (1) at assertString (D:\NB\z2m\zigbee2mqtt\node_modules\zigbee-herdsman-converters\src\lib\utils2.ts:2:42) at getFromLookup (D:\NB\z2m\zigbee2mqtt\node_modules\zigbee-herdsman-converters\src\lib\utils2.ts:10:5) at Object.convert (D:\NB\z2m\zigbee2mqtt\node_modules\zigbee-herdsman-converters\src\lib\tuya.ts:923:54) at Receive.onDeviceMessage (D:\NB\z2m\zigbee2mqtt\lib\extension\receive.ts:150:51) at processTicksAndRejections (node:internal/process/task_queues:95:5)

2023-06-02 17:12:52Received MQTT message on 'zigbee2mqtt/Tuya/set' with data '{"child_lock":"UNLOCK","indicator_mode":"off/on","power_outage_memory":"on"}'
Debug 2023-06-02 17:12:52Publishing 'set' 'child_lock' to 'Tuya'
Error 2023-06-02 17:12:52Publish 'set' 'child_lock' to 'Tuya' failed: 'Error: Expected one of: lock, unlock, got: 'UNLOCK''
Debug 2023-06-02 17:12:52Error: Expected one of: lock, unlock, got: 'UNLOCK' at getFromLookup (D:\NB\z2m\zigbee2mqtt\node_modules\zigbee-herdsman-converters\src\lib\utils2.ts:12:24) at Object.convertSet (D:\NB\z2m\zigbee2mqtt\node_modules\zigbee-herdsman-converters\src\lib\tuya.ts:739:36) at Publish.onMQTTMessage (D:\NB\z2m\zigbee2mqtt\lib\extension\publish.ts:247:52) at EventEmitter.emit (node:events:525:35) at EventBus.emitMQTTMessage (D:\NB\z2m\zigbee2mqtt\lib\eventBus.ts:109:22) at MQTT.onMessage (D:\NB\z2m\zigbee2mqtt\lib\mqtt.ts:140:27) at WebSocket.<anonymous> (D:\NB\z2m\zigbee2mqtt\lib\extension\frontend.ts:126:27) at WebSocket.emit (node:events:513:28) at Receiver.receiverOnMessage (D:\NB\z2m\zigbee2mqtt\node_modules\ws\lib\websocket.js:1184:20) at Receiver.emit (node:events:513:28)
```

### What did you expect to happen?

No errors.

### Zigbee2MQTT version

1.31.0-dev commit: 80aa2112

### Adapter firmware version

20230507

### Adapter

Sonoff P

**Comment by Koenkk** [comment]
Fixed, thanks for reporting!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
