### ISSUE TITLE
Previously working installation fails to start

### ISSUE THREAD

**Issue by sticilface** [Koenkk/zigbee2mqtt#17988]
### What happened?

Upgraded to new dev branch.  Running in Home assistant 
```
[21:28:03] INFO: Preparing to start...
[21:28:03] INFO: Socat not enabled
[21:28:03] INFO: Zigbee Herdsman debug logging enabled
[21:28:04] INFO: Starting Zigbee2MQTT...
/app/node_modules/zigbee-herdsman-converters/index.js:79
        if (converter.options) {
                      ^
TypeError: Cannot read properties of undefined (reading 'options')
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:79:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)
```
This error is now all I get.  Even for default config, for both current and dev 

### What did you expect to happen?

It starts.... 

### How to reproduce it (minimal and precise)

Given that it no longer starts I don't know... 

### Zigbee2MQTT version

 1.31.2-1 

### Adapter firmware version

unable to start.... 

### Adapter

usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Debug log

This is the config file
```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt: {}
serial: {}
zigbee_herdsman_debug: true
```

**Comment by sticilface** [comment]
Duplicate
