### ISSUE TITLE
HEIMAN Smoke Alarm gives errors when pairing

### ISSUE THREAD

**Issue by KennethLavrsen** [Koenkk/zigbee2mqtt#18038]
### What happened?

I have 3 HEIMAN Smoke Alarms type HS1SA with firmware 2022.09.09

When I pair them they are added. And if I pair them next to the coordinator it seems to go OK.

But if they pair through a router the interview ends with this error popping up and also in the log

```
error 2023-06-16 15:29:26: Failed to configure 'Living Room Smoke Sensor', attempt 1 (Error: Read 0x8cf681fffe181ddc/1 genPowerCfg(["batteryPercentageRemaining"], {"sendWhen":"active","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 64727 - 1 - 82 - 1 - 1 after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7))
```

I just only started a new Zigbee2MQTT Network and I have 1 coordinator and 1 router. And around 18 sensors.

Both coordinator and sensor are same Sonoff USB devices if the CC2652P type

The coordinator is freshly programmed with latest 20230507 
The router is freshly programmed with latest 20221102 router firmware downloaded from the Koenkk github universe

The device seems to work even though I see the error so the report is only related to the logging and the error message

I have two window sensors that pair without problems through same router.

### What did you expect to happen?

Clean log and no difference between direct and via router pairing

### How to reproduce it (minimal and precise)

Pair the HEIMAN smoke sensor near a CC2652P based router and watch the log. I see it on multiple sensors and tried multiple times

I have good radio coverage between device and router and between router and coordinator. Coordinator mounted via extension wire in a good antenna location far from interference

### Zigbee2MQTT version

1.31.2

### Adapter firmware version

20230507

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus-P

### Debug log

```
error 2023-06-16 15:29:26: Failed to configure 'Living Room Smoke Sensor', attempt 1 (Error: Read 0x8cf681fffe181ddc/1 genPowerCfg(["batteryPercentageRemaining"], {"sendWhen":"active","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 64727 - 1 - 82 - 1 - 1 after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7))
```

**Comment by KennethLavrsen** [comment]
Ping

**Comment by KennethLavrsen** [comment]
Ping bot
