### ISSUE TITLE
[New device support]: _TZE200_44af8vyi

### ISSUE THREAD

**Issue by UnsuspiciousUsername** [Koenkk/zigbee2mqtt#18057]
### Link

https://www.zigbee2mqtt.io/devices/TS0601_temperature_humidity_sensor_2.html

### Database entry

{"id":19,"type":"EndDevice","ieeeAddr":"0x9035eafffe2d6b67","nwkAddr":54597,"manufId":4098,"manufName":"_TZE200_44af8vyi","powerSource":"Battery","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65534":0,"modelId":"TS0601","manufacturerName":"_TZE200_44af8vyi","stackVersion":0,"dateCode":"","zclVersion":3,"appVersion":70,"powerSource":3}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1440156621},"lastSeen":1687097934674,"defaultSendRequestWhen":"immediate"}

### Comments

https://www.zigbee2mqtt.io/devices/TS0601_temperature_humidity_sensor_2.html

Zigbee Model
    TS0601
Zigbee Manufacturer
    _TZE200_44af8vyi

I added _TZE200_44af8vyi to tuya.js:

```
   {
        fingerprint: tuya.fingerprint('TS0601', ['_TZE200_yjjdcqsq', '_TZE200_9yapgbuv','_TZE200_44af8vyi']),
        model: 'TS0601_temperature_humidity_sensor_2',
        vendor: 'TuYa',
        description: 'Temperature and humidity sensor',
        fromZigbee: [tuya.fz.datapoints, tuya.fz.gateway_connection_status],
        toZigbee: [tuya.tz.datapoints],
        configure: tuya.configureMagicPacket,
        exposes: [e.temperature(), e.humidity(), tuya.exposes.batteryState(), e.battery_low()],
        meta: {
            tuyaDatapoints: [
                [1, 'temperature', tuya.valueConverter.divideBy10],
                [2, 'humidity', tuya.valueConverter.raw],
                [3, 'battery_state', tuya.valueConverter.batteryState],
                // [9, 'temperature_unit', tuya.valueConverter.raw], This DP is not properly supported by the device
            ],
        },
        whiteLabel: [
            tuya.whitelabel('TuYa', 'ZTH01', 'Temperature and humidity sensor', ['_TZE200_yjjdcqsq']),
            tuya.whitelabel('TuYa', 'ZTH02', 'Temperature and humidity sensor', ['_TZE200_9yapgbuv']),
        ],
    }
```

The device works exactly as it should, it looks exactly the same as the picture of "TuYa TS0601_temperature_humidity_sensor_2" on the z2m website.

**Comment by UnsuspiciousUsername** [comment]
I only have one problem, the battery information goes null, i've tried to add PowerCfg under the reportinig section of the device but it just seems to error out. 

Here is my log:
`info 2023-06-20 03:15:13MQTT publish: topic 'zigbee2mqtt/0x9035eafffe2d6b67', payload '{"battery":90,"battery_level":"high","battery_low":false,"humidity":60,"last_seen":"2023-06-20T03:15:14+02:00","linkquality":255,"temperature":24.2}'
error 2023-06-20 03:15:13Request 'zigbee2mqtt/bridge/request/device/configure_reporting' failed with error: 'ConfigureReporting 0x9035eafffe2d6b67/1 genPowerCfg([{"attribute":"batteryPercentageRemaining","minimumReportInterval":60,"maximumReportInterval":3600,"reportableChange":1}], 

{"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUP_GENERAL_COMMAND')'
debug 2023-06-20 03:15:13Error: ConfigureReporting 0x9035eafffe2d6b67/1 genPowerCfg([{"attribute":"batteryPercentageRemaining","minimumReportInterval":60,"maximumReportInterval":3600,"reportableChange":1}], 

{"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUP_GENERAL_COMMAND') at Endpoint.checkStatus (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:419:28) at Endpoint.configureReporting (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:760:22) at Bridge.deviceConfigureReporting (/opt/zigbee2mqtt/lib/extension/bridge.ts:425:9) at Bridge.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/bridge.ts:122:34)
info 2023-06-20 03:15:13MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure_reporting', payload '{"data":{},"error":"ConfigureReporting 0x9035eafffe2d6b67/1 genPowerCfg([{\"attribute\":\"batteryPercentageRemaining\",\"minimumReportInterval\":60,\"maximumReportInterval\":3600,\"reportableChange\":1}], {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Status 'UNSUP_GENERAL_COMMAND')","status":"error","transaction":"ls9q0-6"}'`
