### ISSUE TITLE
Z2M fails to start correctly after upgrade to 1.32.0

### ISSUE THREAD

**Issue by jimmyeao** [Koenkk/zigbee2mqtt#18197]
### What happened?

upgraded to 1.32.0, Z2M goes into a loop where it fails, log folder is created each time with no contents

```
pi@zigbeepi:~ $ systemctl status zigbee2mqtt
● zigbee2mqtt.service - zigbee2mqtt
   Loaded: loaded (/etc/systemd/system/zigbee2mqtt.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2023-07-03 14:44:29 BST; 223ms ago
  Process: 8997 ExecStart=/usr/bin/npm start (code=exited, status=1/FAILURE)
 Main PID: 8997 (code=exited, status=1/FAILURE)
```

### What did you expect to happen?

Service would start

### How to reproduce it (minimal and precise)

upgrade to Z2M 1.32.0

### Zigbee2MQTT version

1.32.0

### Adapter firmware version

20221226

### Adapter

Electrolama CC2652

### Debug log

No debug logs are generated, just empty directories

**Comment by jimmyeao** [comment]
to add when running manually:
pi@zigbeepi:/opt/zigbee2mqtt $ npm start
```
> zigbee2mqtt@1.32.0 start
> node index.js



/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/index.js:79
        if (converter.options) {
                      ^
TypeError: Cannot read properties of undefined (reading 'options')
    at Object.addDefinition [as addDeviceDefinition] (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/index.js:79:23)
    at new ExternalConverters (/opt/zigbee2mqtt/lib/extension/externalConverters.ts:15:17)
    at new Controller (/opt/zigbee2mqtt/lib/controller.ts:84:58)
    at start (/opt/zigbee2mqtt/index.js:106:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by jimmyeao** [comment]
traced to an issue with external convertor, closing..
