### ISSUE TITLE
The 1.4 worked fine and the upgrade to 1.5.1 broke probably something more than the configuration itself

### ISSUE THREAD

**Issue by Nihvel** [Koenkk/zigbee2mqtt#1823]
```
./run.sh: line 16: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
2019-08-06T19:03:48: PM2 log: Launching in no daemon mode
2019-08-06T19:03:48: PM2 log: App [npm:0] starting in -fork mode-
2019-08-06T19:03:48: PM2 log: App [npm:0] online
> zigbee2mqtt@1.5.1 start /zigbee2mqtt-1.5.1
> node index.js
  zigbee2mqtt:info 8/6/2019, 7:03:49 PM Logging to directory: '/share/zigbee2mqtt/log/2019-08-06.19-03-49'
  zigbee2mqtt:info 8/6/2019, 7:03:49 PM Starting zigbee2mqtt version 1.5.1 (commit #unknown)
  zigbee2mqtt:info 8/6/2019, 7:03:49 PM Starting zigbee-shepherd
  zigbee2mqtt:info 8/6/2019, 7:03:58 PM Error while starting zigbee-shepherd, attempting to fix... (takes 60 seconds) (Error: request timeout)
  zigbee2mqtt:info 8/6/2019, 7:04:58 PM Starting zigbee-shepherd
  zigbee2mqtt:error 8/6/2019, 7:05:05 PM Error while starting zigbee-shepherd! (Error: request timeout)
  zigbee2mqtt:error 8/6/2019, 7:05:05 PM Press the reset button on the stick (the one closest to the USB) and start again
  zigbee2mqtt:error 8/6/2019, 7:05:05 PM Failed to start
	{"message":"request timeout","stack":"Error: request timeout\n    at CcZnp.<anonymous> (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/cc-znp/index.js:208:22)\n    at Object.onceWrapper (events.js:286:20)\n    at CcZnp.emit (events.js:198:13)\n    at Timeout.<anonymous> (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/cc-znp/index.js:192:18)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)"}
  zigbee2mqtt:error 8/6/2019, 7:05:05 PM Exiting...
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.5.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR!
 Failed at the zigbee2mqtt@1.5.1 start script.
npm
 ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-06T17_05_05_733Z-debug.log
2019-08-06T19:05:08: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-08-06T19:05:08: PM2 log: App [npm:0] starting in -fork mode-
2019-08-06T19:05:08: PM2 log: App [npm:0] online
> zigbee2mqtt@1.5.1 start /zigbee2mqtt-1.5.1
> node index.js
  zigbee2mqtt:info 8/6/2019, 7:05:09 PM Logging to directory: '/share/zigbee2mqtt/log/2019-08-06.19-05-09'
  zigbee2mqtt:info 8/6/2019, 7:05:09 PM Starting zigbee2mqtt version 1.5.1 (commit #unknown)
  zigbee2mqtt:info 8/6/2019, 7:05:09 PM Starting zigbee-shepherd
  zigbee2mqtt:info 8/6/2019, 7:05:16 PM Error while starting zigbee-shepherd, attempting to fix... (takes 60 seconds) (Error: request timeout)
```

It does not start, that's it. Everything is at its latest version, both the software and the usb sniffer.

The updated **configuration.yaml** below
```
{
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://homeassistant:1883",
    "user": "mqtt_user",
    "password": "mqtt_password"
  },
  "serial": {
    "port": "/dev/ttyACM0"
  },
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [
      1,
      3,
      5,
      7,
      9,
      11,
      13,
      15,
      0,
      2,
      4,
      6,
      8,
      10,
      12,
      13
    ],
    "availability_blacklist": []
  },
  "ban": [],
  "whitelist": [],
  "queue": {}
}
```

A) No, I did not push the reset button on the stick
B) Yes, I did read the documentation: https://www.zigbee2mqtt.io/configuration/configuration.html
C) _devices.yaml_ is populated with the devices that were in the previous _configuration.yaml_ file, now the .yaml.bk.

**Comment by Nihvel** [comment]
... unplug the usb sniffer and plug it back plus removing the "null" inside groups.yaml made it work again
