### ISSUE TITLE
[New device support]: _TZE204_ptaqh9tk

### ISSUE THREAD

**Issue by Balyanibl** [Koenkk/zigbee2mqtt#18268]
### Link

https://aliexpress.ru/item/1005004836095177.html?spm=a2g2w.orderdetail.0.0.30ff4aa60AzYdf&sku_id=12000030675485386

### Database entry

{"id":22,"type":"Router","ieeeAddr":"0xdc8e95fffe363ed4","nwkAddr":36930,"manufId":4098,"manufName":"_TZE204_ptaqh9tk","powerSource":"Mains (single phase)","modelId":"TS0601","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,4,5,61184],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"65503":"пїЅпїЅ=,fпїЅпїЅ=,\u0012пїЅпїЅ=,\u0012","65506":31,"65508":0,"modelId":"TS0601","manufacturerName":"_TZE204_ptaqh9tk","stackVersion":0,"dateCode":"","appVersion":70}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1688921495452,"defaultSendRequestWhen":"immediate"}

### Comments

Прошу помощи в интеграции в z2m

**Comment by Balyanibl** [comment]
I found a Js template that doesn't look like a switch, but it doesn't work


const legacy = require('zigbee-herdsman-converters/lib/legacy');
const fz = {...require('zigbee-herdsman-converters/converters/fromZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').fromZigbee};
const tz = {...require('zigbee-herdsman-converters/converters/toZigbee'), legacy: require('zigbee-herdsman-converters/lib/legacy').toZigbee};

//const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
//const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const utils = require('zigbee-herdsman-converters/lib/utils');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const tuya = require('zigbee-herdsman-converters/lib/tuya');
const e = exposes.presets;
const ea = exposes.access;


const definition = {fingerprint: [
    {modelID: 'TS0601', manufacturerName: '_TZE204_ptaqh9tk'},

],
model: 'TS0601_switch_1_gang',
vendor: 'TuYa',
description: '1 gang switch',
exposes: [e.switch().withEndpoint('l1').setAccess('state', ea.STATE_SET)],
fromZigbee: [fz.ignore_basic_report, legacy.fromZigbee.tuya_switch],
toZigbee: [legacy.toZigbee.tuya_switch_state],
meta: {multiEndpoint: true},
configure: async (device, coordinatorEndpoint, logger) => {
    await tuya.configureMagicPacket(device, coordinatorEndpoint, logger);
    await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
    if (device.getEndpoint(2)) await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
},
endpoint: (device) => {
    // Endpoint selection is made in tuya_switch_state
    return {'l1': 1};
},
};

// data types: https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/lib/tuya.js

// Status report:
// Received Zigbee message from 'Moes 3 Gang Dimmer', type 'attributeReport', cluster 'genBasic', data '{"65506":32,"65508":0,"appVersion":64}' from endpoint 1 with groupID 0

// Button 1
// ON:
// type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":1,"dp":1}],"seq":44288}' from endpoint 1 with groupID 0
// Received Tuya DataPoint #1 from 0xdc8e95fffe363ed4 with raw data '{"dp":1,"datatype":1,"data":{"type":"Buffer","data":[1]}}': type='commandDataResponse', datatype='bool', value='true', known DP# usage: ["state","moesSsystemMode","tuyaSabCOalarm","moes105DimmerState1","trsPresenceState","trsfPresenceState","haozeeSystemMode","nousTemperature","wlsWaterLeak","AM02Control","garageDoorTrigger","connecteState","tshpsPresenceState","lmsState","alectoSmokeState"]
// OFF
// type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0],"type":"Buffer"},"datatype":1,"dp":1}],"seq":44544}' from endpoint 1 with groupID 0

// Dimming
// Received Tuya DataPoint #2 from 0xdc8e95fffe363ed4 with raw data '{"dp":2,"datatype":2,"data":{"type":"Buffer","data":[0,0,2,238]}}': type='commandDataResponse', datatype='value', value='750', known DP# usage: ["heatingSetpoint","coverPosition","eardaDimmerLevel","moesHold","moesSheatingSetpoint","silvercrestChangeMode","tuyaSabCO2","tuyaSahkMP25","tuyaSabCO","moes105DimmerLevel1","trsSensitivity","trsfSensitivity","tvMode","haozeeHeatingSetpoint","nousHumidity","tIlluminanceLux","evanellMode","AM02PercentControl","connecteMode","tshpscSensitivity","alectoSmokeValue"]
// Button 2
// ON:
// type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":1,"dp":7}],"seq":43776}' from endpoint 1 with groupID 0
// OFF:
// type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0],"type":"Buffer"},"datatype":1,"dp":7}],"seq":45056}' from endpoint 1 with groupID 0
// Button 3:
// ON:
// type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[1],"type":"Buffer"},"datatype":1,"dp":15}],"seq":45312}' from endpoint 1 with groupID 0
// OFF:
// type 'commandDataResponse', cluster 'manuSpecificTuya', data '{"dpValues":[{"data":{"data":[0],"type":"Buffer"},"datatype":1,"dp":15}],"seq":45568}' from endpoint 1 with groupID 0

// Button 2:
// Received unexpected Tuya DataPoint #7 from 0xdc8e95fffe363ed4 with raw data '{"dp":7,"datatype":1,"data":{"type":"Buffer","data":[0]}}': type='commandDataResponse', datatype='bool', value='false', known DP# usage: ["childLock","coverChange","moesSreset","moesCoverBacklight","neoAODuration","moes105DimmerState2","haozeeWindowState","thitIlluminanceLux","AM02WorkState"]
// Button 3:
// Received unexpected Tuya DataPoint #15 from 0xdc8e95fffe363ed4 with raw data '{"dp":15,"datatype":1,"data":{"type":"Buffer","data":[1]}}': type='commandDataResponse', datatype='bool', value='true', known DP# usage: ["neoAOBattPerc","haozeeMinTemp","nousHumiAlarm","moesSwitchIndicateLight","alectoBatteryPercentage"]

module.exports = definition;


With this template I get:
> node index.js

/mnt/data/root/zigbee2mqtt/data/extension/externally-loaded.js:25
toZigbee: [legacy.toZigbee.tuya_switch_state],
                           ^

TypeError: Cannot read properties of undefined (reading 'tuya_switch_state')
    at /mnt/data/root/zigbee2mqtt/data/extension/externally-loaded.js:25:28
    at Script.runInContext (node:vm:141:12)
    at Script.runInNewContext (node:vm:146:17)
    at Object.runInNewContext (node:vm:306:38)
    at loadModuleFromText (/mnt/data/root/zigbee2mqtt/lib/util/utils.ts:150:8)
    at loadModuleFromFile (/mnt/data/root/zigbee2mqtt/lib/util/utils.ts:157:12)
    at Object.getExternalConvertersDefinitions (/mnt/data/root/zigbee2mqtt/lib/util/utils.ts:167:25)
    at getExternalConvertersDefinitions.next (<anonymous>)
    at new ExternalConverters (/mnt/data/root/zigbee2mqtt/lib/extension/externalConverters.ts:12:20)
    at new Controller (/mnt/data/root/zigbee2mqtt/lib/controller.ts:84:58)
