### ISSUE TITLE
timeout":10000 - failed with status '(0xc7: NWK_TABLE_FULL)'

### ISSUE THREAD

**Issue by PetrMa** [Koenkk/zigbee2mqtt#18351]
### What happened?

Home Assistant 2023.7.2
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

Number of Zigbee devices: 30

Zigbee channel: 15
WiFi channel: 6 (no other WiFi and Zigbee networks near by my environment)
Affected devices: it seems that this issue is specific only for these devices https://www.zigbee2mqtt.io/devices/TS0002_switch_module.html#tuya-ts0002_switch_module and https://www.zigbee2mqtt.io/devices/ZBMINI-L.html#sonoff-zbmini-l
I have these 4 devices in my Zigbee network and all has the same issue Other devices working fine.

PS: last weekend I changed the coordinator from CC2531 to Sonoff ZBDongle-P. I think on CC2531 I did´t see these error messages and everything worked fine.

On some devices there are these errors when some commands sent

Zigbee2MQTT:error 18: Publish 'set' 'state' to 'Roleta obývák' failed: 'Error: Command 0xa4c1389a5dd6c8b7/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":49962,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))'
Zigbee2MQTT:debug 18: Error: Command 0xa4c1389a5dd6c8b7/1 genOnOff.on({}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> ZDO - extRouteDisc - {"dstAddr":49962,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)'))
    at Object.func (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:322:27)
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)

### What did you expect to happen?

don´t get 10000ms timeout on device

### How to reproduce it (minimal and precise)

try to send some settings to device

### Zigbee2MQTT version

1.32.1

### Adapter firmware version

20230507

### Adapter

Sonoff ZBDongle-P

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/12076879/log.txt)

**Comment by PetrMa** [comment]
Hello,

for now it seems that the problem was solved propably by-self in time.
Maybe the new Zigbee network need some time to be more stable.
I didn´t change anything but now I have about 5 errors in the log during the day and all devices worked fine and are connected to Zigbee.
