### ISSUE TITLE
ZclFrame length is lower than minimal length

### ISSUE THREAD

**Issue by milakov** [Koenkk/zigbee2mqtt#1843]
Hi, running the latest dev branch, got this error in the log:

```
PROBLEM DETECTED
Please create an issue here with the contents of below: https://github.com/koenkk/zigbee2mqtt/issues
===== Stack =====
Error: ZclFrame length is lower than minimal length
    at Function.fromBuffer (/app/node_modules/zigbee-herdsman/dist/zcl/zclFrame.js:133:19)
    at Object.header (/app/node_modules/zigbee-herdsman/dist/lib/components/zcl.js:81:42)
    at dispatchIncomingMsg (/app/node_modules/zigbee-herdsman/dist/lib/components/af.js:528:29)
    at Controller.incomingMsgHandler (/app/node_modules/zigbee-herdsman/dist/lib/components/af.js:625:12)
    at Controller.emit (events.js:198:13)
    at Object.bridge._areqEventBridge (/app/node_modules/zigbee-herdsman/dist/lib/components/event_bridge.js:11:16)
    at Znp.<anonymous> (/app/node_modules/zigbee-herdsman/dist/lib/components/controller.js:104:20)
    at Znp.emit (events.js:198:13)
    at Znp.onUnpiParsed (/app/node_modules/zigbee-herdsman/dist/znp/znp.js:67:18)
    at Parser.emit (events.js:198:13)
===== Buffer =====
{ type: 'Buffer', data: [] }
===== zcl-packet header =====
undefined
===== zcl header =====
undefined
===============

```

**Comment by Koenkk** [comment]
Thanks, fixed in the latest dev branch!
