### ISSUE TITLE
Publish to Xiaomi Aqara B1 curtain motor failed

### ISSUE THREAD

**Issue by PePe2KC** [Koenkk/zigbee2mqtt#18477]
### What happened?

Publish 'set' 'state' to curtain failed

Device:
Zigbee model: lumi.curtain.hagl04
Firmware: 2019www.
Manufacturer: Xiaomi
Model: [ZNCLDJ12LM](https://www.zigbee2mqtt.io/devices/ZNCLDJ12LM.html#xiaomi-zncldj12lm)

Discovery and adding device works fine. Device seems to be supported. 
I also tried:
1. To remove and add the device - does not fix the problem.
2. To restart Zigbee2Mqtt container - does not fix the problem.

### What did you expect to happen?

Publish 'set' 'state' to curtain without error

### Zigbee2MQTT version

1.32.1-dev commit: 3408e3c

### Adapter firmware version

0x26720700

### Adapter

ConBee2/RaspBee2

### Debug log

Error 2023-07-31 22:24:15Publish 'set' 'state' to '0x04cf8cdf3c812249' failed: 'Error: Write 0x04cf8cdf3c812249/1 genAnalogOutput({"85":{"value":100,"type":57}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (5))'

Debug 2023-07-31 22:24:15Error: Write 0x04cf8cdf3c812249/1 genAnalogOutput({"85":{"value":100,"type":57}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (5)) at DeconzAdapter.sendZclFrameToEndpoint (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:656:23) at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:81:20) at Endpoint.write (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:486:28) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.js:2646:21) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:248:36)

**Comment by PePe2KC** [comment]
Hi, still an issue on 1.35 release.
Can someone help?
