### ISSUE TITLE
Error: {"sequence":-1} after 10000ms

### ISSUE THREAD

**Issue by HulioEglesias** [Koenkk/zigbee2mqtt#18568]
### What happened?

I'm trying to start addon zigbee2mqtt at the Home assistant, but I got an error
It started in docker
Stick which I use: CC2530 USB | TTL UART CH340G
To MQTT broker I can connect from my pc and can see the messages.
when I start addon, i got an error `Error: Error: {"sequence":-1} after 10000ms`, What does it mean? How to fix it?

This is log:

### Zigbee2MQTT version

1.32.2-1

### Adapter firmware version

can't start

### Adapter

(https://aliexpress.ru/item/4000834500002.html) CC2530 USB to TTL UART CH340G Test Board Kit ZigBee Module 2.4GHz E18-TBL-01 for E18-MS1-PCB

### Debug log

```
[00:44:24] INFO: Preparing to start...
[00:44:25] INFO: Socat not enabled
[00:44:25] INFO: Zigbee Herdsman debug logging enabled
[00:44:25] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:debug 2023-08-10 00:44:27: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2023-08-10 00:44:27: Logging to console and directory: '/config/zigbee2mqtt/log/2023-08-10.00-44-27' filename: log.txt
Zigbee2MQTT:debug 2023-08-10 00:44:27: Removing old log directory '/config/zigbee2mqtt/log/2023-08-10.00-10-58'
Zigbee2MQTT:info  2023-08-10 00:44:27: Starting Zigbee2MQTT version 1.32.2 (commit #unknown)
Zigbee2MQTT:info  2023-08-10 00:44:27: Starting zigbee-herdsman (0.17.2)
Zigbee2MQTT:debug 2023-08-10 00:44:27: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"ezsp","path":"/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0"}}'
2023-08-09T21:44:27.198Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2023-08-09T21:44:27.199Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0","adapter":"ezsp"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2023-08-09T21:44:27.200Z zigbee-herdsman:adapter:ezsp:uart Opening SerialPort with {"path":"/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0","baudRate":115200,"rtscts":false,"autoOpen":false}
2023-08-09T21:44:27.206Z zigbee-herdsman:adapter:ezsp:uart Serialport opened
2023-08-09T21:44:27.206Z zigbee-herdsman:adapter:ezsp:uart Uart reseting
2023-08-09T21:44:27.207Z zigbee-herdsman:adapter:ezsp:uart --> Write reset
2023-08-09T21:44:27.208Z zigbee-herdsman:adapter:ezsp:uart --> [1ac038bc7e]
2023-08-09T21:44:27.209Z zigbee-herdsman:adapter:ezsp:uart -?- waiting reset
2023-08-09T21:44:27.261Z zigbee-herdsman:adapter:ezsp:uart <-- [5503fffe01]
2023-08-09T21:44:37.212Z zigbee-herdsman:adapter:ezsp:uart --> Error: Error: {"sequence":-1} after 10000ms
2023-08-09T21:44:37.214Z zigbee-herdsman:adapter:ezsp:driv Reset connection. Try 0
2023-08-09T21:44:37.214Z zigbee-herdsman:adapter:ezsp:driv Stop driver
2023-08-09T21:44:37.215Z zigbee-herdsman:adapter:ezsp:ezsp Stop ezsp
2023-08-09T21:44:37.216Z zigbee-herdsman:adapter:ezsp:ezsp Close ezsp
2023-08-09T21:44:37.216Z zigbee-herdsman:adapter:ezsp:driv Close driver
Error: Reset error: Error: {"sequence":-1} after 10000ms
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:299:23
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
```

**Comment by Koenkk** [comment]
In your config you set `adapter: ezsp`, this should be `adapter: zstack`
