### ISSUE TITLE
Path of adapter changed for a moment, doesn't work anymore but values in the error message match

### ISSUE THREAD

**Issue by percidae** [Koenkk/zigbee2mqtt#18580]
### What happened?

For a short moment the adapter path changed from /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_9e8d938ab639ec119688e6680aac08d5-if00-port0 to something like /dev/serial/by-id/pci... so I changed it to this path and it worked. Then I probably fixed the Debian issue (don'r remember what it was). When it was first changed it worked, but when I changed the path back to the original path it doesn't work anymore, but the log message seems to confirm that every setting is right.

Installation:
Supervised Homeassistant with zigbee2mqtt on previously Debian 11 (where it happened), now it is Debian 12.

### What did you expect to happen?

Working zigbee2mqtt.

### How to reproduce it (minimal and precise)

Unfortunately no idea.

### Zigbee2MQTT version

1.32.2 

### Adapter firmware version

?

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

### Debug log

[22:38:44] INFO: Preparing to start...
[22:38:44] INFO: Socat not enabled
[22:38:45] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-08-10 22:38:46: Logging to console and directory: '/config/zigbee2mqtt/log/2023-08-10.22-38-46' filename: log.txt
Zigbee2MQTT:info  2023-08-10 22:38:46: Starting Zigbee2MQTT version 1.32.2 (commit #unknown)
Zigbee2MQTT:info  2023-08-10 22:38:46: Starting zigbee-herdsman (0.17.2)
Zigbee2MQTT:error 2023-08-10 22:38:47: Configuration is not consistent with adapter state/backup!
Zigbee2MQTT:error 2023-08-10 22:38:47: - PAN ID: configured=6754, adapter=6754
Zigbee2MQTT:error 2023-08-10 22:38:47: - Extended PAN ID: configured=00124b0024c04c8e, adapter=00124b0024c04c8e
Zigbee2MQTT:error 2023-08-10 22:38:47: - Network Key: configured=01030507090b0d0f00020406080a0c0d, adapter=01030507090b0d0f00020406080a0c0d
Zigbee2MQTT:error 2023-08-10 22:38:47: - Channel List: configured=20, adapter=20
Zigbee2MQTT:error 2023-08-10 22:38:47: Please update configuration to prevent further issues.
Zigbee2MQTT:error 2023-08-10 22:38:47: If you wish to re-commission your network, please remove coordinator backup at /config/zigbee2mqtt/coordinator_backup.json.
Zigbee2MQTT:error 2023-08-10 22:38:47: Re-commissioning your network will require re-pairing of all devices!
Zigbee2MQTT:error 2023-08-10 22:38:47: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-08-10 22:38:47: Failed to start zigbee
Zigbee2MQTT:error 2023-08-10 22:38:47: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-08-10 22:38:47: Exiting...
Zigbee2MQTT:error 2023-08-10 22:38:47: Error: startup failed - configuration-adapter mismatch - see logs above for more information
    at ZnpAdapterManager.determineStrategy (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:229:35)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:63:26)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:59:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)

**Comment by percidae** [comment]
I do not know what the problem is but it looks like I got it resolved: I have a second "SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P". I flashed it with the newest firmware and got the IEEE from the current Zigbee Dongle and wrote it into the new one too. Now the network seems to come up again (quite slow).

I have no idea what it is or was, maybe firmware "broken"?

**Comment by percidae** [comment]
I do not know what the problem is but it looks like I got it resolved: I have a second "SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P". I flashed it with the newest firmware and got the IEEE from the current Zigbee Dongle and wrote it into the new one too. Now the network seems to come up again (quite slow).

I have no idea what it is or was, maybe firmware "broken"?
