### ISSUE TITLE
Crash on Touchlink scan

### ISSUE THREAD

**Issue by Roy-974** [Koenkk/zigbee2mqtt#18601]
### What happened?

I am trying to do a factory reset on some Philips Living colors gen 3 (with the wheel remote control). I have 4 living colors and 1 living colors bloom. I succeded to perform a factory reset on 3 of the living colors. Unfortunately, when i start the Touchlink on the last one and the bloom, Z2M is crashing.

I tried on both the release version and the dev version.
I'm using Skyconnect. It's configured correctly, as I could see the other lamps and do factory reset + firmware upgrade on these.

### What did you expect to happen?

I could see the lamp and perform a factory reset.

### How to reproduce it (minimal and precise)

Start Touchlink with a living colors lamp turned on in the proximity on the module.

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

EZSP v9

### Adapter

Skyconnect

### Debug log

`
2023-08-13T07:24:49.529Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (6,1,0): 61c2a1a9512a64fa7e 2023-08-13T07:24:49.529Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (7) 2023-08-13T07:24:49.530Z zigbee-herdsman:adapter:ezsp:uart --> [87009f7e] 2023-08-13T07:24:49.531Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 8080010500 2023-08-13T07:24:49.531Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x5: {"_cls_":"nop","_id_":5,"_isRequest_":false} 2023-08-13T07:24:49.532Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (1) success 2023-08-13T07:24:59.523Z zigbee-herdsman:adapter:ezsp:ezsp Time to watchdog ... 0 2023-08-13T07:24:59.524Z zigbee-herdsman:adapter:ezsp:ezsp ==> nop: null 
2023-08-13T07:24:59.525Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"nop","_id_":5,"_isRequest_":true} 2023-08-13T07:24:59.526Z zigbee-herdsman:adapter:ezsp:uart --> DATA (1,7,0): 8100010500 2023-08-13T07:24:59.527Z zigbee-herdsman:adapter:ezsp:uart --> [17c321a9512adbee7e] 2023-08-13T07:24:59.528Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (2) 2023-08-13T07:24:59.535Z zigbee-herdsman:adapter:ezsp:uart <-- [72c3a1a9512a7d3acf7e] 
2023-08-13T07:24:59.536Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (7,2,0): 72c3a1a9512a1acf7e 2023-08-13T07:24:59.536Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (0) 2023-08-13T07:24:59.537Z zigbee-herdsman:adapter:ezsp:uart --> [8070787e] 2023-08-13T07:24:59.538Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 8180010500 2023-08-13T07:24:59.539Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x5: {"_cls_":"nop","_id_":5,"_isRequest_":false} 2023-08-13T07:24:59.540Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (2) success 2023-08-13T07:25:09.528Z zigbee-herdsman:adapter:ezsp:ezsp Time to watchdog ... 0 2023-08-13T07:25:09.528Z zigbee-herdsman:adapter:ezsp:ezsp ==> nop: null 
2023-08-13T07:25:09.529Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"nop","_id_":5,"_isRequest_":true} 2023-08-13T07:25:09.530Z zigbee-herdsman:adapter:ezsp:uart --> DATA (2,0,0): 8200010500 2023-08-13T07:25:09.531Z zigbee-herdsman:adapter:ezsp:uart --> [20c021a9512ad2f17e] 2023-08-13T07:25:09.533Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (3) 2023-08-13T07:25:09.539Z zigbee-herdsman:adapter:ezsp:uart <-- [03c0a1a9512af4217e] 
2023-08-13T07:25:09.540Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (0,3,0): 03c0a1a9512af4217e 2023-08-13T07:25:09.540Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (1) 2023-08-13T07:25:09.541Z zigbee-herdsman:adapter:ezsp:uart --> [8160597e] 2023-08-13T07:25:09.543Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 8280010500 2023-08-13T07:25:09.543Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x5: {"_cls_":"nop","_id_":5,"_isRequest_":false} 2023-08-13T07:25:09.544Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (3) success 2023-08-13T07:25:19.530Z zigbee-herdsman:adapter:ezsp:ezsp Time to watchdog ... 0 2023-08-13T07:25:19.530Z zigbee-herdsman:adapter:ezsp:ezsp ==> nop: null 
2023-08-13T07:25:19.531Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"nop","_id_":5,"_isRequest_":true} 2023-08-13T07:25:19.532Z zigbee-herdsman:adapter:ezsp:uart --> DATA (3,1,0): 8300010500 2023-08-13T07:25:19.533Z zigbee-herdsman:adapter:ezsp:uart --> [31c121a9512a27847e] 2023-08-13T07:25:19.535Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (4) 2023-08-13T07:25:19.542Z zigbee-herdsman:adapter:ezsp:uart <-- [14c1a1a9512a8cb57e] 
2023-08-13T07:25:19.543Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (1,4,0): 14c1a1a9512a8cb57e 2023-08-13T07:25:19.543Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (2) 2023-08-13T07:25:19.544Z zigbee-herdsman:adapter:ezsp:uart --> [82503a7e] 2023-08-13T07:25:19.545Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 8380010500 2023-08-13T07:25:19.546Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x5: {"_cls_":"nop","_id_":5,"_isRequest_":false} 2023-08-13T07:25:19.547Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (4) success Zigbee2MQTT:debug 2023-08-13 16:25:26: Received MQTT message on 'zigbee2mqtt/bridge/request/touchlink/scan' with data '{"transaction":"qktug-2","value":true}' Zigbee2MQTT:info  2023-08-13 16:25:26: Start Touchlink scan 2023-08-13T07:25:26.642Z zigbee-herdsman:controller:touchlink Set InterPAN channel to '11' 2023-08-13T07:25:26.643Z zigbee-herdsman:adapter:ezsp:ezsp ==> setLogicalAndRadioChannel: {"radioChannel":11} 2023-08-13T07:25:26.644Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"setLogicalAndRadioChannel","_id_":185,"_isRequest_":true,"radioChannel":11} 2023-08-13T07:25:26.645Z zigbee-herdsman:adapter:ezsp:uart --> DATA (4,2,0): 840001b9000b 2023-08-13T07:25:26.646Z zigbee-herdsman:adapter:ezsp:uart --> [42c621a9ed2a1e3c467e] 2023-08-13T07:25:26.647Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (5) 
2023-08-13T07:25:26.657Z zigbee-herdsman:adapter:ezsp:uart <-- [25c6a1a9ed2a1505a37e] 2023-08-13T07:25:26.658Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (2,5,0): 25c6a1a9ed2a1505a37e 2023-08-13T07:25:26.658Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (3) 2023-08-13T07:25:26.659Z zigbee-herdsman:adapter:ezsp:uart --> [83401b7e] 2023-08-13T07:25:26.660Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 848001b90000 2023-08-13T07:25:26.661Z zigbee-herdsman:adapter:ezsp:ezsp <== 0xb9: {"_cls_":"setLogicalAndRadioChannel","_id_":185,"_isRequest_":false,"status":0} 2023-08-13T07:25:26.662Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (5) success 
2023-08-13T07:25:26.663Z zigbee-herdsman:adapter:ezsp:debg sendZclFrameInterPANBroadcast 2023-08-13T07:25:26.665Z zigbee-herdsman:adapter:ezsp:ezsp ==> sendRawMessage: {"message":{"type":"Buffer","data":[1,200,23,255,255,255,255,98,26,38,254,16,254,255,141,121,224,11,0,11,0,16,94,192,17,0,0,80,212,82,103,4,18]}} 2023-08-13T07:25:26.665Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"sendRawMessage","_id_":150,"_isRequest_":true,"message":{"type":"Buffer","data":[1,200,23,255,255,255,255,98,26,38,254,16,254,255,141,121,224,11,0,11,0,16,94,192,17,0,0,80,212,82,103,4,18]}} 2023-08-13T07:25:26.666Z zigbee-herdsman:adapter:ezsp:uart --> DATA (5,3,0): 85000196002101c817ffffffff621a26fe10feff8d79e00b000b00105ec011000050d452670412 2023-08-13T07:25:26.667Z zigbee-herdsman:adapter:ezsp:uart --> [53c721a9c22a34b39183b5da55aaf053bab0375512431e6bf6c66889ec20ffb6ebcd8ebbdd98c3c9b6967e] 2023-08-13T07:25:26.668Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (6) 2023-08-13T07:25:26.681Z zigbee-herdsman:adapter:ezsp:uart <-- [36c7a1a9c22a15050d7e] 2023-08-13T07:25:26.682Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (3,6,0): 36c7a1a9c22a15050d7e 2023-08-13T07:25:26.682Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (4) 2023-08-13T07:25:26.683Z zigbee-herdsman:adapter:ezsp:uart --> [8430fc7e] 2023-08-13T07:25:26.684Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 858001960000 2023-08-13T07:25:26.685Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x96: {"_cls_":"sendRawMessage","_id_":150,"_isRequest_":false,"status":0} 2023-08-13T07:25:26.686Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (6) success 2023-08-13T07:25:26.688Z zigbee-herdsman:adapter:ezsp:uart <-- [46c7b1a9cc2a159e377e] 2023-08-13T07:25:26.689Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (4,6,0): 46c7b1a9cc2a159e377e 2023-08-13T07:25:26.690Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (5) 2023-08-13T07:25:26.690Z zigbee-herdsman:adapter:ezsp:uart --> [8520dd7e] 2023-08-13T07:25:26.692Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 859001980000 2023-08-13T07:25:26.692Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x98: {"_cls_":"rawTransmitCompleteHandler","_id_":152,"_isRequest_":false,"status":0} 2023-08-13T07:25:26.693Z zigbee-herdsman:adapter:ezsp:driv Unhandled frame rawTransmitCompleteHandler 2023-08-13T07:25:26.709Z zigbee-herdsman:adapter:ezsp:uart <-- [56c7b1a9122a1732a6740f2466e16db6bab0375512431e6b8edd1d57e47d5e3e2ffccdd56f8cffd78515d2698d16f7fb8b673ea5e8756bfb35689b0e038987b6] 2023-08-13T07:25:26.712Z zigbee-herdsman:adapter:ezsp:uart <-- [5baa07b096d1678a449a46c08f9ff5c2d9db037e] 2023-08-13T07:25:26.714Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (5,6,0): 56c7b1a9122a1732a6740f2466e16db6bab0375512431e6b8edd1d57e47e3e2ffccdd56f8cffd78515d2698d16f7fb8b673ea5e8756bfb35689b0e038987b65baa07b096d1678a449a46c08f9ff5c2d9db037e 2023-08-13T07:25:26.714Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (6) 2023-08-13T07:25:26.715Z zigbee-herdsman:adapter:ezsp:uart --> [8610be7e] 2023-08-13T07:25:26.716Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 85900146000280ffe04501ccb4ffff26fe10feff8d79e0731b7ede1800018817000b000300105ec000000150d452671105000200e9baad24bd1db269f78e47a4000b731b020001000b5ec000020100 2023-08-13T07:25:26.718Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x46: {"_cls_":"macFilterMatchMessageHandler","_id_":70,"_isRequest_":false,"filterIndexMatch":2,"legacyPassthroughType":128,"lastHopLqi":255,"lastHopRssi":-32,"message":{"type":"Buffer","data":[1,204,180,255,255,38,254,16,254,255,141,121,224,115,27,126,222,24,0,1,136,23,0,11,0,3,0,16,94,192,0,0,1,80,212,82,103,17,5,0,2,0,233,186,173,36,189,29,178,105,247,142,71,164,0,11,115,27,2,0,1,0,11,94,192,0,2,1,0]}} 2023-08-13T07:25:26.721Z zigbee-herdsman:adapter:ezsp:driv macFilterMatchMessageHandler frame message: EmberIeeeRawFrame: {"ieeeFrameControl":52225,"sequence":180,"destPanId":65535,"destAddress":{"type":"Buffer","data":[224,121,141,255,254,16,254,38]},"sourcePanId":7027,"sourceAddress":{"type":"Buffer","data":[0,23,136,1,0,24,222,126]},"nwkFrameControl":11,"appFrameControl":3,"clusterId":4096,"profileId":49246} 2023-08-13T07:25:26.722Z zigbee-herdsman:adapter:ezsp:debg processMessage: {"messageType":null,"apsFrame":{"ieeeFrameControl":52225,"sequence":180,"destPanId":65535,"destAddress":{"type":"Buffer","data":[224,121,141,255,254,16,254,38]},"sourcePanId":7027,"sourceAddress":{"type":"Buffer","data":[0,23,136,1,0,24,222,126]},"nwkFrameControl":11,"appFrameControl":3,"clusterId":4096,"profileId":49246},"lqi":255,"rssi":-32,"sender":null,"bindingIndex":null,"addressIndex":null,"message":{"type":"Buffer","data":[0,0,1,80,212,82,103,17,5,0,2,0,233,186,173,36,189,29,178,105,247,142,71,164,0,11,115,27,2,0,1,0,11,94,192,0,2,1,0]},"senderEui64":{"_value":{"type":"Buffer","data":[0,23,136,1,0,24,222,126]}}} TypeError: Cannot read properties of undefined (reading 'toUpperCase') at BuffaloZcl.read (/app/node_modules/zigbee-herdsman/src/zcl/buffaloZcl.ts:687:36) at BuffaloZcl.readUseDataType (/app/node_modules/zigbee-herdsman/src/zcl/buffaloZcl.ts:139:21) at BuffaloZcl.read 
(/app/node_modules/zigbee-herdsman/src/zcl/buffaloZcl.ts:652:25) at Function.parsePayloadGlobal (/app/node_modules/zigbee-herdsman/src/zcl/zclFrame.ts:279:53) at Function.parsePayload 
(/app/node_modules/zigbee-herdsman/src/zcl/zclFrame.ts:214:25) at Function.fromBuffer (/app/node_modules/zigbee-herdsman/src/zcl/zclFrame.ts:186:30) at EZSPAdapter.processMessage 
(/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:102:33) at Driver.emit (node:events:513:28) at Driver.handleFrame (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:336:18) at Ezsp.emit (node:events:513:28)
`

**Comment by Roy-974** [comment]
If that can help, I can get the log on a Touchlink scan where it does not crash the app.

**Comment by Roy-974** [comment]
I checked with newer version of Z2M 1.33.0. Still the same issue.

**Comment by Roy-974** [comment]
Please, anyone can help me on this issue?
