### ISSUE TITLE
Moes BHT-002-GCLZB Thermostat incorrect value template for the "program" object

### ISSUE THREAD

**Issue by Jarikk** [Koenkk/zigbee2mqtt#18614]
### What happened?

I thought the problem was related to the MQTT integration and created the ticket there first (home-assistant/core#98344). But in the discussion it was found out that it's an issue of Zigbee2Mqtt.

The problem is in the value template for object "program" because it cannot handle NULL value correctly.
**{{ value_json.program|default("") | truncate(254, True, '', 0) }}**

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

20230507

### Adapter

ZigStar Lan CC2652P

### Debug log

2023-08-14 10:03:06.773 DEBUG (MainThread) [homeassistant.components.mqtt.models] Rendering incoming payload '{"child_lock":null,"current_heating_setpoint":23,"deadzone_temperature":null,"heat":"OFF","last_seen":"2023-08-14T10:03:03+03:00","linkquality":58,"local_temperature":23,"local_temperature_calibration":null,"max_temperature_limit":null,"min_temperature_limit":null,"preset":"hold","preset_mode":"hold","program":null,"running_state":"idle","sensor":null,"system_mode":"off"}' with variables {'entity_id': 'sensor.0x60a423fffeb27fa1_program', 'name': 'program', 'this': <template TemplateStateFromEntityId(sensor.0x60a423fffeb27fa1_program)>} with default value 'default' and Template<template=({{ value_json.program|default("") | truncate(254, True, '', 0) }}) renders=3240>

2023-08-14 10:03:06.794 ERROR (MainThread) [homeassistant.util.logging] Exception in message_received when handling msg on 'zigbee2mqtt_livingroom/Balcony, thermostat': '{"child_lock":null,"current_heating_setpoint":23,"deadzone_temperature":null,"heat":"OFF","last_seen":"2023-08-14T10:03:03+03:00","linkquality":58,"local_temperature":23,"local_temperature_calibration":null,"max_temperature_limit":null,"min_temperature_limit":null,"preset":"hold","preset_mode":"hold","program":null,"running_state":"idle","sensor":null,"system_mode":"off"}'
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper
    msg_callback(msg)
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/mqtt/sensor.py", line 293, in message_received
    _update_state(msg)
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/mqtt/sensor.py", line 244, in _update_state
    payload = self._template(msg.payload, PayloadSentinel.DEFAULT)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/mqtt/models.py", line 251, in async_render_with_possible_json_value
    rendered_payload = self._value_template.async_render_with_possible_json_value(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/template.py", line 735, in async_render_with_possible_json_value
    return _render_with_context(self.template, compiled, **variables).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/template.py", line 2179, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/lsiopy/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/lsiopy/lib/python3.11/site-packages/jinja2/filters.py", line 870, in do_truncate
    if len(s) <= length + leeway:
       ^^^^^^
TypeError: object of type 'NoneType' has no len()

**Comment by Jarikk** [comment]
up
