### ISSUE TITLE
Random exceptions: Cannot read properties of undefined (reading 'hasOwnProperty')}

### ISSUE THREAD

**Issue by tkarlsson** [Koenkk/zigbee2mqtt#18656]
### What happened?

Getting random exceptions

### Zigbee2MQTT version

1.32.2-dev commit: 3736b59

### Adapter firmware version

20230507

### Adapter

Sonoff

### Debug log

Zigbee2MQTT:error 2023-08-18 15:37:42: Exception while calling fromZigbee converter: Cannot read properties of undefined (reading 'hasOwnProperty')}
Zigbee2MQTT:debug 2023-08-18 15:37:42: TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at Object.convert (/app/node_modules/zigbee-herdsman-converters/src/converters/fromZigbee.js:782:24)
    at Receive.onDeviceMessage (/app/lib/extension/receive.ts:150:51)
    at EventEmitter.emit (node:events:526:35)
    at EventBus.emitDeviceMessage (/app/lib/eventBus.ts:102:22)
    at Controller.<anonymous> (/app/lib/zigbee.ts:108:27)
    at Controller.emit (node:events:514:28)
    at Controller.selfAndDeviceEmit (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:527:14)
    at Controller.onZclOrRawData (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:738:18)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:144:70)
    at ZStackAdapter.emit (node:events:514:28)

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by djcrawleravp** [comment]
Im on the last version, any idea why is happening again?
