### ISSUE TITLE
Sonoff Dongle-E (EFR32MG21)

### ISSUE THREAD

**Issue by Blackspell01** [Koenkk/zigbee2mqtt#18733]
### What happened?

Ive just bought two sonoff dongles (both the silicon labs version). One for my home assistant and one for home bridge.
On the first one I flashed the multipan software which works flawlessly now on my home assistant.
Now im struggling with the second stick on my raspberry pi which runs home bridge.
I did update the firmware on the stick itself to the most recent one and installed mosquitto and zigbee2mqtt on the raspberry pi. My config looks like this:

mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.188.79'
  user: mqtt-user
  password: mqtt

serial:
  port: /dev/ttyACM0
  adapter: ezsp

Did I do something wrong?

### Zigbee2MQTT version

1.32.2

### Adapter firmware version

EZSP 7.3.1.0

### Adapter

Sonoff Dongle-E

### Debug log

pi@raspberrypi:/opt/zigbee2mqtt $ npm start

> zigbee2mqtt@1.32.2 start
> node index.js

Zigbee2MQTT:info  2023-08-25 16:22:06: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2023-08-25.16-22-06' filename: log.txt
Zigbee2MQTT:info  2023-08-25 16:22:06: Starting Zigbee2MQTT version 1.32.2 (commit #1ec1e572)
Zigbee2MQTT:info  2023-08-25 16:22:06: Starting zigbee-herdsman (0.17.2)
Zigbee2MQTT:error 2023-08-25 16:22:27: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-08-25 16:22:27: Failed to start zigbee
Zigbee2MQTT:error 2023-08-25 16:22:27: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-08-25 16:22:27: Exiting...
Zigbee2MQTT:error 2023-08-25 16:22:28: Error: Connection not initialized
    at Ezsp.execCommand (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:551:19)
    at Ezsp.version (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:349:35)
    at Driver.startup (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:141:25)
    at EZSPAdapter.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:165:16)
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:59:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:101:27)
    at start (/opt/zigbee2mqtt/index.js:107:5)
pi@raspberrypi:/opt/zigbee2mqtt $

**Comment by joesensoric** [comment]
I also had this error after installation. The reason was missing permission on the tty port, see:

https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html#verify-that-the-user-you-run-zigbee2mqtt-as-has-write-access-to-the-port
