### ISSUE TITLE
Z2mqtt not working after update

### ISSUE THREAD

**Issue by gfrcr** [Koenkk/zigbee2mqtt#18807]
### What happened?

After a blackout at home, z2mqtt stopped working, I was using the dev branch, I updated and nothing happened, I switched to normal z2mqtt and it stayed the same.

### How to reproduce it (minimal and precise)

[22:20:41] INFO: Preparing to start...
[22:20:41] INFO: Socat not enabled
[22:20:43] INFO: Starting Zigbee2MQTT...
/app/node_modules/zigbee-herdsman-converters/index.js:79
        if (converter.options) {
                      ^
TypeError: Cannot read properties of undefined (reading 'options')
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:79:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)

### Zigbee2MQTT version

1.32.2-1

### Adapter firmware version

 0x84b4dbfffef816f0

### Adapter

 EZSP v8 ( sonoff 3.0)

**Comment by Koenkk** [comment]
You are using an external converter which is not compatible with the latest z2m, removing this converter from your `configuration.yaml` should fix the issue.
