### ISSUE TITLE
Zigbee2MQTT addon crashes due to 'MAC no ack' when sending zigbee message

### ISSUE THREAD

**Issue by JJdeVries** [Koenkk/zigbee2mqtt#18944]
### What happened?

When sending any command to the [Aqara Pet Feeder](https://www.zigbee2mqtt.io/devices/ZNCWWSQ01LM.html) the Home-Assistant addon crashes with the following log message:
```
{"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233))
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23)
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
```

I'm unsure whether this issue should be raised here (the add-on is the one crashing), or in the zigbee-herdsman repo as that module seems to raise an unexpected error?

### What did you expect to happen?

The message should probably be received correctly, but also a failure should probably not fully crash the add-on

### How to reproduce it (minimal and precise)

* Start up the zigbee2mqtt add-on
* Send any command to the pet-feeder (e.g. UNLOCK)
* After ~10 secs the application crashes

### Zigbee2MQTT version

1.33.0 commit: unknown

### Adapter firmware version

20211115

### Adapter

CC2531 

### Debug log

```
Zigbee2MQTT:debug 2023-09-11 11:11:18: Publishing 'set' 'child_lock' to 'De Foodzi unit'
Zigbee2MQTT:info  2023-09-11 11:11:18: MQTT publish: topic 'zigbee2mqtt/De Foodzi unit', payload '{"child_lock":"UNLOCK","error":false,"feed":"START","feeding_size":1,"feeding_source":"remote","led_indicator":"ON","linkquality":76,"mode":"manual","portion_weight":7,"portions_per_day":0,"schedule":[{"days":"everyday","hour":18,"minute":30,"size":1},{"days":"everyday","hour":7,"minute":30,"size":1},{"days":"everyday","hour":7,"minute":40,"size":2},{"days":"everyday","hour":18,"minute":40,"size":2}],"serving_size":1,"update":{"installed_version":9761,"latest_version":9761,"state":"idle"},"update_available":false,"weight_per_day":0}'
Error: Write 0x54ef441000714653/1 aqaraOpple({"65521":{"value":{"type":"Buffer","data":[0,2,1,4,22,0,85,1,0]},"type":65}}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233))
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23)
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
```

### Additional info
Other devices such as IKEA tradfri lights, and Hue work perfectly fine. Also issues during sending such as `No network route`:
```
{"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205)))
```
Do **not** cause the addon to crash.

**Comment by JJdeVries** [comment]
Deleting the specific device and reconnecting it solved the above issue. I'll thus close this issue, although the entire application crashing due to a connection issue is maybe not desired behaviour.
