### ISSUE TITLE
Error after power outage

### ISSUE THREAD

**Issue by ciB89** [Koenkk/zigbee2mqtt#1903]
# Bug Report
## What happened

After a power outage (~5 min) zigbee2mqtt stopped working/crashes with error code. Tried updating to 1.5.1 - did not help. Did I break my CC2531? Shall I try reflashing it? I also reboted the device, checked whether ttyACM0 changed to ttyACM1 - but no luck :(

The shepard starts mostly on the second try, but crashes shortly after again. It then continues with a reboot loop.

```
/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/node_modules/q/q.js:155
                throw e;
                ^
Error: ccznp has not been initialized yet
    at CcZnp.request (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/cc-znp/index.js:133:15)
    at CcZnp.(anonymous function) [as zdoRequest] (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/cc-znp/index.js:176:21)
    at Zdo._sendZdoRequestViaZnp (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/components/zdo.js:29:12)
    at Zdo._genericRequest (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/components/zdo.js:47:10)
    at Zdo._specialRequest (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/components/zdo.js:63:25)
    at Zdo.request (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/components/zdo.js:20:21)
    at Controller.request (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/components/controller.js:300:19)
    at req (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/components/query.js:119:47)
    at performReq (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/components/query.js:127:9)
    at /zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/components/query.js:133:17
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.5.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR!
 Failed at the zigbee2mqtt@1.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-28T22_08_52_384Z-debug.log
2019-08-29T00:08:53: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-08-29T00:08:53: PM2 log: App [npm:0] starting in -fork mode-
2019-08-29T00:08:53: PM2 log: App [npm:0] online
> zigbee2mqtt@1.5.1 start /zigbee2mqtt-1.5.1
> node index.js
  zigbee2mqtt:info 8/29/2019, 12:08:58 AM Logging to directory: '/share/zigbee2mqtt/log/2019-08-29.00-08-57'
  zigbee2mqtt:info 8/29/2019, 12:08:59 AM Starting zigbee2mqtt version 1.5.1 (commit #unknown)
  zigbee2mqtt:info 8/29/2019, 12:08:59 AM Starting zigbee-shepherd
  zigbee2mqtt:info 8/29/2019, 12:08:59 AM Error while starting zigbee-shepherd, attempting to fix... (takes 60 seconds) (Error: Error: No such device or address, cannot open /dev/ttyACM0)
  zigbee2mqtt:info 8/29/2019, 12:09:59 AM Starting zigbee-shepherd
  zigbee2mqtt:error 8/29/2019, 12:09:59 AM Error while starting zigbee-shepherd! (Error: Error: Resource busy, cannot open /dev/ttyACM0)
  zigbee2mqtt:error 8/29/2019, 12:09:59 AM Press the reset button on the stick (the one closest to the USB) and start again
  zigbee2mqtt:error 8/29/2019, 12:09:59 AM Failed to start
	{"message":"Error: Resource busy, cannot open /dev/ttyACM0","stack":"Error: Error: Resource busy, cannot open /dev/ttyACM0"}
  zigbee2mqtt:error 8/29/2019, 12:09:59 AM Exiting...
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.5.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-28T22_09_59_359Z-debug.log
2019-08-29T00:09:59: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-08-29T00:09:59: PM2 log: App [npm:0] starting in -fork mode-
2019-08-29T00:09:59: PM2 log: App [npm:0] online
```

## Debug Info
zigbee2mqtt version: 1.5.0 / 1.5.1
CC2531 firmware version: 20190425

Running Hassio and zigbe2mqtt-edge on a Raspberry Pi 3

**Comment by ciB89** [comment]
So tried reflashing the stick and using a different USB port on my device, did not help. But I tried using the non-edge version and that did work.. this really confuses me, config is exactly the same. Only database/paired devices are different.

**Comment by ciB89** [comment]
Fixed it - for whatever reason my config updated to the new scheme (1.5.1) although I had not updated - maybe it was a simple display error. Had to move my devices/groups to devices.yaml and now it works again.
