### ISSUE TITLE
[New device support]: lumi.remote.acn008

### ISSUE THREAD

**Issue by LazareffR** [Koenkk/zigbee2mqtt#19109]
### Link

https://aliexpress.ru/item/33007165642.html?spm=a2g2w.orderdetail.0.0.611d4aa645Y7na&sku_id=12000035187525449

### Database entry

{"id":96,"type":"EndDevice","ieeeAddr":"0x54ef44100078e673","nwkAddr":20358,"manufId":4447,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.remote.acn008","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":0,"inClusterList":[0,1,3,18,64704],"outClusterList":[3,6,25],"clusters":{"genBasic":{"attributes":{"appVersion":7,"modelId":"lumi.remote.acn008","manufacturerName":"LUMI","powerSource":3,"zclVersion":3,"stackVersion":2,"hwVersion":0}},"genMultistateInput":{"attributes":{"presentValue":1}},"aqaraOpple":{"attributes":{"247":{"type":"Buffer","data":[1,33,170,11,3,40,25,4,33,0,0,5,33,1,0,8,33,7,0,10,33,25,80,12,32,30,100,32,1]}}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":7,"stackVersion":2,"hwVersion":0,"zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1695975305532,"defaultSendRequestWhen":"immediate"}

### Comments

 Please add this device. Thanks a lot

**Comment by LazareffR** [comment]
Пожалуйста сделайте поддержку. Очень нужно ))

**Comment by godmff** [comment]
for me also+++

**Comment by LazareffR** [comment]
Can someone help? I'm ready to pay.

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following [external converter](https://gist.github.com/Koenkk/325c0672f66dd0ba550b79a5aa0d1269): 

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, check if issue is fixed

**Comment by cazxtc** [comment]
iI get the following message when I start

`[14:04:38] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:error 2024-02-24 14:04:42: Failed to load external converter file 'WXKG21LM.js' (ENOENT: no such file or directory, open '/config/zigbee2mqtt/WXKG21LM.js')
Zigbee2MQTT:error 2024-02-24 14:04:42: Probably there is a syntax error in the file or the external converter is not compatible with the current Zigbee2MQTT version
Zigbee2MQTT:error 2024-02-24 14:04:42: Note that external converters are not meant for long term usage, it's meant for local testing after which a pull request should be created to add out-of-the-box support for the device
Zigbee2MQTT:info  2024-02-24 14:04:42: Logging to console and directory: '/config/zigbee2mqtt/log/2024-02-24.14-04-42' filename: log.txt
Zigbee2MQTT:info  2024-02-24 14:04:42: Starting Zigbee2MQTT version 1.35.3 (commit #unknown)
Zigbee2MQTT:info  2024-02-24 14:04:42: Starting zigbee-herdsman (0.33.8)`

**Comment by LazareffR** [comment]
> iI get the following message when I start
> 
> `[14:04:38] INFO: Starting Zigbee2MQTT... Zigbee2MQTT:error 2024-02-24 14:04:42: Failed to load external converter file 'WXKG21LM.js' (ENOENT: no such file or directory, open '/config/zigbee2mqtt/WXKG21LM.js') Zigbee2MQTT:error 2024-02-24 14:04:42: Probably there is a syntax error in the file or the external converter is not compatible with the current Zigbee2MQTT version Zigbee2MQTT:error 2024-02-24 14:04:42: Note that external converters are not meant for long term usage, it's meant for local testing after which a pull request should be created to add out-of-the-box support for the device Zigbee2MQTT:info 2024-02-24 14:04:42: Logging to console and directory: '/config/zigbee2mqtt/log/2024-02-24.14-04-42' filename: log.txt Zigbee2MQTT:info 2024-02-24 14:04:42: Starting Zigbee2MQTT version 1.35.3 (commit #unknown) Zigbee2MQTT:info 2024-02-24 14:04:42: Starting zigbee-herdsman (0.33.8)`

The same problem

**Comment by Koenkk** [comment]
Did you name the file the same as you did it in the `configuration.yaml`?

**Comment by LazareffR** [comment]
> Did you name the file the same as you did it in the `configuration.yaml`?

Yes. ext_converter.js

**Comment by LazareffR** [comment]
Zigbee2MQTT:error 2024-02-25 16:20:02: Failed to load external converter file 'ext_converter.js' (Cannot read properties of undefined (reading 'options'))
Zigbee2MQTT:error 2024-02-25 16:20:02: Probably there is a syntax error in the file or the external converter is not compatible with the current Zigbee2MQTT version
Zigbee2MQTT:error 2024-02-25 16:20:02: Note that external converters are not meant for long term usage, it's meant for local testing after which a pull request should be created to add out-of-the-box support for the device

**Comment by LazareffR** [comment]
<img width="226" alt="Снимок экрана 2024-02-25 в 16 26 28" src="https://github.com/Koenkk/zigbee2mqtt/assets/90869264/12fad697-18d7-4fee-ac41-2967aa863bcb">

**Comment by Koenkk** [comment]
Can you try with the latest [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)?

**Comment by godmff** [comment]
> Can you try with the latest [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)?

Works but only single press action. Not possible to switch Click mode

**Comment by cazxtc** [comment]
same by me

**Comment by ddetkovs** [comment]
I'm getting this when using the converter:

> Failed to configure '0x54ef441000a1652d', attempt 2 (Error: Bind 0x54ef441000a1652d/1 genPowerCfg from '0x00124b0014d97069/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:691:28 at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:465:13) at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:75:13) at configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:112:17) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:173:21) at Configure.configure (/app/lib/extension/configure.ts:121:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

Any clue why would it do it? Thanks in advance!

**Comment by Koenkk** [comment]
@ddetkovs make sure the device is awake

To all others, does it send any other commands besides `single`? If not, can you provide the debug log when triggering them?

**Comment by ddetkovs** [comment]
Thanks @Koenkk . I realized that there was a typo in the gist of the converter that you provided and so it was failing for me. 
In a nutshell, `manufacturerCode` was undefined and so configure block failed.
Here's what works for me: https://gist.github.com/ddetkovs/17d71ec66ebffab4d0fe251c5b187b33

I can confirm that I get single/double/hold messages, but not triple. Nothing in the logs for triple.

**Comment by Koenkk** [comment]
Would be great if you could make a PR!

**Comment by aperevalov** [comment]
Hi there. Thank you for your effort with supporting converters for different devices.
I'm trying the latest one from @ddetkovs but I'm getting an errors in logs:

> Error 2024-08-16 19:02:11z2m: Failed to configure '0x54ef44100078d6f4', attempt 1 (Error: ZCL command 0x54ef44100078d6f4/1 manuSpecificLumi.write({"mode":1}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 49912 - 1 - 113 - 64704 - 4 after 10000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23) at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:525:47) at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:81:20) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:866:28) at Endpoint.write (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:388:9) at configure (/app/data/extension/externally-loaded.js:29:9) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:190:21) at Configure.configure (/app/lib/extension/configure.ts:126:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

When I'm clicking on the button once, I get next logs:

> Info 2024-08-16 19:01:51z2m: Configuring '0x54ef44100078d6f4'
Info 2024-08-16 19:01:51z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/0x54ef44100078d6f4', payload '{"action":"single","battery":null,"click_mode":null,"linkquality":144,"operation_mode":null,"voltage":null}'
Info 2024-08-16 19:01:51z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/0x54ef44100078d6f4', payload '{"action":"","battery":null,"click_mode":null,"linkquality":144,"operation_mode":null,"voltage":null}'
Info 2024-08-16 19:01:51z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/0x54ef44100078d6f4/action', payload 'single'

Device for some reason does not send `battery` and `voltage`.

Also it time out when trying to change click mode or operation mode.

Could you please advise if it's an issue with convertor or configuration on my end?

**Comment by Medved77** [comment]
Adding a comment to keep the issue active. Hoping that someone with more capabilities than I will create a PR based on ddetkovs fix.

**Comment by Medved77** [comment]
Bump

**Comment by devau-remi** [comment]
Hello!
Small bump to check if any of you manage to make it work.
I tried dev branch, same error as the others.
I'll try today to checkout an older version of z2m to check if I can make it work like @ddetkovs did

**Comment by dankarization** [comment]
any news on that?

**Comment by devau-remi** [comment]
Hello,
@dankarization , I did manage to make this switch working with ddetkovs converters.

I'm using a fresh z2m 2.4.
I had to add this converter into data/external_converters.
You can create the folder and the file with pushing a message in:

`zigbee2mqtt/bridge/request/converter/save`

With this kind of payload:

`{"name": "my-first-converter.js", "code": "test"}`

Then you copy/past all js from ddetkovs

I just modified this line 15, 
` meta: {battery: {voltageToPercentage: '3V_2100'}, multiEndpoint: false},`
**3V_2100** instead of **3V_2850_3000**

As stated by ddetkovs, single/double/hold is ok.
Battery and link quality reporting are ok

I'm reading/learning how to make the PR, i'll let you know here

**Comment by pyatins** [comment]
I created a pull request to add support for this switch:
https://github.com/Koenkk/zigbee-herdsman-converters/pull/9902
https://github.com/Koenkk/zigbee2mqtt.io/pull/4091

I hope Zigbee2MQTT will soon support it and we will be able to remove the external converter.
