### ISSUE TITLE
Unable to create a working docker-compose.yaml - remote network adapter 

### ISSUE THREAD

**Issue by d3zit** [Koenkk/zigbee2mqtt#19192]
### What happened?

I am unable to create a Docker Compose yaml that allows me to use the remote adapter I have. In all the examples in the documentation, I see references to a USB adapter

`version: '3.8'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED3DDF-if00:/dev/ttyACM0`

It doesn't work even If I remove the last lines and I add the

`serial:
  port: 'tcp://192.168.1.1:23'`

in the configuration.yaml

### What did you expect to happen?

The container doesn't start

### Zigbee2MQTT version

1.33.1

### Adapter firmware version

/

### Adapter

Z-Bee Duo

### Debug log

info  2023-10-06 21:40:46: Logging to console and directory: '/app/data/log/2023-10-06.21-40-46' filename: log.txt
info  2023-10-06 21:40:46: Starting Zigbee2MQTT version 1.33.1 (commit #7e63039)
info  2023-10-06 21:40:46: Starting zigbee-herdsman (0.19.0)
error 2023-10-06 21:40:46: Error while starting zigbee-herdsman
error 2023-10-06 21:40:46: Failed to start zigbee
error 2023-10-06 21:40:46: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2023-10-06 21:40:46: Exiting...
error 2023-10-06 21:40:46: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/app/node_modules/@serialport/stream/dist/index.js:82:22)
    at /app/node_modules/@serialport/stream/dist/index.js:118:18

**Comment by d3zit** [comment]
Even if I remove the devices line, it doesn't work.

version: '3.8'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Europe/Rome

**Comment by d3zit** [comment]
The cause is always linked to the inaccessibility of the Zigbee antenna, therefore it is essential to edit the configuration.yaml file with the correct network address and port.
