### ISSUE TITLE
Crash when pairing with icasa zigbee 3.0 dimmer ICZB-IW11D

### ISSUE THREAD

**Issue by rutgerhendriks** [Koenkk/zigbee2mqtt#1946]
# Bug Report
## What happened
Zigbee2mqtt crashes when pairing with icasa dimmer 
ICZB-IW11D icasa zigbee 3.0 dimmer

## What did you expect to happen
No crash but normal pairing
## How to reproduce it (minimal and precise)
Press the reset button on the icasa dimmer 5 times and it starts the pairing sequence again. Here is the logging I got with zigbee2mqtt running in debug mode:
  zigbee2mqtt:info 9/6/2019, 9:00:08 PM Successfully reenabled joining
  zigbee2mqtt:debug 9/6/2019, 9:00:13 PM Received zigbee message of type 'devLeaving' with data '"0x000d6f00137473de"' of endpoint undefined
  zigbee2mqtt:warn 9/6/2019, 9:00:13 PM Message without device!
  zigbee2mqtt:debug 9/6/2019, 9:00:20 PM Received zigbee message of type 'readRsp' with data '{"cid":"genBasic","data":{"manufacturerName":"icasa","modelId":"ICZB-IW11D","powerSource":1}}' of device 'ICZB-IW11D' (0x000d6f00137473de) of endpoint 1
  zigbee2mqtt:debug 9/6/2019, 9:00:20 PM Received zigbee message of type 'readRsp' with data '{"cid":"genBasic","data":{"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"NULL","swBuildId":"2.4.1_r33"}}' of device 'ICZB-IW11D' (0x000d6f00137473de) of endpoint 1
  zigbee2mqtt:debug 9/6/2019, 9:00:20 PM Received zigbee message of type 'readRsp' with data '{"cid":"genBasic","data":{"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":0,"manufacturerName":"icasa"}}' of device 'ICZB-IW11D' (0x000d6f00137473de) of endpoint 1
  zigbee2mqtt:debug 9/6/2019, 9:00:21 PM Received zigbee message of type 'readRsp' with data '{"cid":"genBasic","data":{"9":255,"modelId":"ICZB-IW11D","dateCode":"NULL","powerSource":1,"appProfileVersion":255}}' of device 'ICZB-IW11D' (0x000d6f00137473de) of endpoint 1
  zigbee2mqtt:debug 9/6/2019, 9:00:21 PM Received zigbee message of type 'readRsp' with data '{"cid":"genBasic","data":{"10":{"type":"Buffer","data":[48,48]},"11":"NULL","30721":260,"30722":269,"swBuildId":"2.4.1_r33"}}' of device 'ICZB-IW11D' (0x000d6f00137473de) of endpoint 1
  zigbee2mqtt:debug 9/6/2019, 9:00:21 PM Received zigbee message of type 'readRsp' with data '{"cid":"genBasic","data":{"30723":255,"30724":255,"34819":0,"34820":0,"36864":255}}' of device 'ICZB-IW11D' (0x000d6f00137473de) of endpoint 1
  zigbee2mqtt:debug 9/6/2019, 9:00:21 PM Received zigbee message of type 'readRsp' with data '{"cid":"genBasic","data":{"65533":1}}' of device 'ICZB-IW11D' (0x000d6f00137473de) of endpoint 1
  zigbee2mqtt:debug 9/6/2019, 9:00:21 PM Received zigbee message of type 'devInterview' with data '"0x000d6f00137473de"'
  zigbee2mqtt:debug 9/6/2019, 9:00:21 PM Received zigbee message of type 'readRsp' with data '{"cid":"genIdentify","data":{"65533":1,"identifyTime":0}}' of device 'ICZB-IW11D' (0x000d6f00137473de) of endpoint 1
  zigbee2mqtt:debug 9/6/2019, 9:00:21 PM Received zigbee message of type 'devInterview' with data '"0x000d6f00137473de"'
  zigbee2mqtt:debug 9/6/2019, 9:00:22 PM Received zigbee message of type 'readRsp' with data '{"cid":"genGroups","data":{"65533":1,"nameSupport":0}}' of device 'ICZB-IW11D' (0x000d6f00137473de) of endpoint 1
  zigbee2mqtt:debug 9/6/2019, 9:00:22 PM Received zigbee message of type 'devInterview' with data '"0x000d6f00137473de"'
  zigbee2mqtt:debug 9/6/2019, 9:00:22 PM Received zigbee message of type 'readRsp' with data '{"cid":"genScenes","data":{"count":0,"currentScene":0,"currentGroup":0,"sceneValid":0,"nameSupport":0}}' of device 'ICZB-IW11D' (0x000d6f00137473de) of endpoint 1
  zigbee2mqtt:debug 9/6/2019, 9:00:22 PM Received zigbee message of type 'readRsp' with data '{"cid":"genScenes","data":{"65533":1}}' of device 'ICZB-IW11D' (0x000d6f00137473de) of endpoint 1
  zigbee2mqtt:debug 9/6/2019, 9:00:22 PM Received zigbee message of type 'devInterview' with data '"0x000d6f00137473de"'
  zigbee2mqtt:debug 9/6/2019, 9:00:22 PM Received zigbee message of type 'readRsp' with data '{"cid":"genOnOff","data":{"16387":255,"onOff":1,"globalSceneCtrl":1,"onTime":0,"offWaitTime":0}}' of device 'ICZB-IW11D' (0x000d6f00137473de) of endpoint 1
  zigbee2mqtt:info 9/6/2019, 9:00:22 PM MQTT publish: topic 'zigbee2mqtt/Icasa dimmer test', payload '{"state":"ON","linkquality":63,"brightness":255,"device":{"ieeeAddr":"0x000d6f00137473de","friendlyName":"Icasa dimmer test","type":"Router","nwkAddr":12441,"manufId":4107,"manufName":"icasa","powerSource":"Mains (single phase)","modelId":"ICZB-IW11D","hwVersion":"unknown","swBuildId":"2.4.1_r33","dateCode":"NULL","status":"online"}}'
  zigbee2mqtt:debug 9/6/2019, 9:00:22 PM Received zigbee message of type 'readRsp' with data '{"cid":"genOnOff","data":{"65533":1}}' of device 'ICZB-IW11D' (0x000d6f00137473de) of endpoint 1
  zigbee2mqtt:debug 9/6/2019, 9:00:22 PM Received zigbee message of type 'devInterview' with data '"0x000d6f00137473de"'
  zigbee2mqtt:debug 9/6/2019, 9:00:23 PM Received zigbee message of type 'readRsp' with data '{"cid":"genLevelCtrl","data":{"15":1,"currentLevel":254,"remainingTime":0,"onOffTransitionTime":1,"onLevel":255}}' of device 'ICZB-IW11D' (0x000d6f00137473de) of endpoint 1
  zigbee2mqtt:info 9/6/2019, 9:00:23 PM MQTT publish: topic 'zigbee2mqtt/Icasa dimmer test', payload '{"state":"ON","linkquality":65,"brightness":254,"device":{"ieeeAddr":"0x000d6f00137473de","friendlyName":"Icasa dimmer test","type":"Router","nwkAddr":12441,"manufId":4107,"manufName":"icasa","powerSource":"Mains (single phase)","modelId":"ICZB-IW11D","hwVersion":"unknown","swBuildId":"2.4.1_r33","dateCode":"NULL","status":"online"}}'
  zigbee2mqtt:debug 9/6/2019, 9:00:23 PM Received zigbee message of type 'readRsp' with data '{"cid":"genLevelCtrl","data":{"16384":255,"65533":1}}' of device 'ICZB-IW11D' (0x000d6f00137473de) of endpoint 1
  zigbee2mqtt:debug 9/6/2019, 9:00:23 PM Received zigbee message of type 'devInterview' with data '"0x000d6f00137473de"'
  zigbee2mqtt:debug 9/6/2019, 9:00:23 PM Received zigbee message of type 'devInterview' with data '"0x000d6f00137473de"'
\  zigbee2mqtt:debug 9/6/2019, 9:00:23 PM Received zigbee message of type 'readRsp' with data '{"cid":"haDiagnostic","data":{"65533":1,"numberOfResets":0,"averageMacRetryPerApsMessageSent":0,"lastMessageLqi":0,"lastMessageRssi":0}}' of device 'ICZB-IW11D' (0x000d6f00137473de) of endpoint 1
  zigbee2mqtt:debug 9/6/2019, 9:00:23 PM Received zigbee message of type 'devInterview' with data '"0x000d6f00137473de"'
  zigbee2mqtt:debug 9/6/2019, 9:00:24 PM Received zigbee message of type 'readRsp' with data '{"cid":"lightLink","data":{"65533":1}}' of device 'ICZB-IW11D' (0x000d6f00137473de) of endpoint 1
  zigbee2mqtt:debug 9/6/2019, 9:00:24 PM Received zigbee message of type 'devInterview' with data '"0x000d6f00137473de"'
/app/node_modules/zigbee-herdsman/dist/zcl/utils.js:49
        throw new Error(`Cluster with key '${key}' does not exist`);
        ^

Error: Cluster with key '33' does not exist
    at Object.getCluster (/app/node_modules/zigbee-herdsman/dist/zcl/utils.js:49:15)
    at Object.getAttributeLegacy (/app/node_modules/zigbee-herdsman/dist/zcl/index.js:39:27)
    at /app/node_modules/zigbee-herdsman/dist/lib/shepherd.js:145:36
    at Object._.forEach (/app/node_modules/zigbee-herdsman/node_modules/busyman/index.js:411:27)
    at ZShepherd.<anonymous> (/app/node_modules/zigbee-herdsman/dist/lib/shepherd.js:144:11)
    at ZShepherd.emit (events.js:182:13)
    at dispatchIncomingMsg (/app/node_modules/zigbee-herdsman/dist/lib/components/af.js:565:41)
    at Controller.zclIncomingMsgHandler (/app/node_modules/zigbee-herdsman/dist/lib/components/af.js:631:12)
    at Controller.emit (events.js:182:13)
    at Immediate.<anonymous> (/app/node_modules/zigbee-herdsman/dist/lib/components/af.js:640:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.5.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.5.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-06T19_00_24_384Z-debug.log

## Debug Info
zigbee2mqtt version: 1.5.1
CC253X firmware version:
[icasa dimmer subscribe crash.txt](https://github.com/Koenkk/zigbee2mqtt/files/3591917/icasa.dimmer.subscribe.crash.txt)

 20190619

**Comment by Koenkk** [comment]
Hi rutger,

Could you switch to the dev branch, it won't solve the issue but it will at least make it easier for me to do so. Afterwards we will continue with #1947.
