### ISSUE TITLE
EZSP Green Power Message deserialize crash

### ISSUE THREAD

**Issue by konistehrad** [Koenkk/zigbee2mqtt#19551]
### What happened?

I'm attempting to reverse the command structure of the Moes Self Powered Zigbee Scene Switch, and during some data collection I hit a cool crash bug in the EZSP stack. I'm gonna continue investigating this, but for now this'll serve as a tracking issue.

### What did you expect to happen?

Not crash, that for sure!

### How to reproduce it (minimal and precise)

Just spam one of the buttons on the Moes Self Powered Zigbee scene switch until it happens.

### Zigbee2MQTT version

1.33.2 

### Adapter firmware version

6.10.3.0 build 297

### Adapter

EZSP v8

### Debug log

RangeError: Attempt to access memory outside buffer bounds
    at new NodeError (node:internal/errors:405:5)
    at boundsError (node:internal/buffer:86:11)
    at Buffer.readUInt8 (node:internal/buffer:254:5)
    at Buffer.readUIntLE (node:internal/buffer:184:17)
    at Function.deserialize (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/types/basic.ts:19:67)
    at Driver.handleGPMessage (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:707:40)
    at Driver.handleFrame (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:361:18)
    at Ezsp.emit (node:events:517:28)
    at Ezsp.onFrameReceived (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:340:28)
    at SerialDriver.emit (node:events:517:28)

**Comment by konistehrad** [comment]
The root cause is the `frame.gpdCommandId == 0xE0` test in `driver.ts`, which apparently the Moes Self Powered Scene Switch will sometimes emit outside of a commissioning process.

**Comment by konistehrad** [comment]
A couple notes as I dig in:
- This device clearly uses ZGP encryption. I evaluated hundreds of packets and there’s no clear pattern in the command ID. (I had initially wondered if it was using the frame counter as a nonce for error checking. It’s not.)
- The driver does not check to ensure it’s in commissioning mode before trying to register the device in the event that it receives a 0xE0. 
- The driver doesn’t seem to handle encryption paths. I’ll investigate expanding this as part of more robust ZGP handling.
