### ISSUE TITLE
Does not start from Docker in Unraid.

### ISSUE THREAD

**Issue by madmax5900** [Koenkk/zigbee2mqtt#19611]
### What happened?

Hello!

Unfortunately I don't know what exactly I'm doing wrong. I want to use zigbee2mqtt in Docker under Unraid.

After starting I get the following error message.

Zigbee2MQTT:info 2023-11-07 14:11:08: Logging to console and directory: '/app/data/log/2023-11-07.14-11-08' filename: log.txt
Zigbee2MQTT:info 2023-11-07 14:11:08: Starting Zigbee2MQTT version 1.33.2 (commit #9996c93)
Zigbee2MQTT:info 2023-11-07 14:11:08: Starting zigbee-herdsman (0.21.0)
Zigbee2MQTT:error 2023-11-07 14:11:28: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-11-07 14:11:28: Failed to start zigbee
Zigbee2MQTT:error 2023-11-07 14:11:28: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-11-07 14:11:28: Exiting...
Zigbee2MQTT:error 2023-11-07 14:11:28: Error: Connection not initialized
     at Ezsp.execCommand (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:551:19)
     at Ezsp.version (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:349:35)
     at Driver.startup (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:140:25)
     at EZSPAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:172:16)
     at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
     at Zigbee.start (/app/lib/zigbee.ts:60:27)
     at Controller.start (/app/lib/controller.ts:101:27)
     at start (/app/index.js:107:5)

I hope that can help me with what I'm doing wrong.

Here is also my configuration.yaml file.
As a dongle I use a Sonoff Zigbee Dongle-E.

Maybe someone can help me.
<img width="1045" alt="Bildschirmfoto 2023-11-07 um 14 16 43" src="https://github.com/Koenkk/zigbee2mqtt/assets/103837959/8b8ef824-8da9-409e-a0d1-0476eebd21f0">

### What did you expect to happen?

Does not start from Docker in Unraid.

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

202112

### Adapter

Sonoff Zigbee Dongle-E

**Comment by rbrowning85** [comment]
I am having the exact same issue. Any help would be greatly appreciated.
