### ISSUE TITLE
Tuya TS004F  (_TZ3000_xabckq1v) is always disappearing from network

### ISSUE THREAD

**Issue by ikarisan** [Koenkk/zigbee2mqtt#19712]
### What happened?

Hi!

One of my Tuya TS004F  (4x buttons) device is always disappearing from network every few days. 

Than I have to rejoin the switch the network and everything works fine, again. No need to rename or reconfigure the device.
I think this has only happened since I started using a "SONOFF Zigbee 3.0 USB Dongle Plus" as a coordinator. 

### What did you expect to happen?

No disconnection

### How to reproduce it (minimal and precise)

Join the TS004F  to your network and wait a few days. 

### Zigbee2MQTT version

1.33.2-dev

### Adapter firmware version

20230507

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

**Comment by ikarisan** [comment]
Something similar happens with my Sonoff SNZB-04 window sensor. 
It works nice for a few days and then suddenly it is shown as "offline since x days". Then I have to allow joining of new devices and reset the sensor.

**Comment by ikarisan** [comment]
Very strange:

The payload.action of the TS004F should be one of 1_single, 1_double, 2_single, 2_double...
But zigbee2mqtt sends:

Button1 single click: "on"
Button1 double click: ---
Button2 single click: "undefined" followed by "brightness_step_up"
Button2 double click: "undefined" followed by "undefined"
Button3 single click: "off"
Button3 double click: ---
Button4 single click: brightness_step_up
Button4 double click: ---

This is the debug output for "button1 single click":

```
debug 2023-11-19 14:09:11Received Zigbee message from 'TuYa_Vierfach_Schalter', type 'commandOn', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0
info 2023-11-19 14:09:11MQTT publish: topic 'zigbee2mqtt/TuYa_Vierfach_Schalter', payload '{"action":"on","battery":100,"device":{"applicationVersion":65,"dateCode":"","friendlyName":"TuYa_Vierfach_Schalter","hardwareVersion":1,"ieeeAddr":"0x84fd27fffe8d3e0c","manufacturerID":4098,"manufacturerName":"_TZ3000_xabckq1v","model":"TS004F","networkAddress":30763,"powerSource":"Battery","stackVersion":0,"type":"EndDevice","zclVersion":3},"last_seen":"2023-11-19T14:09:10+01:00","linkquality":3,"operation_mode":"event","voltage":3000}'
```

**Comment by ikarisan** [comment]
After updating to 1.33.2-dev commit: [fd19c86] (https://github.com/Koenkk/zigbee2mqtt/commit/fd19c86) the switch seems to work again.

**Comment by ikarisan** [comment]
I rejoiced too soon. After just two hours, the switch no longer works, but it still appears in the list of devices. After clicking on "reconfigure" the folowing happens:
```

Received Zigbee message from 'TuYa_Zweifach_Schalter', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200,"batteryVoltage":30}' from endpoint 1 with groupID 0
info 2023-11-19 16:10:52MQTT publish: topic 'zigbee2mqtt/TuYa_Zweifach_Schalter', payload '{"battery":100,"device":{"applicationVersion":66,"friendlyName":"TuYa_Zweifach_Schalter","ieeeAddr":"0x943469fffecea5aa","manufacturerID":4098,"manufacturerName":"_TZ3000_dfgbtub0","model":"TS0042","networkAddress":36308,"powerSource":"Battery","type":"EndDevice","zclVersion":3},"last_seen":"2023-11-19T16:10:51+01:00","linkquality":83,"voltage":3000}'
debug 2023-11-19 16:12:34Received MQTT message on 'zigbee2mqtt/bridge/request/device/configure' with data '{"id":"TuYa_Vierfach_Schalter2","transaction":"hj0jb-2"}'
info 2023-11-19 16:12:34Configuring 'TuYa_Vierfach_Schalter2'
error 2023-11-19 16:12:59Failed to configure 'TuYa_Vierfach_Schalter2', attempt 1 (Error: Read 0x5c0272fffe050e42/1 genBasic([4,0,1,5,7,65534], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205)) at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23) at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32))
info 2023-11-19 16:12:59MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"TuYa_Vierfach_Schalter2"},"error":"Failed to configure (Read 0x5c0272fffe050e42/1 genBasic([4,0,1,5,7,65534], {\"sendWhen\":\"immediate\",\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Data request failed with error: 'No network route' (205)))","status":"error","transaction":"hj0jb-2"}'
debug 2023-11-19 16:13:14Saving state to file /app/data/state.json
```

d

**Comment by ikarisan** [comment]
I rejoiced too soon. After just two hours, the switch no longer works and disappeared from the list of devices. It is no longer in the database.db but still in state.json. 

state.json:
```
"0x84fd27fffe8d3e0c": {
        "battery": 100,
        "voltage": 3000,
        "last_seen": "2023-11-19T14:16:27+01:00",
        "linkquality": 21,
        "operation_mode": "event"
    },

```
