### ISSUE TITLE
Zigbee2MQTT fails to start

### ISSUE THREAD

**Issue by masp31** [Koenkk/zigbee2mqtt#19717]
### What happened?

Hi

I have pass code inside and now i cant start the zigbee2mqtt add-on. I have already reinstall but nothing.

### What did you expect to happen?

How to remove the add code? thank you

### How to reproduce it (minimal and precise)

I have introduce this italic code (log) on the the text frame external

### Zigbee2MQTT version

1.22.1

### Adapter firmware version

dont know

### Adapter

Snooff zigbee 3.0 dongle +

### Debug log

19:36:21] INFO: Preparing to start...
[19:36:22] INFO: Socat not enabled
[19:36:22] INFO: Zigbee Herdsman debug logging enabled
[19:36:23] INFO: Starting Zigbee2MQTT...
Error: Cannot find module '**_const fz = require('zigbee-herdsman-converters/converters/fromZigbee'); const tz = require('zigbee-herdsman-converters/converters/toZigbee'); const exposes = require('zigbee-herdsman-converters/lib/exposes'); const reporting = require('zigbee-herdsman-converters/lib/reporting'); const extend = require('zigbee-herdsman-converters/lib/extend'); const e = exposes.presets; const ea = exposes.access; const tuya = require('zigbee-herdsman-converters/lib/tuya');  const definition = {     fingerprint: tuya.fingerprint('TS0601', ['_TZE200_rjxqso4a']),     model: 'ZSS-HM-CO',     vendor: 'Moes',     description: 'Carbon Monoxide Alarm',     fromZigbee: [tuya.fz.datapoints],     toZigbee: [tuya.tz.datapoints],     configure: tuya.configureMagicPacket,     exposes: [         /* DP  1 */ e.carbon_monoxide(),         /* DP  2 */ e.co(),         /* DP  9 */ tuya.exposes.selfTestResult(),         /* DP 15 */ e.battery(),         /* DP 16 */ tuya.exposes.silence()     ],     meta: {         tuyaDatapoints: [             [1, 'carbon_monoxide', tuya.valueConverter.trueFalse0],             [2, 'co', tuya.valueConverter.raw],             [9, 'self_test_result', tuya.valueConverter.selfTestResult],             [15, 'battery', tuya.valueConverter.raw],             [16, 'silence', tuya.valueConverter.raw]         ]     } };  module.exports = definition;_**'
Require stack:
- /app/dist/util/utils.js
- /app/dist/util/settings.js
- /app/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.getExternalConvertersDefinitions (/app/lib/util/utils.ts:173:25)
    at getExternalConvertersDefinitions.next (<anonymous>)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:12:20)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)

**Comment by masp31** [comment]
I have found. Thank you
