### ISSUE TITLE
Unable to pair Ikea E1743

### ISSUE THREAD

**Issue by ra-kal** [Koenkk/zigbee2mqtt#19743]
### What happened?

I decided to change Zigbee channel from 11 to 25 and also change the network key to hopefully improve network stability.

I have two Ikea buttons E1743. Both fail to pair with error "Failed to interview 'xxx', device has not successfully been paired"

Both buttons were previously updated to latest version 24.4.6

### What did you expect to happen?

To pair successfully

### How to reproduce it (minimal and precise)

Change Zigbee channel and repair devices.

### Zigbee2MQTT version

1.33.2

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Sonoff Zigbee Dongle E

### Debug log

Not exactly debug log. I will attach once it is ne
Error 2023-11-17 14:01:04Failed to interview 'IKEA tlačítko 1', device has not successfully been paired
Error 2023-11-17 14:01:20Failed to configure 'IKEA tlačítko 1', attempt 1 (Error: Bind 0xdc8e95fffe2e2f8d/1 genOnOff from '0x84b4dbfffefcf9b8/1' failed ({"address":3111,"clusterId":32801,"sequence":179} after 10000ms) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7))
Error 2023-11-17 14:09:05Failed to interview '0x70ac08fffeb3b850', device has not successfully been paired
Error 2023-11-17 14:09:50Failed to interview '0x70ac08fffeb3b850', device has not successfully been paired
Error 2023-11-17 14:11:24Failed to configure '0x70ac08fffeb3b850', attempt 1 (TypeError: Cannot read properties of undefined (reading 'split') at Object.configureRemote [as configure] (/app/node_modules/zigbee-herdsman-converters/src/devices/ikea.ts:70:44) at Configure.configure (/app/lib/extension/configure.ts:117:37) at EventEmitter.<anonymous> (/app/lib/extension/configure.ts:81:62) at EventEmitter.emit (node:events:525:35) at EventBus.emitDeviceInterview (/app/lib/eventBus.ts:74:22) at Controller.<anonymous> (/app/lib/zigbee.ts:88:27) at Controller.emit (node:events:513:28) at Controller.selfAndDeviceEmit (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:527:14) at Controller.onDeviceJoined (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:582:22))
Error 2023-11-17 14:12:15Failed to interview '0x70ac08fffeb3b850', device has not successfully been paired

**Comment by ra-kal** [comment]
UPDATE: After many more attempts the pairing finally finished.
