### ISSUE TITLE
PROBLEMS DETECTED - RangeError [ERR_OUT_OF_RANGE] and AssertionError [ERR_ASSERTION]:

### ISSUE THREAD

**Issue by ccorderod** [Koenkk/zigbee2mqtt#1976]
# Bug Report 
## What happened

PROBLEM DETECTED
Please create an issue here with the contents of below: https://github.com/koenkk/zigbee2mqtt/issues
===== Stack =====
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 16. Received 17
    at boundsError (internal/buffer.js:49:9)
    at Buffer.readUInt8 (internal/buffer.js:137:5)
    at BuffaloZcl.readUInt8 (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/buffalo/buffalo.js:34:35)
    at BuffaloZcl.read (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/buffalo/buffalo.js:264:25)
    at BuffaloZcl.read (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/zcl/buffaloZcl.js:263:26)
    at BuffaloZcl.readUseDataType (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/zcl/buffaloZcl.js:45:21)
    at BuffaloZcl.read (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/zcl/buffaloZcl.js:226:25)
    at Function.parsePayloadGlobal (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/zcl/zclFrame.js:198:53)
    at Function.parsePayload (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/zcl/zclFrame.js:150:25)
    at Function.fromBuffer (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/zcl/zclFrame.js:129:30)
===== Buffer =====
{ type: 'Buffer',
  data: [ 24, 45, 1, 7, 0, 0, 48, 1, 16, 0, 0, 66, 0, 18, 0, 0, 16 ] }
===== Arguments =====
<Buffer 18 2d 01 07 00 00 30 01 10 00 00 42 00 12 00 00 10> 0
===== zcl-packet parse =====
undefined
===== zcl =====
undefined
===============

PROBLEM DETECTED
Please create an issue here with the contents of below: https://github.com/koenkk/zigbee2mqtt/issues
===== Stack =====
AssertionError [ERR_ASSERTION]: { frameCntl:
   { frameType: 0, manufSpec: 0, direction: 1, disDefaultRsp: 1 },
  manufCode: null,
  seqNum: 45,
  cmdId: 1 } deepEqual undefined
    at Object.header (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/lib/components/zcl.js:93:20)
    at dispatchIncomingMsg (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/lib/components/af.js:528:29)
    at Controller.incomingMsgHandler (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/lib/components/af.js:625:12)
    at Controller.emit (events.js:198:13)
    at Object.bridge._areqEventBridge (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/lib/components/event_bridge.js:11:16)
    at Znp.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/lib/components/controller.js:104:20)
    at Znp.emit (events.js:198:13)
    at Znp.onUnpiParsed (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/znp/znp.js:72:18)
    at Parser.emit (events.js:198:13)
    at Parser.parseNext (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/unpi/parser.js:39:26)
===== Arguments =====
<Buffer 18 2d 01 07 00 00 30 01 10 00 00 42 00 12 00 00 10> 0
===== Buffer =====
{ type: 'Buffer',
  data: [ 24, 45, 1, 7, 0, 0, 48, 1, 16, 0, 0, 66, 0, 18, 0, 0, 16 ] }
===== zcl-packet header =====
{"frameCntl":{"frameType":0,"manufSpec":0,"direction":1,"disDefaultRsp":1},"manufCode":null,"seqNum":45,"cmdId":1}
===== zcl header =====
undefined
===============

## How to reproduce it (minimal and precise)
This happen pairing meazon plug
## Debug Info
zigbee2mqtt version: zigbee2mqtt version 1.6.0 (commit #e26ad2a)
CC253X firmware version: source routing CC2531 20190619

**Comment by Koenkk** [comment]
Can you check if this device pairs correctly in the dev branch?
