### ISSUE TITLE
Log message on unsupported cid crash

### ISSUE THREAD

**Issue by tb-killa** [Koenkk/zigbee2mqtt#199]
@Koenkk 
```
                    `type '${message.type}' and message '${JSON.stringify(message)}'`
                                                                ^

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Controller.handleZigbeeMessage (/opt/zigbee2mqtt/lib/controller.js:286:65)
    at Zigbee.handleMessage (/opt/zigbee2mqtt/lib/zigbee.js:157:18)
    at emitOne (events.js:116:13)
    at ZShepherd.emit (events.js:211:7)
    at ZShepherd.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-shepherd/lib/shepherd.js:159:14)
    at emitThree (events.js:136:13)
    at ZShepherd.emit (events.js:217:7)
    at dispatchIncomingMsg (/opt/zigbee2mqtt/node_modules/zigbee-shepherd/lib/components/af.js:669:45)
    at Controller.zclIncomingMsgHandler (/opt/zigbee2mqtt/node_modules/zigbee-shepherd/lib/components/af.js:730:12)
```

**Comment by tb-killa** [comment]
Shouldn´t it be this ?

```
if (!converters.length) {
            if (cid) {
                logger.warn(
                    `No converter available for '${mappedModel.model}' with cid '${cid}', ` +
                    `type '${message.type}' and message '${JSON.stringify(message.data)}'`
                );
            } else if (cmdId) {
                logger.warn(
                    `No converter available for '${mappedModel.model}' with cmd '${cmdId}' ` +
                    `and message '${JSON.stringify(message.data)}'`
                );
            }

            logger.warn(`Please see: https://github.com/Koenkk/zigbee2mqtt/wiki/How-to-support-new-devices.`);
            return;
        }
```

**Comment by Koenkk** [comment]
Thanks, fixed!
