### ISSUE TITLE
[SONOFF zigbee 3.0 usb dongle plus P][Docker] Error while starting zigbee-herdsman

### ISSUE THREAD

**Issue by kaysan13** [Koenkk/zigbee2mqtt#19921]
### What happened?

When I try to start my container with fresh install i have this error

Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby

### What did you expect to happen?

configuration.yaml

homeassistant: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://xxx.xxx.xxx.xxx:xxxx
  user: 
  password: 
  keepalive: 60
serial:
  port: /dev/ttyACM0
frontend:
  port: xxxx
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  timestamp_format: DD-MM-YYYY HH:mm:ss
  pan_id: GENERATE
  ext_pan_id: [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08]
  network_key: GENERATE
device_options:
  legacy: false
permit_join: false

### Zigbee2MQTT version

1.33.2-dev

### Adapter firmware version

CC1352P2_CC2652P_launchpad_coordinator_20221226

### Adapter

sonoff zigbee 3.0 usb dongle plus P

### Debug log

info  29-11-2023 21:05:54: Logging to console and directory: '/app/data/log/2023-11-29.21-05-54' filename: log.txt
info  29-11-2023 21:05:54: Starting Zigbee2MQTT version 1.33.2-dev (commit #4e128e2)
info  29-11-2023 21:05:54: Starting zigbee-herdsman (0.23.0)
error 29-11-2023 21:07:01: Error while starting zigbee-herdsman
error 29-11-2023 21:07:01: Failed to start zigbee
error 29-11-2023 21:07:01: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 29-11-2023 21:07:01: Exiting...
error 29-11-2023 21:07:01: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:347:23)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:92:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:60:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)

**Comment by kaysan13** [comment]
I solved my problem
I have an HUE bridge and he works on the same channel just switch to channel 25 [(don't forget)](https://github.com/Koenkk/zigbee2mqtt/discussions/13242)
