### ISSUE TITLE
Error: Can't insert key 1, it violates the unique constraint

### ISSUE THREAD

**Issue by Zerosoul303** [Koenkk/zigbee2mqtt#1993]
i Installing zigbee2mqtt but i usually dispaly error log, plz check help me . this zigbee2mqtt version 1.60 and usb zigbee CC2531
This is log : 
./run.sh: line 16: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
2019-09-18T22:33:22: PM2 log: Launching in no daemon mode
2019-09-18T22:33:22: PM2 log: App [npm:0] starting in -fork mode-
2019-09-18T22:33:23: PM2 log: App [npm:0] online
> zigbee2mqtt@1.6.0 start /zigbee2mqtt-1.6.0
> node index.js
  zigbee2mqtt:info 9/18/2019, 10:33:28 PM Logging to directory: '/share/zigbee2mqtt/log/2019-09-18.22-33-26'
  zigbee2mqtt:info 9/18/2019, 10:33:28 PM Starting zigbee2mqtt version 1.6.0 (commit #unknown)
  zigbee2mqtt:info 9/18/2019, 10:33:28 PM Starting zigbee-shepherd
/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/nedb/lib/datastore.js:77
    if (err) { throw err; }
               ^
Error: Can't insert key 1, it violates the unique constraint
    at _AVLTree.insert (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/binary-search-tree/lib/avltree.js:273:19)
    at AVLTree.insert (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/binary-search-tree/lib/avltree.js:307:27)
    at Index.insert (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/nedb/lib/indexes.js:77:15)
    at Index.insertMultipleDocs (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/nedb/lib/indexes.js:114:12)
    at Index.insert (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/nedb/lib/indexes.js:69:33)
    at Index.reset (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/nedb/lib/indexes.js:55:23)
    at /zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/nedb/lib/datastore.js:107:21
    at Array.forEach (<anonymous>)
    at Datastore.resetIndexes (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/nedb/lib/datastore.js:106:29)
    at /zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/nedb/lib/persistence.js:293:23
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.6.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-18T15_33_28_743Z-debug.log
2019-09-18T22:33:28: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2019-09-18T22:33:28: PM2 log: App [npm:0] starting in -fork mode-
2019-09-18T22:33:28: PM2 log: App [npm:0] online

**Comment by Koenkk** [comment]
Can you try with the edge version?
