### ISSUE TITLE
Cannot change operation_mode on Aqara Switches in dev branch

### ISSUE THREAD

**Issue by pusheax0** [Koenkk/zigbee2mqtt#20053]
### What happened?

Aqara opple switches do not switch into decoupled mode on dev branch

### What did you expect to happen?

switches to work

### How to reproduce it (minimal and precise)

add aqara opple switch

### Zigbee2MQTT version

1.34.0-dev (commit #299b37a7)

### Adapter firmware version

Latest

### Adapter

SONOFF ZBDongle-E and SONOFF ZBDongle-P 

### Debug log

<img width="948" alt="about" src="https://github.com/Koenkk/zigbee2mqtt/assets/127334508/8d450e41-b99f-4f05-9ab3-8ebca326f146">
<img width="1698" alt="log" src="https://github.com/Koenkk/zigbee2mqtt/assets/127334508/92dfcad4-5c60-4588-96f0-2ee2369d5f22">
<img width="927" alt="state" src="https://github.com/Koenkk/zigbee2mqtt/assets/127334508/34774405-0075-4233-b045-4260f6cae731">
<img width="1718" alt="switch" src="https://github.com/Koenkk/zigbee2mqtt/assets/127334508/1f62cccc-17aa-4ca9-b080-96a4f6d8ea77">

**Comment by pusheax0** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/converters/toZigbee.ts#L2503

**Comment by pusheax0** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/pull/6629

**Comment by pusheax0** [comment]
@Koenkk please look again for ``` xiaomi_switch_operation_mode_opple: {```

**Comment by Koenkk** [comment]
Could you provide the debug log when setting it fails?

See [this](https://www.zigbee2mqtt.io/guide/usage/debug.html) on how to enable debug logging.

**Comment by pusheax0** [comment]
```info  2023-12-05 14:52:56: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2023-12-05.14-52-56' filename: log.txt
info  2023-12-05 14:52:56: Starting Zigbee2MQTT version 1.34.0-dev (commit #cb74db47)
info  2023-12-05 14:52:56: Starting zigbee-herdsman (0.25.3)
info  2023-12-05 14:53:01: zigbee-herdsman started (reset)
info  2023-12-05 14:53:01: Coordinator firmware version: '{"meta":{"maintrel":"1 ","majorrel":"7","minorrel":"3","product":12,"revision":"7.3.1.0 build 176"},"type":"EZSP v12"}'
info  2023-12-05 14:53:01: Currently 0 devices are joined:
info  2023-12-05 14:53:01: Zigbee: disabling joining new devices.
info  2023-12-05 14:53:01: Connecting to MQTT server at mqtt://localhost
info  2023-12-05 14:53:01: Connected to MQTT server
info  2023-12-05 14:53:01: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"online"}'
info  2023-12-05 14:53:01: Started frontend on port 8080
info  2023-12-05 14:53:01: Zigbee2MQTT started!
info  2023-12-05 14:53:47: Successfully changed options
info  2023-12-05 14:53:47: MQTT publish: topic 'zigbee2mqtt/bridge/response/options', payload '{"data":{"restart_required":false},"status":"ok","transaction":"1o984-1"}'
debug 2023-12-05 14:53:58: Received MQTT message on 'zigbee2mqtt/bridge/request/options' with data '{"options":{"permit_join":true},"transaction":"1o984-2"}'
info  2023-12-05 14:53:58: Zigbee: allowing new devices to join.
debug 2023-12-05 14:53:58: Received Zigbee message from 'Coordinator', type 'commandNotification', cluster 'greenPower', data '{"data":[25,3,2,11,254,0],"type":"Buffer"}' from endpoint 242 with groupID null, ignoring since it is from coordinator
info  2023-12-05 14:53:59: Successfully changed options
info  2023-12-05 14:53:59: MQTT publish: topic 'zigbee2mqtt/bridge/response/options', payload '{"data":{"restart_required":false},"status":"ok","transaction":"1o984-2"}'
info  2023-12-05 14:54:42: Device '0x54ef4410009905c4' joined
info  2023-12-05 14:54:42: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x54ef4410009905c4","ieee_address":"0x54ef4410009905c4"},"type":"device_joined"}'
info  2023-12-05 14:54:42: Starting interview of '0x54ef4410009905c4'
info  2023-12-05 14:54:42: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x54ef4410009905c4","ieee_address":"0x54ef4410009905c4","status":"started"},"type":"device_interview"}'
debug 2023-12-05 14:54:42: Received Zigbee message from '0x54ef4410009905c4', type 'readResponse', cluster 'genBasic', data '{"modelId":"lumi.switch.b2naus01"}' from endpoint 1 with groupID 0
debug 2023-12-05 14:54:42: Skipping message, definition is undefined and still interviewing
debug 2023-12-05 14:54:42: Received Zigbee message from '0x54ef4410009905c4', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"LUMI"}' from endpoint 1 with groupID 0
debug 2023-12-05 14:54:42: Skipping message, definition is undefined and still interviewing
debug 2023-12-05 14:54:42: Received Zigbee message from '0x54ef4410009905c4', type 'readResponse', cluster 'genBasic', data '{"powerSource":1}' from endpoint 1 with groupID 0
debug 2023-12-05 14:54:42: Skipping message, definition is undefined and still interviewing
debug 2023-12-05 14:54:42: Received Zigbee message from '0x54ef4410009905c4', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
debug 2023-12-05 14:54:42: Skipping message, definition is undefined and still interviewing
debug 2023-12-05 14:54:42: Received Zigbee message from '0x54ef4410009905c4', type 'readResponse', cluster 'genBasic', data '{"appVersion":31}' from endpoint 1 with groupID 0
debug 2023-12-05 14:54:42: Skipping message, definition is undefined and still interviewing
debug 2023-12-05 14:54:42: Received Zigbee message from '0x54ef4410009905c4', type 'readResponse', cluster 'genBasic', data '{"stackVersion":2}' from endpoint 1 with groupID 0
debug 2023-12-05 14:54:42: Skipping message, definition is undefined and still interviewing
debug 2023-12-05 14:54:42: Received Zigbee message from '0x54ef4410009905c4', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID 0
debug 2023-12-05 14:54:42: Skipping message, definition is undefined and still interviewing
debug 2023-12-05 14:54:42: Received Zigbee message from '0x54ef4410009905c4', type 'readResponse', cluster 'genBasic', data '{"dateCode":"12-28-2021"}' from endpoint 1 with groupID 0
debug 2023-12-05 14:54:42: Skipping message, definition is undefined and still interviewing
debug 2023-12-05 14:54:42: Received Zigbee message from '0x54ef4410009905c4', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0
debug 2023-12-05 14:54:42: Skipping message, definition is undefined and still interviewing
debug 2023-12-05 14:54:42: Received Zigbee message from '0x54ef4410009905c4', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 2 with groupID 0
debug 2023-12-05 14:54:42: Skipping message, definition is undefined and still interviewing
info  2023-12-05 14:54:42: Successfully interviewed '0x54ef4410009905c4', device has successfully been paired
info  2023-12-05 14:54:42: Device '0x54ef4410009905c4' is supported, identified as: Xiaomi Aqara smart wall switch (neutral, double rocker) (WS-USC04)
info  2023-12-05 14:54:43: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Aqara smart wall switch (neutral, double rocker)","exposes":[{"endpoint":"top","features":[{"access":7,"description":"On/off state of the switch","endpoint":"top","label":"State","name":"state","property":"state_top","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"}],"type":"switch"},{"endpoint":"bottom","features":[{"access":7,"description":"On/off state of the switch","endpoint":"bottom","label":"State","name":"state","property":"state_bottom","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"}],"type":"switch"},{"access":7,"description":"Decoupled mode for top button","endpoint":"top","label":"Operation mode","name":"operation_mode","property":"operation_mode_top","type":"enum","values":["control_relay","decoupled"]},{"access":7,"description":"Decoupled mode for bottom button","endpoint":"bottom","label":"Operation mode","name":"operation_mode","property":"operation_mode_bottom","type":"enum","values":["control_relay","decoupled"]},{"access":1,"description":"Number of power outages (since last pairing)","label":"Power outage count","name":"power_outage_count","property":"power_outage_count","type":"numeric"},{"access":1,"description":"Temperature of the device","label":"Device temperature","name":"device_temperature","property":"device_temperature","type":"numeric","unit":"°C"},{"access":7,"description":"After turn on, the indicator light turns on while switch is off, and vice versa","label":"Flip indicator light","name":"flip_indicator_light","property":"flip_indicator_light","type":"binary","value_off":"OFF","value_on":"ON"},{"access":5,"description":"Instantaneous measured power","label":"Power","name":"power","property":"power","type":"numeric","unit":"W"},{"access":1,"description":"Sum of consumed energy","label":"Energy","name":"energy","property":"energy","type":"numeric","unit":"kWh"},{"access":1,"description":"Measured electrical potential value","label":"Voltage","name":"voltage","property":"voltage","type":"numeric","unit":"V"},{"access":7,"description":"Enable/disable the power outage memory, this recovers the on/off mode after power failure","label":"Power outage memory","name":"power_outage_memory","property":"power_outage_memory","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Triggered action (e.g. a button click)","label":"Action","name":"action","property":"action","type":"enum","values":["single_top","single_bottom","single_both","double_top","double_bottom","double_both"]},{"access":1,"description":"Link quality (signal strength)","label":"Linkquality","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"WS-USC04","options":[{"access":2,"description":"State actions will also be published as 'action' when true (default false).","label":"State action","name":"state_action","property":"state_action","type":"binary","value_off":false,"value_on":true},{"access":2,"description":"Calibrates the power value (percentual offset), takes into effect on next report of device.","label":"Power calibration","name":"power_calibration","property":"power_calibration","type":"numeric"},{"access":2,"description":"Number of digits after decimal point for power, takes into effect on next report of device.","label":"Power precision","name":"power_precision","property":"power_precision","type":"numeric","value_max":3,"value_min":0},{"access":2,"description":"Calibrates the device_temperature value (absolute offset), takes into effect on next report of device.","label":"Device temperature calibration","name":"device_temperature_calibration","property":"device_temperature_calibration","type":"numeric"},{"access":2,"description":"Calibrates the energy value (percentual offset), takes into effect on next report of device.","label":"Energy calibration","name":"energy_calibration","property":"energy_calibration","type":"numeric"},{"access":2,"description":"Number of digits after decimal point for energy, takes into effect on next report of device.","label":"Energy precision","name":"energy_precision","property":"energy_precision","type":"numeric","value_max":3,"value_min":0},{"access":2,"description":"Calibrates the voltage value (percentual offset), takes into effect on next report of device.","label":"Voltage calibration","name":"voltage_calibration","property":"voltage_calibration","type":"numeric"},{"access":2,"description":"Number of digits after decimal point for voltage, takes into effect on next report of device.","label":"Voltage precision","name":"voltage_precision","property":"voltage_precision","type":"numeric","value_max":3,"value_min":0}],"supports_ota":true,"vendor":"Xiaomi"},"friendly_name":"0x54ef4410009905c4","ieee_address":"0x54ef4410009905c4","status":"successful","supported":true},"type":"device_interview"}'
info  2023-12-05 14:54:43: Configuring '0x54ef4410009905c4'
info  2023-12-05 14:54:43: Successfully configured '0x54ef4410009905c4'
debug 2023-12-05 14:54:43: Received Zigbee message from '0x54ef4410009905c4', type 'attributeReport', cluster 'aqaraOpple', data '{"247":{"data":[100,16,0,101,16,0,3,40,30,152,57,0,0,0,0,150,57,0,0,0,0,151,57,0,0,0,0,5,33,1,0,154,32,16,8,33,31,1,9,33,0,1,11,32,0,10,33,0,0,12,32,1],"type":"Buffer"}}' from endpoint 1 with groupID 0
debug 2023-12-05 14:54:43: WS-USC04: Processed buffer into data {"3":30,"5":1,"8":287,"9":256,"10":0,"11":0,"12":1,"100":0,"101":0,"150":0,"151":0,"152":0,"154":16}
debug 2023-12-05 14:54:43: WS-USC04: Processed data into payload {"device_temperature":30,"power_outage_count":0,"state":"OFF","voltage":0,"current":0,"power":0}
debug 2023-12-05 14:54:43: WS-USC04: Processed data into payload {"device_temperature":30,"power_outage_count":0,"state":"OFF","voltage":0,"current":0,"power":0}
info  2023-12-05 14:54:43: MQTT publish: topic 'zigbee2mqtt/0x54ef4410009905c4', payload '{"current":0,"device_temperature":30,"linkquality":252,"power":0,"power_outage_count":0,"state":"OFF","voltage":0}'
debug 2023-12-05 14:54:43: Received Zigbee message from '0x54ef4410009905c4', type 'attributeReport', cluster 'genBasic', data '{"appVersion":31,"modelId":"lumi.switch.b2naus01"}' from endpoint 1 with groupID 0
debug 2023-12-05 14:54:44: Received Zigbee message from '0x54ef4410009905c4', type 'read', cluster 'genTime', data '["time","timeZone"]' from endpoint 1 with groupID 0
debug 2023-12-05 14:54:45: Received Zigbee message from '0x54ef4410009905c4', type 'attributeReport', cluster 'genBasic', data '{"appVersion":31}' from endpoint 1 with groupID 0
debug 2023-12-05 14:54:46: Received Zigbee message from '0x54ef4410009905c4', type 'attributeReport', cluster 'aqaraOpple', data '{"247":{"data":[100,16,0,101,16,0,3,40,18,152,57,0,0,0,0,150,57,0,0,0,0,151,57,0,0,0,0,5,33,1,0,154,32,0,8,33,31,1,9,33,0,1,11,32,0,10,33,0,0,12,32,1],"type":"Buffer"}}' from endpoint 1 with groupID 0
debug 2023-12-05 14:54:46: WS-USC04: Processed buffer into data {"3":18,"5":1,"8":287,"9":256,"10":0,"11":0,"12":1,"100":0,"101":0,"150":0,"151":0,"152":0,"154":0}
debug 2023-12-05 14:54:46: WS-USC04: Processed data into payload {"device_temperature":18,"power_outage_count":0,"state":"OFF","voltage":0,"current":0,"power":0}
debug 2023-12-05 14:54:46: WS-USC04: Processed data into payload {"device_temperature":18,"power_outage_count":0,"state":"OFF","voltage":0,"current":0,"power":0}
info  2023-12-05 14:54:46: MQTT publish: topic 'zigbee2mqtt/0x54ef4410009905c4', payload '{"current":0,"device_temperature":18,"linkquality":255,"power":0,"power_outage_count":0,"state":"OFF","voltage":0}'
debug 2023-12-05 14:54:47: Received Zigbee message from '0x54ef4410009905c4', type 'attributeReport', cluster 'genOnOff', data '{"245":50331392,"onOff":0}' from endpoint 1 with groupID 0
info  2023-12-05 14:54:47: MQTT publish: topic 'zigbee2mqtt/0x54ef4410009905c4', payload '{"current":0,"device_temperature":18,"linkquality":255,"power":0,"power_outage_count":0,"state":"OFF","state_top":"OFF","voltage":0}'
debug 2023-12-05 14:54:48: Received Zigbee message from '0x54ef4410009905c4', type 'attributeReport', cluster 'genOnOff', data '{"245":50331392,"onOff":0}' from endpoint 2 with groupID 0
info  2023-12-05 14:54:48: MQTT publish: topic 'zigbee2mqtt/0x54ef4410009905c4', payload '{"current":0,"device_temperature":18,"linkquality":252,"power":0,"power_outage_count":0,"state":"OFF","state_bottom":"OFF","state_top":"OFF","voltage":0}'
debug 2023-12-05 14:55:27: Received MQTT message on 'zigbee2mqtt/0x54ef4410009905c4/set' with data '{"flip_indicator_light":"ON"}'
debug 2023-12-05 14:55:27: Publishing 'set' 'flip_indicator_light' to '0x54ef4410009905c4'
info  2023-12-05 14:55:27: MQTT publish: topic 'zigbee2mqtt/0x54ef4410009905c4', payload '{"current":0,"device_temperature":18,"flip_indicator_light":"ON","linkquality":248,"power":0,"power_outage_count":0,"state":"OFF","state_bottom":"OFF","state_top":"OFF","voltage":0}'
debug 2023-12-05 14:55:27: Received Zigbee message from '0x54ef4410009905c4', type 'attributeReport', cluster 'aqaraOpple', data '{"240":1}' from endpoint 1 with groupID 0
debug 2023-12-05 14:55:27: WS-USC04: Processed data into payload {"flip_indicator_light":"ON"}
info  2023-12-05 14:55:27: MQTT publish: topic 'zigbee2mqtt/0x54ef4410009905c4', payload '{"current":0,"device_temperature":18,"flip_indicator_light":"ON","linkquality":248,"power":0,"power_outage_count":0,"state":"OFF","state_bottom":"OFF","state_top":"OFF","voltage":0}'
debug 2023-12-05 14:55:29: Received MQTT message on 'zigbee2mqtt/0x54ef4410009905c4/set' with data '{"power_outage_memory":true}'
debug 2023-12-05 14:55:29: Publishing 'set' 'power_outage_memory' to '0x54ef4410009905c4'
info  2023-12-05 14:55:30: MQTT publish: topic 'zigbee2mqtt/0x54ef4410009905c4', payload '{"current":0,"device_temperature":18,"flip_indicator_light":"ON","linkquality":248,"power":0,"power_outage_count":0,"power_outage_memory":true,"state":"OFF","state_bottom":"OFF","state_top":"OFF","voltage":0}'
debug 2023-12-05 14:55:30: Received Zigbee message from '0x54ef4410009905c4', type 'attributeReport', cluster 'aqaraOpple', data '{"513":1}' from endpoint 1 with groupID 0
debug 2023-12-05 14:55:30: WS-USC04: Processed data into payload {"power_outage_memory":true}
info  2023-12-05 14:55:30: MQTT publish: topic 'zigbee2mqtt/0x54ef4410009905c4', payload '{"current":0,"device_temperature":18,"flip_indicator_light":"ON","linkquality":252,"power":0,"power_outage_count":0,"power_outage_memory":true,"state":"OFF","state_bottom":"OFF","state_top":"OFF","voltage":0}'
debug 2023-12-05 14:55:32: Received MQTT message on 'zigbee2mqtt/0x54ef4410009905c4/set' with data '{"operation_mode_top":"decoupled"}'
debug 2023-12-05 14:55:32: Publishing 'set' 'operation_mode' to '0x54ef4410009905c4'
error 2023-12-05 14:55:32: Publish 'set' 'operation_mode' to '0x54ef4410009905c4' failed: 'Error: undefined is not a object, got string ("decoupled")'
debug 2023-12-05 14:55:33: Error: undefined is not a object, got string ("decoupled")
    at Object.assertObject (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:517:15)
    at Object.convertSet (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:2501:19)
    at Publish.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/publish.ts:249:52)
    at EventEmitter.emit (node:events:529:35)
    at EventBus.emitMQTTMessage (/opt/zigbee2mqtt/lib/eventBus.ts:109:22)
    at MQTT.onMessage (/opt/zigbee2mqtt/lib/mqtt.ts:141:27)
    at WebSocket.<anonymous> (/opt/zigbee2mqtt/lib/extension/frontend.ts:130:27)
    at WebSocket.emit (node:events:517:28)
    at Receiver.receiverOnMessage (/opt/zigbee2mqtt/node_modules/ws/lib/websocket.js:1192:20)
    at Receiver.emit (node:events:517:28)
debug 2023-12-05 14:55:39: Received MQTT message on 'zigbee2mqtt/0x54ef4410009905c4/set' with data '{"state_top":"ON"}'
debug 2023-12-05 14:55:39: Publishing 'set' 'state' to '0x54ef4410009905c4'
info  2023-12-05 14:55:39: MQTT publish: topic 'zigbee2mqtt/0x54ef4410009905c4', payload '{"current":0,"device_temperature":18,"flip_indicator_light":"ON","linkquality":255,"power":0,"power_outage_count":0,"power_outage_memory":true,"state":"OFF","state_bottom":"OFF","state_top":"ON","voltage":0}'
debug 2023-12-05 14:55:40: Received Zigbee message from '0x54ef4410009905c4', type 'attributeReport', cluster 'genOnOff', data '{"245":117440529,"onOff":1}' from endpoint 1 with groupID 0
info  2023-12-05 14:55:40: MQTT publish: topic 'zigbee2mqtt/0x54ef4410009905c4', payload '{"current":0,"device_temperature":18,"flip_indicator_light":"ON","linkquality":255,"power":0,"power_outage_count":0,"power_outage_memory":true,"state":"OFF","state_bottom":"OFF","state_top":"ON","voltage":0}'
debug 2023-12-05 14:55:41: Received MQTT message on 'zigbee2mqtt/0x54ef4410009905c4/set' with data '{"state_bottom":"ON"}'
debug 2023-12-05 14:55:41: Publishing 'set' 'state' to '0x54ef4410009905c4'
info  2023-12-05 14:55:41: MQTT publish: topic 'zigbee2mqtt/0x54ef4410009905c4', payload '{"current":0,"device_temperature":18,"flip_indicator_light":"ON","linkquality":255,"power":0,"power_outage_count":0,"power_outage_memory":true,"state":"OFF","state_bottom":"ON","state_top":"ON","voltage":0}'
debug 2023-12-05 14:55:42: Received Zigbee message from '0x54ef4410009905c4', type 'attributeReport', cluster 'genOnOff', data '{"245":117440530,"onOff":1}' from endpoint 2 with groupID 0
info  2023-12-05 14:55:42: MQTT publish: topic 'zigbee2mqtt/0x54ef4410009905c4', payload '{"current":0,"device_temperature":18,"flip_indicator_light":"ON","linkquality":240,"power":0,"power_outage_count":0,"power_outage_memory":true,"state":"OFF","state_bottom":"ON","state_top":"ON","voltage":0}'
debug 2023-12-05 14:55:45: Received MQTT message on 'zigbee2mqtt/0x54ef4410009905c4/set' with data '{"operation_mode_bottom":"decoupled"}'
debug 2023-12-05 14:55:45: Publishing 'set' 'operation_mode' to '0x54ef4410009905c4'
error 2023-12-05 14:55:45: Publish 'set' 'operation_mode' to '0x54ef4410009905c4' failed: 'Error: undefined is not a object, got string ("decoupled")'
debug 2023-12-05 14:55:45: Error: undefined is not a object, got string ("decoupled")
    at Object.assertObject (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:517:15)
    at Object.convertSet (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:2501:19)
    at Publish.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/publish.ts:249:52)
    at EventEmitter.emit (node:events:529:35)
    at EventBus.emitMQTTMessage (/opt/zigbee2mqtt/lib/eventBus.ts:109:22)
    at MQTT.onMessage (/opt/zigbee2mqtt/lib/mqtt.ts:141:27)
    at WebSocket.<anonymous> (/opt/zigbee2mqtt/lib/extension/frontend.ts:130:27)
    at WebSocket.emit (node:events:517:28)
    at Receiver.receiverOnMessage (/opt/zigbee2mqtt/node_modules/ws/lib/websocket.js:1192:20)
    at Receiver.emit (node:events:517:28)
debug 2023-12-05 14:55:47: Received MQTT message on 'zigbee2mqtt/0x54ef4410009905c4/set' with data '{"operation_mode_top":"control_relay"}'
debug 2023-12-05 14:55:47: Publishing 'set' 'operation_mode' to '0x54ef4410009905c4'
error 2023-12-05 14:55:47: Publish 'set' 'operation_mode' to '0x54ef4410009905c4' failed: 'Error: undefined is not a object, got string ("control_relay")'
debug 2023-12-05 14:55:47: Error: undefined is not a object, got string ("control_relay")
    at Object.assertObject (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:517:15)
    at Object.convertSet (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:2501:19)
    at Publish.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/publish.ts:249:52)
    at EventEmitter.emit (node:events:529:35)
    at EventBus.emitMQTTMessage (/opt/zigbee2mqtt/lib/eventBus.ts:109:22)
    at MQTT.onMessage (/opt/zigbee2mqtt/lib/mqtt.ts:141:27)
    at WebSocket.<anonymous> (/opt/zigbee2mqtt/lib/extension/frontend.ts:130:27)
    at WebSocket.emit (node:events:517:28)
    at Receiver.receiverOnMessage (/opt/zigbee2mqtt/node_modules/ws/lib/websocket.js:1192:20)
    at Receiver.emit (node:events:517:28)
debug 2023-12-05 14:55:49: Received MQTT message on 'zigbee2mqtt/0x54ef4410009905c4/get' with data '{"operation_mode_top":""}'
debug 2023-12-05 14:55:49: Publishing get 'get' 'operation_mode' to '0x54ef4410009905c4'
debug 2023-12-05 14:55:49: Received Zigbee message from '0x54ef4410009905c4', type 'readResponse', cluster 'aqaraOpple', data '{"512":1}' from endpoint 1 with groupID 0
debug 2023-12-05 14:55:49: WS-USC04: Processed data into payload {"operation_mode_top":"control_relay"}
info  2023-12-05 14:55:49: MQTT publish: topic 'zigbee2mqtt/0x54ef4410009905c4', payload '{"current":0,"device_temperature":18,"flip_indicator_light":"ON","linkquality":240,"operation_mode_top":"control_relay","power":0,"power_outage_count":0,"power_outage_memory":true,"state":"OFF","state_bottom":"ON","state_top":"ON","voltage":0}'
debug 2023-12-05 14:55:52: Received MQTT message on 'zigbee2mqtt/0x54ef4410009905c4/set' with data '{"operation_mode_top":"decoupled"}'
debug 2023-12-05 14:55:52: Publishing 'set' 'operation_mode' to '0x54ef4410009905c4'
error 2023-12-05 14:55:52: Publish 'set' 'operation_mode' to '0x54ef4410009905c4' failed: 'Error: undefined is not a object, got string ("decoupled")'
debug 2023-12-05 14:55:52: Error: undefined is not a object, got string ("decoupled")
    at Object.assertObject (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:517:15)
    at Object.convertSet (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:2501:19)
    at Publish.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/publish.ts:249:52)
    at EventEmitter.emit (node:events:529:35)
    at EventBus.emitMQTTMessage (/opt/zigbee2mqtt/lib/eventBus.ts:109:22)
    at MQTT.onMessage (/opt/zigbee2mqtt/lib/mqtt.ts:141:27)
    at WebSocket.<anonymous> (/opt/zigbee2mqtt/lib/extension/frontend.ts:130:27)
    at WebSocket.emit (node:events:517:28)
    at Receiver.receiverOnMessage (/opt/zigbee2mqtt/node_modules/ws/lib/websocket.js:1192:20)
    at Receiver.emit (node:events:517:28)
debug 2023-12-05 14:55:58: Received MQTT message on 'zigbee2mqtt/0x54ef4410009905c4/set' with data '{"operation_mode_top":"control_relay"}'
debug 2023-12-05 14:55:58: Publishing 'set' 'operation_mode' to '0x54ef4410009905c4'
error 2023-12-05 14:55:58: Publish 'set' 'operation_mode' to '0x54ef4410009905c4' failed: 'Error: undefined is not a object, got string ("control_relay")'
debug 2023-12-05 14:55:58: Error: undefined is not a object, got string ("control_relay")
    at Object.assertObject (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:517:15)
    at Object.convertSet (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:2501:19)
    at Publish.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/publish.ts:249:52)
    at EventEmitter.emit (node:events:529:35)
    at EventBus.emitMQTTMessage (/opt/zigbee2mqtt/lib/eventBus.ts:109:22)
    at MQTT.onMessage (/opt/zigbee2mqtt/lib/mqtt.ts:141:27)
    at WebSocket.<anonymous> (/opt/zigbee2mqtt/lib/extension/frontend.ts:130:27)
    at WebSocket.emit (node:events:517:28)
    at Receiver.receiverOnMessage (/opt/zigbee2mqtt/node_modules/ws/lib/websocket.js:1192:20)
    at Receiver.emit (node:events:517:28)```

**Comment by Koenkk** [comment]
Found the issue, fixed now.

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
