### ISSUE TITLE
ConBee 3 Manufacture Specific Binding Issue

### ISSUE THREAD

**Issue by thk-socal** [Koenkk/zigbee2mqtt#20105]
### What happened?

Testing out a new ConBee 3 device with the latest firmware 0x264e0900 running in the latest-dev docker for zigbee2mqtt. When joining a new device configuration begins after device interview and manu

### What did you expect to happen?

Expectation is proper binding of specific Philips Hue devices like other adapters do.

### How to reproduce it (minimal and precise)

Configure any Philips Hue device that has the manuSpecificPhilips2 binding.

### Zigbee2MQTT version

1.33.2-dev commit: b17487e

### Adapter firmware version

0x264e0900

### Adapter

ConBee 3

### Debug log

2023/12/08 08:42:43,stdout,"Zigbee2MQTT:info  2023-12-08 08:42:43: MQTT publish: topic 'zigbee2mqtt/0x001788010dda0921', payload '{\"color_mode\":\"xy\",\"gradient\":null,\"linkquality\":192,\"power_on_behavior\":null,\"state\":\"OFF\",\"update\":{\"installed_version\":16779268,\"latest_version\":16779268,\"state\":\"idle\"},\"update_available\":null}'
"
2023/12/08 08:42:10,stdout,"Zigbee2MQTT:info  2023-12-08 08:42:10: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{\"data\":{\"id\":\"0x001788010dda0921\"},\"error\":\"Failed to configure (Bind 0x001788010dda0921/242 manuSpecificPhilips2 from '0x00212effff0db637/1' failed (Error: status: 130))\",\"status\":\"error\",\"transaction\":\"51spg-2\"}'
"
2023/12/08 08:42:10,stdout,    at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:21))

2023/12/08 08:42:10,stdout,    at Configure.configure (/app/lib/extension/configure.ts:117:13)

2023/12/08 08:42:10,stdout,    at Object.result.configure (/app/node_modules/zigbee-herdsman-converters/src/lib/philips.ts:142:17)

2023/12/08 08:42:10,stdout,    at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:645:13)

2023/12/08 08:42:10,stdout,    at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:776:19)

2023/12/08 08:42:10,stdout,"Zigbee2MQTT:error 2023-12-08 08:42:10: Failed to configure '0x001788010dda0921', attempt 4 (Error: Bind 0x001788010dda0921/242 manuSpecificPhilips2 from '0x00212effff0db637/1' failed (Error: status: 130)
"
2023/12/08 08:42:10,stdout,"Zigbee2MQTT:info  2023-12-08 08:42:10: MQTT publish: topic 'zigbee2mqtt/0x001788010dda0921', payload '{\"color_mode\":\"xy\",\"gradient\":null,\"linkquality\":192,\"power_on_behavior\":null,\"state\":\"OFF\",\"update\":{\"installed_version\":-1,\"latest_version\":-1,\"state\":null},\"update_available\":null}'
"
2023/12/08 08:42:10,stdout,"Zigbee2MQTT:info  2023-12-08 08:42:10: MQTT publish: topic 'zigbee2mqtt/0x001788010dda0921', payload '{\"color_mode\":\"xy\",\"gradient\":null,\"linkquality\":201,\"power_on_behavior\":null,\"state\":\"OFF\",\"update\":{\"installed_version\":-1,\"latest_version\":-1,\"state\":null},\"update_available\":null}'
"
2023/12/08 08:42:10,stdout,Zigbee2MQTT:info  2023-12-08 08:42:10: Configuring '0x001788010dda0921'

**Comment by thk-socal** [comment]
Also just added the Hue Tap Dial Switch to the network and none of the button actions are received by the network. I wonder if this is another binding issue during device configuration.
