### ISSUE TITLE
Issue while starting Edge version  (release 16.6.0)

### ISSUE THREAD

**Issue by Minims** [Koenkk/zigbee2mqtt#20159]
### What happened?

Zigbee2MQTT fails to start because of this error.
I have a Zlinky by Live, is suppose this is related.

```
TypeError: Cannot read properties of undefined (reading 'debug')
    at getCurrentConfig (/app/node_modules/zigbee-herdsman-converters/src/devices/lixee.ts:724:12)
    at Object.exposes (/app/node_modules/zigbee-herdsman-converters/src/devices/lixee.ts:800:27)
    at Device.exposes (/app/lib/model/device.ts:34:36)
    at HomeAssistant.getConfigs (/app/lib/extension/homeassistant.ts:1143:36)
    at HomeAssistant.onMQTTMessage (/app/lib/extension/homeassistant.ts:1584:31)
    at EventEmitter.emit (node:events:525:35)
    at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:109:22)
    at MQTT.onMessage (/app/lib/mqtt.ts:141:27)
    at MqttClient.emit (node:events:513:28)
    at handlePublish (/app/node_modules/mqtt/src/lib/handlers/publish.ts:172:11)
```

### What did you expect to happen?

Zigbee2MQTT starts without error

### How to reproduce it (minimal and precise)

Install Edge version (release 16.6.0) and start it with a Zlinky/Lixee device

### Zigbee2MQTT version

Edge with (release 16.6.0)

### Adapter firmware version

20230507

### Adapter

Sonoff Zigbee USB Dongle

### Debug log

No Debug, only startup trace : 

```
TypeError: Cannot read properties of undefined (reading 'debug')
    at getCurrentConfig (/app/node_modules/zigbee-herdsman-converters/src/devices/lixee.ts:724:12)
    at Object.exposes (/app/node_modules/zigbee-herdsman-converters/src/devices/lixee.ts:800:27)
    at Device.exposes (/app/lib/model/device.ts:34:36)
    at HomeAssistant.getConfigs (/app/lib/extension/homeassistant.ts:1143:36)
    at HomeAssistant.onMQTTMessage (/app/lib/extension/homeassistant.ts:1584:31)
    at EventEmitter.emit (node:events:525:35)
    at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:109:22)
    at MQTT.onMessage (/app/lib/mqtt.ts:141:27)
    at MqttClient.emit (node:events:513:28)
    at handlePublish (/app/node_modules/mqtt/src/lib/handlers/publish.ts:172:11)
```

**Comment by Koenkk** [comment]
Should be fixed by https://github.com/Koenkk/zigbee-herdsman-converters/commit/993644b8cdfb8d3777461cb1abe4fccb4a73e4ae
