### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by tkarlsson** [Koenkk/zigbee2mqtt#20193]
### What happened?

I'm getting a lot of these errors in the logfile:

debug 2023-12-13 04:08:23: TypeError: Cannot read properties of undefined (reading 'constructor')
    at Object.convert (/app/node_modules/zigbee-herdsman-converters/src/devices/schneider_electric.ts:176:63)
    at Receive.onDeviceMessage (/app/lib/extension/receive.ts:152:51)
    at EventEmitter.emit (node:events:529:35)
    at EventBus.emitDeviceMessage (/app/lib/eventBus.ts:102:22)
    at Controller.<anonymous> (/app/lib/zigbee.ts:108:27)
    at Controller.emit (node:events:517:28)
    at Controller.selfAndDeviceEmit (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:527:14)
    at Controller.onZclOrRawData (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:741:18)

### What did you expect to happen?

No such errors

### Zigbee2MQTT version

1.34.0-dev commit: 7c81eda

### Adapter firmware version

20231112

### Adapter

Sonoff

**Comment by tkarlsson** [comment]
Looks like it fixes the problem. Still get crashes with:

Error: SREQ '--> ZDO - mgmtPermitJoinReq - {"addrmode":15,"dstaddr":65532,"duration":254,"tcsignificance":0}' failed with status '(0x11: BUFFER_FULL)' (expected '(0x00: SUCCESS)')
    at Object.func (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:322:27)
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)

But, that's a separate issue
