### ISSUE TITLE
[Solved] Problem with RTCGQ12LM

### ISSUE THREAD

**Issue by vsatmydynipnet** [Koenkk/zigbee2mqtt#20203]
### What happened?

Cannot get occupancy to show up in Home Assistant. illuminance, linkquality of the same motion sensor shows up, only occupancy is missing, event its on mqtt. I tried already lot of settings. 

I defined it that way:

```
  - name: "Bewegung Terrasse Aktiv"               
    state_topic: zigbee2mqtt/0x00158d0008478e43
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: ""                                  
    value_template: "{{ value_json.occupancy }}"                            
    unique_id: "aqarabewegung1occupancy"       
 ```
 
 All other values from the other sensors are fine, even from the motion sensor only occupancy is missing in HA and keeps state unknown.
 
 

### What did you expect to happen?

I run HA + Z2M with Conbee II (Firmware 0x26720700) everything updated with 4 Aqara temperature sensors and the above mentioned motion sensor.

### Zigbee2MQTT version

1.34.0 

### Adapter firmware version

0x26720700

### Adapter

 ConBee2/RaspBee2

### Debug log

I run z2m as ha addon. I am no dev, but if somebody tells me how to create the log in this combi i will create it.

**Comment by vsatmydynipnet** [comment]
I found this. Sorry foe posting from mobile

``
Logger: homeassistant.components.mqtt.models
Source: components/mqtt/models.py:305
Integration: MQTT (documentation, issues)
First occurred: 23:03:05 (3 occurrences)
Last logged: 23:12:16

Exception raised when updating state of sensor.bewegung_terrasse_aktiv, topic: 'zigbee2mqtt/0x00158d0008478e43' with payload: b'{"battery":null,"device_temperature":null,"illuminance":0,"illuminance_lux":0,"linkquality":255,"occupancy":false,"power_outage_count":null,"voltage":null}'
Exception raised when updating state of sensor.bewegung_terrasse_aktiv, topic: 'zigbee2mqtt/0x00158d0008478e43' with payload: b'{"battery":null,"device_temperature":null,"illuminance":0,"illuminance_lux":0,"linkquality":255,"occupancy":true,"power_outage_count":null,"voltage":null}'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 621, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'False'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 305, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 745, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 751, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 623, in state
    raise ValueError(
ValueError: Sensor sensor.bewegung_terrasse_aktiv has device class 'None', state class 'None' unit '' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'False' (<class 'str'>)
``

**Comment by vsatmydynipnet** [comment]
SOLVED:

REMOVED->    unit_of_measurement: ""                                  

now its working.

  - name: "Bewegung Terrasse Aktiv"               
    state_topic: zigbee2mqtt/0x00158d0008478e43
    availability_topic: "zigbee2mqtt/bridge/state"
    value_template: "{{ value_json.occupancy }}"                            
    unique_id: "aqarabewegung1occupancy"
