### ISSUE TITLE
error crashing/restarting zigbee-heardsman,  this occurs after running for days.

### ISSUE THREAD

**Issue by jdodgen** [Koenkk/zigbee2mqtt#20231]
### What happened?

my system starts up and runs fine for days then I get this: (log_level: warn)
from:  /opt/zigbee2mqtt/data/log/2023-12-15.15-18-22
```
error 2023-12-10 20:14:59: Error while starting zigbee-herdsman
error 2023-12-10 20:14:59: Failed to start zigbee
error 2023-12-10 20:14:59: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2023-12-10 20:14:59: Exiting...
error 2023-12-10 20:14:59: Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/opt/zigbee2mqtt/node_modules/@serialport/stream/dist/index.js:82:22)
    at /opt/zigbee2mqtt/node_modules/@serialport/stream/dist/index.js:118:18
```
when I attempt to restart:
```
npm start
```
and get the same error
I tried this to see if some other process had ttyUSB0
```
fuser /dev/ttyUSB0
```
and it reports nothing

If I reboot it runs fine, which is my current solution to the problem.
Any Ideas?

### What did you expect to happen?

not to do this.

### How to reproduce it (minimal and precise)

Not easy, intermittent. Some times it takes a week to fail.

### Zigbee2MQTT version

1.33.1 commit: 7e63039

### Adapter firmware version

20210120

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus

### Debug log

Sorry I don't have that right now.  I'll turn on "debugging"
```
advanced:
  log_level: debug
```
and provided the log the next time it breaks

**Comment by jdodgen** [comment]
Here is where the problem starts. "Adapter disconnected"

```...
debug 2023-12-16 13:02:27: Received Zigbee message from 'ss1', type 'attributeReport', cluster 'genBasic', data '{"65506":56,"65508":0,"appVersion":72}' from endpoint 1 with groupID 0
error 2023-12-16 13:02:58: Adapter disconnected, stopping
debug 2023-12-16 13:02:58: Saving state to file /opt/zigbee2mqtt/data/state.json
info  2023-12-16 13:02:58: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'offline'
info  2023-12-16 13:02:58: Disconnecting from MQTT server
info  2023-12-16 13:02:58: Stopping zigbee-herdsman...
error 2023-12-16 13:02:58: Failed to stop Zigbee2MQTT```

**Comment by jdodgen** [comment]
It needs to stay open until a resolution. Nothing back from the mqtt2zigbee engineers.
