### ISSUE TITLE
Develco MOSZB-140 using Conbee 3

### ISSUE THREAD

**Issue by emandtf** [Koenkk/zigbee2mqtt#20244]
### What happened?

Trying to pair this Develco MOSZB-140 I get this error:

> Failed to configure '0x0015bc001a02296f', attempt 1 (Error: Bind 0x0015bc001a02296f/39 msIlluminanceMeasurement from '0x00212effff0e192f/1' failed (waiting for response TIMEOUT) at DeconzAdapter.bind (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:776:19) at Endpoint.bind (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:545:13) at Object.bind (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:43:9) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/devices/develco.ts:679:13) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:117:13) at Configure.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/configure.ts:55:21))

The device remains:

- Interview completed: false

### Zigbee2MQTT version

1.34-dev

### Adapter firmware version

0x264e0900

### Adapter

Conbee 3

**Comment by emandtf** [comment]
Forcing pairing via a specific Router (not the Coordinator Conbee 3) seems to have fixed this.
Same behavior for other devices: if trying to pair leaving "Permit Join (All)" enabled from the drop-down it cannot be completed.
I don't know if those devices tries to pair directly via Conbee3 or other devices however if I switch to Conbee 2 all seems working fine.

**Comment by emandtf** [comment]
The error still present using 1.36.1 and latest Conbee 3 firmware 0x26510900 (15 April) with this error log:

> 11:33:15: Received Zigbee message from '0xa4c1387d8b05873c', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID null
11:33:15: Successfully pinged '0xa4c1387d8b05873c' (attempt 1/2)
11:33:17: Received Zigbee message from '0xa4c1388ee0e1d124', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID null
11:33:17: Successfully pinged '0xa4c1388ee0e1d124' (attempt 1/2)
11:33:34: Device '0x0015bc001a02296f' joined
11:33:34: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x0015bc001a02296f","ieee_address":"0x0015bc001a02296f"},"type":"device_joined"}'
11:33:34: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x0015bc001a02296f"},"type":"device_connected"}'
11:33:34: Starting interview of '0x0015bc001a02296f'
11:33:34: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x0015bc001a02296f","ieee_address":"0x0015bc001a02296f","status":"started"},"type":"device_interview"}'
11:33:34: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x0015bc001a02296f"},"type":"pairing"}'
11:33:35: Failed to interview '0x0015bc001a02296f', device has not successfully been paired
