### ISSUE TITLE
OTA not working - self signed certificates

### ISSUE THREAD

**Issue by uphillbattle** [Koenkk/zigbee2mqtt#20432]
### What happened?

Fresh install on HA OS - HA v2023.12.4, OS v11.2 - exact same config as on another HA instance I have somewhere else. 

OTA of Philips Hue Outdoor Motion sensor does not work. Error message:
`Update of 'Bevegelse nord' failed (self signed certificate in certificate chain) `

Problem also reported in discussion #20423

### What did you expect to happen?

OTA to succeed as I’m used to. :)

### How to reproduce it (minimal and precise)

Initiate OTA from OTA page of zigbee2mqtt frontend

### Zigbee2MQTT version

1.34.0

### Adapter firmware version

20220219

### Adapter

Sonoff Zigbee 3.0

### Debug log

```
Debug 2023-12-29 15:33:36Received MQTT message on 'z2mhytta/bridge/request/device/ota_update/update' with data '{"id":"Bevegelse nord","transaction":"whlsr-3"}'
Info 2023-12-29 15:33:36Updating 'Bevegelse nord' to latest firmware
Debug 2023-12-29 15:33:36Received Zigbee message from 'Bevegelse nord', type 'readResponse', cluster 'genBasic', data '{"dateCode":"20180828","swBuildId":"6.1.0.25261"}' from endpoint 1 with groupID 0
Debug 2023-12-29 15:33:36Updating to latest '0x001788010649f7fd' (SML002)
Debug 2023-12-29 15:33:36Using endpoint '2'
Debug 2023-12-29 15:33:37Received Zigbee message from 'Bevegelse nord', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":1107321517,"imageType":269,"manufacturerCode":4107}' from endpoint 2 with groupID 0
Debug 2023-12-29 15:33:37Got OTA request '{"fieldControl":0,"manufacturerCode":4107,"imageType":269,"fileVersion":1107321517}'
Debug 2023-12-29 15:33:38ZigbeeOTA: downloaded main index
Debug 2023-12-29 15:33:38getNewImage for '0x001788010649f7fd', meta {"fileVersion":1107323831,"fileSize":240760,"url":"https://otau.meethue.com/storage/ZGB_100B_010D/bd3f218f-190b-4498-b6b3-69aea563fd9d/Sensor-ATmega_6.1.1.27575_0012.sbl-ota","sha512":"10e549c55d262b2f227b75817f6620be407f537e04ac08db4dbebdf53e8d460299a2cda248b3be13476757d61a1c79b632963c4f126cd26b7c18ea6a2ab4ac59"}
Debug 2023-12-29 15:33:38ZigbeeOTA: downloading firmware image from https://otau.meethue.com/storage/ZGB_100B_010D/bd3f218f-190b-4498-b6b3-69aea563fd9d/Sensor-ATmega_6.1.1.27575_0012.sbl-ota
Debug 2023-12-29 15:33:38Update of 'Bevegelse nord' failed (Error: self signed certificate in certificate chain)
Info 2023-12-29 15:33:38MQTT publish: topic 'z2mhytta/Bevegelse nord', payload '{"battery":100,"illuminance":15546,"illuminance_lux":36,"led_indication":false,"linkquality":80,"motion_sensitivity":"low","occupancy":false,"occupancy_timeout":0,"temperature":-6.17,"update":{"installed_version":1107321517,"latest_version":1107323831,"state":"available"},"update_available":null}'
Info 2023-12-29 15:33:38MQTT publish: topic 'z2mhytta/bridge/response/device/ota_update/update', payload '{"data":{"id":"Bevegelse nord"},"error":"Update of 'Bevegelse nord' failed (self signed certificate in certificate chain)","status":"error","transaction":"whlsr-3"}'
Error 2023-12-29 15:33:38Update of 'Bevegelse nord' failed (self signed certificate in certificate chain)
Debug 2023-12-29 15:33:38Error: self signed certificate in certificate chain at Function.AxiosError.from (/app/node_modules/axios/lib/core/AxiosError.js:89:14) at RedirectableRequest.handleRequestError (/app/node_modules/axios/lib/adapters/http.js:606:25) at RedirectableRequest.emit (node:events:513:28) at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24) at ClientRequest.emit (node:events:513:28) at TLSSocket.socketErrorListener (node:_http_client:494:9) at TLSSocket.emit (node:events:513:28) at emitErrorNT (node:internal/streams/destroy:157:8) at emitErrorCloseNT (node:internal/streams/destroy:122:3) at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by uphillbattle** [comment]
Duplicate of #20429
