### ISSUE TITLE
Zigbee2mqtt doesn't start (Configuration is not consistent)

### ISSUE THREAD

**Issue by Shponzo** [Koenkk/zigbee2mqtt#20443]
### What happened?

I just installed a bunch of updates (Supervisor, HA, ...) and did some reboots, and now my Zigbee2MQTT doesn't start.
I tried to do restart, replug the Sonoff, ...

### Zigbee2MQTT version

1.34.0-1

### Adapter firmware version

/

### Adapter

Sonoff Zigbee 3.0 USB dongle plus

### Debug log

debug 2023-12-30 16:20:59: Loaded state from file /share/zigbee2mqtt/state.json
info  2023-12-30 16:20:59: Logging to console and directory: '/share/zigbee2mqtt/log/2023-12-30.16-20-59' filename: log.txt
debug 2023-12-30 16:20:59: Removing old log directory '/share/zigbee2mqtt/log/2023-12-30.16-12-11'
info  2023-12-30 16:20:59: Starting Zigbee2MQTT version 1.34.0 (commit #unknown)
info  2023-12-30 16:20:59: Starting zigbee-herdsman (0.25.0)
debug 2023-12-30 16:20:59: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/share/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/share/zigbee2mqtt/database.db.backup","databasePath":"/share/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyUSB0"}}'
error 2023-12-30 16:20:59: Configuration is not consistent with adapter state/backup!
error 2023-12-30 16:20:59: - PAN ID: configured=6754, adapter=6754
error 2023-12-30 16:20:59: - Extended PAN ID: configured=00124b001XXXXXX, adapter=dddddddddddddddd
error 2023-12-30 16:20:59: - Network Key: configured=25282174720b11bfeXXXXXXXXXXX, adapter=00000000000000000000000000000000
error 2023-12-30 16:20:59: - Channel List: configured=11, adapter=11
error 2023-12-30 16:20:59: Please update configuration to prevent further issues.
error 2023-12-30 16:20:59: If you wish to re-commission your network, please remove coordinator backup at /share/zigbee2mqtt/coordinator_backup.json.
error 2023-12-30 16:20:59: Re-commissioning your network will require re-pairing of all devices!
error 2023-12-30 16:20:59: Error while starting zigbee-herdsman
error 2023-12-30 16:20:59: Failed to start zigbee
error 2023-12-30 16:20:59: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2023-12-30 16:20:59: Exiting...
error 2023-12-30 16:20:59: Error: startup failed - configuration-adapter mismatch - see logs above for more information
    at ZnpAdapterManager.determineStrategy (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:229:35)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:63:26)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:60:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)

**Comment by Shponzo** [comment]
I managed to get it back working by changing "Extended PAN ID" and "Network Key" in coordinator_backup.json file.
