### ISSUE TITLE
Crash after updating to 1.35

### ISSUE THREAD

**Issue by Ropuh** [Koenkk/zigbee2mqtt#20469]
### What happened?

Crash of the homebridge after uodating to 1.35

### What did you expect to happen?

Start homebridge services

### How to reproduce it (minimal and precise)

Update from fit

### Zigbee2MQTT version

1.35

### Adapter firmware version

20230507

### Adapter

Sonoff dongle plus 2652P

### Debug log

[1/1/2024, 12:58:42 PM] [homebridge-z2m] Publish to 'zigbee2mqtt/0x680ae2fffe3fdfe4/get': '{"state":0}'
[1/1/2024, 12:58:42 PM] [homebridge-z2m] Publish to 'zigbee2mqtt/0xa4c1385d85a35265/get': '{"state":0}'
TypeError: Cannot read properties of null (reading 'vendor')
    at isDeviceDefinition (/usr/lib/node_modules/homebridge-z2m/src/z2mModels.ts:294:73)
    at Zigbee2mqttAccessory.updateDeviceInformation (/usr/lib/node_modules/homebridge-z2m/src/platformAccessory.ts:290:30)
    at new Zigbee2mqttAccessory (/usr/lib/node_modules/homebridge-z2m/src/platformAccessory.ts:82:10)
    at Zigbee2mqttPlatform.addAccessory (/usr/lib/node_modules/homebridge-z2m/src/platform.ts:419:19)
    at Zigbee2mqttPlatform.configureAccessory (/usr/lib/node_modules/homebridge-z2m/src/platform.ts:319:10)
    at /usr/lib/node_modules/homebridge/src/bridgeService.ts:328:25
    at Array.filter (<anonymous>)
    at BridgeService.restoreCachedPlatformAccessories (/usr/lib/node_modules/homebridge/src/bridgeService.ts:288:69)
    at ChildBridgeFork.startBridge (/usr/lib/node_modules/homebridge/src/childBridgeFork.ts:186:24)
[1/1/2024, 12:58:43 PM] [homebridge-z2m] Child bridge process ended
[1/1/2024, 12:58:43 PM] [homebridge-z2m] Process Ended. Code: 1, Signal: null
[1/1/2024, 12:58:50 PM] [homebridge-z2m] Restarting Process...
[1/1/2024, 12:58:54 PM] [homebridge-z2m] Launched child bridge with PID 3760
[1/1/2024, 12:58:55 PM] Registering platform 'homebridge-z2m.zigbee2mqtt'
[1/1/2024, 12:58:55 PM] [homebridge-z2m] Loaded homebridge-z2m v1.9.2 child bridge successfully
[1/1/2024, 12:58:56 PM] Loaded 70 cached accessories from cachedAccessories.0E9CACDE5EA2.
[1/1/2024, 12:58:57 PM] [homebridge-z2m] Connecting to MQTT server at mqtt://127.0.0.1:1883
[1/1/2024, 12:58:58 PM] [homebridge-z2m] Restoring accessory: Sypialnia Computer Switch (0x00158d0004506dde)

**Comment by Koenkk** [comment]
This looks like an issue in the homebridge z2m plugin, please create an issue there.
