### ISSUE TITLE
Reset error when installing on Home Assistant Yellow

### ISSUE THREAD

**Issue by jezzalencko** [Koenkk/zigbee2mqtt#20507]
### What happened?

Hi all,
Read multiple threads on similar topics but nothing seems to work. Have tried uninstalling Z2M, uninstalling mosquitto, reinstalling both, replacing core-mosquitto server with the IP address of my HA, ensuring ezsp is in as adapter, but each time getting this error:

[19:07:44] INFO: Preparing to start…
[19:07:44] INFO: Socat not enabled
[19:07:47] INFO: Starting Zigbee2MQTT…
Zigbee2MQTT:info 2024-01-02 19:07:54: Logging to console and directory: ‘/config/zigbee2mqtt/log/2024-01-02.19-07-54’ filename: log.txt
Zigbee2MQTT:info 2024-01-02 19:07:54: Starting Zigbee2MQTT version 1.35.0 (commit #unknown)
Zigbee2MQTT:info 2024-01-02 19:07:54: Starting zigbee-herdsman (0.30.0)
Error: Reset error: Error: {“sequence”:-1} after 10000ms
at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:299:23
at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)

Got this in my zigbee2mqtt config files:

mqtt:
server: mqtt://[my_HA_IP]:1883
user: my_username
password: “my_pwd”
serial:
port: /dev/ttyAMA1
adapter: ezsp
baudrate: 115200
rtscts: true
frontend:
port: 8099

Please help.

### What did you expect to happen?

Installation to go ahead successfully and then access to Web UI and so on.

### How to reproduce it (minimal and precise)

Installed Mosquitto add-on.
Installed Zigbee2MQTT add-on.
Start add-on.

### Zigbee2MQTT version

1.35.0-1

### Adapter firmware version

20230802.1

### Adapter

On-board 

### Debug log

[22:08:07] INFO: Preparing to start...
[22:08:08] INFO: Socat not enabled
[22:08:08] INFO: Zigbee Herdsman debug logging enabled
[22:08:11] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:debug 2024-01-02 22:08:17: Can't load state from file /config/zigbee2mqtt/state.json (doesn't exist)
Zigbee2MQTT:info  2024-01-02 22:08:17: Logging to console and directory: '/config/zigbee2mqtt/log/2024-01-02.22-08-17' filename: log.txt
Zigbee2MQTT:debug 2024-01-02 22:08:17: Removing old log directory '/config/zigbee2mqtt/log/2024-01-02.21-57-56'
Zigbee2MQTT:info  2024-01-02 22:08:17: Starting Zigbee2MQTT version 1.35.0 (commit #unknown)
Zigbee2MQTT:info  2024-01-02 22:08:17: Starting zigbee-herdsman (0.30.0)
Zigbee2MQTT:debug 2024-01-02 22:08:17: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[76,89,170,21,55,61,149,128],"networkKey":"HIDDEN","panID":45379},"serialPort":{"adapter":"ezsp","baudRate":115200,"path":"/dev/ttyAMA1","rtscts":true}}'
2024-01-02T14:08:18.399Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2024-01-02T14:08:18.401Z zigbee-herdsman:adapter:ezsp:debg Adapter concurrent: 8
2024-01-02T14:08:18.403Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[78,34,49,87,239,207,195,112,62,223,3,183,240,98,150,228],"panID":45379,"extendedPanID":[76,89,170,21,55,61,149,128],"channelList":[11]},"serialPort":{"baudRate":115200,"rtscts":true,"path":"/dev/ttyAMA1","adapter":"ezsp"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2024-01-02T14:08:18.408Z zigbee-herdsman:adapter:ezsp:uart Opening SerialPort with {"path":"/dev/ttyAMA1","baudRate":115200,"rtscts":true,"autoOpen":false}
2024-01-02T14:08:18.420Z zigbee-herdsman:adapter:ezsp:uart Serialport opened
2024-01-02T14:08:18.421Z zigbee-herdsman:adapter:ezsp:uart Uart reseting
2024-01-02T14:08:18.423Z zigbee-herdsman:adapter:ezsp:uart --> Write reset
2024-01-02T14:08:18.425Z zigbee-herdsman:adapter:ezsp:uart --> [1ac038bc7e]
2024-01-02T14:08:18.427Z zigbee-herdsman:adapter:ezsp:uart -?- waiting reset
2024-01-02T14:08:28.428Z zigbee-herdsman:adapter:ezsp:uart --> Error: Error: {"sequence":-1} after 10000ms
2024-01-02T14:08:28.430Z zigbee-herdsman:adapter:ezsp:driv Reset connection. Try 0
2024-01-02T14:08:28.433Z zigbee-herdsman:adapter:ezsp:driv Stop driver
2024-01-02T14:08:28.435Z zigbee-herdsman:adapter:ezsp:ezsp Stop ezsp
2024-01-02T14:08:28.436Z zigbee-herdsman:adapter:ezsp:ezsp Close ezsp
2024-01-02T14:08:28.437Z zigbee-herdsman:adapter:ezsp:driv Close driver
Error: Reset error: Error: {"sequence":-1} after 10000ms
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:299:23
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)

**Comment by burntoc** [comment]
Seeing the same behavior on my Skyconnect with Z2M 1.35.0-1.
