### ISSUE TITLE
z2m wont start after changes the network box coordinator is attached to

### ISSUE THREAD

**Issue by yarafie** [Koenkk/zigbee2mqtt#20529]
### What happened?

I swapped out an eero network wifi  device with a new one this is what my coordinator is attached to.
Nothing else changed in z2m configuration

See log below

Any help woukd be appreciated

### Zigbee2MQTT version

latest version

### Adapter firmware version

20230503

### Adapter

slzb-06 CC2652PP1FRGZR

### Debug log

Using '/app/data' as data directory
Zigbee2MQTT:error 2024-01-03 06:12:55: Configuration is not consistent with adapter state/backup!
Zigbee2MQTT:error 2024-01-03 06:12:55: - PAN ID: configured=6754, adapter=6754
Zigbee2MQTT:error 2024-01-03 06:12:55: - Extended PAN ID: configured=00124b00257c8f01, adapter=00124b00257c8f01
Zigbee2MQTT:error 2024-01-03 06:12:55: - Network Key: configured=29fc9a14f6e18100d1ea2cf2ebd6981f, adapter=29fc9a14f6e18100d1ea2cf2ebd6981f
Zigbee2MQTT:error 2024-01-03 06:12:55: - Channel List: configured=15, adapter=15
Zigbee2MQTT:error 2024-01-03 06:12:55: Please update configuration
to prevent further issues.
Zigbee2MQTT:error 2024-01-03 06:12:55: If you wish to re-commission your network, please remove coordinator backup at /app/data/coordinator_backup.json.
Zigbee2MQTT:error 2024-01-03 06:12:55: Re-commissioning your network will require re-pairing of all devices!
Zigbee2MQTT:error 2024-01-03 06:12:55: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-01-03 06:12:55: Failed to start zigbee
Zigbee2MQTT:error 2024-01-03 06:12:55: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-01-03 06:12:55: Exiting...
Zigbee2MQTT:error 2024-01-03 06:12:55: Error: startup failed - configuration-adapter mismatch - see logs above for more information
    at ZnpAdapterManager.determineStrategy (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:229:35)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:63:26)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:60:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)
Using '/app/data' as data directory

**Comment by yarafie** [comment]
Problem resolved had to revert back to original eero device that coordinator was attached to.
