### ISSUE TITLE
Power on behavoiur "UNSUPPORTED_ATTRIBUTE" since last Z2M update for Enbrighten 43082 devices

### ISSUE THREAD

**Issue by pyrodex** [Koenkk/zigbee2mqtt#20527]
### What happened?

Setting the power on behavior in the device causes the following alerts new in 1.35.0:

```
Zigbee2MQTT:error 2024-01-02 19:05:33: Publish 'get' 'power_on_behavior' to 'Family Room Dimmer' failed: 'Error: Read 0xa49e69fffe62fd02/1 genOnOff(["startUpOnOff"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
```

### What did you expect to happen?

No error

### How to reproduce it (minimal and precise)

Upgrade to 1.35.0

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

20230507

### Adapter

Tubezb POE P7

### Debug log

```
Zigbee2MQTT:debug 2024-01-02 19:09:42: Received Zigbee message from 'Family Room Dimmer', type 'readResponse', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2024-01-02 19:09:42: MQTT publish: topic 'zigbee2mqtt/Family Room Dimmer', payload '{"brightness":254,"device":{"applicationVersion":18,"friendlyName":"Family Room Dimmer","hardwareVersion":2,"ieeeAddr":"0xa49e69fffe62fd02","manufacturerID":4388,"manufacturerName":"Jasco Products","model":"43082","networkAddress":46631,"powerSource":"Mains (single phase)","stackVersion":101,"type":"Router","zclVersion":3},"energy":0,"last_seen":"2024-01-02T19:09:42-05:00","linkquality":112,"power":0,"state":"OFF"}'
Zigbee2MQTT:error 2024-01-02 19:09:42: Publish 'get' 'power_on_behavior' to 'Family Room Dimmer' failed: 'Error: Read 0xa49e69fffe62fd02/1 genOnOff(["startUpOnOff"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Zigbee2MQTT:debug 2024-01-02 19:09:42: Error: Read 0xa49e69fffe62fd02/1 genOnOff(["startUpOnOff"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:321:28)
    at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:463:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.convertGet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:292:13)
    at Publish.onMQTTMessage (/app/lib/extension/publish.ts:276:21)
```

**Comment by Koenkk** [comment]
Should be fixed in the dev branch!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
