### ISSUE TITLE
Aqara B1 motor misses genOTA cluster

### ISSUE THREAD

**Issue by new-kirte** [Koenkk/zigbee2mqtt#20583]
### What happened?

When trying to check OTA for Aqara B1 I am getting the error:
2024-01-05 12:31:17Failed to check if update available for 'Sonya Curtains Wireless' (Failed to find endpoint which support OTA cluster)
Debug 2024-01-05 12:31:17AssertionError [ERR_ASSERTION]: Failed to find endpoint which support OTA cluster at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:330:15) at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/zigbeeOTA.ts:110:19) at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:205:73) at EventEmitter.emit (node:events:529:35) at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:109:22) at MQTT.onMessage (/app/lib/mqtt.ts:141:27) at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:130:27) at WebSocket.emit (node:events:517:28) at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1209:20) at Receiver.emit (node:events:517:28)

### What did you expect to happen?

OTA is checked

### Zigbee2MQTT version

1.35.0 commit: b5a90e9

### Adapter firmware version

0x26780700

### Adapter

 ConBee2/RaspBee2

**Comment by new-kirte** [comment]
Resolved as per instructions in #8297:
Update file database.db:
	1. Stop Zigbee2MQTT container
	2. Open file database.db in the Notepad
	3. Search for lumi.curtain.hagl04
	4. add 25 to the outClusterList for each lumi.curtain.hagl04 device
	5. Start Zigbee2MQTT container and attempt the ota update
