### ISSUE TITLE
Empty String in Config of TS011F_plug_1 crashes Zigbee2MQTT in HA since 1.35.0

### ISSUE THREAD

**Issue by janfuhlrott** [Koenkk/zigbee2mqtt#20616]
### What happened?

Since Update to 1.35.0, HA addon crashes every 5 to 15 minutes.

Empty String in Configuration (power_calibration = '') should only give an error but crashes zigbee2mqtt container.

### How to reproduce it (minimal and precise)

Zigbee2MQTT-Version
    1.35.0 commit: unknown

Coordinator-Typ
    ConBee2/RaspBee2

Coordinator-Version
    0x26780700

Coordinator IEEE Adresse
    0x00212effff095f33

Frontend-Version
    0.6.150

Zigbee-herdsman-converters version
    18.3.0

Zigbee-herdsman version
    0.30.0

### Zigbee2MQTT version

1.35.0

### Adapter firmware version

0x26780700

### Adapter

ConBee2/RaspBee2

### Debug log

2024-01-06T13:00:08.080Z zigbee-herdsman:deconz:driver DATA_REQUEST - destAddr: 0xe09a EP:1 SeqNr. 59 request id: 85
2024-01-06T13:00:08.090Z zigbee-herdsman:deconz:frameParser DATA_REQUEST RESPONSE - request id: 85 status: 0
2024-01-06T13:00:08.090Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2024-01-06T13:00:08.091Z zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10100110
2024-01-06T13:00:08.091Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 1 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2024-01-06T13:00:08.092Z zigbee-herdsman:deconz:driver query aps data confirm
2024-01-06T13:00:08.097Z zigbee-herdsman:deconz:driver DATA_CONFIRM - sending data state request - SeqNr. 60
2024-01-06T13:00:08.100Z zigbee-herdsman:deconz:frameParser DATA_CONFIRM RESPONSE - destAddr: 0xe09a request id: 85 confirm status: 0
2024-01-06T13:00:08.100Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2024-01-06T13:00:08.100Z zigbee-herdsman:deconz:adapter sendZclFrameToEndpoint - message send with transSeq Nr.: 140
2024-01-06T13:00:08.101Z zigbee-herdsman:deconz:adapter false, true, false, 10000
2024-01-06T13:00:08.101Z zigbee-herdsman:deconz:adapter resolve request (140)
2024-01-06T13:00:10.186Z zigbee-herdsman:deconz:driver send read device state from queue. seqNr: 61
2024-01-06T13:00:10.191Z zigbee-herdsman:deconz:frameParser device state: 10100010
2024-01-06T13:00:10.191Z zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
Error: 'power_calibration' is not a number, got string ()
    at toNumber (/app/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:565:15)
    at Object.calibrateAndPrecisionRoundOptions (/app/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:92:29)
    at Object.postProcessConvertedFromZigbeeMessage (/app/node_modules/zigbee-herdsman-converters/src/index.ts:233:34)
    at publish (/app/lib/extension/receive.ts:121:17)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman-converters/src/devices/tuya.ts:461:86)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)

**Comment by Koenkk** [comment]
Should already be fixed in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)
