### ISSUE TITLE
Problem detected - Ikea 

### ISSUE THREAD

**Issue by lorek123** [Koenkk/zigbee2mqtt#2062]
# Bug Report
## What happened
```
PROBLEM DETECTED
Please create an issue here with the contents of below: https://github.com/koenkk/zigbee2mqtt/issues
===== Stack =====
AssertionError [ERR_ASSERTION]: { frameCntl:
   { frameType: 1, manufSpec: 1, direction: 0, disDefaultRsp: 0 },
  manufCode: 4476,
  seqNum: 63,
  cmdId: 'tr... deepEqual { frameCntl:
   { frameType: 1, manufSpec: 1, direction: 0, disDefaultRsp: 0 },
  manufCode: 4476,
  seqNum: 63,
  cmdId: 'tr...
    at cb (/app/node_modules/zigbee-herdsman/dist/lib/components/zcl.js:59:24)
    at /app/node_modules/zigbee-herdsman/dist/deprecated/zcl-packet/lib/zcl.js:31:17
    at Dissolve.<anonymous> (/app/node_modules/zigbee-herdsman/dist/deprecated/zcl-packet/lib/functional.js:76:17)
    at Object.onceWrapper (events.js:273:13)
    at Dissolve.emit (events.js:182:13)
    at Dissolve.<anonymous> (/app/node_modules/zigbee-herdsman/dist/deprecated/dissolve-chunks/index.js:65:29)
    at Dissolve.emit (events.js:182:13)
    at emitReadable_ (/app/node_modules/zigbee-herdsman/node_modules/readable-stream/lib/_stream_readable.js:456:10)
    at emitReadable (/app/node_modules/zigbee-herdsman/node_modules/readable-stream/lib/_stream_readable.js:450:7)
    at readableAddChunk (/app/node_modules/zigbee-herdsman/node_modules/readable-stream/lib/_stream_readable.js:206:11)
===== Buffer =====
{ type: 'Buffer', data: [ 5, 124, 17, 63, 7, 2, 0, 0, 0 ] }
===== Arguments =====
<Buffer 05 7c 11 3f 07 02 00 00 00> 5
===== zcl-packet parse =====
{"frameCntl":{"frameType":1,"manufSpec":1,"direction":0,"disDefaultRsp":0},"manufCode":4476,"seqNum":63,"cmdId":"tradfriArrowSingle","payload":{"value":2}}
===== zcl =====
{"frameCntl":{"frameType":1,"manufSpec":1,"direction":0,"disDefaultRsp":0},"manufCode":4476,"seqNum":63,"cmdId":"tradfriArrowSingle","payload":{"value":2,"value2":0}}
===============
```
## What did you expect to happen
Nothing particular, just trying to get some logs how zigbee2mqtt works

## How to reproduce it (minimal and precise)
1/ Pair E1524/E1810 Ikea remote
2/ Long press any button
## Debug Info
zigbee2mqtt version: Starting zigbee2mqtt version 1.6.0 (commit #e26ad2a)
CC253X firmware version: Coordinator firmware version: '20190608

**Comment by Koenkk** [comment]
Thanks for reporting, this is a known issue and is already solved in the dev branch (same as #2006)
