### ISSUE TITLE
Different model of TS011F_plug_1 receiving errors

### ISSUE THREAD

**Issue by yarafie** [Koenkk/zigbee2mqtt#20647]
### What happened?

Model of TS011F_plug_1 although recognized getting errors as per log below
Its a universal wall socket not the same as the plug from link
https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html#tuya-ts011f_plug_1

Below is description in about
Zigbee Model TS011F
Zigbee Manufacturer **_TZ3000_rikal2fw**
Description Smart plug (with power monitoring)
Support status Supported
Manufacturer TuYa
Model TS011F_plug_1

Under exposes Values of Power/Current/Voltage/Energy is Null

### What did you expect to happen?

Not sure

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

20230507

### Adapter

SMLIGHT SLZB-06

### Debug log

Zigbee2MQTT:error 2024-01-07 18:41:00: Failed to configure 'Washing
 Machine Socket', attempt 1 (Error: ConfigureReporting 0xdc8e95fffe
c70319/1 haElectricalMeasurement([{"attribute":"rmsVoltage","minimu
mReportInterval":5,"maximumReportInterval":3600,"reportableChange":
5}], {"sendWhen":"immediate","timeout":10000,"disableResponse":fals
e,"disableRecovery":false,"disableDefaultResponse":true,"direction"
:0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"tra
nsactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'U
NSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/
controller/model/endpoint.ts:321:28)
    at Endpoint.configureReporting (/app/node_modules/zigbee-herdsm
an/src/controller/model/endpoint.ts:665:22)
    at processTicksAndRejections (node:internal/process/task_queues
:95:5)
    at Object.rmsVoltage (/app/node_modules/zigbee-herdsman-convert
ers/src/lib/reporting.ts:220:5)
    at Object.configure (/app/node_modules/zigbee-herdsman-converte
rs/src/devices/tuya.ts:3401:13)
    at Configure.configure (/app/lib/extension/configure.ts:120:13)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:167:17))
Zigbee2MQTT:error 2024-01-07 18:43:22: Failed to configure 'Washing
 Machine Socket', attempt 2 (Error: ConfigureReporting 0xdc8e95fffe
c70319/1 haElectricalMeasurement([{"attribute":"rmsVoltage","minimu
mReportInterval":5,"maximumReportInterval":3600,"reportableChange":
5}], {"sendWhen":"immediate","timeout":10000,"disableResponse":fals
e,"disableRecovery":false,"disableDefaultResponse":true,"direction"
:0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"tra
nsactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'U
NSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/
controller/model/endpoint.ts:321:28)
    at Endpoint.configureReporting (/app/node_modules/zigbee-herdsm
an/src/controller/model/endpoint.ts:665:22)
    at processTicksAndRejections (node:internal/process/task_queues
:95:5)
    at Object.rmsVoltage (/app/node_modules/zigbee-herdsman-convert
ers/src/lib/reporting.ts:220:5)
    at Object.configure (/app/node_modules/zigbee-herdsman-converte
rs/src/devices/tuya.ts:3401:13)
    at Configure.configure (/app/lib/extension/configure.ts:120:13)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:167:17))
Zigbee2MQTT:error 2024-01-07 18:43:58: Failed to configure 'Washing
 Machine Socket', attempt 3 (Error: ConfigureReporting 0xdc8e95fffe
c70319/1 haElectricalMeasurement([{"attribute":"rmsVoltage","minimu
mReportInterval":5,"maximumReportInterval":3600,"reportableChange":
5}], {"sendWhen":"immediate","timeout":10000,"disableResponse":fals
e,"disableRecovery":false,"disableDefaultResponse":true,"direction"
:0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"tra
nsactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'U
NSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/
controller/model/endpoint.ts:321:28)
    at Endpoint.configureReporting (/app/node_modules/zigbee-herdsm
an/src/controller/model/endpoint.ts:665:22)
    at processTicksAndRejections (node:internal/process/task_queues
:95:5)
    at Object.rmsVoltage (/app/node_modules/zigbee-herdsman-convert
ers/src/lib/reporting.ts:220:5)
    at Object.configure (/app/node_modules/zigbee-herdsman-converte
rs/src/devices/tuya.ts:3401:13)
    at Configure.configure (/app/lib/extension/configure.ts:120:13)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:167:17))

**Comment by yarafie** [comment]
Any Help?

**Comment by yarafie** [comment]
Zigbee2MQTT:error 2024-02-14 00:45:05: Failed to configure 'Washing Machine Socket', attempt 1 (Error: ConfigureReporting 0xdc8e95fffec70319/1 haElectricalMeasurement([{"attribute":"rmsVoltage","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":5}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:319:28)
    at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:672:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.rmsVoltage (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:220:5)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/tuya.ts:3595:13)
    at Configure.configure (/app/lib/extension/configure.ts:120:13)    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

**Comment by yarafie** [comment]
Still receiving this with v 1.36.1
