### ISSUE TITLE
OTA support for PARASOLL Door/Window Sensor

### ISSUE THREAD

**Issue by usma0118** [Koenkk/zigbee2mqtt#20688]
### What happened?

Support for Ikea E2013 is implemented in #20007.
but no OTA update is reflected.

### Zigbee2MQTT version

1.35

### Adapter firmware version

20221226

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus,TI CC2652P + CP2102(N)

**Comment by danieledwardgeorgehitchcock** [comment]
It doesn't look as-if there are any OTA images for this device currently published in the IKEA environments:

[Production](http://[fw.ota.homesmart.ikea.net/feed/version_info.json](http://fw.ota.homesmart.ikea.net/feed/version_info.json))

[Test](http://[fw.test.ota.homesmart.ikea.net/feed/version_info.json](http://fw.test.ota.homesmart.ikea.net/feed/version_info.json))

**Comment by usma0118** [comment]
Carrying discussion from #20686.
OTA updates are not supported for this device as this is not displayed under OTA tab in Z2M

**Comment by pvangorp** [comment]
It was working correctly in 1.35.0.1. Since 1.35.1.1 I suddenly got issues as well. See attachments.

![Screenshot_20240113_051700_Home Assistant](https://github.com/Koenkk/zigbee2mqtt/assets/25818919/50174521-2567-4d57-8884-c9a75ff3e673)

![Screenshot_20240113_051802_Home Assistant](https://github.com/Koenkk/zigbee2mqtt/assets/25818919/df132ae4-21cb-49b3-9710-a79660226d3e)

After reverting to 1.35.0.1 everything works fine.

![Screenshot_20240113_052521_Home Assistant](https://github.com/Koenkk/zigbee2mqtt/assets/25818919/5f9b22c5-b9f3-4d4c-80de-cc22d7d98aac)

**Comment by mklooss** [comment]
@pvangorp use contact not tamper.

Temper has been removed
https://github.com/Koenkk/zigbee-herdsman-converters/commit/5403c8aa704fa1a8db7f2fcc01623dd26215b7a9

**Comment by LarsStegman** [comment]
It does have a tamper function? How do you know?

**Comment by pvangorp** [comment]
When you open the batteryslot, it triggers tamper e.g. sabotage. Because I have them

**Comment by LarsStegman** [comment]
Interesting. How can you see what the device does? I have them as well but I'm relatively new to zigbee.

**Comment by pvangorp** [comment]
![Screenshot_20240118_193530_Home Assistant](https://github.com/Koenkk/zigbee2mqtt/assets/25818919/0919ca4c-9d99-4727-839f-e87c25ec1300)

When I open the batteryslot. It triggers tamper

**Comment by LarsStegman** [comment]
Strange, mine don't seem to trigger when I open the battery slot

**Comment by pvangorp** [comment]
Your right. Only one gifs sabotage, the others don't. I bought one earlier than the others. Might be a batch difference?!

**Comment by LarsStegman** [comment]
What is the firmware version of each sensor?

**Comment by pvangorp** [comment]
All of them have firmware 1.0.19

**Comment by mklooss** [comment]
this Topic is about OTA and not the Tamper, could u create an ticket here:
https://github.com/Koenkk/zigbee-herdsman-converters

**Comment by x2005254** [comment]
Hello, 

from z2m 1.35.1, the plugin crash if I tried to add a new parasoll with this error :
TypeError: Cannot read properties of undefined (reading 'resolveDefinition')
 at Controller.<anonymous> (/var/www/html/plugins/z2m/resources/zigbee2mqtt/lib/zigbee.ts:89:26)
    at Controller.emit (node:events:517:28)
    at Controller.selfAndDeviceEmit (/var/www/html/plugins/z2m/resources/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:527:14)
    at Controller.onDeviceJoined (/var/www/html/plugins/z2m/resources/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:586:22)

should I update the zigbee.ts with the one available there 
https://github.com/Koenkk/zigbee-herdsman-converters

but it's not an external converter right?

**Comment by usma0118** [comment]
Still valid.

**Comment by MrAdam** [comment]
Still relevant

**Comment by LarsStegman** [comment]
Not stale

**Comment by sjorge** [comment]
The device does have OTA enabled, see https://github.com/Koenkk/zigbee-herdsman-converters/blob/4b7c15c91a5f8582c18ab7a4d46123a1db45d062/src/devices/ikea.ts#L943

It probably means there are no ota images available yet, or if there are they are not added to https://github.com/Koenkk/zigbee-OTA

**Comment by LarsStegman** [comment]
Okay, then it can be closed right?

**Comment by sjorge** [comment]
> Okay, then it can be closed right?

I think so, and if there is an ota image available that is not in zigbee-OTA it probably worth trying to add it your self or open an issue with the URL to the image so someone else can add it.
