### ISSUE TITLE
zigbee2mqtt starts and stops after a few seconds

### ISSUE THREAD

**Issue by Alex12358795** [Koenkk/zigbee2mqtt#20715]
### What happened?

I migrated to a new drive on Synology 7.2, removed Container Manager (Docker) and reinstalled. All the containers have been reinstalled and are all working, except zigbee2mqtt which starts and stops after a few seconds.

### What did you expect to happen?

zigbee2mqtt to keep running

### How to reproduce it (minimal and precise)

n/a

### Zigbee2MQTT version

No access to frontend / latest version as of 10/01/2024

### Adapter firmware version

No access to frontend

### Adapter

ZBdongle-P

### Setup

Docker (Container manager) on Synology 7.2 ds920+

### Debug log

<html>
<body>

2024/01/10 11:22:49 | stderr | at read (/app/lib/util/settings.ts:333:20)
-- | -- | --
2024/01/10 11:22:49 | stderr | at Object.read (/app/lib/util/yaml.ts:7:29)
2024/01/10 11:22:49 | stderr | at Object.load (/app/node_modules/js-yaml/lib/loader.js:1714:19)
2024/01/10 11:22:49 | stderr | at loadDocuments (/app/node_modules/js-yaml/lib/loader.js:1688:5)
2024/01/10 11:22:49 | stderr | at readDocument (/app/node_modules/js-yaml/lib/loader.js:1625:3)
2024/01/10 11:22:49 | stderr | at composeNode (/app/node_modules/js-yaml/lib/loader.js:1441:12)
2024/01/10 11:22:49 | stderr | at readBlockMapping (/app/node_modules/js-yaml/lib/loader.js:1173:9)
2024/01/10 11:22:49 | stderr | at storeMappingPair (/app/node_modules/js-yaml/lib/loader.js:358:7)
2024/01/10 11:22:49 | stderr | at throwError (/app/node_modules/js-yaml/lib/loader.js:187:9)
2024/01/10 11:22:49 | stderr | at generateError (/app/node_modules/js-yaml/lib/loader.js:183:10)
2024/01/10 11:22:49 | stderr | 14 \|   host: 192.168.178.33
2024/01/10 11:22:49 | stderr | 13 \|   port: 8081
2024/01/10 11:22:49 | stderr | ------^
2024/01/10 11:22:49 | stderr | 12 \| frontend:
2024/01/10 11:22:49 | stderr | 11 \| frontend: true
2024/01/10 11:22:49 | stderr | 10 \|   port: /dev/ttyUSB0
2024/01/10 11:22:49 | stderr | 9 \| serial:
2024/01/10 11:22:49 | stderr |  
2024/01/10 11:22:49 | stderr | YAMLException: duplicated mapping key (12:1)
2024/01/10 11:22:49 | stderr | ^
2024/01/10 11:22:49 | stderr | return new YAMLException(message, mark);
2024/01/10 11:22:49 | stderr | /app/node_modules/js-yaml/lib/loader.js:183
2024/01/10 11:22:49 | stderr |  
2024/01/10 11:22:48 | stdout | Using '/app/data' as data directory
2024/01/10 11:22:16 | stderr | at read (/app/lib/util/settings.ts:333:20)
2024/01/10 11:22:16 | stderr | at Object.read (/app/lib/util/yaml.ts:7:29)
2024/01/10 11:22:16 | stderr | at Object.load (/app/node_modules/js-yaml/lib/loader.js:1714:19)
2024/01/10 11:22:16 | stderr | at loadDocuments (/app/node_modules/js-yaml/lib/loader.js:1688:5)
2024/01/10 11:22:16 | stderr | at readDocument (/app/node_modules/js-yaml/lib/loader.js:1625:3)
2024/01/10 11:22:16 | stderr | at composeNode (/app/node_modules/js-yaml/lib/loader.js:1441:12)
2024/01/10 11:22:16 | stderr | at readBlockMapping (/app/node_modules/js-yaml/lib/loader.js:1173:9)
2024/01/10 11:22:16 | stderr | at storeMappingPair (/app/node_modules/js-yaml/lib/loader.js:358:7)
2024/01/10 11:22:16 | stderr | at throwError (/app/node_modules/js-yaml/lib/loader.js:187:9)
2024/01/10 11:22:16 | stderr | at generateError (/app/node_modules/js-yaml/lib/loader.js:183:10)
2024/01/10 11:22:16 | stderr | 14 \|   host: 192.168.178.33
2024/01/10 11:22:16 | stderr | 13 \|   port: 8081
2024/01/10 11:22:16 | stderr | ------^
2024/01/10 11:22:16 | stderr | 12 \| frontend:
2024/01/10 11:22:16 | stderr | 11 \| frontend: true
2024/01/10 11:22:16 | stderr | 10 \|   port: /dev/ttyUSB0
2024/01/10 11:22:16 | stderr | 9 \| serial:
2024/01/10 11:22:16 | stderr |  
2024/01/10 11:22:16 | stderr | YAMLException: duplicated mapping key (12:1)
2024/01/10 11:22:16 | stderr | ^
2024/01/10 11:22:16 | stderr | return new YAMLException(message, mark);
2024/01/10 11:22:16 | stderr | /app/node_modules/js-yaml/lib/loader.js:183
2024/01/10 11:22:15 | stderr |  
2024/01/10 11:22:14 | stdout | Using '/app/data' as data directory
2024/01/10 11:21:48 | stderr | at read (/app/lib/util/settings.ts:333:20)
2024/01/10 11:21:48 | stderr | at Object.read (/app/lib/util/yaml.ts:7:29)
2024/01/10 11:21:48 | stderr | at Object.load (/app/node_modules/js-yaml/lib/loader.js:1714:19)
2024/01/10 11:21:48 | stderr | at loadDocuments (/app/node_modules/js-yaml/lib/loader.js:1688:5)
2024/01/10 11:21:48 | stderr | at readDocument (/app/node_modules/js-yaml/lib/loader.js:1625:3)
2024/01/10 11:21:48 | stderr | at composeNode (/app/node_modules/js-yaml/lib/loader.js:1441:12)
2024/01/10 11:21:48 | stderr | at readBlockMapping (/app/node_modules/js-yaml/lib/loader.js:1173:9)
2024/01/10 11:21:48 | stderr | at storeMappingPair (/app/node_modules/js-yaml/lib/loader.js:358:7)
2024/01/10 11:21:48 | stderr | at throwError (/app/node_modules/js-yaml/lib/loader.js:187:9)
2024/01/10 11:21:48 | stderr | at generateError (/app/node_modules/js-yaml/lib/loader.js:183:10)
2024/01/10 11:21:48 | stderr | 14 \|   host: 192.168.178.33
2024/01/10 11:21:48 | stderr | 13 \|   port: 8081

</body>
</html>

**Comment by Alex12358795** [comment]
**Formatted the syntax below**

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/akomr/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/akomr/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


zigbee2mqtt
--
date,stream,content
2024/01/10 11:46:07,stderr,    at read   (/app/lib/util/settings.ts:333:20)
 
2024/01/10 11:46:07,stderr,    at Object.read   (/app/lib/util/yaml.ts:7:29)
 
2024/01/10 11:46:07,stderr,    at Object.load   (/app/node_modules/js-yaml/lib/loader.js:1714:19)
 
2024/01/10 11:46:07,stderr,    at loadDocuments   (/app/node_modules/js-yaml/lib/loader.js:1688:5)
 
2024/01/10 11:46:07,stderr,    at readDocument   (/app/node_modules/js-yaml/lib/loader.js:1625:3)
 
2024/01/10 11:46:07,stderr,    at composeNode   (/app/node_modules/js-yaml/lib/loader.js:1441:12)
 
2024/01/10 11:46:07,stderr,    at readBlockMapping   (/app/node_modules/js-yaml/lib/loader.js:1173:9)
 
2024/01/10 11:46:07,stderr,    at storeMappingPair   (/app/node_modules/js-yaml/lib/loader.js:358:7)
 
2024/01/10 11:46:07,stderr,    at throwError   (/app/node_modules/js-yaml/lib/loader.js:187:9)
 
2024/01/10 11:46:07,stderr,    at generateError   (/app/node_modules/js-yaml/lib/loader.js:183:10)
 
2024/01/10 11:46:07,stderr, 14 \|   host: 192.168.178.33
 
2024/01/10 11:46:07,stderr, 13 \|   port: 8081
 
2024/01/10 11:46:07,stderr,------^
 
2024/01/10 11:46:07,stderr, 12 \|   frontend:
 
2024/01/10 11:46:07,stderr, 11 \|   frontend: true
 
2024/01/10 11:46:07,stderr, 10 \|   port: /dev/ttyUSB0
 
2024/01/10 11:46:07,stderr,  9 \| serial:
 
2024/01/10 11:46:07,stderr,
 
2024/01/10 11:46:07,stderr,YAMLException:   duplicated mapping key (12:1)
 
2024/01/10 11:46:07,stderr,         ^
 
2024/01/10 11:46:07,stderr,"  return new YAMLException(message, mark)



</body>

</html>

**Comment by Alex12358795** [comment]
Had a mistake in my config

Advanced: was double in the config file - big thanks to the Discord for helping me out!
