### ISSUE TITLE
Stacktrace during the configure

### ISSUE THREAD

**Issue by rclsilver** [Koenkk/zigbee2mqtt#20833]
### What happened?

At startup, I have stacktrace during the configuration of my devices.

**LiXee:**
```
error 2024-01-16 06:50:40: Failed to configure 'linky', attempt 1 (Error: ConfigureReporting 0x00158d0005d2a0c7/1 seMetering([{"attribute":"currentTier4SummDelivered","minimumReportInterval":60,"maximumReportInterval":900,"reportableChange":100}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'SOFTWARE_FAILURE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:321:28)
    at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:665:22)
    at async Promise.allSettled (index 4)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/lixee.ts:891:14)
    at Configure.configure (/app/lib/extension/configure.ts:117:13))
```

**Profalux cover:**
```
error 2024-01-16 06:50:16: Failed to configure 'bureau_cover', attempt 1 (Error: ConfigureReporting 0x20918a00000dacd4/1 closuresWindowCovering([{"attribute":"currentPositionLiftPercentage","minimumReportInterval":1,"maximumReportInterval":65000,"reportableChange":1}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:321:28)
    at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:665:22)
    at Object.currentPositionLiftPercentage (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:49:5)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/profalux.ts:91:13)
    at Configure.configure (/app/lib/extension/configure.ts:117:13)
    at Immediate.<anonymous> (/app/lib/extension/configure.ts:69:17))
```

### Zigbee2MQTT version

1.35.0 commit: b5a90e9

### Adapter firmware version

2103

### Adapter

zigate

### Setup

Docker container

**Comment by rclsilver** [comment]
About the profalux covers, I guess it is related to https://github.com/Koenkk/zigbee-herdsman-converters/commit/893fa578581d1303741b9e3194377af4a0441a65: the `brightness` function has been replaced by `currentPositionLiftPercentage`
