### ISSUE TITLE
    TONGOU   TO-Q-SY2-163JZT

### ISSUE THREAD

**Issue by dann032** [Koenkk/zigbee2mqtt#20838]
### What happened?

Hello. 
I set the fuse to disconnect when the voltage is below 200v and above 240v.
The product works ok until the overvoltage / overcurrent protection becomes active, then  the fuse turn off(this is ok) but z2mqtt add-on crash.

### What did you expect to happen?

z2mqtt don't crash  when protection become active

### How to reproduce it (minimal and precise)

Activate voltage/current/power protection. 

### Zigbee2MQTT version

    1.35.1

### Adapter firmware version

7.3.1.0 build 176 / 7.3.2.0 build 212

### Adapter

Sonoff dongle-E

### Setup

Z2MQTT add-on, Raspberry pi 3B+, Latest HA OS

### Debug log

Zigbee2MQTT:debug 2024-01-16 12:16:25: Received Zigbee message from 'E-fuse1', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2024-01-16 12:16:25: MQTT publish: topic 'zigbee2mqtt/E-fuse1', payload '{"current":0,"energy":0.47,"indicator_mode":"on/off","linkquality":248,"over_current_breaker":"ON","over_current_threshold":2,"over_voltage_breaker":"ON","over_voltage_threshold":232,"power":0,"power_breaker":"OFF","power_outage_memory":"restore","power_threshold":1,"state":"OFF","temperature":27.44,"temperature_breaker":"ON","temperature_threshold":40,"under_voltage_breaker":"ON","under_voltage_threshold":191,"update":{"installed_version":67,"latest_version":-1,"state":"idle"},"update_available":null,"voltage":233}'
Error: Cluster 'genOnOff' has no command 'notification'
    at Object.getCommand (/app/node_modules/zigbee-herdsman/src/zcl/utils.ts:114:19)
    at Function.create (/app/node_modules/zigbee-herdsman/src/zcl/zclFrame.ts:49:25)
    at EZSPAdapter.processMessage (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:121:39)
    at Driver.emit (node:events:517:28)
    at Driver.handleFrame (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:277:22)
    at Ezsp.emit (node:events:517:28)
    at Ezsp.onFrameReceived (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:340:28)
    at SerialDriver.emit (node:events:517:28)
    at SerialDriver.handleDATA (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:226:14)
    at SerialDriver.onParsed (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:174:22)

**Comment by Koenkk** [comment]
Could you provide the herdsman debug log of this error?

See [this](https://www.zigbee2mqtt.io/guide/usage/debug.html) on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by dann032** [comment]
I have attached 3 logs, the first is when the protection becomes active (over voltage in the present case), the 2nd is after a restart of the add-on and the 3rd is after the 2nd attempt to restart the add-on. 
In order for z2mqtt to become functional I had to reboot the whole system (Raspberry pi3), I hope it contains the necessary information. 
Thank you.
[1 fuse protection .txt](https://github.com/Koenkk/zigbee2mqtt/files/13973368/1.fuse.protection.txt)
[2 restart add-on.txt](https://github.com/Koenkk/zigbee2mqtt/files/13973369/2.restart.add-on.txt)
[3 2nd restart add-on.txt](https://github.com/Koenkk/zigbee2mqtt/files/13973386/3.2nd.restart.add-on.txt)

**Comment by Koenkk** [comment]
Pushed a fix!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by dann032** [comment]
Hello!
I tested with z2mqtt edge and sonoff dongle-e fw 7.4.0.0 and now it works ok, no add-on crash.

TO-Q-SY2-163JZT shouldn't expose something like "protection active" = true or false, something to notify that a protection is activated? Can something like this be added?

Thank you for your time.

**Comment by Koenkk** [comment]
Not sure about that, don't have the device. Maybe can be added if we have a [datapoint](https://www.zigbee2mqtt.io/advanced/support-new-devices/03_find_tuya_data_points.html) for it.
