### ISSUE TITLE
EnOcean PTM 216Z - (reading 'raw')

### ISSUE THREAD

**Issue by wayetii** [Koenkk/zigbee2mqtt#20845]
### What happened?

Hello,

I wan't use my pushbutton transmitter module "EnOcean PTM 216Z " with my SONOFF ZBDongle-E (EFR32MG21).

The device pairs on channel 11 and appears in the list of devices. 

```
info 2024-01-16 17:21:16Successfully interviewed '0x0000000001555c05', device has successfully been paired
info 2024-01-16 17:21:16Device '0x0000000001555c05' is supported, identified as: EnOcean Pushbutton transmitter module (PTM 216Z)
info 2024-01-16 17:21:16MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Pushbutton transmitter module","exposes":[{"access":1,"description":"Triggered action (e.g. a button click)","label":"Action","name":"action","property":"action","type":"enum","values":["press_1","press_2","press_1_and_2","press_3","press_1_and_3","press_3_and_4","press_1_and_2_and_3","press_4","press_1_and_4","press_2_and_4","press_1_and_2_and_4","press_3_and_4","press_1_and_3_and_4","press_2_and_3_and_4","press_all","press_energy_bar","release"]},{"access":1,"description":"Link quality (signal strength)","label":"Linkquality","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"PTM 216Z","options":[],"supports_ota":false,"vendor":"EnOcean"},"friendly_name":"0x0000000001555c05","ieee_address":"0x0000000001555c05","status":"successful","supported":true},"type":"device_interview"}'
```

But when I press any button, I obtain the error "Exception while calling fromZigbee converter: Cannot read properties of undefined (reading 'raw')}".

```
debug 2024-01-16 18:37:03Received Zigbee message from '0x0000000001555c05', type 'commandNotification', cluster 'greenPower', data '{"commandID":105,"frameCounter":222,"srcID":22371333}' from endpoint 242 with groupID null
error 2024-01-16 18:37:03Exception while calling fromZigbee converter: Cannot read properties of undefined (reading 'raw')}
debug 2024-01-16 18:37:03TypeError: Cannot read properties of undefined (reading 'raw') at Object.convert (/app/node_modules/zigbee-herdsman-converters/src/converters/fromZigbee.ts:3439:62) at Receive.onDeviceMessage (/app/lib/extension/receive.ts:147:51) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:167:23) at EventEmitter.emit (node:events:529:35) at EventBus.emitDeviceMessage (/app/lib/eventBus.ts:101:22) at Controller.<anonymous> (/app/lib/zigbee.ts:115:27)
debug 2024-01-16 18:37:03Received Zigbee message from '0x0000000001555c05', type 'commandNotification', cluster 'greenPower', data '{"commandID":106,"frameCounter":223,"srcID":22371333}' from endpoint 242 with groupID null
error 2024-01-16 18:37:03Exception while calling fromZigbee converter: Cannot read properties of undefined (reading 'raw')}
debug 2024-01-16 18:37:03TypeError: Cannot read properties of undefined (reading 'raw') at Object.convert (/app/node_modules/zigbee-herdsman-converters/src/converters/fromZigbee.ts:3439:62) at Receive.onDeviceMessage (/app/lib/extension/receive.ts:147:51) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:167:23) at EventEmitter.emit (node:events:529:35) at EventBus.emitDeviceMessage (/app/lib/eventBus.ts:101:22) at Controller.<anonymous> (/app/lib/zigbee.ts:115:27)
```

### What did you expect to happen?

I expect "action" to return one of the following values `press_1, press_2, press_1_and_2, press_3, press_1_and_3, press_3_and_4, press_1_and_2_and_3, press_4, press_1_and_4, press_2_and_4, press_1_and_2_and_4, press_3_and_4, press_1_and_3_and_4, press_2_and_3_and_4, press_all, press_energy_bar, release`

### How to reproduce it (minimal and precise)

Just pair the module and press any button

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

6.10.3.0 build 297

### Adapter

SONOFF ZBDongle-E (EFR32MG21)

### Setup

Add-on on Home Assistant OS - Home assistant is a virtual machine on Synology NAS

### Debug log

[log.txt](https://github.com/Koenkk/zigbee2mqtt/files/13954340/log.txt)

**Comment by wayetii** [comment]
Problem resolved after updating with version 7.4.1 of the SONOFF Dongle-E adapter (cf. https://github.com/Koenkk/zigbee2mqtt/discussions/21462 )

Thanks @chris-1243 for your help
