### ISSUE TITLE
when recofigure the device: failed (AREQ - ZDO - bindRsp after 10000ms)

### ISSUE THREAD

**Issue by cropse** [Koenkk/zigbee2mqtt#20911]
### What happened?

I think I encountered the [issue](https://github.com/Koenkk/zigbee2mqtt/discussions/9216)

```
Failed to configure (Bind 0x00124b0022e95928/1 genOnOff from '0x00124b002c3abd90/1' failed (AREQ - ZDO - bindRsp after 10000ms))
Failed to configure '[Living] Finger button', attempt 2 (Error: Bind 0x00124b0022e95928/1 genOnOff from '0x00124b002c3abd90/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:569:17) at processTimers (node:internal/timers:512:7))
```

### What did you expect to happen?

Should be configure right, at least no more retry for 10 time and still not working.

### How to reproduce it (minimal and precise)

WB01 or MS01, most device is not working.

### Zigbee2MQTT version

 1.35.1

### Adapter firmware version

20230507

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

### Setup

VM and usb passthrough the adapter

### Debug log

Failed to configure (Bind 0x00124b0022e95928/1 genOnOff from '0x00124b002c3abd90/1' failed (AREQ - ZDO - bindRsp after 10000ms))
Failed to configure '[Living] Finger button', attempt 2 (Error: Bind 0x00124b0022e95928/1 genOnOff from '0x00124b002c3abd90/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:569:17) at processTimers (node:internal/timers:512:7))

**Comment by cropse** [comment]
And when I keep trying, some device is recognized but if I keep reconfigrate it, it show up this log and service just down:
```
{"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))
Error: Command 0xa4c138a91a4a748a/1 ssIasZone.enrollRsp({"enrollrspcode":0,"zoneid":23}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23)
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
```
