### ISSUE TITLE
Error when running update.sh: Cannot read property 'ajv' of undefined

### ISSUE THREAD

**Issue by iamkaransharma** [Koenkk/zigbee2mqtt#20960]
### What happened?

On the frontend, I changed the Zigbee channel from 11 to 25 and clicked the "Restart" button. After Z2M failed to load for ~10 minutes, I then went to the installation folder and ran `sudo ./update.sh`, which failed with this trace:

```
Stopping Zigbee2MQTT...
Creating backup of configuration...
Checking out changes to package-lock.json...
Updated 0 paths from the index
Updating...
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
Installing dependencies...
npm WARN prepare removing existing node_modules/ before installation
npm ERR! Cannot read property 'ajv' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2024-01-23T16_17_33_454Z-debug.log
```

/home/pi/.npm/_logs/2024-01-23T16_17_33_454Z-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'ci' ]
2 info using npm@6.14.18
3 info using node@v14.21.3
4 verbose npm-session 3f628af632bf6d8d
5 info prepare initializing installer
6 verbose prepare starting workers
7 verbose prepare installation prefix: /opt/zigbee2mqtt
8 verbose prepare using package-lock.json
9 warn prepare removing existing node_modules/ before installation
10 verbose checkLock verifying package-lock data
11 verbose teardown shutting down workers.
12 info teardown Done in 0.001s
13 verbose stack TypeError: Cannot read property 'ajv' of undefined
13 verbose stack     at /usr/lib/node_modules/npm/node_modules/lock-verify/index.js:27:40
13 verbose stack     at Array.forEach (<anonymous>)
13 verbose stack     at /usr/lib/node_modules/npm/node_modules/lock-verify/index.js:25:25
14 verbose cwd /opt/zigbee2mqtt
15 verbose Linux 6.1.21-v7l+
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "ci"
17 verbose node v14.21.3
18 verbose npm  v6.14.18
19 error Cannot read property 'ajv' of undefined
20 verbose exit [ 1, true ]
```

### What did you expect to happen?

Update script should complete without errors

### How to reproduce it (minimal and precise)

Inside the Z2M directory, run `./update.sh`. It is unclear if changing the Zigbee channel, and restarting via the frontend are relevant to reproducing this bug.

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

(cannot access frontend to check)

### Adapter

Sonoff ‎ZBDongle-P

### Setup

Plain install on Raspberry Pi 4

**Comment by iamkaransharma** [comment]
Fixed it by updating nodejs from 14.21.3 to 20.11.0 as per https://www.zigbee2mqtt.io/guide/installation/01_linux.html#installing.

@Koenkk  Should the update.sh script should be amended to check for the minimum compatible node version?
