### ISSUE TITLE
Error: SREQ '--> AF - dataRequestExt 

### ISSUE THREAD

**Issue by Mathadon** [Koenkk/zigbee2mqtt#21019]
### What happened?

Yesterday I have updated Z2M from cdf62ea to the master branch 3c96204. Initially everything worked fine but this night the process crashed/stopped with the following error message:

```
Error: SREQ '--> AF - dataRequestExt - {"dstaddrmode":2,"dstaddr":"0x000000000000fffd","destendpoint":242,"dstpanid":0,"srcendpoint":242,"clusterid":33,"transid":159,"options":0,"radius":30,"len":6,"data":{"type":"Buffer","data":[25,190,2,11,254,0]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)')

at Object.func (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:322:27)

at Queue.executeNext (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
```

I have made no other significant changes than this software update.

Possibly relevant though: I had some issues running update.sh. The script does not work since it runs with `-e` by default and the command to stop the Z2M service failed since I'm not running Z2M as a service but instead start it using a cron job. So I manually called `git pull && npm ci && npm run build` instead.

### What did you expect to happen?

No crash ☺️

### Zigbee2MQTT version

1.35.1

### Adapter firmware version

3.2.6 revision 20211115

### Adapter

D4F CC2531

### Setup

On rPi4 with ubuntu.

**Comment by Mathadon** [comment]
@Koenkk thanks for the feedback. I ordered a new dongle and will report back once I know more.

**Comment by Mathadon** [comment]
I had some problems with the Sonoff dongle and ordered an SLZB-06 instead. Updated to the latest Z2M and the problem seems to have disappeared..
