### ISSUE TITLE
Fails to connect to "TCP ZBBridge Pro" device

### ISSUE THREAD

**Issue by ribz** [Koenkk/zigbee2mqtt#21032]
### What happened?

When starting the zigbee2mqtt container, it runs for around 13 seconds and restarts.

### What did you expect to happen?

I expected that zigbee2mqtt would start.

### How to reproduce it (minimal and precise)

Tasmota (13.3.0) on a Sonoff Zigbee Bridge Pro (installed following these [instuctions](https://notenoughtech.com/home-automation/tasmota-on-sonoff-zb-bridge-pro/)).

I'm trying to get zigbee2mqtt to run in a docker container, started with:

```
docker run \
   -e DEBUG=zigbee-herdsman* \
   --name zigbee2mqtt  \
  --restart=unless-stopped \
   -p 8080:8080 \
   -v $(pwd)/data:/app/data  \
  -v /run/udev:/run/udev:ro \
   -e TZ=Europe/London \
  koenkk/zigbee2mqtt:latest-dev
```

configuration.yaml:

```
homeassistant: true

frontend:
  port: 8080
  host: 0.0.0.0

permit_join: true

mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://172.17.0.1'

serial:
  port: 'tcp://192.168.1.20:8888'
  adapter: ezsp
  
advanced:
  log_level: debug
```

I have tested that the Tasmota TCP link works using [zigpy_znp](https://github.com/zigpy/zigpy-znp):

`python3 -m zigpy_znp.tools.nvram_read -v socket://192.168.1.20:8888`

Returns data, as does

`python3 -m zigpy_znp.tools.energy_scan -v socket://192.168.1.20:8888`

which returns realtime data, so I don't think I've got the install on the Sonoff incorrect.

### Zigbee2MQTT version

1.35.1-dev (commit #a879382)

### Adapter firmware version

Cannot get to frontend to find out

### Adapter

Sonoff Zigbee Bridge Pro running TCP ZBBridge Pro

### Setup

Docker container (x86-64)

### Debug log

```
Zigbee2MQTT:debug 2024-01-26 19:32:02: Loaded state from file /app/data/state.json  
Zigbee2MQTT:info  2024-01-26 19:32:02: Logging to console and directory: '/app/data/log/2024-01-26.19-32-02' filename: log.txt  
Zigbee2MQTT:debug 2024-01-26 19:32:02: Removing old log directory '/app/data/log/2024-01-26.19-28-33'
Zigbee2MQTT:info  2024-01-26 19:32:02: Starting Zigbee2MQTT version 1.35.1-dev (commit #a879382)
Zigbee2MQTT:info  2024-01-26 19:32:02: Starting zigbee-herdsman (0.33.2)
Zigbee2MQTT:debug 2024-01-26 19:32:02: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"ezsp","path":"tcp://192.168.1.20:8888"}}'
2024-01-26T19:32:03.036Z zigbee-herdsman:adapter:ezsp:debg Adapter concurrent: 8
2024-01-26T19:32:03.037Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"tcp://192.168.1.20:8888","adapter":"ezsp"},"databasePath":"/app/data/database.db","databaseBackupPath":"/app/data/database.db.backup","backupPath":"/app/data/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2024-01-26T19:32:03.039Z zigbee-herdsman:adapter:ezsp:uart Opening TCP socket with 192.168.1.20:8888
2024-01-26T19:32:03.178Z zigbee-herdsman:adapter:ezsp:uart Socket connected
2024-01-26T19:32:03.179Z zigbee-herdsman:adapter:ezsp:uart Socket ready
2024-01-26T19:32:03.179Z zigbee-herdsman:adapter:ezsp:uart Uart reseting
2024-01-26T19:32:03.180Z zigbee-herdsman:adapter:ezsp:uart --> Write reset
2024-01-26T19:32:03.182Z zigbee-herdsman:adapter:ezsp:uart --> [1ac038bc7e]
2024-01-26T19:32:03.182Z zigbee-herdsman:adapter:ezsp:uart -?- waiting reset
2024-01-26T19:32:13.188Z zigbee-herdsman:adapter:ezsp:uart --> Error: Error: {"sequence":-1} after 10000ms
Error: Reset error: Error: {"sequence":-1} after 10000ms
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:316:23
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
    at Socket.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:145:17)
```

**Comment by ribz** [comment]
The clue's in what worked and what didn't. The device is znp, not ezsp!

```
  adapter: zstack
```
instead of the ezsp line works somewhat better!
