### ISSUE TITLE
Error: DatabaseEntry with ID already exists - crash

### ISSUE THREAD

**Issue by kucharskim** [Koenkk/zigbee2mqtt#21127]
### What happened?

```
Error: DatabaseEntry with ID '24' already exists
    at Database.insert (/data/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/database.ts:40:19)
    at Device.undelete (/data/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/device.ts:438:25)
    at Controller.onDeviceJoined (/data/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:555:20)
```

### What did you expect to happen?

Not to crash.

### How to reproduce it (minimal and precise)

- permit_join is true in configuration.yaml
- I reset IKEA's TRADFRI Driver 30W to start pairing
- It showed up in the device list with IEEE Address on the list, but with red Z icon, Manufacturer Unsupported
- It also had red exclamation mark, interview failed
- Interview completed was false
- That device got stuck like that on the list, I tried to delete it with force=disabled
- Deletion failed
- I repeat deletion with force=enabled
- Deletion succeeded
- I press reset / pairing pin again on IKEA's TRADFRI Driver 30W to start pairing again
- zigbee2mqtt crashed with database entry already exists

Coordinator type: EZSP v8
Coordinator revision: 6.10.3.0 build 297
Zigbee-herdsman-converters version: 18.9.0
Zigbee-herdsman version: 0.30.0
Frontend version: 0.6.151

### Zigbee2MQTT version

1.35.1 commit: 3c96204

### Adapter firmware version

6.10.3.0 build 297

### Adapter

ITEAD SONOFF Zigbee 3.0 USB Dongle Plus V2

### Setup

PC Engines APU3, OpenBSD -current, amd64, node-18.19.0

**Comment by kucharskim** [comment]
node.js process is gone after the crash:
```
# pgrep -x node | wc -l
       0
```
I don't have auto restart enabled - by design, on purpose.

**Comment by kucharskim** [comment]
Upgraded to Zigbee2MQTT version [1.35.2](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.35.2) commit: [fdc9f7d4](https://github.com/Koenkk/zigbee2mqtt/commit/fdc9f7d4), but at this moment I am not adding or removing devices to the Zigbee network, so I would need to shuffle some devices around. I need some time for this.
