### ISSUE TITLE
IKEA E2134 VALLHORN motion sensor (1.0.57)

### ISSUE THREAD

**Issue by dhruvinsh** [Koenkk/zigbee2mqtt#21231]
### What happened?

Not able to query battery status on IKEA E2134 Vallhorn motion sensor. Purchased from [here](https://www.ikea.com/ca/en/p/vallhorn-wireless-motion-sensor-smart-white-40504348) Canadian version.

### What did you expect to happen?

Read the battery status accurately. 

### How to reproduce it (minimal and precise)

Pair with zigbee2MQTT and it fail to query the battery state.

### Zigbee2MQTT version

1.35.2

### Adapter firmware version

20230507

### Adapter

Sonoff Zigbee 3.0 Dongle Plus TI CC2652P + CP2102N

### Setup

Add-on on home assistant os running under VM where usb is passthrough, all other device are getting connected.

### Debug log

```
error 2024-02-04 19:32:27Failed to configure '0x142d41fffee4e651', attempt 3 (Error: Bind 0x142d41fffee4e651/1 genPowerCfg from '0x00124b002a2f1183/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:692:28 at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:551:13) at Object.bind (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:43:9) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/ikea.ts:1244:13) at Configure.configure (/app/lib/extension/configure.ts:120:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
```

**Comment by dhruvinsh** [comment]
Looks like it took a while to kick in, after about hour I performed reconfigure and started working as expected. 

<img width="1092" alt="image" src="https://github.com/Koenkk/zigbee2mqtt/assets/33428164/3a1843b8-94fb-493d-a79c-4ed922559260">
