### ISSUE TITLE
Nous A1Z does not return energy consumption and bad

### ISSUE THREAD

**Issue by espeka44** [Koenkk/zigbee2mqtt#21250]
### What happened?

I did a fresh install of Z2M on my new RPi 5 and my smartplugs (NOUS A1Z :  _TZ3000_2putqrmw) dont show me all parameters and others are totally wrong ("current"). E.g. my freezer use to have a 35W power on 230V but Z2M display around 230A. Impossible !
All my smartplug device, don't see the "energy" which it's the sum of consumption of the plug.

Don't remember which previous Z2M version i ran on my RPi 3B+ but all theses devices properties were available and correct

### What did you expect to happen?

Works well as my old setup

### How to reproduce it (minimal and precise)

Fresh install of the latest Z2M version (1.35.2) and paring NOUS A1Z smartplug.

### Zigbee2MQTT version

1.35.2

### Adapter firmware version

 0x26720700

### Adapter

Conbee II

### Setup

Python virtual env on RPi 5

### Debug log

Failed to configure 'clothes_dryer_smartplug', attempt 1 (Error: ConfigureReporting 0xa4c1385608c58a5c/1 haElectricalMeasurement([{"attribute":"rmsCurrent","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":50}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (11)) at DeconzAdapter.sendZclFrameToEndpoint (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:666:23) at Request.send (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20) at Endpoint.configureReporting (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:669:28) at Object.rmsCurrent (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:216:5) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/devices/tuya.ts:3559:13) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:120:13) at EventEmitter.wrappedCallback (/opt/zigbee2mqtt/lib/eventBus.ts:174:17))

**Comment by espeka44** [comment]
I did a fresh install and same issue when i re-pairing theses smartplugs

```
Zigbee2MQTT:error 2024-02-08 09:46:35: Failed to configure 'hair_dryer_smartplug', attempt 2 (Error: ConfigureReporting 0xa4c13877a334d878/1 haElectricalMeasurement([{"attribute":"rmsVoltage","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":5}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (14))
    at DeconzAdapter.sendZclFrameToEndpoint (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:666:23)
    at Request.send (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)
    at Endpoint.configureReporting (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:669:28)
    at Object.rmsVoltage (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:220:5)
    at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/devices/tuya.ts:3595:13)
    at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:120:13)
    at EventEmitter.wrappedCallback (/opt/zigbee2mqtt/lib/eventBus.ts:174:17))
```

Something go wrong with the latest Z2M version cause the previous ones, it worked.

**Comment by Koenkk** [comment]
Try with the latest  [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by espeka44** [comment]
I got a error with the procedure... not sure to understand the issue
```
spk@espikabox2:/opt/zigbee2mqtt $ git checkout dev
error: pathspec 'dev' did not match any file(s) known to git
```

**Comment by Koenkk** [comment]
try: git fetch origin

**Comment by espeka44** [comment]
the procedure to switch to dev branch don't work for me. maybe it will be include in the next release, reachable after a upgrade ?

**Comment by Koenkk** [comment]
It's available in 1.36.0

**Comment by espeka44** [comment]
Still not work...
`2024-03-03 10:29:34Failed to configure '0xa4c138fad5fa7dae', attempt 1 (Error: ConfigureReporting 0xa4c138fad5fa7dae/1 haElectricalMeasurement([{"attribute":"rmsCurrent","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":50}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (10)) at DeconzAdapter.sendZclFrameToEndpoint (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:666:23) at Request.send (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20) at Endpoint.configureReporting (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:669:28) at Object.rmsCurrent (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:216:5) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/devices/tuya.ts:3653:13) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:122:13) at Immediate.<anonymous> (/opt/zigbee2mqtt/lib/extension/configure.ts:74:17))
2024-03-03 10:29:41Failed to configure 'washing_machine_smartplug', attempt 1 (Error: ConfigureReporting 0xa4c13819cd05e870/1 haElectricalMeasurement([{"attribute":"rmsCurrent","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":50}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (13)) at DeconzAdapter.sendZclFrameToEndpoint (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:666:23) at runNextTicks (node:internal/process/task_queues:60:5) at processTimers (node:internal/timers:511:9) at Request.send (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20) at Endpoint.configureReporting (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:669:28) at Object.rmsCurrent (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:216:5) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/devices/tuya.ts:3653:13) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:122:13) at EventEmitter.wrappedCallback (/opt/zigbee2mqtt/lib/eventBus.ts:174:17))`

Same data errors returned.

**Comment by espeka44** [comment]
1.36.0 don't fix my issue

**Comment by schnickalodeon** [comment]
Same problem here with Zigbe2mqtt 1.36.0-1 and Nous A1Z

**Comment by Guik** [comment]
Hello, using 1.37.1 same issue for me: after re-pairing 3 x A1Z, they stop reporting energy.

**Comment by pscoffoni** [comment]
Hi
Same problem with 1.38.0-1

**Comment by Shasdo** [comment]
Dongle SONOFF Zigbee E - Ember
MQTT 1.38.0-1

No return of Power;
OK for energy

![image](https://github.com/Koenkk/zigbee2mqtt/assets/4083901/154ac961-f1c0-4b69-9027-f6acf6ad0ca3)
![image](https://github.com/Koenkk/zigbee2mqtt/assets/4083901/1b4faa28-40cb-407a-8361-b52047599c87)

**Comment by Koenkk** [comment]
Is a power value returned when attaching a load and doing a read through the dev console?

<img width="982" alt="Screenshot 2024-07-03 at 21 58 25" src="https://github.com/Koenkk/zigbee2mqtt/assets/2892853/1f4d2839-5872-4cff-a88a-2cb6660c2414">

**Comment by espeka44** [comment]
Still not work, with lastest version of Z2M.
Any hope to have "energy" field back and a correct "current" measurement back ?

> error 2024-08-18 15:38:54z2m: Failed to configure 'washing_machine_smartplug', attempt 1 (Error: ZCL command 0xa4c13819cd05e870/1 haElectricalMeasurement.configReport([{"attribute":"rmsCurrent","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":50}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (6)) at DeconzAdapter.sendZclFrameToEndpoint (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:768:19) at runNextTicks (node:internal/process/task_queues:60:5) at processTimers (node:internal/timers:511:9) at Request.send (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:81:20) at Endpoint.zclCommand (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:866:28) at Endpoint.configureReporting (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:611:9) at Object.rmsCurrent (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:217:5) at configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/devices/tuya.ts:4983:13) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/index.ts:190:21) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:126:13))

**Comment by jojeju9428** [comment]
Hello,

Since the update to version 1.40.1, I no longer see the current power consumption in watts for my A1Z outlets.

The `haElectricalMeasurement activePower` command returns the information correctly, but I don't have the information in the state.

![image](https://github.com/user-attachments/assets/77c167d5-1efb-46e5-83b3-b66f032a940f)

![image](https://github.com/user-attachments/assets/3e605755-e18c-4ae7-8f5c-c4f774c5e0cf)

![image](https://github.com/user-attachments/assets/d8b903b1-94da-4e17-8d9b-dfd6ba7743ea)

![image](https://github.com/user-attachments/assets/c39393a6-f1e3-4669-8094-edf9c14fdcb3)

Thank you for your help.

**Comment by qsilver84** [comment]
Hi,
I have this version 1.41.0 but the energy returns 0. Recently I`ve update the firmware version up to 192 version

![image](https://github.com/user-attachments/assets/299f10f5-4b41-4a9d-988f-754a611585ad)

![image](https://github.com/user-attachments/assets/a9f664a2-fa4d-49ae-b550-f64805099baa)


Thanks

**Comment by michi2005** [comment]
Hi all

I have the same issue- newest Z2MQTT-version and newest firmware update for Nous A1Z- no power consumption visible.
Thanks in advance for looking in to this issue.

**Comment by sc-ampersand-p** [comment]
I'm also affected. Power is reported as 0 while a 2W led chain of lights is on. Current is also reported as 0.

When using a stronger consumer like a space heater, accurate values are reported.

**Comment by wtom** [comment]
Firmware 192.

So I have one plug with a led lamp and it shows power 0 W.

But I also have one with a device that takes 350-360W. And the power is stated as 35-36W. So I think they might just changed the calculation?

**Comment by peregrines2** [comment]
Had two devices out of 41 showing only 50% of the real power consumption (all of a sudden!). Repairing them removed the issue.
Unfortunately one quit responding alltogether and I was not able to pair it anymore.

Really dont know whats going on with myNous A1Z ...

**Comment by hutasje** [comment]
**[ ISSUE SOLVED (?) ]**

Dear all, 

With regards to my reported problem above, <[link](https://github.com/Koenkk/zigbee2mqtt/issues/21250#issuecomment-2761725062)> somehow I do no longer experience any issues. 

After an update warning for Z2M, I performed the update and curious to see if this fixed my A1Z issue, ... IT DID !!  

My A1Z suddenly started to report energy and power consumption again (without any physical intervention, e.g. no re-bindinding or resetting)... just a Z2M update (see below versions).   

**_.... so ... was this just a coincidence, and did I got lucky  ?_**  

(I could not find any writing about a 'fix' for the A1Z device, but a few fixes for other NOUS devices in the SW Change Log). 

**_Old:_** 
Zigbee2MQTT version 2.1.3 commit: unknown
Coordinator type zStack3x0
Coordinator revision 20230507
Coordinator IEEE Address 0x00124b002a2f0ab4
Frontend version 0.9.4
zigbee-herdsman-converters version 23.2.0
zigbee-herdsman version 3.2.7

**_Updated:_** 
Zigbee2MQTT version [2.2.1]
Coordinator type zStack3x0
Coordinator revision 20230507
Coordinator IEEE Address 0x00124b002a2f0ab4
Frontend version 0.9.7
zigbee-herdsman-converters version 23.20.1
zigbee-herdsman version 3.4.11

**Comment by espeka44** [comment]
@hutasje 

Updated for me, and still don't work...

Zigbee2MQTT version: 2.2.1commit: a2debc08
Coordinator type : ConBee2/RaspBee2
Coordinator revision : 0x26720700
Coordinator IEEE Address : 0x00.....52129
Frontend version : 0.9.7
zigbee-herdsman-converters version : 23.20.1
zigbee-herdsman version : 3.4.11

**Comment by espeka44** [comment]
Issue still going. A1Z products have been downgraded for a while and no Z2M update hasn't fixed it.

**Comment by diego351** [comment]
Still an issue

**Comment by jabber77** [comment]
The problem persists. Still no solution?

**Comment by sc-ampersand-p** [comment]
No solution as far as I'm aware.

**Comment by AndiHaas85** [comment]
Still having trouble with A1Z. Power monitoring works for minutes then returns to 0W and stays there.

**Comment by nh2** [comment]
I had the same problem with `Nous A1Z` firmware version `192`, zigbee2mqtt `1.42.0`, and `Sonoff ZBDongle-P` as coordinator.

I found that changing the Reporting options fixed the issue for me (at least for the last ~1h):

## Possible solution

Under **Reporting**, for `activePower`, change the intervals, e.g. to `Min rep interval: 1`, `max rep interval: 5`:

<img width="1554" height="80" alt="Image" src="https://github.com/user-attachments/assets/b7473e5f-db2d-4a2e-9a68-557cb2020ac8" />

I found that after doing that:

* The Z2M Reporting GUI reordered the rows (not sure if relevant).
* Fast updates of the power **continued working even after setting the intervals back to the defaults**.
  * So maybe this device has to be "initialised" this way somehow to work correctly?

Previous defaults:

<img width="1689" height="616" alt="Image" src="https://github.com/user-attachments/assets/bba714d6-8471-4058-a028-cfad7e0c1a52" />

---

My details:

```
z2m: Starting Zigbee2MQTT version 1.42.0 (commit #unknown)
z2m: Starting zigbee-herdsman (2.1.9)
zh:zstack:znp: Opening SerialPort with {"path":"/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_46a27f35c28ded1180f702f6b86ce6f8-if00-port0","baudRate":115200,"rtscts":false,"autoOpen":false}
zh:zstack:znp: Serialport opened
z2m: zigbee-herdsman started (restored)
z2m: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20240710,"transportrev":2},"type":"zStack3x0"}'
z2m: Plug 0xa4c138b80d18c69f (0xa4c138b80d18c69f): A1Z - Nous Smart plug (with power monitoring) (Router)
z2m: 0xa4c13880d7234ea9 (0xa4c13880d7234ea9): A1Z - Nous Smart plug (with power monitoring) (Router)
```

**Comment by sc-ampersand-p** [comment]
I tried what @nh2 suggested, but it didn't change anything.

I did, however, just notice once again that the "Energy" entity has been cumulating energy use over the past 9 months: 

<img width="1636" height="374" alt="Image" src="https://github.com/user-attachments/assets/1d4df85a-5914-45b9-b633-1d4871707a1c" />

This means that there's clearly some measuring going on. If the Power didn't register, how would the plug know about the Energy and be able to report it?

**Comment by espeka44** [comment]
Issue still here

**Comment by LiquidWicked** [comment]
I have the same issue with one of my Nous A1Z plugs (I have 4)! The plug was reporting the current in thousands of amperes (2000 A). I tried resetting and reconnecting the device. After reconnecting, nothing was being reported.

I then tried restoring the default settings on the Reporting tab and managed to get all values back except the energy sum, but the current was still too high.

Z2M version: 2.7.1-1 
A1Z firmware: Stack: 0.0 build 192

Core: 2025.12.1
Supervisor: 2025.12.3
Operating System: 16.3
Frontend: 20251203.1

**Comment by lu-x** [comment]
Still an issue with

Core: 2026.2.0
Supervisor: 2026.01.1
Operating System: 17.0
Frontend: 20260128.6 
Z2M: 2.8.0-1
A1Z firmware: build 192

Power value doesn't work, energy sum works

**Comment by tgaboo** [comment]
> I had the same problem with `Nous A1Z` firmware version `192`, zigbee2mqtt `1.42.0`, and `Sonoff ZBDongle-P` as coordinator.
> 
> I found that changing the Reporting options fixed the issue for me (at least for the last ~1h):
> ## Possible solution
> 
> Under **Reporting**, for `activePower`, change the intervals, e.g. to `Min rep interval: 1`, `max rep interval: 5`:
> <img alt="Image" width="1554" height="80" src="https://private-user-images.githubusercontent.com/399535/500162001-b7473e5f-db2d-4a2e-9a68-557cb2020ac8.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzA4MDUyMDEsIm5iZiI6MTc3MDgwNDkwMSwicGF0aCI6Ii8zOTk1MzUvNTAwMTYyMDAxLWI3NDczZTVmLWRiMmQtNGEyZS05YTY4LTU1N2NiMjAyMGFjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDIxMVQxMDE1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNWUxOGE5ODM1MzAyN2JjZmNlMmFlMGQ3NzNkNjczM2U3NmMzODk3ODE2YTk5MWFlZWIzZjc3NmVhMTU4ZTNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JtSmNOf33xl1p2XvKyA79294Huv7xNd_97hld94vDWs">
> 
> I found that after doing that:
> 
>     * The Z2M Reporting GUI reordered the rows (not sure if relevant).
> 
>     * Fast updates of the power **continued working even after setting the intervals back to the defaults**.
>       
>       * So maybe this device has to be "initialised" this way somehow to work correctly?
> 
> 
> Previous defaults:
> <img alt="Image" width="1689" height="616" src="https://private-user-images.githubusercontent.com/399535/500161999-bba714d6-8471-4058-a028-cfad7e0c1a52.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzA4MDUyMDEsIm5iZiI6MTc3MDgwNDkwMSwicGF0aCI6Ii8zOTk1MzUvNTAwMTYxOTk5LWJiYTcxNGQ2LTg0NzEtNDA1OC1hMDI4LWNmYWQ3ZTBjMWE1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDIxMVQxMDE1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTQ2NjZhNDNlZDkxYWY2Mzc4Y2Y5ODg4Mjg1ZWE2MWI0MmRjNTI5ZGQ4ZWNmNDEyODNhOTIwMTA0YWNmMTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VcRhEcZhAflUr9N5Bo7tTRU9bwp2iEr7TE-jb3sKDFU">
> 
> My details:
> 
> ```
> z2m: Starting Zigbee2MQTT version 1.42.0 (commit #unknown)
> z2m: Starting zigbee-herdsman (2.1.9)
> zh:zstack:znp: Opening SerialPort with {"path":"/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_46a27f35c28ded1180f702f6b86ce6f8-if00-port0","baudRate":115200,"rtscts":false,"autoOpen":false}
> zh:zstack:znp: Serialport opened
> z2m: zigbee-herdsman started (restored)
> z2m: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20240710,"transportrev":2},"type":"zStack3x0"}'
> z2m: Plug 0xa4c138b80d18c69f (0xa4c138b80d18c69f): A1Z - Nous Smart plug (with power monitoring) (Router)
> z2m: 0xa4c13880d7234ea9 (0xa4c13880d7234ea9): A1Z - Nous Smart plug (with power monitoring) (Router)
> ```

Worked for me, thank you!

**Comment by nh2** [comment]
Please don't waste our time / spam 16 participants with stalebots emails (especially not every 60 days). Most issues don't fix themselves. It should stay open while this bug exists.

**Comment by andrei-lazarov** [comment]
@nh2 Stalebot is perfectly fine imo. It brings attention to stale issues. If there is still interest and fix is possible, someone may do it. If not, close the issue. I saw activity, so I'll try to help 🙂

Yes, the plug needs reporting to show power measurements.
Z2M automatically sets-up reporting (with some reasonable defaults) for most devices, including the three Tuya devices recognized as Nous A1Z: `_TZ3000_2putqrmw, _TZ3210_2putqrmw, _TZ3000_ksw8qtmt`.
This happens immediately after pairing, during the configuration step. If it fails, it shows an error.

I understand you had to set up reporting manually. So it's likely the default reporting set-up failed.
Can you test if that is still the case in the latest version of Z2M (or any recent version)?
1. Disable all reporting entries for the plug
2. Hit the Reconfigure button
3. Tell me what error you get, or if it works (reporting gets set up like in your screenshot above)
4. Check if the plug actually follows the reportings, and displays measurements as often as configured, or it needs polling from Z2M (probably not)
5. Check if units are correct

You may additionally test it "from scratch", but it should give the same results as reconfiguring:
1. Remove plug from Z2M
2. Restart Z2M
3. Permit join (pair plug)

**Comment by nh2** [comment]
@andrei-lazarov Thanks for your input!

I've upgraded zigbee2mqtt from 1.42.0 to 2.6.3 now so that I have a reasonably new version.

I have paired that with anew Nous A1Z.

The first thing I notice is that the device does not show up as https://www.zigbee2mqtt.io/devices/A1Z.html but as https://www.zigbee2mqtt.io/devices/TS011F_plug_3.html#tuya-ts011f_plug_3 -- is that potentially relevant? All my Nous A1Z have that problem.

I changed nothing but the device name after this.

> 1. Disable all reporting entries for the plug

What exactly do I have to do for that? The `Reporting` tab looks like this:

<img width="1700" height="682" alt="Image" src="https://github.com/user-attachments/assets/e09500c5-4920-4c0e-aa3e-52f1cae5f7c7" />

When I click `Reconfigure`, it says `device/reconfigure: OK (xj5dy-4)`.

Clicking `Reconfigure` in this case does not add any new rows in the `Reporting` tab. It stays empty as in the screenshot posted in this post above.

Note that this seems to be different than my screenshot from the older zigbee2mqtt version, where there were Reporting rows (https://github.com/Koenkk/zigbee2mqtt/issues/21250#issuecomment-3393419889). The A1Z device that was used in that older screenshot is still around and looks like this in my current version:

<img width="1714" height="634" alt="Image" src="https://github.com/user-attachments/assets/917e87fc-6107-4387-a60f-4053948b68ff" />

> Check if the plug [..] needs polling from Z2M

How do I check that?

---

In this default state with 0 Reporting rows, the new A1Z I just configured does not update its Power in W when I turn on a 300 W dimmable lamp to max.

However if I create this Reporting row:

<img width="1727" height="204" alt="Image" src="https://github.com/user-attachments/assets/fd402857-398e-44d3-a335-cba4b189eee4" />

then the Power updates within a second or less when I turn it on.

Let me know if that helps!

**Comment by andrei-lazarov** [comment]
@nh2 what's the ID of this device `_TZ3000_xxxxxxxx`?

> How do I check that?

You confirmed Reporting works, so no need to poll the device for measurements.

**Comment by nh2** [comment]
> what's the ID of this device `_TZ3000_xxxxxxxx`?

It says:

> Zigbee Model
> TS011F
> _TZ3000_2putqrmw (Smart plug (with power monitoring by polling))

<img width="1477" height="659" alt="Image" src="https://github.com/user-attachments/assets/ed1445ae-473c-4e27-abd4-4732b94ef0d8" />

**Comment by andrei-lazarov** [comment]
@nh2 if device appVersion is 192
(device -> dev console -> read / write attributes -> endpoint 1 -> genBasic -> appVersion -> read)

Detection is wrong only in Z2M 2.6.3. Previous and next versions detect it as Nous A1Z and set-up reporting automatically.
So you can update and reconfigure the device, or set-up reporting manually for all measurements.
I don't think there are other issues

**Comment by nh2** [comment]
> if device appVersion is 192

Yes, it outputs `Read result of 'genBasic': {"appVersion":192}`

@andrei-lazarov I will do an update and try it.

Do you have an idea about what I reported in https://github.com/Koenkk/zigbee2mqtt/issues/21250#issuecomment-3393419889 on the old version, that changing the Reporting setting and setting it back to the default version somehow fixed the problem?

**Comment by andrei-lazarov** [comment]
It means the user interface was displaying a Reporting setting that was not successfully applied. You re-applied it successfully and it started to report.

**Comment by nh2** [comment]
I upgraded zigbee2mqtt 2.6.3 -> 2.9.2 now and the Nous A1Z is now correctly detected (as https://www.zigbee2mqtt.io/devices/A1Z.html).

Indeed, the reporting is now correct automatically. I re-paired the device I tried above to validate. I also paired another A1Z that was never before paired with my Z2M and it also works out of the box. Both devices report power changes immediately, no more need to change the reporting value once.

@andrei-lazarov Thank you very much for the help!

From my side, this is finally solved!

@sc-ampersand-p @LiquidWicked @lu-x Can you retest with the current version and report if it also fixes it for you?

**Comment by sc-ampersand-p** [comment]
@nh2 my problem was always that the devices didn't report active power when the draw was low. For example, I have one of these plugs on a 3D printer and it shows plausible values (App/Firmware Version `192`). 

I also have one of these on a little chain of fairy lights, and that has never reported any active power (the chain of lights should draw something like 3 W):

<img width="1407" height="492" alt="Image" src="https://github.com/user-attachments/assets/00218c5b-3656-4f48-8c98-c6972e69883a" />

Interestingly, the energy counter rises continuously:

<img width="1406" height="508" alt="Image" src="https://github.com/user-attachments/assets/7a8d8dad-50b3-4453-a223-91835a2ba9c3" />

I'm on Zigbee2MQTT version [2.9.2](https://github.com/Koenkk/zigbee2mqtt/releases/tag/2.9.2).

Re-configuring and re-pairing (just tried both) this device hasn't changed this behavior in any way.

**Comment by andrei-lazarov** [comment]
@sc-ampersand-p that is expected. By default, Z2M configures activePower reporting with **min rep change 5.**
So the plug will report a new value only when it's at least 5W higher/lower than the previous value.

This is to limit the number of messages and prevent network spam with insignificant differences.
But you can of course **lower that value** to monitor small changes (1-2W).

Imo monitoring 3W fairy lights is totally unnecessary. 
My recommendation is to consider the load these devices add on your Zigbee network, and to disable some reportings.
- you likely don't need voltage from every plug (it should be the same value around the house)
- you likely don't need current if you are reading wattage
- you don't need to monitor wattage for devices where the power draw is known/constant (you can "compute" it: e.g. ON = 3W, OFF = 0W)
