### ISSUE TITLE
UNSUPPORTED_ATTRIBUTE on Aqara Dual relay module T2

### ISSUE THREAD

**Issue by lost-carrier** [Koenkk/zigbee2mqtt#21281]
### What happened?

I've got a couple of Aqara Dual Relay Module T2 installed. Monitoring the logs I found exceptions throwen by them every now and then. The devices generally appear to work fine.

### What did you expect to happen?

No Exception

### How to reproduce it (minimal and precise)

Pair and configure devices, then monitor the logs. Nothing particularty to be done (I did not trigger any of the relays atm).

### Zigbee2MQTT version

1.35.2 & 1.35.3

### Adapter firmware version

20220219

### Adapter

zStack3x0 / Sonoff CC2652P

### Setup

docker on RasPi 4

### Debug log

Zigbee2MQTT:error 2024-02-07 12:26:54: Failed to configure 'garage/actor-licht', attempt 1 (Error: Read 0x54ef44100096c1bc/2 manuSpecificLumi([10], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:319:28)
    at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:469:22)
    at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:63:13)
    at configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:84:17)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:140:25)
    at Configure.configure (/app/lib/extension/configure.ts:120:13)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

...

Zigbee2MQTT:error 2024-02-07 12:27:17: Failed to configure 'schlafen/actor-licht', attempt 1 (Error: Read 0x54ef44100096f56d/2 manuSpecificLumi([10], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:319:28)
    at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:469:22)
    at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:63:13)
    at configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:84:17)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:140:25)
    at Configure.configure (/app/lib/extension/configure.ts:120:13)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

...

Zigbee2MQTT:error 2024-02-07 12:31:42: Failed to configure 'eingang/actor', attempt 3 (Error: Read 0x54ef441000969076/2 manuSpecificLumi([10], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:319:28)
    at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:469:22)
    at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:63:13)
    at configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:84:17)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:140:25)
    at Configure.configure (/app/lib/extension/configure.ts:120:13)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

**Comment by lost-carrier** [comment]
Model is listed as [LLKZMK12LM](https://www.zigbee2mqtt.io/devices/LLKZMK12LM.html#aqara-llkzmk12lm) to be precise.
