### ISSUE TITLE
Livarno Lux Ceiling Panel RGB+CCT Set Colortemp and Set Brightness gives an error

### ISSUE THREAD

**Issue by yvos** [Koenkk/zigbee2mqtt#21464]
### What happened?

Livarno Lux Ceiling Panel RGB+CCT Set Colortemp and Set Brightness gives an error
When using the Z2m frontend to set the brightness or colortemp errors appear in the log. See Debug log underneath.

### Zigbee2MQTT version

1.35.3 

### Adapter firmware version

7.3.1.0 build 0

### Adapter

Sonoff Zigbee 3 USB Dongle 

### Setup

Add-on on Home Assistent OS

### Debug log

Debug 2024-02-19 09:54:34Received MQTT message on 'zigbee2mqtt/Hal 2e Ledpaneel/set' with data '{"color_temp":454}'
Debug 2024-02-19 09:54:34Skipping state because of Home Assistant
Debug 2024-02-19 09:54:34Publishing 'set' 'color_temp' to 'Hal 2e Ledpaneel'
Debug 2024-02-19 09:54:34Missing colorTempPhysicalMin and/or colorTempPhysicalMax for endpoint 0x84b4dbfffeec9be0!
Error 2024-02-19 09:54:54Publish 'set' 'color_temp' to 'Hal 2e Ledpaneel' failed: 'Error: Command 0x84b4dbfffeec9be0/1 lightingColorCtrl.moveToColorTemp({"colortemp":454,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 64935 - 1 - 177 - 768 - 11 after 10000ms)'
Debug 2024-02-19 09:54:54Error: Command 0x84b4dbfffeec9be0/1 lightingColorCtrl.moveToColorTemp({"colortemp":454,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 64935 - 1 - 177 - 768 - 11 after 10000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:486:47) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20) at Endpoint.command (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:746:28) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:180:13) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:1207:32) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:249:36) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17)

-----------------------------------------------
Debug 2024-02-19 09:58:22Received MQTT message on 'zigbee2mqtt/Hal 2e Ledpaneel/set' with data '{"brightness":73}'
Debug 2024-02-19 09:58:22Publishing 'set' 'brightness' to 'Hal 2e Ledpaneel'
Error 2024-02-19 09:58:42Publish 'set' 'brightness' to 'Hal 2e Ledpaneel' failed: 'Error: Command 0x84b4dbfffeec9be0/1 genLevelCtrl.moveToLevelWithOnOff({"level":73,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 64935 - 1 - 182 - 8 - 11 after 10000ms)'
Debug 2024-02-19 09:58:42Error: Command 0x84b4dbfffeec9be0/1 genLevelCtrl.moveToLevelWithOnOff({"level":73,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 64935 - 1 - 182 - 8 - 11 after 10000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:486:47) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20) at Endpoint.command (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:746:28) at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:1137:13) at Publish.onMQTTMessage (/app/lib/extension/publish.ts:249:36) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17)

**Comment by yvos** [comment]
Okay I figured out the difference between the three led panels. The errors occur due to missing bindings with the coordinator.  That leaves us with the: Missing colorTempPhysicalMin and/or colorTempPhysicalMax for endpoint
