### ISSUE TITLE
SmartThings IM6001-MPP01 UNSUPPORTED_ATTRIBUTE

### ISSUE THREAD

**Issue by Madj42** [Koenkk/zigbee2mqtt#21503]
### What happened?

While configuring the reporting options on a SmartThings IM6001-MPP01 and clicking apply, I get an unsupported_attribute error.  This happens on multiple devices of the same model.

### What did you expect to happen?

Change the reporting options.

### How to reproduce it (minimal and precise)

1. Pull up the properties of device.
2. Click on the reporting tab.
3. Change any of the existing values and click apply.  This also happens if you try to disable the attribute.

### Zigbee2MQTT version

1.35.3

### Adapter firmware version

20230507

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

### Setup

add-on

### Debug log

Error 2024-02-20 13:19:38Request 'zigbee2mqtt/bridge/request/device/configure_reporting' failed with error: 'ConfigureReporting 0x286d9700010c2889/1 manuSpecificSamsungAccelerometer([{"attribute":"x_axis","minimumReportInterval":10,"maximumReportInterval":3600,"reportableChange":1000}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4362,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Debug 2024-02-20 13:19:38Error: ConfigureReporting 0x286d9700010c2889/1 manuSpecificSamsungAccelerometer([{"attribute":"x_axis","minimumReportInterval":10,"maximumReportInterval":3600,"reportableChange":1000}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4362,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:319:28) at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:672:22) at Bridge.deviceConfigureReporting (/app/lib/extension/bridge.ts:439:9) at Bridge.onMQTTMessage (/app/lib/extension/bridge.ts:128:34) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17)
Info 2024-02-20 13:19:38MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure_reporting', payload '{"data":{},"error":"ConfigureReporting 0x286d9700010c2889/1 manuSpecificSamsungAccelerometer([{\"attribute\":\"x_axis\",\"minimumReportInterval\":10,\"maximumReportInterval\":3600,\"reportableChange\":1000}], {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":4362,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')","status":"error","transaction":"h4xa5-2"}'

**Comment by Madj42** [comment]
Any chance someone might look at this?  Not sure where to diagnose this myself.
