### ISSUE TITLE
UNSUPPORTED_ATTRIBUTE Temp sensor ORVIBO ST30

### ISSUE THREAD

**Issue by saucekorn69** [Koenkk/zigbee2mqtt#21541]
### What happened?

I've successfully added a temp/humidity sensor ORVIBO ST30, it is displayed correctly on the frontend however, I have an error message which pops after a while and crashes the Zigbee2mqtt service.

The service restarts and crashes after a while again and so on.

### Zigbee2MQTT version

1.35.3

### Adapter firmware version

 6.10.3.0 build 297

### Adapter

POPP Zigbee USB Stick

### Setup

Zigbee2Mqtt deployed on DEBIAN11 VM, Mosquitto on the NAS and HA on another VM.

### Debug log

2024-02-23 14:10:14Failed to configure 'Temp Ch Timothée', attempt 1 (Error: ConfigureReporting 0x5c0272fffef6d372/2 genPowerCfg([{"attribute":"batteryVoltage","minimumReportInterval":3600,"maximumReportInterval":65000,"reportableChange":0}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:319:28) at Endpoint.configureReporting (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:672:22) at Object.batteryVoltage (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:64:5) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/devices/orvibo.ts:152:13) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:120:13) at EventEmitter.wrappedCallback (/opt/zigbee2mqtt/lib/eventBus.ts:174:17))

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by saucekorn69** [comment]
Hello,

I am having difficulties to switch to the dev branch, despite following this guide: https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html

![image](https://github.com/Koenkk/zigbee2mqtt/assets/160407829/11597de1-e452-4409-933c-46547fed4145)

Am I missing something ?

Thank you !

Nicolas.

**Comment by saucekorn69** [comment]
I found the problem: I followed the installation instructions here https://www.zigbee2mqtt.io/guide/installation/01_linux.html#installing

The git clone "depth 1" was not allowing me to switch to the dev branch.

**Comment by Koenkk** [comment]
Thanks for letting me know, I've fixed the instructions on https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html

**Comment by saucekorn69** [comment]
No problem, but the issue was in this documentation under the 'Installing" section:

https://www.zigbee2mqtt.io/guide/installation/01_linux.html#determine-location-of-the-adapter-and-checking-user-permissions
