### ISSUE TITLE
HEIMAN HS3SA-E recognized as HEIMAN HS1SA

### ISSUE THREAD

**Issue by hellcry37** [Koenkk/zigbee2mqtt#21552]
### What happened?

I bought a new device HEIMAN HS3SA-E and tray to pair works with some errors but in the end device gets paired as HEIMAN HS1SA

What i have: HEIMAN HS3SA-E
What is recognized as: HEIMAN HS1SA - https://www.zigbee2mqtt.io/devices/HS1SA.html

On pairing:
```txt
2024-02-24 12:53:27Failed to configure '0x00158d0003e4949d', attempt 1 (Error: Bind 0x00158d0003e4949d/1 genPowerCfg from '0x00124b002281a218/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Object.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:699:28 at processTicksAndRejections (node:internal/process/task_queues:95:5) at Queue.execute (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Endpoint.bind (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:551:13) at Object.bind (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:43:9) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/devices/heiman.ts:105:13) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:120:13) at EventEmitter.wrappedCallback (/opt/zigbee2mqtt/lib/eventBus.ts:174:17))
2024-02-24 12:54:06Failed to configure '0x00158d0003e4949d', attempt 2 (Error: Read 0x00158d0003e4949d/1 genPowerCfg(["batteryPercentageRemaining"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 62023 - 1 - 20 - 1 - 1 after 10000ms) at Object.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at ZStackAdapter.sendZclFrameToEndpointInternal (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:502:47) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Queue.execute (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Request.send (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20) at Endpoint.read (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:466:28) at Object.batteryPercentageRemaining (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:60:5) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/devices/heiman.ts:106:13) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:120:13) at EventEmitter.wrappedCallback (/opt/zigbee2mqtt/lib/eventBus.ts:174:17))
```

### What did you expect to happen?

Device to pair correctly as HEIMAN HS3SA-E without errors.

### How to reproduce it (minimal and precise)

Pair device as many times as you want same results.

### Zigbee2MQTT version

1.35.3 commit: fe0742a

### Adapter firmware version

20230507

### Adapter

zig-a-zig-ah!

### Setup

Run as docker image with adapter connected via TCP soket 

### Debug log

```log
debug 2024-02-24 13:28:20: Device '0x00158d0003e4949d' announced itself
error 2024-02-24 13:28:50: Failed to interview '0x00158d0003e4949d', device has not successfully been paired
debug 2024-02-24 13:28:50: Received MQTT message on 'homeassistant/binary_sensor/0x00158d0003e4949d/smoke/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"},{"topic":"zigbee2mqtt/0x00158d0003e4949d/availability","value_template":"{{ value_json.state }}"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x00158d0003e4949d"],"manufacturer":"HEIMAN","model":"Smoke detector (HS1SA)","name":"0x00158d0003e4949d","sw_version":"2000-0001","via_device":"zigbee2mqtt_bridge_0x00124b002281a218"},"device_class":"smoke","object_id":"0x00158d0003e4949d_smoke","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"payload_off":false,"payload_on":true,"state_topic":"zigbee2mqtt/0x00158d0003e4949d","unique_id":"0x00158d0003e4949d_smoke_zigbee2mqtt","value_template":"{{ value_json.smoke }}"}'
debug 2024-02-24 13:28:50: Received MQTT message on 'homeassistant/binary_sensor/0x00158d0003e4949d/battery_low/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"},{"topic":"zigbee2mqtt/0x00158d0003e4949d/availability","value_template":"{{ value_json.state }}"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x00158d0003e4949d"],"manufacturer":"HEIMAN","model":"Smoke detector (HS1SA)","name":"0x00158d0003e4949d","sw_version":"2000-0001","via_device":"zigbee2mqtt_bridge_0x00124b002281a218"},"device_class":"battery","entity_category":"diagnostic","object_id":"0x00158d0003e4949d_battery_low","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"payload_off":false,"payload_on":true,"state_topic":"zigbee2mqtt/0x00158d0003e4949d","unique_id":"0x00158d0003e4949d_battery_low_zigbee2mqtt","value_template":"{{ value_json.battery_low }}"}'
debug 2024-02-24 13:28:50: Received MQTT message on 'homeassistant/sensor/0x00158d0003e4949d/battery/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"},{"topic":"zigbee2mqtt/0x00158d0003e4949d/availability","value_template":"{{ value_json.state }}"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x00158d0003e4949d"],"manufacturer":"HEIMAN","model":"Smoke detector (HS1SA)","name":"0x00158d0003e4949d","sw_version":"2000-0001","via_device":"zigbee2mqtt_bridge_0x00124b002281a218"},"device_class":"battery","enabled_by_default":true,"entity_category":"diagnostic","object_id":"0x00158d0003e4949d_battery","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"state_class":"measurement","state_topic":"zigbee2mqtt/0x00158d0003e4949d","unique_id":"0x00158d0003e4949d_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
debug 2024-02-24 13:28:50: Received MQTT message on 'homeassistant/sensor/0x00158d0003e4949d/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"},{"topic":"zigbee2mqtt/0x00158d0003e4949d/availability","value_template":"{{ value_json.state }}"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x00158d0003e4949d"],"manufacturer":"HEIMAN","model":"Smoke detector (HS1SA)","name":"0x00158d0003e4949d","sw_version":"2000-0001","via_device":"zigbee2mqtt_bridge_0x00124b002281a218"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:signal","name":"Linkquality","object_id":"0x00158d0003e4949d_linkquality","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"state_class":"measurement","state_topic":"zigbee2mqtt/0x00158d0003e4949d","unique_id":"0x00158d0003e4949d_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
debug 2024-02-24 13:28:50: Received MQTT message on 'homeassistant/sensor/0x00158d0003e4949d/last_seen/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"},{"topic":"zigbee2mqtt/0x00158d0003e4949d/availability","value_template":"{{ value_json.state }}"}],"availability_mode":"all","device":{"identifiers":["zigbee2mqtt_0x00158d0003e4949d"],"manufacturer":"HEIMAN","model":"Smoke detector (HS1SA)","name":"0x00158d0003e4949d","sw_version":"2000-0001","via_device":"zigbee2mqtt_bridge_0x00124b002281a218"},"device_class":"timestamp","enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:clock","name":"Last seen","object_id":"0x00158d0003e4949d_last_seen","origin":{"name":"Zigbee2MQTT","sw":"1.35.3","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/0x00158d0003e4949d","unique_id":"0x00158d0003e4949d_last_seen_zigbee2mqtt","value_template":"{{ value_json.last_seen }}"}'
debug 2024-02-24 13:29:16: Received MQTT message on 'zigbee2mqtt/bridge/request/device/remove' with data '{"block":false,"force":false,"id":"0x00158d0003e4949d","transaction":"qcjmv-11"}'
debug 2024-02-24 13:29:21: Device '0x00158d0003e4949d' announced itself
error 2024-02-24 13:29:26: Request 'zigbee2mqtt/bridge/request/device/remove' failed with error: 'Failed to remove device '0x00158d0003e4949d' (block: false, force: false) (Error: AREQ - ZDO - mgmtLeaveRsp after 10000ms)'
debug 2024-02-24 13:29:26: Error: Failed to remove device '0x00158d0003e4949d' (block: false, force: false) (Error: AREQ - ZDO - mgmtLeaveRsp after 10000ms)
    at Bridge.removeEntity (/opt/zigbee2mqtt/lib/extension/bridge.ts:580:19)
    at Bridge.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/bridge.ts:128:34)
    at EventEmitter.wrappedCallback (/opt/zigbee2mqtt/lib/eventBus.ts:174:17)
debudebug 2024-02-24 13:29:35: Received Zigbee message from '0x00158d0003e4949d', type 'readResponse', cluster 'ssIasZone', data '{"iasCieAddr":"0x0000000000000000","zoneState":1}' from endpoint 1 with groupID 0
debug 2024-02-24 13:29:35: Skipping message, still interviewing
debudebug 2024-02-24 13:29:36: ZNJLBL01LM: Processed buffer into data {"3":32,"5":2,"9":256,"10":2834,"11":0,"12":1,"13":3870,"17":1,"100":0,"101":90,"102":128,"103":30,"105":1,"106":8044,"107":0}
debug 2024-02-24 13:29:36: ZNJLBL01LM: Processed data into payload {"device_temperature":32,"power_outage_count":1,"state":"OFF","battery":90}
debug 2024-02-24 13:29:36: ZNJLBL01LM: Processed data into payload {"device_temperature":32,"power_outage_count":1,"state":"OFF","battery":90}
debug 2024-02-24 13:29:42: Received Zigbee message from '0x00158d0003e4949d', type 'readResponse', cluster 'ssIasZone', data '{"iasCieAddr":"0x00124b002281a218","zoneState":1}' from endpoint 1 with groupID 0
debug 2024-02-24 13:29:42: Skipping message, still interviewing
debug 2024-02-24 13:29:45: Received Zigbee message from '0x00158d0003e4949d', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":33}' from endpoint 1 with groupID 0
debug 2024-02-24 13:29:46: Received Zigbee message from '0x00158d0003e4949d', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":32}' from endpoint 1 with groupID 0
debug 2024-02-24 13:29:48: Received Zigbee message from '0x00158d0003e4949d', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":32}' from endpoint 1 with groupID 0
debug 2024-02-24 13:29:49: Received Zigbee message from '0x00158d0003e4949d', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200}' from endpoint 1 with groupID 0
debug 2024-02-24 13:29:49: Received Zigbee message from '0x00158d0003e4949d', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":33}' from endpoint 1 with groupID 0
debug 2024-02-24 13:29:50: Received Zigbee message from '0x00158d0003e4949d', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":32}' from endpoint 1 with groupID 0
debug 2024-02-24 13:29:53: Received Zigbee message from '0x00158d0003e4949d', type 'readResponse', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200}' from endpoint 1 with groupID 0
debug 2024-02-24 13:29:56: Received Zigbee message from '0x00158d0003e4949d', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":33}' from endpoint 1 with groupID 0
debug 2024-02-24 13:29:57: Received Zigbee message from '0x00158d0003e4949d', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":32}' from endpoint 1 with groupID 0
debug 2024-02-24 13:30:05: WSDCGQ01LM: unknown key 6 with value 0,2
debug 2024-02-24 13:31:18: Received MQTT message on 'zigbee2mqtt/bridge/request/permit_join' with data '{"device":"Server Room Light","time":254,"transaction":"qcjmv-12","value":false}'
debug 2024-02-24 13:31:23: Received MQTT message on 'zigbee2mqtt/bridge/request/options' with data '{"options":{"advanced":{"adapter_concurrent":null,"adapter_delay":null,"availability_blacklist":[],"availability_blocklist":[],"availability_passlist":[],"availability_whitelist":[],"cache_state":true,"cache_state_persistent":true,"cache_state_send_on_startup":true,"channel":24,"elapsed":false,"ext_pan_id":[221,221,221,221,221,221,221,221],"last_seen":"ISO_8601","legacy_api":false,"legacy_availability_payload":false,"log_directory":"/var/log/zigbee2mqtt/%TIMESTAMP%","log_file":"log.txt","log_level":"info","log_output":["console","file"],"log_rotation":true,"log_symlink_current":true,"log_syslog":{"app_name":"Zigbee2MQTT","eol":"/n","host":"localhost","localhost":"localhost","path":"/dev/log","pid":"process.pid","port":123,"protocol":"tcp4","type":"5424"},"output":"json","pan_id":27749,"report":false,"soft_reset_timeout":0,"timestamp_format":"YYYY-MM-DD HH:mm:ss"}},"transaction":"qcjmv-13"}'
```

**Comment by hellcry37** [comment]
device also droops off the network after some time, pushing the buttons brings it up

**Comment by hellcry37** [comment]
anything else I could do to push this forward?

**Comment by hellcry37** [comment]
yah this clearly won't happen
