### ISSUE TITLE
questions regarding tcp sonoff zigbee bridge and config in HA

### ISSUE THREAD

**Issue by vrtsman** [Koenkk/zigbee2mqtt#21555]
### What happened?

Followed your instructions on 
https://www.zigbee2mqtt.io/advanced/remote-adapter/connect_to_a_remote_sonoff_zbbridge.html

but not sure what is really needed and cant make it work

from the Z2M yaml: 
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: "removed"
frontend:
  port: 8099
serial: 
  port: 'tcp://192.168.x.yy:8123' => the IP and Port of my HA installation
  adapter: ezsp

The Sonoff bridge has no special port configured to access its admin gui; just plain 192.168.x.yy same subnet as the HA instance, but HA uses port 8888 to connect for the ZHA integration with the tasmota bridge
So how does the communication flow work?
From the log using port 8123:

[17:41:44] INFO: Preparing to start...
[17:41:44] INFO: Socat not enabled
[17:41:45] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2024-02-24 17:41:48: Logging to console and directory: '/config/zigbee2mqtt/log/2024-02-24.17-41-48' filename: log.txt
Zigbee2MQTT:info  2024-02-24 17:41:48: Starting Zigbee2MQTT version 1.35.3 (commit #unknown)
Zigbee2MQTT:info  2024-02-24 17:41:48: Starting zigbee-herdsman (0.33.8)
Error: Reset error: Error: {"sequence":-1} after 10000ms
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:323:23
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
    at Socket.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:152:17)

From the log using port 8888:
[18:18:12] INFO: Preparing to start...
[18:18:12] INFO: Socat not enabled
[18:18:13] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2024-02-24 18:18:16: Logging to console and directory: '/config/zigbee2mqtt/log/2024-02-24.18-18-16' filename: log.txt
Zigbee2MQTT:info  2024-02-24 18:18:16: Starting Zigbee2MQTT version 1.35.3 (commit #unknown)
Zigbee2MQTT:info  2024-02-24 18:18:16: Starting zigbee-herdsman (0.33.8)
Zigbee2MQTT:error 2024-02-24 18:18:46: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-02-24 18:18:46: Failed to start zigbee
Zigbee2MQTT:error 2024-02-24 18:18:46: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-02-24 18:18:46: Exiting...
Zigbee2MQTT:error 2024-02-24 18:18:46: Error: Failure to connect
    at Ezsp.connect (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:364:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Driver.startup (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:158:13)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:60:27)
    at Controller.start (/app/lib/controller.ts:109:27)
    at start (/app/index.js:107:5)

MQTT works: 1 Device attached (AI on the edge watermeter)
Zigbee works: 47 devices attached

Dirk

### Zigbee2MQTT version

Current version: 1.35.3-1

### Adapter firmware version

13.3.0(zbbrdgpro)

### Adapter

Tasmota/Sonoff TCP ZBBridge Pro

### Setup

HA on Intel NUC (HA as vhdx)

**Comment by Genzzry** [comment]
Similar issue here.
HA-Core updated, then Zigbee2MQTT stopped working:

[18:22:48] INFO: Preparing to start...
[18:22:49] INFO: Socat not enabled
[18:22:51] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2024-02-24 18:22:58: Logging to console and directory: '/config/zigbee2mqtt/log/2024-02-24.18-22-58' filename: log.txt
Zigbee2MQTT:info  2024-02-24 18:22:58: Starting Zigbee2MQTT version 1.35.3 (commit #unknown)
Zigbee2MQTT:info  2024-02-24 18:22:58: Starting zigbee-herdsman (0.33.8)
Zigbee2MQTT:error 2024-02-24 18:22:59: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-02-24 18:22:59: Failed to start zigbee
Zigbee2MQTT:error 2024-02-24 18:22:59: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-02-24 18:22:59: Exiting...
Zigbee2MQTT:error 2024-02-24 18:22:59: Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/serialPort.ts:28:28)
    at SerialPort._error (/app/node_modules/@serialport/stream/dist/index.js:82:22)
    at /app/node_modules/@serialport/stream/dist/index.js:118:18
