### ISSUE TITLE
IKEA E1704 Tradfri OTA update fails

### ISSUE THREAD

**Issue by BurningTheSky** [Koenkk/zigbee2mqtt#21565]
### What happened?

When I try and update either of the IKEA E1704 Tradfri plugs I get the error "OTA: Device didn't respond to OTA request". I have tried 2 different plugs, restarted HA and the end devices but no change. According the HA it's trying to update from 537019939 to 587765297, Z2M says the current firmware version is 2.0.024.

### Zigbee2MQTT version

1.35.3

### Adapter firmware version

20210708

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus

### Setup

Add-on on HA OS running on a HA Green

### Debug log

debug 2024-02-18 12:25:23 Received MQTT message on 'zigbee2mqtt/bridge/request/device/ota_update/update' with data '{"id":"Bedroom Lamp Switch","transaction":"hvnyz-2"}'
info 2024-02-18 12:25:23 MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Updating 'Bedroom Lamp Switch' to latest firmware","meta":{"device":"Bedroom Lamp Switch","status":"update_in_progress"},"type":"ota_update"}'
debug 2024-02-18 12:25:24 OTA: Updating to latest '0xbc026efffe7c0598' (TRADFRI control outlet)
debug 2024-02-18 12:25:24 OTA: Using endpoint '1'
error 2024-02-18 12:23:16 Update of 'Bedroom Lamp Switch' failed (OTA: Device didn't respond to OTA request)
debug 2024-02-18 12:23:16 Error: OTA: Device didn't respond to OTA request at requestOTA (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:304:15) at Object.updateToLatest (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:428:21) at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:269:41) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17)
debug 2024-02-18 12:26:24 Update of 'Bedroom Lamp Switch' failed (Error: OTA: Device didn't respond to OTA request)
info 2024-02-18 12:26:24 MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Update of 'Bedroom Lamp Switch' failed (OTA: Device didn't respond to OTA request)","meta":{"device":"Bedroom Lamp Switch","status":"update_failed"},"type":"ota_update"}'
info 2024-02-18 12:26:24 MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"Bedroom Lamp Switch"},"error":"Update of 'Bedroom Lamp Switch' failed (OTA: Device didn't respond to OTA request)","status":"error","transaction":"hvnyz-2"}'
error 2024-02-18 12:26:24 Update of 'Bedroom Lamp Switch' failed (OTA: Device didn't respond to OTA request)
debug 2024-02-18 12:26:25 Error: OTA: Device didn't respond to OTA request at requestOTA (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:304:15) at Object.updateToLatest (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:428:21) at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:269:41) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17)

**Comment by BurningTheSky** [comment]
Resolved with version 1.36.0
