### ISSUE TITLE
[PTM 216Z] Problem to get button pressed (value does not show)

### ISSUE THREAD

**Issue by Merzhin79** [Koenkk/zigbee2mqtt#21573]
### What happened?

I have integrated a PTM 216Z interrupter (GreenPower) in Jeedom with jeezigbee. Not problem to add it but when I click on it no value is shown in button action.

Interrupter: https://www.enocean.com/en/product/ptm-216z/

### What did you expect to happen?

To get the value of button pressed.

### How to reproduce it (minimal and precise)

Just integrate a PTM 216Z interrupter (GreenPower) in Jeedom with jeezigbee (trio2sys), the two position button (https://www.enocean.com/en/product/ptm-216z/)

### Zigbee2MQTT version

 1.33.1 commit: 51f15bd

### Adapter firmware version

6.7.8.0 build 373

### Adapter

Jeedom Luna

### Setup

Z2M in localhost

### Debug log

Zigbee2MQTT:debug 2024-02-25 17:09:56: Received Zigbee message from '0x0000000001555c1a', type 'commandNotification', cluster 'greenPower', data '{"commandID":105,"frameCounter":52,"srcID":22371354}' from endpoint 242 with groupID null
Zigbee2MQTT:error 2024-02-25 17:09:56: Exception while calling fromZigbee converter: Cannot read properties of undefined (reading 'raw')}
Zigbee2MQTT:debug 2024-02-25 17:09:57: TypeError: Cannot read properties of undefined (reading 'raw')
at Object.convert (/var/www/html/plugins/z2m/resources/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/converters/fromZigbee.js:3642:45)
at Receive.onDeviceMessage (/var/www/html/plugins/z2m/resources/zigbee2mqtt/lib/extension/receive.ts:150:51)
at EventEmitter.emit (node:events:526:35)
at EventBus.emitDeviceMessage (/var/www/html/plugins/z2m/resources/zigbee2mqtt/lib/eventBus.ts:102:22)
at Controller. (/var/www/html/plugins/z2m/resources/zigbee2mqtt/lib/zigbee.ts:108:27)
at Controller.emit (node:events:514:28)
at Controller.selfAndDeviceEmit (/var/www/html/plugins/z2m/resources/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:527:14)
at Controller.onZclOrRawData (/var/www/html/plugins/z2m/resources/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:738:18)
Zigbee2MQTT:info  2024-02-25 17:09:57: MQTT publish: topic 'zigbee2mqtt/0x0000000001555c1a', payload '{"device":{"friendlyName":"0x0000000001555c1a","ieeeAddr":"0x0000000001555c1a","manufacturerID":null,"model":"PTM 216Z","networkAddress":23578,"type":"GreenPower"},"last_seen":"2024-02-25T17:09:56.842Z","linkquality":218}'
Zigbee2MQTT:debug 2024-02-25 17:09:57: Received Zigbee message from '0x0000000001555c1a', type 'commandNotification', cluster 'greenPower', data '{"commandID":106,"frameCounter":53,"srcID":22371354}' from endpoint 242 with groupID null
Zigbee2MQTT:error 2024-02-25 17:09:57: Exception while calling fromZigbee converter: Cannot read properties of undefined (reading 'raw')}
Zigbee2MQTT:debug 2024-02-25 17:09:57: TypeError: Cannot read properties of undefined (reading 'raw')
at Object.convert (/var/www/html/plugins/z2m/resources/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/converters/fromZigbee.js:3642:45)
at Receive.onDeviceMessage (/var/www/html/plugins/z2m/resources/zigbee2mqtt/lib/extension/receive.ts:150:51)
at EventEmitter.emit (node:events:526:35)
at EventBus.emitDeviceMessage (/var/www/html/plugins/z2m/resources/zigbee2mqtt/lib/eventBus.ts:102:22)
at Controller. (/var/www/html/plugins/z2m/resources/zigbee2mqtt/lib/zigbee.ts:108:27)
at Controller.emit (node:events:514:28)
at Controller.selfAndDeviceEmit (/var/www/html/plugins/z2m/resources/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:527:14)
at Controller.onZclOrRawData (/var/www/html/plugins/z2m/resources/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:738:18)

After searching a while it comes from the file fromZigbee.js in converter zigbee herdsman:

const ID = ${commandID}_${msg.data.commandFrame.raw.slice(0, 1).join('_')};
==> the 'raw' data in msg.data.commandFrame does not exists: undefined

**Comment by Koenkk** [comment]
This is probably an issue of the current EZSP driver, I suggest to try the new [ember driver](https://github.com/Koenkk/zigbee2mqtt/discussions/21462)

**Comment by chris-1243** [comment]
> This is probably an issue of the current EZSP driver, I suggest to try the new [ember driver](https://github.com/Koenkk/zigbee2mqtt/discussions/21462)

I just had a try on ember driver and it is working correctly [21462](https://github.com/Koenkk/zigbee2mqtt/discussions/21462#discussioncomment-8584437)

**Comment by Koenkk** [comment]
Great. Then I'll close this.
