### ISSUE TITLE
ZBDongle-E and TuYa TS011F_plug_3 not working

### ISSUE THREAD

**Issue by nevesigor** [Koenkk/zigbee2mqtt#21577]
### What happened?

Hello,

I'm using z2m with ZBDongle-E (usbid 1a86:55d4) last oficial firmware.

I'm trying to use [TS011F_plug_3](https://www.zigbee2mqtt.io/devices/TS011F_plug_3.html#tuya-ts011f_plug_3) which its identified manufacture as _TZ3000_u5u4cakc .

It does pair correctly, but any kind of device comunication (changing state) or even the consumption by pooling does not work, I always get error like the above and the state on the interface never shows anything (screenshot above).

`2024-02-25T16:10:59.905Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (0)
2024-02-25T16:10:59.905Z zigbee-herdsman:controller:endpoint Write 0xbc026efffe846555/1 genOnOff({"32768":{"value":true,"type":16}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 11976 - 1 - 18 - 6 - 4 after 10000ms)
Zigbee2MQTT:error 2024-02-25 16:10:59: Publish 'set' 'child_lock' to '0xbc026efffe846555' failed: 'Error: Write 0xbc026efffe846555/1 genOnOff({"32768":{"value":true,"type":16}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 11976 - 1 - 18 - 6 - 4 after 10000ms)'
Zigbee2MQTT:debug 2024-02-25 16:10:59: Error: Write 0xbc026efffe846555/1 genOnOff({"32768":{"value":true,"type":16}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 11976 - 1 - 18 - 6 - 4 after 10000ms)
    at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23)
    at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:486:47)
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
    at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)
    at Endpoint.write (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:390:28)
    at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:1075:13)
    at Publish.onMQTTMessage (/app/lib/extension/publish.ts:249:36)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17)
`

![image](https://github.com/Koenkk/zigbee2mqtt/assets/45663547/95e4a1b0-de5f-4b27-9de9-bb1a6a6b984f)

Notes:
- I have tried this TuYa device on another zigbee2mqtt and they are working correctly, so I'm assuming it's something with dongle and this device
- I have one xiaomi motion sensor in this z2m and it's working fine

![image](https://github.com/Koenkk/zigbee2mqtt/assets/45663547/af0fca78-6905-41c0-93ca-fb983ad9c0ce)

### Zigbee2MQTT version

 1.35.3

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Itead SONOFF Zigbee 3.0 USB Dongle Plus V2

### Setup

x64 Linux on docker

**Comment by nevesigor** [comment]
I found the problem, zigbee newbie, just changed the channel (yes, i have another networt) and it all worked out, please close this ticket.

Quick informations, now with firmware **7.4.1.0 build 0** and all working.

![image](https://github.com/Koenkk/zigbee2mqtt/assets/45663547/2f661c40-f956-4397-89d2-7c8fb658312f)
