### ISSUE TITLE
TuYa TS0202_1 log error (Failed to configure) every time movement detected (_TYZB01_jytabjkb)

### ISSUE THREAD

**Issue by demonaxxx** [Koenkk/zigbee2mqtt#21615]
![tuya](https://github.com/Koenkk/zigbee2mqtt/assets/59745733/cfda5570-9040-494c-b26a-7cbb1774ecc7)
### What happened?

z2m log error every time when movement detected

> Zigbee2MQTT:error 2024-02-29 14:28:29: Failed to configure 'tuya_outdoor_movement_sensor', attempt 3 (Error: ConfigureReporting 0x60a423fffe93d453/1 genPowerCfg([{"attribute":"batteryPercentageRemaining","minimumReportInterval":3600,"maximumReportInterval":65000,"reportableChange":0}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 32827 - 1 - 174 - 1 - 7 after 10000ms)
>     at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23)
>     at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:502:47)
>     at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
>     at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)
>     at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:669:28)
>     at Object.batteryPercentageRemaining (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:59:5)
>     at Object.configure (/app/data/extension/externally-loaded.js:25:9)
>     at Configure.configure (/app/lib/extension/configure.ts:120:13)
>     at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

### What did you expect to happen?

no error in log

### How to reproduce it (minimal and precise)

move in front of sensor

### Zigbee2MQTT version

1.35.3-1

### Adapter firmware version

20220302

### Adapter

Egony Stick V4

### Setup

Add-on on Home Assistant OS (2024.2.5)

**Comment by demonaxxx** [comment]
- repair device not help
- update to 1.36.0-1 not help
