### ISSUE TITLE
Error: SRSP - ZDO - startupFromApp after 40000ms

### ISSUE THREAD

**Issue by WhistleMaster** [Koenkk/zigbee2mqtt#21962]
### What happened?

Everything was working fine for a few years, and then suddenly, some devices did not respond, so I've tried to restart zigbee2mqtt and I have this error. I have tried to flash 20221226 and go back to 1.35.3, same issue. It's very strange as everything was working fine until now, I did not made any change or update. Thanks for your help.

### What did you expect to happen?

---

### How to reproduce it (minimal and precise)

---

### Zigbee2MQTT version

1.36.0

### Adapter firmware version

20230507

### Adapter

Sonoff Zigbee 3.0 USB Dongle Plus

### Setup

Plain on Docker

### Debug log

```
Using '/app/data' as data directory

Zigbee2MQTT:info  2024-03-26 23:46:52: Logging to console and directory: '/app/data/log/2024-03-26.23-46-52' filename: log.txt

Zigbee2MQTT:info  2024-03-26 23:46:52: Starting Zigbee2MQTT version 1.35.3 (commit #fe0742a)

Zigbee2MQTT:info  2024-03-26 23:46:52: Starting zigbee-herdsman (0.33.8)

Zigbee2MQTT:error 2024-03-26 23:47:40: Error while starting zigbee-herdsman

Zigbee2MQTT:error 2024-03-26 23:47:40: Failed to start zigbee

Zigbee2MQTT:error 2024-03-26 23:47:40: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions

Zigbee2MQTT:error 2024-03-26 23:47:40: Exiting...

Zigbee2MQTT:error 2024-03-26 23:47:40: Error: SRSP - ZDO - startupFromApp after 40000ms

    at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23)

    at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:312:45

    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:26)

    at Znp.request (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:300:27)

    at ZnpAdapterManager.beginStartup (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:262:28)

    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:70:13)

    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)

    at Zigbee.start (/app/lib/zigbee.ts:60:27)

    at Controller.start (/app/lib/controller.ts:109:27)

    at start (/app/index.js:107:5)
```

**Comment by WhistleMaster** [comment]
Sometime zigbee2mqtt is starting and I see a lot of "SRSP - AF - dataRequest after 6000ms" error.

**Comment by WhistleMaster** [comment]
I have added the DEBUG=zigbee-herdsman* and downloaded the log. Hope it helps.

[_zigbee2mqtt_logs.txt](https://github.com/Koenkk/zigbee2mqtt/files/14771983/_zigbee2mqtt_logs.txt)
