### ISSUE TITLE
Stack trace -- the computer told me to do it!

### ISSUE THREAD

**Issue by skandragon** [Koenkk/zigbee2mqtt#2196]
```zigbee2mqtt    | ===== Stack =====
zigbee2mqtt    | AssertionError [ERR_ASSERTION]: { frameCntl:
zigbee2mqtt    |    { frameType: 1, manufSpec: 0, direction: 0, disDefaultRsp: 0 },
zigbee2mqtt    |   manufCode: null,
zigbee2mqtt    |   seqNum: 80,
zigbee2mqtt    |   cmdId: 1 } deepEqual undefined
zigbee2mqtt    |     at Object.header (/app/node_modules/zigbee-herdsman/dist/lib/components/zcl.js:93:20)
zigbee2mqtt    |     at dispatchIncomingMsg (/app/node_modules/zigbee-herdsman/dist/lib/components/af.js:528:29)
zigbee2mqtt    |     at Controller.incomingMsgHandler (/app/node_modules/zigbee-herdsman/dist/lib/components/af.js:625:12)
zigbee2mqtt    |     at Controller.emit (events.js:182:13)
zigbee2mqtt    |     at Object.bridge._areqEventBridge (/app/node_modules/zigbee-herdsman/dist/lib/components/event_bridge.js:11:16)
zigbee2mqtt    |     at Znp.<anonymous> (/app/node_modules/zigbee-herdsman/dist/lib/components/controller.js:104:20)
zigbee2mqtt    |     at Znp.emit (events.js:182:13)
zigbee2mqtt    |     at Znp.onUnpiParsed (/app/node_modules/zigbee-herdsman/dist/znp/znp.js:72:18)
zigbee2mqtt    |     at Parser.emit (events.js:182:13)
zigbee2mqtt    |     at Parser.parseNext (/app/node_modules/zigbee-herdsman/dist/unpi/parser.js:39:26)
zigbee2mqtt    | ===== Arguments =====
zigbee2mqtt    | <Buffer 01 50 01 01 41 12 30 00 11 00 00 00 00 00> 25
zigbee2mqtt    | ===== Buffer =====
zigbee2mqtt    | { type: 'Buffer',
zigbee2mqtt    |   data: [ 1, 80, 1, 1, 65, 18, 48, 0, 17, 0, 0, 0, 0, 0 ] }
zigbee2mqtt    | ===== zcl-packet header =====
zigbee2mqtt    | {"frameCntl":{"frameType":1,"manufSpec":0,"direction":0,"disDefaultRsp":0},"manufCode":null,"seqNum":80,"cmdId":1}
zigbee2mqtt    | ===== zcl header =====
zigbee2mqtt    | undefined
zigbee2mqtt    | ===============```

**Comment by Koenkk** [comment]
Thanks for reporting, I checked and this case can be ignored.
