### ISSUE TITLE
Powering light randomly make the "Adapter disconnected, stopping" error (Aeontec Zi-Stick)

### ISSUE THREAD

**Issue by hadjedjvincent** [Koenkk/zigbee2mqtt#21989]
### What happened?

Sometimes, when a light is turned on, zigbee2mqtt enter in a sort of "starting" loop.
I can see all my Philips hue bulbs dimming at the same time (while the coordinator restart/init I think)

The issues start here error 2024-03-27 20:39:38: **Failed to read state of 'Plafond 2' after reconnect** (Read 0x0017880104fedb07/11
Zigbee2MQTT "crash" right after this light "Plafond 2" was available again (this light point is managed by a classic switch).

After a couple of start/stop tries, Zigbee2MQTT finally start and the lights stop flashing, everything works fine again.

I'm running on the dev branch.

### What did you expect to happen?

Zigbee2MQTT and/or adapter should not crash :)

### How to reproduce it (minimal and precise)

It has always happened after an offline light was switched on, but it does not happen all the time.

### Zigbee2MQTT version

1.36.0-dev commit 25cec20f

### Adapter firmware version

6.10.3.0 build 297

### Adapter

Aeontec Zi-Stick

### Setup

RPi running homebridge / z2m

### Debug log

```
info  2024-03-27 20:38:41: MQTT publish: topic 'zigbee2mqtt/Détecteur - Étage', payload '{"battery":100,"device":{"applicationVersion":2,"dateCode":"20210830","friendlyName":"Détecteur - Étage","hardwareVersion":1,"ieeeAddr":"0x001788010bce7670","manufacturerID":4107,"manufacturerName":"Signify Netherlands B.V.","model":"9290030675","networkAddress":40775,"powerSource":"Battery","softwareBuildID":"2.53.6","stackVersion":1,"type":"EndDevice","zclVersion":2},"illuminance":18657,"illuminance_lux":73,"last_seen":1711568321129,"led_indication":false,"linkquality":168,"motion_sensitivity":"very_high","occupancy":true,"occupancy_timeout":0,"temperature":20.81}'
error 2024-03-27 20:39:38: Failed to read state of 'Plafond 2' after reconnect (Read 0x0017880104fedb07/11 genLevelCtrl(["currentLevel"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error))
warn  2024-03-27 20:39:58: Failed to ping 'Palmier' (attempt 1/2, Read 0x001788010c3a48c3/11 genBasic(["zclVersion"], {"timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error))
error 2024-03-27 20:40:28: Adapter disconnected, stopping
info  2024-03-27 20:40:28: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'offline'
info  2024-03-27 20:40:28: Disconnecting from MQTT server
info  2024-03-27 20:40:28: Stopping zigbee-herdsman...
error 2024-03-27 20:40:28: Failed to stop Zigbee2MQTT
```

First restart attempt:

```
info  2024-03-27 20:40:34: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2024-03-27.20-40-34' filename: log.txt
info  2024-03-27 20:40:34: Starting Zigbee2MQTT version 1.36.0-dev (commit #25cec20f)
info  2024-03-27 20:40:34: Starting zigbee-herdsman (0.39.1)
error 2024-03-27 20:40:47: Error while starting zigbee-herdsman
error 2024-03-27 20:40:47: Failed to start zigbee
error 2024-03-27 20:40:47: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2024-03-27 20:40:47: Exiting...
error 2024-03-27 20:40:47: Error: Failure send getNodeId:{"type":"Buffer","data":[27,0,1,39,0]}
    at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:664:23
    at Queue.execute (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
    at Driver.startup (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:262:22)
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:62:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:109:27)
    at start (/opt/zigbee2mqtt/index.js:107:5)
```

Next restart attempt:

```

info  2024-03-27 20:42:06: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2024-03-27.20-42-06' filename: log.txt
info  2024-03-27 20:42:06: Starting Zigbee2MQTT version 1.36.0-dev (commit #25cec20f)
info  2024-03-27 20:42:06: Starting zigbee-herdsman (0.39.1)
error 2024-03-27 20:42:19: Error while starting zigbee-herdsman
error 2024-03-27 20:42:19: Failed to start zigbee
error 2024-03-27 20:42:19: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2024-03-27 20:42:19: Exiting...
error 2024-03-27 20:42:19: Error: Failure send getEui64:{"type":"Buffer","data":[28,0,1,38,0]}
    at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:664:23
    at Queue.execute (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
    at Driver.startup (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:263:23)
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:62:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:109:27)
    at start (/opt/zigbee2mqtt/index.js:107:5)
```

Next restart attempt:

```
info  2024-03-27 20:42:25: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2024-03-27.20-42-25' filename: log.txt
info  2024-03-27 20:42:25: Starting Zigbee2MQTT version 1.36.0-dev (commit #25cec20f)
info  2024-03-27 20:42:25: Starting zigbee-herdsman (0.39.1)
error 2024-03-27 20:42:39: Error while starting zigbee-herdsman
error 2024-03-27 20:42:39: Failed to start zigbee
error 2024-03-27 20:42:39: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2024-03-27 20:42:39: Exiting...
error 2024-03-27 20:42:39: Error: Failure send setManufacturerCode:{"type":"Buffer","data":[32,0,1,21,0,73,16]}
    at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:664:23
    at Queue.execute (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
    at Driver.startup (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:275:9)
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:62:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:109:27)
    at start (/opt/zigbee2mqtt/index.js:107:5)
```

Next restart attempt:

```
info  2024-03-27 20:42:45: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2024-03-27.20-42-45' filename: log.txt
info  2024-03-27 20:42:45: Starting Zigbee2MQTT version 1.36.0-dev (commit #25cec20f)
info  2024-03-27 20:42:45: Starting zigbee-herdsman (0.39.1)
error 2024-03-27 20:43:01: Error while starting zigbee-herdsman
error 2024-03-27 20:43:01: Failed to start zigbee
error 2024-03-27 20:43:01: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2024-03-27 20:43:01: Exiting...
error 2024-03-27 20:43:01: Error: {"address":0,"clusterId":32772,"sequence":5} after 10000ms
    at Object.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23)
    at Driver.zdoRequest (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:692:43)
    at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:232:36
    at Queue.execute (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:183:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:62:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:109:27)
    at start (/opt/zigbee2mqtt/index.js:107:5)
```

**Comment by hadjedjvincent** [comment]
Still happens randomly, using 1.40.1-dev commit: [d3de77da]
Type de coordinateur: EmberZNet
Révision du coordinateur: 7.4.3 [GA]
