### ISSUE TITLE
PTRPP-WH02 suddenly unsupported and not working

### ISSUE THREAD

**Issue by lee-costa** [Koenkk/zigbee2mqtt#22127]
### What happened?

PTRPP-WH02 suddenly stopped working but still online.

### What did you expect to happen?

Work as previously. I have followed the instructions [here](https://zigbee.blakadder.com/Quirky_PTRPP-WH02.html) when I first configured it and have always worked great. I only noticed it not working after the last couple updates (I think, not entirely sure).

### How to reproduce it (minimal and precise)

Try and use the device by opening a door. 

### Zigbee2MQTT version

1.36.1

### Adapter firmware version

20230507

### Adapter

SONOFF Zigbee 3.0 

### Setup

Ubuntu VM via docker compose

### Debug log

    info 2024-04-07 14:02:54Successfully changed options
    info 2024-04-07 14:02:54MQTT publish: topic 'zigbee2mqtt/bridge/response/options', payload '{"data":{"restart_required":false},"status":"ok","transaction":"w76u8-1"}'
    info 2024-04-07 14:02:59Successfully changed options
    info 2024-04-07 14:02:59MQTT publish: topic 'zigbee2mqtt/bridge/response/options', payload '{"data":{"restart_required":false},"status":"ok","transaction":"w76u8-3"}'
    debug 2024-04-07 14:03:10Received Zigbee message from 'Bedroom Closet', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":49}' from endpoint 1 with groupID 0
    info 2024-04-07 14:03:10MQTT publish: topic 'zigbee2mqtt/Bedroom Closet', payload '{"ac_status":false,"alarm_1":true,"alarm_2":false,"battery":16,"battery_defect":false,"battery_low":false,"contact":true,"linkquality":61,"restore_reports":true,"supervision_reports":true,"tamper":false,"test":false,"trouble":false,"voltage":2700}'
    debug 2024-04-07 14:03:16Received Zigbee message from 'Bedroom Closet', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":48}' from endpoint 1 with groupID 0
    info 2024-04-07 14:03:16MQTT publish: topic 'zigbee2mqtt/Bedroom Closet', payload '{"ac_status":false,"alarm_1":false,"alarm_2":false,"battery":16,"battery_defect":false,"battery_low":false,"contact":true,"linkquality":61,"restore_reports":true,"supervision_reports":true,"tamper":false,"test":false,"trouble":false,"voltage":2700}'
    debug 2024-04-07 14:03:20Received Zigbee message from 'Bedroom Closet', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":49}' from endpoint 1 with groupID 0
    info 2024-04-07 14:03:20MQTT publish: topic 'zigbee2mqtt/Bedroom Closet', payload '{"ac_status":false,"alarm_1":true,"alarm_2":false,"battery":16,"battery_defect":false,"battery_low":false,"contact":true,"linkquality":69,"restore_reports":true,"supervision_reports":true,"tamper":false,"test":false,"trouble":false,"voltage":2700}'
    debug 2024-04-07 14:04:00Received MQTT message on 'zigbee2mqtt/bridge/request/device/configure' with data '{"id":"Bedroom Closet","transaction":"w76u8-4"}'
    info 2024-04-07 14:04:00Configuring 'Bedroom Closet'
    debug 2024-04-07 14:04:00Configure reporting: true, read: true for 0x7ce524000009510b/1 genPowerCfg [{"attribute":"batteryPercentageRemaining","min":"1_HOUR","max":"MAX","change":10}]
    error 2024-04-07 14:04:10Failed to configure 'Bedroom Closet', attempt 4 (Error: Bind 0x7ce524000009510b/1 genPowerCfg from '0x00124b0024c3d458/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:692:28 at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:469:13) at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:68:13) at result.configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:287:17) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:162:21) at Configure.configure (/app/lib/extension/configure.ts:122:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:21) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
    info 2024-04-07 14:04:10MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"Bedroom Closet"},"error":"Failed to configure (Bind 0x7ce524000009510b/1 genPowerCfg from '0x00124b0024c3d458/1' failed (AREQ - ZDO - bindRsp after 10000ms))","status":"error","transaction":"w76u8-4"}'
    debug 2024-04-07 14:04:18Received Zigbee message from 'Bedroom Closet', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":48}' from endpoint 1 with groupID 0
    info 2024-04-07 14:04:18MQTT publish: topic 'zigbee2mqtt/Bedroom Closet', payload '{"ac_status":false,"alarm_1":false,"alarm_2":false,"battery":16,"battery_defect":false,"battery_low":false,"contact":true,"linkquality":69,"restore_reports":true,"supervision_reports":true,"tamper":false,"test":false,"trouble":false,"voltage":2700}'
    debug 2024-04-07 14:04:24Received Zigbee message from 'Bedroom Closet', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":49}' from endpoint 1 with groupID 0
    info 2024-04-07 14:04:24MQTT publish: topic 'zigbee2mqtt/Bedroom Closet', payload '{"ac_status":false,"alarm_1":true,"alarm_2":false,"battery":16,"battery_defect":false,"battery_low":false,"contact":true,"linkquality":65,"restore_reports":true,"supervision_reports":true,"tamper":false,"test":false,"trouble":false,"voltage":2700}'
    debug 2024-04-07 14:04:31Received Zigbee message from 'Bedroom Closet', type 'commandStatusChangeNotification', cluster 'ssIasZone', data '{"extendedstatus":0,"zonestatus":48}' from endpoint 1 with groupID 0
    info 2024-04-07 14:04:31MQTT publish: topic 'zigbee2mqtt/Bedroom Closet', payload '{"ac_status":false,"alarm_1":false,"alarm_2":false,"battery":16,"battery_defect":false,"battery_low":false,"contact":true,"linkquality":65,"restore_reports":true,"supervision_reports":true,"tamper":false,"test":false,"trouble":false,"voltage":2700}'

**Comment by lee-costa** [comment]
The solution: For some reason it now exposes Alarm 1 as the entity I was using in Home Assistant. Renamed it to what it used to be in my automation and now it's back to normal. 

Thanks for maintaining such an amazing product.
