### ISSUE TITLE
DIY (SNZB-02_EFEKTA) Error: Device 0xxxxxx has no input cluster genPowerCfg

### ISSUE THREAD

**Issue by odibox** [Koenkk/zigbee2mqtt#22158]
### What happened?

Since the last version 1.36.1 i get this Error Message from the (SNZB-02_EFEKTA) Sensor.
With Version 1.36.0 everything was OK.
Zigbee2MQTT:error 2024-04-07 19:49:45: Failed to configure '0x00124b002549ce72', attempt 1 (Error: Device 0x00124b002549ce72 has no input cluster genPowerCfg
    at getEndpointsWithCluster (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:28:15)
    at setupAttributes (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:63:55)
    at result.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:287:23)
    at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/index.ts:162:27)
    at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:122:37)
    at /opt/zigbee2mqtt/lib/extension/configure.ts:86:62
    at EventEmitter.wrappedCallback (/opt/zigbee2mqtt/lib/eventBus.ts:174:23)
    at EventEmitter.emit (node:events:530:35)
    at EventBus.emitDeviceInterview (/opt/zigbee2mqtt/lib/eventBus.ts:73:22)
    at Controller.<anonymous> (/opt/zigbee2mqtt/lib/zigbee.ts:95:27))
Zigbee2MQTT:info  2024-04-07 19:49:57: Configuring '0x00124b002549ce72'
Zigbee2MQTT:error 2024-04-07 19:49:57: Failed to configure '0x00124b002549ce72', attempt 2 (Error: Device 0x00124b002549ce72 has no input cluster genPowerCfg
    at getEndpointsWithCluster (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:28:15)
    at setupAttributes (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:63:55)
    at result.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:287:23)
    at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/index.ts:162:27)
    at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:122:37)
    at /opt/zigbee2mqtt/lib/extension/configure.ts:87:62
    at EventEmitter.wrappedCallback (/opt/zigbee2mqtt/lib/eventBus.ts:174:23)
    at EventEmitter.emit (node:events:530:35)
    at EventBus.emitLastSeenChanged (/opt/zigbee2mqtt/lib/eventBus.ts:51:22)
    at Controller.<anonymous> (/opt/zigbee2mqtt/lib/zigbee.ts:74:27))
Zigbee2MQTT:info  2024-04-07 19:49:57: Configuring '0x00124b002549ce72'
Zigbee2MQTT:error 2024-04-07 19:49:57: Failed to configure '0x00124b002549ce72', attempt 3 (Error: Device 0x00124b002549ce72 has no input cluster genPowerCfg
    at getEndpointsWithCluster (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:28:15)
    at setupAttributes (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:63:55)
    at result.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:287:23)
    at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/index.ts:162:27)
    at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:122:37)
    at /opt/zigbee2mqtt/lib/extension/configure.ts:87:62
    at EventEmitter.wrappedCallback (/opt/zigbee2mqtt/lib/eventBus.ts:174:23)
    at EventEmitter.emit (node:events:530:35)
    at EventBus.emitLastSeenChanged (/opt/zigbee2mqtt/lib/eventBus.ts:51:22)
    at Controller.<anonymous> (/opt/zigbee2mqtt/lib/zigbee.ts:74:27))

### Zigbee2MQTT version

1.36.1

### Adapter firmware version

20230507

### Adapter

CC2652P

### Setup

plain on arm64 Debian 11

**Comment by pswid** [comment]
Same for me. I use Z2M v.1.37.0 and Sonoff USB coordinator with firmware zStack3x0 20240315.

`Failed to configure '0x00124b0024549931', attempt 3 (Error: Device 0x00124b0024549931 has no input cluster genPowerCfg at getEndpointsWithCluster (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:30:15) at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:67:55) at configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:112:23) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:160:27) at Configure.configure (/app/lib/extension/configure.ts:121:37) at /app/lib/extension/configure.ts:87:62 at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:23) at EventEmitter.emit (node:events:529:35) at EventBus.emitLastSeenChanged (/app/lib/eventBus.ts:51:22) at Controller.<anonymous> (/app/lib/zigbee.ts:74:27))`
