### ISSUE TITLE
Strange issue with consistency of configuration

### ISSUE THREAD

**Issue by antst** [Koenkk/zigbee2mqtt#22238]
### What happened?

At some point my zigbee network became non-functional, I went to restart Z2M, but it now refuses to work due to inconsistency of configuration. At the same time it reports
` Configuration is not consistent with adapter state/backup!
 - PAN ID: configured=6755, adapter=6755
 - Extended PAN ID: configured=00124b0014b556a2, adapter=00124b0014b556a2
 - Network Key: configured=01030507090b0d0f00020406080a0c0d, adapter=01030507090b0d0f00020406080a0c0d
 - Channel List: configured=20, adapter=20
`
so, all configuration values are the same.

### What did you expect to happen?

to start normally 

### Zigbee2MQTT version

1.36.1-dev, 1.35.3-dev

### Adapter firmware version

20230507

### Adapter

Sonoff

### Setup

plain, x86-64

### Debug log

`2024-04-17 19:25:09] error:    zh:adapter:zstack:manager: Configuration is not consistent with adapter state/backup!
[2024-04-17 19:25:09] error:    zh:adapter:zstack:manager: - PAN ID: configured=6755, adapter=6755
[2024-04-17 19:25:09] error:    zh:adapter:zstack:manager: - Extended PAN ID: configured=00124b0014b556a2, adapter=00124b0014b556a2
[2024-04-17 19:25:09] error:    zh:adapter:zstack:manager: - Network Key: configured=01030507090b0d0f00020406080a0c0d, adapter=01030507090b0d0f00020406080a0c0d
[2024-04-17 19:25:09] error:    zh:adapter:zstack:manager: - Channel List: configured=20, adapter=20
[2024-04-17 19:25:09] error:    zh:adapter:zstack:manager: Please update configuration to prevent further issues.
[2024-04-17 19:25:09] error:    zh:adapter:zstack:manager: If you wish to re-commission your network, please remove coordinator backup at /opt/zigbee2mqtt/data/coordinator_backup.json.
[2024-04-17 19:25:09] error:    zh:adapter:zstack:manager: Re-commissioning your network will require re-pairing of all devices!
[2024-04-17 19:25:09] error:    z2m: Error while starting zigbee-herdsman
[2024-04-17 19:25:09] error:    z2m: Failed to start zigbee
[2024-04-17 19:25:09] error:    z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-04-17 19:25:09] error:    z2m: Exiting...
[2024-04-17 19:25:09] error:    z2m: Error: startup failed - configuration-adapter mismatch - see logs above for more information
    at ZnpAdapterManager.determineStrategy (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:223:35)
    at ZnpAdapterManager.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:57:26)
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:124:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:62:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:108:27)
    at start (/opt/zigbee2mqtt/index.js:107:5)
`

**Comment by Mchl** [comment]
Hey @antst 

I'm facing a similar issue right now. Did you find a solution, or did you end up having to re-pair your devices?

**Comment by Micha70** [comment]
Same issue like here https://github.com/Koenkk/zigbee2mqtt/issues/24103 ?

**Comment by benedikt-bartscher** [comment]
I have the same issue, it suddenly stopped working. All parameters match.

**Comment by Koenkk** [comment]
Let's continue in https://github.com/Koenkk/zigbee2mqtt/issues/24103
