### ISSUE TITLE
TO-Q-SY2-163JZT error

### ISSUE THREAD

**Issue by Pajuris** [Koenkk/zigbee2mqtt#22272]
### What happened?

Home assistant Zigbee2mqtt add-on
Tongou TO-Q-SY2-163JZT device.
In every start Home assistant generate error:

Exception in functools.partial(<function _async_discover at 0xffff7a5cc860>, <HomeAssistant NOT_RUNNING>, 'select', <function async_setup_entity_entry_helper.<locals>.async_setup_from_discovery at 0xffff78c4f880>, None) when dispatching 'SignalType(name='mqtt_discovery_new_select_mqtt')': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state', 'value_template': '{{ value_json.state }}'}], 'command_topic': 'zigbee2mqtt/UPS automatas/set/power_outage_memory', 'device': {'identifiers': ['zigbee2mqtt_0xe0798dfffebbe2ba'], 'manufacturer': 'TONGOU', 'model': 'Smart circuit breaker (TO-Q-SY2-163JZT)', 'name': 'UPS automatas', 'via_device': 'zigbee2mqtt_bridge_0x00124b0024cb6151'}, 'enabled_by_default': True, 'entity_category': 'config', 'icon': 'mdi:power-settings', 'name': 'Power outage memory', 'object_id': 'ups_automatas_power_outage_memory', 'options': ['on', 'off', 'restore'], 'origin': {'name': 'Zigbee2MQTT', 'sw_version': '1.36.1', 'support_url': 'https://www.zigbee2mqtt.io'}, 'state_topic': 'zigbee2mqtt/UPS automatas', 'unique_id': '0xe0798dfffebbe2ba_power_outage_memory_zigbee2mqtt', 'value_template': '{{ value_json.power_outage_memory }}', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 302, in _async_discover setup(discovery_payload) File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 369, in async_setup_from_discovery [entity_class(hass, config, entry, discovery_payload.discovery_data)] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 1194, in __init__ MqttAvailability.__init__(self, config) File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 583, in __init__ self._availability_setup_from_config(config) File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 622, in _availability_setup_from_config CONF_PAYLOAD_AVAILABLE: avail[CONF_PAYLOAD_AVAILABLE], ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^ KeyError: 'payload_available' 

### Zigbee2MQTT version

1.36.1 

### Adapter firmware version

20220219

### Adapter

HamGeek CC2652P

### Setup

Home assistant Zigbee2mqtt add-on

**Comment by Pajuris** [comment]
I'm surprised... but after few restarts - error gone.
