### ISSUE TITLE
Unable to set state ON/OFF - Tuya Mini switch (TS0001_switch_module)

### ISSUE THREAD

**Issue by Bitcraze26** [Koenkk/zigbee2mqtt#22314]
### What happened?

Unable to set On or Off state from Home Assistant or Z2M dashboard.
The device send it's state on plug succesfully but impossible to command it.

### What did you expect to happen?

Setting the ON or OFF state on the switch.

### Zigbee2MQTT version

1.36.1

### Adapter firmware version

EZSP v8 -  6.10.3.0 build 297

### Adapter

Sonoff Zigbee Dongle E

### Setup

Pi Core on Docker

### Debug log

Zigbee2MQTT:debug 2024-04-25 17:55:54: Received Zigbee message from 'mini_switch1', type 'attributeReport', cluster 'genBasic', data '{"65506":56,"65508":0,"appVersion":72}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2024-04-25 17:55:54: MQTT publish: topic 'zigbee2mqtt/mini_switch1', payload '{"last_seen":"2024-04-25T15:55:54.607Z","linkquality":104,"power_on_behavior":"previous","state":"ON","switch_type":"toggle"}'
2024-04-25T15:55:54.798Z zigbee-herdsman:adapter:ezsp:uart <-- [027d33b1a97d312a15b658944a24ab5593499c97431e55239874f2ce6f83fd7d5e1fef0932fe576b00e7db9e4a7e]
2024-04-25T15:55:54.800Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (0,2,0): 0213b1a9112a15b658944a24ab5593499c97431e55239874f2ce6f83fd7e1fef0932fe576b00e7db9e4a7e
2024-04-25T15:55:54.800Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (1)
2024-04-25T15:55:54.800Z zigbee-herdsman:adapter:ezsp:uart --> [8160597e]
2024-04-25T15:55:54.801Z zigbee-herdsman:adapter:ezsp:uart <-- ACK (2): 0213b1a9112a15b658944a24ab5593499c97431e55239874f2ce6f83fd7e1fef0932fe576b00e7db9e4a7e
2024-04-25T15:55:54.801Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 51900145000004010000010100010000d964b5b8edffff0f080c0a01002048e2ff2038e4ff2000
2024-04-25T15:55:54.802Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x45: {"_cls_":"incomingMessageHandler","_id_":69,"_isRequest_":false,"type":0,"apsFrame":{"profileId":260,"sequence":217,"clusterId":0,"sourceEndpoint":1,"destinationEndpoint":1,"groupId":0,"options":256},"lastHopLqi":100,"lastHopRssi":-75,"sender":60856,"bindingIndex":255,"addressIndex":255,"message":{"type":"Buffer","data":[8,12,10,1,0,32,72,226,255,32,56,228,255,32,0]}}
2024-04-25T15:55:54.803Z zigbee-herdsman:adapter:ezsp:debg processMessage: {"messageType":0,"apsFrame":{"profileId":260,"sequence":217,"clusterId":0,"sourceEndpoint":1,"destinationEndpoint":1,"groupId":0,"options":256},"lqi":100,"rssi":-75,"sender":60856,"bindingIndex":255,"addressIndex":255,"message":{"type":"Buffer","data":[8,12,10,1,0,32,72,226,255,32,56,228,255,32,0]}}
2024-04-25T15:55:54.807Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false,"reservedBits":0},"transactionSequenceNumber":12,"manufacturerCode":null,"commandIdentifier":10},"Payload":[{"attrId":1,"dataType":32,"attrData":72},{"attrId":65506,"dataType":32,"attrData":56},{"attrId":65508,"dataType":32,"attrData":0}],"Command":{"ID":10,"name":"report","parameters":[{"name":"attrId","type":33},{"name":"dataType","type":32},{"name":"attrData","type":1000}]}},"address":60856,"endpoint":1,"linkquality":100,"groupID":0,"wasBroadcast":false,"destinationEndpoint":1}'
Zigbee2MQTT:debug 2024-04-25 17:55:54: Received Zigbee message from 'mini_switch1', type 'attributeReport', cluster 'genBasic', data '{"65506":56,"65508":0,"appVersion":72}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2024-04-25 17:55:54: MQTT publish: topic 'zigbee2mqtt/mini_switch1', payload '{"last_seen":"2024-04-25T15:55:54.807Z","linkquality":100,"power_on_behavior":"previous","state":"ON","switch_type":"toggle"}'
2024-04-25T15:55:57.230Z zigbee-herdsman:adapter:ezsp:debg Response timeout (0xa4c1388d1e14b582:60856,0)
2024-04-25T15:55:57.230Z zigbee-herdsman:adapter:ezsp:debg sendZclFrameToEndpointInternal 0xa4c1388d1e14b582:60856/1 (1,0,2), timeout=10000
2024-04-25T15:55:57.232Z zigbee-herdsman:adapter:ezsp:ezsp ==> sendUnicast: {"type":0,"indexOrDestination":60856,"apsFrame":{"profileId":260,"sequence":15,"clusterId":6,"sourceEndpoint":1,"destinationEndpoint":1,"groupId":0,"options":256},"messageTag":16,"message":{"type":"Buffer","data":[1,4,0]}}
2024-04-25T15:55:57.232Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"sendUnicast","_id_":52,"_isRequest_":true,"type":0,"indexOrDestination":60856,"apsFrame":{"profileId":260,"sequence":15,"clusterId":6,"sourceEndpoint":1,"destinationEndpoint":1,"groupId":0,"options":256},"messageTag":16,"message":{"type":"Buffer","data":[1,4,0]}}
2024-04-25T15:55:57.233Z zigbee-herdsman:adapter:ezsp:uart --> DATA (2,1,0): 520001340000b8ed040106000101000100000f1003010400
2024-04-25T15:55:57.234Z zigbee-herdsman:adapter:ezsp:uart --> [211021a9602a150ab4904b23aa5493499d4e27a4fdcd668ffd688f7e]
2024-04-25T15:55:57.235Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (3)
2024-04-25T15:55:57.243Z zigbee-herdsman:adapter:ezsp:uart <-- [7d3310a1a9602a15740f547e]
2024-04-25T15:55:57.244Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (1,3,0): 1310a1a9602a15740f547e
2024-04-25T15:55:57.244Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (2)
2024-04-25T15:55:57.244Z zigbee-herdsman:adapter:ezsp:uart --> [82503a7e]
2024-04-25T15:55:57.245Z zigbee-herdsman:adapter:ezsp:uart <-- ACK (3): 1310a1a9602a15740f547e
2024-04-25T15:55:57.246Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 528001340000c6
2024-04-25T15:55:57.246Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x34: {"_cls_":"sendUnicast","_id_":52,"_isRequest_":false,"status":0,"sequence":198}
2024-04-25T15:55:57.247Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (3) success
2024-04-25T15:55:58.845Z zigbee-herdsman:adapter:ezsp:uart <-- [2310b1a96b2a150ab4904b23aa5493499c4e276dfda86735877e]
2024-04-25T15:55:58.846Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (2,3,0): 2310b1a96b2a150ab4904b23aa5493499c4e276dfda86735877e
2024-04-25T15:55:58.846Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (3)
2024-04-25T15:55:58.847Z zigbee-herdsman:adapter:ezsp:uart --> [83401b7e]
2024-04-25T15:55:58.848Z zigbee-herdsman:adapter:ezsp:uart <-- ACK (3): 2310b1a96b2a150ab4904b23aa5493499c4e276dfda86735877e
2024-04-25T15:55:58.848Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 5290013f0000b8ed04010600010100000000c6106600
2024-04-25T15:55:58.850Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x3f: {"_cls_":"messageSentHandler","_id_":63,"_isRequest_":false,"type":0,"indexOrDestination":60856,"apsFrame":{"profileId":260,"sequence":198,"clusterId":6,"sourceEndpoint":1,"destinationEndpoint":1,"groupId":0,"options":0},"messageTag":16,"status":102,"message":{"type":"Buffer","data":[]}}
2024-04-25T15:56:02.154Z zigbee-herdsman:adapter:ezsp:ezsp Time to watchdog ... 0
2024-04-25T15:56:02.154Z zigbee-herdsman:adapter:ezsp:ezsp ==> nop: null
2024-04-25T15:56:02.155Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"nop","_id_":5,"_isRequest_":true}
2024-04-25T15:56:02.157Z zigbee-herdsman:adapter:ezsp:uart --> DATA (3,3,0): 5300010500
2024-04-25T15:56:02.158Z zigbee-herdsman:adapter:ezsp:uart --> [337d3121a9512a9b267e]
2024-04-25T15:56:02.159Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (4)
2024-04-25T15:56:02.164Z zigbee-herdsman:adapter:ezsp:uart <-- [347d31a1a9512a8e5f7e]
2024-04-25T15:56:02.165Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (3,4,0): 3411a1a9512a8e5f7e
2024-04-25T15:56:02.165Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (4)
2024-04-25T15:56:02.166Z zigbee-herdsman:adapter:ezsp:uart --> [8430fc7e]
2024-04-25T15:56:02.168Z zigbee-herdsman:adapter:ezsp:uart <-- ACK (4): 3411a1a9512a8e5f7e
2024-04-25T15:56:02.168Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 5380010500
2024-04-25T15:56:02.170Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x5: {"_cls_":"nop","_id_":5,"_isRequest_":false}
2024-04-25T15:56:02.171Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (4) success
2024-04-25T15:56:07.250Z zigbee-herdsman:adapter:ezsp:debg Response timeout (0xa4c1388d1e14b582:60856,1)
2024-04-25T15:56:07.251Z zigbee-herdsman:adapter:ezsp:debg sendZclFrameToEndpointInternal 0xa4c1388d1e14b582:60856/1 (0,0,1), timeout=10000
2024-04-25T15:56:07.253Z zigbee-herdsman:adapter:ezsp:ezsp ==> sendUnicast: {"type":0,"indexOrDestination":60856,"apsFrame":{"profileId":260,"sequence":16,"clusterId":0,"sourceEndpoint":1,"destinationEndpoint":1,"groupId":0,"options":256},"messageTag":17,"message":{"type":"Buffer","data":[24,12,11,10,0]}}
2024-04-25T15:56:07.253Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"sendUnicast","_id_":52,"_isRequest_":true,"type":0,"indexOrDestination":60856,"apsFrame":{"profileId":260,"sequence":16,"clusterId":0,"sourceEndpoint":1,"destinationEndpoint":1,"groupId":0,"options":256},"messageTag":17,"message":{"type":"Buffer","data":[24,12,11,10,0]}}
2024-04-25T15:56:07.254Z zigbee-herdsman:adapter:ezsp:uart --> DATA (4,4,0): 540001340000b8ed04010000010100010000101105180c0b0a00
2024-04-25T15:56:07.255Z zigbee-herdsman:adapter:ezsp:uart --> [441621a9602a150ab4904b25aa5493499d4e27bbfccb7f87f6cc63393d7e]
2024-04-25T15:56:07.256Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (5)
2024-04-25T15:56:07.257Z zigbee-herdsman:controller:endpoint ZCL command 0xa4c1388d1e14b582/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 60856 - 1 - 4 - 6 - 11 after 10000ms)
Zigbee2MQTT:error 2024-04-25 17:56:07: Publish 'set' 'state' to 'mini_switch1' failed: 'Error: ZCL command 0xa4c1388d1e14b582/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 60856 - 1 - 4 - 6 - 11 after 10000ms)'
Zigbee2MQTT:debug 2024-04-25 17:56:07: Error: ZCL command 0xa4c1388d1e14b582/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 60856 - 1 - 4 - 6 - 11 after 10000ms)
    at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23)
    at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:492:47)
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
    at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)
    at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:760:28)
    at Endpoint.command (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:591:24)
    at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:46:17)
    at Publish.onMQTTMessage (/app/lib/extension/publish.ts:259:36)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17)
2024-04-25T15:56:07.278Z zigbee-herdsman:adapter:ezsp:uart <-- [4516a1a9602a1575f5ff7e]
2024-04-25T15:56:07.279Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (4,5,0): 4516a1a9602a1575f5ff7e
2024-04-25T15:56:07.279Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (5)
2024-04-25T15:56:07.280Z zigbee-herdsman:adapter:ezsp:uart --> [8520dd7e]
2024-04-25T15:56:07.280Z zigbee-herdsman:adapter:ezsp:uart <-- ACK (5): 4516a1a9602a1575f5ff7e
2024-04-25T15:56:07.281Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 548001340000c7
2024-04-25T15:56:07.282Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x34: {"_cls_":"sendUnicast","_id_":52,"_isRequest_":false,"status":0,"sequence":199}
2024-04-25T15:56:07.282Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (5) success
2024-04-25T15:56:08.865Z zigbee-herdsman:adapter:ezsp:uart <-- [5516b1a96b2a150ab4904b25aa5493499c4e276cfca867dc957e]
2024-04-25T15:56:08.867Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (5,5,0): 5516b1a96b2a150ab4904b25aa5493499c4e276cfca867dc957e
2024-04-25T15:56:08.867Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (6)
2024-04-25T15:56:08.867Z zigbee-herdsman:adapter:ezsp:uart --> [8610be7e]
2024-04-25T15:56:08.868Z zigbee-herdsman:adapter:ezsp:uart <-- ACK (5): 5516b1a96b2a150ab4904b25aa5493499c4e276cfca867dc957e
2024-04-25T15:56:08.869Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 5490013f0000b8ed04010000010100000000c7116600
2024-04-25T15:56:08.870Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x3f: {"_cls_":"messageSentHandler","_id_":63,"_isRequest_":false,"type":0,"indexOrDestination":60856,"apsFrame":{"profileId":260,"sequence":199,"clusterId":0,"sourceEndpoint":1,"destinationEndpoint":1,"groupId":0,"options":0},"messageTag":17,"status":102,"message":{"type":"Buffer","data":[]}}
2024-04-25T15:56:12.155Z zigbee-herdsman:adapter:ezsp:ezsp Time to watchdog ... 0
2024-04-25T15:56:12.156Z zigbee-herdsman:adapter:ezsp:ezsp ==> nop: null
2024-04-25T15:56:12.156Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"nop","_id_":5,"_isRequest_":true}
2024-04-25T15:56:12.157Z zigbee-herdsman:adapter:ezsp:uart --> DATA (5,6,0): 5500010500
2024-04-25T15:56:12.157Z zigbee-herdsman:adapter:ezsp:uart --> [561721a9512a4aba7e]
2024-04-25T15:56:12.158Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (6)
2024-04-25T15:56:12.163Z zigbee-herdsman:adapter:ezsp:uart <-- [6617a1a9512ab80e7e]
2024-04-25T15:56:12.164Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (6,6,0): 6617a1a9512ab80e7e
2024-04-25T15:56:12.164Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (7)
2024-04-25T15:56:12.164Z zigbee-herdsman:adapter:ezsp:uart --> [87009f7e]
2024-04-25T15:56:12.165Z zigbee-herdsman:adapter:ezsp:uart <-- ACK (6): 6617a1a9512ab80e7e
2024-04-25T15:56:12.165Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 5580010500
2024-04-25T15:56:12.166Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x5: {"_cls_":"nop","_id_":5,"_isRequest_":false}
2024-04-25T15:56:12.166Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (6) success
2024-04-25T15:56:22.160Z zigbee-herdsman:adapter:ezsp:ezsp Time to watchdog ... 0
2024-04-25T15:56:22.160Z zigbee-herdsman:adapter:ezsp:ezsp ==> nop: null
2024-04-25T15:56:22.161Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"nop","_id_":5,"_isRequest_":true}
2024-04-25T15:56:22.162Z zigbee-herdsman:adapter:ezsp:uart --> DATA (6,7,0): 5600010500
2024-04-25T15:56:22.162Z zigbee-herdsman:adapter:ezsp:uart --> [671421a9512ace447e]
2024-04-25T15:56:22.163Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (7)
2024-04-25T15:56:22.168Z zigbee-herdsman:adapter:ezsp:uart <-- [7714a1a9512a09f87e]
2024-04-25T15:56:22.169Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (7,7,0): 7714a1a9512a09f87e
2024-04-25T15:56:22.170Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (0)
2024-04-25T15:56:22.170Z zigbee-herdsman:adapter:ezsp:uart --> [8070787e]
2024-04-25T15:56:22.171Z zigbee-herdsman:adapter:ezsp:uart <-- ACK (7): 7714a1a9512a09f87e
2024-04-25T15:56:22.172Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 5680010500
2024-04-25T15:56:22.172Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x5: {"_cls_":"nop","_id_":5,"_isRequest_":false}
2024-04-25T15:56:22.173Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (7) success
2024-04-25T15:56:30.520Z zigbee-herdsman:adapter:ezsp:uart <-- [0714b1a97d312a15b658924a2dab5592499c02070f27809874fac6fe83fc7d5e1fa7e95b477e]
2024-04-25T15:56:30.521Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (0,7,0): 0714b1a9112a15b658924a2dab5592499c02070f27809874fac6fe83fc7e1fa7e95b477e
2024-04-25T15:56:30.521Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (1)
2024-04-25T15:56:30.522Z zigbee-herdsman:adapter:ezsp:uart --> [8160597e]
2024-04-25T15:56:30.523Z zigbee-herdsman:adapter:ezsp:uart <-- ACK (7): 0714b1a9112a15b658924a2dab5592499c02070f27809874fac6fe83fc7e1fa7e95b477e
2024-04-25T15:56:30.523Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 569001450000040106000801000000004c20a4ca4effff07009d0a0000200002
2024-04-25T15:56:30.524Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x45: {"_cls_":"incomingMessageHandler","_id_":69,"_isRequest_":false,"type":0,"apsFrame":{"profileId":260,"sequence":76,"clusterId":6,"sourceEndpoint":8,"destinationEndpoint":1,"groupId":0,"options":0},"lastHopLqi":32,"lastHopRssi":-92,"sender":20170,"bindingIndex":255,"addressIndex":255,"message":{"type":"Buffer","data":[0,157,10,0,0,32,0]}}
2024-04-25T15:56:30.525Z zigbee-herdsman:adapter:ezsp:debg processMessage: {"messageType":0,"apsFrame":{"profileId":260,"sequence":76,"clusterId":6,"sourceEndpoint":8,"destinationEndpoint":1,"groupId":0,"options":0},"lqi":32,"rssi":-92,"sender":20170,"bindingIndex":255,"addressIndex":255,"message":{"type":"Buffer","data":[0,157,10,0,0,32,0]}}
2024-04-25T15:56:30.529Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":false,"reservedBits":0},"transactionSequenceNumber":157,"manufacturerCode":null,"commandIdentifier":10},"Payload":[{"attrId":0,"dataType":32,"attrData":0}],"Command":{"ID":10,"name":"report","parameters":[{"name":"attrId","type":33},{"name":"dataType","type":32},{"name":"attrData","type":1000}]}},"address":20170,"endpoint":8,"linkquality":32,"groupID":0,"wasBroadcast":false,"destinationEndpoint":1}'
2024-04-25T15:56:30.538Z zigbee-herdsman:controller:endpoint ZCL command 0x00124b001936790d/8 genOnOff.defaultRsp({"cmdId":10,"statusCode":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":157,"writeUndiv":false})
2024-04-25T15:56:30.540Z zigbee-herdsman:adapter:ezsp:debg sendZclFrameToEndpointInternal 0x00124b001936790d:20170/8 (0,0,1), timeout=10000
Zigbee2MQTT:debug 2024-04-25 17:56:30: Received Zigbee message from 'router_cc2531', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 8 with groupID 0
2024-04-25T15:56:30.548Z zigbee-herdsman:adapter:ezsp:ezsp ==> sendUnicast: {"type":0,"indexOrDestination":20170,"apsFrame":{"profileId":260,"sequence":17,"clusterId":6,"sourceEndpoint":1,"destinationEndpoint":8,"groupId":0,"options":256},"messageTag":18,"message":{"type":"Buffer","data":[24,157,11,10,0]}}
2024-04-25T15:56:30.549Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"sendUnicast","_id_":52,"_isRequest_":true,"type":0,"indexOrDestination":20170,"apsFrame":{"profileId":260,"sequence":17,"clusterId":6,"sourceEndpoint":1,"destinationEndpoint":8,"groupId":0,"options":256},"messageTag":18,"message":{"type":"Buffer","data":[24,157,11,10,0]}}
2024-04-25T15:56:30.551Z zigbee-herdsman:adapter:ezsp:uart --> DATA (7,1,0): 570001340000ca4e04010600010800010000111205189d0b0a00
2024-04-25T15:56:30.551Z zigbee-herdsman:adapter:ezsp:uart --> [711521a9602a157817904b23aa549a499d4e27baffcb7f16f6cc631df77e]
2024-04-25T15:56:30.552Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (0)
Zigbee2MQTT:info  2024-04-25 17:56:30: MQTT publish: topic 'zigbee2mqtt/router_cc2531', payload '{"last_seen":"2024-04-25T15:56:30.530Z","led":false,"linkquality":32}'
2024-04-25T15:56:30.580Z zigbee-herdsman:adapter:ezsp:uart <-- [1015a1a9602a157a5f487e]
2024-04-25T15:56:30.581Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (1,0,0): 1015a1a9602a157a5f487e
2024-04-25T15:56:30.582Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (2)
2024-04-25T15:56:30.582Z zigbee-herdsman:adapter:ezsp:uart --> [82503a7e]
2024-04-25T15:56:30.583Z zigbee-herdsman:adapter:ezsp:uart <-- ACK (0): 1015a1a9602a157a5f487e
2024-04-25T15:56:30.583Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 578001340000c8
2024-04-25T15:56:30.584Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x34: {"_cls_":"sendUnicast","_id_":52,"_isRequest_":false,"status":0,"sequence":200}
2024-04-25T15:56:30.584Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (0) success
2024-04-25T15:56:30.593Z zigbee-herdsman:adapter:ezsp:uart <-- [2015b1a96b2a157817904b23aa549a499d4e2763ffce67c4747e]
2024-04-25T15:56:30.594Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (2,0,0): 2015b1a96b2a157817904b23aa549a499d4e2763ffce67c4747e
2024-04-25T15:56:30.595Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (3)
2024-04-25T15:56:30.596Z zigbee-herdsman:adapter:ezsp:uart --> [83401b7e]
2024-04-25T15:56:30.598Z zigbee-herdsman:adapter:ezsp:uart <-- ACK (0): 2015b1a96b2a157817904b23aa549a499d4e2763ffce67c4747e
2024-04-25T15:56:30.599Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 5790013f0000ca4e04010600010800010000c8120000
2024-04-25T15:56:30.600Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x3f: {"_cls_":"messageSentHandler","_id_":63,"_isRequest_":false,"type":0,"indexOrDestination":20170,"apsFrame":{"profileId":260,"sequence":200,"clusterId":6,"sourceEndpoint":1,"destinationEndpoint":8,"groupId":0,"options":256},"messageTag":18,"status":0,"message":{"type":"Buffer","data":[]}}
2024-04-25T15:56:32.162Z zigbee-herdsman:adapter:ezsp:ezsp Time to watchdog ... 0
2024-04-25T15:56:32.162Z zigbee-herdsman:adapter:ezsp:ezsp ==> nop: null
2024-04-25T15:56:32.163Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"nop","_id_":5,"_isRequest_":true}
2024-04-25T15:56:32.163Z zigbee-herdsman:adapter:ezsp:uart --> DATA (0,3,0): 5800010500
2024-04-25T15:56:32.164Z zigbee-herdsman:adapter:ezsp:uart --> [037d3a21a9512a58557e]
2024-04-25T15:56:32.165Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (1)
2024-04-25T15:56:32.170Z zigbee-herdsman:adapter:ezsp:uart <-- [317d3aa1a9512a21a17e]
2024-04-25T15:56:32.171Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (3,1,0): 311aa1a9512a21a17e
2024-04-25T15:56:32.171Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (4)
2024-04-25T15:56:32.180Z zigbee-herdsman:adapter:ezsp:uart --> [8430fc7e]
2024-04-25T15:56:32.181Z zigbee-herdsman:adapter:ezsp:uart <-- ACK (1): 311aa1a9512a21a17e
2024-04-25T15:56:32.181Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 5880010500
2024-04-25T15:56:32.182Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x5: {"_cls_":"nop","_id_":5,"_isRequest_":false}
2024-04-25T15:56:32.183Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (1) success
Zigbee2MQTT:debug 2024-04-25 17:56:37: Saving state to file /app/data/state.json
2024-04-25T15:56:42.167Z zigbee-herdsman:adapter:ezsp:ezsp Time to watchdog ... 0
2024-04-25T15:56:42.168Z zigbee-herdsman:adapter:ezsp:ezsp ==> nop: null
2024-04-25T15:56:42.168Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"nop","_id_":5,"_isRequest_":true}
2024-04-25T15:56:42.169Z zigbee-herdsman:adapter:ezsp:uart --> DATA (1,4,0): 5900010500
2024-04-25T15:56:42.169Z zigbee-herdsman:adapter:ezsp:uart --> [141b21a9512a20c17e]
2024-04-25T15:56:42.170Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (2)
2024-04-25T15:56:42.176Z zigbee-herdsman:adapter:ezsp:uart <-- [421ba1a9512a008c7e]
2024-04-25T15:56:42.177Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (4,2,0): 421ba1a9512a008c7e
2024-04-25T15:56:42.177Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (5)
2024-04-25T15:56:42.177Z zigbee-herdsman:adapter:ezsp:uart --> [8520dd7e]
2024-04-25T15:56:42.178Z zigbee-herdsman:adapter:ezsp:uart <-- ACK (2): 421ba1a9512a008c7e
2024-04-25T15:56:42.179Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 5980010500
2024-04-25T15:56:42.179Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x5: {"_cls_":"nop","_id_":5,"_isRequest_":false}
2024-04-25T15:56:42.180Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (2) success

**Comment by Bitcraze26** [comment]
UPDATE: able to set ON and OFF only plugged and paired with coordinator in just 2 meters away.
In about 3 meter (line of sight) it won't work.
Dongle with 1.5 meter USB cord away from raspberry and from wifi nets
