### ISSUE TITLE
The adapter crashes after about a week of operation

### ISSUE THREAD

**Issue by almirus** [Koenkk/zigbee2mqtt#22367]
### What happened?

The Zigbee stick is connected to the USB port of an x86 mini computer. HA is running through Proxmox. Only physically disconnecting and reconnecting the stick or rebooting the PC helps. The usbreset utility run on Proxmox does not help. The frozen device is visible in the system, but zigbee2mqtt cannot connect to it.

### Zigbee2MQTT version

1.36.1

### Adapter firmware version

20230507

### Adapter

egony cc2652p

### Setup

Home Assistant OS x86 (via Proxmox)

### Debug log

Zigbee2MQTT:error 2024-04-30 22:37:27: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-04-30 22:37:27: Failed to start zigbee
Zigbee2MQTT:error 2024-04-30 22:37:27: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-04-30 22:37:27: Exiting...
Zigbee2MQTT:error 2024-04-30 22:37:27: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:62:27)
    at Controller.start (/app/lib/controller.ts:109:27)
    at start (/app/index.js:107:5)
[22:37:28] INFO: Preparing to start...
[22:37:28] INFO: Socat not enabled
[22:37:28] INFO: Zigbee Herdsman debug logging enabled
[22:37:29] INFO: Starting Zigbee2MQTT...
2024-04-30T19:37:31.243Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2024-04-30T19:37:31.244Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[25]},"serialPort":{"path":"/dev/ttyUSB0"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2024-04-30T19:37:31.245Z zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with {"path":"/dev/ttyUSB0","baudRate":115200,"rtscts":false,"autoOpen":false}
2024-04-30T19:37:31.251Z zigbee-herdsman:adapter:zStack:znp:log Serialport opened
2024-04-30T19:37:31.252Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2024-04-30T19:37:31.253Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2024-04-30T19:37:31.505Z zigbee-herdsman:adapter:zStack:znp:log Writing CC2530/CC2531 skip bootloader payload
2024-04-30T19:37:31.505Z zigbee-herdsman:adapter:zStack:unpi:writer --> buffer [239]
2024-04-30T19:37:32.508Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2024-04-30T19:37:32.508Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2024-04-30T19:37:32.760Z zigbee-herdsman:adapter:zStack:znp:log Skip bootloader for CC2652/CC1352
2024-04-30T19:37:33.216Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2024-04-30T19:37:33.216Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]

**Comment by Koenkk** [comment]
Try the fw from https://github.com/Koenkk/Z-Stack-firmware/discussions/496 and provide your feedback there.
