### ISSUE TITLE
Dongle-P crashes with an error

### ISSUE THREAD

**Issue by den67rus** [Koenkk/zigbee2mqtt#22403]
### What happened?

After upgrading to version 1.37.0-1, it started to crash with some kind of error

### How to reproduce it (minimal and precise)

I can't determine. But it repeats itself.
0x54ef441000691c58: https://www.zigbee2mqtt.io/devices/ZNXNKG02LM.html 

### Zigbee2MQTT version

1.37.0-1

### Adapter firmware version

20230507

### Adapter

Sonoff ZBDongle-P

### Setup

HAOS

### Debug log

[2024-05-02 15:48:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-05-02 15:48:08] debug: 	zh:zstack:unpi:parser: <-- [254,3,68,128,0,1,33,231]
[2024-05-02 15:48:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,3,68,128,0,1,33,231]
[2024-05-02 15:48:08] debug: 	zh:zstack:unpi:parser: --> parsed 3 - 2 - 4 - 128 - [0,1,33] - 231
[2024-05-02 15:48:08] debug: 	zh:zstack:znp: AREQ: <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":33}
[2024-05-02 15:48:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-05-02 15:48:09] debug: 	zh:zstack:unpi:parser: <-- [254,5,69,196,72,107,1,62,160,56]
[2024-05-02 15:48:09] debug: 	zh:zstack:unpi:parser: --- parseNext [254,5,69,196,72,107,1,62,160,56]
[2024-05-02 15:48:09] debug: 	zh:zstack:unpi:parser: --> parsed 5 - 2 - 5 - 196 - [72,107,1,62,160] - 56
[2024-05-02 15:48:09] debug: 	zh:zstack:znp: AREQ: <-- ZDO - srcRtgInd - {"dstaddr":27464,"relaycount":1,"relaylist":[41022]}
[2024-05-02 15:48:09] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-05-02 15:48:09] debug: 	zh:zstack:unpi:parser: <-- [254,65,68,129,0,0,192,252,72,107,1,1,0,40,0,64,70,179,0,0,45,28,95,17,180,10,247,0,65,36,1,33,55,12,3,40,25,4,33,168,19,5,33,110,0,6,36,3,0,0,0,0,8,33,20,1,10,33,62,160,12,32,1,100,16,0,62,160,28,219]
[2024-05-02 15:48:09] debug: 	zh:zstack:unpi:parser: --- parseNext [254,65,68,129,0,0,192,252,72,107,1,1,0,40,0,64,70,179,0,0,45,28,95,17,180,10,247,0,65,36,1,33,55,12,3,40,25,4,33,168,19,5,33,110,0,6,36,3,0,0,0,0,8,33,20,1,10,33,62,160,12,32,1,100,16,0,62,160,28,219]
[2024-05-02 15:48:09] debug: 	zh:zstack:unpi:parser: --> parsed 65 - 2 - 4 - 129 - [0,0,192,252,72,107,1,1,0,40,0,64,70,179,0,0,45,28,95,17,180,10,247,0,65,36,1,33,55,12,3,40,25,4,33,168,19,5,33,110,0,6,36,3,0,0,0,0,8,33,20,1,10,33,62,160,12,32,1,100,16,0,62,160,28] - 219
[2024-05-02 15:48:09] debug: 	zh:zstack:znp: AREQ: <-- AF - incomingMsg - {"groupid":0,"clusterid":64704,"srcaddr":27464,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":40,"securityuse":0,"timestamp":11748928,"transseqnumber":0,"len":45,"data":{"type":"Buffer","data":[28,95,17,180,10,247,0,65,36,1,33,55,12,3,40,25,4,33,168,19,5,33,110,0,6,36,3,0,0,0,0,8,33,20,1,10,33,62,160,12,32,1,100,16,0]}}
[2024-05-02 15:48:09] debug: 	zh:controller: Received payload: clusterID=64704, address=27464, groupID=0, endpoint=1, destinationEndpoint=1, wasBroadcast=false, linkQuality=40, frame={"header":{"frameControl":{"frameType":0,"manufacturerSpecific":true,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"manufacturerCode":4447,"transactionSequenceNumber":180,"commandIdentifier":10},"payload":[{"attrId":247,"dataType":65,"attrData":{"type":"Buffer","data":[1,33,55,12,3,40,25,4,33,168,19,5,33,110,0,6,36,3,0,0,0,0,8,33,20,1,10,33,62,160,12,32,1,100,16,0]}}],"command":{"ID":10,"name":"report","parameters":[{"name":"attrId","type":33},{"name":"dataType","type":32},{"name":"attrData","type":1000}]}}
[2024-05-02 15:48:09] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-05-02 15:48:09] debug: 	z2m: Received Zigbee message from '0x54ef441000691c58', type 'attributeReport', cluster 'manuSpecificLumi', data '{"247":{"data":[1,33,55,12,3,40,25,4,33,168,19,5,33,110,0,6,36,3,0,0,0,0,8,33,20,1,10,33,62,160,12,32,1,100,16,0],"type":"Buffer"}}' from endpoint 1 with groupID 0
ReferenceError: meta is not defined
    at numericAttributes2Lookup (/app/node_modules/zigbee-herdsman-converters/src/lib/lumi.ts:845:57)
    at Object.convert (/app/node_modules/zigbee-herdsman-converters/src/lib/lumi.ts:1888:49)
    at Receive.onDeviceMessage (/app/lib/extension/receive.ts:153:51)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:23)
    at EventEmitter.emit (node:events:529:35)
    at EventBus.emitDeviceMessage (/app/lib/eventBus.ts:108:22)
    at Controller.<anonymous> (/app/lib/zigbee.ts:117:27)

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.
