### ISSUE TITLE
Aqara shade driver E1 keeps erroring out

### ISSUE THREAD

**Issue by vinodmishra** [Koenkk/zigbee2mqtt#22431]
### What happened?

I have two Aqara shade drives. It seems one exposes this cluster manuSpecificLumi while the other one doesn't even though they are the exact same model numbers and have the same manufacturing date. 

The blind that works fine 
![image](https://github.com/Koenkk/zigbee2mqtt/assets/1963995/111f1637-3014-449c-b81a-9adb9b85952b)

The blind that throws the error
![image](https://github.com/Koenkk/zigbee2mqtt/assets/1963995/0f25a88f-0ee0-48a4-9d74-c4729cdf5f57)

### What did you expect to happen?

I expected both blinds to behave the same.

### How to reproduce it (minimal and precise)

I am not doing anything special. Just paired both and one is the state that keeps throwing errors

### Zigbee2MQTT version

1.37.0

### Adapter firmware version

20230507

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P

### Setup

containerized

### Debug log

info 2024-05-03 19:27:23Configuring 'Bedroom blinds'
error 2024-05-03 19:27:24Failed to configure 'Bedroom blinds', attempt 3 (Error: Device 0x54ef441000aa0643 has no input cluster manuSpecificLumi at getEndpointsWithCluster (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:30:15) at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:67:55) at configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:112:23) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:160:27) at Configure.configure (/app/lib/extension/configure.ts:121:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

**Comment by vinodmishra** [comment]
Closing this as it seems it was an issue with signal strength. Adding an ikea signal repeater near the shade driver and then deleting and pairing the shade driver  fixed the issue. Hope this helps anyone who is facing the same issue.
