### ISSUE TITLE
Sonoff ZBDongle-E / Firmware 7.4.2 / docker unable to start

### ISSUE THREAD

**Issue by rgafarov** [Koenkk/zigbee2mqtt#22510]
### What happened?

Hello,
Unable to start zigbee2mqtt.

### What did you expect to happen?

Work with docker

### How to reproduce it (minimal and precise)

I bought new dongle and tried to use latest docker image of zigbee2mqtt.

I updated my dongle to 7.4.2.

Also, I tried to use zigbee-herdsman (0.46.4) by local image rebuilding.

My config:

```
serial:
  adapter: ember
  port: /dev/ttyACM0

frontend:
  port: 8099
  url: 'http://zigbee2mqtt:8099'

homeassistant: true

advanced:
  log_level: debug
```

### Zigbee2MQTT version

Unable to access

### Adapter firmware version

Unable to access

### Adapter

QinHeng Electronics SONOFF Zigbee 3.0 USB Dongle Plus V2

### Setup

run as docker image using docker-compose

### Debug log

```
[2024-05-07 01:57:50] info:     z2m: Logging to console, file (filename: log.log)
[2024-05-07 01:57:52] debug:    z2m: Can't load state from file /app/data/state.json (doesn't exist)
[2024-05-07 01:57:52] info:     z2m: Starting Zigbee2MQTT version 1.37.0 (commit #)
[2024-05-07 01:57:52] info:     z2m: Starting zigbee-herdsman (0.46.4)
[2024-05-07 01:57:52] debug:    z2m: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"ember","path":"/dev/ttyACM0"}}'
[2024-05-07 01:57:53] debug:    zh:adapter: Path '/dev/ttyACM0' is valid for 'EmberAdapter'
[2024-05-07 01:57:53] debug:    zh:ember: Using delay=5.
[2024-05-07 01:57:53] debug:    zh:controller: Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/ttyACM0","adapter":"ember"},"databasePath":"/app/data/database.db","databaseBackupPath":"/app/data/database.db.backup","backupPath":"/app/data/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
[2024-05-07 01:57:53] info:     zh:ember: ======== Ember Adapter Starting ========
[2024-05-07 01:57:53] debug:    zh:ember: Starting EZSP with stack configuration: "default".
[2024-05-07 01:57:53] info:     zh:ember:ezsp: ======== EZSP starting ========
[2024-05-07 01:57:53] info:     zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-05-07 01:57:53] info:     zh:ember:uart:ash: RTS/CTS config is off, enabling software flow control.
[2024-05-07 01:57:53] debug:    zh:ember:uart:ash: Opening serial port with {"path":"/dev/ttyACM0","baudRate":115200,"rtscts":false,"autoOpen":false,"parity":"none","stopBits":1,"xon":true,"xoff":true}
[2024-05-07 01:57:53] info:     zh:ember:uart:ash: Serial port opened
[2024-05-07 01:57:53] info:     zh:ember:uart:ash: ======== ASH starting ========
[2024-05-07 01:57:53] debug:    zh:ember:uart:ash: ---> [FRAME type=RST]
[2024-05-07 01:57:53] debug:    zh:ember:uart:ash: Waiting for RSTACK... 0/2500
[2024-05-07 01:57:53] debug:    zh:ember:uart:ash: Waiting for RSTACK... 100/2500
[2024-05-07 01:57:53] debug:    zh:ember:uart:ash: Waiting for RSTACK... 200/2500
[2024-05-07 01:57:53] debug:    zh:ember:uart:ash: Waiting for RSTACK... 300/2500
[2024-05-07 01:57:53] debug:    zh:ember:uart:ash: Waiting for RSTACK... 400/2500
[2024-05-07 01:57:53] debug:    zh:ember:uart:ash: Waiting for RSTACK... 500/2500
[2024-05-07 01:57:53] debug:    zh:ember:uart:ash: Waiting for RSTACK... 600/2500
[2024-05-07 01:57:53] debug:    zh:ember:uart:ash: Waiting for RSTACK... 700/2500
[2024-05-07 01:57:54] debug:    zh:ember:uart:ash: Waiting for RSTACK... 800/2500
[2024-05-07 01:57:54] debug:    zh:ember:uart:ash: Waiting for RSTACK... 900/2500
[2024-05-07 01:57:54] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1000/2500
[2024-05-07 01:57:54] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1100/2500
[2024-05-07 01:57:54] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1200/2500
[2024-05-07 01:57:54] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1300/2500
[2024-05-07 01:57:54] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1400/2500
[2024-05-07 01:57:54] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1500/2500
[2024-05-07 01:57:54] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1600/2500
[2024-05-07 01:57:55] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1700/2500
[2024-05-07 01:57:55] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1800/2500
[2024-05-07 01:57:55] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1900/2500
[2024-05-07 01:57:55] debug:    zh:ember:uart:ash: Waiting for RSTACK... 2000/2500
[2024-05-07 01:57:55] debug:    zh:ember:uart:ash: Waiting for RSTACK... 2100/2500
[2024-05-07 01:57:55] debug:    zh:ember:uart:ash: Waiting for RSTACK... 2200/2500
[2024-05-07 01:57:55] error:    zh:ember:uart:ash: ASH disconnected: ASH_ERROR_RESET_FAIL | NCP status: NO_ERROR
[2024-05-07 01:57:55] info:     zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-05-07 01:57:55] info:     zh:ember:uart:ash: ======== ASH starting ========
[2024-05-07 01:57:55] debug:    zh:ember:uart:ash: ---> [FRAME type=RST]
[2024-05-07 01:57:55] debug:    zh:ember:uart:ash: Waiting for RSTACK... 0/2500
[2024-05-07 01:57:55] debug:    zh:ember:uart:ash: Waiting for RSTACK... 100/2500
[2024-05-07 01:57:55] debug:    zh:ember:uart:ash: Waiting for RSTACK... 200/2500
[2024-05-07 01:57:56] debug:    zh:ember:uart:ash: Waiting for RSTACK... 300/2500
[2024-05-07 01:57:56] debug:    zh:ember:uart:ash: Waiting for RSTACK... 400/2500
[2024-05-07 01:57:56] debug:    zh:ember:uart:ash: Waiting for RSTACK... 500/2500
[2024-05-07 01:57:56] debug:    zh:ember:uart:ash: Waiting for RSTACK... 600/2500
[2024-05-07 01:57:56] debug:    zh:ember:uart:ash: Waiting for RSTACK... 700/2500
[2024-05-07 01:57:56] debug:    zh:ember:uart:ash: Waiting for RSTACK... 800/2500
[2024-05-07 01:57:56] debug:    zh:ember:uart:ash: Waiting for RSTACK... 900/2500
[2024-05-07 01:57:56] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1000/2500
[2024-05-07 01:57:56] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1100/2500
[2024-05-07 01:57:57] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1200/2500
[2024-05-07 01:57:57] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1300/2500
[2024-05-07 01:57:57] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1400/2500
[2024-05-07 01:57:57] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1500/2500
[2024-05-07 01:57:57] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1600/2500
[2024-05-07 01:57:57] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1700/2500
[2024-05-07 01:57:57] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1800/2500
[2024-05-07 01:57:57] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1900/2500
[2024-05-07 01:57:58] debug:    zh:ember:uart:ash: Waiting for RSTACK... 2000/2500
[2024-05-07 01:57:58] debug:    zh:ember:uart:ash: Waiting for RSTACK... 2100/2500
[2024-05-07 01:57:58] error:    zh:ember:uart:ash: ASH disconnected: ASH_ERROR_RESET_FAIL | NCP status: NO_ERROR
[2024-05-07 01:57:58] info:     zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-05-07 01:57:58] info:     zh:ember:uart:ash: ======== ASH starting ========
[2024-05-07 01:57:58] debug:    zh:ember:uart:ash: ---> [FRAME type=RST]
[2024-05-07 01:57:58] debug:    zh:ember:uart:ash: Waiting for RSTACK... 0/2500
[2024-05-07 01:57:58] debug:    zh:ember:uart:ash: Waiting for RSTACK... 100/2500
[2024-05-07 01:57:58] debug:    zh:ember:uart:ash: Waiting for RSTACK... 200/2500
[2024-05-07 01:57:58] debug:    zh:ember:uart:ash: Waiting for RSTACK... 300/2500
[2024-05-07 01:57:58] debug:    zh:ember:uart:ash: Waiting for RSTACK... 400/2500
[2024-05-07 01:57:58] debug:    zh:ember:uart:ash: Waiting for RSTACK... 500/2500
[2024-05-07 01:57:58] debug:    zh:ember:uart:ash: Waiting for RSTACK... 600/2500
[2024-05-07 01:57:59] debug:    zh:ember:uart:ash: Waiting for RSTACK... 700/2500
[2024-05-07 01:57:59] debug:    zh:ember:uart:ash: Waiting for RSTACK... 800/2500
[2024-05-07 01:57:59] debug:    zh:ember:uart:ash: Waiting for RSTACK... 900/2500
[2024-05-07 01:57:59] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1000/2500
[2024-05-07 01:57:59] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1100/2500
[2024-05-07 01:57:59] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1200/2500
[2024-05-07 01:57:59] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1300/2500
[2024-05-07 01:57:59] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1400/2500
[2024-05-07 01:57:59] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1500/2500
[2024-05-07 01:58:00] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1600/2500
[2024-05-07 01:58:00] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1700/2500
[2024-05-07 01:58:00] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1800/2500
[2024-05-07 01:58:00] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1900/2500
[2024-05-07 01:58:00] debug:    zh:ember:uart:ash: Waiting for RSTACK... 2000/2500
[2024-05-07 01:58:00] debug:    zh:ember:uart:ash: Waiting for RSTACK... 2100/2500
[2024-05-07 01:58:00] debug:    zh:ember:uart:ash: Waiting for RSTACK... 2200/2500
[2024-05-07 01:58:00] error:    zh:ember:uart:ash: ASH disconnected: ASH_ERROR_RESET_FAIL | NCP status: NO_ERROR
[2024-05-07 01:58:00] info:     zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-05-07 01:58:00] info:     zh:ember:uart:ash: ======== ASH starting ========
[2024-05-07 01:58:00] debug:    zh:ember:uart:ash: ---> [FRAME type=RST]
[2024-05-07 01:58:00] debug:    zh:ember:uart:ash: Waiting for RSTACK... 0/2500
[2024-05-07 01:58:00] debug:    zh:ember:uart:ash: Waiting for RSTACK... 100/2500
[2024-05-07 01:58:01] debug:    zh:ember:uart:ash: Waiting for RSTACK... 200/2500
[2024-05-07 01:58:01] debug:    zh:ember:uart:ash: Waiting for RSTACK... 300/2500
[2024-05-07 01:58:01] debug:    zh:ember:uart:ash: Waiting for RSTACK... 400/2500
[2024-05-07 01:58:01] debug:    zh:ember:uart:ash: Waiting for RSTACK... 500/2500
[2024-05-07 01:58:01] debug:    zh:ember:uart:ash: Waiting for RSTACK... 600/2500
[2024-05-07 01:58:01] debug:    zh:ember:uart:ash: Waiting for RSTACK... 700/2500
[2024-05-07 01:58:01] debug:    zh:ember:uart:ash: Waiting for RSTACK... 800/2500
[2024-05-07 01:58:01] debug:    zh:ember:uart:ash: Waiting for RSTACK... 900/2500
[2024-05-07 01:58:02] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1000/2500
[2024-05-07 01:58:02] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1100/2500
[2024-05-07 01:58:02] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1200/2500
[2024-05-07 01:58:02] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1300/2500
[2024-05-07 01:58:02] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1400/2500
[2024-05-07 01:58:02] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1500/2500
[2024-05-07 01:58:02] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1600/2500
[2024-05-07 01:58:02] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1700/2500
[2024-05-07 01:58:02] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1800/2500
[2024-05-07 01:58:03] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1900/2500
[2024-05-07 01:58:03] debug:    zh:ember:uart:ash: Waiting for RSTACK... 2000/2500
[2024-05-07 01:58:03] debug:    zh:ember:uart:ash: Waiting for RSTACK... 2100/2500
[2024-05-07 01:58:03] error:    zh:ember:uart:ash: ASH disconnected: ASH_ERROR_RESET_FAIL | NCP status: NO_ERROR
[2024-05-07 01:58:03] info:     zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-05-07 01:58:03] info:     zh:ember:uart:ash: ======== ASH starting ========
[2024-05-07 01:58:03] debug:    zh:ember:uart:ash: ---> [FRAME type=RST]
[2024-05-07 01:58:03] debug:    zh:ember:uart:ash: Waiting for RSTACK... 0/2500
[2024-05-07 01:58:03] debug:    zh:ember:uart:ash: Waiting for RSTACK... 100/2500
[2024-05-07 01:58:03] debug:    zh:ember:uart:ash: Waiting for RSTACK... 200/2500
[2024-05-07 01:58:03] debug:    zh:ember:uart:ash: Waiting for RSTACK... 300/2500
[2024-05-07 01:58:03] debug:    zh:ember:uart:ash: Waiting for RSTACK... 400/2500
[2024-05-07 01:58:04] debug:    zh:ember:uart:ash: Waiting for RSTACK... 500/2500
[2024-05-07 01:58:04] debug:    zh:ember:uart:ash: Waiting for RSTACK... 600/2500
[2024-05-07 01:58:04] debug:    zh:ember:uart:ash: Waiting for RSTACK... 700/2500
[2024-05-07 01:58:04] debug:    zh:ember:uart:ash: Waiting for RSTACK... 800/2500
[2024-05-07 01:58:04] debug:    zh:ember:uart:ash: Waiting for RSTACK... 900/2500
[2024-05-07 01:58:04] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1000/2500
[2024-05-07 01:58:04] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1100/2500
[2024-05-07 01:58:04] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1200/2500
[2024-05-07 01:58:04] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1300/2500
[2024-05-07 01:58:05] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1400/2500
[2024-05-07 01:58:05] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1500/2500
[2024-05-07 01:58:05] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1600/2500
[2024-05-07 01:58:05] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1700/2500
[2024-05-07 01:58:05] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1800/2500
[2024-05-07 01:58:05] debug:    zh:ember:uart:ash: Waiting for RSTACK... 1900/2500
[2024-05-07 01:58:05] debug:    zh:ember:uart:ash: Waiting for RSTACK... 2000/2500
[2024-05-07 01:58:06] error:    zh:ember:uart:ash: ASH disconnected: ASH_ERROR_RESET_FAIL | NCP status: NO_ERROR
[2024-05-07 01:58:06] error:    z2m: Error while starting zigbee-herdsman
[2024-05-07 01:58:06] error:    z2m: Failed to start zigbee
[2024-05-07 01:58:06] error:    z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-05-07 01:58:06] error:    z2m: Exiting...
[2024-05-07 01:58:06] error:    z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:798:19)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:2660:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:124:29)
    at Zigbee.start (/app/lib/zigbee.ts:62:27)
    at Controller.start (/app/lib/controller.ts:108:27)
    at start (/app/index.js:107:5)

```

**Comment by rgafarov** [comment]
@Nerivec thank you for your help, my bad, I uploaded firmware with 230400 baudrate by mistake, now with 7.4.2-115200 device replying properly)

btw, tried to set 230400 in config and it's not applied, looks like new possible values have to be added to the code)
