### ISSUE TITLE
[New device support]: wxkg21lm Aqara 

### ISSUE THREAD

**Issue by walkpig** [Koenkk/zigbee2mqtt#22542]
### Link

https://www.aliexpress.com/item/3256805590979867.html?spm=a2g0o.productlist.main.1.f36715f1WaEHOh&algo_pvid=73cc4025-4c9d-458d-bab4-36d11f2ebecb&algo_exp_id=73cc4025-4c9d-458d-bab4-36d11f2ebecb-0&pdp_npi=4%40dis%21USD%2120.00%2120.00%21%21%2120.00%2120.00%21%402101e80317151828673622688e67ab%2112000036830739186%21sea%21US%21917119002%21&curPageLogUid=nXdiSCoQkomI&utparam-url=scene%3Asearch%7Cquery_from%3A

### Database entry

{"id":44,"type":"EndDevice","ieeeAddr":"0x54ef44100078e884","nwkAddr":17518,"manufId":4447,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.remote.acn008","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":0,"inClusterList":[0,1,3,18,64704],"outClusterList":[3,6,25],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.remote.acn008","manufacturerName":"LUMI","powerSource":3,"zclVersion":3,"appVersion":7,"stackVersion":2,"hwVersion":0}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00212effff082d70","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":7,"stackVersion":2,"hwVersion":0,"zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1715182959623}

### Comments
This is the wireless single rocker aqara H1M switch
lumi.remote.acn008.
Tried following https://github.com/Koenkk/zigbee2mqtt/issues/19109. 
But i was able to get the switch recognized but unresponsive.

### External definition

```shell
const {battery, identify, commandsOnOff} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['lumi.remote.acn008'],
    model: 'lumi.remote.acn008',
    vendor: 'LUMI',
    description: 'Automatically generated definition',
    extend: [battery(), identify(), commandsOnOff()],
    meta: {},
};

module.exports = definition;
```

**Comment by walkpig** [comment]
rror 2024-05-16 23:39:57Publish 'set' 'click_mode' to '0x54ef44100078e884' failed: 'Error: ZCL command 0x54ef44100078e884/1 manuSpecificLumi.write({"293":{"value":2,"type":32}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (9))'
Info 2024-05-16 23:40:15Configuring '0x54ef44100078e884'
Info 2024-05-16 23:40:20Successfully configured '0x54ef44100078e884'
Error 2024-05-16 23:40:43Publish 'set' 'operation_mode' to '0x54ef44100078e884' failed: 'Error: ZCL command 0x54ef44100078e884/1 manuSpecificLumi.write({"mode":1}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (14))'
Info 2024-05-16 23:42:07Configuring '0x54ef44100078e884'
Error 2024-05-16 23:42:17Failed to configure '0x54ef44100078e884', attempt 1 (Error: ZCL command 0x54ef44100078e884/1 manuSpecificLumi.write({"mode":1}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (15)) at DeconzAdapter.sendZclFrameToEndpoint (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:664:23) at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:767:28) at Endpoint.write (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:359:9) at Object.configure (/app/data/extension/externally-loaded.js:36:9) at Configure.configure (/app/lib/extension/configure.ts:121:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:21) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
