### ISSUE TITLE
Ikea E2002 Styrbar switch deleted and rejoined OK won't work, won't reconfigure (possible followup to #22458)

### ISSUE THREAD

**Issue by Ian-42erghwWhbvw** [Koenkk/zigbee2mqtt#22634]
### What happened?

I was/am experiencing issues with not being able to use some actions that previously worked on Styrbar switches after updating them (OTA) to firmware 2.4.11 - essentially as detailed in Issue #22458.

As part of working through the proffered solutions in #22458 I upgraded Z2M to  1.37.1 commit: ea39d86 and then I deleted and rejoined the Styrbar switch. Rejoined OK but now wasn't registering ANY buttons at all, not even the ones that previously worked (e.g. OF/OFF). Tried a reconfigure from the yellow button on the device's page and got the following error logged:

Info 2024-05-14 15:44:44Configuring 'Styrbar Switch IV'
Error 2024-05-14 15:44:54Failed to configure 'Styrbar Switch IV', attempt 7 (Error: Bind 0x30fb10fffedd2259/1 genOnOff from '0x00124b0026b7a968/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:691:28 at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:464:13) at Object.bind (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:43:9) at configure (/app/node_modules/zigbee-herdsman-converters/src/lib/ikea.ts:143:17) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:172:21) at Configure.configure (/app/lib/extension/configure.ts:121:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:21) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

Styrbar switches were happily working with all button actions on earlier Styrbar firmware and earlier Z2M version (1.36.1 I think). I have Styrbar switches still partially working (ON/OFF actions file, left and right not) other than the one I pulled to use as a victim for debugging.

So in summary: Will pair, will interview, won't log any button presses, a reconfigure generates the error log posted; was working on earlier firmware/z2m, other Styrbars with newest firmware/z2m still work but are still missing left and right button actions (i.e. I don't think #22458 fixed what it was supposed to).

### What did you expect to happen?

Expected Styrbar to operate correctly, including all button actions.

### How to reproduce it (minimal and precise)

Try to join a Styrbar E2002 switch with latest firmware to Z2M and "configure" it.

### Zigbee2MQTT version

1.37.1

### Adapter firmware version

20210708

### Adapter

Sonoff ZB dongle p (zStack3x0)

### Setup

Docker container under TrueNAS scale k8s

### Debug log

[2024-05-14 16:17:49] info:     z2m: Configuring 'Styrbar Switch IV'
[2024-05-14 16:17:49] debug:    zh:controller:endpoint: Bind 0x30fb10fffedd2259/1 genOnOff from '0x00124b0026b7a968/1'
[2024-05-14 16:17:49] debug:    zh:zstack:znp: SREQ: --> ZDO - bindReq - {"dstaddr":11043,"srcaddr":"0x30fb10fffedd2259","srcendpoint":1,"clusterid":6,"dstaddrmode":3,"dstaddress":"0x00124b0026b7a968","dstendpoint":1}
[2024-05-14 16:17:49] debug:    zh:zstack:unpi:writer: --> frame [254,23,37,33,35,43,89,34,221,254,255,16,251,48,1,6,0,3,104,169,183,38,0,75,18,0,1,107]
[2024-05-14 16:17:49] debug:    zh:zstack:unpi:parser: <-- [254,1,101,33,0,69]
[2024-05-14 16:17:49] debug:    zh:zstack:unpi:parser: --- parseNext [254,1,101,33,0,69]
[2024-05-14 16:17:49] debug:    zh:zstack:unpi:parser: --> parsed 1 - 3 - 5 - 33 - [0] - 69
[2024-05-14 16:17:49] debug:    zh:zstack:znp: SRSP: <-- ZDO - bindReq - {"status":0}
[2024-05-14 16:17:49] debug:    zh:zstack:unpi:parser: --- parseNext []
[2024-05-14 16:17:59] debug:    zh:controller:endpoint: Bind 0x30fb10fffedd2259/1 genOnOff from '0x00124b0026b7a968/1' failed (AREQ - ZDO - bindRsp after 10000ms)
[2024-05-14 16:17:59] error:    z2m: Failed to configure 'Styrbar Switch IV', attempt 1 (Error: Bind 0x30fb10fffedd2259/1 genOnOff from '0x00124b0026b7a968/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23)
    at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:691:28
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
    at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:464:13)
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:43:9)
    at configure (/app/node_modules/zigbee-herdsman-converters/src/lib/ikea.ts:143:17)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:172:21)
    at Configure.configure (/app/lib/extension/configure.ts:121:13)
    at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:21)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
[2024-05-14 16:17:59] debug:    z2m: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"Styrbar Switch IV"},"error":"Failed to configure (Bind 0x30fb10fffedd2259/1 genOnOff from '0x00124b0026b7a968/1' failed (AREQ - ZDO - bindRsp after 10000ms))","status":"error","transaction":"uke6w-6"}'

**Comment by Ian-42erghwWhbvw** [comment]
Follow up. Weird one here. I went through #22458 more carefully and did the one thing from there that i hadn't tried and that was physically removing and replacing the battery from the Styrbar switch as part of following https://github.com/Koenkk/zigbee2mqtt/issues/22458#issuecomment-2097032528 . Up popped "configuring" in the web/GUI front end and the switch jumped into life - but not just that switch, the others now regained their left/right buttons too and I hadn't done anything to them (indeed I was keeping well away from changing them in the hope of at least preserving their 1/2 functioning state). 

So, I'm leaving this here in case (1) it helps someone else, (2) it offers the authors a clue as to what the flip was going on inside Z2M. Otherwise I'd call this closed.
