### ISSUE TITLE
SONOFF Zigbee Gateway ZBDongle-E 3.0 Problem

### ISSUE THREAD

**Issue by RichardIstSauer** [Koenkk/zigbee2mqtt#22677]
### What happened?

I started Zigbee2MQTT Home Assistant Add-on and got first error message after this I updated the firmware from the coordinator with this site: https://darkxst.github.io/silabs-firmware-builder/. After this, I got the second error message.

### Zigbee2MQTT version

1.37.1-1

### Adapter firmware version

Zigbee (EZSP) 7.3.1.0 build 176

### Adapter

SONOFF Zigbee Gateway ZBDongle-E 3.0 EFR32MG21 

### Setup

Home Assistant OS

### Debug log

[2024-05-17 17:12:36] error: 	z2m: Error while starting zigbee-herdsman
[2024-05-17 17:12:36] error: 	z2m: Failed to start zigbee
[2024-05-17 17:12:36] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-05-17 17:12:36] error: 	z2m: Exiting...
[2024-05-17 17:12:36] error: 	z2m: Error: NCP EZSP protocol version of 8 does not match Host version 13
    at EmberAdapter.emberVersion (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1633:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:784:9)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:2642:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:124:29)
    at Zigbee.start (/app/lib/zigbee.ts:62:27)
    at Controller.start (/app/lib/controller.ts:109:27)
    at start (/app/index.js:107:5)

### **After update:**
[2024-05-17 17:27:45] error: 	z2m: Error while starting zigbee-herdsman
[2024-05-17 17:27:45] error: 	z2m: Failed to start zigbee
[2024-05-17 17:27:45] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-05-17 17:27:45] error: 	z2m: Exiting...
[2024-05-17 17:27:45] error: 	z2m: Error: NCP EZSP protocol version of 12 does not match Host version 13
    at EmberAdapter.emberVersion (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1633:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:784:9)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:2642:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:124:29)
    at Zigbee.start (/app/lib/zigbee.ts:62:27)
    at Controller.start (/app/lib/controller.ts:109:27)
    at start (/app/index.js:107:5)

**Comment by wastez** [comment]
You need to install a version with 7.4. 
7.3.2 is still ezsp protocol version 12. 

Here is the firmware:
https://github.com/darkxst/silabs-firmware-builder/blob/main/firmware_builds/zbdonglee/ncp-uart-hw-v7.4.2.0-zbdonglee-115200.gbl
