### ISSUE TITLE
[New device support]: Aqara ceiling light H1

### ISSUE THREAD

**Issue by stylisk** [Koenkk/zigbee2mqtt#22712]
### Link

https://www.aqara.cn/Ceiling-Light-H1_overview

### Database entry

{"id":48,"type":"Router","ieeeAddr":"0x54ef441000b24a61","nwkAddr":5813,"manufId":4447,"manufName":"Aqara","powerSource":"DC Source","modelId":"lumi.light.acn033","epList":[1,21],"endpoints":{"1":{"profId":260,"epId":1,"devId":258,"inClusterList":[5,4,3,0,768,8,6,2820,1794,64704],"outClusterList":[25,10],"clusters":{"genBasic":{"attributes":{"61440":2,"modelId":"lumi.light.acn033","appVersion":22,"zclVersion":3}},"genOnOff":{"attributes":{"245":1488250,"onOff":1}},"manuSpecificLumi":{"attributes":{"22":"F3F67CF36ADB84ED6C6DB6B6C495D3CAAB67E13BB1AE5DDFA6BA625D93FA4C75","223":{"type":"Buffer","data":[22,33,0,0,23,33,0,0,12,33,18,0,24,33,91,19]},"229":{"type":"Buffer","data":[16,2,14,65,67,37,83,61,71,37,138,158,77,37,74,225,135,37,32,192,141,37,43,227,142,37,129,162,157,37,77,189,159,37,112,99,175,37,103,157,180,37,136,51,211,37,108,94,216,37,42,68,217,37,53,24,237,37,102]},"247":{"type":"Buffer","data":[3,40,66,5,33,94,0,8,33,22,1,9,33,2,16,10,33,227,142,11,32,0,12,32,10,21,33,2,0,22,33,2,0,160,32,1,154,32,0,100,32,1,101,32,234,102,33,166,0,106,35,140,10,100,25,105,32,0,113,32,1]}}},"genLevelCtrl":{"attributes":{"245":1488159,"currentLevel":234}},"lightingColorCtrl":{"attributes":{"245":1488227,"colorTemperature":166,"colorMode":2,"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":370}},"haElectricalMeasurement":{"attributes":{"acPowerDivisor":10,"acPowerMultiplier":1}}},"binds":[],"configuredReportings":[],"meta":{}},"21":{"profId":260,"epId":21,"devId":0,"inClusterList":[12],"outClusterList":[],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":22,"stackVersion":27,"hwVersion":1,"dateCode":"20231023","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1716214521534}

### Comments

[2024-05-14 01:00:05] error: 	z2m: Failed to configure '안방 천장 조명', attempt 1 (Error: ZCL command 0x54ef441000b24a61/1 haElectricalMeasurement.read(["acCurrentDivisor","acCurrentMultiplier"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:315:28)
    at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:770:26)
    at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:401:29)
    at result.configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:1469:33)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:172:21)
    at Configure.configure (/app/lib/extension/configure.ts:121:13)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

[2024-05-20 23:35:22] debug: 	z2m: No converter available for 'lumi.light.acn033' with cluster 'manuSpecificLumi' and type 'attributeReport' and data '{"247":{"data":[3,40,67,5,33,94,0,8,33,22,1,9,33,2,16,10,33,0,0,11,32,0,12,32,10,21,33,2,0,22,33,2,0,160,32,1,154,32,0,100,32,1,101,32,234,102,33,166,0,106,35,140,10,100,25,105,32,0,113,32,1],"type":"Buffer"}}'

[2024-05-21 00:09:16] debug: 	z2m: No converter available for 'lumi.light.acn033' with cluster 'manuSpecificLumi' and type 'attributeReport' and data '{"247":{"data":[3,40,65,5,33,94,0,8,33,22,1,9,33,2,16,10,33,0,0,11,32,0,12,32,10,21,33,2,0,22,33,2,0,160,32,1,154,32,0,100,32,1,101,32,234,102,33,166,0,106,35,140,10,100,25,105,32,0,113,32,1],"type":"Buffer"}}'

[2024-05-21 00:16:38] debug: 	z2m: No converter available for 'lumi.light.acn033' with cluster 'manuSpecificLumi' and type 'attributeReport' and data '{"247":{"data":[3,40,63,5,33,94,0,8,33,22,1,9,33,2,16,10,33,0,0,11,32,0,12,32,10,21,33,2,0,22,33,2,0,160,32,1,154,32,0,100,32,1,101,32,69,102,33,184,0,106,35,140,10,100,25,105,32,0,113,32,1],"type":"Buffer"}}'

### External definition

```shell
const {deviceEndpoints, identify, light, electricityMeter} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['lumi.light.acn033'],
    model: 'lumi.light.acn033',
    vendor: 'Aqara',
    description: 'Automatically generated definition',
    extend: [deviceEndpoints({"endpoints":{"1":1,"21":21}}), identify(), light({"colorTemp":{"range":[153,370]}}), electricityMeter()],
    meta: {"multiEndpoint":true},
};

module.exports = definition;
```

**Comment by andrazek** [comment]
I'm looking for this one as well.

**Comment by ileodo** [comment]
@stylisk @andrazek  I'm considering getting a H1 as well, wondering do you have more details on this? does it work well with z2m?
