### ISSUE TITLE
Occasuib UnhandledPromiseRejectionWarning from waitress.js

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee2mqtt#2272]
# Bug Report
## What happened
```
(node:88401) UnhandledPromiseRejectionWarning: Error: Timeout - 36534 - 11 - 21 - 1 after 10000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
(node:88401) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:88401) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I get this error every now and then after having paired 2 new E1743 remotes. Both got unbound from group with ID 99 and bound to 2 other groups, each group has 1 bulb in it, one has an IKEA bulb the other a Hue bulb.

This may be related to the 'emulated' reporting, but I also got it at least once after removing a group.

## What did you expect to happen
n/a

## How to reproduce it (minimal and precise)
Not sure, I thought it might be the emulated reporting stuff for the hue bulb but I drop and raised the brightness for it a few times without triggering it.

## Debug Info
zigbee2mqtt version: 1.6.0-dev @ 2fb4e20
CC253X firmware version: 20190425

**Comment by Koenkk** [comment]
I've added some extra logging in the dev branch, could you provide some more context of the log? It's hard to determine form just this snippet.
