### ISSUE TITLE
panId collision detected over usbip

### ISSUE THREAD

**Issue by mateuszdrab** [Koenkk/zigbee2mqtt#22778]
### What happened?

I migrated my HASS VM from ESXi to Hyper-V today through a Veeam restore and this resulted moving the CC2531 from being passed through using ESXi's native USB device passthrough to a combination of [usbipd](https://github.com/dorssel/usbipd-win) on the host and [this add-on ](https://github.com/AverageJoe89/hassio-usbip-mounter) on HASSIO side.

Since this change, Z2M won't start with message `z2m: Error: network commissioning failed - panId collision detected (expected=6754, actual=6755)`

There have been no configuration changes made, it was essentially a lift and shift migration which I've done a couple of times in different environments during the last few weeks.

When I change the config to the suggested `6755`, it starts but the devices don't seem to work as `pan_id` changing requires repairing.

Since the devices are 1k miles away, I wanted to avoid having to have them repaired.

I know the dongle firmware is very old, but I don't know if it's a good idea to start changing things as this might mess things up even more.

### What did you expect to happen?

Z2M to start as usual. 

A couple of weeks ago before today'smigration, I moved the same CC2531 stick from a Raspberry Pi (with Z2M as a service) into the ESXi host and migrated the config into the addon which worked perfectly fine. 

I've done things like this many times before.

### How to reproduce it (minimal and precise)

Move an existing dongle to be attached to `usbip` from whatever method was used before 

### Zigbee2MQTT version

1.37.1

### Adapter firmware version

20181024

### Adapter

TI CC2531

### Setup

HASS add-on, x86-64, Hyper-V. usbipd

### Debug log

Startup log before migration:

```
  |   | [19:26:33] INFO: Socat not enabled |  
  |   | [19:26:33] INFO: Starting Zigbee2MQTT... |  
  |   | [2024-05-24 19:26:40] info: 	z2m: Logging to console |  
  |   | [2024-05-24 19:26:40] info: 	z2m: Starting Zigbee2MQTT version 1.37.1 (commit #unknown) |  
  |   | [2024-05-24 19:26:40] info: 	z2m: Starting zigbee-herdsman (0.46.6) |  
  |   | [2024-05-24 19:26:42] info: 	zh:zstack:znp: Opening SerialPort with {"path":"/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001936DD61-if00","baudRate":115200,"rtscts":false,"autoOpen":false} |  
  |   | [2024-05-24 19:26:42] info: 	zh:zstack:znp: Serialport opened |  
  |   | [2024-05-24 19:26:42] info: 	zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload |  
  |   | [2024-05-24 19:26:43] info: 	zh:zstack:znp: Skip bootloader for CC2652/CC1352 |  
  |   | [2024-05-24 19:26:44] info: 	z2m: zigbee-herdsman started (resumed) |  
  |   | [2024-05-24 19:26:44] info: 	z2m: Coordinator firmware version: '{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20181024,"transportrev":2},"type":"zStack12"}' |  
  |   | [2024-05-24 19:26:44] info: 	z2m: Currently 7 devices are joined:
```

Log post migration:

```
[2024-05-26 01:25:01] info: 	z2m: Logging to console |  
-- | --
  |   | [2024-05-26 01:25:01] info: 	z2m: Starting Zigbee2MQTT version 1.37.1 (commit #unknown) |  
  |   | [2024-05-26 01:25:01] info: 	z2m: Starting zigbee-herdsman (0.46.6) |  
  |   | [2024-05-26 01:25:02] info: 	zh:zstack:znp: Opening SerialPort with {"path":"/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001936DD61-if00","baudRate":115200,"rtscts":false,"autoOpen":false} |  
  |   | [2024-05-26 01:25:02] info: 	zh:zstack:znp: Serialport opened |  
  |   | [2024-05-26 01:25:11] error: 	z2m: Error while starting zigbee-herdsman |  
  |   | [2024-05-26 01:25:11] error: 	z2m: Failed to start zigbee |  
  |   | [2024-05-26 01:25:11] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions |  
  |   | [2024-05-26 01:25:11] error: 	z2m: Exiting... |  
  |   | [2024-05-26 01:25:11] error: 	z2m: Error: network commissioning failed - panId collision detected (expected=6754, actual=6755) |  
  |   | at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:364:19) |  
  |   | at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:71:17) |  
  |   | at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:124:29) |  
  |   | at Zigbee.start (/app/lib/zigbee.ts:62:27) |  
  |   | at Controller.start (/app/lib/controller.ts:109:27) |  
  |   | at start (/app/index.js:107:5)
```

**Comment by mateuszdrab** [comment]
Replaced the dongle with the Sonoff Zigbee stick and it works fine. 
During troubleshooting I was also able to prove that using socat on Windows in conjunction with the socat in the addon also resulted in the same issue.
