### ISSUE TITLE
 problem with report in the dev branch

### ISSUE THREAD

**Issue by zhapwey** [Koenkk/zigbee2mqtt#2284]
## What happened
when an ikea bulb loses tension and recovers it does not show its change in value.

## What did you expect to happen
as does the master branch that when a team has tension again update the status.

## How to reproduce it (minimal and precise)
synchronize bulb, remove tension and return it

## Debug Info
zigbee2mqtt:error 2019-11-06T09:08:36: Failed to setup reporting for '0x086bd7fffe04f5f7' - Error: AREQ - ZDO - bindRsp after 10000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

zigbee2mqtt version:
1.6 dev
CC253X firmware version:
20190608

**Comment by carldebilly** [comment]
I think this PR will solve your problem: https://github.com/Koenkk/zigbee-herdsman/pull/115

I had the exact same problem.
