### ISSUE TITLE
Docker container fails to start after pulling the latest version 

### ISSUE THREAD

**Issue by roobbb** [Koenkk/zigbee2mqtt#22891]
### What happened?

The container was upgraded to latest as it did several times in the past without any problem.
The log shows such messages:
```
[2024-06-02 11:48:56] info: 	z2m: Logging to console, file (filename: log.log)
[2024-06-02 11:48:56] info: 	z2m: Starting Zigbee2MQTT version 1.38.0 (commit #fe048e6)
[2024-06-02 11:48:56] info: 	z2m: Starting zigbee-herdsman (0.49.2)
[2024-06-02 11:48:58] info: 	zh:zstack:znp: Opening TCP socket with 192.168.222.202:6638
[2024-06-02 11:48:58] info: 	zh:zstack:znp: Socket connected
[2024-06-02 11:48:58] info: 	zh:zstack:znp: Socket ready
[2024-06-02 11:48:58] info: 	zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload
[2024-06-02 11:48:59] info: 	zh:zstack:znp: Skip bootloader for CC2652/CC1352
[2024-06-02 11:48:59] error: 	zh:adapter:zstack:manager: Configuration is not consistent with adapter state/backup!
[2024-06-02 11:48:59] error: 	zh:adapter:zstack:manager: - PAN ID: configured=6754, adapter=6754
[2024-06-02 11:48:59] error: 	zh:adapter:zstack:manager: - Extended PAN ID: configured=00124b00237dfb33, adapter=00124b00237dfb33
[2024-06-02 11:48:59] error: 	zh:adapter:zstack:manager: - Network Key: configured=27afd6324eade26a1c2cc86f60b5b059, adapter=27afd6324eade26a1c2cc86f60b5b059
[2024-06-02 11:48:59] error: 	zh:adapter:zstack:manager: - Channel List: configured=11, adapter=11
[2024-06-02 11:48:59] error: 	zh:adapter:zstack:manager: Please update configuration to prevent further issues.
[2024-06-02 11:48:59] error: 	zh:adapter:zstack:manager: If you wish to re-commission your network, please remove coordinator backup at /app/data/coordinator_backup.json.
[2024-06-02 11:48:59] error: 	zh:adapter:zstack:manager: Re-commissioning your network will require re-pairing of all devices!
[2024-06-02 11:48:59] error: 	z2m: Error while starting zigbee-herdsman
[2024-06-02 11:48:59] error: 	z2m: Failed to start zigbee
[2024-06-02 11:48:59] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-06-02 11:48:59] error: 	z2m: Exiting...
[2024-06-02 11:49:00] error: 	z2m: Error: startup failed - configuration-adapter mismatch - see logs above for more information
    at ZnpAdapterManager.determineStrategy (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:223:35)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:57:26)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:127:29)
    at Zigbee.start (/app/lib/zigbee.ts:62:27)
    at Controller.start (/app/lib/controller.ts:109:27)
    at start (/app/index.js:107:5)
Using '/app/data' as data directory
[2024-06-02 11:49:15] info: 	z2m: Logging to console, file (filename: log.log)
[2024-06-02 11:49:15] error: 	z2m: Failed to call 'OnEvent' 'stop' (TypeError: Cannot read properties of undefined (reading 'getDevices')
    at Zigbee.devices (/app/lib/zigbee.ts:329:30)
    at OnEvent.stop (/app/lib/extension/onEvent.ts:37:42)
    at Controller.callExtensions (/app/lib/controller.ts:337:42)
    at Controller.stop (/app/lib/controller.ts:209:20)
    at stop (/app/index.js:111:22)
    at process.handleQuit (/app/index.js:117:15)
    at process.emit (node:events:517:28)
    at process.emit (/app/node_modules/source-map-support/source-map-support.js:516:21))
TypeError: Cannot read properties of undefined (reading 'getGroupByID')
    at Zigbee.resolveGroup (/app/lib/zigbee.ts:262:37)
    at Zigbee.resolveEntity (/app/lib/zigbee.ts:281:36)
    at /app/lib/state.ts:36:66
    at Array.filter (<anonymous>)
    at State.stop (/app/lib/state.ts:36:14)
    at Controller.stop (/app/lib/controller.ts:213:20)
    at stop (/app/index.js:111:5)
    at process.handleQuit (/app/index.js:117:9)

```
---
It tried to go back to these versions:
```
zigbee2mqtt/zigbee2mqtt-armv7:1.37.1-1
zigbee2mqtt/zigbee2mqtt-armv7:1.37.0-1
zigbee2mqtt/zigbee2mqtt-armv7:1.36.1-1
```

But there are  always such log-messages
```
[13:21:00] INFO: Preparing to start...
[13:21:01] FATAL: 
[13:21:01] FATAL: A required add-on configuration option is missing!
[13:21:01] FATAL: 
[13:21:01] FATAL: Please set a value for the 'data_path' option.
[13:21:01] FATAL: 
[13:21:01] FATAL: If unsure, check the add-on manual for more information.
[13:21:01] FATAL: 
```

### What did you expect to happen?

It should start the new container without any problems.

### Zigbee2MQTT version

1.38.0 (commit #fe048e6)

### Adapter firmware version

0.6.0

### Adapter

ZigStar LAN Gateway

### Setup

inside docker-container (koenkk/zigbee2mqtt) on Raspi3 running debian bullseye

### Debug log

```
[2024-06-02 12:11:35] info: 	z2m: Logging to console, file (filename: log.log)
[2024-06-02 12:11:35] debug: 	z2m: Loaded state from file /app/data/state.json
[2024-06-02 12:11:35] info: 	z2m: Starting Zigbee2MQTT version 1.38.0 (commit #fe048e6)
[2024-06-02 12:11:36] info: 	z2m: Starting zigbee-herdsman (0.49.2)
[2024-06-02 12:11:36] debug: 	z2m: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"tcp://192.168.222.202:6638"}}'
[2024-06-02 12:11:37] debug: 	zh:controller: Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[39,175,214,50,78,173,226,106,28,44,200,111,96,181,176,89],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"tcp://192.168.222.202:6638"},"databasePath":"/app/data/database.db","databaseBackupPath":"/app/data/database.db.backup","backupPath":"/app/data/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
[2024-06-02 12:11:37] info: 	zh:zstack:znp: Opening TCP socket with 192.168.222.202:6638
[2024-06-02 12:11:37] info: 	zh:zstack:znp: Socket connected
[2024-06-02 12:11:37] info: 	zh:zstack:znp: Socket ready
[2024-06-02 12:11:37] info: 	zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload
[2024-06-02 12:11:37] debug: 	zh:zstack:unpi:writer: --> buffer [239]
[2024-06-02 12:11:38] info: 	zh:zstack:znp: Skip bootloader for CC2652/CC1352
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SREQ: --> SYS - ping - {"capabilities":1}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:writer: --> frame [254,0,33,1,32]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,1,89,6,61]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,1,89,6,61]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 1 - [89,6] - 61
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SRSP: <-- SYS - ping - {"capabilities":1625}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SREQ: --> SYS - version - {}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:writer: --> frame [254,0,33,2,35]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [254,10,97,2,2,1,2,7,1]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,10,97,2,2,1,2,7,1]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [42,98,52,1,0,19]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,10,97,2,2,1,2,7,1,42,98,52,1,0,19]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --> parsed 10 - 3 - 1 - 2 - [2,1,2,7,1,42,98,52,1,0] - 19
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SRSP: <-- SYS - version - {"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20210218}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-06-02 12:11:38] debug: 	zh:zstack: Adapter concurrent: 16
[2024-06-02 12:11:38] debug: 	zh:zstack: Detected znp version 'zStack3x0' ({"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20210218})
[2024-06-02 12:11:38] debug: 	zh:adapter:zstack:manager: beginning znp startup
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SREQ: --> SYS - getExtAddr - {}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:writer: --> frame [254,0,33,4,37]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [254,8,97,4,51,251,125,35,0]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,8,97,4,51,251,125,35,0]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [75,18,0,162]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,8,97,4,51,251,125,35,0,75,18,0,162]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --> parsed 8 - 3 - 1 - 4 - [51,251,125,35,0,75,18,0] - 162
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SRSP: <-- SYS - getExtAddr - {"extaddress":"0x00124b00237dfb33"}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvLength - {"id":130}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:writer: --> frame [254,2,33,19,130,0,178]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,19]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,19]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [24,0,104]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,19,24,0,104]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 19 - [24,0] - 104
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvLength - {"length":24}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvReadExt - {"id":130,"offset":0}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:writer: --> frame [254,4,33,28,130,0,0,0,187]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [254,26,97,28,0,24,0,39,175,214,50,78,173]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,26,97,28,0,24,0,39,175,214,50,78,173]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [226,106,28,44,200,111,96,181,176,89,0,0,0,255,190,255,0,109]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,26,97,28,0,24,0,39,175,214,50,78,173,226,106,28,44,200,111,96,181,176,89,0,0,0,255,190,255,0,109]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --> parsed 26 - 3 - 1 - 28 - [0,24,0,39,175,214,50,78,173,226,106,28,44,200,111,96,181,176,89,0,0,0,255,190,255,0] - 109
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvReadExt - {"status":0,"len":24,"value":{"type":"Buffer","data":[0,39,175,214,50,78,173,226,106,28,44,200,111,96,181,176,89,0,0,0,255,190,255,0]}}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-06-02 12:11:38] debug: 	zh:adapter:zstack:manager: determining znp startup strategy
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvLength - {"id":96}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:writer: --> frame [254,2,33,19,96,0,80]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,19,1,0,113]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,19,1,0,113]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 19 - [1,0] - 113
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvLength - {"length":1}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvReadExt - {"id":96,"offset":0}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:writer: --> frame [254,4,33,28,96,0,0,0,89]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [254,3]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,3]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [97,28,0,1,85,42]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,3,97,28,0,1,85,42]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --> parsed 3 - 3 - 1 - 28 - [0,1,85] - 42
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvReadExt - {"status":0,"len":1,"value":{"type":"Buffer","data":[85]}}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvLength - {"id":33}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:writer: --> frame [254,2,33,19,33,0,17]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,19,116,0,4]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,19,116,0,4]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 19 - [116,0] - 4
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvLength - {"length":116}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvReadExt - {"id":33,"offset":0}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:writer: --> frame [254,4,33,28,33,0,0,0,24]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [254]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [118,97,28,0,116,67,5,2,51,15,51,0,30,0,0,0,1,5,1,143,0,7,0,2,13,30,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,98,26,8,0,0,8,0,0,15,15,4,0,1,0,0,0,1,0,0,0,0,51,251,125,35,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,5,0,1,100,10,1,0,0,0,0,0,0,0,107]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,118,97,28,0,116,67,5,2,51,15,51,0,30,0,0,0,1,5,1,143,0,7,0,2,13,30,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,98,26,8,0,0,8,0,0,15,15,4,0,1,0,0,0,1,0,0,0,0,51,251,125,35,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,5,0,1,100,10,1,0,0,0,0,0,0,0,107]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --> parsed 118 - 3 - 1 - 28 - [0,116,67,5,2,51,15,51,0,30,0,0,0,1,5,1,143,0,7,0,2,13,30,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,98,26,8,0,0,8,0,0,15,15,4,0,1,0,0,0,1,0,0,0,0,51,251,125,35,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,5,0,1,100,10,1,0,0,0,0,0,0,0] - 107
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvReadExt - {"status":0,"len":116,"value":{"type":"Buffer","data":[67,5,2,51,15,51,0,30,0,0,0,1,5,1,143,0,7,0,2,13,30,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,98,26,8,0,0,8,0,0,15,15,4,0,1,0,0,0,1,0,0,0,0,51,251,125,35,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,5,0,1,100,10,1,0,0,0,0,0,0,0]}}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvLength - {"id":98}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:writer: --> frame [254,2,33,19,98,0,82]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,19,16,0,96]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,19,16,0,96]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 19 - [16,0] - 96
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvLength - {"length":16}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvReadExt - {"id":98,"offset":0}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:writer: --> frame [254,4,33,28,98,0,0,0,91]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [254,18]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,18]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [97,28,0,16,227,129,85,174,221,163,251,38,50,229,14,225,73,48,101,162,195]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,18,97,28,0,16,227,129,85,174,221,163,251,38,50,229,14,225,73,48,101,162,195]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --> parsed 18 - 3 - 1 - 28 - [0,16,227,129,85,174,221,163,251,38,50,229,14,225,73,48,101,162] - 195
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvReadExt - {"status":0,"len":16,"value":{"type":"Buffer","data":[227,129,85,174,221,163,251,38,50,229,14,225,73,48,101,162]}}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvLength - {"id":58}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:writer: --> frame [254,2,33,19,58,0,10]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,19,17,0,97]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,19,17,0,97]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 19 - [17,0] - 97
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvLength - {"length":17}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvReadExt - {"id":58,"offset":0}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:writer: --> frame [254,4,33,28,58,0,0,0,3]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [254,19,97]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,19,97]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [28,0,17,0,39,175,214,50,78,173,226,106,28,44,200,111,96,181,176,89,211]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,19,97,28,0,17,0,39,175,214,50,78,173,226,106,28,44,200,111,96,181,176,89,211]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --> parsed 19 - 3 - 1 - 28 - [0,17,0,39,175,214,50,78,173,226,106,28,44,200,111,96,181,176,89] - 211
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvReadExt - {"status":0,"len":17,"value":{"type":"Buffer","data":[0,39,175,214,50,78,173,226,106,28,44,200,111,96,181,176,89]}}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvLength - {"id":59}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:writer: --> frame [254,2,33,19,59,0,11]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,19,17,0,97]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,19,17,0,97]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 19 - [17,0] - 97
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvLength - {"length":17}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-06-02 12:11:38] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvReadExt - {"id":59,"offset":0}
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:writer: --> frame [254,4,33,28,59,0,0,0,2]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: <-- [254,19,97,28]
[2024-06-02 12:11:38] debug: 	zh:zstack:unpi:parser: --- parseNext [254,19,97,28]
[2024-06-02 12:11:39] debug: 	zh:zstack:unpi:parser: <-- [0,17,0,39,175,214,50,78,173,226,106,28,44,200,111,96,181,176,89,211]
[2024-06-02 12:11:39] debug: 	zh:zstack:unpi:parser: --- parseNext [254,19,97,28,0,17,0,39,175,214,50,78,173,226,106,28,44,200,111,96,181,176,89,211]
[2024-06-02 12:11:39] debug: 	zh:zstack:unpi:parser: --> parsed 19 - 3 - 1 - 28 - [0,17,0,39,175,214,50,78,173,226,106,28,44,200,111,96,181,176,89] - 211
[2024-06-02 12:11:39] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvReadExt - {"status":0,"len":17,"value":{"type":"Buffer","data":[0,39,175,214,50,78,173,226,106,28,44,200,111,96,181,176,89]}}
[2024-06-02 12:11:39] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-06-02 12:11:39] debug: 	zh:adapter:zstack:manager: (stage-1) adapter is configured
[2024-06-02 12:11:39] debug: 	zh:adapter:zstack:manager: (stage-2) adapter state does not match configuration
[2024-06-02 12:11:39] debug: 	zh:adapter:zstack:manager: (stage-3) got adapter backup
[2024-06-02 12:11:39] debug: 	zh:adapter:zstack:manager: (stage-4) adapter state matches backup
[2024-06-02 12:11:39] error: 	zh:adapter:zstack:manager: Configuration is not consistent with adapter state/backup!
[2024-06-02 12:11:39] error: 	zh:adapter:zstack:manager: - PAN ID: configured=6754, adapter=6754
[2024-06-02 12:11:39] error: 	zh:adapter:zstack:manager: - Extended PAN ID: configured=00124b00237dfb33, adapter=00124b00237dfb33
[2024-06-02 12:11:39] error: 	zh:adapter:zstack:manager: - Network Key: configured=27afd6324eade26a1c2cc86f60b5b059, adapter=27afd6324eade26a1c2cc86f60b5b059
[2024-06-02 12:11:39] error: 	zh:adapter:zstack:manager: - Channel List: configured=11, adapter=11
[2024-06-02 12:11:39] error: 	zh:adapter:zstack:manager: Please update configuration to prevent further issues.
[2024-06-02 12:11:39] error: 	zh:adapter:zstack:manager: If you wish to re-commission your network, please remove coordinator backup at /app/data/coordinator_backup.json.
[2024-06-02 12:11:39] error: 	zh:adapter:zstack:manager: Re-commissioning your network will require re-pairing of all devices!
[2024-06-02 12:11:39] error: 	z2m: Error while starting zigbee-herdsman
[2024-06-02 12:11:39] error: 	z2m: Failed to start zigbee
[2024-06-02 12:11:39] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-06-02 12:11:39] error: 	z2m: Exiting...
[2024-06-02 12:11:39] error: 	z2m: Error: startup failed - configuration-adapter mismatch - see logs above for more information
    at ZnpAdapterManager.determineStrategy (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:223:35)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:57:26)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:127:29)
    at Zigbee.start (/app/lib/zigbee.ts:62:27)
    at Controller.start (/app/lib/controller.ts:109:27)
    at start (/app/index.js:107:5)
```

PS: the link for the debug log https://www.zigbee2mqtt.io/guide/usage/debug.html as mentioned in this template here results in a 404-message

**Comment by roobbb** [comment]
Hello.

After trying a lots of things and getting some sorts of error messages, I just renamed the file "coordinator_backup.json" to "coordinator_backup.json_" and tried to restart the container (koenkk/zigbee2mqtt = latest). But without any luck. 
The logs said it gets no connection to MQTT-server. But when I tried to ping that server from inside the zigbee2mqtt-container, it was reachable.

```
[2024-06-02 14:34:24] info: 	z2m: Logging to console, file (filename: log.log)
[2024-06-02 14:34:24] info: 	z2m: Starting Zigbee2MQTT version 1.38.0 (commit #fe048e6)
[2024-06-02 14:34:24] info: 	z2m: Starting zigbee-herdsman (0.49.2)
[2024-06-02 14:34:26] info: 	zh:zstack:znp: Opening TCP socket with 192.168.222.202:6638
[2024-06-02 14:34:26] info: 	zh:zstack:znp: Socket connected
[2024-06-02 14:34:26] info: 	zh:zstack:znp: Socket ready
[2024-06-02 14:34:26] info: 	zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload
[2024-06-02 14:34:27] info: 	zh:zstack:znp: Skip bootloader for CC2652/CC1352
[2024-06-02 14:35:33] error: 	z2m: Error while starting zigbee-herdsman
[2024-06-02 14:35:33] error: 	z2m: Failed to start zigbee
[2024-06-02 14:35:33] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-06-02 14:35:33] error: 	z2m: Exiting...
[2024-06-02 14:35:34] error: 	z2m: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:341:23)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:86:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:127:29)
    at Zigbee.start (/app/lib/zigbee.ts:62:27)
    at Controller.start (/app/lib/controller.ts:109:27)
    at start (/app/index.js:107:5)
```

```
[2024-06-02 14:35:50] info: 	z2m: Logging to console, file (filename: log.log)
[2024-06-02 14:35:50] info: 	z2m: Starting Zigbee2MQTT version 1.38.0 (commit #fe048e6)
[2024-06-02 14:35:50] info: 	z2m: Starting zigbee-herdsman (0.49.2)
[2024-06-02 14:35:51] info: 	zh:zstack:znp: Opening TCP socket with 192.168.222.202:6638
[2024-06-02 14:35:51] info: 	zh:zstack:znp: Socket connected
[2024-06-02 14:35:51] info: 	zh:zstack:znp: Socket ready
[2024-06-02 14:35:51] info: 	zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload
[2024-06-02 14:35:52] info: 	zh:zstack:znp: Skip bootloader for CC2652/CC1352
[2024-06-02 14:36:29] error: 	z2m:mqtt: Not connected to MQTT server!
[2024-06-02 14:36:29] error: 	z2m:mqtt: Cannot send message: topic: 'zigbee2mqtt/bridge/state', payload: 'offline
[2024-06-02 14:36:29] info: 	z2m:mqtt: Disconnecting from MQTT server
[2024-06-02 14:36:29] info: 	z2m: Stopping zigbee-herdsman...
[2024-06-02 14:36:29] info: 	z2m: Stopped zigbee-herdsman
[2024-06-02 14:36:29] info: 	z2m: Stopped Zigbee2MQTT
```

After that I renamed the file back to "coordinator_backup.json" and restarted the container again: and then it started fine and is working now 😀

I have no clue what was wrong. But maybe this could help someone. And hopefully this problem doesn't come back after the next container upgrade.

Kind regards
roobbb
