### ISSUE TITLE
Z2M crashes after update firmware version from ezsp to ember

### ISSUE THREAD

**Issue by Holger237237** [Koenkk/zigbee2mqtt#22991]
### What happened?

Z2B is no longer able to start after update firmware version from ezsp to ember

### What did you expect to happen?

I expected that Z2M starts without errors.

### How to reproduce it (minimal and precise)

- Stop Z2M
- Update Firmware Adapter from ezsp to ember 7.4.1.0 
- change Z2M YAML: 
  serial:
  port: /dev/ttyACM0
  adapter: ember
-start Z2M 

### Zigbee2MQTT version

1.38.0

### Adapter firmware version

ncp-uart-hw-v7.4.1.0-zbdonglee-115200

### Adapter

SONOFF ZBDongle-E 

### Setup

Synology DSM 7.0

### Debug log

[2024-06-09 12:14:04] error: 	z2m: Error while starting zigbee-herdsman
[2024-06-09 12:14:04] error: 	z2m: Failed to start zigbee
[2024-06-09 12:14:04] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-06-09 12:14:04] error: 	z2m: Exiting...
[2024-06-09 12:14:04] error: 	z2m: Error: [BACKUP] Current backup file is from an unsupported EZSP version (min: 12).
    at EmberAdapter.getStoredBackup (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1363:23)
    at EmberAdapter.initTrustCenter (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1156:37)
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:865:19)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:2682:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:127:29)
    at Zigbee.start (/app/lib/zigbee.ts:62:27)
    at Controller.start (/app/lib/controller.ts:110:27)
    at start (/app/index.js:107:5)

**Comment by Nerivec** [comment]
You need to move/rename the old backup file you have (`coordinator_backup.json`) in your config folder. After that, it should start fine.
See [docs](https://www.zigbee2mqtt.io/guide/adapters/emberznet.html#logging-specific-to-this-stack) for details on other ember-specific messages.
