### ISSUE TITLE
Unable to get LQI until after zigbee2mqtt restart

### ISSUE THREAD

**Issue by nanobra1n** [Koenkk/zigbee2mqtt#2301]
# Bug Report
## What happened
Sometimes (but not rarely) when I try to get a refreshed network map using https://github.com/azuwis/zigbee2mqtt-networkmap the displayed network breaks apart and won't recover

The log shows
```
zigbee2mqtt:error 2019-11-09T17:25:40: Failed to execute LQI for 'LR Right'
2019-11-09T17:25:40.897Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - mgmtLqiReq - {"dstaddr":29741,"startindex":0}
2019-11-09T17:25:40.900Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,37,49,45,116,0,78]
(node:58) UnhandledPromiseRejectionWarning: Error: SRSP - ZDO - mgmtLqiReq after 6000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:58) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
```
for all devices. The only way to recover is to restart zigbee2mqtt.
  
## What did you expect to happen
Fail more gracefully? 
## Debug Info
zigbee2mqtt version: z2m-edge 1.6.0 36c7a27e6c632e0450db18279fc46a1d01365579
CC253X firmware version: 20190608

**Comment by Koenkk** [comment]
The stick crashes because of the network scan, you might want to try the source routing firmware as it improves stability: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing
