### ISSUE TITLE
CC2531 not detected after RPi4 firmware update Libreeelec Docker

### ISSUE THREAD

**Issue by Morphy99** [Koenkk/zigbee2mqtt#2302]
# Bug Report
## What happened
After updating Libreelec to 9.1.502 and updating the RPi4 firmware the CC2531 is not being detected by the docker container.

## What did you expect to happen
Update as normal...
## How to reproduce it (minimal and precise)
Updated LE from 9.1.501 to 9.1.502
Updated RPi4 firmware to latest.
Updated Docker addon to latest

## Debug Info
zigbee2mqtt version: latest stable
CC253X firmware version: latest

log:

`  zigbee2mqtt:info 11/9/2019, 5:49:25 PM Logging to directory: '/app/data/log/2019-11-09.17-49-08'

  zigbee2mqtt:info 11/9/2019, 5:49:27 PM Starting zigbee2mqtt version 1.6.0 (commit #e26ad2a)

  zigbee2mqtt:info 11/9/2019, 5:49:27 PM Starting zigbee-shepherd

  zigbee2mqtt:info 11/9/2019, 5:49:40 PM Error while starting zigbee-shepherd, attempting to fix... (takes 60 seconds) (Error: SRSP - SYS - osalNvRead after 6000ms)

  zigbee2mqtt:info 11/9/2019, 5:50:40 PM Starting zigbee-shepherd

  zigbee2mqtt:error 11/9/2019, 5:50:53 PM Error while starting zigbee-shepherd! (Error: SRSP - SYS - osalNvRead after 6000ms)

  zigbee2mqtt:error 11/9/2019, 5:50:53 PM Press the reset button on the stick (the one closest to the USB) and start again

  zigbee2mqtt:error 11/9/2019, 5:50:53 PM Failed to start

	{"message":"SRSP - SYS - osalNvRead after 6000ms","stack":"Error: SRSP - SYS - osalNvRead after 6000ms\n    at Timeout.object.timer.setTimeout [as _onTimeout] (/app/node_modules/zigbee-herdsman/dist/znp/znp.js:227:24)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)"}

  zigbee2mqtt:error 11/9/2019, 5:50:53 PM Exiting...

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! zigbee2mqtt@1.6.0 start: `node index.js`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the zigbee2mqtt@1.6.0 start script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     /root/.npm/_logs/2019-11-09T17_50_53_728Z-debug.log

Using '/app/data' as data directory`

**Comment by Morphy99** [comment]
Sorry for the lack of detail I was in a rush when posting this bug report. I have rolled back LE now so its working again. When I have more time I will do some updates and try and figure out what broke it and version numbers...

**Comment by Morphy99** [comment]
I've done a fresh LE install (9.2) which has the latest firmware for RPi4 and everything seems ok now. Not sure what went wrong before but seems fixed.
