### ISSUE TITLE
Z2M with Home Assistant Yellow: [Error: NCP EZSP protocol version of 8 does not match Host version 13]

### ISSUE THREAD

**Issue by SavanFlou** [Koenkk/zigbee2mqtt#23053]
### What happened?

Hello,
I am trying to flash my Home Assistant Yellow to use ember.
I used the method described here https://community.home-assistant.io/t/ha-yellow-zigbee2mqtt-ember/727832/5
To be specific, I used the Silicon Labs Flasher extension with the following configuration:
```
device: /dev/ttyAMA1
bootloader_baudrate: "115200"
flow_control: true
verbose: false
firmware_url: >-
    https://github.com/NabuCasa/silabs-firmware/raw/main/EmberZNet/NabuCasa_Yellow_EZSP_v6.10.3.0_PA32_ncp-uart-hw_115200.gbl
```
I also tried with a beta version, the 7.4.0.0 but Z2M does not work in the end. if I try to look at the web interface, I just got a "502 bad getaway. 
 I indicated the log of Z2M when I tried to start it after the flash.

Thank you for your help.

### What did you expect to happen?

Zigbee2MQTT to work

### How to reproduce it (minimal and precise)

Have a Home Assistant Yellow and follow the process I described, I would say.

### Zigbee2MQTT version

 1.38.0-1 

### Adapter firmware version

sorry, cannot find this information

### Adapter

Silicon Labs MGM210P 

### Setup

Add-on on a Home Assistant Rev 1.3

### Debug log

[13:38:45] INFO: Preparing to start...
[13:38:46] INFO: Socat not enabled
[13:38:48] INFO: Starting Zigbee2MQTT...
[2024-06-14 13:38:55] info: 	z2m: Logging to console, file (filename: log.log)
[2024-06-14 13:38:55] info: 	z2m: Starting Zigbee2MQTT version 1.38.0 (commit #unknown)
[2024-06-14 13:38:55] info: 	z2m: Starting zigbee-herdsman (0.49.2)
[2024-06-14 13:38:56] info: 	zh:ember: Using default stack config.
[2024-06-14 13:38:56] info: 	zh:ember: ======== Ember Adapter Starting ========
[2024-06-14 13:38:56] info: 	zh:ember:ezsp: ======== EZSP starting ========
[2024-06-14 13:38:56] info: 	zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-06-14 13:38:56] info: 	zh:ember:uart:ash: RTS/CTS config is off, enabling software flow control.
[2024-06-14 13:38:56] info: 	zh:ember:uart:ash: Serial port opened
[2024-06-14 13:38:56] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-06-14 13:38:57] info: 	zh:ember:uart:ash: ======== ASH connected ========
[2024-06-14 13:38:57] info: 	zh:ember:uart:ash: ======== ASH started ========
[2024-06-14 13:38:57] info: 	zh:ember:ezsp: ======== EZSP started ========
[2024-06-14 13:38:57] error: 	z2m: Error while starting zigbee-herdsman
[2024-06-14 13:38:57] error: 	z2m: Failed to start zigbee
[2024-06-14 13:38:57] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-06-14 13:38:57] error: 	z2m: Exiting...
[2024-06-14 13:38:57] error: 	z2m: Error: NCP EZSP protocol version of 8 does not match Host version 13
    at EmberAdapter.emberVersion (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1674:19)
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:854:9)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:2683:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:127:29)
    at Zigbee.start (/app/lib/zigbee.ts:62:27)
    at Controller.start (/app/lib/controller.ts:109:27)
    at start (/app/index.js:107:5)

**Comment by Koenkk** [comment]
This error means your firmware is outdated, look here for the required firmware: https://www.zigbee2mqtt.io/guide/adapters/emberznet.html
