### ISSUE TITLE
Skyconnect rtscts not working

### ISSUE THREAD

**Issue by paull27** [Koenkk/zigbee2mqtt#23069]
### What happened?

I updated my skyconnect to the recommended firmware (ncp-uart-hw-v7.4.1.0-skyconnect-115200.gbl).
I changed the settings to
```
port: >-
  /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_80e77934b3d8ed11b9026f6162c613ac-if00-port0
adapter: ember
rtscts: true
```
This leads to:
```
[16:41:35] INFO: Starting Zigbee2MQTT...
[2024-06-15 16:41:53] error: 	z2m: Error while starting zigbee-herdsman
[2024-06-15 16:41:53] error: 	z2m: Failed to start zigbee
[2024-06-15 16:41:53] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-06-15 16:41:53] error: 	z2m: Exiting...
[2024-06-15 16:41:54] error: 	z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:850:19)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:2683:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:127:29)
    at Zigbee.start (/app/lib/zigbee.ts:62:27)
    at Controller.start (/app/lib/controller.ts:109:27)
    at start (/app/index.js:107:5)
```

If i change it to `rtscts: false` (without changing the firmware), it produces a warning:
```
[16:43:22] INFO: Starting Zigbee2MQTT...
[2024-06-15 16:43:30] warning: 	zh:ember: [EzspConfigId] Failed to SET "APS_UNICAST_MESSAGE_COUNT" TO "32" with status=ERROR_OUT_OF_MEMORY. Firmware value will be used instead.
```
But it seems to work besides that.

### What did you expect to happen?

Use the recommended firmware with `rtscts: true`

### Zigbee2MQTT version

1.38.0

### Adapter firmware version

7.4.1 [GA]

### Adapter

Skyconnect

### Setup

Add-on Home Assistant OS, RPi 4

**Comment by Koenkk** [comment]
Hw flow control doesnt work well, switch to a sw control one as indicated in the docs: https://www.zigbee2mqtt.io/guide/adapters/emberznet.html
