### ISSUE TITLE
Dongle z-wave.me Z-station don't work

### ISSUE THREAD

**Issue by haade-administrator** [Koenkk/zigbee2mqtt#23117]
### What happened?

z-station does not work with zigbee2mqtt on a fresh HAOSinstall
attached z2m messages with rtscts set to false and then set to true

```
[15:38:51] INFO: Preparing to start...
[15:38:54] INFO: Socat not enabled
[15:39:04] INFO: Starting Zigbee2MQTT...
[2024-06-20 15:39:29] info: z2m: Logging to console, file (filename: log.log)
[2024-06-20 15:39:29] info: z2m: Starting Zigbee2MQTT version 1.38.0 (commit #unknown)
[2024-06-20 15:39:29] info: z2m: Starting zigbee-herdsman (0.49.2)
[2024-06-20 15:39:32] info: zh:ember: Using default stack config.
[2024-06-20 15:39:32] info: zh:ember: ======== Ember Adapter Starting ========
[2024-06-20 15:39:32] info: zh:ember:ezsp: ======== EZSP starting ========
[2024-06-20 15:39:32] info: zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-06-20 15:39:32] info: zh:ember:uart:ash: RTS/CTS config is off, enabling software flow control.
[2024-06-20 15:39:32] info: zh:ember:uart:ash: ASH COUNTERS since last clear:
[2024-06-20 15:39:32] info: zh:ember:uart:ash: Total frames: RX=0, TX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: Cancelled : RX=0, TX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: DATA frames : RX=0, TX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: DATA bytes : RX=0, TX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: Retry frames: RX=0, TX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: ACK frames : RX=0, TX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: NAK frames : RX=0, TX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: nRdy frames : RX=0, TX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: CRC errors : RX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: Comm errors : RX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: Length < minimum: RX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: Length > maximum: RX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: Bad controls : RX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: Bad lengths : RX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: Bad ACK numbers : RX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: Out of buffers : RX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: Retry dupes : RX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: Out of sequence : RX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: ACK timeouts : RX=0
[2024-06-20 15:39:32] info: zh:ember:uart:ash: ======== ASH stopped ========
[2024-06-20 15:39:32] error: zh:ember:uart:ash: Failed to init port with error Error: Error: No such file or directory, cannot open /dev/serial/by-id/usb-Silicon_Labs_CP2105_Dual_USB_to_UART_Bridge_Controller_012B810E-if01-port0
[2024-06-20 15:39:32] error: z2m: Error while starting zigbee-herdsman
[2024-06-20 15:39:32] error: z2m: Failed to start zigbee
[2024-06-20 15:39:32] error: z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-06-20 15:39:32] error: z2m: Exiting...
[2024-06-20 15:39:33] error: z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:850:19)
at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:2683:24)
at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:127:29)
at Zigbee.start (/app/lib/zigbee.ts:62:27)
at Controller.start (/app/lib/controller.ts:109:27)
at start (/app/index.js:107:5)
[15:40:56] INFO: Preparing to start...
[15:40:59] INFO: Socat not enabled
[15:41:10] INFO: Starting Zigbee2MQTT...
[2024-06-20 15:41:33] info: z2m: Logging to console, file (filename: log.log)
[2024-06-20 15:41:33] info: z2m: Starting Zigbee2MQTT version 1.38.0 (commit #unknown)
[2024-06-20 15:41:33] info: z2m: Starting zigbee-herdsman (0.49.2)
[2024-06-20 15:41:35] info: zh:ember: Using default stack config.
[2024-06-20 15:41:35] info: zh:ember: ======== Ember Adapter Starting ========
[2024-06-20 15:41:35] info: zh:ember:ezsp: ======== EZSP starting ========
[2024-06-20 15:41:35] info: zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-06-20 15:41:35] info: zh:ember:uart:ash: ASH COUNTERS since last clear:
[2024-06-20 15:41:35] info: zh:ember:uart:ash: Total frames: RX=0, TX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: Cancelled : RX=0, TX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: DATA frames : RX=0, TX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: DATA bytes : RX=0, TX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: Retry frames: RX=0, TX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: ACK frames : RX=0, TX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: NAK frames : RX=0, TX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: nRdy frames : RX=0, TX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: CRC errors : RX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: Comm errors : RX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: Length < minimum: RX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: Length > maximum: RX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: Bad controls : RX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: Bad lengths : RX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: Bad ACK numbers : RX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: Out of buffers : RX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: Retry dupes : RX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: Out of sequence : RX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: ACK timeouts : RX=0
[2024-06-20 15:41:35] info: zh:ember:uart:ash: ======== ASH stopped ========
[2024-06-20 15:41:35] error: zh:ember:uart:ash: Failed to init port with error Error: Error: No such file or directory, cannot open /dev/serial/by-id/usb-Silicon_Labs_CP2105_Dual_USB_to_UART_Bridge_Controller_012B810E-if01-port0
[2024-06-20 15:41:35] error: z2m: Error while starting zigbee-herdsman
[2024-06-20 15:41:35] error: z2m: Failed to start zigbee
[2024-06-20 15:41:35] error: z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-06-20 15:41:35] error: z2m: Exiting...
[2024-06-20 15:41:36] error: z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:850:19)
at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:2683:24)
at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:127:29)
at Zigbee.start (/app/lib/zigbee.ts:62:27)
at Controller.start (/app/lib/controller.ts:109:27)
at start (/app/index.js:107:5)
```

attached the copy of the firmware:

```
Openning port .............................. OK
BOARD INFORMATION
FIRMWARE:
ZME CORE VERSION: 0304
BUILD SEQUENCE: 00001641
BUILD DATETIME: 2024-04-15T19:28:38
VERSION: 00.00.23.00
BOOTLOADER VERSION: 02.03.00.01
BOOTLOADER CRC32: bc945096
SE VERSION: 00.01.02.16
IMAGE MIN: 00078000
IMAGE MAX: 000e8000
PAGE SIZE: 00002000
CRC32 KEY UPDATE: c51431b2
USER DATA: VALID
USER DATA PIN: VALID
HARDWARE:
REVISION: 1711
CHIP UUID: 943469fffe18ab21
LOCK: DBG_LOCKED
FAMILY: EFR32MG21
CHIP: EFR32MG21A020F1024IM32
SN:
RAW: F2 C0 16 FE FF 69 34 94 2D FF F3 65 53 02 00 06
PRG. UUID: 943469fffe16c0f2
TIMESATMP: 2024-03-15T08:56:29
SEQUENCE: 000595
CRC8: 06
VALID: YES
LICENSE:
RAW: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 DA D6
Flags:
Validation:OK
MFG STRING:
Z-Wave.Me
MFG_BOARD_NAME:
ZME_ZB-WB7
Close port
```

### Zigbee2MQTT version

1.38.0

### Adapter firmware version

ZME CORE VERSION: 0304

### Adapter

Z-station by z-wave.me

### Setup

Haos on raspberry pi 3

**Comment by haade-administrator** [comment]
i'm to go to fresh install and all is good, my config

```
adapter: ember
baudrate: 115200
port: >-
  /dev/serial/by-id/usb-Silicon_Labs_CP2105_Dual_USB_to_UART_Bridge_Controller_012BA83E-if01-port0
rtscts: false
```
