### ISSUE TITLE
Bug message on entering Dev Console for new unsupported device

### ISSUE THREAD

**Issue by onetoomany** [Koenkk/zigbee2mqtt#23289]
### What happened?

Tried to generate external definition for new device. I clicked on Dev console, and received the following message:

Hello, you've found a bug. Congratulations!
Calm down
Click here, and save this file [Note, no file is downloaded when I click "here"]
Raise a github issue, attach previously downloaded file
Take a screenshot of this page and attach to the issue
In the github issue write detailed description for the issue, how this happened? Steps to reproduce

### What did you expect to happen?

To enter the dev console.

### Zigbee2MQTT version

1.39.0-1

### Adapter firmware version

?

### Adapter

Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Setup

Add-on

### Debug log

TypeError
Cannot read properties of undefined (reading 'clusters')
TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (https://haos.my_server.net/api/hassio_ingress/FxJxr-rtA0Hqb6y0OpCpfNZJTnyGNFrGnI7x_Z5numI/assets/ConnectedDevicePage-e3a64b21.js:1:30966)
    at ab (https://haos.my_server.net/api/hassio_ingress/FxJxr-rtA0Hqb6y0OpCpfNZJTnyGNFrGnI7x_Z5numI/assets/index-e24b99e4.js:43:6186)
    at yD (https://haos.my_server.net/api/hassio_ingress/FxJxr-rtA0Hqb6y0OpCpfNZJTnyGNFrGnI7x_Z5numI/assets/index-e24b99e4.js:43:5982)
    at r3 (https://haos.my_server.net/api/hassio_ingress/FxJxr-rtA0Hqb6y0OpCpfNZJTnyGNFrGnI7x_Z5numI/assets/index-e24b99e4.js:43:44865)
    at e3 (https://haos.my_server.net/api/hassio_ingress/FxJxr-rtA0Hqb6y0OpCpfNZJTnyGNFrGnI7x_Z5numI/assets/index-e24b99e4.js:43:39756)
    at ITe (https://haos.my_server.net/api/hassio_ingress/FxJxr-rtA0Hqb6y0OpCpfNZJTnyGNFrGnI7x_Z5numI/assets/index-e24b99e4.js:43:39682)
    at ap (https://haos.my_server.net/api/hassio_ingress/FxJxr-rtA0Hqb6y0OpCpfNZJTnyGNFrGnI7x_Z5numI/assets/index-e24b99e4.js:43:39534)
    at cb (https://haos.my_server.net/api/hassio_ingress/FxJxr-rtA0Hqb6y0OpCpfNZJTnyGNFrGnI7x_Z5numI/assets/index-e24b99e4.js:43:35900)
    at CD (https://haos.my_server.net/api/hassio_ingress/FxJxr-rtA0Hqb6y0OpCpfNZJTnyGNFrGnI7x_Z5numI/assets/index-e24b99e4.js:43:36704)
    at Gn (https://haos.my_server.net/api/hassio_ingress/FxJxr-rtA0Hqb6y0OpCpfNZJTnyGNFrGnI7x_Z5numI/assets/index-e24b99e4.js:41:3283)

**Comment by Koenkk** [comment]
Please create issues related to the frontend in this repository: https://github.com/nurikk/zigbee2mqtt-frontend
