### ISSUE TITLE
Tuya TS011F_plug_1 display Null as sum of consumed energy

### ISSUE THREAD

**Issue by evilmumi** [Koenkk/zigbee2mqtt#23457]
### What happened?

The plug is not sending a value as energy:
![grafik](https://github.com/user-attachments/assets/a7e19db8-aa69-499b-9c59-0f3943c8cc22)
![grafik](https://github.com/user-attachments/assets/bfec7dcc-257c-4438-ad3e-f14d2fd1c1fa)
i have tried to reset count via dev console - no change.
Also tried to play with calibration settings or something - no change.

Data:
`{"id":45,"type":"Router","ieeeAddr":"0xa4c1384b40863719","nwkAddr":54607,"manufId":4417,"manufName":"_TZ3000_cicwjqth","powerSource":"Mains (single phase)","modelId":"TS011F","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6,1794,2820,57344,57345],"outClusterList":[25,10],"clusters":{"haElectricalMeasurement":{"attributes":{"activePower":0,"rmsVoltage":229,"rmsCurrent":0}},"genBasic":{"attributes":{"modelId":"TS011F","manufacturerName":"_TZ3000_cicwjqth","powerSource":1,"zclVersion":3,"appVersion":116,"stackVersion":0,"hwVersion":1,"swBuildId":""}},"genOnOff":{"attributes":{"32768":0,"moesStartUpOnOff":0,"tuyaBacklightMode":0,"onOff":1}},"seMetering":{"attributes":{"currentSummDelivered":[0,423]}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c2b4d0","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c2b4d0","endpointID":1},{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b0024c2b4d0","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":116,"stackVersion":0,"hwVersion":1,"swBuildId":"","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1722405323108}`

any more information / logs needed?

### Zigbee2MQTT version

1.39.0

### Adapter firmware version

20230507

### Adapter

SONOFF Zigbee 3.0 USB Dongle Plus

### Setup

docker container

**Comment by evilmumi** [comment]
still same in 1.39.1

**Comment by JamesDAdams** [comment]
Same...

**Comment by Koenkk** [comment]
When pressing the configure (yellow refresh) button on the frontend, does this succeed?

**Comment by evilmumi** [comment]
I get:
![grafik](https://github.com/user-attachments/assets/91cbfaae-dce0-4899-986b-67e8397b2c2b)

**Comment by Koenkk** [comment]
Could you check if the issue is fixed with the following [external converter](https://gist.github.com/Koenkk/3eeb90dd20a3bf6f09e76880abfc9c74): 

- save this as file next to `configuration.yaml` as `ext_converter.js`
- add it to `configuration.yaml`:
```yaml
external_converters:
  - ext_converter.js
```
- start z2m, 
- in the frontend, check if the description of this device now ends with `CUSTOM` (this indicates the external converter has been loaded correctly)
- check if configure succeeds now

**Comment by evilmumi** [comment]
log:
`[2024-09-19 09:23:16] info: 	z2m: Loaded external converter 'ext_converter.js'
`
no custom in description:
![image](https://github.com/user-attachments/assets/c1991c1f-a864-4956-9a2a-7453c50e8100)
`[2024-09-19 09:23:19] error: 	z2m: Failed to configure 'Tuya_Gartenpumpe', attempt 1 (Error: ZCL command 0xa4c1384b40863719/1 seMetering.configReport([{"attribute":"currentSummDelivered","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":[1,1]}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:347:28)
    at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:916:26)
    at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:648:9)
    at Object.currentSummDelivered (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:128:5)
    at configure (/app/data/extension/externally-loaded.js:61:9)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:193:21)
    at Configure.configure (/app/lib/extension/configure.ts:125:13)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
`

**Comment by Koenkk** [comment]
`UNSUPPORTED_ATTRIBUTE` indicates it doesn't support reporting the `energy`, does it work when reading via the dev console? If yes, then we need to poll it

<img width="1435" alt="Screenshot 2024-09-19 at 21 50 18" src="https://github.com/user-attachments/assets/40e0ce96-dcb5-4d86-9b11-ac849a9c030e">

**Comment by evilmumi** [comment]
if i do so i receive:
![grafik](https://github.com/user-attachments/assets/d1c3cdd8-e050-4270-9f2b-9e1509c10082)

**Comment by Koenkk** [comment]
`UNSUPPORTED_ATTRIBUTE` indicated this device doesn't support it. To confirm this you would have to check with the Tuya gateway. I think there is little we can do from the z2m side.

**Comment by evilmumi** [comment]
hi , what excatly do you mean with Tuya gateway?

**Comment by Koenkk** [comment]
I mean testing if it work with the original Tuya gateway

**Comment by svmaris** [comment]
I have a couple of these power plugs (slightly different models, `_TZ3000_gjnozsaz` and `_TZ3000_w0qqde0g`) and noticed that they suddenly stopped reporting the total energy value a couple of days ago. Not sure if it's related, but I added a couple of these plugs and a couple of hours later they all stopped reporting the total energy.

Adding ext_converter.js didn't help. Only after downgrading the Docker image from `:dev-latest` to `:latest` (v1.40.1) they started reporting this value again and they've been working fine for the last couple of days.

**Comment by evilmumi** [comment]
> I mean testing if it work with the original Tuya gateway

ah ok. I don't own that HW :/

**Comment by Koenkk** [comment]
@svmaris thanks for reporting, latest-dev indeed had an issue, fix it now.

**Comment by ganslmeier** [comment]
Same issue on my side with TS011F_plug_1. 
I figured out that it works well with the stable version. Dev shows NULL for energy.

**Comment by ganslmeier** [comment]
Version: 1.40.1-dev not working. 
Version: 1.40.1 working. 

I have two lxc container running. If I switch to dev the energy is showing NULL. If I start the stable lxc the energy value is working.

**Comment by briodan** [comment]
Seeing an issue with my [TS011F_plug_3](https://www.zigbee2mqtt.io/devices/TS011F_plug_3.html#tuya-ts011f_plug_3),
![image](https://github.com/user-attachments/assets/ef31f610-6b7c-46be-a378-b01b17c9504e)
 seeing it via the HA addon on 1.40.0, 1.40.1 and 1.40.2

**Comment by Koenkk** [comment]
@ganslmeier is 1.40.2 ok?

**Comment by ganslmeier** [comment]
It is working. Thanks a lot for your great work. 
"version": "1.40.2-dev"

![image](https://github.com/user-attachments/assets/e80fe575-2a69-4735-a3d9-91793e61a3f5)

**Comment by Koenkk** [comment]
@ others, can this be closed?

**Comment by svmaris** [comment]
@Koenkk Just upgraded to 1.40.2-dev commit: [e5fac76](https://github.com/Koenkk/zigbee2mqtt/commit/e5fac76) and it's working fine. Thanks!
