### ISSUE TITLE
Error when changing settings on Tongou TO-Q-SY2-163JZT

### ISSUE THREAD

**Issue by Asion001** [Koenkk/zigbee2mqtt#23466]
### What happened?

I see error 
```
z2m: Publish 'set' 'temperature_threshold' to 'House' failed: 'Error: Expected string or number, got: undefined'
``` 
when changing any threshold settings like "Temperature threshold", "Temperature breaker", "Power threshold", "Power breaker"...
I tried updating firmware on dongle and using ember driver and using latest-dev container as was writen in issue template but error stays. Looks like its an error on `zigbee-herdsman-converters` code and something was fixed couple hours ago.

### What did you expect to happen?

Setting a threshold

### How to reproduce it (minimal and precise)

Press or change value in Exposes -> *** threshold

### Zigbee2MQTT version

1.39.0-dev commit: 7cc5209

### Adapter firmware version

7.4.3 [GA]

### Adapter

szkoston Dongle Plus (gw04-1v2)

### Setup

Docker, x86-64

### Debug log

Error part:
```
[2024-08-01 12:27:00] debug:    z2m:mqtt: Received MQTT message on 'zigbee2mqtt/House/set' with data '{"temperature_threshold":69}'
[2024-08-01 12:27:00] debug:    z2m: Publishing 'set' 'temperature_threshold' to 'House'
[2024-08-01 12:27:00] error:    z2m: Publish 'set' 'temperature_threshold' to 'House' failed: 'Error: Expected string or number, got: undefined'
[2024-08-01 12:27:00] debug:    z2m: Error: Expected string or number, got: undefined
    at Object.getFromLookup (/app/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:647:19)
    at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/devices/tuya.ts:460:55)
    at Publish.onMQTTMessage (/app/lib/extension/publish.ts:277:52)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:23)
    at EventEmitter.emit (node:events:529:35)
    at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:115:22)
    at MQTT.onMessage (/app/lib/mqtt.ts:147:27)
    at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:125:27) 
    at WebSocket.emit (node:events:517:28)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1220:20)
```

[log.log](https://github.com/user-attachments/files/16454052/log.log)

**Comment by Asion001** [comment]
I have a same smart breaker and there all settings is set and can be changed. I think i can fix problem if i set all settings and apply them at once. Is there a way to do this?

**Comment by Asion001** [comment]
Fixed first one too by deleting device from zigbee2mqtt and reconecting (press and hold button on the breaker for 5 sec).
