### ISSUE TITLE
Failed to interview Frient Smoke detector (Model: SMSZB-120) HW:5.0.2

### ISSUE THREAD

**Issue by Uberpainer** [Koenkk/zigbee2mqtt#23536]
### What happened?

I'm not able to successfully interview the mentioned type of smoke detector, even though it is mentioned as supported here:
https://www.zigbee2mqtt.io/devices/SMSZB-120.html
Have tried with three different detectors and changed the batteries.

### What did you expect to happen?

Succesfully interview of smoke detector and able to see mentioned exposes mentioned on this page:
https://www.zigbee2mqtt.io/devices/SMSZB-120.html

### How to reproduce it (minimal and precise)

1. Reset Smoke detector
2. Permit join from Zigbee2MQTT webpage

### Zigbee2MQTT version

1.39.1

### Adapter firmware version

0x264e0900, have also tried with newest adapter firmware 0x26530900, still same issue.

### Adapter

ConBee3

### Setup

Plain from a docker container

### Debug log

info 2024-08-06 19:20:20zh:controller: Interview for '0x0015bc003100fef4' started
info 2024-08-06 19:20:20z2m: Device '0x0015bc003100fef4' joined
info 2024-08-06 19:20:20z2m:mqtt: MQTT publish: topic 'zigbee2mqttmain/bridge/log', payload '{"message":{"friendly_name":"0x0015bc003100fef4"},"type":"device_connected"}'
info 2024-08-06 19:20:20z2m: Starting interview of '0x0015bc003100fef4'
info 2024-08-06 19:20:20z2m:mqtt: MQTT publish: topic 'zigbee2mqttmain/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x0015bc003100fef4"},"type":"pairing"}'
info 2024-08-06 19:20:20z2m:mqtt: MQTT publish: topic 'zigbee2mqttmain/bridge/event', payload '{"data":{"friendly_name":"0x0015bc003100fef4","ieee_address":"0x0015bc003100fef4"},"type":"device_joined"}'
info 2024-08-06 19:20:20z2m:mqtt: MQTT publish: topic 'zigbee2mqttmain/bridge/event', payload '{"data":{"friendly_name":"0x0015bc003100fef4","ieee_address":"0x0015bc003100fef4","status":"started"},"type":"device_interview"}'
error 2024-08-06 19:26:20zh:controller: Interview failed for '0x0015bc003100fef4 with error 'Error: Interview failed because can not get node descriptor ('0x0015bc003100fef4')'
error 2024-08-06 19:26:20z2m: Failed to interview '0x0015bc003100fef4', device has not successfully been paired
info 2024-08-06 19:26:20z2m:mqtt: MQTT publish: topic 'zigbee2mqttmain/bridge/log', payload '{"message":"interview_failed","meta":{"friendly_name":"0x0015bc003100fef4"},"type":"pairing"}'
info 2024-08-06 19:26:20z2m:mqtt: MQTT publish: topic 'zigbee2mqttmain/bridge/event', payload '{"data":{"friendly_name":"0x0015bc003100fef4","ieee_address":"0x0015bc003100fef4","status":"failed"},"type":"device_interview"}'

---------------------

TypeError
Cannot read properties of undefined (reading 'clusters')
TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://192.168.1.140:8080/assets/ConnectedDevicePage-792280da.js:1:31105)
    at ab (http://192.168.1.140:8080/assets/index-74e84a13.js:43:6186)
    at yD (http://192.168.1.140:8080/assets/index-74e84a13.js:43:5982)
    at r3 (http://192.168.1.140:8080/assets/index-74e84a13.js:43:44865)
    at e3 (http://192.168.1.140:8080/assets/index-74e84a13.js:43:39756)
    at ISe (http://192.168.1.140:8080/assets/index-74e84a13.js:43:39682)
    at ap (http://192.168.1.140:8080/assets/index-74e84a13.js:43:39534)
    at cb (http://192.168.1.140:8080/assets/index-74e84a13.js:43:35900)
    at CD (http://192.168.1.140:8080/assets/index-74e84a13.js:43:36704)
    at Gn (http://192.168.1.140:8080/assets/index-74e84a13.js:41:3283)

---------------------

![image](https://github.com/user-attachments/assets/0b72b19d-9de8-4a0a-9a9d-7871d30a9fc9)
###

**Comment by Uberpainer** [comment]
So i tried out with another Conbee 3 I had. Updated firmware to 0x26530900 as I did with the first one. 
Apparently it does now pair
