### ISSUE TITLE
Wrong Device / wrong command?

### ISSUE THREAD

**Issue by SandraCHC** [Koenkk/zigbee2mqtt#23574]
### What happened?

I'm not sure if it is detectet only as wrong devices and all other issues are from this.

After I try reconfiguration I get this error:
```
Error 2024-08-09 13:55:26z2m: Failed to configure 'Temperatursensor Esszimmer', attempt 1 (Error: ZCL command 0xa4c13887e3283998/1 genBasic.read(["manufacturerName","zclVersion","appVersion","modelId","powerSource",65534], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Delivery failed for {"profileId":260,"clusterId":0,"sourceEndpoint":1,"destinationEndpoint":1,"options":4160,"groupId":0,"sequence":223}) at EmberOneWaitress.deliveryFailedFor (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/oneWaitress.ts:98:31) at EmberAdapter.onMessageSent (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:454:42) at Ezsp.emit (node:events:517:28) at Ezsp.ezspMessageSentHandler (/app/node_modules/zigbee-herdsman/src/adapter/ember/ezsp/ezsp.ts:5016:14) at Ezsp.callbackDispatch (/app/node_modules/zigbee-herdsman/src/adapter/ember/ezsp/ezsp.ts:770:26) at Ezsp.onAshFrame (/app/node_modules/zigbee-herdsman/src/adapter/ember/ezsp/ezsp.ts:430:22) at UartAsh.emit (node:events:517:28) at Immediate.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/ember/uart/ash.ts:1187:45) at processImmediate (node:internal/timers:476:21))
```

Detected Device:
Hersteller
[Tuya](https://www.zigbee2mqtt.io/supported-devices/#v=Tuya)
Modell
[ZG-227Z](https://www.zigbee2mqtt.io/devices/ZG-227Z.html#tuya-zg-227z)

But it is a ZG-227ZS i think from the case it is something like this: https://www.zigbee2mqtt.io/devices/ZTH01_ZTH02.html

With the detected device, I see all values and can set values like calibration. But this does not work

### Zigbee2MQTT version

1.39.1

### Adapter firmware version

7.4.2 [GA]

### Adapter

SkyConnect

### Setup

HomeAssistant on Proxmox VM

**Comment by frech-tech** [comment]
This issue is also described in [28695](https://github.com/koenkk/zigbee2mqtt/issues/28695)
