### ISSUE TITLE
Error: SREQ '--> ZDO - activeEpReq - {"dstaddr":0,"nwkaddrofinterest":0}' failed with status '(0xcd: NWK_NO_ROUTE)' (expected '(0x00: SUCCESS)')

### ISSUE THREAD

**Issue by tmoiron** [Koenkk/zigbee2mqtt#23590]
### What happened?

The zigbee2mqtt container stop working after some initialisation steps.
It was working fine before (not a first install)

### What did you expect to happen?

Working as before (zigbee2mqtt working)

### How to reproduce it (minimal and precise)

Every startup reporduce this behaviour.

### Zigbee2MQTT version

koenkk/zigbee2mqtt:1.39.1

### Adapter firmware version

The frontend is not working (init error)

### Adapter

sonoff zigbee 3.0 usb dongle plus

### Setup

docker container (docker-compose). But also don't work unitary docker run.

### Debug log

Using '/app/data' as data directory
Starting Zigbee2MQTT without watchdog.
[2024-08-11 17:01:07] info: 	z2m: Logging to console, file (filename: log.log)
[2024-08-11 17:01:07] debug: 	z2m: Loaded state from file /app/data/state.json
[2024-08-11 17:01:07] info: 	z2m: Starting Zigbee2MQTT version 1.39.1 (commit #e132316)
[2024-08-11 17:01:07] info: 	z2m: Starting zigbee-herdsman (0.55.3)
[2024-08-11 17:01:07] debug: 	z2m: Using zigbee-herdsman with settings: '"{\"network\":{\"panID\":6754,\"extendedPanID\":[221,221,221,221,221,221,221,221],\"channelList\":[11],\"networkKey\":\"HIDDEN\"},\"databasePath\":\"/app/data/database.db\",\"databaseBackupPath\":\"/app/data/database.db.backup\",\"backupPath\":\"/app/data/coordinator_backup.json\",\"serialPort\":{\"path\":\"/dev/ttyACM0\"},\"adapter\":{\"concurrent\":null,\"delay\":null,\"disableLED\":false}}"'
[2024-08-11 17:01:08] debug: 	zh:adapter: Path '/dev/ttyACM0' is valid for 'ZStackAdapter'
[2024-08-11 17:01:08] debug: 	zh:controller: Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":"HIDDEN","panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/ttyACM0"},"databasePath":"/app/data/database.db","databaseBackupPath":"/app/data/database.db.backup","backupPath":"/app/data/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
[2024-08-11 17:01:08] info: 	zh:zstack:znp: Opening SerialPort with {"path":"/dev/ttyACM0","baudRate":115200,"rtscts":false,"autoOpen":false}
[2024-08-11 17:01:08] info: 	zh:zstack:znp: Serialport opened
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SYS - ping - {"capabilities":1}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,0,33,1,32]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,1,121,1,26]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,1,121,1,26]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 1 - [121,1] - 26
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SYS - ping - {"capabilities":377}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SYS - ping - {"capabilities":1}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,0,33,1,32]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,1,121,1,26]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,1,121,1,26]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 1 - [121,1] - 26
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SYS - ping - {"capabilities":377}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SYS - version - {}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,0,33,2,35]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,14,97,2,2,0,2,6,3,167,62,52,1,2,0,0,0,0,198]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,14,97,2,2,0,2,6,3,167,62,52,1,2,0,0,0,0,198]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 14 - 3 - 1 - 2 - [2,0,2,6,3,167,62,52,1,2,0,0,0,0] - 198
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SYS - version - {"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20201127}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:zstack: Adapter concurrent: 2
[2024-08-11 17:01:08] debug: 	zh:zstack: Detected znp version 'zStack12' ({"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20201127})
[2024-08-11 17:01:08] debug: 	zh:adapter:zstack:manager: beginning znp startup
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SYS - getExtAddr - {}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,0,33,4,37]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,8,97,4,162,111,56,25,0,75,18,0,216]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,8,97,4,162,111,56,25,0,75,18,0,216]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 8 - 3 - 1 - 4 - [162,111,56,25,0,75,18,0] - 216
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SYS - getExtAddr - {"extaddress":"0x00124b0019386fa2"}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvLength - {"id":130}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,2,33,19,130,0,178]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,19,21,0,101]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,19,21,0,101]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 19 - [21,0] - 101
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvLength - {"length":21}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvReadExt - {"id":130,"offset":0}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,4,33,28,130,0,0,0,187]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,23,97,28,0,21,0,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13,196,9,0,0,177]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,23,97,28,0,21,0,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13,196,9,0,0,177]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 23 - 3 - 1 - 28 - [0,21,0,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13,196,9,0,0] - 177
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvReadExt - {"status":0,"len":21,"value":{"type":"Buffer","data":[0,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13,196,9,0,0]}}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:adapter:zstack:manager: determining znp startup strategy
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvLength - {"id":3840}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,2,33,19,0,15,63]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,19,1,0,113]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,19,1,0,113]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 19 - [1,0] - 113
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvLength - {"length":1}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvReadExt - {"id":3840,"offset":0}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,4,33,28,0,15,0,0,54]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,3,97,28,0,1,85,42]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,3,97,28,0,1,85,42]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 3 - 3 - 1 - 28 - [0,1,85] - 42
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvReadExt - {"status":0,"len":1,"value":{"type":"Buffer","data":[85]}}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvLength - {"id":33}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,2,33,19,33,0,17]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,19,110,0,30]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,19,110,0,30]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 19 - [110,0] - 30
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvLength - {"length":110}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvReadExt - {"id":33,"offset":0}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,4,33,28,33,0,0,0,24]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,112,97,28,0,110,93,5,2,21,20,21,0,20,0,0,0,1,5,1,143,7,0,2,5,30,0,0,11,0,0,0,0,0,0,0,0,0,0,98,26,8,0,8,0,0,15,15,5,0,1,0,0,0,1,0,0,0,0,162,111,56,25,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,3,0,1,60,10,1,0,0,0,0,0,85]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,112,97,28,0,110,93,5,2,21,20,21,0,20,0,0,0,1,5,1,143,7,0,2,5,30,0,0,11,0,0,0,0,0,0,0,0,0,0,98,26,8,0,8,0,0,15,15,5,0,1,0,0,0,1,0,0,0,0,162,111,56,25,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,3,0,1,60,10,1,0,0,0,0,0,85]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 112 - 3 - 1 - 28 - [0,110,93,5,2,21,20,21,0,20,0,0,0,1,5,1,143,7,0,2,5,30,0,0,11,0,0,0,0,0,0,0,0,0,0,98,26,8,0,8,0,0,15,15,5,0,1,0,0,0,1,0,0,0,0,162,111,56,25,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,3,0,1,60,10,1,0,0,0,0,0] - 85
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvReadExt - {"status":0,"len":110,"value":{"type":"Buffer","data":[93,5,2,21,20,21,0,20,0,0,0,1,5,1,143,7,0,2,5,30,0,0,11,0,0,0,0,0,0,0,0,0,0,98,26,8,0,8,0,0,15,15,5,0,1,0,0,0,1,0,0,0,0,162,111,56,25,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,3,0,1,60,10,1,0,0,0,0,0]}}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SAPI - readConfiguration - {"configid":98}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,1,38,4,98,65]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,19,102,4,0,98,16,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13,0]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,19,102,4,0,98,16,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13,0]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 19 - 3 - 6 - 4 - [0,98,16,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13] - 0
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SAPI - readConfiguration - {"status":0,"configid":98,"len":16,"value":{"type":"Buffer","data":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13]}}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvLength - {"id":58}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,2,33,19,58,0,10]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,19,17,0,97]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,19,17,0,97]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 19 - [17,0] - 97
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvLength - {"length":17}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvReadExt - {"id":58,"offset":0}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,4,33,28,58,0,0,0,3]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,28,2,0,125]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,28,2,0,125]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 28 - [2,0] - 125
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvReadExt - {"status":2,"len":0,"value":{"type":"Buffer","data":[]}}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvReadExt - {"id":58,"offset":0}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,4,33,28,58,0,0,0,3]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,28,2,0,125]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,28,2,0,125]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 28 - [2,0] - 125
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvReadExt - {"status":2,"len":0,"value":{"type":"Buffer","data":[]}}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvReadExt - {"id":58,"offset":0}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,4,33,28,58,0,0,0,3]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,28,2,0,125]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,28,2,0,125]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 28 - [2,0] - 125
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvReadExt - {"status":2,"len":0,"value":{"type":"Buffer","data":[]}}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvLength - {"id":59}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,2,33,19,59,0,11]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,19,17,0,97]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,19,17,0,97]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 19 - [17,0] - 97
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvLength - {"length":17}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvReadExt - {"id":59,"offset":0}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,4,33,28,59,0,0,0,2]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,28,2,0,125]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,28,2,0,125]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 28 - [2,0] - 125
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvReadExt - {"status":2,"len":0,"value":{"type":"Buffer","data":[]}}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvReadExt - {"id":59,"offset":0}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,4,33,28,59,0,0,0,2]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,28,2,0,125]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,28,2,0,125]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 28 - [2,0] - 125
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvReadExt - {"status":2,"len":0,"value":{"type":"Buffer","data":[]}}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> SYS - osalNvReadExt - {"id":59,"offset":0}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,4,33,28,59,0,0,0,2]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,2,97,28,2,0,125]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,2,97,28,2,0,125]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 2 - 3 - 1 - 28 - [2,0] - 125
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- SYS - osalNvReadExt - {"status":2,"len":0,"value":{"type":"Buffer","data":[]}}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:adapter:zstack:manager: (stage-1) adapter is configured
[2024-08-11 17:01:08] debug: 	zh:adapter:zstack:manager: (stage-2) adapter state matches configuration
[2024-08-11 17:01:08] debug: 	zh:adapter:zstack:manager: determined startup strategy: startup
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> UTIL - getDeviceInfo - {}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,0,39,0,39]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,14,103,0,0,162,111,56,25,0,75,18,0,0,0,7,9,0,210]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,14,103,0,0,162,111,56,25,0,75,18,0,0,0,7,9,0,210]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 14 - 3 - 7 - 0 - [0,162,111,56,25,0,75,18,0,0,0,7,9,0] - 210
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- UTIL - getDeviceInfo - {"status":0,"ieeeaddr":"0x00124b0019386fa2","shortaddr":0,"devicetype":7,"devicestate":9,"numassocdevices":0,"assocdeviceslist":[]}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-08-11 17:01:08] debug: 	zh:adapter:zstack:manager: adapter is already running in coordinator mode
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SREQ: --> ZDO - activeEpReq - {"dstaddr":0,"nwkaddrofinterest":0}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:writer: --> frame [254,4,37,5,0,0,0,0,36]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: <-- [254,1,101,5,205,172]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext [254,1,101,5,205,172]
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --> parsed 1 - 3 - 5 - 5 - [205] - 172
[2024-08-11 17:01:08] debug: 	zh:zstack:znp: SRSP: <-- ZDO - activeEpReq - {"status":205}
[2024-08-11 17:01:08] debug: 	zh:zstack:unpi:parser: --- parseNext []
Error: SREQ '--> ZDO - activeEpReq - {"dstaddr":0,"nwkaddrofinterest":0}' failed with status '(0xcd: NWK_NO_ROUTE)' (expected '(0x00: SUCCESS)')
    at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:306:27
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)

**Comment by tmoiron** [comment]
The problem was not due to zigbee2mqtt.
My RPI sd card was read only. I changed it and it is back.
