### ISSUE TITLE
Cover Entity not Available in Home Assistant

### ISSUE THREAD

**Issue by nilshoell** [Koenkk/zigbee2mqtt#23764]
### What happened?

I have a couple of [Lonsonho QS-Zigbee-C03](https://www.zigbee2mqtt.io/devices/QS-Zigbee-C03.html) blind/cover motor controllers that I use to control blinds in my home.  
They are correctly adopted in Z2M, I can control everything from the frontend, but not via Home Assistant. The devices are discovered and show up, I can see most of the attributes like `moving`, `calibration`, I can even set the `motor_reversal`, but the actual `cover` options to open/close the blinds or set a position are missing completely.

I have not filtered any attributes, the `state` of the devices contains the position as expected, but maybe I need to configure something for Home Assistant to correctly discover these devices as covers, similar to light switches so they are discovered as lights?

### What did you expect to happen?

The `cover` entity of the devices to show up in Home Assistant so I can control the blinds from HA.

### Zigbee2MQTT version

1.39.1

### Adapter firmware version

20230507

### Adapter

TubesZB CC2652 P7 PoE

### Setup

Dockerized on a Pi4 with Mosquitto and the MQTT integration in HA

**Comment by nilshoell** [comment]
No change after the upgrade to z2m version 1.40.1, but I got this from the HomeAssistant logs:

```
2024-09-08 12:47:25.761 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state', 'value_template': '{{ value_json.state }}'}], 'command_topic': 'zigbee2mqtt/<friendly_name>/set', 'device': {'configuration_url': 'https://zigbee2mqtt.<domain.tld>/#/device/<device_id>/info', 'identifiers': ['zigbee2mqtt_<device_id>'], 'manufacturer': 'Lonsonho', 'model': 'Curtain/blind motor controller (QS-Zigbee-C03)', 'name': '<friendly_name>', 'via_device': 'zigbee2mqtt_bridge_0x00124b002e0e1e7a'}, 'name': None, 'object_id': '<friendly_name>', 'origin': {'name': 'Zigbee2MQTT', 'sw': '1.40.1', 'url': 'https://www.zigbee2mqtt.io'}, 'position_template': '{{ value_json.position }}', 'position_topic': 'zigbee2mqtt/<friendly_name>', 'set_position_template': '{ "position": {{ position }} }', 'set_position_topic': 'zigbee2mqtt/<friendly_name>/set', 'state_closing': 'DOWN', 'state_opening': 'UP', 'state_stopped': 'STOP', 'state_topic': 'zigbee2mqtt/<friendly_name>', 'unique_id': '<device_id>_cover_zigbee2mqtt', 'value_template': '{% if "moving" in value_json and value_json.moving %} {{ value_json.moving }} {% else %} STOP {% endif %}', 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 270, in async_discover
    config: DiscoveryInfoType = discovery_schema(discovery_payload)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 232, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 351, in _exec
    v = func(v)
        ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: string value is None for dictionary value @ data['name']
```

This seems to suggest that something might be missing or broken in the discovery payload, maybe just for this specific device.
I know too little about how z2m integrates with HA, so if someone could point me into the right direction of where to look for more details that would be great.

**Comment by nilshoell** [comment]
Turns out it was an issue with Home Assistant after all, a clean install of the latest version of HA and everything worked as expected.
