### ISSUE TITLE
Zemismart ZM25RX-08/30 doesn't control motor - reports state only

### ISSUE THREAD

**Issue by markxroberts** [Koenkk/zigbee2mqtt#23801]
### What happened?

Device pairs, but doesn't report anything until a second attempt at pairing.
After the second attempt, it reports its state, but doesn't respond to any of the actions.
OPEN/CLOSE/STOP lead to a state report of the same value without any movement of the blind.
upper/upper_micro/lower/lower_micro similarly lead to no movement.

### What did you expect to happen?

Pushing buttons leads to a motor response

### How to reproduce it (minimal and precise)

See above

### Zigbee2MQTT version

1.39.1/Conbee 1.40.0/Z-Stack

### Adapter firmware version

zStack3x0 20220219, Conbee  0x26580700

### Adapter

Conbee or Z-Stack

### Setup

Z2M container, running via serial/ethernet

### Debug log

```
Error 2024-09-01 21:15:40z2m: EventBus error 'Publish/mqttMessage': Cannot read properties of undefined (reading 'some')
Error 2024-09-01 21:15:45z2m: EventBus error 'Publish/mqttMessage': Cannot read properties of undefined (reading 'some')
Error 2024-09-01 21:15:51z2m: EventBus error 'Publish/mqttMessage': Cannot read properties of undefined (reading 'some')
Error 2024-09-01 21:15:53z2m: EventBus error 'Publish/mqttMessage': Cannot read properties of undefined (reading 'some')
Info 2024-09-01 21:15:40z2m:mqtt: MQTT publish: topic 'zigbee2mqttlights/0x286847fffe27c6d6', payload '{"battery":null,"click_control":"lower","linkquality":83,"motor_direction":"normal","position":0,"program":"set_upper","state":"OPEN","work_state":"closing"}'
Info 2024-09-01 21:15:45z2m:mqtt: MQTT publish: topic 'zigbee2mqttlights/0x286847fffe27c6d6', payload '{"battery":null,"click_control":"lower","linkquality":83,"motor_direction":"normal","position":0,"program":"set_upper","state":"CLOSE","work_state":"closing"}'
Info 2024-09-01 21:15:51z2m:mqtt: MQTT publish: topic 'zigbee2mqttlights/0x286847fffe27c6d6', payload '{"battery":null,"click_control":"lower","linkquality":83,"motor_direction":"normal","position":0,"program":"set_bottom","state":"CLOSE","work_state":"closing"}'
Info 2024-09-01 21:15:53z2m:mqtt: MQTT publish: topic 'zigbee2mqttlights/0x286847fffe27c6d6', payload '{"battery":null,"click_control":"lower","linkquality":83,"motor_direction":"normal","position":0,"program":"set_upper","state":"CLOSE","work_state":"closing"}'
```

**Comment by markxroberts** [comment]
This is still a problem on ```latest-dev``` branch
The above errors have gone away, but there remains debug errors:
Error messages through debug logging as below:
```
[2024-09-04 19:56:48] debug: 	zh:controller:endpoint: Error: ZCL command 0x286847fffe27c6d6/1 manuSpecificTuya.dataRequest({"seq":1,"dpValues":[{"dp":1,"datatype":4,"data":[0]}]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)
    at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23)
    at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:300:45
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:26)
    at Znp.request (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:291:27)
    at ZStackAdapter.dataRequest (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:1201:24)
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:446:46)
    at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:380:25
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:26)
    at ZStackAdapter.sendZclFrameToEndpoint (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:378:27)
    at Request.func (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:296:36)
[2024-09-04 19:56:48] error: 	z2m: Publish 'set' 'state' to '0x286847fffe27c6d6' failed: 'Error: ZCL command 0x286847fffe27c6d6/1 manuSpecificTuya.dataRequest({"seq":1,"dpValues":[{"dp":1,"datatype":4,"data":[0]}]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)'
[2024-09-04 19:56:48] debug: 	z2m: Error: ZCL command 0x286847fffe27c6d6/1 manuSpecificTuya.dataRequest({"seq":1,"dpValues":[{"dp":1,"datatype":4,"data":[0]}]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)
    at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23)
    at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:300:45
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:26)
    at Znp.request (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:291:27)
    at ZStackAdapter.dataRequest (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:1201:24)
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:446:46)
    at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:380:25
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:26)
    at ZStackAdapter.sendZclFrameToEndpoint (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:378:27)
    at Request.func (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:296:36)
[2024-09-04 19:56:48] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqttlights/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x286847fffe27c6d6' failed: 'Error: ZCL command 0x286847fffe27c6d6/1 manuSpecificTuya.dataRequest({\"seq\":1,\"dpValues\":[{\"dp\":1,\"datatype\":4,\"data\":[0]}]}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"reservedBits\":0,\"writeUndiv\":false}) failed (SRSP - AF - dataRequest after 6000ms)'","meta":{"friendly_name":"0x286847fffe27c6d6"},"type":"zigbee_publish_error"}'
[2024-09-04 19:56:54] debug: 	zh:zstack: sendZclFrameToEndpointInternal 0x286847fffe27c6d6:62051/1 (0,0,1)
[2024-09-04 19:56:54] debug: 	zh:zstack:znp: SREQ: --> AF - dataRequest - {"dstaddr":62051,"destendpoint":1,"srcendpoint":1,"clusterid":61184,"transid":44,"options":0,"radius":30,"len":10,"data":{"type":"Buffer","data":[17,29,0,1,0,1,4,0,1,1]}}
[2024-09-04 19:56:54] debug: 	zh:zstack:unpi:writer: --> frame [254,20,36,1,99,242,1,1,0,239,44,0,30,10,17,29,0,1,0,1,4,0,1,1,127]
[2024-09-04 19:56:54] debug: 	zh:controller:endpoint: Error: ZCL command 0x286847fffe27c6d6/1 manuSpecificTuya.dataRequest({"seq":1,"dpValues":[{"dp":1,"datatype":4,"data":[2]}]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)
    at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23)
    at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:300:45
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:26)
    at Znp.request (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:291:27)
    at ZStackAdapter.dataRequest (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:1201:24)
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:446:46)
    at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:380:25
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:26)
    at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:82:20)
    at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:911:28)
[2024-09-04 19:56:54] error: 	z2m: Publish 'set' 'state' to '0x286847fffe27c6d6' failed: 'Error: ZCL command 0x286847fffe27c6d6/1 manuSpecificTuya.dataRequest({"seq":1,"dpValues":[{"dp":1,"datatype":4,"data":[2]}]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)'
[2024-09-04 19:56:54] debug: 	z2m: Error: ZCL command 0x286847fffe27c6d6/1 manuSpecificTuya.dataRequest({"seq":1,"dpValues":[{"dp":1,"datatype":4,"data":[2]}]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)
    at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23)
    at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:300:45
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:26)
    at Znp.request (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:291:27)
    at ZStackAdapter.dataRequest (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:1201:24)
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:446:46)
    at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:380:25
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:26)
    at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:82:20)
    at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:911:28)
[2024-09-04 19:56:54] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqttlights/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x286847fffe27c6d6' failed: 'Error: ZCL command 0x286847fffe27c6d6/1 manuSpecificTuya.dataRequest({\"seq\":1,\"dpValues\":[{\"dp\":1,\"datatype\":4,\"data\":[2]}]}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"reservedBits\":0,\"writeUndiv\":false}) failed (SRSP - AF - dataRequest after 6000ms)'","meta":{"friendly_name":"0x286847fffe27c6d6"},"type":"zigbee_publish_error"}'
[2024-09-04 19:57:00] debug: 	zh:controller:endpoint: Error: ZCL command 0x286847fffe27c6d6/1 manuSpecificTuya.dataRequest({"seq":1,"dpValues":[{"dp":1,"datatype":4,"data":[1]}]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)
    at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23)
    at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:300:45
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:26)
    at Znp.request (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:291:27)
    at ZStackAdapter.dataRequest (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:1201:24)
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:446:46)
    at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:380:25
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:26)
    at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:82:20)
    at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:911:28)
[2024-09-04 19:57:00] error: 	z2m: Publish 'set' 'state' to '0x286847fffe27c6d6' failed: 'Error: ZCL command 0x286847fffe27c6d6/1 manuSpecificTuya.dataRequest({"seq":1,"dpValues":[{"dp":1,"datatype":4,"data":[1]}]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)'
[2024-09-04 19:57:00] debug: 	z2m: Error: ZCL command 0x286847fffe27c6d6/1 manuSpecificTuya.dataRequest({"seq":1,"dpValues":[{"dp":1,"datatype":4,"data":[1]}]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)
    at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23)
    at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:300:45
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:26)
    at Znp.request (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:291:27)
    at ZStackAdapter.dataRequest (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:1201:24)
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:446:46)
    at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:380:25
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:26)
    at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:82:20)
    at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:911:28)
[2024-09-04 19:57:00] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqttlights/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x286847fffe27c6d6' failed: 'Error: ZCL command 0x286847fffe27c6d6/1 manuSpecificTuya.dataRequest({\"seq\":1,\"dpValues\":[{\"dp\":1,\"datatype\":4,\"data\":[1]}]}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"reservedBits\":0,\"writeUndiv\":false}) failed (SRSP - AF - dataRequest after 6000ms)'","meta":{"friendly_name":"0x286847fffe27c6d6"},"type":"zigbee_publish_error"}'
```

**Comment by markxroberts** [comment]
This was also a problem with the branded Tuya hub.  I returned the motor as faulty.  An externally similar version with a different model number seems to work perfectly.  See issue #24155.
