### ISSUE TITLE
IKEA	 E1603/E1702/E1708 - keep disappearing

### ISSUE THREAD

**Issue by chrisrock1984** [Koenkk/zigbee2mqtt#23829]
### What happened?

after ~ 2 days (devices have been removed and added again to make the connected again), the devices will disappear. when trying to use the "configure" command, they do not reconnect and produce the added log below. only re-adding them or a power cylce them every time, they will reconnect.
one of the 4 sockets is close to the coordinator, the other 3 are further away but were added using the closest repeater (sonoff)

### What did you expect to happen?

that the sockets keep connected

### How to reproduce it (minimal and precise)

wait 2 days or so until they are gone

### Zigbee2MQTT version

1.40.0

### Adapter firmware version

20240716

### Adapter

SLZB-06P7

### Setup

Add-On on Home Assistant - HAOS running on proxmox x86

### Debug log

z2m: Failed to configure '0x680ae2fffe40dc71', attempt 2 (Error: Bind 0x680ae2fffe40dc71/1 genOnOff from '0x00124b001ca60ef4/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23) at Object.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:1118:40) at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:857:28 at processTicksAndRejections (node:internal/process/task_queues:95:5) at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:20) at ZStackAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:799:9) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:531:13) at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:109:13) at result.configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:486:17) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:190:21))

**Comment by chrisrock1984** [comment]
The problems keep appearing but will close this issue, as it seems a local event on my installation.
