### ISSUE TITLE
Ikea E2123 keeps losing connection

### ISSUE THREAD

**Issue by fthiery** [Koenkk/zigbee2mqtt#23840]
### What happened?

Device keeps losing connection after a few hours, often right after i use it (e.g. i click on a button -- action works -- but then device becomes unresponsive). To fix it, i have to either
* open the lid, remove the batteries and re-insert them
* **fetch the battery level !**

![image](https://github.com/user-attachments/assets/ff0d7298-bb3d-4937-bf1a-74d31bf661cd)

I tried pairing on multiple routers (Ikea plug, LIDL plug), even placed the device a few centimeters away from the Ikea plug, and it still loses connection.

NB: Legacy integration is disabled

### What did you expect to happen?

I wish it kept working...

### How to reproduce it (minimal and precise)

The logs below have been acquired with the following scenario:
* press button yesterday evening (toggle button to stop music playback)
* night passes
* in the morning, press button (launches an action in HA) <-- WORKS
* press volume down <-- WORKS
* press volume down/up/whatever <-- NO EFFECT, NOTHING IN THE LOGS

### Zigbee2MQTT version

1.40.0

### Adapter firmware version

20240710

### Adapter

zStack3x0 (Sonoff-P)

### Setup

Home Assistant Addon (HAOS on Home Assistant Green)

### Debug log

It was surprisingly complicated to get the logs (did not manage to make syslog work), i managed using:
- set logging to debug, enable "Log symlink current" and "Log rotation" options
- on machine with a large disk and ip address IP, start `nc -l 1234 | tee z2m.log`
- run `tail -F /root/config/zigbee2mqtt/log/current/log.log | nc IP 1234` in Home Assistant

```
$ grep Télécommande log  | grep info | grep -v "{"
[2024-09-04 20:43:02] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Télécommande Soundsystem/action', payload 'toggle'
[2024-09-05 07:46:25] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Télécommande Soundsystem/action', payload 'dots_1_initial_press'
[2024-09-05 07:46:26] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Télécommande Soundsystem/action', payload 'dots_1_short_release'
[2024-09-05 07:46:32] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Télécommande Soundsystem/action', payload 'dots_1_initial_press'
[2024-09-05 07:46:36] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Télécommande Soundsystem/action', payload 'dots_1_short_release'
[2024-09-05 07:46:36] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Télécommande Soundsystem/action', payload 'volume_down'
```
All subsequent presses after the last one are not doing anything.

Detailed info of the last command -- and any further items related to the device (which does not seem to indicate much):

```
[2024-09-05 07:46:36] debug:    z2m: Received Zigbee message from 'Télécommande Soundsystem', type 'commandMoveWithOnOff', cluster 'genLevelCtrl', data '{"movemode":1,"rate":255}' from endpoint 1 with groupID 0
[2024-09-05 07:46:36] info:     z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Télécommande Soundsystem', payload '{"action":"volume_down","battery":82,"linkquality":65,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null,"voltage":2600}'
[2024-09-05 07:46:36] info:     z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Télécommande Soundsystem', payload '{"action":"","battery":82,"linkquality":65,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null,"voltage":2600}'
[2024-09-05 07:46:36] info:     z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Télécommande Soundsystem/action', payload 'volume_down'
[2024-09-05 07:46:36] debug:    zh:zstack:unpi:parser: <-- [254,33,68,129,0,0,0,239,189,223,1,1,0,65,0,106,125,68,0,0,13,9,95,2,0,16,9,2,0,4,0,0,0,0,111,114,27,59]
[2024-09-05 07:46:36] debug:    zh:zstack:unpi:parser: --- parseNext [254,33,68,129,0,0,0,239,189,223,1,1,0,65,0,106,125,68,0,0,13,9,95,2,0,16,9,2,0,4,0,0,0,0,111,114,27,59]
[2024-09-05 07:46:36] debug:    zh:zstack:unpi:parser: --> parsed 33 - 2 - 4 - 129 - [0,0,0,239,189,223,1,1,0,65,0,106,125,68,0,0,13,9,95,2,0,16,9,2,0,4,0,0,0,0,111,114,27] - 59
[2024-09-05 07:46:36] debug:    zh:zstack:znp: AREQ: <-- AF - incomingMsg - {"groupid":0,"clusterid":61184,"srcaddr":57277,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":65,"securityuse":0,"timestamp":4488554,"transseqnumber":0,"len":13,"data":{"type":"Buffer","data":[9,95,2,0,16,9,2,0,4,0,0,0,0]}}
[2024-09-05 07:46:36] debug:    zh:controller: Received payload: clusterID=61184, address=57277, groupID=0, endpoint=1, destinationEndpoint=1, wasBroadcast=false, linkQuality=65, frame={"header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false,"reservedBits":0},"transactionSequenceNumber":95,"commandIdentifier":2},"payload":{"seq":4096,"dpValues":[{"dp":9,"datatype":2,"data":{"type":"Buffer","data":[0,0,0,0]}}]},"command":{"ID":2,"parameters":[{"name":"seq","type":33},{"name":"dpValues","type":1011}],"name":"dataReport"}}
[2024-09-05 07:46:36] debug:    zh:controller:endpoint: ZCL command 0x4c5bb3fffe932813/1 manuSpecificTuya.defaultRsp({"cmdId":2,"statusCode":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"transactionSequenceNumber":95,"writeUndiv":false})
[2024-09-05 07:46:36] debug:    zh:zstack: sendZclFrameToEndpointInternal 0x4c5bb3fffe932813:57277/1 (0,0,1)
[2024-09-05 07:46:36] debug:    zh:zstack:znp: SREQ: --> AF - dataRequest - {"dstaddr":57277,"destendpoint":1,"srcendpoint":1,"clusterid":61184,"transid":148,"options":0,"radius":30,"len":5,"data":{"type":"Buffer","data":[16,95,11,2,0]}}
[2024-09-05 07:46:36] debug:    zh:zstack:unpi:writer: --> frame [254,15,36,1,189,223,1,1,0,239,148,0,30,5,16,95,11,2,0,110]
[2024-09-05 07:46:36] debug:    zh:zstack:unpi:parser: --- parseNext []
```

**Comment by chrisrock1984** [comment]
I also have problems with Ikea devices now. for me the sockets keep disappearing

**Comment by fthiery** [comment]
I finally catched logs... Which indicate nothing ! When it stops working, i just see nothing anymore in the Z2M logs. The logs are really big, so if anyone has an idea of additional items to check in the logs, please ask

**Comment by fthiery** [comment]
I just discovered that if i get the battery level, the device will resume emitting press events, @Koenkk does that ring any bell or is the device just buggy ?

```
PRESS buttons <-- nothing happens
GET BATTERY
[2024-09-05 11:20:45] debug: 	z2m:mqtt: Received MQTT message on 'zigbee2mqtt/Télécommande Soundsystem/get' with data '{"battery":""}'
WORKS BACK
[2024-09-05 11:20:57] debug: 	z2m: Received Zigbee message from 'Télécommande Soundsystem', type 'commandMoveWithOnOff', cluster 'genLevelCtrl', data '{"movemode":1,"rate":255}' from endpoint 1 with groupID 0
[2024-09-05 11:20:57] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Télécommande Soundsystem', payload '{"action":"volume_down","battery":84,"linkquality":65,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null,"voltage":2600}'
[2024-09-05 11:20:57] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Télécommande Soundsystem', payload '{"action":"","battery":84,"linkquality":65,"update":{"installed_version":-1,"latest_version":-1,"state":null},"update_available":null,"voltage":2600}'
[2024-09-05 11:20:57] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Télécommande Soundsystem/action', payload 'volume_down'
```

**Comment by Koenkk** [comment]
@fthiery that doesn't ring any bell, if you do not see any `Received Zigbee message` then the device doesn't send any message. [Sniffing](https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html) would be needed to debug it further.

Does the issue also occur when re-pairing the device through the coordinator and keeping it close to it? If not, then the issue may be related to one of the routers in your network.

**Comment by fthiery** [comment]
> @fthiery that doesn't ring any bell, if you do not see any `Received Zigbee message` then the device doesn't send any message.

I confirm: when the device has reached the problematic state, there is no `Received Zigbee message` at all.

> [Sniffing](https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html) would be needed to debug it further.

I'll look into this

> Does the issue also occur when re-pairing the device through the coordinator and keeping it close to it? If not, then the issue may be related to one of the routers in your network.

I'll try this next, thanks for the suggestion.

**Comment by fthiery** [comment]
For the record, this weekend i did a full mesh "reset" (i.e. stop z2m, kill house mains power for 1 minute, wait 20 min, then restart the coordinator), and so far the problem did not reproduce, although i am ready to sniff the traffic. I guess this seems to int at a router/routing problem...

**Comment by fthiery** [comment]
@Koenkk i managed to catch a trace when reproducing the problem, here's a trace captured with filter `_ws.col.def_src == "0xb950" or _ws.col.def_dst == "0xb950"` ; in this trace i was pressing buttons and while the device seems to send and receive data, it seems it does not send action packets; if i request the battery attribute, it comes back and i see the presses.

[trace_state.pcapng.gz](https://github.com/user-attachments/files/17114599/trace_state.pcapng.gz)

What do you think ?

**Comment by Koenkk** [comment]
- Whats the network key of this sniff?
- Could you try to wakeup the device and immediately after that do a configure (z2m frontend -> device -> yellow refresh icon). Does that succeed and fix the issue?

**Comment by fthiery** [comment]
> * Whats the network key of this sniff?

Sorry, i thought that Wireshark would export decrypted packets. I've connected you on linkedin to DM it to you.

> * Could you try to wakeup the device and immediately after that do a configure (z2m frontend -> device -> yellow refresh icon). Does that succeed and fix the issue?

Will do next time it happens (i.e. run configure instead of querying battery state)

**Comment by fthiery** [comment]
Alternatively, 

Here's a normal trace: it shows Zigbee HA requests
![image](https://github.com/user-attachments/assets/d2ccbd9e-416a-472d-9939-f123a6d883d2)

Here's the trace when it's not working; it shows Zigbee ZDP requests 
![image](https://github.com/user-attachments/assets/4f5f7dfa-ba38-4143-8e01-8f1596316ce5)

**Comment by fthiery** [comment]
> * Could you try to wakeup the device and immediately after that do a configure (z2m frontend -> device -> yellow refresh icon). Does that succeed and fix the issue?

Hi, just tried (the device got stuck again); the configure errors out with the following log:

```
error 2024-10-02 13:17:08z2m: Failed to configure 'Télécommande Soundsystem', attempt 3 (Error: Bind 0x540f57fffe1e42b7/1 genPollCtrl from '0x00124b002a2ec36f/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23) at Object.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:1118:40) at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:857:28 at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:20) at ZStackAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:799:9) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:531:13) at configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:176:17) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:193:21) at Configure.configure (/app/lib/extension/configure.ts:125:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:56:21))
```

**Comment by fthiery** [comment]
@Koenkk i did sniff the traffic again; when the device is stuck, i see a lot of ZDP requests (Network Address Request) from the device; it seems it left the network and is requesting a new address, without success.

When i request the battery level, it seems to get an address ???

![image](https://github.com/user-attachments/assets/9c5c219d-6ab8-4f19-a54d-bdec271615d5)

**Comment by fthiery** [comment]
> That's not what this ZDP request does. A network address request allows a device to request the network address of another device. It seems to request the network address of the coordinator, which is answered correctly on 1442

What could block the device from receiving a response to it's request ?

> One thing that confuses me, I see the device starts sending requests again (e.g. 1633) but the battery read is later (1671)?

Yes, that's the strange part; i literally do nothing else than requesting the battery level; it seems that asking the coordinator to request the battery level "unblocks" the pending ZDP response.

I'll use a chronometer next time, started when i start the capture, to reference the exact moment when i press the button, so that i can identify the moment in the traces.

>> Could you try to wakeup the device and immediately after that do a configure (z2m frontend -> device -> yellow refresh icon). Does that succeed and fix the issue?
> Hi, just tried (the device got stuck again); the configure errors out with the following log:

What did you have in mind ? What can you do from the fact that it does not work ?

**Comment by Koenkk** [comment]
I have no clue tbh, and did not see any other reports about this, could it be that your E2123 is broken? (did you already try with another one)?

**Comment by fthiery** [comment]
Still happening, i'm gradually removing devices from my network to see if there is a culprit.

**Comment by fthiery** [comment]
For the record, the problem disappeared after removing some devices, notably one Silvercrest smart plug that had bad signal, and heiman sirens. Not sure what fixed it, but it did...

**Comment by 1aranzant** [comment]
I have the exact same issue... my symfo gen2 remote stops responding randomly, I deleted a lot of devices but the issue keeps on happening... @fthiery did you fix it for good?

**Comment by fthiery** [comment]
> I have the exact same issue... my symfo gen2 remote stops responding randomly, I deleted a lot of devices but the issue keeps on happening... [@fthiery](https://github.com/fthiery) did you fix it for good?

It does not happen anymore, but I'm not sure why not, I did these two things:
- I removed a router (smart plug) that was close to it but that had bad coverage (behind a dishwasher)
- I added a sonoff E flashed as repeater in the same room

I will re-add the smart plug to see if the repeater did the trick
