### ISSUE TITLE
z2m fails to start if attribute read timeout

### ISSUE THREAD

**Issue by tomaszduda23** [Koenkk/zigbee2mqtt#23879]
### What happened?

after https://github.com/Koenkk/zigbee-herdsman-converters/pull/7913 z2m sometimes fails to start if device is offline. 

```js
export async function getClusterAttributeValue<T>(endpoint: Zh.Endpoint, cluster: string, attribute: string, fallback: T = undefined)
```

there is fallback so I would expect that it is used if attribute cannot be read. Any idea how to handle that without removing reading of attribures?

### What did you expect to happen?

z2m should start even if device is offline.

### How to reproduce it (minimal and precise)

1. add genBinaryOutput device to z2m
2. power it off
3. restart z2m

### Zigbee2MQTT version

1.40.0

### Adapter firmware version

20230507

### Adapter

CC2652P

### Setup

docker arm64

### Debug log

```
genBinaryOutput.read(["description"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233))
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:482:23)
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:20)
    at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:82:20)
    at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:911:28)
    at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:443:29)
    at getClusterAttributeValue (/app/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:536:13)
    at Array.extenderBinaryOutput (/app/node_modules/zigbee-herdsman-converters/src/lib/generateDefinition.ts:365:19)
    at addGenerators (/app/node_modules/zigbee-herdsman-converters/src/lib/generateDefinition.ts:123:34)
    at generateDefinition (/app/node_modules/zigbee-herdsman-converters/src/lib/generateDefinition.ts:127:9)
    at findDefinition (/app/node_modules/zigbee-herdsman-converters/src/index.ts:354:35)
```

**Comment by Koenkk** [comment]
I still would expect z2m to start, but it may take longer indeed. Could you provide the debug log of this?

See [this](https://www.zigbee2mqtt.io/guide/configuration/logging.html) on how to enable debug logging.
