### ISSUE TITLE
Error when clicking the button - Loginovo ZG-101ZL

### ISSUE THREAD

**Issue by rursache** [Koenkk/zigbee2mqtt#23876]
### What happened?

**Zigbee Model** TS004F
**Zigbee Manufacturer** _TZ3000_ja5osu5g
**Manufacturer** Loginovo
**Model** ZG-101ZL

Every time I press the button, this error comes up. It works fine and it triggers my automations in HASS but it logs this error:
```
z2m: Failed to configure 'BUTTON_NAME', attempt 1 (Error: ZCL command 0xa4c138d47e3ef5e3/1 genBasic.read([4,0,1,5,7,65534], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:347:28) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:916:26) at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:443:29) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/moes.ts:548:13) at Configure.configure (/app/lib/extension/configure.ts:125:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
```

### What did you expect to happen?
 
Don't throw errors

### How to reproduce it (minimal and precise)

1. Link the button
2. Press it

### Zigbee2MQTT version

1.40.0 commit: 6fa1dab

### Adapter firmware version

20240710 and 20221226

### Adapter

Slaesh's CC2652RB

### Setup

Docker

### Debug log

```
error 2024-09-06 22:14:38z2m: Failed to configure 'BUTTON_NAME', attempt 1 (Error: ZCL command 0xa4c138d47e3ef5e3/1 genBasic.read([4,0,1,5,7,65534], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:347:28) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:916:26) at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:443:29) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/moes.ts:548:13) at Configure.configure (/app/lib/extension/configure.ts:125:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
error 2024-09-06 22:39:00z2m: Failed to configure 'BUTTON_NAME', attempt 2 (Error: ZCL command 0xa4c138d47e3ef5e3/1 genBasic.read([4,0,1,5,7,65534], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:347:28) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:916:26) at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:443:29) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/moes.ts:548:13) at Configure.configure (/app/lib/extension/configure.ts:125:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
error 2024-09-06 22:39:10z2m: Failed to configure 'BUTTON_NAME', attempt 3 (Error: ZCL command 0xa4c138d47e3ef5e3/1 genBasic.read([4,0,1,5,7,65534], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:347:28) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:916:26) at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:443:29) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/moes.ts:548:13) at Configure.configure (/app/lib/extension/configure.ts:125:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
```

**Comment by guillaumematheron** [comment]
I solved this by pressing the reset button next to the battery. Zigbee2mqtt indicated the device left the network, and after re-joining everything worked as before.

**Comment by kartone** [comment]
Same issue here. Actions and automations seem to work without issue but it's annoying seeing the error messages every now and then.

**Comment by numminorih-git** [comment]
+1 all is work but time to time (without button press) in log I see error: 	z2m: Failed to configure 'click_name', attempt 1
Zigbee2MQTT version [1.40.2]
Coordinator type zStack3x0
Coordinator revision 20240716

**Comment by rursache** [comment]
still not fixed.

**Comment by rursache** [comment]
still not fixed.

**Comment by numminorih-git** [comment]
version: 2.1.1-1 not fixed. Same issues.

**Comment by carlosnh96** [comment]
I have the same problem and it has not been solved with the latest versions.

**Comment by rursache** [comment]
not fixed

**Comment by Feriman22** [comment]
I have the exactly same issue.

Zigbee2MQTT version
[2.6.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/2.6.0)

Error message:

```
[2025-08-11 13:14:40] error: 	z2m: Failed to configure 'SmartButton', attempt 1 (Error: ZCL command 0xa4c1387b6eb59c7e/1 genOnOff.write({"tuyaOperationMode":1}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/.pnpm/zigbee-herdsman@5.0.4/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:372:28)
    at Endpoint.zclCommand (/app/node_modules/.pnpm/zigbee-herdsman@5.0.4/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:1005:26)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Endpoint.write (/app/node_modules/.pnpm/zigbee-herdsman@5.0.4/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:417:9)
    at Object.configure (/app/node_modules/.pnpm/zigbee-herdsman-converters@24.11.0/node_modules/zigbee-herdsman-converters/src/devices/moes.ts:767:13)
    at Configure.configure (/app/lib/extension/configure.ts:123:13)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:252:17))
```

Based on [this comment](https://github.com/Koenkk/zigbee2mqtt/issues/24013#issuecomment-2364601474), it should be fixed, but it's not.
