### ISSUE TITLE
OTA firmware update fails for LEDVANCE 4058075729322

### ISSUE THREAD

**Issue by 1Rolf** [Koenkk/zigbee2mqtt#23888]
### What happened?

I tried to update my Ledvance Plug but i get an Error (Size mismatch)
https://www.zigbee2mqtt.io/devices/4058075729322.html#ledvance-4058075729322

```
info 2024-09-07 15:01:21z2m: Updating 'ZB-ODPL-05 (POE-Tablet)' to latest firmware
info 2024-09-07 15:01:22z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/ZB-ODPL-05 (POE-Tablet)', payload '{"last_seen":1725714082023,"linkquality":204,"state":"OFF","update":{"installed_version":51263090,"latest_version":53163636,"state":"available"}}'
info 2024-09-07 15:01:22z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/ZB-ODPL-05 (POE-Tablet)', payload '{"last_seen":1725714082095,"linkquality":207,"state":"OFF","update":{"installed_version":51263090,"latest_version":53163636,"state":"available"}}'
info 2024-09-07 15:01:22z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"ZB-ODPL-05 (POE-Tablet)"},"error":"Update of 'ZB-ODPL-05 (POE-Tablet)' failed (Size mismatch)","status":"error","transaction":"ty3lv-3"}'
error 2024-09-07 15:01:22z2m: Update of 'ZB-ODPL-05 (POE-Tablet)' failed (Size mismatch)
```

### Zigbee2MQTT version

1.40.0 commit: 13084d22

### Adapter firmware version

20240710

### Adapter

Sonoff ZBDonlge-P

### Setup

Z2M plain on PiOS Lite x64, Pi4

### Debug log

```
[2024-09-07 15:01:21] debug:    z2m:mqtt: Received MQTT message on 'zigbee2mqtt/bridge/request/device/ota_update/update' with data '{"id":"ZB-ODPL-05 (POE-Tablet)","transaction":"ty3lv-3"}'
[2024-09-07 15:01:21] info:     z2m: Updating 'ZB-ODPL-05 (POE-Tablet)' to latest firmware
[2024-09-07 15:01:21] debug:    zh:controller:endpoint: ZCL command 0xf0d1b8be24083d3e/1 genBasic.read(["dateCode","swBuildId"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false,"sendPolicy":"immediate"})
[2024-09-07 15:01:21] debug:    zh:zstack: sendZclFrameToEndpointInternal 0xf0d1b8be24083d3e:59237/1 (0,0,1)
[2024-09-07 15:01:21] debug:    zh:zstack:znp: SREQ: --> AF - dataRequest - {"dstaddr":59237,"destendpoint":1,"srcendpoint":1,"clusterid":0,"transid":13,"options":0,"radius":30,"len":7,"data":{"type":"Buffer","data":[16,98,0,6,0,0,64]}}
[2024-09-07 15:01:21] debug:    zh:zstack:unpi:writer: --> frame [254,17,36,1,101,231,1,1,0,0,13,0,30,7,16,98,0,6,0,0,64,150]
[2024-09-07 15:01:21] debug:    zh:zstack:unpi:parser: <-- [254,1,100,1,0,100]
[2024-09-07 15:01:21] debug:    zh:zstack:unpi:parser: --- parseNext [254,1,100,1,0,100]
[2024-09-07 15:01:21] debug:    zh:zstack:unpi:parser: --> parsed 1 - 3 - 4 - 1 - [0] - 100
[2024-09-07 15:01:21] debug:    zh:zstack:znp: SRSP: <-- AF - dataRequest - {"status":0}
[2024-09-07 15:01:21] debug:    zh:zstack:unpi:parser: --- parseNext []
[2024-09-07 15:01:21] debug:    zh:zstack:unpi:parser: <-- [254,3,68,128,0,1,13,203]
[2024-09-07 15:01:21] debug:    zh:zstack:unpi:parser: --- parseNext [254,3,68,128,0,1,13,203]
[2024-09-07 15:01:21] debug:    zh:zstack:unpi:parser: --> parsed 3 - 2 - 4 - 128 - [0,1,13] - 203
[2024-09-07 15:01:21] debug:    zh:zstack:znp: AREQ: <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":13}
[2024-09-07 15:01:21] debug:    zh:zstack:unpi:parser: --- parseNext []
[2024-09-07 15:01:22] debug:    zh:zstack:unpi:parser: <-- [254,39,68,129,0,0,0,0,101,231,1,1,0,204,0,160,92,42,0,0,19,24,98,1,6,0,134,0,64,0,66,8,48,51,48,101,51,54,55,50,101,231,29,81]
[2024-09-07 15:01:22] debug:    zh:zstack:unpi:parser: --- parseNext [254,39,68,129,0,0,0,0,101,231,1,1,0,204,0,160,92,42,0,0,19,24,98,1,6,0,134,0,64,0,66,8,48,51,48,101,51,54,55,50,101,231,29,81]
[2024-09-07 15:01:22] debug:    zh:zstack:unpi:parser: --> parsed 39 - 2 - 4 - 129 - [0,0,0,0,101,231,1,1,0,204,0,160,92,42,0,0,19,24,98,1,6,0,134,0,64,0,66,8,48,51,48,101,51,54,55,50,101,231,29] - 81
[2024-09-07 15:01:22] debug:    zh:zstack:znp: AREQ: <-- AF - incomingMsg - {"groupid":0,"clusterid":0,"srcaddr":59237,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":204,"securityuse":0,"timestamp":2776224,"transseqnumber":0,"len":19,"data":{"type":"Buffer","data":[24,98,1,6,0,134,0,64,0,66,8,48,51,>
[2024-09-07 15:01:22] debug:    zh:controller: Received payload: clusterID=0, address=59237, groupID=0, endpoint=1, destinationEndpoint=1, wasBroadcast=false, linkQuality=204, frame={"header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"t>
[2024-09-07 15:01:22] debug:    zh:zstack:unpi:parser: --- parseNext []
[2024-09-07 15:01:22] debug:    z2m: Received Zigbee message from 'ZB-ODPL-05 (POE-Tablet)', type 'readResponse', cluster 'genBasic', data '{"swBuildId":"030e3672"}' from endpoint 1 with groupID 0
[2024-09-07 15:01:22] info:     z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/ZB-ODPL-05 (POE-Tablet)', payload '{"last_seen":1725714082023,"linkquality":204,"state":"OFF","update":{"installed_version":51263090,"latest_version":53163636,"state":"available"}}'
[2024-09-07 15:01:22] debug:    zh:controller:endpoint: Error: ZCL command 0xf0d1b8be24083d3e/1 genBasic.read(["dateCode","swBuildId"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false,"sendPolicy":"immediate"}) failed (>
    at Endpoint.checkStatus (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:347:28)
    at Endpoint.zclCommand (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:916:26)
    at Endpoint.read (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:443:29)
    at OTAUpdate.readSoftwareBuildIDAndDateCode (/opt/zigbee2mqtt/lib/extension/otaUpdate.ts:139:28)
    at OTAUpdate.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/otaUpdate.ts:267:35)
    at EventEmitter.wrappedCallback (/opt/zigbee2mqtt/lib/eventBus.ts:174:17)
[2024-09-07 15:01:22] debug:    zhc:ota:common: Updating '0xf0d1b8be24083d3e' (PLUG COMPACT EU T) to latest
[2024-09-07 15:01:22] debug:    zhc:ota:common: Using endpoint '1'
[2024-09-07 15:01:22] debug:    zh:controller:endpoint: CommandResponse 0xf0d1b8be24083d3e/1 genOta.imageNotify({"payloadType":0,"queryJitter":100}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"reservedBits":0,"writeUndiv":false,"sendPolicy":"immediat>
[2024-09-07 15:01:22] debug:    zh:zstack: sendZclFrameToEndpointInternal 0xf0d1b8be24083d3e:59237/1 (0,0,1)
[2024-09-07 15:01:22] debug:    zh:zstack:znp: SREQ: --> AF - dataRequest - {"dstaddr":59237,"destendpoint":1,"srcendpoint":1,"clusterid":25,"transid":14,"options":0,"radius":30,"len":5,"data":{"type":"Buffer","data":[25,99,0,0,100]}}
[2024-09-07 15:01:22] debug:    zh:zstack:unpi:writer: --> frame [254,15,36,1,101,231,1,1,25,0,14,0,30,5,25,99,0,0,100,186]
[2024-09-07 15:01:22] debug:    zh:zstack:unpi:parser: <-- [254,1,100,1,0,100]
[2024-09-07 15:01:22] debug:    zh:zstack:unpi:parser: --- parseNext [254,1,100,1,0,100]
[2024-09-07 15:01:22] debug:    zh:zstack:unpi:parser: --> parsed 1 - 3 - 4 - 1 - [0] - 100
[2024-09-07 15:01:22] debug:    zh:zstack:znp: SRSP: <-- AF - dataRequest - {"status":0}
[2024-09-07 15:01:22] debug:    zh:zstack:unpi:parser: --- parseNext []
[2024-09-07 15:01:22] debug:    zh:zstack:unpi:parser: <-- [254,3,68,128,0,1,14,200]
[2024-09-07 15:01:22] debug:    zh:zstack:unpi:parser: --- parseNext [254,3,68,128,0,1,14,200]
[2024-09-07 15:01:22] debug:    zh:zstack:unpi:parser: --> parsed 3 - 2 - 4 - 128 - [0,1,14] - 200
[2024-09-07 15:01:22] debug:    zh:zstack:znp: AREQ: <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":14}
[2024-09-07 15:01:22] debug:    zh:zstack:unpi:parser: --- parseNext []
[2024-09-07 15:01:22] debug:    zh:zstack:unpi:parser: <-- [254,32,68,129,0,0,25,0,101,231,1,1,0,207,0,39,111,42,0,0,12,1,17,1,0,137,17,214,0,114,54,14,3,101,231,29,86]
[2024-09-07 15:01:22] debug:    zh:zstack:unpi:parser: --- parseNext [254,32,68,129,0,0,25,0,101,231,1,1,0,207,0,39,111,42,0,0,12,1,17,1,0,137,17,214,0,114,54,14,3,101,231,29,86]
[2024-09-07 15:01:22] debug:    zh:zstack:unpi:parser: --> parsed 32 - 2 - 4 - 129 - [0,0,25,0,101,231,1,1,0,207,0,39,111,42,0,0,12,1,17,1,0,137,17,214,0,114,54,14,3,101,231,29] - 86
[2024-09-07 15:01:22] debug:    zh:zstack:znp: AREQ: <-- AF - incomingMsg - {"groupid":0,"clusterid":25,"srcaddr":59237,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":207,"securityuse":0,"timestamp":2780967,"transseqnumber":0,"len":12,"data":{"type":"Buffer","data":[1,17,1,0,137,17,214,0,114,54,14,3>
[2024-09-07 15:01:22] debug:    zh:controller: Received payload: clusterID=25, address=59237, groupID=0, endpoint=1, destinationEndpoint=1, wasBroadcast=false, linkQuality=207, frame={"header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":false,"reservedBits":0},>
[2024-09-07 15:01:22] debug:    zh:zstack:unpi:parser: --- parseNext []
[2024-09-07 15:01:22] debug:    z2m: Received Zigbee message from 'ZB-ODPL-05 (POE-Tablet)', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":51263090,"imageType":214,"manufacturerCode":4489}' from endpoint 1 with groupID 0
[2024-09-07 15:01:22] info:     z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/ZB-ODPL-05 (POE-Tablet)', payload '{"last_seen":1725714082095,"linkquality":207,"state":"OFF","update":{"installed_version":51263090,"latest_version":53163636,"state":"available"}}'
[2024-09-07 15:01:22] debug:    zhc:ota:common: Got request payload '{"fieldControl":0,"manufacturerCode":4489,"imageType":214,"fileVersion":51263090}'
[2024-09-07 15:01:22] debug:    zhc:ota:ledvance: Call getImageMeta for PLUG COMPACT EU T
[2024-09-07 15:01:22] debug:    zhc:ota:common: Getting new image for '0xf0d1b8be24083d3e' (PLUG COMPACT EU T), latest meta {"fileVersion":53163636,"fileSize":197136,"url":"https://api.update.ledvance.com/v1/zigbee/firmwares/download?company=4489&product=214&version=3.43.54.116","sha256":"3a22c73e82187b6c6697508366>
[2024-09-07 15:01:22] debug:    zhc:ota:common: Update checksum validation succeeded for '0xf0d1b8be24083d3e' (PLUG COMPACT EU T)
[2024-09-07 15:01:22] debug:    zhc:ota:common: Partially failed to parse the image, continuing anyway...
[2024-09-07 15:01:22] debug:    z2m: Update of 'ZB-ODPL-05 (POE-Tablet)' failed (AssertionError [ERR_ASSERTION]: Size mismatch)
[2024-09-07 15:01:22] info:     z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/ZB-ODPL-05 (POE-Tablet)', payload '{"last_seen":1725714082095,"linkquality":207,"state":"OFF","update":{"installed_version":51263090,"latest_version":53163636,"state":"available"}}'
[2024-09-07 15:01:22] info:     z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/update', payload '{"data":{"id":"ZB-ODPL-05 (POE-Tablet)"},"error":"Update of 'ZB-ODPL-05 (POE-Tablet)' failed (Size mismatch)","status":"error","transaction":"ty3lv-3"}'
[2024-09-07 15:01:22] error:    z2m: Update of 'ZB-ODPL-05 (POE-Tablet)' failed (Size mismatch)
[2024-09-07 15:01:22] debug:    z2m: AssertionError [ERR_ASSERTION]: Size mismatch
    at parseImage (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:282:11)
    at getNewImage (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:777:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.updateToLatest (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:571:19)
    at OTAUpdate.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/otaUpdate.ts:268:41)
    at EventEmitter.wrappedCallback (/opt/zigbee2mqtt/lib/eventBus.ts:174:17)
[2024-09-07 15:01:28] debug:    zh:zstack:unpi:parser: <-- [254,5,69,196,239,99,1,172,210,119]
[2024-09-07 15:01:28] debug:    zh:zstack:unpi:parser: --- parseNext [254,5,69,196,239,99,1,172,210,119]
[2024-09-07 15:01:28] debug:    zh:zstack:unpi:parser: --> parsed 5 - 2 - 5 - 196 - [239,99,1,172,210] - 119
[2024-09-07 15:01:28] debug:    zh:zstack:znp: AREQ: <-- ZDO - srcRtgInd - {"dstaddr":25583,"relaycount":1,"relaylist":[53932]}
[2024-09-07 15:01:28] debug:    zh:zstack:unpi:parser: --- parseNext []
[2024-09-07 15:01:29] debug:    zh:zstack:unpi:parser: <-- [254,32,68,129,0,0,25,0,239,99,1,13,0,91,0,173,15,49,0,0,12,17,68,1,0,134,18,5,8,9,16,0,0,172,210,28,14]
[2024-09-07 15:01:29] debug:    zh:zstack:unpi:parser: --- parseNext [254,32,68,129,0,0,25,0,239,99,1,13,0,91,0,173,15,49,0,0,12,17,68,1,0,134,18,5,8,9,16,0,0,172,210,28,14]
[2024-09-07 15:01:29] debug:    zh:zstack:unpi:parser: --> parsed 32 - 2 - 4 - 129 - [0,0,25,0,239,99,1,13,0,91,0,173,15,49,0,0,12,17,68,1,0,134,18,5,8,9,16,0,0,172,210,28] - 14
[2024-09-07 15:01:29] debug:    zh:zstack:znp: AREQ: <-- AF - incomingMsg - {"groupid":0,"clusterid":25,"srcaddr":25583,"srcendpoint":1,"dstendpoint":13,"wasbroadcast":0,"linkquality":91,"securityuse":0,"timestamp":3215277,"transseqnumber":0,"len":12,"data":{"type":"Buffer","data":[17,68,1,0,134,18,5,8,9,16,0,0]}}
[2024-09-07 15:01:29] debug:    zh:controller: Received payload: clusterID=25, address=25583, groupID=0, endpoint=1, destinationEndpoint=13, wasBroadcast=false, linkQuality=91, frame={"header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":true,"reservedBits":0},">
[2024-09-07 15:01:29] debug:    zh:zstack:unpi:parser: --- parseNext []


```

**Comment by Koenkk** [comment]
Should be fixed in 1.40.1
