### ISSUE TITLE
ZIgbee2MQTT not starting beacause of Home Assistant

### ISSUE THREAD

**Issue by louanrobert** [Koenkk/zigbee2mqtt#23950]
### What happened?

Z2M not starting because of HA

### What did you expect to happen?

Z2M to start

### How to reproduce it (minimal and precise)

1. setup Z2M with home assistant discovery
2. start Z2M
3. disable home assistant discovery in Z2M config
4. start Z2M : Z2M is starting

### Zigbee2MQTT version

 1.37.1

### Adapter firmware version

 7.4.3 [GA]

### Adapter

 EmberZNet

### Setup

Running on an LXC container

### Log file :
[log.log](https://github.com/user-attachments/files/16981667/log.log)

### Console output : 
```/usr/lib/zigbee2mqtt/node_modules/unix-dgram/lib/unix_dgram.js:23
  var e = new Error(syscall + ' ' + errorno);
          ^
Error: send -11
    at errnoException (/usr/lib/zigbee2mqtt/node_modules/unix-dgram/lib/unix_dgram.js:23:11)
    at Socket.send (/usr/lib/zigbee2mqtt/node_modules/unix-dgram/lib/unix_dgram.js:106:16)
    at sendDgram (/usr/lib/zigbee2mqtt/node_modules/winston-syslog/lib/winston-syslog.js:249:23)
    at /usr/lib/zigbee2mqtt/node_modules/winston-syslog/lib/winston-syslog.js:266:9
    at Syslog.connect (/usr/lib/zigbee2mqtt/node_modules/winston-syslog/lib/winston-syslog.js:344:11)
    at Syslog.log (/usr/lib/zigbee2mqtt/node_modules/winston-syslog/lib/winston-syslog.js:216:10)
    at Syslog._write (/usr/lib/zigbee2mqtt/node_modules/winston-transport/modern.js:103:17)
    at doWrite (/usr/lib/zigbee2mqtt/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:390:139)
    at writeOrBuffer (/usr/lib/zigbee2mqtt/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:381:5)
    at Syslog.Writable.write (/usr/lib/zigbee2mqtt/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:302:11)```

**Comment by Irix0** [comment]
Update: seems like stopping HA before starting Z2M and then starting HA works. Will see if it works in the long term.
