### ISSUE TITLE
Blinds get unresponsive

### ISSUE THREAD

**Issue by vascozorrinho** [Koenkk/zigbee2mqtt#23999]
### What happened?

Since a few weeks back one of my blinds cover (lonsonho based on the Tuya TS130F module and named "Switch/LivingRoom/BlindsRight") started to get unresponsive. Can't control it via HA or even from the blind's from que cover buttons. Some reboots or re-pairs seam to work for a couple of days.

### What did you expect to happen?

Blinds should oper or close when I send the command either via the UI or automation.

### How to reproduce it (minimal and precise)

It just happens every few days.

### Zigbee2MQTT version

1.40.1 commit: unknown

### Adapter firmware version

Tried with 20230507 and 20240710

### Adapter

Sonoff Dongle-P

### Setup

HAOS on a RP4 

### Debug log

Starting Zigbee2MQTT without watchdog.
[2024-09-17 07:47:29] error: 	z2m: Failed to configure 'Switch/Kitchen/2gangBottom', attempt 1 (Error: ZCL command 0x84fd27fffee27953/1 genOnOff.configReport([{"minimumReportInterval":0,"maximumReportInterval":65000,"reportableChange":1,"attribute":"onOff"}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Timeout - 58201 - 1 - 9 - 6 - 7 after 10000ms)
    at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23)
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:598:47)
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:20)
    at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:82:20)
    at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:911:28)
    at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:648:9)
    at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:110:13)
    at result.configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:486:17)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:193:21)
    at Configure.configure (/app/lib/extension/configure.ts:125:13))
[2024-09-17 07:48:19] error: 	z2m: Failed to configure 'Switch/SuiteBathroom/Fan', attempt 1 (Error: Device 0x804b50fffe584b82 has no input cluster genOnOff
    at getEndpointsWithCluster (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:60:15)
    at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:101:55)
    at result.configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:486:23)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:193:27)
    at Configure.configure (/app/lib/extension/configure.ts:125:37)
    at Immediate.<anonymous> (/app/lib/extension/configure.ts:74:28))
[2024-09-17 07:48:20] error: 	z2m: Publish 'set' 'state' to 'Switch/LivingRoom/BlindsRight' failed: 'Error: ZCL command 0x84fd27fffe60db7e/1 closuresWindowCovering.upOpen({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-09-17 07:48:45] error: 	z2m: Publish 'set' 'state' to 'Switch/LivingRoom/BlindsRight' failed: 'Error: ZCL command 0x84fd27fffe60db7e/1 closuresWindowCovering.stop({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-09-17 07:49:10] error: 	z2m: Publish 'set' 'state' to 'Switch/LivingRoom/BlindsRight' failed: 'Error: ZCL command 0x84fd27fffe60db7e/1 closuresWindowCovering.upOpen({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-09-17 07:49:34] error: 	z2m: Publish 'set' 'state' to 'Switch/LivingRoom/BlindsRight' failed: 'Error: ZCL command 0x84fd27fffe60db7e/1 closuresWindowCovering.upOpen({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-09-17 07:53:31] error: 	z2m: Publish 'set' 'state' to 'Switch/LivingRoom/BlindsRight' failed: 'Error: ZCL command 0x84fd27fffe60db7e/1 closuresWindowCovering.upOpen({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-09-17 08:12:39] error: 	z2m: Failed to configure 'Switch/SuiteBathroom/Fan', attempt 2 (Error: Device 0x804b50fffe584b82 has no input cluster genOnOff
    at getEndpointsWithCluster (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:60:15)
    at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:101:55)
    at result.configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:486:23)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:193:27)
    at Configure.configure (/app/lib/extension/configure.ts:125:37)
    at /app/lib/extension/configure.ts:87:62
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:23)
    at EventEmitter.emit (node:events:529:35)
    at EventBus.emitLastSeenChanged (/app/lib/eventBus.ts:52:22)
    at Controller.<anonymous> (/app/lib/zigbee.ts:76:27))
[2024-09-17 08:19:21] error: 	z2m: Failed to configure 'Switch/Kitchen/2gangBottom', attempt 2 (Error: ZCL command 0x84fd27fffee27953/1 genOnOff.configReport([{"minimumReportInterval":0,"maximumReportInterval":65000,"reportableChange":1,"attribute":"onOff"}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Timeout - 58201 - 1 - 47 - 6 - 7 after 10000ms)
    at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23)
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:598:47)
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:20)
    at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:82:20)
    at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:911:28)
    at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:648:9)
    at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:110:13)
    at result.configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:486:17)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:193:21)
    at Configure.configure (/app/lib/extension/configure.ts:125:13))
[2024-09-17 08:25:33] error: 	z2m: Publish 'set' 'state' to 'Switch/LivingRoom/BlindsRight' failed: 'Error: ZCL command 0x84fd27fffe60db7e/1 closuresWindowCovering.upOpen({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
[2024-09-17 08:36:52] info: 	z2m: Successfully changed options
[2024-09-17 08:36:52] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/options', payload '{"data":{"restart_required":false},"status":"ok","transaction":"tk3cy-1"}'
[2024-09-17 08:36:53] debug: 	zh:zstack:unpi:parser: <-- [254,3,69,196,118,164,0,80,254,32,68,129,0,0,25,0,118,164,11,1,0,18,0,212,222,10,0,0,12,1,189,1,0,79,18,38,20,1,48,1,34,118,164,29,53]
[2024-09-17 08:36:53] debug: 	zh:zstack:unpi:parser: --- parseNext [254,3,69,196,118,164,0,80,254,32,68,129,0,0,25,0,118,164,11,1,0,18,0,212,222,10,0,0,12,1,189,1,0,79,18,38,20,1,48,1,34,118,164,29,53]
[2024-09-17 08:36:53] debug: 	zh:zstack:unpi:parser: --> parsed 3 - 2 - 5 - 196 - [118,164,0] - 80
[2024-09-17 08:36:53] debug: 	zh:zstack:znp: AREQ: <-- ZDO - srcRtgInd - {"dstaddr":42102,"relaycount":0,"relaylist":[]}
[2024-09-17 08:36:53] debug: 	zh:zstack:unpi:parser: --- parseNext [254,32,68,129,0,0,25,0,118,164,11,1,0,18,0,212,222,10,0,0,12,1,189,1,0,79,18,38,20,1,48,1,34,118,164,29,53]
[2024-09-17 08:36:53] debug: 	zh:zstack:unpi:parser: --> parsed 32 - 2 - 4 - 129 - [0,0,25,0,118,164,11,1,0,18,0,212,222,10,0,0,12,1,189,1,0,79,18,38,20,1,48,1,34,118,164,29] - 53
[2024-09-17 08:36:53] debug: 	zh:zstack:znp: AREQ: <-- AF - incomingMsg - {"groupid":0,"clusterid":25,"srcaddr":42102,"srcendpoint":11,"dstendpoint":1,"wasbroadcast":0,"linkquality":18,"securityuse":0,"timestamp":712404,"transseqnumber":0,"len":12,"data":{"type":"Buffer","data":[1,189,1,0,79,18,38,20,1,48,1,34]}}
[2024-09-17 08:36:53] debug: 	zh:controller: Received payload: clusterID=25, address=42102, groupID=0, endpoint=11, destinationEndpoint=1, wasBroadcast=false, linkQuality=18, frame={"header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":false,"reservedBits":0},"transactionSequenceNumber":189,"commandIdentifier":1},"payload":{"fieldControl":0,"manufacturerCode":4687,"imageType":5158,"fileVersion":570503169},"command":{"ID":1,"response":2,"parameters":[{"name":"fieldControl","type":32},{"name":"manufacturerCode","type":33},{"name":"imageType","type":33},{"name":"fileVersion","type":35}],"name":"queryNextImageRequest"}}
[2024-09-17 08:36:53] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-09-17 08:36:53] debug: 	z2m: Received Zigbee message from 'Light/Office/CeilingLightTwo', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":570503169,"imageType":5158,"manufacturerCode":4687}' from endpoint 11 with groupID 0
[2024-09-17 08:36:53] debug: 	z2m: Device 'Light/Office/CeilingLightTwo' requested OTA
[2024-09-17 08:36:53] debug: 	zh:controller:endpoint: CommandResponse 0xa4c138b78730a9ed/11 genOta.queryNextImageResponse({"status":152}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"reservedBits":0,"writeUndiv":false})
[2024-09-17 08:36:53] debug: 	zh:zstack: sendZclFrameToEndpointInternal 0xa4c138b78730a9ed:42102/11 (0,0,1)
[2024-09-17 08:36:53] debug: 	zh:zstack:znp: SREQ: --> AF - dataRequest - {"dstaddr":42102,"destendpoint":11,"srcendpoint":1,"clusterid":25,"transid":136,"options":0,"radius":30,"len":4,"data":{"type":"Buffer","data":[25,189,2,152]}}
[2024-09-17 08:36:53] debug: 	zh:zstack:unpi:writer: --> frame [254,14,36,1,118,164,11,1,25,0,136,0,30,4,25,189,2,152,70]
[2024-09-17 08:36:53] debug: 	zh:zstack:unpi:parser: <-- [254,1,100,1,0,100]
[2024-09-17 08:36:53] debug: 	zh:zstack:unpi:parser: --- parseNext [254,1,100,1,0,100]
[2024-09-17 08:36:53] debug: 	zh:zstack:unpi:parser: --> parsed 1 - 3 - 4 - 1 - [0] - 100
[2024-09-17 08:36:53] debug: 	zh:zstack:znp: SRSP: <-- AF - dataRequest - {"status":0}
[2024-09-17 08:36:53] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-09-17 08:36:53] debug: 	zh:zstack:unpi:parser: <-- [254,3,68,128,0,1,136,78]
[2024-09-17 08:36:53] debug: 	zh:zstack:unpi:parser: --- parseNext [254,3,68,128,0,1,136,78]
[2024-09-17 08:36:53] debug: 	zh:zstack:unpi:parser: --> parsed 3 - 2 - 4 - 128 - [0,1,136] - 78
[2024-09-17 08:36:53] debug: 	zh:zstack:znp: AREQ: <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":136}
[2024-09-17 08:36:53] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-09-17 08:36:53] debug: 	z2m: Responded to OTA request of 'Light/Office/CeilingLightTwo' with 'NO_IMAGE_AVAILABLE'
[2024-09-17 08:36:55] debug: 	zh:zstack:unpi:parser: <-- [254,3,69,196,182,38,0,18,254,32,68,129,0,0,25,0,182,38,11,1,0,83,0,158,149,12,0,0,12,1,250,1,0,79,18,50,20,1,48,1,32,182,38,29,34]
[2024-09-17 08:36:55] debug: 	zh:zstack:unpi:parser: --- parseNext [254,3,69,196,182,38,0,18,254,32,68,129,0,0,25,0,182,38,11,1,0,83,0,158,149,12,0,0,12,1,250,1,0,79,18,50,20,1,48,1,32,182,38,29,34]
[2024-09-17 08:36:55] debug: 	zh:zstack:unpi:parser: --> parsed 3 - 2 - 5 - 196 - [182,38,0] - 18
[2024-09-17 08:36:55] debug: 	zh:zstack:znp: AREQ: <-- ZDO - srcRtgInd - {"dstaddr":9910,"relaycount":0,"relaylist":[]}
[2024-09-17 08:36:55] debug: 	zh:zstack:unpi:parser: --- parseNext [254,32,68,129,0,0,25,0,182,38,11,1,0,83,0,158,149,12,0,0,12,1,250,1,0,79,18,50,20,1,48,1,32,182,38,29,34]
[2024-09-17 08:36:55] debug: 	zh:zstack:unpi:parser: --> parsed 32 - 2 - 4 - 129 - [0,0,25,0,182,38,11,1,0,83,0,158,149,12,0,0,12,1,250,1,0,79,18,50,20,1,48,1,32,182,38,29] - 34
[2024-09-17 08:36:55] debug: 	zh:zstack:znp: AREQ: <-- AF - incomingMsg - {"groupid":0,"clusterid":25,"srcaddr":9910,"srcendpoint":11,"dstendpoint":1,"wasbroadcast":0,"linkquality":83,"securityuse":0,"timestamp":824734,"transseqnumber":0,"len":12,"data":{"type":"Buffer","data":[1,250,1,0,79,18,50,20,1,48,1,32]}}
[2024-09-17 08:36:55] debug: 	zh:controller: Received payload: clusterID=25, address=9910, groupID=0, endpoint=11, destinationEndpoint=1, wasBroadcast=false, linkQuality=83, frame={"header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":false,"reservedBits":0},"transactionSequenceNumber":250,"commandIdentifier":1},"payload":{"fieldControl":0,"manufacturerCode":4687,"imageType":5170,"fileVersion":536948737},"command":{"ID":1,"response":2,"parameters":[{"name":"fieldControl","type":32},{"name":"manufacturerCode","type":33},{"name":"imageType","type":33},{"name":"fileVersion","type":35}],"name":"queryNextImageRequest"}}
[2024-09-17 08:36:55] debug: 	zh:zstack:unpi:parser: --- parseNext []
[2024-09-17 08:36:55] debug: 	z2m: Received Zigbee message from 'Light/BedroomEntranceHall/Two', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":536948737,"imageType":5170,"manufacturerCode":4687}' from endpoint 11 with groupID 0
[2024-09-17 08:36:55] debug: 	z2m: Device 'Light/BedroomEntranceHall/Two' requested OTA

**Comment by alikhanich** [comment]
@vascozorrinho have you solved that?
