### ISSUE TITLE
problem with third reality smart button 3RSB22BZ after OTA firmware update

### ISSUE THREAD

**Issue by materoxxx** [Koenkk/zigbee2mqtt#24038]
### What happened?

I update via OTA page my smart button Third reality 3RSB22BZ to the latest firmware version V1.00.35 from the previous 1.00.28 and the device is recognized correctly but the action button reports no change if I press it, only "null" . the device is connected and the "last seen" updates when I press the button but it should report 3 types of button press like it did before the update. 
I tried restarting everything, repairing the device, factory rest the device etc...no luck

### What did you expect to happen?

to work as before

### How to reproduce it (minimal and precise)

just update the smart button firmware

### Zigbee2MQTT version

 1.40.1 commit: 403d3c0

### Adapter firmware version

7.4.4 [GA]

### Adapter

dongle E ember firmware latest

### Setup

z2m in docker container connects to home assistant in another container ( machine is a minipc with OpenMediavault on it 

### Debug log

 error 2024-09-20 15:54:25z2m: Failed to configure 'pulsante cucina', attempt 2 (Error: ZCL command 0x282c02bfffee04f4/1 genPowerCfg.read(["batteryPercentageRemaining"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Delivery failed for {"profileId":260,"clusterId":1,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":210}) at EmberOneWaitress.deliveryFailedFor (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/oneWaitress.ts:101:31) at EmberAdapter.onMessageSent (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:480:42) at Ezsp.emit (node:events:517:28) at Ezsp.ezspMessageSentHandler (/app/node_modules/zigbee-herdsman/src/adapter/ember/ezsp/ezsp.ts:4982:14) at Ezsp.callbackDispatch (/app/node_modules/zigbee-herdsman/src/adapter/ember/ezsp/ezsp.ts:738:26) at Ezsp.onAshFrame (/app/node_modules/zigbee-herdsman/src/adapter/ember/ezsp/ezsp.ts:398:22) at UartAsh.emit (node:events:517:28) at Immediate.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/ember/uart/ash.ts:1169:45) at processImmediate (node:internal/timers:476:21))

**Comment by materoxxx** [comment]
error 2024-09-20 15:54:25z2m: Failed to configure 'pulsante cucina', attempt 2 (Error: ZCL command 0x282c02bfffee04f4/1 genPowerCfg.read(["batteryPercentageRemaining"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Delivery failed for {"profileId":260,"clusterId":1,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":210}) at EmberOneWaitress.deliveryFailedFor (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/oneWaitress.ts:101:31) at EmberAdapter.onMessageSent (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:480:42) at Ezsp.emit (node:events:517:28) at Ezsp.ezspMessageSentHandler (/app/node_modules/zigbee-herdsman/src/adapter/ember/ezsp/ezsp.ts:4982:14) at Ezsp.callbackDispatch (/app/node_modules/zigbee-herdsman/src/adapter/ember/ezsp/ezsp.ts:738:26) at Ezsp.onAshFrame (/app/node_modules/zigbee-herdsman/src/adapter/ember/ezsp/ezsp.ts:398:22) at UartAsh.emit (node:events:517:28) at Immediate.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/ember/uart/ash.ts:1169:45) at processImmediate (node:internal/timers:476:21))

**Comment by materoxxx** [comment]
For me the preoblem was the zigbee pairing mode. If you look for the manual of the button, there are 2 different zigbee pairing mode, I had accidentally changed into one that wasn't compatible. In the manual is explained how to change mode but I don't have it handy at the moment, you need to set it in normal zigbee before pairing it. I hoope it helps
