### ISSUE TITLE
[New device support]: EcoDin 0.7

### ISSUE THREAD

**Issue by jeremybreeschoten** [Koenkk/zigbee2mqtt#24104]
### Link

https://www.zigbee2mqtt.io/devices/Eco-Dim.07_Eco-Dim.10.html

### Database entry

{"id":27,"type":"Unknown","ieeeAddr":"0x881a14fffed2ea3d","nwkAddr":3087,"epList":[],"endpoints":{},"interviewCompleted":false,"meta":{},"lastSeen":1727284832638}

### Zigbee2MQTT version

1.40.1 commit: unknown

### Comments

I tried resetting <5 times and even pairing again. Always fails. Different restarts of HA

### External definition

```shell
ypeError
Cannot read properties of undefined (reading 'clusters')
TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (https://9lm9xsu2mzoqcbsstu19cxe2dbkin9yu.ui.nabu.casa/api/hassio_ingress/eKUxljdyXdTIZG7bVWaNRAvdVfE0PAyGryTVMYkYVb4/assets/ConnectedDevicePage-792280da.js:1:31105)
    at ab (https://9lm9xsu2mzoqcbsstu19cxe2dbkin9yu.ui.nabu.casa/api/hassio_ingress/eKUxljdyXdTIZG7bVWaNRAvdVfE0PAyGryTVMYkYVb4/assets/index-74e84a13.js:43:6186)
    at yD (https://9lm9xsu2mzoqcbsstu19cxe2dbkin9yu.ui.nabu.casa/api/hassio_ingress/eKUxljdyXdTIZG7bVWaNRAvdVfE0PAyGryTVMYkYVb4/assets/index-74e84a13.js:43:5982)
    at r3 (https://9lm9xsu2mzoqcbsstu19cxe2dbkin9yu.ui.nabu.casa/api/hassio_ingress/eKUxljdyXdTIZG7bVWaNRAvdVfE0PAyGryTVMYkYVb4/assets/index-74e84a13.js:43:44865)
    at e3 (https://9lm9xsu2mzoqcbsstu19cxe2dbkin9yu.ui.nabu.casa/api/hassio_ingress/eKUxljdyXdTIZG7bVWaNRAvdVfE0PAyGryTVMYkYVb4/assets/index-74e84a13.js:43:39756)
    at ISe (https://9lm9xsu2mzoqcbsstu19cxe2dbkin9yu.ui.nabu.casa/api/hassio_ingress/eKUxljdyXdTIZG7bVWaNRAvdVfE0PAyGryTVMYkYVb4/assets/index-74e84a13.js:43:39682)
    at ap (https://9lm9xsu2mzoqcbsstu19cxe2dbkin9yu.ui.nabu.casa/api/hassio_ingress/eKUxljdyXdTIZG7bVWaNRAvdVfE0PAyGryTVMYkYVb4/assets/index-74e84a13.js:43:39534)
    at cb (https://9lm9xsu2mzoqcbsstu19cxe2dbkin9yu.ui.nabu.casa/api/hassio_ingress/eKUxljdyXdTIZG7bVWaNRAvdVfE0PAyGryTVMYkYVb4/assets/index-74e84a13.js:43:35900)
    at CD (https://9lm9xsu2mzoqcbsstu19cxe2dbkin9yu.ui.nabu.casa/api/hassio_ingress/eKUxljdyXdTIZG7bVWaNRAvdVfE0PAyGryTVMYkYVb4/assets/index-74e84a13.js:43:36704)
    at Gn (https://9lm9xsu2mzoqcbsstu19cxe2dbkin9yu.ui.nabu.casa/api/hassio_ingress/eKUxljdyXdTIZG7bVWaNRAvdVfE0PAyGryTVMYkYVb4/assets/index-74e84a13.js:41:3283)
```

### What does/doesn't work with the external definition?

-

**Comment by jeremybreeschoten** [comment]
i think because it is the Ecodin.07 Basic. THere is no difference between the pro and basic. Only the voltage

**Comment by jeremybreeschoten** [comment]
Hello,

is there someone who can have a look? @Koenkk for example? I think the whole config is the same as the prof. But not recognised

**Comment by jeremybreeschoten** [comment]
Hello team, 3 months later and no reponds?
