### ISSUE TITLE
z2m: Error while starting zigbee-herdsman

### ISSUE THREAD

**Issue by WodkaExpress** [Koenkk/zigbee2mqtt#24112]
### What happened?

**Hello my english is not the best. SRY
I suddenly after update had an issue. 
My Sonoff Zigbee 3.0 does´t start with Zigbee2MQTT. 
I had this issue "z2m: Error while starting zigbee-herdsman".
I updatet my Sonoff to the news software. 
Then i startet Zigbee2MQTT again an this happens.** 

"[2024-09-26 20:42:05] info: 	z2m: Logging to console, file (filename: log.log)
[2024-09-26 20:42:05] info: 	z2m: Starting Zigbee2MQTT version 1.40.1 (commit #unknown)
[2024-09-26 20:42:05] info: 	z2m: Starting zigbee-herdsman (0.57.3)
[2024-09-26 20:42:06] info: 	zh:ember: Using default stack config.
[2024-09-26 20:42:06] info: 	zh:ember: ======== Ember Adapter Starting ========
[2024-09-26 20:42:06] info: 	zh:ember:ezsp: ======== EZSP starting ========
[2024-09-26 20:42:06] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2024-09-26 20:42:06] info: 	zh:ember:uart:ash: RTS/CTS config is off, enabling software flow control.
[2024-09-26 20:42:06] info: 	zh:ember:uart:ash: Serial port opened
[2024-09-26 20:42:06] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-09-26 20:42:07] info: 	zh:ember:uart:ash: ======== ASH connected ========
[2024-09-26 20:42:07] info: 	zh:ember:uart:ash: ======== ASH started ========
[2024-09-26 20:42:07] info: 	zh:ember:ezsp: ======== EZSP started ========
[2024-09-26 20:42:07] info: 	zh:ember: Adapter EZSP protocol version (13) lower than Host. Switched.
[2024-09-26 20:42:07] info: 	zh:ember: Adapter version info: {"ezsp":13,"revision":"7.4.4 [GA]","build":0,"major":7,"minor":4,"patch":4,"special":0,"type":170}
[2024-09-26 20:42:07] info: 	zh:ember: [STACK STATUS] Network up.
[2024-09-26 20:42:07] info: 	zh:ember: [INIT TC] Adapter network does not match config. Leaving network...
[2024-09-26 20:42:08] info: 	zh:ember: [STACK STATUS] Network down.
[2024-09-26 20:42:09] info: 	zh:ember: [INIT TC] No valid backup found.
[2024-09-26 20:42:09] info: 	zh:ember: [INIT TC] Forming from config.
[2024-09-26 20:42:09] info: 	zh:ember: [INIT FORM] Forming new network with: {"panId":43011,"extendedPanId":[48,129,139,199,4,168,109,211],"radioTxPower":5,"radioChannel":11,"joinMethod":0,"nwkManagerId":0,"nwkUpdateId":0,"channels":134215680}
[2024-09-26 20:42:09] info: 	zh:ember: [STACK STATUS] Network up.
[2024-09-26 20:42:09] info: 	zh:ember: [INIT FORM] New network formed!
[2024-09-26 20:42:09] info: 	zh:ember: [CONCENTRATOR] Started source route discovery. 1248ms until next broadcast.
[2024-09-26 20:42:09] info: 	zh:controller: Wrote coordinator backup to '/config/zigbee2mqtt/coordinator_backup.json'
[2024-09-26 20:42:09] info: 	z2m: zigbee-herdsman started (reset)
[2024-09-26 20:42:09] info: 	z2m: Coordinator firmware version: '{"meta":{"build":0,"ezsp":13,"major":7,"minor":4,"patch":4,"revision":"7.4.4 [GA]","special":0,"type":170},"type":"EmberZNet"}'
[2024-09-26 20:42:09] info: 	z2m: Currently 0 devices are joined.
[2024-09-26 20:42:09] info: 	z2m: Zigbee: disabling joining new devices.
[2024-09-26 20:42:10] info: 	z2m: Connecting to MQTT server at mqtt://core-mosquitto:1883
[2024-09-26 20:42:10] info: 	z2m: Connected to MQTT server
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"online"}'
[2024-09-26 20:42:10] info: 	z2m: Started frontend on port 8099
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"online"}'
[2024-09-26 20:42:10] info: 	z2m: Zigbee2MQTT started!
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/binary_sensor/0x00124b002894326c/contact/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/binary_sensor/0x00124b002894326c/battery_low/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/binary_sensor/0x00124b00291a09ee/occupancy/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/binary_sensor/0x00124b00291a09ee/battery_low/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/binary_sensor/0x00124b00288fd974/occupancy/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/binary_sensor/0x00124b00288fd974/battery_low/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/binary_sensor/0x00124b002919c18c/occupancy/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/binary_sensor/0x00124b002919c18c/battery_low/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/binary_sensor/0x00124b002894335e/contact/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/binary_sensor/0x00124b002894335e/battery_low/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/binary_sensor/0x00124b002894331e/contact/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/binary_sensor/0x00124b002894331e/battery_low/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/binary_sensor/0xb43522fffe52d79d/update_available/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/binary_sensor/0x84ba20fffe623fbb/update_available/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/button/0xb43522fffe52d79d/identify/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/button/0x84ba20fffe623fbb/identify/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/select/0xb43522fffe52d79d/identify/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/select/0x84ba20fffe623fbb/identify/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b002894326c/battery/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b002894326c/voltage/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b002894326c/linkquality/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b00291a09ee/battery/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b00291a09ee/voltage/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b00291a09ee/linkquality/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b00288fd974/battery/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b00288fd974/voltage/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b00288fd974/linkquality/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b002919c18c/battery/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b002919c18c/voltage/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b002919c18c/linkquality/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b002894335e/battery/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b002894335e/voltage/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b002894335e/linkquality/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b0029193859/battery/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b0029193859/temperature/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b0029193859/humidity/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b0029193859/voltage/config', payload 'null'
[2024-09-26 20:42:10] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b0029193859/linkquality/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b002894331e/battery/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b002894331e/voltage/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x00124b002894331e/linkquality/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0xb43522fffe52d79d/linkquality/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0xb43522fffe52d79d/update_state/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x84ba20fffe623fbb/battery/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x84ba20fffe623fbb/action/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x84ba20fffe623fbb/linkquality/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/0x84ba20fffe623fbb/update_state/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/update/0xb43522fffe52d79d/update/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/update/0x84ba20fffe623fbb/update/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/device_automation/0x84ba20fffe623fbb/action_brightness_move_down/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/device_automation/0x84ba20fffe623fbb/action_brightness_stop/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/device_automation/0x84ba20fffe623fbb/action_off/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/device_automation/0x84ba20fffe623fbb/action_arrow_right_click/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/device_automation/0x84ba20fffe623fbb/action_on/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/device_automation/0x84ba20fffe623fbb/action_arrow_left_click/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/device_automation/0x84ba20fffe623fbb/action_arrow_left_hold/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/device_automation/0x84ba20fffe623fbb/action_arrow_left_release/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/device_automation/0x84ba20fffe623fbb/action_brightness_move_up/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/device_automation/0x84ba20fffe623fbb/action_arrow_right_hold/config', payload 'null'
[2024-09-26 20:42:11] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/device_automation/0x84ba20fffe623fbb/action_arrow_right_release/config', payload 'null'
[2024-09-26 20:42:15] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/binary_sensor/1221051039810110150109113116116_0xdc8e95fffe25801a/connection_state/config', payload '{"device":{"hw_version":"EmberZNet 7.4.4 [GA]","identifiers":["zigbee2mqtt_bridge_0xdc8e95fffe25801a"],"manufacturer":"Zigbee2MQTT","model":"Bridge","name":"Zigbee2MQTT Bridge","sw_version":"1.40.1"},"device_class":"connectivity","entity_category":"diagnostic","name":"Connection state","object_id":"zigbee2mqtt_bridge_connection_state","origin":{"name":"Zigbee2MQTT","sw":"1.40.1","url":"https://www.zigbee2mqtt.io"},"payload_off":"offline","payload_on":"online","state_topic":"zigbee2mqtt/bridge/state","unique_id":"bridge_0xdc8e95fffe25801a_connection_state_zigbee2mqtt","value_template":"{{ value_json.state }}"}'
[2024-09-26 20:42:15] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/binary_sensor/1221051039810110150109113116116_0xdc8e95fffe25801a/restart_required/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"availability_mode":"all","device":{"hw_version":"EmberZNet 7.4.4 [GA]","identifiers":["zigbee2mqtt_bridge_0xdc8e95fffe25801a"],"manufacturer":"Zigbee2MQTT","model":"Bridge","name":"Zigbee2MQTT Bridge","sw_version":"1.40.1"},"device_class":"problem","enabled_by_default":false,"entity_category":"diagnostic","name":"Restart required","object_id":"zigbee2mqtt_bridge_restart_required","origin":{"name":"Zigbee2MQTT","sw":"1.40.1","url":"https://www.zigbee2mqtt.io"},"payload_off":false,"payload_on":true,"state_topic":"zigbee2mqtt/bridge/info","unique_id":"bridge_0xdc8e95fffe25801a_restart_required_zigbee2mqtt","value_template":"{{ value_json.restart_required }}"}'
[2024-09-26 20:42:15] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/button/1221051039810110150109113116116_0xdc8e95fffe25801a/restart/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"availability_mode":"all","command_topic":"zigbee2mqtt/bridge/request/restart","device":{"hw_version":"EmberZNet 7.4.4 [GA]","identifiers":["zigbee2mqtt_bridge_0xdc8e95fffe25801a"],"manufacturer":"Zigbee2MQTT","model":"Bridge","name":"Zigbee2MQTT Bridge","sw_version":"1.40.1"},"device_class":"restart","name":"Restart","object_id":"zigbee2mqtt_bridge_restart","origin":{"name":"Zigbee2MQTT","sw":"1.40.1","url":"https://www.zigbee2mqtt.io"},"payload_press":"","unique_id":"bridge_0xdc8e95fffe25801a_restart_zigbee2mqtt"}'
[2024-09-26 20:42:15] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/select/1221051039810110150109113116116_0xdc8e95fffe25801a/log_level/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"availability_mode":"all","command_template":"{\"options\": {\"advanced\": {\"log_level\": \"{{ value }}\" } } }","command_topic":"zigbee2mqtt/bridge/request/options","device":{"hw_version":"EmberZNet 7.4.4 [GA]","identifiers":["zigbee2mqtt_bridge_0xdc8e95fffe25801a"],"manufacturer":"Zigbee2MQTT","model":"Bridge","name":"Zigbee2MQTT Bridge","sw_version":"1.40.1"},"entity_category":"config","name":"Log level","object_id":"zigbee2mqtt_bridge_log_level","options":["error","warning","info","debug"],"origin":{"name":"Zigbee2MQTT","sw":"1.40.1","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/bridge/info","unique_id":"bridge_0xdc8e95fffe25801a_log_level_zigbee2mqtt","value_template":"{{ value_json.log_level | lower }}"}'
[2024-09-26 20:42:15] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/1221051039810110150109113116116_0xdc8e95fffe25801a/version/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"availability_mode":"all","device":{"hw_version":"EmberZNet 7.4.4 [GA]","identifiers":["zigbee2mqtt_bridge_0xdc8e95fffe25801a"],"manufacturer":"Zigbee2MQTT","model":"Bridge","name":"Zigbee2MQTT Bridge","sw_version":"1.40.1"},"entity_category":"diagnostic","icon":"mdi:zigbee","name":"Version","object_id":"zigbee2mqtt_bridge_version","origin":{"name":"Zigbee2MQTT","sw":"1.40.1","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/bridge/info","unique_id":"bridge_0xdc8e95fffe25801a_version_zigbee2mqtt","value_template":"{{ value_json.version }}"}'
[2024-09-26 20:42:15] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/1221051039810110150109113116116_0xdc8e95fffe25801a/coordinator_version/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"availability_mode":"all","device":{"hw_version":"EmberZNet 7.4.4 [GA]","identifiers":["zigbee2mqtt_bridge_0xdc8e95fffe25801a"],"manufacturer":"Zigbee2MQTT","model":"Bridge","name":"Zigbee2MQTT Bridge","sw_version":"1.40.1"},"enabled_by_default":false,"entity_category":"diagnostic","icon":"mdi:chip","name":"Coordinator version","object_id":"zigbee2mqtt_bridge_coordinator_version","origin":{"name":"Zigbee2MQTT","sw":"1.40.1","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/bridge/info","unique_id":"bridge_0xdc8e95fffe25801a_coordinator_version_zigbee2mqtt","value_template":"{{ value_json.coordinator.meta.revision }}"}'
[2024-09-26 20:42:16] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/1221051039810110150109113116116_0xdc8e95fffe25801a/network_map/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"availability_mode":"all","device":{"hw_version":"EmberZNet 7.4.4 [GA]","identifiers":["zigbee2mqtt_bridge_0xdc8e95fffe25801a"],"manufacturer":"Zigbee2MQTT","model":"Bridge","name":"Zigbee2MQTT Bridge","sw_version":"1.40.1"},"enabled_by_default":false,"entity_category":"diagnostic","json_attributes_template":"{{ value_json.data.value | tojson }}","json_attributes_topic":"zigbee2mqtt/bridge/response/networkmap","name":"Network map","object_id":"zigbee2mqtt_bridge_network_map","origin":{"name":"Zigbee2MQTT","sw":"1.40.1","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/bridge/response/networkmap","unique_id":"bridge_0xdc8e95fffe25801a_network_map_zigbee2mqtt","value_template":"{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"}'
[2024-09-26 20:42:16] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/sensor/1221051039810110150109113116116_0xdc8e95fffe25801a/permit_join_timeout/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"availability_mode":"all","device":{"hw_version":"EmberZNet 7.4.4 [GA]","identifiers":["zigbee2mqtt_bridge_0xdc8e95fffe25801a"],"manufacturer":"Zigbee2MQTT","model":"Bridge","name":"Zigbee2MQTT Bridge","sw_version":"1.40.1"},"device_class":"duration","entity_category":"diagnostic","name":"Permit join timeout","object_id":"zigbee2mqtt_bridge_permit_join_timeout","origin":{"name":"Zigbee2MQTT","sw":"1.40.1","url":"https://www.zigbee2mqtt.io"},"state_topic":"zigbee2mqtt/bridge/info","unique_id":"bridge_0xdc8e95fffe25801a_permit_join_timeout_zigbee2mqtt","unit_of_measurement":"s","value_template":"{{ iif(value_json.permit_join_timeout is defined, value_json.permit_join_timeout, None) }}"}'
[2024-09-26 20:42:16] info: 	z2m:mqtt: MQTT publish: topic 'homeassistant/switch/1221051039810110150109113116116_0xdc8e95fffe25801a/permit_join/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state","value_template":"{{ value_json.state }}"}],"availability_mode":"all","command_topic":"zigbee2mqtt/bridge/request/permit_join","device":{"hw_version":"EmberZNet 7.4.4 [GA]","identifiers":["zigbee2mqtt_bridge_0xdc8e95fffe25801a"],"manufacturer":"Zigbee2MQTT","model":"Bridge","name":"Zigbee2MQTT Bridge","sw_version":"1.40.1"},"icon":"mdi:human-greeting-proximity","name":"Permit join","object_id":"zigbee2mqtt_bridge_permit_join","origin":{"name":"Zigbee2MQTT","sw":"1.40.1","url":"https://www.zigbee2mqtt.io"},"payload_off":"false","payload_on":"true","state_topic":"zigbee2mqtt/bridge/info","unique_id":"bridge_0xdc8e95fffe25801a_permit_join_zigbee2mqtt","value_template":"{{ value_json.permit_join | lower }}"}'
[2024-09-26 20:43:11] info: 	z2m: Starting network scan (includeRoutes 'false')
[2024-09-26 20:43:12] info: 	z2m: Network scan finished
[2024-09-26 20:43:12] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/networkmap', payload '{"data":{"routes":false,"type":"raw","value":{"links":[],"nodes":[{"definition":null,"failed":[],"friendlyName":"Coordinator","ieeeAddr":"0xdc8e95fffe25801a","networkAddress":0,"type":"Coordinator"}]}},"status":"ok","transaction":"sgpfu-1"}'
[2024-09-26 20:43:34] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"offline"}'
[2024-09-26 20:43:34] info: 	z2m: Disconnecting from MQTT server
[2024-09-26 20:43:34] info: 	z2m: Stopping zigbee-herdsman...
[2024-09-26 20:43:35] info: 	zh:controller: Wrote coordinator backup to '/config/zigbee2mqtt/coordinator_backup.json'
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash: ASH COUNTERS since last clear:
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   Total frames: RX=70, TX=130
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   Cancelled   : RX=0, TX=0
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   DATA frames : RX=69, TX=60
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   DATA bytes  : RX=759, TX=703
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   Retry frames: RX=0, TX=0
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   ACK frames  : RX=0, TX=69
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   NAK frames  : RX=0, TX=0
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   nRdy frames : RX=0, TX=0
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   CRC errors      : RX=0
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   Comm errors     : RX=0
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   Length < minimum: RX=0
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   Length > maximum: RX=0
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   Bad controls    : RX=0
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   Bad lengths     : RX=0
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   Bad ACK numbers : RX=0
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   Out of buffers  : RX=0
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   Retry dupes     : RX=0
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   Out of sequence : RX=0
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash:   ACK timeouts    : RX=0
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash: Port closed.
[2024-09-26 20:43:35] info: 	zh:ember:uart:ash: ======== ASH stopped ========
[2024-09-26 20:43:35] info: 	zh:ember:ezsp: ======== EZSP stopped ========
[2024-09-26 20:43:35] info: 	zh:ember: ======== Ember Adapter Stopped ========
[2024-09-26 20:43:35] info: 	z2m: Stopped zigbee-herdsman
[2024-09-26 20:43:35] info: 	z2m: Stopped Zigbee2MQTT
"

**All went fine. 
I restartet the homeassistent. 
But after restart, Zigbee2MQTT cant start. 
new log is this...**

"[21:57:02] INFO: Preparing to start...
[21:57:02] INFO: Socat not enabled
[21:57:04] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-09-26 21:57:11] info: 	z2m: Logging to console, file (filename: log.log)
[2024-09-26 21:57:11] info: 	z2m: Starting Zigbee2MQTT version 1.40.1 (commit #unknown)
[2024-09-26 21:57:11] info: 	z2m: Starting zigbee-herdsman (0.57.3)
[2024-09-26 21:57:12] info: 	zh:ember: Using default stack config.
[2024-09-26 21:57:12] info: 	zh:ember: ======== Ember Adapter Starting ========
[2024-09-26 21:57:12] info: 	zh:ember:ezsp: ======== EZSP starting ========
[2024-09-26 21:57:12] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2024-09-26 21:57:12] info: 	zh:ember:uart:ash: RTS/CTS config is off, enabling software flow control.
[2024-09-26 21:57:12] info: 	zh:ember:uart:ash: Serial port opened
[2024-09-26 21:57:12] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-09-26 21:57:14] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2024-09-26 21:57:14] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-09-26 21:57:17] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2024-09-26 21:57:17] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-09-26 21:57:19] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2024-09-26 21:57:19] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-09-26 21:57:22] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2024-09-26 21:57:22] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-09-26 21:57:24] error: 	z2m: Error while starting zigbee-herdsman
[2024-09-26 21:57:24] error: 	z2m: Failed to start zigbee
[2024-09-26 21:57:24] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-09-26 21:57:24] error: 	z2m: Exiting...
[2024-09-26 21:57:25] error: 	z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:701:19)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1708:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:138:29)
    at Zigbee.start (/app/lib/zigbee.ts:64:27)
    at Controller.start (/app/lib/controller.ts:140:27)
    at start (/app/index.js:154:5)
    "
   
   **Can someone help me pls. I am completly frustated...**

### Zigbee2MQTT version

1.40.1

### Adapter firmware version

ncp-uart-hw-v7.4.4.0-zbdonglee-115200

### Adapter

SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2

### Setup

Core 2024.9.3 Supervisor 2024.09.1 Operating System 13.1 Frontend 20240909.1

**Comment by WodkaExpress** [comment]
Sry Guys, i am learning the Post system...
It's not solved! 
Thanks for any Help.
