### ISSUE TITLE
Danfoss Ally 014G2461 TRV cannot be interviewed

### ISSUE THREAD

**Issue by OZ1SEJ** [Koenkk/zigbee2mqtt#24134]
### What happened?

When trying to pair one of my Danfoss Ally TRVs, model 014G2461, I got this message:
```
[2024-09-29 08:43:46] error: 	zh:controller: Interview failed for '0x0c4314fffecb7b53 with error 'Error: Interview failed because can not get active endpoints ('0x0c4314fffecb7b53')'
```
-three times in a row.

### What did you expect to happen?

I expected it to pair up the exact same way as the first two I paired.

### How to reproduce it (minimal and precise)

1. Enable joining the network
2. Put the device in joining mode
3. I get this in the log:
```
[2024-09-29 08:47:46] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/0x0c4314fffecb7b53', payload '{"last_seen":"2024-09-29T06:47:46.334Z","linkquality":141,"update":{"installed_version":-1,"latest_version":-1}}'
[2024-09-29 08:47:46] info: 	zh:controller: Interview for '0x0c4314fffecb7b53' started
[2024-09-29 08:47:46] info: 	z2m: Device '0x0c4314fffecb7b53' joined
[2024-09-29 08:47:46] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x0c4314fffecb7b53"},"type":"device_connected"}'
[2024-09-29 08:47:46] info: 	z2m: Starting interview of '0x0c4314fffecb7b53'
[2024-09-29 08:47:46] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x0c4314fffecb7b53"},"type":"pairing"}'
[2024-09-29 08:47:46] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x0c4314fffecb7b53","ieee_address":"0x0c4314fffecb7b53"},"type":"device_joined"}'
[2024-09-29 08:47:46] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x0c4314fffecb7b53","ieee_address":"0x0c4314fffecb7b53","status":"started"},"type":"device_interview"}'
[2024-09-29 08:47:53] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/0x0c4314fffecb7b53', payload '{"last_seen":"2024-09-29T06:47:53.588Z","linkquality":141,"update":{"installed_version":-1,"latest_version":-1}}'
[2024-09-29 08:48:04] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/0x0c4314fffecb7b53', payload '{"last_seen":"2024-09-29T06:48:04.974Z","linkquality":141,"update":{"installed_version":-1,"latest_version":-1}}'
[2024-09-29 08:48:05] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/0x0c4314fffecb7b53', payload '{"last_seen":"2024-09-29T06:48:05.240Z","linkquality":141,"update":{"installed_version":-1,"latest_version":-1}}'
[2024-09-29 08:48:05] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x0c4314fffecb7b53"},"type":"device_announced"}'
[2024-09-29 08:48:05] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x0c4314fffecb7b53","ieee_address":"0x0c4314fffecb7b53"},"type":"device_announce"}'
[2024-09-29 08:48:06] error: 	zh:controller: Interview failed for '0x0c4314fffecb7b53 with error 'Error: Interview failed because can not get active endpoints ('0x0c4314fffecb7b53')'
[2024-09-29 08:48:06] error: 	z2m: Failed to interview '0x0c4314fffecb7b53', device has not successfully been paired
```

### Zigbee2MQTT version

1.40.1

### Adapter firmware version

20210708

### Adapter

ITead Sonoff Zigbee 3.0 USB Dongle Plus

### Setup

Add-on on Home Assistant OS on NUC i5

### Debug log

The page https://www.zigbee2mqtt.io/guide/configuration/logging.html#debugging suggest to put
```
advanced:
    log_level: debug
```
in `configuration.yaml`, but that gives me a "Configuration warning: Integration error: advanced - Integration 'advanced' not found."

UPDATE 1: I've tried pairing directly with my coordinator, which gives the above error. When I try to pair with a repeater, I get a new error:
```
[2024-09-29 22:26:44] error: 	z2m: Failed to configure '0x0c4314fffecb7b53', attempt 3 (Error: Bind 0x0c4314fffecb7b53/1 hvacThermostat from '0x00124b0024c166ad/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23)
    at Object.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:1118:40)
    at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:857:28
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:20)
    at ZStackAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:799:9)
    at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:531:13)
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:42:9)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/devices/danfoss.ts:215:13)
    at Configure.configure (/app/lib/extension/configure.ts:125:13)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
```
UPDATE 2: Well, despite the above error, pairing directly with the repeater apparently did the trick - the device is now joined and configured, and responds to commands! I guess I'm closing my issue since it now works. (But what in the world triggers this error, then?)

**Comment by OZ1SEJ** [comment]
UPDATE 3: Sorry, too fast. It responds to commands (e.g. mounted mode, viewing direction) but it doesn't send any temperature data...?

**Comment by OZ1SEJ** [comment]
Okay, it was just a question of sending a lot of data to the valve - works now.
