### ISSUE TITLE
Mac transaction expired zstacktransaction.js error

### ISSUE THREAD

**Issue by SBTephan** [Koenkk/zigbee2mqtt#2414]
Hi

I am getting the following error when adding a bitron video thermostat.

googled it but didn't find a solution.

`info  2019-11-25T22:05:22: Successfully interviewed '0x000d6f000ef172**', device has successfully been paired
info  2019-11-25T22:05:22: Device '0x000d6f000ef17**' is supported, identified as: Bitron Wireless wall thermostat with relay (AV2010/32)
info  2019-11-25T22:05:22: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x000d6f000ef172**","model":"AV2010/32","vendor":"Bitron","description":"Wireless wall thermostat with relay","supported":true}}'
info  2019-11-25T22:05:22: Configuring '0x000d6f000ef172**'
error 2019-11-25T22:05:29: Failed to configure '0x000d6f000ef172**', attempt 2 (Error: Data request failed with error: 'MAC transaction expired' (240)
    at ZStackAdapter.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:522:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:5:58))
`

I updated to the latest stable version.

Anyone any ideas?

**Comment by SBTephan** [comment]
hmm, maybe a bit to soon, I restarted the zigbee2mqtt service and since then it is showing the data from the device..
