### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by ChirpyTurnip** [Koenkk/zigbee2mqtt#24192]
### What happened?

In Settings > Advanced I'm trying to change _syslog (enabled)_ to _syslog (disabled)_. I make this change then scroll down and click 'Submit' ans the then the system returns:

```
Hello, you've found a bug. Congratulations!
Calm down
[Click here, and save this file](http://192.168.1.10:8123/api/hassio_ingress/oy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY/#)
[Raise a github issue](https://github.com/nurikk/zigbee2mqtt-frontend/issues/new?template=bug_report.yaml&stacktracke=**Current+url**%3A+http%3A%2F%2F192.168.1.10%3A8123%2Fapi%2Fhassio_ingress%2Foy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY%2F%23%2Fsettings%2Fsettings%0A**Previous+url**%3A+http%3A%2F%2F192.168.1.10%3A8123%2F45df7312_zigbee2mqtt%0A%0A%0A**Error+type**%3A+TypeError%0A**Error+message**%3A+Cannot+convert+undefined+or+null+to+object%0A%0A%0A%0ATypeError%3A+Cannot+convert+undefined+or+null+to+object%0A++++at+Function.entries+%28%3Canonymous%3E%29%0A++++at+r+%28http%3A%2F%2F192.168.1.10%3A8123%2Fapi%2Fhassio_ingress%2Foy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY%2Fassets%2Findex-74e84a13.js%3A62%3A9430%29%0A++++at+r+%28http%3A%2F%2F192.168.1.10%3A8123%2Fapi%2Fhassio_ingress%2Foy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY%2Fassets%2Findex-74e84a13.js%3A62%3A9492%29%0A++++at+P6e+%28http%3A%2F%2F192.168.1.10%3A8123%2Fapi%2Fhassio_ingress%2Foy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY%2Fassets%2Findex-74e84a13.js%3A62%3A9532%29%0A++++at+Se.onSettingsSave+%5Bas+onSubmit%5D+%28http%3A%2F%2F192.168.1.10%3A8123%2Fapi%2Fhassio_ingress%2Foy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY%2Fassets%2Findex-3a8e477d.js%3A1%3A8632%29%0A++++at+e.%3Canonymous%3E+%28http%3A%2F%2F192.168.1.10%3A8123%2Fapi%2Fhassio_ingress%2Foy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY%2Fassets%2Fbootstrap-5.esm-672cb437.js%3A11%3A47737%29%0A++++at+lD+%28http%3A%2F%2F192.168.1.10%3A8123%2Fapi%2Fhassio_ingress%2Foy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY%2Fassets%2Findex-74e84a13.js%3A41%3A9885%29%0A++++at+zD+%28http%3A%2F%2F192.168.1.10%3A8123%2Fapi%2Fhassio_ingress%2Foy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY%2Fassets%2Findex-74e84a13.js%3A43%3A31876%29%0A++++at+Q5+%28http%3A%2F%2F192.168.1.10%3A8123%2Fapi%2Fhassio_ingress%2Foy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY%2Fassets%2Findex-74e84a13.js%3A43%3A31458%29%0A++++at+Q5+%28http%3A%2F%2F192.168.1.10%3A8123%2Fapi%2Fhassio_ingress%2Foy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY%2Fassets%2Findex-74e84a13.js%3A43%3A31368%29), attach previously downloaded file
Take a screenshot of this page and attach to the issue
In the github issue write detailed description for the issue, how this happened? Steps to reproduce
TypeError
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at r (http://192.168.1.10:8123/api/hassio_ingress/oy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY/assets/index-74e84a13.js:62:9430)
    at r (http://192.168.1.10:8123/api/hassio_ingress/oy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY/assets/index-74e84a13.js:62:9492)
    at P6e (http://192.168.1.10:8123/api/hassio_ingress/oy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY/assets/index-74e84a13.js:62:9532)
    at Se.onSettingsSave [as onSubmit] (http://192.168.1.10:8123/api/hassio_ingress/oy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY/assets/index-3a8e477d.js:1:8632)
    at e.<anonymous> (http://192.168.1.10:8123/api/hassio_ingress/oy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY/assets/bootstrap-5.esm-672cb437.js:11:47737)
    at lD (http://192.168.1.10:8123/api/hassio_ingress/oy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY/assets/index-74e84a13.js:41:9885)
    at zD (http://192.168.1.10:8123/api/hassio_ingress/oy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY/assets/index-74e84a13.js:43:31876)
    at Q5 (http://192.168.1.10:8123/api/hassio_ingress/oy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY/assets/index-74e84a13.js:43:31458)
    at Q5 (http://192.168.1.10:8123/api/hassio_ingress/oy_rE8vMkxoP-S1NYNaI5w7vPJWQns-ye20jpn-YRtY/assets/index-74e84a13.js:43:31368)
```

The download link doesn't yield any download. 

The fault is repeatable - it is not possible to disable syslog. 

However, it is possible to make and successfully submit other changes - for example port and protocol can be updated and committed. It is only the attempt to disable syslog that causes the crash. 

### What did you expect to happen?

Syslog should be disabled. No more. No less. 

### How to reproduce it (minimal and precise)

1. Got to settings
2. Got to Advanced
3. Scroll down to syslog
4. Set to disabled
5. Scroll down to submit and click
6. System generates error.

### Zigbee2MQTT version

1.40.2 commit: unknown

### Adapter firmware version

20210120

### Adapter

Electolama Zig-ah-Zig-Ahh 

### Setup

HAOS on dedicated Intel NUC (not virtualised)

**Comment by Koenkk** [comment]
Please create issues related to the frontend in this repository: https://github.com/nurikk/zigbee2mqtt-frontend
