### ISSUE TITLE
Cannot find module node:url

### ISSUE THREAD

**Issue by NathanSweet** [Koenkk/zigbee2mqtt#24232]
### What happened?

Followed instructions to install and run. Got error: `Cannot find module node:url`.

### How to reproduce it (minimal and precise)

```C:\tools>git clone https://github.com/Koenkk/zigbee2mqtt.git zigbee2mqtt
Cloning into 'zigbee2mqtt'...
remote: Enumerating objects: 30356, done.
remote: Counting objects: 100% (8574/8574), done.
remote: Compressing objects: 100% (495/495), done.
remote: Total 30356 (delta 8370), reused 8123 (delta 8079), pack-reused 21782 (from 1)
Receiving objects: 100% (30356/30356), 108.39 MiB | 2.65 MiB/s, done.
Resolving deltas: 100% (22898/22898), done.

C:\tools>cd zigbee2mqtt

C:\tools\zigbee2mqtt>..\node\node.exe -v
v20.18.0

C:\tools\zigbee2mqtt>..\node\npm.cmd -v
10.8.2

C:\tools\zigbee2mqtt>..\node\npm.cmd ci
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

added 786 packages, and audited 787 packages in 8s

88 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\tools\zigbee2mqtt>..\node\npm.cmd start

> zigbee2mqtt@1.40.2 start
> node index.js

internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'node:url'
Require stack:
- C:\tools\zigbee2mqtt\node_modules\rimraf\node_modules\glob\dist\commonjs\glob.js
- C:\tools\zigbee2mqtt\node_modules\rimraf\node_modules\glob\dist\commonjs\index.js
- C:\tools\zigbee2mqtt\node_modules\rimraf\dist\commonjs\index.js
- C:\tools\zigbee2mqtt\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\tools\zigbee2mqtt\node_modules\rimraf\node_modules\glob\dist\commonjs\glob.js:5:20)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\tools\\zigbee2mqtt\\node_modules\\rimraf\\node_modules\\glob\\dist\\commonjs\\glob.js',
    'C:\\tools\\zigbee2mqtt\\node_modules\\rimraf\\node_modules\\glob\\dist\\commonjs\\index.js',
    'C:\\tools\\zigbee2mqtt\\node_modules\\rimraf\\dist\\commonjs\\index.js',
    'C:\\tools\\zigbee2mqtt\\index.js'
  ]
}
```

### Zigbee2MQTT version

master (e06848db8c5ad247c27e959eb85465a30134769f)

### Adapter

TubesZB CC2652 P7

### Setup

Windows 10

**Comment by NathanSweet** [comment]
Seems running a specific `npm` fails if there is another `node` on the path (case above) or there is no `node` on the path (case below). Requiring the `node` in use to be on the path is pretty annoying.

```
76 error code 1
77 error path C:\tools\zigbee2mqtt\node_modules\@serialport\bindings-cpp
78 error command failed
79 error command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp-build
80 error '"node"' is not recognized as an internal or external command,
80 error operable program or batch file.
```
