### ISSUE TITLE
30 of my 80 devices offline since a couple of days

### ISSUE THREAD

**Issue by helgek** [Koenkk/zigbee2mqtt#24248]
### What happened?

A number of Aqara and Tuya devices shows as offline since a couple of days (mostly open/close sensors and temperature/humidity sensors, all affected devices run on battery, but not all devices running on battery are affected, incl. e.g. sensors of the same type, like Sonos temp/humidity sensors which work fine).

Because of the distribution of the affected devices across the entire apartment I'm pretty sure that these devices used to be connected via different routers.

Interestingly all devices of e.g. the following three devices groups are offline (with no exception):

![image](https://github.com/user-attachments/assets/1f6c8ea3-8746-4bc4-a9b8-e857a040afad)

![image](https://github.com/user-attachments/assets/e4d980f9-4445-4507-99b6-0d3f880867c2)

![image](https://github.com/user-attachments/assets/20122279-1468-48ab-b400-3d585a9606ac)

When I click the "i" / info button the UI shows reports successful interview of the device, but the debug log shows an error:

`info 2024-10-07 03:28:40z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"Temp/Humidity Living Room"},"error":"Failed to configure (ZCL command 0xa4c13800838fe4a5/1 genBasic.read([\"manufacturerName\",\"zclVersion\",\"appVersion\",\"modelId\",\"powerSource\",65534], {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"reservedBits\":0,\"writeUndiv\":false}) failed (Data request failed with error: 'No network route' (205)))","status":"error","transaction":"daxor-2"}'`

When I click the "interview" button the log shows:

`error 2024-10-07 03:28:40z2m: Failed to configure 'Temp/Humidity Living Room', attempt 1 (Error: ZCL command 0xa4c13800838fe4a5/1 genBasic.read(["manufacturerName","zclVersion","appVersion","modelId","powerSource",65534], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205)) at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:524:23) at processTicksAndRejections (node:internal/process/task_queues:95:5) at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:619:24) at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:619:24) at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:619:24) at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:619:24) at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:422:20 at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:20) at ZStackAdapter.sendZclFrameToEndpoint (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:420:16) at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:82:20))`

Zigbee2MQTT version
[1.40.2](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.40.2) commit: [unknown](https://github.com/Koenkk/zigbee2mqtt/commit/unknown)
Coordinator type
zStack3x0
Coordinator revision
20240710
Coordinator IEEE Address
0x00124b0026d10089
Frontend version
0.7.4
zigbee-herdsman-converters version
20.21.0
zigbee-herdsman version
2.1.3
Stats
Total 78
By device type
End devices: 59
Router: 19
By power source
Battery: 58
Mains (single phase): 19
unknown: 1
By vendor
LUMI: 16
_TZE200_gubdgai2: 8
Signify Netherlands B.V.: 7
GLEDOPTO: 6
eWeLink: 5
_TZ3000_bguser20: 5
IKEA of Sweden: 4
_TZ3000_2putqrmw: 3
_TZ3040_6ygjfyll: 3
_TZ3290_7v1k4vufotpowp9z: 2
OSRAM: 2
_TZE200_yjjdcqsq: 2
innr: 2
_TZE200_xaabybja: 1
SONOFF: 1
_TZ3000_xr3htd96: 1
_TZE200_r0jdjrvi: 1
_TZE200_cf1sl3tj: 1
Neuhaus Lighting Group : 1
_TZE200_ytibqbra: 1
_TZE200_xuzcvlku: 1
Third Reality, Inc: 1
_TZ3000_fa9mlvja: 1
_TZ3000_abrsvsou: 1
_TZ3000_qja6nq5z: 1
_TZ3000_ja5osu5g: 1
By model
TS0601: 15
lumi.sensor_magnet.aq2: 9
RDM002: 7
TS0201: 6
lumi.airrtc.agl001: 4
SNZB-02P: 4
GL-C-006P: 3
TS011F: 3
TS0202: 3
TS004F: 3
TRADFRI bulb GU10 CWS 345lm: 3
TS1201: 2
Lightify Switch Mini: 2
GL-C-003P: 2
SNZB-01P: 1
lumi.curtain.agl001: 1
SNZB-02D: 1
lumi.sensor_wleak.aq1: 1
NLG-RGBW light : 1
lumi.curtain.acn002: 1
3RSNL02043Z: 1
TS0041: 1
RC 210: 1
RC 250: 1
TRADFRI bulb GU10 WS 345lm: 1
GL-C-008P: 1

### Zigbee2MQTT version

1.40.2

### Adapter firmware version

20240710

### Adapter

zStack3x0, SLZB-06

### Setup

Intel NUC

### Debug log

[log.log](https://github.com/user-attachments/files/17271706/log.log)

**Comment by helgek** [comment]
My bad, I've found out about the reason. Because I had had repairing issues after migrating from a separate Z2M installation to HA Z2M addon I had also tried to change the Zigbee channel to 25 from 15. Had not realised this had led to the issue that some of the devices remained offline. So now I know which devices don't support channel 25...
