### ISSUE TITLE
[New device support]: Sedea ETH700 thermostatic radiator valve

### ISSUE THREAD

**Issue by Furlot** [Koenkk/zigbee2mqtt#24319]
### Link

https://www.leroymerlin.fr/produits/chauffage-et-ventilation/radiateur/radiateur-a-eau-chaude/accessoires-de-radiateur-eau-chaude/thermostat-et-tete-thermostatique-connecte/tete-thermostatique-connectee-et-intelligente-sedea-92041646.html

### Database entry

{"id":30,"type":"EndDevice","ieeeAddr":"0x28dba7fffe6dd0a4","nwkAddr":20963,"manufId":4742,"manufName":"SEDEA","powerSource":"Battery","modelId":"eTH700","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":769,"inClusterList":[0,1,3,6,32,513,64599,64529],"outClusterList":[10,25],"clusters":{"64529":{"attributes":{"0":0,"16":513,"24576":0,"24577":1500,"24578":700,"24579":343,"24580":423,"24581":1371,"24582":2730,"24583":1369,"24584":127,"24585":2500,"24586":1900,"24587":100,"24588":100}},"genBasic":{"attributes":{"modelId":"eTH700","manufacturerName":"SEDEA","powerSource":3,"zclVersion":8,"appVersion":0,"dateCode":"20240321","swBuildId":"1.1.5"}},"genPollCtrl":{"attributes":{"checkinInterval":14400}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":188}},"genOnOff":{"attributes":{"onOff":1}},"hvacThermostat":{"attributes":{"systemMode":4,"localTemp":2390,"occupiedHeatingSetpoint":2500,"runningState":1,"localTemperatureCalibration":0}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffe77c921","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffe77c921","endpointID":1},{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0xe0798dfffe77c921","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":65000,"repChange":10},{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":65000,"repChange":1}],"meta":{}}},"appVersion":0,"dateCode":"20240321","swBuildId":"1.1.5","zclVersion":8,"interviewCompleted":true,"meta":{"configured":332242049},"lastSeen":1728843567729,"checkinInterval":3600}

### Zigbee2MQTT version

1.40.2

### Comments

I think this is the same product than Sonoff TRVZB, is there a way to say to z2m to use the same definitions? 

### External definition

```shell
const {battery, onOff} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['eTH700'],
    model: 'eTH700',
    vendor: 'SEDEA',
    description: 'Automatically generated definition',
    extend: [battery(), onOff({"powerOnBehavior":false})],
    meta: {},
};

module.exports = definition;
```

### What does/doesn't work with the external definition?

power on/ power off 
batterie level

**Comment by Furlot** [comment]
not sure that is really clean, but it is working, I duplicated the Sonoff SRVZB device, extension file is joined

[Sedea-eTH700.txt](https://github.com/user-attachments/files/17414079/Sedea-eTH700.txt)

**Comment by Furlot** [comment]
weekly_schedule is not working... got this error when trying to set :

`[2024-10-17 17:17:23] debug:    z2m:mqtt: Received MQTT message on 'zigbee2mqtt/eTH700/set' with data '{"weekly_schedule":{"monday":"06:30/20 07:30/17"}}'
[2024-10-17 17:17:23] debug:    z2m: Publishing 'set' 'weekly_schedule' to 'eTH700'
[2024-10-17 17:17:23] error:    z2m: Publish 'set' 'weekly_schedule' to 'eTH700' failed: 'ReferenceError: constants is not defined'
[2024-10-17 17:17:23] debug:    z2m: ReferenceError: constants is not defined
    at Object.convertSet (/app/data/extension/externally-loaded.js:94:29)
    at Publish.onMQTTMessage (/app/lib/extension/publish.ts:306:52)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:206:23)
    at EventEmitter.emit (node:events:529:35)
    at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:144:22)
    at MQTT.onMessage (/app/lib/mqtt.ts:150:27)
    at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:147:27)
    at WebSocket.emit (node:events:517:28)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1220:20)
    at Receiver.emit (node:events:517:28)
[2024-10-17 17:17:23] info:     z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'weekly_schedule' to 'eTH700' failed: 'ReferenceError: constants is not defined'","meta":{"friendly_name":"eTH700"},"type":"zigbee_publish_error"}'`

**Comment by Furlot** [comment]
find a bugreport that solve the issue, added this line to my extend file :

_const constants = require('zigbee-herdsman-converters/lib/constants');_
