### ISSUE TITLE
Zigbee Dongle-E (Sonoff) - NCP 7.4.4.0 - zb2mqtt latest as of posting date - Using '/app/data' as data directory  Starting Zigbee2MQTT without watchdog.  [2024-10-13 23:45:52] error: 	zh:ember:uart:ash: Received frame with CRC error  [2024-10-13 23:45:54] error: 	z2m: MQTT error: write EPIPE ad infinitum

### ISSUE THREAD

**Issue by Majestic7979** [Koenkk/zigbee2mqtt#24323]
### What happened?

Suddenly stopped working. I was using the firmware prior to 7.4.4.0 and it functioned normally but then today it suddenly stopped working, so I updated the firmware to 7.4.4.0 and it still doesn't work.
Use EMQX as MQTT broker. All running on Raspberry Pi 5 on Docker, everything is up to date with apt.

### Zigbee2MQTT version

See title

### Adapter firmware version

See description

### Adapter

SONOFF Zigbee Dongle-E (Silicon Labs chip)

### Setup

Docker on Raspberry Pi (64 bit OS)

**Comment by Majestic7979** [comment]
```
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1583:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:137:29)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:161:27)
    at start (/app/index.js:154:5)
Using '/app/data' as data directory
Starting Zigbee2MQTT without watchdog.
[2024-10-13 23:58:38] error: 	zh:ember:uart:ash: Failed to init port with error Error: Error: Is a directory, cannot open /dev/ttyACM0
[2024-10-13 23:58:38] error: 	z2m: Error while starting zigbee-herdsman
[2024-10-13 23:58:38] error: 	z2m: Failed to start zigbee
[2024-10-13 23:58:38] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-10-13 23:58:38] error: 	z2m: Exiting...
[2024-10-13 23:58:38] error: 	z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:684:19)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1583:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:137:29)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:161:27)
    at start (/app/index.js:154:5)
Using '/app/data' as data directory
Starting Zigbee2MQTT without watchdog.
[2024-10-13 23:59:41] error: 	zh:ember:uart:ash: Failed to init port with error Error: Error: Is a directory, cannot open /dev/ttyACM0
[2024-10-13 23:59:41] error: 	z2m: Error while starting zigbee-herdsman
[2024-10-13 23:59:41] error: 	z2m: Failed to start zigbee
[2024-10-13 23:59:41] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-10-13 23:59:41] error: 	z2m: Exiting...
[2024-10-13 23:59:41] error: 	z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:684:19)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1583:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:137:29)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:161:27)
    at start (/app/index.js:154:5)
Using '/app/data' as data directory
Starting Zigbee2MQTT without watchdog.
[2024-10-14 00:00:43] error: 	zh:ember:uart:ash: Failed to init port with error Error: Error: Is a directory, cannot open /dev/ttyACM0
[2024-10-14 00:00:43] error: 	z2m: Error while starting zigbee-herdsman
[2024-10-14 00:00:43] error: 	z2m: Failed to start zigbee
[2024-10-14 00:00:43] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-10-14 00:00:43] error: 	z2m: Exiting...
[2024-10-14 00:00:43] error: 	z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:684:19)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1583:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:137:29)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:161:27)
    at start (/app/index.js:154:5)
Using '/app/data' as data directory
Starting Zigbee2MQTT without watchdog.
[2024-10-14 00:01:46] error: 	zh:ember:uart:ash: Failed to init port with error Error: Error: Is a directory, cannot open /dev/ttyACM0
[2024-10-14 00:01:46] error: 	z2m: Error while starting zigbee-herdsman
[2024-10-14 00:01:46] error: 	z2m: Failed to start zigbee
[2024-10-14 00:01:46] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-10-14 00:01:46] error: 	z2m: Exiting...
[2024-10-14 00:01:46] error: 	z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:684:19)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1583:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:137:29)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:161:27)
    at start (/app/index.js:154:5)
Using '/app/data' as data directory
Starting Zigbee2MQTT without watchdog.
[2024-10-14 00:02:48] error: 	zh:ember:uart:ash: Failed to init port with error Error: Error: Is a directory, cannot open /dev/ttyACM0
[2024-10-14 00:02:48] error: 	z2m: Error while starting zigbee-herdsman
[2024-10-14 00:02:48] error: 	z2m: Failed to start zigbee
[2024-10-14 00:02:48] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-10-14 00:02:48] error: 	z2m: Exiting...
[2024-10-14 00:02:48] error: 	z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:684:19)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1583:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:137:29)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:161:27)
    at start (/app/index.js:154:5)
Using '/app/data' as data directory
Starting Zigbee2MQTT without watchdog.
[2024-10-14 00:03:51] error: 	zh:ember:uart:ash: Failed to init port with error Error: Error: Is a directory, cannot open /dev/ttyACM0
[2024-10-14 00:03:51] error: 	z2m: Error while starting zigbee-herdsman
[2024-10-14 00:03:51] error: 	z2m: Failed to start zigbee
[2024-10-14 00:03:51] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-10-14 00:03:51] error: 	z2m: Exiting...
[2024-10-14 00:03:51] error: 	z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:684:19)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1583:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:137:29)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:161:27)
    at start (/app/index.js:154:5)
Using '/app/data' as data directory
Starting Zigbee2MQTT without watchdog.
[2024-10-14 00:05:48] error: 	z2m: MQTT error: write EPIPE
[2024-10-14 00:05:51] error: 	z2m: MQTT error: write EPIPE
[2024-10-14 00:05:54] error: 	z2m: MQTT error: write EPIPE
[2024-10-14 00:05:57] error: 	z2m: MQTT error: write EPIPE
[2024-10-14 00:06:00] error: 	z2m: MQTT error: write EPIPE
[2024-10-14 00:06:04] error: 	z2m: MQTT error: write EPIPE
[2024-10-14 00:06:08] error: 	z2m: MQTT error: write EPIPE
[2024-10-14 00:06:13] error: 	z2m: MQTT error: write EPIPE
[2024-10-14 00:06:16] error: 	z2m: MQTT error: write EPIPE

```

I also ran the zigby-znp command to erase NVRAM  just in case of corruption. No difference.

**Comment by Majestic7979** [comment]
I checked the device path to make sure it's correct, it was, the error about missing ACM0 was due to me disconnecting the device to do the NVRAM reset. Now it's connected and system restarted this shows up as before:
```
Using '/app/data' as data directory
Starting Zigbee2MQTT without watchdog.
[2024-10-14 00:09:41] error: 	zh:ember:uart:ash: Received frame with CRC error
[2024-10-14 00:09:43] error: 	z2m: MQTT error: write EPIPE
[2024-10-14 00:09:43] error: 	zh:ember: Delivery of BROADCAST failed for '65532'.
[2024-10-14 00:09:47] error: 	z2m: MQTT error: write EPIPE
[2024-10-14 00:09:50] error: 	z2m: MQTT error: write EPIPE
[2024-10-14 00:09:54] error: 	z2m: MQTT error: write EPIPE

```

**Comment by Majestic7979** [comment]
Problem seems to be EMQX broker... I installed Mosquitto MQTT broker and now Z2M started. Will test and report back, and close the issue if it has indeed been an issue with the broker.

**Comment by Majestic7979** [comment]
Z2M works when I use Mosquitto but not EMQX, although it was working fine until this evening, so not sure why it's not working now. EMQX starts, but nothing connects to it. Verified by using MQTT-Explorer, on Mosquitto I can see clients connected to the broken and they send updates to the respective topics. But this is not happening with EMQX. Have to investigate and see if I can fix that because EMQX is much faster than Mosquitto but for now closing this issue as it does not seem to be Z2M at fault.
