### ISSUE TITLE
Error copying database.db to database.db.backup if no database.db

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee2mqtt#2449]
#Bug Report
## What happened

```
zigbee2mqtt:error 2019-12-01 14:51:23: Error while starting zigbee-herdsman
zigbee2mqtt:error 2019-12-01 14:51:23: Failed to start zigbee
zigbee2mqtt:error 2019-12-01 14:51:23: Exiting...
zigbee2mqtt:error 2019-12-01 14:51:23: Error: ENOENT: no such file or directory, copyfile '/opt/zigbee2mqtt/data/database.db' -> '/opt/zigbee2mqtt/data/database.db.backup'
    at Object.copyFileSync (fs.js:1702:3)
    at Controller.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/controller.js:104:34)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/controller.js:5:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.7.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.7.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/zigbee2mqtt/data/.npm/_logs/2019-12-01T14_51_23_799Z-debug.log
```

Error when starting with a new network when no database.db is present.

## What did you expect to happen

Not get an error?

## How to reproduce it (minimal and precise)

Start fresh with a new configuration.yaml file.

## Debug Info
zigbee2mqtt version: `1.7.1+dev (commit #694c45f)`
CC253X firmware version: n\a

**Comment by Koenkk** [comment]
Fixed in latest dev, thanks!
