### ISSUE TITLE
Failed to start EZSP layer Error while starting zigbee-herdsman

### ISSUE THREAD

**Issue by metramo** [Koenkk/zigbee2mqtt#24504]
### What happened?

I tried to start using Zigbee2MQTT with my Homeassistant green in order to be able to control mySonoff and other devices
in a more complete way.

Not easy understanding everything.
- I had/have some zigbee devices not using MQTT and actually I don't know how to remove them, before finding them under MQTT, maybe this is the problem
- It seems I dont need SOCAT since the dongle is plugged directly in the homeassistant Green
- I have to check the driver and read that part
- Also the serial interface seems ok
- MQTT itself seems to work
- I don't really know how to check the EZSP error messages including ember uart

I get the following printout in the log
[2024-10-27 10:47:19] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2024-10-27 10:47:19] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-10-27 10:47:22] error: 	z2m: Error while starting zigbee-herdsman
[2024-10-27 10:47:22] error: 	z2m: Failed to start zigbee
[2024-10-27 10:47:22] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-10-27 10:47:22] error: 	z2m: Exiting...
[2024-10-27 10:47:22] error: 	z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:684:19)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1583:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:137:29)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:161:27)
    at start (/app/index.js:154:5)
[10:47:52] INFO: Preparing to start...
[10:47:53] INFO: Socat not enabled
[10:47:58] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.

### What did you expect to happen?

I expected Zigbee2MQTT to start and become available so that I could autodiscover a sonoff zbmini2
(The zbmini worked without ZigbeeMQTT

### Zigbee2MQTT version

1.40.2-1

### Adapter firmware version

ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231219113934-if00

### Adapter

ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231219113934

### Setup

Home assistant Green - latest update Oct 2024

### Debug log

Don' know how to get this file

**Comment by Ricc68** [comment]
I believe this may be related to the issue #23282 I have reported a while ago. It happens randomly and starts with a crash then I need to restart HAOS VM to regain connection to the dongle, otherwise I continue to receive the HOST_FATAL_ERROR. It seems that z2m cannot reset the dongle at start until the next reboot.
