### ISSUE TITLE
Philips Hue dimmer pairs but fails to configure

### ISSUE THREAD

**Issue by Alllfff** [Koenkk/zigbee2mqtt#24723]
### What happened?

Device pairs ok, but when buttons are pressed, no LED flashes nor anything like LQI updates in Z2M interface. Dimmer still shows slow red LED flash which would indicate it is not paired?

log input from Z2M when this happens:

z2m: Failed to configure '0x000425ffff02caf6', attempt 1 (Error: Bind 0x000425ffff02caf6/1 genOnOff from '0x00124b0024c6aad1/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23) at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:403:47 at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:20) at ZStackAdapter.sendZdo (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:311:16) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:563:30) at Object.bind (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:42:9) at configure (/app/node_modules/zigbee-herdsman-converters/src/devices/philips.ts:2304:13) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:205:21) at Configure.configure (/app/lib/extension/configure.ts:130:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:57:21))

### Zigbee2MQTT version

1.41.0-1

### Adapter firmware version

20230507

### Adapter

Sonoff ZIgbee 3.0 USB Dongle

### Setup

RPi4 running HA OS, using Sonoff USB dongle and Z2M

**Comment by phasperhoven** [comment]
Same here. I've been using this combination for years, but it suddenly stopped working. Tried to reset it, delete and pair again, restart Z2M, Disconnect dongle, you name it. Nothing works.

2024-12-15 17:40:42z2m: Configuring 'Hue dimmer'
error 2024-12-15 17:40:42z2m: Failed to configure 'Hue dimmer', attempt 7 (TypeError: Cannot read properties of undefined (reading 'bind') at Object.bind (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:42:24) at configure (/app/node_modules/zigbee-herdsman-converters/src/devices/philips.ts:2332:29) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:206:27) at Configure.configure (/app/lib/extension/configure.ts:130:37) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:57:32) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:211:23) at EventEmitter.emit (node:events:531:35) at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:144:22) at MQTT.onMessage (/app/lib/mqtt.ts:150:27) at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:170:27))
info 2024-12-15 17:40:42z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"Hue dimmer"},"error":"Failed to configure (Cannot read properties of undefined (reading 'bind'))","status":"error","transaction":"k9oe1-1"}'
