### ISSUE TITLE
zigbee2mqtt restarts ever 8 seconds, console shows message Error: 'homeassistant.discovery_topic' cannot not be equal to the 'mqtt.base_topic'

### ISSUE THREAD

**Issue by alkempter** [Koenkk/zigbee2mqtt#24761]
### What happened?

Tried to go from version 1.30.2 to current version without changing the working setup.
Docker container restarts with version 1.41.0 and also older versions  (e.g. 1.36). No output in log.
Starting it with docker run ... shows following output:
docker run --name zigbee2mqtt --restart=unless-stopped --device=dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0:/dev/zigbee -p 8092:8092 -v /home/domopi3i/zigbeemq/data:/app/data -v /run/udev:/run/udev:ro -e TZ=Europe/Vienna koenkk/zigbee2mqtt

Using '/app/data' as data directory
Starting Zigbee2MQTT without watchdog.
[2024-11-13 19:31:39] info:     z2m: Logging to console, file (filename: log.log)
Error: 'homeassistant.discovery_topic' cannot not be equal to the 'mqtt.base_topic' (got 'domozigbee')
    at new HomeAssistant (/app/lib/extension/homeassistant.ts:470:19)
    at new Controller (/app/lib/controller.ts:135:34)
    at start (/app/index.js:152:18)

Reverting to 1.30.2 solved the situation.

### What did you expect to happen?

I expected that going to the newest version of zigbee2mqtt would not break the setup.
Did not make any change to the rest of the Domoticz setup.
Autodiscovery prefix is set to: domozigbee
Client Gateway settings are 
prefix topic incoming: domozigbee/in
prefix topic outgoing: domozigbee/out

The Domoticz setup contains MQTT settings also for zWave and Shelly, all using the same mosquitto installation 

### Zigbee2MQTT version

1.41.0

### Adapter firmware version

20210708

### Adapter

Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Setup

Add-on to Domoticz Version: 2024.7 on Raspberry PI3B in Docker container

### Debug log

with new release 1.40.1 following output:
Using '/app/data' as data directory
Starting Zigbee2MQTT without watchdog.
[2024-11-13 19:31:39] info:     z2m: Logging to console, file (filename: log.log)
Error: 'homeassistant.discovery_topic' cannot not be equal to the 'mqtt.base_topic' (got 'domozigbee')
    at new HomeAssistant (/app/lib/extension/homeassistant.ts:470:19)
    at new Controller (/app/lib/controller.ts:135:34)
    at start (/app/index.js:152:18)

with old release 1.30.2 following output:
Zigbee2MQTT:info  2024-11-13 19:46:48: Starting Zigbee2MQTT version 1.30.2 (commit #cdf62ea)
Zigbee2MQTT:info  2024-11-13 19:46:48: Starting zigbee-herdsman (0.14.96)
Zigbee2MQTT:debug 2024-11-13 19:46:48: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/zigbee"}}'
Zigbee2MQTT:info  2024-11-13 19:46:53: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2024-11-13 19:46:53: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210708,"transportrev":2},"type":"zStack3x0"}'
Zigbee2MQTT:debug 2024-11-13 19:46:53: Zigbee network parameters: {"channel":11,"extendedPanID":"0x00124b00257e12b5","panID":6754}
Zigbee2MQTT:info  2024-11-13 19:46:53: Currently 3 devices are joined:
Zigbee2MQTT:info  2024-11-13 19:46:53: 0xa4c13800ab200dc2 (0xa4c13800ab200dc2): 45391 - Müller Licht Smart power strip (Router)
Zigbee2MQTT:info  2024-11-13 19:46:53: 0xa4c138d2c875b342 (0xa4c138d2c875b342): SEA801-Zigbee/SEA802-Zigbee - Saswell Thermostatic radiator valve (EndDevice)
Zigbee2MQTT:info  2024-11-13 19:46:53: 0xa4c13800aa300bf1 (0xa4c13800aa300bf1): 45391 - Müller Licht Smart power strip (Router)
Zigbee2MQTT:warn  2024-11-13 19:46:53: `permit_join` set to  `true` in configuration.yaml.
Zigbee2MQTT:warn  2024-11-13 19:46:53: Allowing new devices to join.
Zigbee2MQTT:warn  2024-11-13 19:46:53: Set `permit_join` to `false` once you joined all devices.
Zigbee2MQTT:info  2024-11-13 19:46:53: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2024-11-13 19:46:53: Connecting to MQTT server at http://192.168.0.103:1883
Zigbee2MQTT:debug 2024-11-13 19:46:53: Using MQTT anonymous login
Zigbee2MQTT:info  2024-11-13 19:46:53: Connected to MQTT server
Zigbee2MQTT:info  2024-11-13 19:46:53: MQTT publish: topic 'domozigbee/bridge/state', payload '{"state":"online"}'
Zigbee2MQTT:info  2024-11-13 19:46:53: Started frontend on port 0.0.0.0:8092
Zigbee2MQTT:info  2024-11-13 19:46:53: MQTT publish: topic 'domozigbee/switch/0xa4c13800ab200dc2/switch/config', payload '{"availability":[{"topic":"domozigbee/bridge/state","value_template":"{{ value_json.state }}"}],"command_topic":"domozigbee/0xa4c13800ab200dc2/set","device":{"identifiers":["zigbee2mqtt_0xa4c13800ab200dc2"],"manufacturer":"Müller Licht","model":"Smart power strip (45391)","name":"0xa4c13800ab200dc2","sw_version":"MPLUG01"},"name":"0xa4c13800ab200dc2","payload_off":"OFF","payload_on":"ON","state_topic":"domozigbee/0xa4c13800ab200dc2","unique_id":"0xa4c13800ab200dc2_switch_domozigbee","value_template":"{{ value_json.state }}"}'............................................................

**Comment by alkempter** [comment]
after finding a hint in homeassistant community 

in configuration.yaml changed discovery Topic (now domoadzigbee)
homeassistant:
  discovery_topic: domoadzigbee

and in Domoticz  Auto Discovery Client Gateway Definition changed 
  Autodiscovery prefix to domoadzigbee
Did not Change in Domoticz Client Gateway the prefix definitions (domozigbee/in and domozigbee/out)

Now it starts and seems to work as before.
