### ISSUE TITLE
Issue with HG06619 — no connection

### ISSUE THREAD

**Issue by pandizajner** [Koenkk/zigbee2mqtt#24809]
### What happened?

Since some time I started having issues with my z2m. I've started from updating zigbee2mqtt (currently 1.41.0), upgraded coordinator from CC2531 to CC2652P ZBDongle-P. Most recent issue was node which only for zigbee2mqtt was not up to date (but found a solution [here](https://github.com/Koenkk/zigbee2mqtt/discussions/13364) using PPAand it doesn't throw this error anymode).

But all those didn't solve my issue with HG06619. Even after upgrading dongle, it was at least sometimes responsive (most often after zigbee2mqtt reset). But after I upgraded node and removed this device from the list (even force removed). It appears again on the list (after a few minutes), but there's no connection with the device.

### Zigbee2MQTT version

1.41.0

### Adapter firmware version

20210708

### Adapter

CC2652P ZBDongle-P.

### Setup

Homebridge Zigbee2MQTT on RPi 

### Debug log

```info 2024-11-18 00:56:16z2m: Accepting joining not in blocklist device '0x842e14fffe24bd7e'
info 2024-11-18 00:56:18zh:controller: Interview for '0x842e14fffe24bd7e' started
info 2024-11-18 00:56:18z2m: Device '0x842e14fffe24bd7e' joined
info 2024-11-18 00:56:18z2m: Starting interview of '0x842e14fffe24bd7e'
info 2024-11-18 00:56:18z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x842e14fffe24bd7e","ieee_address":"0x842e14fffe24bd7e"},"type":"device_joined"}'
info 2024-11-18 00:56:18z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x842e14fffe24bd7e","ieee_address":"0x842e14fffe24bd7e","status":"started"},"type":"device_interview"}'
error 2024-11-18 00:56:59z2m: Publish 'get' 'state' to '0x842e14fffe24bd7e' failed: 'Error: ZCL command 0x842e14fffe24bd7e/1 genOnOff.read(["onOff"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'MAC no ack' (233))'
info 2024-11-18 00:57:23zh:controller: Succesfully interviewed '0x842e14fffe24bd7e'
info 2024-11-18 00:57:23z2m: Successfully interviewed '0x842e14fffe24bd7e', device has successfully been paired
info 2024-11-18 00:57:23z2m: Device '0x842e14fffe24bd7e' is supported, identified as: Lidl Silvercrest outdoor plug (HG06619)
info 2024-11-18 00:57:23z2m: Configuring '0x842e14fffe24bd7e'
info 2024-11-18 00:57:23z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Silvercrest outdoor plug","exposes":[{"features":[{"access":7,"description":"On/off state of the switch","label":"State","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"}],"type":"switch"},{"access":7,"category":"config","description":"Controls the behavior when the device is powered on after power loss","label":"Power-on behavior","name":"power_on_behavior","property":"power_on_behavior","type":"enum","values":["off","previous","on"]},{"access":1,"category":"diagnostic","description":"Link quality (signal strength)","label":"Linkquality","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"HG06619","options":[{"access":2,"description":"State actions will also be published as 'action' when true (default false).","label":"State action","name":"state_action","property":"state_action","type":"binary","value_off":false,"value_on":true}],"supports_ota":false,"vendor":"Lidl"},"friendly_name":"0x842e14fffe24bd7e","ieee_address":"0x842e14fffe24bd7e","status":"successful","supported":true},"type":"device_interview"}'
error 2024-11-18 00:57:33z2m: Failed to configure '0x842e14fffe24bd7e', attempt 2 (Error: Bind 0x842e14fffe24bd7e/1 genOnOff from '0x00124b001949cca1/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Object.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23) at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:403:47 at Queue.execute (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:36:20) at ZStackAdapter.sendZdo (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:311:16) at Endpoint.bind (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:563:30) at Object.bind (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:42:9) at configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/devices/lidl.ts:532:13) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/index.ts:205:21) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:130:13) at EventEmitter.wrappedCallback (/opt/zigbee2mqtt/lib/eventBus.ts:206:17))
error 2024-11-18 01:03:16z2m: Publish 'set' 'state' to '0x842e14fffe24bd7e' failed: 'Error: ZCL command 0x842e14fffe24bd7e/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
error 2024-11-18 01:03:38z2m: Publish 'set' 'state' to '0x842e14fffe24bd7e' failed: 'Error: ZCL command 0x842e14fffe24bd7e/1 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))'
```

**Comment by pandizajner** [comment]
Update: 
- Upgraded coordinator to 20240710
- switched to `dev` branch (1.41.0-dev commit: [36e452b0](https://github.com/Koenkk/zigbee2mqtt/commit/36e452b0))

Still the same issue:
```
info 2024-11-18 10:05:23z2m: Configuring '0x842e14fffe24bd7e'
error 2024-11-18 10:05:33z2m: Failed to configure '0x842e14fffe24bd7e', attempt 2 (Error: Bind 0x842e14fffe24bd7e/1 genOnOff from '0x00124b001949cca1/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Object.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23) at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:403:47 at Queue.execute (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:36:20) at ZStackAdapter.sendZdo (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:311:16) at Endpoint.bind (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:563:30) at Object.bind (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:42:9) at configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/devices/lidl.ts:532:13) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/index.ts:205:21) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:130:13) at Configure.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/configure.ts:57:21))
```

**Comment by pandizajner** [comment]
I forced removed and repaired again after last update and now it seems to be working correctly. Closing
