### ISSUE TITLE
dev branch tests fail on macOS

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee2mqtt#2480]
# Bug Report
## What happened
Wanted to give writing tests for #2464 another got, but I wanted to make sure the baseline ran clean.

```
[hyperon :: sjorge][~/Desktop/_github/zigbee2mqtt][dev ✔]
[■]$ npm run test

> zigbee2mqtt@1.7.1 test /Users/sjorge/Desktop/_github/zigbee2mqtt
> jest test

 PASS  test/networkMap.test.js
 PASS  test/bridgeConfig.test.js
 PASS  test/deviceConfigure.test.js
 PASS  test/settings.test.js
 PASS  test/deviceBind.test.js
 PASS  test/data.test.js
 FAIL  test/entityPublish.test.js
  ● Entity publish › Should parse set with color attribute topic

    expect(jest.fn()).toHaveBeenCalledWith(...expected)

    - Expected
    + Received

      "lightingColorCtrl",
      "moveToColor",
      Object {
    -   "colorx": 17806,
    -   "colory": 43155,
    +   "colorx": NaN,
    +   "colory": NaN,
        "transtime": 0,
      },
      {},

    Number of calls: 1

      478 |         await flushPromises();
      479 |         expect(endpoint.command).toHaveBeenCalledTimes(1);
    > 480 |         expect(endpoint.command).toHaveBeenCalledWith("lightingColorCtrl", "moveToColor", {colorx: 17806, colory: 43155, transtime: 0}, {});
          |                                  ^
      481 |         expect(MQTT.publish).toHaveBeenCalledTimes(1);
      482 |         expect(MQTT.publish.mock.calls[0][0]).toStrictEqual('zigbee2mqtt/bulb_color');
      483 |         expect(JSON.parse(MQTT.publish.mock.calls[0][1])).toStrictEqual({color_temp: 156, color: {x: 0.2717, y: 0.6585}});

      at Object.it (test/entityPublish.test.js:480:34)

  ● Entity publish › Should allow to set color via hue and saturation

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 0
    Received number of calls: 1

      670 |         expect(endpoint.command).toHaveBeenCalledTimes(1);
      671 |         expect(endpoint.command.mock.calls[0]).toEqual(["lightingColorCtrl", "enhancedMoveToHueAndSaturation", {"direction": 0, "enhancehue": 45510.416666666664, "saturation": 127, "transtime": 0,}, {}]);
    > 672 |         expect(MQTT.publish).toHaveBeenCalledTimes(0);
          |                              ^
      673 |     });
      674 |
      675 |     it('ZNCLDJ11LM open', async () => {

      at Object.it (test/entityPublish.test.js:672:30)

 PASS  test/deviceReport.test.js
 PASS  test/utils.test.js
 PASS  test/logger.test.js
 PASS  test/deviceEvent.test.js
 PASS  test/deviceAvailability.test.js (5.509s)
 PASS  test/homeassistant.test.js (5.61s)
 PASS  test/group.test.js (5.981s)
 PASS  test/deviceReceive.test.js (6.434s)
 PASS  test/controller.test.js (7.338s)

Test Suites: 1 failed, 15 passed, 16 total
Tests:       2 failed, 317 passed, 319 total
Snapshots:   0 total
Time:        8.855s, estimated 9s
Ran all test suites matching /test/i.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.7.1 test: `jest test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.7.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sjorge/.npm/_logs/2019-12-06T22_36_28_427Z-debug.log
```

## What did you expect to happen
Not have test failures on dev branch.

## How to reproduce it (minimal and precise)
Run npm run test on dev?

## Debug Info
zigbee2mqtt version:
CC253X firmware version:

**Comment by sjorge** [comment]
nvm, I am dumb and forgot to clear my node_modules dir
