### ISSUE TITLE
[New device support]: TuYa TS0505 Smart Bulb

### ISSUE THREAD

**Issue by Bestivus** [Koenkk/zigbee2mqtt#24893]
### Link

https://www.aliexpress.us/item/3256807278358215.html

### Database entry

{"id":30,"type":"Router","ieeeAddr":"0x70b3d52b60120afc","nwkAddr":10375,"manufId":4660,"manufName":"zbeacon","powerSource":"Mains (single phase)","modelId":"TS0505","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":269,"inClusterList":[0,6,3,4,5,4096,8,768,10,57345,57344,1794,2820],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"TS0505","manufacturerName":"zbeacon","powerSource":1,"zclVersion":3,"appVersion":112,"stackVersion":2,"hwVersion":0,"swBuildId":"z.1.0"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":25,"colorTempPhysicalMin":153,"colorTempPhysicalMax":500,"currentHue":157,"colorTemperature":500,"currentSaturation":254}},"haElectricalMeasurement":{"attributes":{"acPowerDivisor":1,"acPowerMultiplier":1,"acCurrentDivisor":1,"acCurrentMultiplier":1,"acVoltageDivisor":1,"acVoltageMultiplier":1}},"genOnOff":{"attributes":{"onOff":1}},"genLevelCtrl":{"attributes":{"currentLevel":17}}},"binds":[{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b002e1455f8","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":112,"stackVersion":2,"hwVersion":0,"swBuildId":"z.1.0","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1732401449965}

### Zigbee2MQTT version

1.41.0

### Comments

Followed the steps to create the external definition, but not sure how to proceed from here.

### External definition

```shell
const {light, electricityMeter} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['TS0505'],
    model: 'TS0505',
    vendor: 'zbeacon',
    description: 'Automatically generated definition',
    extend: [light({"colorTemp":{"range":[153,500]},"color":{"modes":["xy","hs"]}}), electricityMeter()],
    meta: {},
};

module.exports = definition;
```

### What does/doesn't work with the external definition?

Getting error messages about failing to configure:

error 2024-11-23 17:41:07z2m: Failed to configure 'Peyton Bulb 1', attempt 2 (Error: ZCL command 0x70b3d52b60120ad8/1 haElectricalMeasurement.configReport([{"minimumReportInterval":10,"maximumReportInterval":65000,"reportableChange":5,"attribute":"activePower"},{"minimumReportInterval":10,"maximumReportInterval":65000,"reportableChange":0.05,"attribute":"rmsCurrent"},{"minimumReportInterval":10,"maximumReportInterval":65000,"reportableChange":5,"attribute":"rmsVoltage"}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Status 'INVALID_DATA_TYPE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:350:28) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:956:26) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:688:9) at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:162:17) at result.configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:1950:29) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:205:21) at Configure.configure (/app/lib/extension/configure.ts:130:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:206:17))

**Comment by lucasnz** [comment]
I have this device working with the following ext_converter.js:
```
const {light} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['TS0505'],
    model: 'TS0505',
    vendor: 'zbeacon',
    description: 'Automatically generated definition',
    extend: [light({"colorTemp":{"range":[153,500]},"color":{"modes":["xy","hs"]}})],
    meta: {},
};

module.exports = definition;
```
