### ISSUE TITLE
z2m: Failed to call 'Frontend'

### ISSUE THREAD

**Issue by Matten-Matten** [Koenkk/zigbee2mqtt#24957]
### What happened?

error: 	z2m: Failed to call 'Frontend' 'stop' (TypeError: Cannot read properties of undefined (reading 'clients')

### Zigbee2MQTT version

zStack3

### Adapter firmware version

20230507

### Adapter

zstack

### Setup

rpi3

### Debug log

```
[2024-11-29 12:06:47] error: 	z2m: Failed to call 'Frontend' 'stop' (TypeError: Cannot read properties of undefined (reading 'clients')
    at Frontend.stop (/opt/zigbee2mqtt/lib/extension/frontend.ts:120:18)
    at Controller.callExtensions (/opt/zigbee2mqtt/lib/controller.ts:399:17)
    at Controller.stop (/opt/zigbee2mqtt/lib/controller.ts:265:9)
    at stop (/opt/zigbee2mqtt/index.js:165:5)
    at process.handleQuit (/opt/zigbee2mqtt/index.js:173:13))
```

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the [dev branch](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html) in a few hours from now.

**Comment by Matten-Matten** [comment]
@Koenkk Thank you for the quick changes.

greeting 
Matten Matten
