### ISSUE TITLE
Fails to start after upgrade to 1.42.0-1

### ISSUE THREAD

**Issue by CompilerStyler** [Koenkk/zigbee2mqtt#25006]
### What happened?

After upgrading to 1.42.0-1 from 1.41.0-1 it no longer starts. 

After checking changelog, I see this information (note I do not have "custom settings" but I did have to manually move the files. 

>     Zigbee2MQTT configuration is now by default stored in the addon specific configuration directory rather than the main config directory.
>     This is required for Home Assistant's backup functionality to work correctly.
>     New installations and installations using the default settings will automatically migrate to the new path, existing setups with custom settings will continue to work but need to be manually migrated to make use of Home Assistant's backups:
>         Stop the addon
>         Move the /mnt/data/supervisor/homeassistant/zigbee2mqtt folder to /mnt/data/supervisor/addon_configs/45df7312_zigbee2mqtt/zigbee2mqtt (for example using SSH/SMB or the File Explorer/VSCode addon)
>         Go to the addon config and change the data_path from /config/zigbee2mqtt to /addon_config/zigbee2mqtt
>         Start the addon
>     Mount addon specific configuration into the addon container (/addon_config)

### Zigbee2MQTT version

1.42.0-1

### Adapter firmware version

Cannot see this. 

### Adapter

Cannot see this. 

### Setup

Raspberry Pi  Core 2024.11.3 Supervisor 2024.11.4 Operating System 13.2 Frontend 20241106.2

### Debug log

The guide for enabling debug says to add it to the configuration.yaml - which one, there are now several e.g. /addon_configs/45df7312_zigbee2mqtt/zigbee2mqtt/zigbee2mqtt or /addon_configs/45df7312_zigbee2mqtt/zigbee2mqtt

[17:46:13] INFO: Preparing to start...
[17:46:13] INFO: Socat not enabled
[17:46:14] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-12-02 17:46:19] info: 	z2m: Logging to console, file (filename: log.log)
[2024-12-02 17:46:19] info: 	z2m: Starting Zigbee2MQTT version 1.42.0 (commit #unknown)
[2024-12-02 17:46:19] info: 	z2m: Starting zigbee-herdsman (2.1.9)
[2024-12-02 17:46:20] error: 	z2m: Error while starting zigbee-herdsman
[2024-12-02 17:46:20] error: 	z2m: Failed to start zigbee
[2024-12-02 17:46:20] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-12-02 17:46:20] error: 	z2m: Exiting...
[2024-12-02 17:46:20] error: 	z2m: Error: No path provided and failed to auto detect path
    at Function.create (/app/node_modules/zigbee-herdsman/src/adapter/adapter.ts:107:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:133:24)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:161:27)
    at start (/app/index.js:154:5)

**Comment by CompilerStyler** [comment]
I deleted the entire addon and removed all addon data and it still produces the same error.

**Comment by CompilerStyler** [comment]
I was able to eventually fix this - I evidently moved the 'wrong' configuration.yaml file as there were several laying around - however the fact it broke in the first place is not ideal at all, better instructions should be provided on exactly what to move where.
