### ISSUE TITLE
SLZB-06M cant pair devices anymore

### ISSUE THREAD

**Issue by panhans** [Koenkk/zigbee2mqtt#25164]
### What happened?

My network is very stable and now I tried to pair a new device with my coordinator. But it doesn't switch to pairing mode. The adapter is bound over LAN.

### What did you expect to happen?

Enabling pairing mode without issues.

### How to reproduce it (minimal and precise)

Select the coordinator an click on *permit join*.

### Zigbee2MQTT version

1.42.0-2

### Adapter firmware version

 7.4.5 [GA]

### Adapter

SLZB-06M 

### Setup

Home Assistant Addon on x86 Machine

### Debug log

```
[2024-12-11 14:38:37] [31merror[39m: 	z2m: Request 'zigbee2mqtt/bridge/request/permit_join' failed with error: 'Delivery failed for '5101'.'
[2024-12-11 14:40:54] [32minfo[39m: 	z2m: Successfully changed options
[2024-12-11 14:40:54] [32minfo[39m: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/options', payload '{"data":{"restart_required":false},"status":"ok","transaction":"p7pq0-2"}'
[2024-12-11 14:41:00] [34mdebug[39m: 	z2m:mqtt: Received MQTT message on 'zigbee2mqtt/bridge/request/permit_join' with data '{"device":"Coordinator","time":254,"transaction":"p7pq0-3","value":true}'
[2024-12-11 14:41:00] [32minfo[39m: 	z2m: Zigbee: allowing new devices to join via Coordinator.
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:ezsp: ===> [FRAME: ID=273:"IMPORT_TRANSIENT_KEY" Seq=69 Len=30]
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:uart:ash: ---> [FRAME type=DATA frmTx=5 frmRx=1](ackRx=5)
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=6](ackRx=5 frmTx=6)
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=6 frmNum=1](frmRx=1) Added to rxQueue
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=2](ackRx=6)
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:ezsp: <=== [FRAME: ID=273:"IMPORT_TRANSIENT_KEY" Seq=69 Len=9]
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:ezsp: ===> [FRAME: ID=85:"SET_POLICY" Seq=70 Len=7]
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:uart:ash: ---> [FRAME type=DATA frmTx=6 frmRx=2](ackRx=6)
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=7](ackRx=6 frmTx=7)
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=7 frmNum=2](frmRx=2) Added to rxQueue
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=3](ackRx=7)
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:ezsp: <=== [FRAME: ID=85:"SET_POLICY" Seq=70 Len=6]
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember: [EzspPolicyId] SET 'TRUST_CENTER_POLICY' TO '3' with status=OK.
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember: ~~~> [ZDO PERMIT_JOINING_REQUEST UNICAST to=0xFFFFFFFFFFFFFFFF:5101 messageTag=3 payload=03fe01]
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:ezsp: ===> [FRAME: ID=52:"SEND_UNICAST" Seq=71 Len=24]
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:uart:ash: ---> [FRAME type=DATA frmTx=7 frmRx=3](ackRx=7)
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=0](ackRx=7 frmTx=0)
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=0 frmNum=3](frmRx=3) Added to rxQueue
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=4](ackRx=0)
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember:ezsp: <=== [FRAME: ID=52:"SEND_UNICAST" Seq=71 Len=7]
[2024-12-11 14:41:00] [34mdebug[39m: 	zh:ember: ~~~> [SENT ZDO UNICAST messageTag=3 apsSequence=101 status=OK]
[2024-12-11 14:41:05] [34mdebug[39m: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2024-12-11 14:41:05] [34mdebug[39m: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=0](ackRx=0 frmTx=0)
[2024-12-11 14:41:05] [34mdebug[39m: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=0 frmNum=4](frmRx=4) Added to rxQueue
[2024-12-11 14:41:05] [34mdebug[39m: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=5](ackRx=0)
[2024-12-11 14:41:05] [34mdebug[39m: 	zh:ember:ezsp: <=== [CBFRAME: ID=63:"MESSAGE_SENT_HANDLER" Seq=71 Len=22]
[2024-12-11 14:41:05] [34mdebug[39m: 	zh:ember:ezsp: ezspMessageSentHandler(): callback called with: [status=ZIGBEE_DELIVERY_FAILED], [type=DIRECT], [indexOrDestination=5101], [apsFrame={"profileId":0,"clusterId":54,"sourceEndpoint":0,"destinationEndpoint":0,"options":4160,"groupId":0,"sequence":101}], [messageTag=3]
[2024-12-11 14:41:05] [34mdebug[39m: 	zh:ember: ~x~> DELIVERY_FAILED [indexOrDestination=5101 apsFrame={"profileId":0,"clusterId":54,"sourceEndpoint":0,"destinationEndpoint":0,"options":4160,"groupId":0,"sequence":101} messageTag=3]
[2024-12-11 14:41:05] [31merror[39m: 	z2m: Request 'zigbee2mqtt/bridge/request/permit_join' failed with error: 'Delivery failed for '5101'.'
[2024-12-11 14:41:05] [34mdebug[39m: 	z2m: Error: Delivery failed for '5101'.
    at EmberOneWaitress.deliveryFailedFor (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/oneWaitress.ts:100:31)
    at EmberAdapter.onMessageSent (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:469:42)
    at Ezsp.emit (node:events:519:28)
    at Ezsp.ezspMessageSentHandler (/app/node_modules/zigbee-herdsman/src/adapter/ember/ezsp/ezsp.ts:5032:14)
    at Ezsp.callbackDispatch (/app/node_modules/zigbee-herdsman/src/adapter/ember/ezsp/ezsp.ts:735:26)
    at Ezsp.onAshFrame (/app/node_modules/zigbee-herdsman/src/adapter/ember/ezsp/ezsp.ts:395:22)
    at UartAsh.emit (node:events:519:28)
    at Immediate.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/ember/uart/ash.ts:1169:45)
    at processImmediate (node:internal/timers:478:21)
```

**Comment by Nerivec** [comment]
Have you identified that device 5101 (0x13ed)? Is the error always with that device?

**Comment by panhans** [comment]
For some reason z2m detected my coordinator as a dongle-e. I resetup and repaired all devices and now everything is fine. Maybe this causes the issue.
