### ISSUE TITLE
HEIMAN HS2WD-E groups not supported since release 1.35.0

### ISSUE THREAD

**Issue by jdescoux** [Koenkk/zigbee2mqtt#25276]
### What happened?

Hi,

With a Conbee2 dongle, I have 5 Heiman HS2WD-E sirens and they are controlled individually. But in order to optimize radio communication, I created a zigbee group with these 5 sirens called 'allsiren'.

Prior to **1.35.0 release**, all the sirens was controlled with their own name and with their group name (allsiren) but since this 1.35.0 release (and to the last release), it does not work anymore.

I have the error `z2m: Publish 'set' 'warning' to 'allsiren' failed: 'Error: Not supported for groups'`

### What did you expect to happen?

I notice a regression between 2 versions of zigbee2mqtt.

### How to reproduce it (minimal and precise)

MQTT:
mosquitto_pub -h zigbee2mqtt -u test -P test -t "zigbee2mqtt/allsiren/set" -m '{"warning":{"level":"high","mode":"burglar","strobe":false,"duration":5}}'

1.34.0: it works
1.35.0: it does not work

### Zigbee2MQTT version

1.42.0

### Adapter firmware version

26780700

### Adapter

Conbee II

### Setup

Docker container

### Debug log

```
[2024-12-20 13:26:49] debug: 	z2m:mqtt: Received MQTT message on 'zigbee2mqtt/allsiren/set' with data '{"warning":{"level":"high","mode":"burglar","strobe":false,"duration":300}}'
[2024-12-20 13:26:49] debug: 	z2m: Publishing 'set' 'warning' to 'allsiren'
[2024-12-20 13:26:49] error: 	z2m: Publish 'set' 'warning' to 'allsiren' failed: 'Error: Not supported for groups'
[2024-12-20 13:26:49] debug: 	z2m: Error: Not supported for groups
    at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:525:51)
    at Publish.onMQTTMessage (/app/lib/extension/publish.ts:308:52)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:211:23)
    at EventEmitter.emit (node:events:529:35)
    at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:144:22)
    at MQTT.onMessage (/app/lib/mqtt.ts:150:27)
    at MqttClient.emit (node:events:517:28)
    at handlePublish (/app/node_modules/mqtt/src/lib/handlers/publish.ts:172:11)
    at handle (/app/node_modules/mqtt/src/lib/handlers/index.ts:31:17)
    at work (/app/node_modules/mqtt/src/lib/client.ts:773:17)
[2024-12-20 13:26:49] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'warning' to 'allsiren' failed: 'Error: Not supported for groups'","meta":{"friendly_name":"allsiren"},"type":"zigbee_publish_error"}'
[2024-12-20 13:26:49] debug: 	zh:deconz:driver: send read device state from queue. seqNr: 89
[2024-12-20 13:26:49] debug: 	zh:deconz:frameparser: device state: 10100010
[2024-12-20 13:26:49] debug: 	zh:deconz:driver: networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
```

**Comment by jdescoux** [comment]
Anyone with this same issue?
