### ISSUE TITLE
Z2M and SLZB-06 ethernet errors

### ISSUE THREAD

**Issue by pjuhl2313** [Koenkk/zigbee2mqtt#25378]
### What happened?

I am running HAOS in unRaid in the homeassistant_inabox docker container with VM. I am transitioning from a Sonoff Dongle-E to the SLZB-06 ethernet adapter.

When Z2M does start, it will crash with no error logs reporting the crash.

### Zigbee2MQTT version

1.42.0-2

### Adapter firmware version

20240710

### Adapter

SLZB-06

### Setup

Add-on in HAOS running in docker container Homeassistant_inabox in unRaid server

### Debug log

[10:48:21] INFO: Preparing to start...
[10:48:21] INFO: Socat not enabled
[10:48:21] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-12-30 10:48:23] info: 	z2m: Logging to console, file (filename: log.log)
[2024-12-30 10:48:23] info: 	z2m: Starting Zigbee2MQTT version 1.42.0 (commit #unknown)
[2024-12-30 10:48:23] info: 	z2m: Starting zigbee-herdsman (2.1.9)
[2024-12-30 10:48:23] warning: 	zh:ezsp: 'ezsp' driver is deprecated and will only remain to provide support for older firmware (pre 7.4.x). Migration to 'ember' is recommended. If using Zigbee2MQTT see https://github.com/Koenkk/zigbee2mqtt/discussions/21462
[2024-12-30 10:48:30] error: 	zh:ezsp:uart: --> Error: Error: {"sequence":1} after 4000ms
[2024-12-30 10:48:30] error: 	zh:ezsp:uart: -!- break waiting (1)
[2024-12-30 10:48:30] error: 	zh:ezsp:uart: Can't send DATA frame (0,1,0): 1800012800
[2024-12-30 10:48:35] error: 	zh:ezsp:uart: --> Error: Error: {"sequence":1} after 4000ms
[2024-12-30 10:48:35] error: 	zh:ezsp:uart: -!- break rewaiting (1)
[2024-12-30 10:48:35] error: 	zh:ezsp:uart: Can't resend DATA frame (0,1,1): 1800012800
[2024-12-30 10:48:35] error: 	z2m: Error while starting zigbee-herdsman
[2024-12-30 10:48:35] error: 	z2m: Failed to start zigbee
[2024-12-30 10:48:35] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-12-30 10:48:35] error: 	z2m: Exiting...
[2024-12-30 10:48:35] error: 	z2m: Error: Failure send getNetworkParameters:{"type":"Buffer","data":[24,0,1,40,0]}
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:679:23
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:20)
    at Ezsp.execCommand (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:666:16)
    at Driver.needsToBeInitialised (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:310:27)
    at Driver.startup (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:242:13)
    at EZSPAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:152:16)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:137:29)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:161:27)
    at start (/app/index.js:154:5)

**Comment by pyberg** [comment]
You have not reconfigured Z2M from sonoff to use the SLZB-06
