### ISSUE TITLE
Datek HSE2905E meter reader no longer works

### ISSUE THREAD

**Issue by mellbye** [Koenkk/zigbee2mqtt#25401]
### What happened?

After updating to a recent version of Z2M, the Datek (Eva) meter reader HSE2905E has stopped reporting proper values. Configuration fails, leading the device to report values with the wrong order of magnitude. This seems to have been caused by a refactor in https://github.com/Koenkk/zigbee-herdsman-converters/commit/e8883c0d012ecf9b3f103ca070e44877da4f368f#diff-c120e1aea075a1198be68b19a9eebad9750604ef9e9126ee56c8ecd06f42e627

The error observed is

```
z2m: Failed to configure 'AMS Meter', attempt 4 (Error: Device 0x086bd7fffeae4b44 has no input cluster genOnOff
at getEndpointsWithCluster (/app/node_modules/.pnpm/zigbee-herdsman-converters@21.10.0/node_modules/src/lib/modernExtend.ts:59:15)
at setupAttributes (/app/node_modules/.pnpm/zigbee-herdsman-converters@21.10.0/node_modules/src/lib/modernExtend.ts:144:55)
at /app/node_modules/.pnpm/zigbee-herdsman-converters@21.10.0/node_modules/src/lib/modernExtend.ts:542:23
at Object.configure (/app/node_modules/.pnpm/zigbee-herdsman-converters@21.10.0/node_modules/src/index.ts:257:27)
at Configure.configure (/app/lib/extension/configure.ts:124:13)
at Configure.onMQTTMessage (/app/lib/extension/configure.ts:49:25)
at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:204:17))
```

Removing the `onOff` cluster from the `extend` list in an external converter makes configuring get a bit further, but it fails when configuring reporting, since the device doesn't have `activePower` attributes:

```
z2m: Failed to configure 'AMS Meter', attempt 1 (Error: ZCL command 0x086bd7fffeae4b44/1 haElectricalMeasurement.configReport([{"minimumReportInterval":10,"maximumReportInterval":65000,"reportableChange":5,"attribute":"activePower"},{"minimumReportInterval":10,"maximumReportInterval":65000,"reportableChange":5,"attribute":"activePowerPhB"},{"minimumReportInterval":10,"maximumReportInterval":65000,"reportableChange":5,"attribute":"activePowerPhC"},{"minimumReportInterval":10,"maximumReportInterval":65000,"reportableChange":50,"attribute":"rmsCurrent"}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') 
at Endpoint.checkStatus (/app/node_modules/.pnpm/zigbee-herdsman@3.2.0/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:349:28) 
at Endpoint.zclCommand (/app/node_modules/.pnpm/zigbee-herdsman@3.2.0/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:954:26) 
at processTicksAndRejections (node:internal/process/task_queues:105:5) 
at runNextTicks (node:internal/process/task_queues:69:3) 
at processImmediate (node:internal/timers:459:9) 
at Endpoint.configureReporting (/app/node_modules/.pnpm/zigbee-herdsman@3.2.0/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:686:9) 
at setupAttributes (/app/node_modules/.pnpm/zigbee-herdsman-converters@21.11.0/node_modules/src/lib/modernExtend.ts:158:17) 
at result.configure (/app/node_modules/.pnpm/zigbee-herdsman-converters@21.11.0/node_modules/src/lib/modernExtend.ts:1946:29) 
at Object.configure (/app/node_modules/.pnpm/zigbee-herdsman-converters@21.11.0/node_modules/src/index.ts:257:21) 
at Configure.configure (/app/lib/extension/configure.ts:124:13))
```

Looking at the generic `electricityMeter`, the two ways to disable reporting for `activePower` seem to be

* Set `cluster: 'metering'` to disable the HA activePower measurement that the device doesn't support, only leaving SE instantaneousDemand. But this has the side effect of removing voltage and current readings.
* Set `power: false` to entirely disable power measurements.

Fundamentally, it seems this device needs to enable power on the SE cluster and voltage/current on the HA cluster independently, which currently doesn't seem possible by extending the generic electricityMeter object.

This is as far as I've gotten without setting up a dev environment, only relying on an external converter to test things out. 

For reference, this is my final `extend` configuration in an external converter:
```
        extend: [electricityMeter({
		threePhase: true,
		cluster: 'metering', // or power: false
		voltage: {min: 60, max: 3600, change: 0},
		current: {min: 60, max: 3600, change: 0},
		fzMetering: fz.metering_datek,
		producedEnergy: true
	}), temperature()],
```

### What did you expect to happen?

I expect the meter reader to not have an onoff cluster, and to report power using the SE metering cluster and voltage/current using the HA electricity measurement cluster, despite not exposing the power measurement in the HA electricity measurement cluster.

### Zigbee2MQTT version

1.42.0-dev commit: 240ab43f2d7924cb20af39c040871da54abb8bf5

### Adapter firmware version

7.4.5 [GA]

### Adapter

Silicon Labs EFR32 dev kit running ncp-uart-hw reference firmware with ember driver

### Setup

Plain in Docker on x86-64

**Comment by mellbye** [comment]
Realized that this can be worked around by extending the `electricityMeter` twice:

```
extend: [
	electricityMeter({
		cluster: 'metering',
		fzMetering: fz.metering_datek,
		producedEnergy: true
	}),
        electricityMeter({
		threePhase: true,
		cluster: 'electrical',
		power: false,
		voltage: {min: 60, max: 3600, change: 0},
		current: {min: 60, max: 3600, change: 0},
		fzMetering: fz.metering_datek,
	}), temperature()],
```
