### ISSUE TITLE
npm install fails on armv7h

### ISSUE THREAD

**Issue by mr2c12** [Koenkk/zigbee2mqtt#2568]
Trying to install Zigbee2mqtt in virtualenv on an Orange PI 2 Plus.
It's quite an old board that run Archlinux.

The 'npm install' at step 2. Installing fails. The error is not clear to me:

> 16796 info lifecycle prebuild-install@5.3.3~install: prebuild-install@5.3.3
> 16797 silly install @serialport/bindings@8.0.4
> 16798 info lifecycle @serialport/bindings@8.0.4~install: @serialport/bindings@8.0.4
> 16799 verbose lifecycle @serialport/bindings@8.0.4~install: unsafe-perm in lifecycle false
> 16800 verbose lifecycle @serialport/bindings@8.0.4~install: PATH: /opt/zigbee2mqtt/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/zigbee2mqtt/node_mod
> ules/zigbee-herdsman/node_modules/@serialport/bindings/node_modules/.bin:/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/.bin:/opt/zigbee2mqtt/node_modules/.b
> in:/opt/zigbee2mqtt/lib/node_modules/.bin:/opt/zigbee2mqtt/bin:/opt/zigbee2mqtt/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/
> bin/core_perl
> 16801 verbose lifecycle @serialport/bindings@8.0.4~install: CWD: /opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/@serialport/bindings
> 16802 silly lifecycle @serialport/bindings@8.0.4~install: Args: [ '-c',
> 16802 silly lifecycle   'prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild' ]
> 16803 silly lifecycle @serialport/bindings@8.0.4~install: Returned: code: 1  signal: null
> 16804 info lifecycle @serialport/bindings@8.0.4~install: Failed to exec install script
> 16805 timing action:install Completed in 7524ms
> 16806 verbose unlock done using /root/.npm/_locks/staging-dfa04a252d7da3ba.lock for /opt/zigbee2mqtt/node_modules/.staging
> 16807 timing stage:rollbackFailedOptional Completed in 33609ms
> 16808 timing stage:runTopLevelLifecycles Completed in 303944ms
> 16809 silly saveTree zigbee2mqtt@1.8.0
> 16809 silly saveTree +-- ajv@6.10.2
> 16809 silly saveTree | +-- fast-deep-equal@2.0.1
> 16809 silly saveTree | +-- fast-json-stable-stringify@2.1.0

<cut here>

> 16810 warn tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
> 16811 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/zigbee-herdsman/node_modules/fsevents):
> 16812 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
> 16813 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
> 16813 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
> 16813 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
> 16813 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: arm
> 16814 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
> 16815 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
> 16816 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
> 16816 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
> 16816 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
> 16816 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: arm
> 16817 verbose stack Error: @serialport/bindings@8.0.4 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
> 16817 verbose stack Exit status 1
> 16817 verbose stack     at EventEmitter.<anonymous> (/opt/zigbee2mqtt/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
> 16817 verbose stack     at EventEmitter.emit (events.js:189:13)
> 16817 verbose stack     at ChildProcess.<anonymous> (/opt/zigbee2mqtt/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 16817 verbose stack     at ChildProcess.emit (events.js:189:13)
> 16817 verbose stack     at maybeClose (internal/child_process.js:970:16)
> 16817 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> 16818 verbose pkgid @serialport/bindings@8.0.4
> 16819 verbose cwd /opt/zigbee2mqtt
> 16820 verbose Linux 3.4.39
> 16821 verbose argv "/opt/zigbee2mqtt/bin/node" "/opt/zigbee2mqtt/bin/npm" "install"
> 16822 verbose node v10.15.1
> 16823 verbose npm  v6.4.1
> 16824 error code ELIFECYCLE
> 16825 error errno 1
> 16826 error @serialport/bindings@8.0.4 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
> 16826 error Exit status 1
> 16827 error Failed at the @serialport/bindings@8.0.4 install script.
> 16827 error This is probably not a problem with npm. There is likely additional logging output above.
> 16828 verbose exit [ 1, true ]

I don't understand what is wrong here. I hope I installed every dependency required.
Am I missing something?

**Comment by mr2c12** [comment]
I forgot to add that I am running "npm install" as root.
I will repeat the installation following the guide (i.e., with a normal user) and let you know.

**Comment by mr2c12** [comment]
I finally succeed to complete the installation. There were a lot of problems in the original distro.
Running npm install as normal user, anyway, helped a lot and probably fixed my problem.
