### ISSUE TITLE
zigbee/bridge/configure results error

### ISSUE THREAD

**Issue by Kryzek** [Koenkk/zigbee2mqtt#2588]
# Bug Report
## What happened
Issue payload `0x0017880104a5c9f1` (https://www.zigbee2mqtt.io/devices/8718696449691.html) to `zigbee2mqtt/bridge/configure`

## What did you expect to happen
According to documentation device should be re-configured.

## How to reproduce it (minimal and precise)
Issue payload `0x0017880104a5c9f1` to `zigbee2mqtt/bridge/configure` will result error.

## Debug Info
zigbee2mqtt version: 1.8.0-dev (commit #66b3bcb)
CC2652R firmware version: 20191106 

First try...
```
zigbee2mqtt:error 2019-12-22 10:01:22: Failed to configure '0x0017880104a5c9f1', attempt 1 (TypeError: mappedDevice.configure is not a function
    at DeviceConfigure.configure (/opt/zigbee2mqtt/lib/extension/deviceConfigure.js:92:32)
    at DeviceConfigure.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/deviceConfigure.js:51:14)
    at Controller.callExtensionMethod (/opt/zigbee2mqtt/lib/controller.js:322:44)
    at process._tickCallback (internal/process/next_tick.js:68:7))
```

A bit later after a few tries...
```
zigbee2mqtt:debug 2019-12-22 10:04:05: Received MQTT message on 'zigbee2mqtt/bridge/configure' with data '0x0017880104a5c9f1'
zigbee2mqtt:info  2019-12-22 10:04:05: Configuring '0x0017880104a5c9f1'
zigbee2mqtt:error 2019-12-22 10:04:05: Failed to configure '0x0017880104a5c9f1', attempt 3 (TypeError: mappedDevice.configure is not a function
    at DeviceConfigure.configure (/opt/zigbee2mqtt/lib/extension/deviceConfigure.js:92:32)
    at DeviceConfigure.onMQTTMessage (/opt/zigbee2mqtt/lib/extension/deviceConfigure.js:51:14)
    at Controller.callExtensionMethod (/opt/zigbee2mqtt/lib/controller.js:322:44)
    at process._tickCallback (internal/process/next_tick.js:68:7))
```

**Comment by Koenkk** [comment]
Your device does not require a configure (typically only sensor do this), fixed the error when trying this.
