### ISSUE TITLE
Tradfri error : E1524/E1810 Stack Dump

### ISSUE THREAD

**Issue by janlinders** [Koenkk/zigbee2mqtt#2659]
zigbee2mqtt version 1.6.0 (commit #e26ad2a)
 zigbee2mqtt:info 1/2/2020, 10:23:28 PM Coordinator firmware version: '20190608'

Tradfri Dimmer Error : Pressing ON button over 6 seconds

PROBLEM DETECTED
Please create an issue here with the contents of below: https://github.com/koenkk/zigbee2mqtt/issues
===== Stack =====
AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:

{
  cmdId: 'tradfriArrowSingle',
  frameCntl: {
    direction: 0,
    disDefaultRsp: 0,
    frameType: 1,
    manufSpec: 1
  },
  manufCode: 4476,
  payload: {
    value: 2
  },
  seqNum: 35
}

should loosely deep-equal

{
  cmdId: 'tradfriArrowSingle',
  frameCntl: {
    direction: 0,
    disDefaultRsp: 0,
    frameType: 1,
    manufSpec: 1
  },
  manufCode: 4476,
  payload: {
    value2: 0,
    value: 2
  },
  seqNum: 35
}
    at cb (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/lib/components/zcl.js:59:24)
    at /opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/deprecated/zcl-packet/lib/zcl.js:31:17
    at Dissolve.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/deprecated/zcl-packet/lib/functional.js:76:17)
    at Object.onceWrapper (events.js:300:26)
    at Dissolve.emit (events.js:210:5)
    at Dissolve.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/deprecated/dissolve-chunks/index.js:65:29)
    at Dissolve.emit (events.js:210:5)
    at emitReadable_ (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/readable-stream/lib/_stream_readable.js:456:10)
    at emitReadable (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/readable-stream/lib/_stream_readable.js:450:7)
    at readableAddChunk (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/readable-stream/lib/_stream_readable.js:206:11)
===== Buffer =====
{
  type: 'Buffer',
  data: [
    5, 124, 17, 35, 7,
    2,   0,  0,  0
  ]
}
===== Arguments =====
<Buffer 05 7c 11 23 07 02 00 00 00> 5
===== zcl-packet parse =====
{"frameCntl":{"frameType":1,"manufSpec":1,"direction":0,"disDefaultRsp":0},"manufCode":4476,"seqNum":35,"cmdId":"tradfriArrowSingle","payload":{"value":2}}
===== zcl =====
{"frameCntl":{"frameType":1,"manufSpec":1,"direction":0,"disDefaultRsp":0},"manufCode":4476,"seqNum":35,"cmdId":"tradfriArrowSingle","payload":{"value":2,"value2":0}}
===============

**Comment by Koenkk** [comment]
This has already been fixed in zigbee2mqtt 1.7 >
