### ISSUE TITLE
Timeout problem

### ISSUE THREAD

**Issue by develop221** [Koenkk/zigbee2mqtt#2685]
Hallo,
I'm trying develop my own zigbee device. Device seems to be working, but have a specific problem: After successfully joining , device is working and everything is OK. Then, after changing permit_join to false and restarting, device no more responding. 
Version : zigbee2mqtt version 1.8.0 (commit #da4d26a)
Logs:
debug 2020-01-06 15:20:46: Received MQTT message on 'zigbee2mqtt/0x00158d00022939a1/set' with data 'OFF'
debug 2020-01-06 15:20:46: Publishing 'set' 'state' to '0x00158d00022939a1'
debug 2020-01-06 15:20:55: Saving state to file /opt/zigbee2mqtt/data/state.json
error 2020-01-06 15:21:01: Publish 'set' 'state' to '0x00158d00022939a1' failed: 'Error: Timeout - 62212 - 2 - 5 - 6 - 11 after 15000ms'
debug 2020-01-06 15:21:01: Error: Timeout - 62212 - 2 - 5 - 6 - 11 after 15000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
info  2020-01-06 15:21:01: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to '0x00158d00022939a1' failed: 'Error: Timeout - 62212 - 2 - 5 - 6 - 11 after 15000ms'","meta":{"friendly_name":"0x00158d00022939a1"}}'

Any idea?

**Comment by develop221** [comment]
Sorry I didn't read issue #2677 before my post. These issues look similar.
