### ISSUE TITLE
Swapping to different cc1352P-2 adapter not working

### ISSUE THREAD

**Issue by tabnul** [Koenkk/zigbee2mqtt#2873]
# Bug Report
## What happened
I recently changed from cc2531 to cc1352P-2 adapter.
I am doing some tests currently and very impressed with the speed and stability.

However there is one problem; i have an active-passive setup with 2 sticks/adapters to prevent long downtime. With the CC2531 stick it functions correctly: after swapping sticks it takes a while for the network to settle down but after that everything works fine.

When i swap the  cc1352P-2 adapter, zigbee2mqtt won't even start.
Both adapters flashed to the same version.

The error below occurs on startup of zigbee2mqtt. 

## What did you expect to happen
Zigbee2mqtt to start normally and use the new adapter as coordinator for the zigbee network.

## How to reproduce it (minimal and precise)
Swap the cc1352P-2 with a different adapter with the same firmware.
 
## Debug Info
zigbee2mqtt version: 1.9
cc1352P-2 firmware version: CC1352P_2_20191106

LOG:
```
zigbee2mqtt:info  2020-02-02 08:23:15: Logging to console and directory: '/share/zigbee2mqtt/log/2020-02-02.08-23-15'
zigbee2mqtt:debug 2020-02-02 08:23:15: Removing old log directory '/share/zigbee2mqtt/log/2020-02-02.08-22-38'
zigbee2mqtt:debug 2020-02-02 08:23:15: Loaded state from file /share/zigbee2mqtt/state.json
zigbee2mqtt:info  2020-02-02 08:23:15: Starting zigbee2mqtt version 1.9.0 (commit #unknown)
zigbee2mqtt:info  2020-02-02 08:23:15: Starting zigbee-herdsman...
zigbee2mqtt:debug 2020-02-02 08:23:15: Using zigbee-herdsman with settings: '{"network":{"panID":6759,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[21],"networkKey":"HIDDEN"},"databasePath":"/share/zigbee2mqtt/database.db","databaseBackupPath":"/share/zigbee2mqtt/database.db.backup","backupPath":"/share/zigbee2mqtt/coordinator_backup.json","serialPort":{"baudRate":115200,"rtscts":true,"path":"/dev/ttyACM0"}}'
zigbee2mqtt:error 2020-02-02 08:23:17: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-02-02 08:23:17: Failed to start zigbee
zigbee2mqtt:error 2020-02-02 08:23:17: Exiting...
zigbee2mqtt:error 2020-02-02 08:23:17: Error: SREQ '--> SYS - osalNvItemInit - {"id":33,"offset":0,"osal":true,"product":-1,"value":[53,5,2,51,20,51,0,30,0,0,0,1,5,1,143,0,7,0,2,5,30,0,0,0,21,0,0,0,0,0,0,0,0,0,0,0,103,26,8,0,0,0,32,0,15,15,4,0,1,0,0,0,1,0,0,0,0,221,221,221,221,221,221,221,221,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,3,0,1,120,10,1,0,0,0,151,13,0,0],"len":116,"initvalue":[53,5,2,51,20,51,0,30,0,0,0,1,5,1,143,0,7,0,2,5,30,0,0,0,21,0,0,0,0,0,0,0,0,0,0,0,103,26,8,0,0,0,32,0,15,15,4,0,1,0,0,0,1,0,0,0,0,221,221,221,221,221,221,221,221,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,3,0,1,120,10,1,0,0,0,151,13,0,0],"initlen":116}' failed with status '0' (expected '9')
    at Znp.<anonymous> (/zigbee2mqtt-1.9.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:246:27)
    at Generator.next (<anonymous>)
    at fulfilled (/zigbee2mqtt-1.9.0/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:5:58)
npm
 
ERR! code ELIFECYCLE
npm ERR! errno 1
npm
 ERR! zigbee2mqtt@1.9.0 start: `node index.js`
npm
 ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.9.0 start script.
npm ERR!
 This is probably not a problem with npm. There is likely additional logging output above.
npm
 ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-02T07_23_17_139Z-debug.log
2020-02-02T08:23:17: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2020-02-02T08:23:17: PM2 log: App [npm:0] starting in -fork mode-
2020-02-02T08:23:17: PM2 log: App [npm:0] online
> zigbee2mqtt@1.9.0 start /zigbee2mqtt-1.9.0
> node index.js

```

**Comment by tabnul** [comment]
Reflashed second device fixed it. Something must have gone wrong at the intial flash. 
Sorry to bother, but good for the archive :)
donation on its way.
