### ISSUE TITLE
Self singed certificates with secured broker

### ISSUE THREAD

**Issue by ochstobi** [Koenkk/zigbee2mqtt#3068]
I try to connect zigbee2mqtt to an secured mqtt broker (mosquitto). I have generated self signed certificates and stuff and edited the configuration.yaml to connect to the secured broker.
But I got the following error which indicates that self signed certificates are not allowed?

zigbee2mqtt:info  2020-03-05 09:58:30: Connecting to MQTT server at mqtt://myserver:8883
events.js:288
      throw er; // Unhandled 'error' event
      ^
Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1473:34)
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket._finishInit (_tls_wrap.js:916:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:686:12)
Emitted 'error' event on MqttClient instance at:
    at TLSSocket.handleTLSerrors (/app/node_modules/mqtt/lib/connect/tls.js:26:18)
    at TLSSocket.emit (events.js:323:22)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.11.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.11.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-05T08_58_30_602Z-debug.log

**Comment by svrooij** [comment]
If you generated a certificate, why would that make it the broker secured?

According to the [docs](https://www.npmjs.com/package/mqtt#mqttclientstreambuilder-options) it’s possible to allow self signed certificates by setting `rejectUnauthorized: false`. But I’m not sure if zigbee2mqtt exposes this option.
