### ISSUE TITLE
 Failed to call 'OTAUpdate' 'onZigbeeEvent'

### ISSUE THREAD

**Issue by ccorderod** [Koenkk/zigbee2mqtt#3110]
# Bug Report
## What happened
error 2020-03-11 23:26:32: Failed to call 'OTAUpdate' 'onZigbeeEvent'
## How to reproduce it (minimal and precise)
Don't know.
`error 2020-03-11 23:26:32: Failed to call 'OTAUpdate' 'onZigbeeEvent' (Error: CommandResponse 0x0017880104b6ded0/2 genOta.queryNextImageResponse({"status":152}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Data request failed with error: 'MAC channel access failure' (225))
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:359:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))
error 2020-03-11 23:26:42: Failed to call 'OTAUpdate' 'onZigbeeEvent' (Error: CommandResponse 0x0017880104b6ded0/2 genOta.queryNextImageResponse({"status":152}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Data request failed with error: 'MAC channel access failure' (225))
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:359:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))
error 2020-03-11 23:26:52: Failed to call 'OTAUpdate' 'onZigbeeEvent' (Error: CommandResponse 0x0017880104b6ded0/2 genOta.queryNextImageResponse({"status":152}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Data request failed with error: 'MAC no ack' (233))
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:359:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))
error 2020-03-11 23:27:03: Failed to call 'OTAUpdate' 'onZigbeeEvent' (Error: CommandResponse 0x0017880104b6ded0/2 genOta.queryNextImageResponse({"status":152}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Data request failed with error: 'MAC channel access failure' (225))
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:359:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))
`
## Debug Info
zigbee2mqtt version: 1.11.0-dev commit 9b592d4

CC253X firmware version: cc1352-p2 - firmware 20200306

**Comment by ccorderod** [comment]
Fixed after reflashing the coordinator again.
