### ISSUE TITLE
Problems after update to 1.12.0

### ISSUE THREAD

**Issue by Hubschra01** [Koenkk/zigbee2mqtt#3162]
# Bug Report
## What happened
alter update on 1.12.0 my Coordinator Stick will not work. 
Every 10 sec i get a new log file with this content 
```
info  2020-03-20 15:34:24: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2020-03-20.15-34-24' filename: log.txt
debug 2020-03-20 15:34:24: Removing old log directory '/opt/zigbee2mqtt/data/log/2020-03-20.15-29-50'
debug 2020-03-20 15:34:25: Loaded state from file /opt/zigbee2mqtt/data/state.json
info  2020-03-20 15:34:25: Starting zigbee2mqtt version 1.12.0 (commit #840b9d9)
info  2020-03-20 15:34:25: Starting zigbee-herdsman...
debug 2020-03-20 15:34:25: Using zigbee-herdsman with settings: '{"network":{"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11],"networkKey":"HIDDEN"},"databasePath":"/opt/zigbee2mqtt/data/database.db","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","serialPort":{"baudRate":115200,"rtscts":true,"path":null}}'
error 2020-03-20 15:34:32: Error while starting zigbee-herdsman
```

Today I remove and make a fresh install of zigbee2Mqtt.
After i configurate a Tradfri Signal Repeater Zigbee2MqTT stop with Errors.
here the logs

## Debug Info
npm:
```0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zigbee2mqtt@1.12.0~prestart: zigbee2mqtt@1.12.0
6 info lifecycle zigbee2mqtt@1.12.0~start: zigbee2mqtt@1.12.0
7 verbose lifecycle zigbee2mqtt@1.12.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle zigbee2mqtt@1.12.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/zigbee2mqtt/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle zigbee2mqtt@1.12.0~start: CWD: /opt/zigbee2mqtt
10 silly lifecycle zigbee2mqtt@1.12.0~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle zigbee2mqtt@1.12.0~start: Returned: code: 1  signal: null
12 info lifecycle zigbee2mqtt@1.12.0~start: Failed to exec start script
13 verbose stack Error: zigbee2mqtt@1.12.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid zigbee2mqtt@1.12.0
15 verbose cwd /opt/zigbee2mqtt
16 verbose Linux 4.19.97-v7+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error zigbee2mqtt@1.12.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the zigbee2mqtt@1.12.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
zigbee2MQTT log
```
info  2020-03-21 16:22:42: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2020-03-21.16-22-42' filename: log.txt
debug 2020-03-21 16:22:42: Can't load state from file /opt/zigbee2mqtt/data/state.json (doesn't exist)
info  2020-03-21 16:22:42: Starting zigbee2mqtt version 1.12.0 (commit #840b9d9)
info  2020-03-21 16:22:42: Starting zigbee-herdsman...
debug 2020-03-21 16:22:42: Using zigbee-herdsman with settings: '{"network":{"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11],"networkKey":"HIDDEN"},"databasePath":"/opt/zigbee2mqtt/data/database.db","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","serialPort":{"baudRate":115200,"rtscts":true,"path":"/dev/ttyACM0"}}'
info  2020-03-21 16:22:45: zigbee-herdsman started
info  2020-03-21 16:22:45: Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}'
debug 2020-03-21 16:22:45: Zigbee network parameters: {"panID":6754,"extendedPanID":"0xdddddddddddddddd","channel":11}
info  2020-03-21 16:22:45: Currently 0 devices are joined:
warn  2020-03-21 16:22:45: `permit_join` set to  `true` in configuration.yaml.
warn  2020-03-21 16:22:45: Allowing new devices to join.
warn  2020-03-21 16:22:45: Set `permit_join` to `false` once you joined all devices.
info  2020-03-21 16:22:45: Zigbee: allowing new devices to join.
info  2020-03-21 16:22:45: Connecting to MQTT server at mqtt://localhost
info  2020-03-21 16:22:45: Connected to MQTT server
info  2020-03-21 16:22:45: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
info  2020-03-21 16:22:46: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.12.0","commit":"840b9d9","coordinator":{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}},"log_level":"debug","permit_join":true}'
warn  2020-03-21 16:26:57: Device '0x680ae2fffe1c4e9b' left the network
info  2020-03-21 16:26:57: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_removed","message":"left_network","meta":{"friendly_name":"0x680ae2fffe1xxxxx"}}'
info  2020-03-21 16:27:09: Device '0x680ae2fffe1c4e9b' joined
info  2020-03-21 16:27:09: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x680ae2fffe1xxxxx"}}'
info  2020-03-21 16:27:09: Starting interview of '0x680ae2fffe1c4e9b'
info  2020-03-21 16:27:09: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x680ae2fffe1xxxxx"}}'
debug 2020-03-21 16:27:12: Device '0x680ae2fffe1c4e9b' announced itself
info  2020-03-21 16:27:12: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0x680ae2fffe1xxxxx"}}'
debug 2020-03-21 16:27:19: Received Zigbee message from '0x680ae2fffe1xxxxx', type 'readResponse', cluster 'genBasic', data '{"modelId":"TRADFRI Signal Repeater","manufacturerName":"IKEA of Sweden"}' from endpoint 1 with groupID 0
info  2020-03-21 16:27:19: MQTT publish: topic 'zigbee2mqtt/0x680ae2fffe1xxxxx', payload '{"linkquality":36,"last_seen":"2020-03-21T16:27:19+01:00"}'
debug 2020-03-21 16:27:19: Received Zigbee message from '0x680ae2fffe1xxxxx', type 'readResponse', cluster 'genBasic', data '{"powerSource":1,"zclVersion":3}' from endpoint 1 with groupID 0
info  2020-03-21 16:27:19: MQTT publish: topic 'zigbee2mqtt/0x680ae2fffe1xxxxx', payload '{"linkquality":36,"last_seen":"2020-03-21T16:27:19+01:00"}'
debug 2020-03-21 16:27:20: Received Zigbee message from '0x680ae2fffe1xxxxx', type 'readResponse', cluster 'genBasic', data '{"appVersion":33,"stackVersion":98}' from endpoint 1 with groupID 0
info  2020-03-21 16:27:20: MQTT publish: topic 'zigbee2mqtt/0x680ae2fffe1xxxxx', payload '{"linkquality":36,"last_seen":"2020-03-21T16:27:20+01:00"}'
debug 2020-03-21 16:27:20: Received Zigbee message from '0x680ae2fffe1xxxxx', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1,"dateCode":"20190311"}' from endpoint 1 with groupID 0
info  2020-03-21 16:27:20: MQTT publish: topic 'zigbee2mqtt/0x680ae2fffe1xxxxx', payload '{"linkquality":36,"last_seen":"2020-03-21T16:27:20+01:00"}'
debug 2020-03-21 16:27:20: Received Zigbee message from '0x680ae2fffe1xxxxx', type 'readResponse', cluster 'genBasic', data '{"swBuildId":"2.2.005"}' from endpoint 1 with groupID 0
info  2020-03-21 16:27:20: MQTT publish: topic 'zigbee2mqtt/0x680ae2fffe1xxxxx', payload '{"linkquality":36,"last_seen":"2020-03-21T16:27:20+01:00"}'
info  2020-03-21 16:27:20: Successfully interviewed '0x680ae2fffe1xxxxx', device has successfully been paired
info  2020-03-21 16:27:20: Device '0x680ae2fffe1xxxxx' is supported, identified as: IKEA TRADFRI signal repeater (E1746)
info  2020-03-21 16:27:20: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x680ae2fffe1xxxxx","model":"E1746","vendor":"IKEA","description":"TRADFRI signal repeater","supported":true}}'
info  2020-03-21 16:27:20: Configuring '0x680ae2fffe1xxxxx'
info  2020-03-21 16:27:20: Successfully configured '0x680ae2fffe1xxxxx'
error 2020-03-21 16:27:22: Adapter disconnected, stopping


```
on CLI i get this  content after stop an start zigbee2Mqtt with 
`start npm`
```
[17:58:38] openhabian@openhab:/opt/zigbee2mqtt$ npm start

> zigbee2mqtt@1.12.0 start /opt/zigbee2mqtt
> node index.js

zigbee2mqtt:info  2020-03-21 17:59:00: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2020-03-21.17-59-00' filename: log.txt
zigbee2mqtt:debug 2020-03-21 17:59:00: Loaded state from file /opt/zigbee2mqtt/data/state.json
zigbee2mqtt:info  2020-03-21 17:59:01: Starting zigbee2mqtt version 1.12.0 (commit #840b9d9)
zigbee2mqtt:info  2020-03-21 17:59:01: Starting zigbee-herdsman...
zigbee2mqtt:debug 2020-03-21 17:59:01: Using zigbee-herdsman with settings: '{"network":{"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11],"networkKey":"HIDDEN"},"databasePath":"/opt/zigbee2mqtt/data/database.db","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","serialPort":{"baudRate":115200,"rtscts":true,"path":"/dev/ttyACM0"}}'
zigbee2mqtt:error 2020-03-21 17:59:13: Error while starting zigbee-herdsman
zigbee2mqtt:error 2020-03-21 17:59:13: Failed to start zigbee
zigbee2mqtt:error 2020-03-21 17:59:13: Exiting...
zigbee2mqtt:error 2020-03-21 17:59:13: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:71:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:6:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.12.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.12.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/openhabian/.npm/_logs/2020-03-21T16_59_48_926Z-debug.log
```
## Harware
Headless Raspberry pi 3+ Hardware
The Stick (CC2531) software is from jun 2019.
Thanks 
André

**Comment by Koenkk** [comment]
Could you provide the zigbee herdsman debug log when the configure of the tradfri signal repeater happens?

To enable herdsman debug logging, see https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging

**Comment by Hubschra01** [comment]
Here is the log from the tradfri signal repeater when I send the update check via 
`zigbee2mqtt/bridge/ota_update/check` 

[https://hastebin.com/hesikaxeni.coffeescript](url)

**Comment by Hubschra01** [comment]
I disconnect the Stick from the pi and start a new interview by pressing the reset button of the Tradfri signal repeater. Afer the interview the Stick disconnected by Error...
[https://hastebin.com/dubupepeqo.coffeescript](url)

**Comment by Koenkk** [comment]
```
2020-03-25T13:34:45.789Z zigbee-herdsman:adapter:zStack:znp:log Port closed
2020-03-25T13:34:45.790Z zigbee-herdsman:controller:log Adapter disconnected'
```

it seems that the adapter disconnects, could it be a power issue? How is the CC2531 connected?

**Comment by Hubschra01** [comment]
The Adapter is directly plugged in the USB Port at the Raspberry Pi. Without any cable. 
The LED of the Stick is always on.
It´s possible the serial driver disconnect the Stick by Error ? I think the Error comes with the update...

**Comment by Koenkk** [comment]
If you think it comes with this update, can you check on which version it still works?

**Comment by Hubschra01** [comment]
I remember there were some bugs in the update process. I looked over the npm list and found some missing sentences requested by Zigbee-Herdman sentences at the bottom of the list.
is that normal.
[npm list](https://hastebin.com/sajefiqulo.pl)

**Comment by Koenkk** [comment]
No this is not related to this.

**Comment by Hubschra01** [comment]
I tested with 1.11.0 i think the Interview were stable but i don´t know why the Apapter disconnects...

`2020-03-28T19:18:34.504Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-03-28T19:19:01.689Z zigbee-herdsman:adapter:zStack:znp:log Port closed
2020-03-28T19:19:01.690Z zigbee-herdsman:controller:log Adapter disconnected'
`

[Lo1.11.0](https://hastebin.com/awupahuvey.coffeescript)

After the disconnect the Stick isn´t aviable I have to remove the Stick from the USB Port an reconnect it.
Is the Stick buggy?

**Comment by Koenkk** [comment]
So on 1.11.0 the same issue? This means it's not related to the update?

Maybe the stick is buggy indeed.

**Comment by Hubschra01** [comment]
Tomorrow i will give another Stick a try with 1.11.0

**Comment by Hubschra01** [comment]
It seems to be the Stick was defect. I test a new on from a friend and this Stick works fine on 1.11.0
Later i will try with 1.12.0

**Comment by pixeldoc2000** [comment]
@Hubschra01 

Maybe reflash the stick with the latest firmware?

Otherwise i guess is a power issus. maybe connect the stick via a powered usb hub.

**Comment by Hubschra01** [comment]
Hi,
got a new Stick and this this works fine since 3 days. So I think the Stick has an issuse. I will try to fash the the stick later when i get a cheap cc debugger.
So I will close this.
Thanks for help
