### ISSUE TITLE
V1.12.0 - Trying to pair a new device gives errors

### ISSUE THREAD

**Issue by YogoGit** [Koenkk/zigbee2mqtt#3225]
# Bug Report
## What happened
Attempting to pair a new device failed.

## What did you expect to happen
I expected to pair the device.  When doing so, the following errors occurred.
```
zigbee2mqtt:info  2020-03-28 19:56:51: MQTT publish: topic 'zigbee2mqtttest/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x00158d0002c5b501"}}'
zigbee2mqtt:error 2020-03-28 19:56:51: Failed to call 'DeviceEvent' 'onZigbeeEvent' (TypeError: zigbeeHerdsmanConverters.onEvent is not a function
    at DeviceEvent.callOnEvent (/Users/nate/src/zigbee2mqtt/lib/extension/deviceEvent.js:24:34)
    at DeviceEvent.onZigbeeEvent (/Users/nate/src/zigbee2mqtt/lib/extension/deviceEvent.js:13:18)
    at Controller.callExtensionMethod (/Users/nate/src/zigbee2mqtt/lib/controller.js:346:44))
zigbee2mqtt:error 2020-03-28 19:56:51: Failed to call 'DeviceEvent' 'onZigbeeEvent' (TypeError: zigbeeHerdsmanConverters.onEvent is not a function
    at DeviceEvent.callOnEvent (/Users/nate/src/zigbee2mqtt/lib/extension/deviceEvent.js:24:34)
    at DeviceEvent.onZigbeeEvent (/Users/nate/src/zigbee2mqtt/lib/extension/deviceEvent.js:13:18)
    at Controller.callExtensionMethod (/Users/nate/src/zigbee2mqtt/lib/controller.js:346:44))
```

## How to reproduce it (minimal and precise)
Start up zigbee2mqtt, press the pairing button my device, watch it fail. :(

Device used was https://www.zigbee2mqtt.io/devices/DJT11LM.html

## Debug Info
zigbee2mqtt version: 1.12.0
CC253X firmware version: CC2531_DEFAULT_20190608.zip

**Comment by YogoGit** [comment]
Never-mind, this is caused by trying to run an older version of the firmware without first running
`npm ci` before starting.
