### ISSUE TITLE
Problem with Script - Don't find errors...

### ISSUE THREAD

**Issue by apvienna** [Koenkk/zigbee2mqtt#3282]
# Bug Report
PS C:\users\andre\zigbee2mqtt> npm start

> zigbee2mqtt@1.12.0 start C:\users\andre\zigbee2mqtt
> node index.js

zigbee2mqtt:info  2020-04-03 14:51:49: Logging to console and directory: 'C:\users\andre\zigbee2mqtt\data\log\2020-04-03.14-51-49' filename: log.txt
C:\users\andre\zigbee2mqtt\lib\extension\deviceGroupMembership.js:6
const topicRegex = new RegExp(`^${settings.get().mqtt.base_topic}/bridge/device/(.+)/get_group_membership$`);
                                                     ^

TypeError: Cannot read property 'base_topic' of null
    at Object.<anonymous> (C:\users\andre\zigbee2mqtt\lib\extension\deviceGroupMembership.js:6:54)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\users\andre\zigbee2mqtt\lib\controller.js:17:40)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.12.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.12.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andre\AppData\Roaming\npm-cache\_logs\2020-04-03T12_51_49_254Z-debug.log

## What happened
First of all, I would like to apologise for my poor English. I'm new here and don't get the Zigbee USB Stick to run. always get the above error message after npm start and don't find out what I'm doing wrong. ask for your help. have already tried to fight me through all the information on this page.

## My Config
# Home Assistant integration (MQTT discovery)
homeassistant: false

# allow new devices to join

permit_join: true

# MQTT settings

mqtt:
  

# MQTT base topic for zigbee2mqtt MQTT messages
  
base_topic: zigbee2mqtt
  

# MQTT server URL
  
server: 'mqtt://localhost'
  

# MQTT server authentication, uncomment if required:
  
# User: 
# password: 

Serial:
  
 port: com3
 disable_led: false

## Debug Info
zigbee2mqtt version:
CC253X firmware version:

**Comment by Koenkk** [comment]
Make sure the indentation of your configuration file is correct, example can be found here https://www.zigbee2mqtt.io/information/configuration.html
