### ISSUE TITLE
Sometimes on pairing of new devices process exists with error

### ISSUE THREAD

**Issue by ciotlosm** [Koenkk/zigbee2mqtt#33]
Error:
```
2018-5-10 11:59:48 INFO Zigbee: allowing new devices to join.
spinlock: false []
/home/user/zigbee2mqtt/node_modules/q/q.js:155
                throw e;
                ^

Error: Unhandled "error" event. (Cannot get the Node Descriptor of the Device: 0x00158d000110828c)
    at ZShepherd.emit (events.js:185:19)
    at /home/user/zigbee2mqtt/node_modules/zigbee-shepherd/lib/components/controller.js:609:28
    at _rejected (/home/user/zigbee2mqtt/node_modules/q/q.js:864:24)
    at /home/user/zigbee2mqtt/node_modules/q/q.js:890:30
    at Promise.when (/home/user/zigbee2mqtt/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/user/zigbee2mqtt/node_modules/q/q.js:808:41)
    at /home/user/zigbee2mqtt/node_modules/q/q.js:624:44
    at runSingle (/home/user/zigbee2mqtt/node_modules/q/q.js:137:13)
    at flush (/home/user/zigbee2mqtt/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@0.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-05-10T09_03_52_289Z-debug.log
```

Debug:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/user/.nvm/versions/node/v8.8.1/bin/node',
1 verbose cli   '/home/user/.nvm/versions/node/v8.8.1/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.4.2
3 info using node@v8.8.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zigbee2mqtt@0.1.0~prestart: zigbee2mqtt@0.1.0
6 info lifecycle zigbee2mqtt@0.1.0~start: zigbee2mqtt@0.1.0
7 verbose lifecycle zigbee2mqtt@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle zigbee2mqtt@0.1.0~start: PATH: /home/user/.nvm/versions/node/v8.8.1/lib/node_modules/npm/bin/node-gyp-bin:/home/user/zigbee2mqtt/node_modules/.bin:/home/user/.nvm/versions/node/v8.8.1/bin:/usr/local/sbin:/usr/local/bin:/usr/local/apache-maven/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/go/bin:/home/user/esp/xtensa-esp32-elf/bin
9 verbose lifecycle zigbee2mqtt@0.1.0~start: CWD: /home/user/zigbee2mqtt
10 silly lifecycle zigbee2mqtt@0.1.0~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle zigbee2mqtt@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle zigbee2mqtt@0.1.0~start: Failed to exec start script
13 verbose stack Error: zigbee2mqtt@0.1.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/user/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid zigbee2mqtt@0.1.0
15 verbose cwd /home/user/zigbee2mqtt
16 verbose Darwin 17.5.0
17 verbose argv "/home/user/.nvm/versions/node/v8.8.1/bin/node" "/home/user/.nvm/versions/node/v8.8.1/bin/npm" "start"
18 verbose node v8.8.1
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 1
22 error zigbee2mqtt@0.1.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the zigbee2mqtt@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Seems this is related to timeouts during connection. I had this happen on the cube a couple of times. If I keep pressing "link" button during connection it gets through.

**Comment by ciotlosm** [comment]
Closing as duplicate of: https://github.com/Koenkk/zigbee2mqtt/issues/29
