### ISSUE TITLE
Ikea LED1738G7 get recognized as LED1733G7

### ISSUE THREAD

**Issue by swissbyte** [Koenkk/zigbee2mqtt#3330]
#3172 Bug Report
## What happened
I have connected, or tried to connect, a Ikea Tradfri LED1738G7 Bulb. 
The bulb gets recognized as LED1733G7 and is not working. 
The bulb keeps pulsing after the interview of the CC2531
The Bulb is placed 5cm away from the ZNP

Could be related to #3144 
Or even better to #2827 

Chipset: CC2531 flashed with CC2531ZNP-Prod.hex (latest, 10.06.2019)

Would you recommend to upgrade to CC2652R or CC2538?

## What did you expect to happen
I expected to get the Bulb recognized correctly

## How to reproduce it (minimal and precise)

Maybe someone has an idea, what could happened here. 

## Debug Info
```
zigbee2mqtt:info  2020-04-10 23:00:30: Device '0x086bd7fffe2f1b93' joined
zigbee2mqtt:info  2020-04-10 23:00:30: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x086bd7fffe2f1b93"}}'
zigbee2mqtt:info  2020-04-10 23:00:30: Starting interview of '0x086bd7fffe2f1b93'
zigbee2mqtt:info  2020-04-10 23:00:30: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x086bd7fffe2f1b93"}}'
zigbee2mqtt:info  2020-04-10 23:00:33: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0x086bd7fffe2f1b93"}}'
zigbee2mqtt:error 2020-04-10 23:01:30: Failed to interview '0x086bd7fffe2f1b93', device has not successfully been paired
zigbee2mqtt:info  2020-04-10 23:01:30: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_failed","meta":{"friendly_name":"0x086bd7fffe2f1b93"}}'
```

Additional info, when sending some value to the bulb: 

```
zigbee2mqtt:error 2020-04-10 21:56:41: Publish 'set' 'color_temp' to '0x086bd7fffe2f1b93' failed: 'Error: Command 0x086bd7fffe2f1b93/1 lightingColorCtrl.moveToColorTemp({"colortemp":257,"transtime":0}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":false}) failed (Error: Timeout - 15479 - 1 - 5 - 768 - 11 after 6000ms)
```

Update 2: 
I was able to switch the bulb on and off via zigbee 2 times. 
But the above messages still persists. 

Very strange
Many other devices (temp sensor, other tradfri bulbs, presence detecotr, remotes etc) are working without any problems

Update: 
After repeated connections, ive got a "no route" error:
```

zigbee2mqtt:error 2020-04-10 22:43:17: Publish 'set' 'brightness' to '0x086bd7fffe2f1b93' failed: 'Error: Command 0x086bd7fffe2f1b93/1 genLevelCtrl.moveToLevelWithOnOff({"level":98,"transtime":0}, {"timeout":6000,"manufacturerCode":null,"disableDefaultResponse":false}) failed (Error: Data request failed with error: 'No network route' (205))'
zigbee2mqtt:info  2020-04-10 22:43:17: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'brightness' to '0x086bd7fffe2f1b93' failed: 'Error: Command 0x086bd7fffe2f1b93/1 genLevelCtrl.moveToLevelWithOnOff({\"level\":98,\"transtime\":0}, {\"timeout\":6000,\"manufacturerCode\":null,\"disableDefaultResponse\":false}) failed (Error: Data request failed with error: 'No network route' (205))'","meta":{"friendly_name":"0x086bd7fffe2f1b93"}}'
```

Update: 

Looks like that the bulb did not send any descriptors... 

See here: 

```
2020-04-10T21:09:15.137Z zigbee-herdsman:controller:device Interview - node descriptor request failed for '0x086bd7fffe2f1b93', attempt 6
2020-04-10T21:09:15.139Z zigbee-herdsman:controller:device Interview - failed for device '0x086bd7fffe2f1b93' with error 'Error: Interview failed because can not get node descriptor ('0x086bd7fffe2f1b93')
```

Very strange

```
zigbee2mqtt:warn  2020-04-10 23:07:41: Device '0x086bd7fffe2f1b93' left the network
zigbee2mqtt:info  2020-04-10 23:07:41: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_removed","message":"left_network","meta":{"friendly_name":"0x086bd7fffe2f1b93"}}'
2020-04-10T21:07:41.969Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-04-10T21:08:10.259Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,11,69,200,0,0,229,111,54,25,0,75,18,0,12,118]
2020-04-10T21:08:10.261Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,11,69,200,0,0,229,111,54,25,0,75,18,0,12,118]
2020-04-10T21:08:10.262Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 11 - 2 - 5 - 200 - [0,0,229,111,54,25,0,75,18,0,12] - 118
2020-04-10T21:08:10.263Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - concentratorIndCb - {"srcaddr":0,"extaddr":"0x00124b0019366fe5","pktCost":12}
2020-04-10T21:08:10.264Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-04-10T21:08:15.025Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,12,69,202,255,185,147,27,47,254,255,215,107,8,0,0,215]
2020-04-10T21:08:15.026Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,12,69,202,255,185,147,27,47,254,255,215,107,8,0,0,215]
2020-04-10T21:08:15.027Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 12 - 2 - 5 - 202 - [255,185,147,27,47,254,255,215,107,8,0,0] - 215
2020-04-10T21:08:15.028Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - tcDeviceInd - {"nwkaddr":47615,"extaddr":"0x086bd7fffe2f1b93","parentaddr":0}
2020-04-10T21:08:15.032Z zigbee-herdsman:controller:log Device '0x086bd7fffe2f1b93' joined
2020-04-10T21:08:15.034Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-04-10T21:08:15.035Z zigbee-herdsman:controller:log Device '0x086bd7fffe2f1b93' accepted by handler
2020-04-10T21:08:15.035Z zigbee-herdsman:controller:log New device '0x086bd7fffe2f1b93' joined
2020-04-10T21:08:15.035Z zigbee-herdsman:controller:log Creating device '0x086bd7fffe2f1b93'
zigbee2mqtt:info  2020-04-10 23:08:15: Device '0x086bd7fffe2f1b93' joined
zigbee2mqtt:info  2020-04-10 23:08:15: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x086bd7fffe2f1b93"}}'
zigbee2mqtt:info  2020-04-10 23:08:15: Starting interview of '0x086bd7fffe2f1b93'
zigbee2mqtt:info  2020-04-10 23:08:15: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x086bd7fffe2f1b93"}}'
2020-04-10T21:08:15.075Z zigbee-herdsman:controller:log Interview '0x086bd7fffe2f1b93' start
2020-04-10T21:08:15.085Z zigbee-herdsman:controller:device Interview - start device '0x086bd7fffe2f1b93'
2020-04-10T21:08:15.092Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":47615,"nwkaddrofinterest":47615}
2020-04-10T21:08:15.093Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,255,185,255,185,35]
2020-04-10T21:08:15.106Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2020-04-10T21:08:15.107Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2020-04-10T21:08:15.107Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2020-04-10T21:08:15.107Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2020-04-10T21:08:15.108Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-04-10T21:08:18.374Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,12,69,202,255,185,147,27,47,254,255,215,107,8,0,0,215]
2020-04-10T21:08:18.375Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,12,69,202,255,185,147,27,47,254,255,215,107,8,0,0,215]
2020-04-10T21:08:18.375Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 12 - 2 - 5 - 202 - [255,185,147,27,47,254,255,215,107,8,0,0] - 215
2020-04-10T21:08:18.375Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - tcDeviceInd - {"nwkaddr":47615,"extaddr":"0x086bd7fffe2f1b93","parentaddr":0}
2020-04-10T21:08:18.376Z zigbee-herdsman:controller:log Device '0x086bd7fffe2f1b93' joined
2020-04-10T21:08:18.376Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-04-10T21:08:18.376Z zigbee-herdsman:controller:log Device '0x086bd7fffe2f1b93' accepted by handler
2020-04-10T21:08:18.377Z zigbee-herdsman:controller:log Not interviewing '0x086bd7fffe2f1b93', completed 'false', in progress 'true'
2020-04-10T21:08:18.463Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,13,69,193,144,225,144,225,147,27,47,254,255,215,107,8,142,21]
2020-04-10T21:08:18.464Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,13,69,193,144,225,144,225,147,27,47,254,255,215,107,8,142,21]
2020-04-10T21:08:18.464Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 13 - 2 - 5 - 193 - [144,225,144,225,147,27,47,254,255,215,107,8,142] - 21
2020-04-10T21:08:18.464Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - endDeviceAnnceInd - {"srcaddr":57744,"nwkaddr":57744,"ieeeaddr":"0x086bd7fffe2f1b93","capabilities":142}
2020-04-10T21:08:18.465Z zigbee-herdsman:controller:log Device announce '0x086bd7fffe2f1b93'
2020-04-10T21:08:18.465Z zigbee-herdsman:controller:log Device '0x086bd7fffe2f1b93' announced with new networkAddress '57744'
zigbee2mqtt:debug 2020-04-10 23:08:18: Device '0x086bd7fffe2f1b93' announced itself
zigbee2mqtt:info  2020-04-10 23:08:18: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0x086bd7fffe2f1b93"}}'
2020-04-10T21:08:18.478Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-04-10T21:08:21.644Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,69,196,144,225,0,243]
2020-04-10T21:08:21.645Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,69,196,144,225,0,243]
2020-04-10T21:08:21.645Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 5 - 196 - [144,225,0] - 243
2020-04-10T21:08:21.646Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - srcRtgInd - {"dstaddr":57744,"relaycount":0,"relaylist":[]}
2020-04-10T21:08:21.647Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-04-10T21:08:25.100Z zigbee-herdsman:controller:device Interview - node descriptor request failed for '0x086bd7fffe2f1b93', attempt 1
2020-04-10T21:08:25.102Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":57744,"nwkaddrofinterest":57744}
2020-04-10T21:08:25.103Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,144,225,144,225,35]
2020-04-10T21:08:25.116Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2020-04-10T21:08:25.117Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2020-04-10T21:08:25.117Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2020-04-10T21:08:25.118Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2020-04-10T21:08:25.118Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-04-10T21:08:35.107Z zigbee-herdsman:controller:device Interview - node descriptor request failed for '0x086bd7fffe2f1b93', attempt 2
2020-04-10T21:08:35.109Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":57744,"nwkaddrofinterest":57744}
2020-04-10T21:08:35.109Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,144,225,144,225,35]
2020-04-10T21:08:35.120Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2020-04-10T21:08:35.121Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2020-04-10T21:08:35.121Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2020-04-10T21:08:35.121Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2020-04-10T21:08:35.121Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-04-10T21:08:45.115Z zigbee-herdsman:controller:device Interview - node descriptor request failed for '0x086bd7fffe2f1b93', attempt 3
2020-04-10T21:08:45.117Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":57744,"nwkaddrofinterest":57744}
2020-04-10T21:08:45.118Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,144,225,144,225,35]
2020-04-10T21:08:45.131Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2020-04-10T21:08:45.132Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2020-04-10T21:08:45.132Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2020-04-10T21:08:45.133Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2020-04-10T21:08:45.133Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-04-10T21:08:55.122Z zigbee-herdsman:controller:device Interview - node descriptor request failed for '0x086bd7fffe2f1b93', attempt 4
2020-04-10T21:08:55.123Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":57744,"nwkaddrofinterest":57744}
2020-04-10T21:08:55.124Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,144,225,144,225,35]
2020-04-10T21:08:55.135Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2020-04-10T21:08:55.136Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2020-04-10T21:08:55.136Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2020-04-10T21:08:55.136Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2020-04-10T21:08:55.137Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-04-10T21:09:05.130Z zigbee-herdsman:controller:device Interview - node descriptor request failed for '0x086bd7fffe2f1b93', attempt 5
2020-04-10T21:09:05.132Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":57744,"nwkaddrofinterest":57744}
2020-04-10T21:09:05.133Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,144,225,144,225,35]
2020-04-10T21:09:05.145Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2020-04-10T21:09:05.146Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2020-04-10T21:09:05.146Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2020-04-10T21:09:05.147Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2020-04-10T21:09:05.148Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-04-10T21:09:15.137Z zigbee-herdsman:controller:device Interview - node descriptor request failed for '0x086bd7fffe2f1b93', attempt 6
2020-04-10T21:09:15.139Z zigbee-herdsman:controller:device Interview - failed for device '0x086bd7fffe2f1b93' with error 'Error: Interview failed because can not get node descriptor ('0x086bd7fffe2f1b93')
    at Device.<anonymous> (/zigbee2mqtt-1.12.0/node_modules/zigbee-herdsman/dist/controller/model/device.js:275:23)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.12.0/node_modules/zigbee-herdsman/dist/controller/model/device.js:6:65)'
2020-04-10T21:09:15.143Z zigbee-herdsman:controller:error Interview failed for '0x086bd7fffe2f1b93 with error 'Error: Interview failed because can not get node descriptor ('0x086bd7fffe2f1b93')'
zigbee2mqtt:error 2020-04-10 23:09:15: Failed to interview '0x086bd7fffe2f1b93', device has not successfully been paired
zigbee2mqtt:info  2020-04-10 23:09:15: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_failed","meta":{"friendly_name":"0x086bd7fffe2f1b93"}}'
```

**Comment by Koenkk** [comment]
- Is the CC2531 connected through a USB extension cable? 
- Can you try the following firmware: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing

**Comment by swissbyte** [comment]
Hi Koenkk 

Thank you so much for your answer. First of all i want to say thank you for all these hours you have invested into this project. 

I have flashed my CC2531 with the above mentioned firmware. The CC2531 is not connected through an extension cable. It is connected directly. 

The Bulb now works perfectly. But... it gets detected as LED1733G7 instead of LED1738G7
https://pastebin.com/1a4yWujR
What is the difference or what has changed in the above mentioned firmware?

Just as a sidenote. 

By the way, i saw that there is an upcoming support for the CC2538. 
Would you reccommend to switch to an CC2538 or CC2652?

Again, thank you so much for your engagement. I highly appreciate it.

**Comment by Koenkk** [comment]
I would recommend the CC2652 in case you are having stability issues and have a larger network 25/30+ devices.

Can you share your `database.db`? I think this is just a cosmetic issue and can easily be fixed.

**Comment by swissbyte** [comment]
Sure. Sorry for the delay. 
But im not exactly sure where the database.db is located in my hass.io zigbee2mqtt docker container
I will look for it. But the HW/SW is now working since 2 days.

**Comment by Koenkk** [comment]
@swissbyte I don't use hassio but it should have a data directory, if this doesn't help please ask this question here: https://github.com/danielwelch/hassio-zigbee2mqtt
