### ISSUE TITLE
Zigbee2Mqtt crashing when trying to remove device.

### ISSUE THREAD

**Issue by CMDR-Sloma** [Koenkk/zigbee2mqtt#3387]
## What happened
I was trying to pair my new Wiser TRV to the Wiser Heating hub while having "permit_join = true" in config so as a result TRV was added to zigbee2mqtt as an unknown device which resulted in crashing the addon in HA. I don't want it to be paired with zigbee2mqtt so I changed the config to "permit_join = false" but now I can't remove the TRV from my config. Each time I try it crashes the addon and it forces it to restart.

## What did you expect to happen
To remove the device from network completely while using "zigbee2mqtt/bridge/config/remove"

I'm still on 1.6 and I don't want to upgrade because my current config is stable. I was running a newer version before but It was causing problems when pairing devices. 

Now, how I can remove that TRV from my network without crashing the whole system. Is there a way for me to edit my config manually?

## Debug Info
Zigbee2mqtt version: 1.6.0
Adapter hardware: CC2531 
Adapter firmware version: 20190315

**Comment by CMDR-Sloma** [comment]
Now I noticed zigbee2mqtt restarts every minute or so and it logs this error each time:

>   zigbee2mqtt:info 4/18/2020, 12:13:33 PM MQTT publish: topic 'zigbee2mqtt/CC2530Upstairs', payload '{"state":true,"led_state":false,"linkquality":63}'
/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/dist/zcl/utils.js:49
        throw new Error(`Cluster with key '${key}' does not exist`);
        ^
Error: Cluster with key '65027' does not exist
    at Object.getCluster (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/dist/zcl/utils.js:49:15)
    at Object.getAttributeLegacy (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/dist/zcl/index.js:39:27)
    at /zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/dist/lib/shepherd.js:122:36
    at Object._.forEach (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/node_modules/busyman/index.js:411:27)
    at ZShepherd.<anonymous> (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/dist/lib/shepherd.js:121:11)
    at ZShepherd.emit (events.js:198:13)
    at dispatchIncomingMsg (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/dist/lib/components/af.js:565:41)
    at Controller.zclIncomingMsgHandler (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/dist/lib/components/af.js:631:12)
    at Controller.emit (events.js:198:13)
    at Immediate.<anonymous> (/zigbee2mqtt-1.6.0/node_modules/zigbee-herdsman/dist/lib/components/af.js:640:23)
npm
 
ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.6.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
