### ISSUE TITLE
TypeError: zigbeeHerdsmanConverters.findByDevice is not a function

### ISSUE THREAD

**Issue by swissbyte** [Koenkk/zigbee2mqtt#3413]
# Bug Report
## What happened
After trying to pair a device, i get an TypeError: zigbeeHerdsmanConverters.findByDevice is not a function error

## How to reproduce it
After starting the pairing of the device, i get the error below

System: Win 10 x64
Node: 12.16.1
NPM: 6.14.4

## Debug Info
Zigbee2mqtt version:
Adapter hardware: CC2531
Adapter firmware version: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing

```
zigbee2mqtt:info  2020-04-23 14:43:02: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.12.2-dev","commit":"d073a7f","coordinator":{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190619}},"log_level":"info","permit_join":true}'
(node:71080) UnhandledPromiseRejectionWarning: TypeError: zigbeeHerdsmanConverters.findByDevice is not a function
    at Zigbee.resolveEntity (C:\code\node.js\zigbee2mqtt\lib\zigbee.js:226:54)
    at Controller.onZigbeeEvent (C:\code\node.js\zigbee2mqtt\lib\controller.js:187:44)
    at Zigbee.emit (events.js:311:20)
    at Controller.<anonymous> (C:\code\node.js\zigbee2mqtt\lib\zigbee.js:65:57)
    at Controller.emit (events.js:311:20)
    at Controller.<anonymous> (C:\code\node.js\zigbee2mqtt\node_modules\zigbee-herdsman\dist\controller\controller.js:330:22)
    at Generator.next (<anonymous>)
    at fulfilled (C:\code\node.js\zigbee2mqtt\node_modules\zigbee-herdsman\dist\controller\controller.js:5:58)
(node:71080) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:71080) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:71080) UnhandledPromiseRejectionWarning: TypeError: zigbeeHerdsmanConverters.findByDevice is not a function
    at Zigbee.resolveEntity (C:\code\node.js\zigbee2mqtt\lib\zigbee.js:226:54)
    at Controller.onZigbeeEvent (C:\code\node.js\zigbee2mqtt\lib\controller.js:187:44)
    at Zigbee.emit (events.js:311:20)
    at Controller.<anonymous> (C:\code\node.js\zigbee2mqtt\lib\zigbee.js:64:60)
    at Controller.emit (events.js:311:20)
    at Controller.<anonymous> (C:\code\node.js\zigbee2mqtt\node_modules\zigbee-herdsman\dist\controller\controller.js:342:22)
    at Generator.next (<anonymous>)
    at fulfilled (C:\code\node.js\zigbee2mqtt\node_modules\zigbee-herdsman\dist\controller\controller.js:5:58)
(node:71080) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by swissbyte** [comment]
When i try version: 1.12.0 instead, and try to pair a ikea tradfri remote, i got the following: 

```
zigbee2mqtt:info  2020-04-23 14:53:35: Device '0xd0cf5efffe35016f' joined
zigbee2mqtt:info  2020-04-23 14:53:35: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0xd0cf5efffe35016f"}}'
zigbee2mqtt:info  2020-04-23 14:53:35: Starting interview of '0xd0cf5efffe35016f'
zigbee2mqtt:info  2020-04-23 14:53:35: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0xd0cf5efffe35016f"}}'
zigbee2mqtt:info  2020-04-23 14:53:44: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0xd0cf5efffe35016f"}}'
zigbee2mqtt:warn  2020-04-23 14:54:01: Received message from unsupported device with Zigbee model 'undefined'
zigbee2mqtt:warn  2020-04-23 14:54:01: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
zigbee2mqtt:warn  2020-04-23 14:54:02: Received message from unsupported device with Zigbee model 'undefined'
zigbee2mqtt:warn  2020-04-23 14:54:02: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
```

I always get: "model 'undefined'"
