### ISSUE TITLE
Hue bulb fails to setup genOnOff reporting af upgrade (expected?)

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee2mqtt#3420]
# Bug Report
## What happened

I was testing joining of devices for #3177
And grabbed one of my Hue ones... I noticed it failed to setup genOnOff reporting.

It fails on up to date firmware ware because the device no longer supports it (*sad face*)

```
zigbee2mqtt:error 2020-04-24 13:23:10: Failed to setup reporting for '0x0017880104259333' - Error: ConfigureReporting 0x0017880104259333/11 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":300,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Timeout - 25453 - 11 - 97 - 6 - 7 after 10000ms)
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65)
```

I vaguely remember there already being a ticker for this, as I have update the reporting page on the doc site... but I can't find it anymore.

## What did you expect to happen
Reporting to be skipped for devices with a newer firmware, not sure this is currently possible though.

## How to reproduce it (minimal and precise)
Update a hue (C)WS bulb to the latest firmware, remove it from the network, pair it again.

## Debug Info
Zigbee2mqtt version: 1.12.2-dev (commit #63ecc15)
Adapter hardware: CC2531
Adapter firmware version: `{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20200410}}`

**Comment by sjorge** [comment]
Found it... well not the original one I was thinking about as I update the page longer ago... #3419, closing this one.
