### ISSUE TITLE
zigbee2mqtt crashing. Could it be too many deviceS?

### ISSUE THREAD

**Issue by onlymejosh** [Koenkk/zigbee2mqtt#3993]
# Bug Report
I have tried to add 4 new bulbs to my network. the bulbs are ` RS 229 T - Innr GU10` https://www.zigbee2mqtt.io/devices/RS_229_T.html `zigbee2mqtt` crashes and requires me to pull the usb and plug it back in again. Here are the related logs

```
winston:file: written true false
  mqttjs:client publish :: message `{"battery":100,"linkquality":60,"update_available":false,"occupancy":true,"temperature":19.5,"illuminance":24003,"illuminance_lux":250}` to topic `zigbee2mqtt/motion_sensor` +48s
  mqttjs:client publish :: qos 0 +0ms
  mqttjs:client MqttClient:publish: packet cmd: publish +0ms
  mqttjs:client _sendPacket :: (mqttjs_4ddf23d2) ::  start +1ms
  mqttjs:client sendPacket :: packet: {
  mqttjs:client   cmd: 'publish',
  mqttjs:client   topic: 'zigbee2mqtt/motion_sensor',
  mqttjs:client   payload: '{"battery":100,"linkquality":60,"update_available":false,"occupancy":true,"temperature":19.5,"illuminance":24003,"illuminance_lux":250}',
  mqttjs:client   qos: 0,
  mqttjs:client   retain: false,
  mqttjs:client   messageId: 26133,
  mqttjs:client   dup: false
  mqttjs:client } +0ms
  mqttjs:client sendPacket :: emitting `packetsend` +1ms
  mqttjs:client sendPacket :: writing to stream +0ms
  mqtt-packet:writeToStream generate called +48s
  mqtt-packet:writeToStream generate: packet.cmd: publish +0ms
  mqtt-packet:writeToStream publish: packet: { cmd: 'publish', topic: 'zigbee2mqtt/motion_sensor', payload: '{"battery":100,"linkquality":60,"update_available":false,"occupancy":true,"temperature":19.5,"illuminance":24003,"illuminance_lux":250}', qos: 0, retain: false, messageId: 26133, dup: false } +0ms
  mqtt-packet:writeToStream writeVarByteInt: writing to stream: <Buffer a2 01> +1ms
  mqtt-packet:writeToStream writeNumberCached: number: 25 +0ms
  mqtt-packet:writeToStream writeNumberCached: <Buffer 00 19> +0ms
  mqtt-packet:writeToStream publish: payload: '{"battery":100,"linkquality":60,"update_available":false,"occupancy":true,"temperature":19.5,"illuminance":24003,"illuminance_lux":250}' +1ms
  mqttjs:client sendPacket :: writeToStream result true +2ms
  mqttjs:client sendPacket :: invoking cb +0ms
  mqttjs:client _sendPacket :: (mqttjs_4ddf23d2) ::  end +0ms
  zigbee-herdsman:controller:endpoint DefaultResponse 0x001788010862db89/2 1030(10, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":1,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) +49s
  zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":15072,"destendpoint":2,"srcendpoint":1,"clusterid":1030,"transid":10,"options":0,"radius":30,"len":5,"data":{"type":"Buffer","data":[24,120,11,10,0]}} +49s
  zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,15,36,1,224,58,2,1,6,4,10,0,30,5,24,120,11,10,0,129] +49s
  serialport/stream _write 20 bytes of data +35ms
  serialport/binding-abstract write 20 bytes +121ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +35ms
  serialport/bindings/unixWrite Starting write 20 bytes offset 0 bytesToWrite 20 +49s
winston:file: logged 56543 debug 2020-07-27 20:28:57: Received Zigbee message from 'motion_sensor', type 'attributeReport', cluster 'msOccupancySensing', data '{"occupancy":1}' from endpoint 2 with groupID 0

winston:file: logged 56765 info  2020-07-27 20:28:57: MQTT publish: topic 'zigbee2mqtt/motion_sensor', payload '{"battery":100,"linkquality":60,"update_available":false,"occupancy":true,"temperature":19.5,"illuminance":24003,"illuminance_lux":250}'

  serialport/stream _read reading { start: 1038, toRead: 64498 } +10ms
  serialport/binding-abstract read +10ms
  serialport/bindings/unixRead Starting read +45ms
  serialport/bindings/unixWrite write returned: wrote 20 bytes +9ms
  serialport/bindings/unixWrite Finished writing 20 bytes +0ms
  serialport/stream binding.write write finished +2ms
  serialport/bindings/unixRead Finished read 6 bytes +2ms
  serialport/stream binding.read finished { bytesRead: 6 } +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,100,1,0,100] +12ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,1,0,100] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 1 - [0] - 100 +0ms
  zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequest - {"status":0} +49s
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
  serialport/stream _read reading { start: 1044, toRead: 64492 } +3ms
  serialport/binding-abstract read +5ms
  serialport/bindings/unixRead Starting read +3ms
  serialport/bindings/unixRead read error [Error: EAGAIN: resource temporarily unavailable, read] {
  errno: -11,
  code: 'EAGAIN',
  syscall: 'read'
} +1ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +0ms
  serialport/bindings/poller Polling for "readable" +53ms
  serialport/bindings/poller received "readable" +638ms
  serialport/bindings/unixRead Starting read +640ms
  serialport/bindings/unixRead Finished read 8 bytes +0ms
  serialport/stream binding.read finished { bytesRead: 8 } +642ms
  zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,69,196,183,48,0,5] +643ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,69,196,183,48,0,5] +0ms
  zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 5 - 196 - [183,48,0] - 5 +1ms
  zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - srcRtgInd - {"dstaddr":12471,"relaycount":0,"relaylist":[]} +691ms
  zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [] +1ms
  serialport/stream _read reading { start: 1052, toRead: 64484 } +2ms
  serialport/binding-abstract read +644ms
  serialport/bindings/unixRead Starting read +4ms
  serialport/bindings/unixRead read error [Error: EAGAIN: resource temporarily unavailable, read] {
  errno: -11,
  code: 'EAGAIN',
  syscall: 'read'
} +0ms
  serialport/bindings/unixRead waiting for readable because of code: EAGAIN +1ms
  serialport/bindings/poller Polling for "readable" +6ms
  serialport/bindings/poller error [Error: bad file descriptor] +266ms
  serialport/stream binding.read error [Error: bad file descriptor] +269ms
  serialport/stream disconnected [Error: bad file descriptor] +1ms
  serialport/stream #close +1ms
  serialport/binding-abstract close +272ms
  serialport/stream _read queueing _read for after open +1ms
  serialport/bindings/poller Stopping poller +5ms
  serialport/bindings/poller Destroying poller +1ms
  serialport/stream binding.close finished +6ms
  zigbee-herdsman:adapter:zStack:znp:log Port closed +2m
  zigbee-herdsman:controller:log Adapter disconnected' +970ms
zigbee2mqtt:error 2020-07-27 20:28:58: Adapter disconnected, stopping
winston:file: written true false
zigbee2mqtt:debug 2020-07-27 20:28:58: Saving state to file /opt/zigbee2mqtt/data/state.json
winston:file: written true false
zigbee2mqtt:info  2020-07-27 20:28:58: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'offline'
winston:file: written true false
  mqttjs:client publish :: message `offline` to topic `zigbee2mqtt/bridge/state` +960ms
  mqttjs:client publish :: qos 0 +0ms
  mqttjs:client MqttClient:publish: packet cmd: publish +0ms
  mqttjs:client _sendPacket :: (mqttjs_4ddf23d2) ::  start +0ms
  mqttjs:client sendPacket :: packet: {
  mqttjs:client   cmd: 'publish',
  mqttjs:client   topic: 'zigbee2mqtt/bridge/state',
  mqttjs:client   payload: 'offline',
  mqttjs:client   qos: 0,
  mqttjs:client   retain: true,
  mqttjs:client   messageId: 26134,
  mqttjs:client   dup: false
  mqttjs:client } +1ms
  mqttjs:client sendPacket :: emitting `packetsend` +0ms
  mqttjs:client sendPacket :: writing to stream +0ms
  mqtt-packet:writeToStream generate called +961ms
  mqtt-packet:writeToStream generate: packet.cmd: publish +0ms
  mqtt-packet:writeToStream publish: packet: { cmd: 'publish', topic: 'zigbee2mqtt/bridge/state', payload: 'offline', qos: 0, retain: true, messageId: 26134, dup: false } +0ms
  mqtt-packet:writeToStream writeVarByteInt: writing to stream: <Buffer 21> +1ms
  mqtt-packet:writeToStream writeNumberCached: number: 24 +0ms
  mqtt-packet:writeToStream writeNumberCached: <Buffer 00 18> +0ms
  mqtt-packet:writeToStream publish: payload: 'offline' +0ms
  mqttjs:client sendPacket :: writeToStream result true +1ms
  mqttjs:client sendPacket :: invoking cb +0ms
  mqttjs:client _sendPacket :: (mqttjs_4ddf23d2) ::  end +0ms
zigbee2mqtt:info  2020-07-27 20:28:58: Disconnecting from MQTT server
winston:file: written true false
  mqttjs:client end :: (mqttjs_4ddf23d2) +3ms
  mqttjs:client end :: cb? true +0ms
  mqttjs:client _clearReconnect : clearing reconnect timer +0ms
  mqttjs:client end :: (mqttjs_4ddf23d2) :: immediately calling finish +2ms
  mqttjs:client end :: (mqttjs_4ddf23d2) :: finish :: calling _cleanUp with force false +0ms
  mqttjs:client _cleanUp :: done callback provided for on stream close +1ms
  mqttjs:client _cleanUp :: forced? false +0ms
  mqttjs:client _cleanUp :: (mqttjs_4ddf23d2) :: call _sendPacket with disconnect packet +0ms
  mqttjs:client _sendPacket :: (mqttjs_4ddf23d2) ::  start +0ms
  mqttjs:client sendPacket :: packet: { cmd: 'disconnect' } +1ms
  mqttjs:client sendPacket :: emitting `packetsend` +0ms
  mqttjs:client sendPacket :: writing to stream +0ms
  mqtt-packet:writeToStream generate called +7ms
  mqtt-packet:writeToStream generate: packet.cmd: disconnect +0ms
  mqtt-packet:writeToStream writeVarByteInt: writing to stream: <Buffer 00> +1ms
  mqttjs:client sendPacket :: writeToStream result true +1ms
  mqttjs:client sendPacket :: invoking cb +0ms
  mqttjs:client _cleanUp :: clearing pingTimer +0ms
  zigbee-herdsman:controller:log Disable joining +112ms
zigbee2mqtt:error 2020-07-27 20:28:58: Failed to stop zigbee
winston:file: written true false
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.14.2 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.14.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-07-27T19_28_58_702Z-debug.log
pi@raspberrypi:/opt/zigbee2mqtt $ cat  /home/pi/.npm/_logs/2020-07-27T19_28_58_702Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zigbee2mqtt@1.14.2~prestart: zigbee2mqtt@1.14.2
6 info lifecycle zigbee2mqtt@1.14.2~start: zigbee2mqtt@1.14.2
7 verbose lifecycle zigbee2mqtt@1.14.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle zigbee2mqtt@1.14.2~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/zigbee2mqtt/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle zigbee2mqtt@1.14.2~start: CWD: /opt/zigbee2mqtt
10 silly lifecycle zigbee2mqtt@1.14.2~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle zigbee2mqtt@1.14.2~start: Returned: code: 1  signal: null
12 info lifecycle zigbee2mqtt@1.14.2~start: Failed to exec start script
13 verbose stack Error: zigbee2mqtt@1.14.2 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid zigbee2mqtt@1.14.2
15 verbose cwd /opt/zigbee2mqtt
16 verbose Linux 4.19.97-v7+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error zigbee2mqtt@1.14.2 start: `node index.js`
22 error Exit status 1
23 error Failed at the zigbee2mqtt@1.14.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
pi@raspberrypi:/opt/zigbee2mqtt $ cat data/configuration.yaml
homeassistant: true
permit_join: true
advanced:
  log_level: debug
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://homeslice.local:1883'
serial:
  port: /dev/ttyACM0
devices:
  '0x00178801083cc7ef':
    friendly_name: garden_downlight_1
  '0x00178801083cae7c':
    friendly_name: garden_downlight_2
  '0x00158d0003567a38':
    friendly_name: garden_planter
  '0x00158d000356894c':
    friendly_name: garden_sofa
  '0x00158d0003568af1':
    friendly_name: garden_fence
  '0x00158d000356df05':
    friendly_name: garden_tree
  '0x00178801080e09db':
    friendly_name: kitchen_kontrols
  '0x00158d0003ce7ee7':
    friendly_name: temperature_sensor
  '0x001788010862db89':
    friendly_name: motion_sensor
    temperature_precision: 1
    temperature_calibration: -1
  '0x00178801064df84f':
    friendly_name: living_room_pineapple
  '0x0017880102fe6da6':
    friendly_name: living_room_rodd
  '0x0017880102620a4c':
    friendly_name: living_room_ceiling
  '0x00178801026207dd':
    friendly_name: study_pineapple
  '0x0017880102fcec1d':
    friendly_name: study_ceiling
  '0x00178801032651d3':
    friendly_name: hallway_ceiling
  '0x000b57fffe8f718e':
    friendly_name: 0x000b57fffe8f718e
  '0x00158d0004632bf1':
    friendly_name: '0x00158d0004632bf1'
  '0x00158d0004632886':
    friendly_name: '0x00158d0004632886'
  '0x14b457fffe4af880':
    friendly_name: '0x14b457fffe4af880'
  '0x588e81fffe21f46a':
    friendly_name: alley_1
  '0x588e81fffe233426':
    friendly_name: alley_2
  '0x588e81fffe232770':
    friendly_name: '0x588e81fffe232770'

```

## What happened
zigbee unexpectedly crashes 
## How to reproduce it (minimal and precise)
Try and interact with one of the new bulbs or when trying to add another one of the ` RS 229 T - Innr GU10` bulbs
```
  '0x588e81fffe21f46a'
  '0x588e81fffe233426'
  '0x588e81fffe232770'
```

Which are:
```
info  2020-07-27 21:07:11: 0x588e81fffe21f46a (0x588e81fffe21f46a): RS 229 T - Innr GU10 spot 350 lm, dimmable, white spectrum (Router)
info  2020-07-27 21:07:11: 0x588e81fffe233426 (0x588e81fffe233426): RS 229 T - Innr GU10 spot 350 lm, dimmable, white spectrum (Router)
info  2020-07-27 21:07:11: 0x588e81fffe232770 (0x588e81fffe232770): RS 229 T - Innr GU10 spot 350 lm, dimmable, white spectrum (Router)
```

## Debug Info
Zigbee2mqtt version:
```
"name": "zigbee2mqtt",
"version": "1.14.2",
```
Adapter hardware: CC2531
Adapter firmware version:
```info  2020-07-27 21:07:11: Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}'```

**Comment by Koenkk** [comment]
The adapter crashes indeed, try switching to the source routing firmware which provides more stability: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing

**Comment by onlymejosh** [comment]
Does it correlate to the amount of devices I have? I'll switch the source out and try again. 

Is there anything else I can do? A different adapter etc?

**Comment by Koenkk** [comment]
@onlymejosh a more powerful adapter will also solve it probably, e.g. https://www.zigbee2mqtt.io/information/supported_adapters.html#electrolama-zig-a-zig-ah-zzh

**Comment by onlymejosh** [comment]
Great thanks -- Looks like the `Electrolama zig-a-zig-ah!` is out of stock at the moment but I have joined the waitlist. 

I had a look at the ConBee thread -- Although still in WIP what do you think of using that?

**Comment by Koenkk** [comment]
It's still experimental, you can also check https://www.zigbee2mqtt.io/information/supported_adapters.html#slaeshs-cc2652rb-stick or https://www.zigbee2mqtt.io/information/supported_adapters.html#texas-instruments-launchxl-cc26x2r1 (all same chip)

**Comment by onlymejosh** [comment]
Thanks I did see all of those unfortunately they're all saying a while to deliver whereas the conbee is next day! I will hold out for the `Electrolama zig-a-zig-ah!`. 

For now if i re-flash the adapter with the firmware you mentioned, will I need to re-pair all of my devices?

**Comment by Koenkk** [comment]
No you don't need to reflash: (https://www.zigbee2mqtt.io/information/FAQ.html#what-does-and-does-not-require-repairing-of-all-devices)

**Comment by onlymejosh** [comment]
Thanks @Koenkk for all of your help. I flashed with the different firmware and it is working now. I'll keep an eye on both the conbee support and `Electrolama zig-a-zig-ah!`
