### ISSUE TITLE
zigbee2mqtt fails to start when network_key is set to GENERATE (edge case)

### ISSUE THREAD

**Issue by elfhack** [Koenkk/zigbee2mqtt#4231]
I'll forgo the usual bug template as this is a more complicated situation.

On my home server i now have 2 zigbee adapters, a generic cc2531 (with udev rules renaming it to /dev/zigbee) and a new and shiny zzh (under /dev/zzh). I'm now trying to run 2 instances of zigbee2mqtt, with the zzh instance being completely separate from the 2531 one. I run both of them via kubernetes, as statefullsets (so no user errors with sharing data have a chance to occur). They both also have their own topics on mqtt, so no chance of collision here.

The 2531 now has around 40 devices under itself and is running smoothly.
The zzh has nothing, and I'm not trying to migrate any data from the 2531 instance. Completely fresh configs, different pan_id et al.

Now, if i run zigbee2mqtt for zzh, while the zigbee2mqtt for 2531 instance is running, with network_key set to GENERATE
```
advanced:
  network_key: GENERATE
```

it will crash like so

```
> zigbee2mqtt@1.14.3 start /app
> node index.js

Zigbee2MQTT:info  2020-08-31 20:37:59: Logging to console only'
Zigbee2MQTT:debug 2020-08-31 20:37:59: Can't load state from file /data/state.json (doesn't exist)
Zigbee2MQTT:info  2020-08-31 20:37:59: Starting Zigbee2MQTT version 1.14.3 (commit #f8066e8)
Zigbee2MQTT:info  2020-08-31 20:37:59: Starting zigbee-herdsman...
Zigbee2MQTT:debug 2020-08-31 20:37:59: Using zigbee-herdsman with settings: '{"network":{"panID":8149,"extendedPanID":[253,173,170,153,17,35,68,245],"channelList":[11],"networkKey":"HIDDEN"},"databasePath":"/data/database.db","databaseBackupPath":"/data/database.db.backup","backupPath":"/data/coordinator_backup.json","serialPort":{"path":"/dev/zzh"},"adapter":{"concurrent":null}}'
Zigbee2MQTT:error 2020-08-31 20:39:09: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-08-31 20:39:09: Failed to start zigbee
Zigbee2MQTT:error 2020-08-31 20:39:09: Exiting...
Zigbee2MQTT:error 2020-08-31 20:39:09: Error: Coordinator failed to start, probably the panID is already in use, try a different panID or channel
    at /app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/startZnp.js:171:23
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/startZnp.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.14.3 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.14.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-31T18_39_09_710Z-debug.log
```

However, if I either stop the 2531 instance or configure the network key statically like so (the key here doesn't matter, any will do)

```
advanced:
  network_key: [141, 242, 220, 79, 156, 22, 117, 55, 201, 141, 159, 24, 130, 173, 250, 27]
```

Then there's no problem at all. 

I'm guessing you have some sort of scan there that detects a second zigbee network on the same channel and this makes it fail? Not sure about it, since even if i set the channel to let's say 15 (the 2531 network is on channel 11) it would fail as well.

And to reiterate : both instances have no contact with each other - separate containers, separate config files, separate devices.

For completeness sake, this is the complete config for the zzh instance

```yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zzh
  server: 'mqtt://mosquitto.homeassistant'
serial:
  port: /dev/zzh
  disable_led: false
advanced:
  # network_key: [141, 242, 220, 79, 156, 22, 117, 55, 201, 141, 159, 24, 130, 173, 250, 27]
  network_key: GENERATE
  pan_id: 0x1fd5
  ext_pan_id: [0xFD, 0xAD, 0xAA, 0x99, 0x11, 0x23, 0x44, 0xF5]
  log_level: debug
  log_output:
    - console
  availability_timeout: 300
  report: false
```

zigbee2mqtt version: 1.14.3
adapter: zzh and cc2531
adapter fw: CC26X2R1_20200805 and 20190608 for 2531

**Comment by Koenkk** [comment]
Can you provide the herdsman debug logging of this issue?

To enable herdsman debug logging, see https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging

**Comment by elfhack** [comment]
Sorry for the lag
```
Using '/data' as data directory
Creating configuration file...

> zigbee2mqtt@1.14.4 start /app
> node index.js

Zigbee2MQTT:info  2020-09-11 14:42:03: Logging to console only'
Zigbee2MQTT:debug 2020-09-11 14:42:04: Can't load state from file /data/state.json (doesn't exist)
Zigbee2MQTT:info  2020-09-11 14:42:04: Starting Zigbee2MQTT version 1.14.4 (commit #654817a)
Zigbee2MQTT:info  2020-09-11 14:42:04: Starting zigbee-herdsman...
Zigbee2MQTT:debug 2020-09-11 14:42:04: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null},"backupPath":"/data/coordinator_backup.json","databaseBackupPath":"/data/database.db.backup","databasePath":"/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":8149},"serialPort":{"path":"/dev/zzh"}}'
2020-09-11T12:42:04.222Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[73,220,141,253,23,7,1,132,14,188,159,168,123,155,223,154],"panID":8149,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/zzh"},"databasePath":"/data/database.db","databaseBackupPath":"/data/database.db.backup","backupPath":"/data/coordinator_backup.json","adapter":{"concurrent":null}}'
2020-09-11T12:42:04.223Z zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /dev/zzh and {"baudRate":115200,"rtscts":false,"autoOpen":false}
2020-09-11T12:42:04.225Z zigbee-herdsman:adapter:zStack:znp:log Serialport opened
2020-09-11T12:42:04.678Z zigbee-herdsman:adapter:zStack:znp:log Writing skip bootloader payload
2020-09-11T12:42:04.679Z zigbee-herdsman:adapter:zStack:unpi:writer --> buffer [239]
2020-09-11T12:42:05.683Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2020-09-11T12:42:05.685Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2020-09-11T12:42:05.691Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,1,89,6,61]
2020-09-11T12:42:05.692Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,1,89,6,61]
2020-09-11T12:42:05.692Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 1 - [89,6] - 61
2020-09-11T12:42:05.693Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - ping - {"capabilities":1625}
2020-09-11T12:42:05.695Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:05.695Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - version - {}
2020-09-11T12:42:05.696Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,2,35]
2020-09-11T12:42:05.702Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,14,97,2,2,1,2,7,1,126,61,52,1,0,255,255,255,255,28]
2020-09-11T12:42:05.702Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,14,97,2,2,1,2,7,1,126,61,52,1,0,255,255,255,255,28]
2020-09-11T12:42:05.702Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 14 - 3 - 1 - 2 - [2,1,2,7,1,126,61,52,1,0,255,255,255,255] - 28
2020-09-11T12:42:05.703Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - version - {"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20200830}
2020-09-11T12:42:05.703Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:05.703Z zigbee-herdsman:adapter:zStack:adapter Adapter concurrent: 16
2020-09-11T12:42:05.703Z zigbee-herdsman:adapter:zStack:adapter Detected znp version 'zStack3x0' ({"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20200830})
2020-09-11T12:42:05.705Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":96,"offset":0,"len":1,"value":{"type":"Buffer","data":[85]}}
2020-09-11T12:42:05.706Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,96,0,0,74]
2020-09-11T12:42:05.720Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,97,8,0,1,85,62]
2020-09-11T12:42:05.720Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,97,8,0,1,85,62]
2020-09-11T12:42:05.720Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 3 - 1 - 8 - [0,1,85] - 62
2020-09-11T12:42:05.720Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":1,"value":{"type":"Buffer","data":[85]}}
2020-09-11T12:42:05.721Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:05.721Z zigbee-herdsman:adapter:zStack:startZnp Item 'hasConfigured' is valid
2020-09-11T12:42:05.721Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":96,"offset":0,"len":1,"value":{"type":"Buffer","data":[85]}}
2020-09-11T12:42:05.721Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,96,0,0,74]
2020-09-11T12:42:05.731Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,97,8,0,1,85,62]
2020-09-11T12:42:05.731Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,97,8,0,1,85,62]
2020-09-11T12:42:05.731Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 3 - 1 - 8 - [0,1,85] - 62
2020-09-11T12:42:05.731Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":1,"value":{"type":"Buffer","data":[85]}}
2020-09-11T12:42:05.731Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:05.731Z zigbee-herdsman:adapter:zStack:startZnp Item 'hasConfigured' is valid
2020-09-11T12:42:05.732Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":132,"len":4,"offset":0,"value":{"type":"Buffer","data":[0,8,0,0]}}
2020-09-11T12:42:05.732Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,132,0,0,174]
2020-09-11T12:42:05.745Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,6,97,8,0,4,0,8,0,0,99]
2020-09-11T12:42:05.745Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,6,97,8,0,4,0,8,0,0,99]
2020-09-11T12:42:05.745Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 6 - 3 - 1 - 8 - [0,4,0,8,0,0] - 99
2020-09-11T12:42:05.745Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":4,"value":{"type":"Buffer","data":[0,8,0,0]}}
2020-09-11T12:42:05.745Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:05.745Z zigbee-herdsman:adapter:zStack:startZnp Item 'channelList' is valid
2020-09-11T12:42:05.745Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":99,"len":1,"offset":0,"value":{"type":"Buffer","data":[0]}}
2020-09-11T12:42:05.745Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,99,0,0,73]
2020-09-11T12:42:05.760Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,97,8,0,1,0,107]
2020-09-11T12:42:05.760Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,97,8,0,1,0,107]
2020-09-11T12:42:05.760Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 3 - 1 - 8 - [0,1,0] - 107
2020-09-11T12:42:05.760Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":1,"value":{"type":"Buffer","data":[0]}}
2020-09-11T12:42:05.760Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:05.761Z zigbee-herdsman:adapter:zStack:startZnp Item 'networkKeyDistribute' is valid
2020-09-11T12:42:05.761Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":98,"configid":98,"len":16,"offset":0,"value":{"type":"Buffer","data":[73,220,141,253,23,7,1,132,14,188,159,168,123,155,223,154]}}
2020-09-11T12:42:05.761Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,98,0,0,72]
2020-09-11T12:42:05.777Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,18,97,8,0,16,42,101,214,121,164,20,163,141,184,173,164,236,205,240,221,27,179]
2020-09-11T12:42:05.777Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,18,97,8,0,16,42,101,214,121,164,20,163,141,184,173,164,236,205,240,221,27,179]
2020-09-11T12:42:05.777Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 18 - 3 - 1 - 8 - [0,16,42,101,214,121,164,20,163,141,184,173,164,236,205,240,221,27] - 179
2020-09-11T12:42:05.777Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":16,"value":{"type":"Buffer","data":[42,101,214,121,164,20,163,141,184,173,164,236,205,240,221,27]}}
2020-09-11T12:42:05.777Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:05.777Z zigbee-herdsman:adapter:zStack:startZnp Item 'networkKey' is invalid, got '{"type":"Buffer","data":[42,101,214,121,164,20,163,141,184,173,164,236,205,240,221,27]}', expected '{"type":"Buffer","data":[73,220,141,253,23,7,1,132,14,188,159,168,123,155,223,154]}'
2020-09-11T12:42:05.778Z zigbee-herdsman:adapter:zStack:startZnp Initialising coordinator
2020-09-11T12:42:05.778Z zigbee-herdsman:adapter:zStack:znp:AREQ --> SYS - resetReq - {"type":1}
2020-09-11T12:42:05.778Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,1,65,0,1,65]
2020-09-11T12:42:05.787Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [0]
2020-09-11T12:42:05.787Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [0]
2020-09-11T12:42:07.712Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,6,65,128,0,2,1,2,7,1,192]
2020-09-11T12:42:07.713Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [0,254,6,65,128,0,2,1,2,7,1,192]
2020-09-11T12:42:07.713Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 6 - 2 - 1 - 128 - [0,2,1,2,7,1] - 192
2020-09-11T12:42:07.713Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- SYS - resetInd - {"reason":0,"transportrev":2,"productid":1,"majorrel":2,"minorrel":7,"hwrev":1}
2020-09-11T12:42:07.713Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:07.714Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvWrite - {"id":3,"len":1,"offset":0,"value":{"type":"Buffer","data":[2]}}
2020-09-11T12:42:07.715Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,33,9,3,0,0,1,2,45]
2020-09-11T12:42:07.723Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,97,9,0,105]
2020-09-11T12:42:07.723Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,97,9,0,105]
2020-09-11T12:42:07.723Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 1 - 9 - [0] - 105
2020-09-11T12:42:07.723Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvWrite - {"status":0}
2020-09-11T12:42:07.723Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:07.723Z zigbee-herdsman:adapter:zStack:znp:AREQ --> SYS - resetReq - {"type":1}
2020-09-11T12:42:07.724Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,1,65,0,1,65]
2020-09-11T12:42:07.733Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [0]
2020-09-11T12:42:07.733Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [0]
2020-09-11T12:42:10.090Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,6,65,128,0,2,1,2,7,1,192]
2020-09-11T12:42:10.090Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [0,254,6,65,128,0,2,1,2,7,1,192]
2020-09-11T12:42:10.090Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 6 - 2 - 1 - 128 - [0,2,1,2,7,1] - 192
2020-09-11T12:42:10.091Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- SYS - resetInd - {"reason":0,"transportrev":2,"productid":1,"majorrel":2,"minorrel":7,"hwrev":1}
2020-09-11T12:42:10.091Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:10.091Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvWrite - {"id":135,"len":1,"offset":0,"value":{"type":"Buffer","data":[0]}}
2020-09-11T12:42:10.091Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,33,9,135,0,0,1,0,171]
2020-09-11T12:42:10.108Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,97,9,0,105]
2020-09-11T12:42:10.108Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,97,9,0,105]
2020-09-11T12:42:10.108Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 1 - 9 - [0] - 105
2020-09-11T12:42:10.108Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvWrite - {"status":0}
2020-09-11T12:42:10.108Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:10.109Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvWrite - {"id":99,"len":1,"offset":0,"value":{"type":"Buffer","data":[0]}}
2020-09-11T12:42:10.109Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,33,9,99,0,0,1,0,79]
2020-09-11T12:42:10.126Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,97,9,0,105]
2020-09-11T12:42:10.126Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,97,9,0,105]
2020-09-11T12:42:10.126Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 1 - 9 - [0] - 105
2020-09-11T12:42:10.126Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvWrite - {"status":0}
2020-09-11T12:42:10.127Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:10.127Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvWrite - {"id":143,"len":1,"offset":0,"value":{"type":"Buffer","data":[1]}}
2020-09-11T12:42:10.128Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,33,9,143,0,0,1,1,162]
2020-09-11T12:42:10.144Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,97,9,0,105]
2020-09-11T12:42:10.145Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,97,9,0,105]
2020-09-11T12:42:10.145Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 1 - 9 - [0] - 105
2020-09-11T12:42:10.145Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvWrite - {"status":0}
2020-09-11T12:42:10.145Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:10.146Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvWrite - {"id":132,"len":4,"offset":0,"value":{"type":"Buffer","data":[0,8,0,0]}}
2020-09-11T12:42:10.146Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,8,33,9,132,0,0,4,0,8,0,0,168]
2020-09-11T12:42:10.161Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,97,9,0,105]
2020-09-11T12:42:10.161Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,97,9,0,105]
2020-09-11T12:42:10.161Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 1 - 9 - [0] - 105
2020-09-11T12:42:10.161Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvWrite - {"status":0}
2020-09-11T12:42:10.161Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:10.162Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvWrite - {"id":131,"len":2,"offset":0,"value":{"type":"Buffer","data":[213,31]}}
2020-09-11T12:42:10.162Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,6,33,9,131,0,0,2,213,31,101]
2020-09-11T12:42:10.176Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,97,9,0,105]
2020-09-11T12:42:10.177Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,97,9,0,105]
2020-09-11T12:42:10.177Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 1 - 9 - [0] - 105
2020-09-11T12:42:10.177Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvWrite - {"status":0}
2020-09-11T12:42:10.177Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:10.177Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvWrite - {"id":45,"len":8,"offset":0,"value":{"type":"Buffer","data":[221,221,221,221,221,221,221,221]}}
2020-09-11T12:42:10.178Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,12,33,9,45,0,0,8,221,221,221,221,221,221,221,221,1]
2020-09-11T12:42:10.195Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,97,9,0,105]
2020-09-11T12:42:10.195Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,97,9,0,105]
2020-09-11T12:42:10.195Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 1 - 9 - [0] - 105
2020-09-11T12:42:10.196Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvWrite - {"status":0}
2020-09-11T12:42:10.196Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:10.196Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvWrite - {"id":98,"configid":98,"len":16,"offset":0,"value":{"type":"Buffer","data":[73,220,141,253,23,7,1,132,14,188,159,168,123,155,223,154]}}
2020-09-11T12:42:10.197Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,20,33,9,98,0,0,16,73,220,141,253,23,7,1,132,14,188,159,168,123,155,223,154,30]
2020-09-11T12:42:10.215Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,97,9,0,105]
2020-09-11T12:42:10.215Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,97,9,0,105]
2020-09-11T12:42:10.215Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 1 - 9 - [0] - 105
2020-09-11T12:42:10.215Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvWrite - {"status":0}
2020-09-11T12:42:10.216Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:10.216Z zigbee-herdsman:adapter:zStack:znp:SREQ --> APP_CNF - bdbSetChannel - {"isPrimary":1,"channel":2048}
2020-09-11T12:42:10.217Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,47,8,1,0,8,0,0,43]
2020-09-11T12:42:10.221Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,111,8,0,102]
2020-09-11T12:42:10.221Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,111,8,0,102]
2020-09-11T12:42:10.222Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 15 - 8 - [0] - 102
2020-09-11T12:42:10.222Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- APP_CNF - bdbSetChannel - {"status":0}
2020-09-11T12:42:10.222Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:10.222Z zigbee-herdsman:adapter:zStack:znp:SREQ --> APP_CNF - bdbSetChannel - {"isPrimary":0,"channel":0}
2020-09-11T12:42:10.222Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,5,47,8,0,0,0,0,0,34]
2020-09-11T12:42:10.227Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,111,8,0,102]
2020-09-11T12:42:10.227Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,111,8,0,102]
2020-09-11T12:42:10.228Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 15 - 8 - [0] - 102
2020-09-11T12:42:10.228Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- APP_CNF - bdbSetChannel - {"status":0}
2020-09-11T12:42:10.228Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:10.229Z zigbee-herdsman:adapter:zStack:znp:SREQ --> APP_CNF - bdbStartCommissioning - {"mode":4}
2020-09-11T12:42:10.229Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,1,47,5,4,47]
2020-09-11T12:42:13.286Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,111,5,0,107,254,3,79,128,2,0,0,206]
2020-09-11T12:42:13.286Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,111,5,0,107,254,3,79,128,2,0,0,206]
2020-09-11T12:42:13.287Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 15 - 5 - [0] - 107
2020-09-11T12:42:13.287Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- APP_CNF - bdbStartCommissioning - {"status":0}
2020-09-11T12:42:13.287Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,79,128,2,0,0,206]
2020-09-11T12:42:13.287Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 15 - 128 - [2,0,0] - 206
2020-09-11T12:42:13.287Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- APP_CNF - bdbComissioningNotifcation - {"status":2}
2020-09-11T12:42:13.287Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2020-09-11T12:42:13.499Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,69,192,8,140]
2020-09-11T12:42:13.499Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,69,192,8,140]
2020-09-11T12:42:13.499Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 2 - 5 - 192 - [8] - 140
2020-09-11T12:42:13.499Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - stateChangeInd - {"state":8}
2020-09-11T12:42:13.499Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
Zigbee2MQTT:error 2020-09-11 14:43:13: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-09-11 14:43:13: Failed to start zigbee
Zigbee2MQTT:error 2020-09-11 14:43:13: Exiting...
Zigbee2MQTT:error 2020-09-11 14:43:13: Error: Coordinator failed to start, probably the panID is already in use, try a different panID or channel
    at /app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/startZnp.js:171:23
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/startZnp.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.14.4 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.14.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-11T12_43_13_361Z-debug.log
```

With the config being
```
homeassistant: true
        permit_join: false
        mqtt:
          base_topic: zzh
          server: 'mqtt://mosquitto.homeassistant'
        serial:
          port: /dev/zzh
          disable_led: false
        advanced:
          # network_key: [141, 242, 220, 79, 156, 22, 117, 55, 201, 141, 159, 24, 130, 173, 250, 27]
          network_key: GENERATE
          pan_id: 0x1fd5
          log_level: debug
          log_output:
            - console
          availability_timeout: 300
          report: false
```

**Comment by Koenkk** [comment]
Are you able to sniff the traffic on channel 11 during this startup? https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

**Comment by elfhack** [comment]
> Are you able to sniff the traffic on channel 11 during this startup? https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

Unfortunately no. That would require a 3rd zigbee adapter, and I just don't have that many :(
