### ISSUE TITLE
Blaupunkt SCM-S1 doesn't support reporting it's position

### ISSUE THREAD

**Issue by krumbholz** [Koenkk/zigbee2mqtt#4246]
# Bug Report
## What happened
My Blaupunkt SCM-S1 with id SCM-2_00.00.03.15 raises an error while being configured on startup:
```
zigbee.0 (823) DeviceConfigure failed 0x00124b001bfbd2bc SCM-2_00.00.03.15, attempt 3 (Error: ConfigureReporting 0x00124b001bfbd2bc/1 genLevelCtrl([{"attribute":"currentLevel","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":1}], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Status 'UNREPORTABLE_ATTRIBUTE')
    at Endpoint.checkStatus (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:140:23)
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:348:26)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58))
```

## Proposed solution
I commented out the line for position reporting and I'm fine with it ;-)  But it may be best to distinguish between the different shutter variants.
```
    // Blaupunkt
    {
        zigbeeModel: ['SCM-2_00.00.03.15', 'SCM-R_00.00.03.15TC', 'SCM_00.00.03.14TC', 'SCM_00.00.03.05TC'],
        model: 'SCM-S1',
        vendor: 'Blaupunkt',
        description: 'Roller shutter',
        supports: 'open/close',
        fromZigbee: [fz.cover_position_via_brightness, fz.cover_state_via_onoff],
        toZigbee: [tz.cover_position_via_brightness, tz.cover_open_close_via_brightness],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genLevelCtrl']);
    ////        await configureReporting.brightness(endpoint);
        },
    },
```

## Debug Info
```
zigbee.0 (819) starting. Version 1.2.1 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.18.3, js-controller: 3.1.6
zigbee.0 (819) Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}
```

**Comment by Koenkk** [comment]
Added a try catch, thanks!
