### ISSUE TITLE
zigbee2mqtt crashes when sending wrong sensibility to vibration sensor 

### ISSUE THREAD

**Issue by lolorc** [Koenkk/zigbee2mqtt#427]
Hi,

I'm playing with my vibration sensors (DJT11LM_vibration)
I just tried to set its sensibility (looks like it's not working but I'll fill another issue)
and I tried with to set it with an incorrect value, zigbee2mqtt does crash in that case.
here are the logs.

zigbee2mqtt from dev branch, commit bf68f4575f591c5ef6ecb500acf6ec056c1eee97

```
Sep 30 13:00:22   zigbee2mqtt:debug 2018-9-30 13:00:22 Recieved mqtt message on topic 'zigbee2mqtt/vibration_01/set' with data '{"sensitivity": "highBLA"}'                                                        │
Sep 30 13:00:22   zigbee2mqtt:info 2018-9-30 13:00:22 Zigbee publish to '0x00158d0002a51e32', genBasic - write                                                                                                     │
Sep 30 13:00:22         - {"attrId":65293,"dataType":32} - {"manufSpec":1,"disDefaultRsp":1,"manufCode":4447} - null                                                                                               │
Sep 30 13:00:22 /home/pi/zigbee2mqtt/node_modules/zigbee-shepherd/lib/components/af.js:269                                                                                                                         │
Sep 30 13:00:22             throw e;                                                                                                                                                                               │
Sep 30 13:00:22             ^                                                                                                                                                                                      │
Sep 30 13:00:22                                                                                                                                                                                                    │
Sep 30 13:00:22 Error: Payload of commnad: write must have attrData property.                                                                                                                                      │
Sep 30 13:00:22     at /home/pi/zigbee2mqtt/node_modules/zcl-packet/lib/foundation.js:176:27                                                                                                                       │
Sep 30 13:00:22     at Array.forEach (<anonymous>)                                                                                                                                                                 │
Sep 30 13:00:22     at FoundPayload._getBuf (/home/pi/zigbee2mqtt/node_modules/zcl-packet/lib/foundation.js:171:25)                                                                                                │
Sep 30 13:00:22     at /home/pi/zigbee2mqtt/node_modules/zcl-packet/lib/foundation.js:112:22                                                                                                                       │
Sep 30 13:00:22     at Array.forEach (<anonymous>)                                                                                                                                                                 │
Sep 30 13:00:22     at FoundPayload.frame (/home/pi/zigbee2mqtt/node_modules/zcl-packet/lib/foundation.js:111:21)                                                                                                  │
Sep 30 13:00:22     at Object.zcl.frame (/home/pi/zigbee2mqtt/node_modules/zcl-packet/lib/zcl.js:66:78)                                                                                                            │
Sep 30 13:00:22     at Object.af.zclFoundation (/home/pi/zigbee2mqtt/node_modules/zigbee-shepherd/lib/components/af.js:263:25)                                                                                     │
Sep 30 13:00:22     at ZShepherd._foundation (/home/pi/zigbee2mqtt/node_modules/zigbee-shepherd/lib/shepherd.js:648:20)                                                                                            │
Sep 30 13:00:22     at Endpoint.ep.foundation (/home/pi/zigbee2mqtt/node_modules/zigbee-shepherd/lib/shepherd.js:536:25)                                                                                           │
Sep 30 13:00:22 npm ERR! code ELIFECYCLE                                                                                                                                                                           │
Sep 30 13:00:22 npm ERR! errno 1                                                                                                                                                                                   │
Sep 30 13:00:22 npm ERR! zigbee2mqtt@0.1.6 start: `node index.js`                                                                                                                                                  │
Sep 30 13:00:22 npm ERR! Exit status 1                                                                                                                                                                             │
Sep 30 13:00:22 npm ERR!                                                                                                                                                                                           │
Sep 30 13:00:22 npm ERR! Failed at the zigbee2mqtt@0.1.6 start script.                                                                                                                                             │
Sep 30 13:00:22 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                                 │
Sep 30 13:00:22                                                                                                                                                                                                    │
Sep 30 13:00:22 npm ERR! A complete log of this run can be found in:                                                                                                                                               │
Sep 30 13:00:22 npm ERR!     /home/pi/.npm/_logs/2018-09-30T11_00_22_373Z-debug.log
```

```
0 info it worked if it ends with ok                                                                                                                                                                                │
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]                                                                                                                                                         │
2 info using npm@6.4.1                                                                                                                                                                                             │
3 info using node@v8.12.0                                                                                                                                                                                          │
4 verbose run-script [ 'prestart', 'start', 'poststart' ]                                                                                                                                                          │
5 info lifecycle zigbee2mqtt@0.1.6~prestart: zigbee2mqtt@0.1.6                                                                                                                                                     │
6 info lifecycle zigbee2mqtt@0.1.6~start: zigbee2mqtt@0.1.6                                                                                                                                                        │
7 verbose lifecycle zigbee2mqtt@0.1.6~start: unsafe-perm in lifecycle true                                                                                                                                         │
8 verbose lifecycle zigbee2mqtt@0.1.6~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/zigbee2mqtt/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin│
9 verbose lifecycle zigbee2mqtt@0.1.6~start: CWD: /home/pi/zigbee2mqtt                                                                                                                                             │
10 silly lifecycle zigbee2mqtt@0.1.6~start: Args: [ '-c', 'node index.js' ]                                                                                                                                        │
11 silly lifecycle zigbee2mqtt@0.1.6~start: Returned: code: 1  signal: null                                                                                                                                        │
12 info lifecycle zigbee2mqtt@0.1.6~start: Failed to exec start script                                                                                                                                             │
13 verbose stack Error: zigbee2mqtt@0.1.6 start: `node index.js`                                                                                                                                                   │
13 verbose stack Exit status 1                                                                                                                                                                                     │
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)                                                                                            │
13 verbose stack     at emitTwo (events.js:126:13)                                                                                                                                                                 │
13 verbose stack     at EventEmitter.emit (events.js:214:7)                                                                                                                                                        │
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)                                                                                         │
13 verbose stack     at emitTwo (events.js:126:13)                                                                                                                                                                 │
13 verbose stack     at ChildProcess.emit (events.js:214:7)                                                                                                                                                        │
13 verbose stack     at maybeClose (internal/child_process.js:915:16)                                                                                                                                              │
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)                                                                                                                      │
14 verbose pkgid zigbee2mqtt@0.1.6                                                                                                                                                                                 │
15 verbose cwd /home/pi/zigbee2mqtt                                                                                                                                                                                │
16 verbose Linux 4.14.72-v7+                                                                                                                                                                                       │
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"                                                                                                                                                             │
18 verbose node v8.12.0                                                                                                                                                                                            │
19 verbose npm  v6.4.1                                                                                                                                                                                             │
20 error code ELIFECYCLE                                                                                                                                                                                           │
21 error errno 1                                                                                                                                                                                                   │
22 error zigbee2mqtt@0.1.6 start: `node index.js`                                                                                                                                                                  │
22 error Exit status 1                                                                                                                                                                                             │
23 error Failed at the zigbee2mqtt@0.1.6 start script.                                                                                                                                                             │
23 error This is probably not a problem with npm. There is likely additional logging output above.                                                                                                                 │
24 verbose exit [ 1, true ]                                                                            
```

**Comment by Koenkk** [comment]
fixed, thanks for reporting.
