### ISSUE TITLE
IKEA E1743 / E1810 not working after 1.16.0

### ISSUE THREAD

**Issue by blackthornedk** [Koenkk/zigbee2mqtt#4994]
## What happened
I tried upgrading to 1.16.0 and later to 1.16.1, but my buttons doesn't work anymore.
I get a JS TypeError: Cannot read property 'type' of undefined in /zigbee2mqtt-1.16.1/lib/extension/receive.js:120:42

```
debug 2020-11-15 23:20:13: Received Zigbee message from 'Knap2', type 'commandToggle', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 0
error 2020-11-15 23:20:13: Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined
    at /zigbee2mqtt-1.16.1/lib/extension/receive.js:120:42
    at Array.filter (<anonymous>)
    at Receive.onZigbeeEvent (/zigbee2mqtt-1.16.1/lib/extension/receive.js:119:65)
    at Controller.callExtensionMethod (/zigbee2mqtt-1.16.1/lib/controller.js:378:44)
    at Controller.onZigbeeEvent (/zigbee2mqtt-1.16.1/lib/controller.js:261:14)
    at Zigbee.emit (events.js:315:20)
    at Controller.<anonymous> (/zigbee2mqtt-1.16.1/lib/zigbee.js:68:52)
    at Controller.emit (events.js:315:20)
    at Controller.<anonymous> (/zigbee2mqtt-1.16.1/node_modules/zigbee-herdsman/dist/controller/controller.js:545:22)
    at Generator.next (<anonymous>))
debug 2020-11-15 23:20:15: Received Zigbee message from 'Knap1', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 901
error 2020-11-15 23:20:15: Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'type' of undefined
    at /zigbee2mqtt-1.16.1/lib/extension/receive.js:120:42
    at Array.filter (<anonymous>)
    at Receive.onZigbeeEvent (/zigbee2mqtt-1.16.1/lib/extension/receive.js:119:65)
    at Controller.callExtensionMethod (/zigbee2mqtt-1.16.1/lib/controller.js:378:44)
    at Controller.onZigbeeEvent (/zigbee2mqtt-1.16.1/lib/controller.js:261:14)
    at Zigbee.emit (events.js:315:20)
    at Controller.<anonymous> (/zigbee2mqtt-1.16.1/lib/zigbee.js:68:52)
    at Controller.emit (events.js:315:20)
    at Controller.<anonymous> (/zigbee2mqtt-1.16.1/node_modules/zigbee-herdsman/dist/controller/controller.js:545:22)
    at Generator.next (<anonymous>))
```

log.txt:
https://pastebin.com/GBc1kjcM

## What did you expect to happen
I expect the button to work. :)

## How to reproduce it (minimal and precise)
Upgrade from 1.15.0 to 1.16.0.

## Debug info
Zigbee2MQTT version: 1.16.0
Adapter hardware: CC2531

**Comment by blackthornedk** [comment]
Nevermind, found the problem:
I had a faulty devices.js in my data directory.
