### ISSUE TITLE
Timeout during cc2530 reboot 

### ISSUE THREAD

**Issue by walzing** [Koenkk/zigbee2mqtt#5048]
##  What happened
I have a cc2591 module. I was able to flash the coordinator firmware "CC2530_CC2591_DEFAULT_20190608". I followed this howto https://zigbee.blakadder.com/flashing_ccloader.html. Flashing was successful. When I try to use the module I receive a timeout. I tested:
- with Zigbee2mqtt and direct raspberry connect (GPIO)
- Zigbee2mqtt and fdti raspberry
- Zigbee2tasmota and Wemos D1 Mini Pro)

Logging
`Zigbee2MQTT:info  2020-11-22 11:12:18: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2020-11-22.11-12-16' filename: log.txt
Zigbee2MQTT:info  2020-11-22 11:12:18: Starting Zigbee2MQTT version 1.16.1 (commit #4978d09)
Zigbee2MQTT:info  2020-11-22 11:12:18: Starting zigbee-herdsman...
Zigbee2MQTT:error 2020-11-22 11:12:39: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2020-11-22 11:12:39: Failed to start zigbee
Zigbee2MQTT:error 2020-11-22 11:12:39: Exiting...
Zigbee2MQTT:error 2020-11-22 11:12:39: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
`

## What did you expect to happen
Succesful start of module

## How to reproduce it (minimal and precise)
See above

## Debug info
Zigbee2MQTT version: 1.16.1 (commit #4978d09)
Adapter hardware: CC2591
Adapter firmware version: CC2530_CC2591_DEFAULT_20190608

**Comment by walzing** [comment]
Just checked this and it was successful: https://www.zigbee2mqtt.io/information/zigbee2mqtt_fails_to_start.html
However zigbee module won't start.
