### ISSUE TITLE
Bitron AV2010/26: Dimmable Wireless Socket

### ISSUE THREAD

**Issue by fabsss** [Koenkk/zigbee2mqtt#5064]
## Information about the device + link
Bitron 2,5A Dimmable Socket: zigbeeModel: ['902010/26']
Features: 
- On/Off and Dimming
- Power Meter
- Button (Default: Select Brightness levels, on, off, Pairing)

Purchase-Link: https://www.conrad.at/de/p/bitron-video-steckdose-av2010-26-902010-26-1095388.html#productHighlights
Manual: https://asset.conrad.com/media10/add/160267/c1/-/gl/001095388ML01/bedienungsanleitung-1095388-bitron-video-steckdose-av201026-90201026.pdf

## data/database.db entry of the device
not yet available (similar model without dimming: zigbeeModel: ['902010/25']

I tried to create an external converter which recognizes the device by copying the entry of the similar model /25 but are just not capable to get even the simple functions (on/off, power meter, without dimming) working. I just don't understand enough of the code to contribute. I can provide logging data if someone needs them to implement the new device, though. 

I added the following to ext_conv_bitron_av2010_26.js in /usr/share/hassio/share/zigbee2mqtt 
```
const device = {
        zigbeeModel: ['902010/26'],
        model: 'AV2010/26',
        vendor: 'Bitron',
        description: 'Video wireless socket with 2,5A Dimmer',
        fromZigbee: [zigbeeHerdsmanConverters.fromZigbeeConverters.on_off, zigbeeHerdsmanConverters.fromZigbeeConverters.bitron_power],
        toZigbee: [zigbeeHerdsmanConverters.toZigbeeConverters.on_off],
        exposes: [],
        meta: {configureKey: 2},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(1);
            await bind(endpoint, coordinatorEndpoint, ['genOnOff', 'seMetering']);
            await configureReporting.instantaneousDemand(endpoint);
        },
        //homeassistant: [homeAssistantSwitch],
};
```
and added
```
external_converters:
  - ext_conv_bitron_av2010_26.js
```
to the configuration.yaml.

The output in the log file regarding the device after reconnecting it:
```

Zigbee2MQTT:info  2020-11-23 19:56:44: 0x00124b000ee9b6e2 (0x00124b000ee9b6e2): AV2010/26 - Bitron Video wireless socket with 2,5A Dimmer (Router)
info  2020-11-23 19:56:44: Configuring '0x00124b000ee9b6e2'

[...] {"date_code":"20151005        ","definition":{"description":"Video wireless socket with 2,5A Dimmer","exposes":[],"model":"AV2010/26","vendor":"Bitron"},"endpoints":{"1":{"bindings":[],"clusters":{"input":["genBasic","genIdentify","genGroups","genScenes","genOnOff","genLevelCtrl"],"output":["genBasic"]}},"4":{"bindings":[],"clusters":{"input":[],"output":["genOta"]}}},"friendly_name":"0x00124b000ee9b6e2","ieee_address":"0x00124b000ee9b6e2","interview_completed":true,"interviewing":false,"network_address":8029,"power_source":"Mains (single phase)","supported":true,"type":"Router"} [...]

error 2020-11-23 19:56:54: Failed to configure '0x00124b000ee9b6e2', attempt 1 (Error: Bind 0x00124b000ee9b6e2/1 genOnOff from '0x00124b0018e85a7c/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7))
Zigbee2MQTT:debug 2020-11-23 20:06:24: Device '0x00124b000ee9b6e2' announced itself
Zigbee2MQTT:info  2020-11-23 20:06:24: Configuring '0x00124b000ee9b6e2'
Zigbee2MQTT:info  2020-11-23 20:06:24: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x00124b000ee9b6e2","ieee_address":"0x00124b000ee9b6e2"},"type":"device_announce"}'
Zigbee2MQTT:info  2020-11-23 20:06:24: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x00124b000ee9b6e2"},"type":"device_announced"}'
Zigbee2MQTT:error 2020-11-23 20:06:24: Failed to configure '0x00124b000ee9b6e2', attempt 2 (ReferenceError: configureReporting is not defined
    at Object.configure (evalmachine.<anonymous>:93:13)
    at async Configure.configure (/app/lib/extension/configure.js:131:13))
Zigbee2MQTT:debug 2020-11-23 20:06:25: Received Zigbee message from '0x00124b000ee9b6e2', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-11-23 20:06:25: MQTT publish: topic 'zigbee2mqtt/0x00124b000ee9b6e2', payload '{"linkquality":76,"state":"OFF"}'
Zigbee2MQTT:info  2020-11-23 20:06:25: Configuring '0x00124b000ee9b6e2'
Zigbee2MQTT:error 2020-11-23 20:06:25: Failed to configure '0x00124b000ee9b6e2', attempt 3 (ReferenceError: configureReporting is not defined
    at Object.configure (evalmachine.<anonymous>:93:13)
    at async Configure.configure (/app/lib/extension/configure.js:131:13))
Zigbee2MQTT:debug 2020-11-23 20:06:30: Received Zigbee message from '0x00124b000ee9b6e2', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-11-23 20:06:30: MQTT publish: topic 'zigbee2mqtt/0x00124b000ee9b6e2', payload '{"linkquality":47,"state":"ON"}'
Zigbee2MQTT:debug 2020-11-23 20:06:31: Received Zigbee message from '0x00124b000ee9b6e2', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-11-23 20:06:31: MQTT publish: topic 'zigbee2mqtt/0x00124b000ee9b6e2', payload '{"linkquality":63,"state":"ON"}'
Zigbee2MQTT:debug 2020-11-23 20:06:32: Received Zigbee message from '0x00124b000ee9b6e2', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-11-23 20:06:32: MQTT publish: topic 'zigbee2mqtt/0x00124b000ee9b6e2', payload '{"linkquality":70,"state":"ON"}'
Zigbee2MQTT:debug 2020-11-23 20:06:33: Received Zigbee message from '0x00124b000ee9b6e2', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-11-23 20:06:33: MQTT publish: topic 'zigbee2mqtt/0x00124b000ee9b6e2', payload '{"linkquality":65,"state":"ON"}'
Zigbee2MQTT:debug 2020-11-23 20:06:34: Received Zigbee message from '0x00124b000ee9b6e2', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-11-23 20:06:34: MQTT publish: topic 'zigbee2mqtt/0x00124b000ee9b6e2', payload '{"linkquality":70,"state":"ON"}'
Zigbee2MQTT:debug 2020-11-23 20:06:35: Received Zigbee message from '0x00124b000ee9b6e2', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-11-23 20:06:35: MQTT publish: topic 'zigbee2mqtt/0x00124b000ee9b6e2', payload '{"linkquality":60,"state":"ON"}'
Zigbee2MQTT:debug 2020-11-23 20:06:36: Received Zigbee message from '0x00124b000ee9b6e2', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-11-23 20:06:36: MQTT publish: topic 'zigbee2mqtt/0x00124b000ee9b6e2', payload '{"linkquality":63,"state":"ON"}'
Zigbee2MQTT:debug 2020-11-23 20:06:37: Received Zigbee message from '0x00124b000ee9b6e2', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-11-23 20:06:37: MQTT publish: topic 'zigbee2mqtt/0x00124b000ee9b6e2', payload '{"linkquality":55,"state":"ON"}'
Zigbee2MQTT:debug 2020-11-23 20:06:37: Received Zigbee message from '0x00124b000ee9b6e2', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-11-23 20:06:37: MQTT publish: topic 'zigbee2mqtt/0x00124b000ee9b6e2', payload '{"linkquality":55,"state":"ON"}'
Zigbee2MQTT:debug 2020-11-23 20:06:38: Received Zigbee message from '0x00124b000ee9b6e2', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-11-23 20:06:38: MQTT publish: topic 'zigbee2mqtt/0x00124b000ee9b6e2', payload '{"linkquality":60,"state":"ON"}'
Zigbee2MQTT:debug 2020-11-23 20:06:40: Received Zigbee message from '0x00124b000ee9b6e2', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-11-23 20:06:40: MQTT publish: topic 'zigbee2mqtt/0x00124b000ee9b6e2', payload '{"linkquality":68,"state":"OFF"}'
Zigbee2MQTT:debug 2020-11-23 20:06:41: Saving state to file /share/zigbee2mqtt/state.json
Zigbee2MQTT:debug 2020-11-23 20:06:43: Received Zigbee message from '0x00124b000ee9b6e2', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-11-23 20:06:43: MQTT publish: topic 'zigbee2mqtt/0x00124b000ee9b6e2', payload '{"linkquality":65,"state":"ON"}'
Zigbee2MQTT:debug 2020-11-23 20:06:46: Received Zigbee message from '0x00124b000ee9b6e2', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-11-23 20:06:46: MQTT publish: topic 'zigbee2mqtt/0x00124b000ee9b6e2', payload '{"linkquality":70,"state":"ON"}'
Zigbee2MQTT:debug 2020-11-23 20:06:51: Received Zigbee message from '0x00124b000ee9b6e2', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2020-11-23 20:06:51: MQTT publish: topic 'zigbee2mqtt/0x00124b000ee9b6e2', payload '{"linkquality":89,"state":"ON"}'
```

It would be really great if someone had a look on the device since there aren't so many zigbee dimmable sockets around and I think its quite useful.

Regards
Fabian

**Comment by gebauer** [comment]
Hi fabss, 

Have you managed to register the bitron dimmer? 
Best, 
Jan

**Comment by fabsss** [comment]
> Hi fabss,
> 
> Have you managed to register the bitron dimmer?
> Best,
> Jan

Hi Jan,

nope, unfortunately not. :(

Regards
Fabian

**Comment by WordsOfMe** [comment]
I just found the SMaBiT (Bitron Video) AV2010/26 perfectly registering under zigbee2mqtt 1.24.0.
