### ISSUE TITLE
Add support for OS600 Window sensor

### ISSUE THREAD

**Issue by George-andrew** [Koenkk/zigbee2mqtt#5136]
Salus Controls Window sensor OS600

Features:

- Contact
- Tamper
- Low battery alarm

## Information about the device + link
[Page OS600](https://www.salus-controls.eu/products/os600-window-door-sensor)
[Photo OS600](https://salus-controls.pl/wp-content/plugins/dodawanie_produktow/includes/zdjecia/OS600_zdjecie.png)

I’ve added an entry into devices.js : 
```
    {
        zigbeeModel: ['OS600'],
        model: 'OS600',
        vendor: 'Salus Controls',
        description: 'Door or window contact sensor',
        supports: 'Contact, temper,battery alert',
        fromZigbee: [fz.ias_contact_alarm_1],
        toZigbee: [],
        exposes: [e.contact(), e.battery_low(), e.tamper()],
        ota: ota.salus,
    },
```
## data/database.db entry of the device
..
```
Zigbee2MQTT:info  2020-11-30 12:23:19: MQTT publish: topic 'zigbee2mqtt/0x001e5e09021bf8b1', payload '{"battery_low":false,"contact":true,"linkquality":105,"tamper":true}'
Zigbee2MQTT:info  2020-11-30 12:23:59: MQTT publish: topic 'zigbee2mqtt/bridge/config/devices', payload '[{"dateCode":"20190608","friendly_name":"Coordinator","ieeeAddr":"0x00124b000be895ff","lastSeen":1606735439833,"networkAddress":0,"softwareBuildID":"zStack12","type":"Coordinator"},{"dateCode":"20160620","description":"Door or window contact sensor","friendly_name":"0x001e5e09021bf8b1","hardwareVersion":1,"ieeeAddr":"0x001e5e09021bf8b1","lastSeen":1606735399153,"manufacturerID":4216,"manufacturerName":"SALUS","model":"OS600","modelID":"OS600","networkAddress":43756,"powerSource":"Battery","type":"EndDevice","vendor":"Salus Controls"}]'
Zigbee2MQTT:info  2020-11-30 12:23:59: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":[{"dateCode":"20190608","friendly_name":"Coordinator","ieeeAddr":"0x00124b000be895ff","lastSeen":1606735439839,"networkAddress":0,"softwareBuildID":"zStack12","type":"Coordinator"},{"dateCode":"20160620","description":"Door or window contact sensor","friendly_name":"0x001e5e09021bf8b1","hardwareVersion":1,"ieeeAddr":"0x001e5e09021bf8b1","lastSeen":1606735399153,"manufacturerID":4216,"manufacturerName":"SALUS","model":"OS600","modelID":"OS600","networkAddress":43756,"powerSource":"Battery","type":"EndDevice","vendor":"Salus Controls"}],"type":"devices"}'
Zigbee2MQTT:info  2020-11-30 12:29:05: MQTT publish: topic 'zigbee2mqtt/0x001e5e09021bf8b1', payload '{"battery_low":false,"contact":true,"linkquality":97,"tamper":false}'
Zigbee2MQTT:info  2020-11-30 12:29:06: MQTT publish: topic 'zigbee2mqtt/0x001e5e09021bf8b1', payload '{"battery_low":false,"contact":true,"linkquality":78,"tamper":true}'
Zigbee2MQTT:info  2020-11-30 12:29:06: MQTT publish: topic 'zigbee2mqtt/0x001e5e09021bf8b1', payload '{"battery_low":false,"contact":false,"linkquality":63,"tamper":true}'
Zigbee2MQTT:info  2020-11-30 12:29:06: MQTT publish: topic 'zigbee2mqtt/0x001e5e09021bf8b1', payload '{"battery_low":false,"contact":true,"linkquality":84,"tamper":true}'
Zigbee2MQTT:error 2020-11-30 12:30:40: Failed to call 'OTAUpdate' 'onZigbeeEvent' (AssertionError [ERR_ASSERTION]: No image available for modelID 'OS600'
    at getImageMeta (C:\Users\yurii.andriuk\Desktop\hass_io\zigbee2mqtt_new\node_modules\zigbee-herdsman-converters\ota\salus.js:15:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async isNewImageAvailable (C:\Users\yurii.andriuk\Desktop\hass_io\zigbee2mqtt_new\node_modules\zigbee-herdsman-converters\ota\common.js:263:18)
    at async Object.isUpdateAvailable (C:\Users\yurii.andriuk\Desktop\hass_io\zigbee2mqtt_new\node_modules\zigbee-herdsman-converters\ota\common.js:254:23)
    at async OTAUpdate.onZigbeeEvent (C:\Users\yurii.andriuk\Desktop\hass_io\zigbee2mqtt_new\lib\extension\otaUpdate.js:58:31)
    at async Controller.callExtensionMethod (C:\Users\yurii.andriuk\Desktop\hass_io\zigbee2mqtt_new\lib\controller.js:378:21))
Zigbee2MQTT:info  2020-11-30 12:30:49: MQTT publish: topic 'zigbee2mqtt/0x001e5e09021bf8b1', payload '{"battery_low":false,"contact":true,"linkquality":97,"tamper":false}'
Zigbee2MQTT:info  2020-11-30 12:30:55: MQTT publish: topic 'zigbee2mqtt/0x001e5e09021bf8b1', payload '{"battery_low":false,"contact":true,"linkquality":94,"tamper":true}'
Zigbee2MQTT:info  2020-11-30 12:30:56: MQTT publish: topic 'zigbee2mqtt/0x001e5e09021bf8b1', payload '{"battery_low":false,"contact":true,"linkquality":97,"tamper":false}'
Zigbee2MQTT:info  2020-11-30 12:31:07: MQTT publish: topic 'zigbee2mqtt/0x001e5e09021bf8b1', payload '{"battery_low":false,"contact":true,"linkquality":97,"tamper":true}'
Zigbee2MQTT:info  2020-11-30 12:32:17: MQTT publish: topic 'zigbee2mqtt/0x001e5e09021bf8b1', payload '{"battery_low":false,"contact":true,"linkquality":97,"tamper":true}'
```

**Comment by Koenkk** [comment]
Added, thanks!
