### ISSUE TITLE
Feibit SAA01ZB smoke sensor does not include properly 

### ISSUE THREAD

**Issue by SargonofAssyria** [Koenkk/zigbee2mqtt#5146]
This device does not include. What can I do?

`{"date_code":"20171215","definition":{"description":"Smoke detector","exposes":[{"access":1,"description":"Indicates whether the device detected smoke","name":"smoke","property":"smoke","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Indicates if the battery of this device is almost empty","name":"battery_low","property":"battery_low","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Indicates whether the device is tampered","name":"tamper","property":"tamper","type":"binary","value_off":false,"value_on":true},{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"SSA01ZB","vendor":"Feibit"},"endpoints":{"1":{"bindings":[],"clusters":{"input":["genBasic","genIdentify","genTime","genOta","genPowerCfg","ssIasZone","ssIasAce","touchlink"],"output":["genGroups","genIdentify","genPowerCfg","ssIasZone","ssIasAce"]}}},"friendly_name":"SmokeSlaapkamer","ieee_address":"0x00158d0001ff59b3","interview_completed":true,"interviewing":false,"network_address":48537,"power_source":"Battery","software_build_id":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","supported":true,"type":"EndDevice"}]'
info  2020-12-01 13:57:57: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"Smoke detector","friendly_name":"SmokeSlaapkamer","model":"SSA01ZB","supported":true,"vendor":"Feibit"},"type":"pairing"}'
info  2020-12-01 13:57:57: Changed device specific options of 'SmokeSlaapkamer' ({"retain":true})
error 2020-12-01 13:57:57: Failed to configure 'SmokeSlaapkamer', attempt 2 (Error: ConfigureReporting 0x00158d0001ff59b3/1 genPowerCfg([{"attribute":"batteryAlarmState","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Status 'SOFTWARE_FAILURE')
    at Endpoint.checkStatus (/home/pi/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:173:23)
    at Endpoint.<anonymous> (/home/pi/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:396:26)
    at Generator.next (<anonymous>)
    at fulfilled (/home/pi/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58))
`

## Debug info
Zigbee2MQTT version: 1.16.1-dev commit: b1b134f
Adapter hardware: CC1352P-2
Adapter firmware version: 20201113

**Comment by SargonofAssyria** [comment]
Sorry for the issue, but after the 10 time of inclusion the error is gone and device is working.
