### ISSUE TITLE
Node V12.20 leads to code ELIFECYCLE errno 1 error

### ISSUE THREAD

**Issue by ArJay60** [Koenkk/zigbee2mqtt#5312]
## What happened
Pi4. Fresh install with MQTT and Zigbee2MQTT is working find. After upgrade to node.js V12.20 code ELIFECYCLE errno 1 error and adapters is not reachable.

Zigbee2MQTT:error 2020-12-15 19:37:10: Error: libnode.so.64: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/node_modules/@serialport/bindings/lib/linux.js:2:36)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

## What did you expect to happen

Normal start up of Zigbee2MQTT

## How to reproduce it (minimal and precise)

upgrade node.js to V12.20 (I did this by installing latest node-red)

## Debug info
Zigbee2MQTT version: Zigbee2MQTT version 1.16.2 (commit #0514204)
Adapter hardware: CC2531 but also with Zzh! adapter
Adapter firmware version: latest

**Comment by ArJay60** [comment]
Solved: Did renew install with directly upgrading to nodejs V.12.20 dirst and rebuilding (npm cli -production)
