### ISSUE TITLE
SmartThings 2015 motion sensor fails to interview

### ISSUE THREAD

**Issue by biddster** [Koenkk/zigbee2mqtt#5366]
## What happened

I've just bought one of the prebuilt zigbee usb sticks (CC2538 + CC2592 - Zigbee dongle - ZB3.0), inserted it into a pi2 and been attempting to pair my old SmartThings motion sensors. I have 4 and none of them complete pairing.

Here's a snippet of what happens:

```
Dec 21 20:55:13 pi2 npm[25253]: Zigbee2MQTT:info  2020-12-21 20:55:13: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x000d6f0005760829"},"type":"pairing"}'
Dec 21 20:57:31 pi2 npm[25253]: Zigbee2MQTT:error 2020-12-21 20:57:31: Failed to interview '0x000d6f0005760829', device has not successfully been paired
Dec 21 20:57:31 pi2 npm[25253]: Zigbee2MQTT:info  2020-12-21 20:57:31: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_failed","meta":{"friendly_name":"0x000d6f0005760829"},"type":"pairing"}'
```

## What did you expect to happen

Docs say they're supported so I expected to start getting mqtt messages.

## How to reproduce it (minimal and precise)

Put zigbee2mqtt into pairing mode. Hold the button down on the motion sensor and insert the battery. Motion sensor blue light flashes 3 times. Logging reports interview started. Eventually interview fails.

## Debug info

Zigbee2MQTT version: 1.16.2
Adapter hardware: CC2538 + CC2592 - Zigbee dongle - ZB3.0
Adapter firmware version:
SmartThings Motion sensor model: TSL-SS014

I have an ewlink 240v socket that is working perfectly so I don't think it's a hardware issue with the dongle. 

I've also inserted a new battery and moved the sensor close to the usb dongle. That didn't help. I've also removed all other USB devices from the Pi2 and that doesn't help. The dongle is on an extension lead away from any interference.

**Comment by Koenkk** [comment]
Can you provide the herdsman debug log of the interview?

To enable herdsman debug logging, see https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging

**Comment by biddster** [comment]
Log file attached. Here's the exception at the end of the interview process:

```
zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0x000d6f000575f9bd', attempt 6 +23s
  zigbee-herdsman:controller:device:log Interview - failed for device '0x000d6f000575f9bd' with error 'Error: Interview failed because can not get node descriptor ('0x000d6f000575f9bd')
  zigbee-herdsman:controller:device:log     at Device.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/device.js:350:23)
  zigbee-herdsman:controller:device:log     at Generator.throw (<anonymous>)
  zigbee-herdsman:controller:device:log     at rejected (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/device.js:25:65)' +2ms
  zigbee-herdsman:controller:error Interview failed for '0x000d6f000575f9bd with error 'Error: Interview failed because can not get node descriptor ('0x000d6f000575f9bd')' +0ms
Zigbee2MQTT:error 2021-01-02 16:10:05: Failed to interview '0x000d6f000575f9bd', device has not successfully been paired
```

[zigbee2mqtt.log](https://github.com/Koenkk/zigbee2mqtt/files/5760502/zigbee2mqtt.log)

**Comment by Koenkk** [comment]
Looks the device does not communicate at all, check https://www.zigbee2mqtt.io/information/FAQ.html#interview-fails and try replacing the battery.

**Comment by biddster** [comment]
Thanks for the reply.

I've tried brand new batteries and followed the advice in the link before raising the bug. I'll persist with repeatedly trying to pair them. 

Maybe there's something else I have to do to them before putting them in pairing mode.

**Comment by biddster** [comment]
In case anyone finds themselves landing here, there are now working. 

There have been 2 changes since I raised the bug:

1. Several releases of zigbee2mqtt
2. I changed zigbee channel to 20 from the defaul

I don't know which of the changes fixed it, but these motion sensors pair immediately now and are very lucid in operation.

**Comment by famewolf** [comment]
> In case anyone finds themselves landing here, these are now working.
> 
> There have been 2 changes since I raised the bug:
> 
>     1. Several releases of zigbee2mqtt (I'm now on 1.17.1)
> 
>     2. I changed zigbee channel to 20 from the default
> 
> 
> I don't know which of the changes fixed it, but these motion sensors pair immediately now and are very lucid in operation.

Did you ever nail down if it was the channel change?  I'm on latest z2m with one of those smartthing motions sensors.  Get the flashing blue light for pairing but see no activity in z2m from it.  I'm currently using channel 25 and was hoping you might have updated info since I'd have to re-pair all the existing devices with the new channel (or at least I did the last time I changed the channel).
