### ISSUE TITLE
Eurotronic Spirit - Error: Cluster 'hvacThermostat' has no attribute '16387'

### ISSUE THREAD

**Issue by Robert904** [Koenkk/zigbee2mqtt#5666]
First, thanks a lot for this great software, I love it !
I'm afraid my skills do not allow me to track down this issue myself...

## What happened
After replacing my CC2531 with a CC2652RB and while repairing my eurotronic spirit radiator valves, I get the following error, during the painring and "onZigbeeEvent" and "onMQTTConnected" callbacks :

```
Zigbee2MQTT:error 2021-01-10 10:36:27: Failed to call 'Bridge' 'onMQTTConnected' (Error: Cluster 'hvacThermostat' has no attribute '16387'
    at Object.getAttribute (/local/zigbee2mqtt/node_modules/zigbee-herdsman/dist/zcl/utils.js:84:19)
    at _configuredReportings.map (/local/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:87:36)
    at Array.map (<anonymous>)
    at Endpoint.get configuredReportings [as configuredReportings] (/local/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:83:43)
    at devices.zigbee.getDevices.map (/local/zigbee2mqtt/lib/extension/bridge.js:512:60)
    at Array.map (<anonymous>)
    at Bridge.publishDevices (/local/zigbee2mqtt/lib/extension/bridge.js:484:50)
    at Bridge.onMQTTConnected (/local/zigbee2mqtt/lib/extension/bridge.js:47:20))
```

While I can still use the devices normally, I can't receive anymore the list of devices in the zigbee2mqtt web interface ("Loading devices takes too long time."). Not sure it is related, but it started after I paired the first of these devices.

Enabling the debug messages, I see this, related to an attribute 16387:

```
2021-01-10T09:37:03.631Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":true,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":102,"manufacturerCode":4151,"commandIdentifier":10},"Payload":[{"attrId":16387,"dataType":41,"attrData":2300}]},"address":61145,"endpoint":1,"linkquality":147,"groupID":0}
Zigbee2MQTT:debug 2021-01-10 10:37:03: Received Zigbee message from '0x00158d0001ffc636', type 'attributeReport', cluster 'hvacThermostat', data '{"16387":2300}' from endpoint 1 with groupID 0
```
which seems to contains the requested temperature *100

## What did you expect to happen
No error messages, and list of devices in the web interface

## How to reproduce it (minimal and precise)
Not sure, I had no such error with my CC2531 adapter.  I also tried deleting and repairing the devices with the same outcome

## Debug info
Zigbee2MQTT version: 1.17.0
Adapter hardware: CC2652RB
Adapter firmware version: 20201026

**Comment by Koenkk** [comment]
Fixed!
Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by Robert904** [comment]
Working perfectly, many thanks!
