### ISSUE TITLE
HA integration "died" after changing back and forth the base_topic

### ISSUE THREAD

**Issue by kpmkpm** [Koenkk/zigbee2mqtt#5709]
## What happened
(Perhaps) after changing my zigbee2mqtt base topic from "z2b" to "zigbee2mqtt" the integration with HA seems to be broken. Can controll lights directly via mqtt, but on home assistant I only get errors:

`2021-01-12` 08:40:11 ERROR (MainThread) [homeassistant.util.logging] Exception in state_received when handling msg on 'zigbee2mqtt/light.upstairs_pink': '{"update_available":true}'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/mqtt/debug_info.py", line 35, in wrapper
    msg_callback(msg)
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/mqtt/light/schema_json.py", line 219, in state_received
    if values["state"] == "ON":
KeyError: 'state'`

Seems to be same/related problem as #44057, but did not find the solution.

Tried to changing base_topic back to "z2b" and removing and re-adding the mqtt integration in HA but the problem persists.

## What did you expect to happen
Lights could be controlled by HA as usual.

## Debug info
Zigbee2MQTT version: 1.16.2 (commit #0514204)
Adapter hardware: CC26X2R1
Adapter firmware version:  Z-Stack_3.x.0 20201026 firmware (#226)

**Comment by kpmkpm** [comment]
Further remove / add integration attempts seemed to correct the situation. No need to study this anymore.
