### ISSUE TITLE
No network route - Router 20201026 

### ISSUE THREAD

**Issue by exetico** [Koenkk/zigbee2mqtt#5973]
## What happened
To wrap things up. One day nothing worked at all. I restarted zigbee2mqtt, and everything worked just fine again. The same thing happend the next day, too. At day three, the same thing happend again.

So I updated zigbee2mqtt, and restarted everything.

**Issue** 
Now every button are sending button-presses as they should. My sensors are sending "movement" signals too, but no lamp-bulbs are responding to commands.

Here's a log:
```bash
Zigbee2MQTT:info  2021-01-29 17:36:57: MQTT publish: topic 'zigbee2mqtt/mijia_sensor3', payload '{"battery":100,"linkquality":162,"occupancy":true,"voltage":3005}'
Zigbee2MQTT:info  2021-01-29 17:36:59: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"hue2","ieee_address":"0x0017880103aeb867"},"type":"device_announce"}'
Zigbee2MQTT:info  2021-01-29 17:36:59: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"hue2"},"type":"device_announced"}'
Zigbee2MQTT:info  2021-01-29 17:37:00: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"hue1","ieee_address":"0x0017880104e821a0"},"type":"device_announce"}'
Zigbee2MQTT:info  2021-01-29 17:37:00: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"hue1"},"type":"device_announced"}'
Zigbee2MQTT:info  2021-01-29 17:37:21: MQTT publish: topic 'zigbee2mqtt/aqara1', payload '{"action":"single_left","battery":100,"click":"left","linkquality":102,"voltage":3015}'
Zigbee2MQTT:info  2021-01-29 17:37:21: MQTT publish: topic 'zigbee2mqtt/aqara1', payload '{"action":"","battery":100,"linkquality":102,"voltage":3015}'
Zigbee2MQTT:info  2021-01-29 17:37:21: MQTT publish: topic 'zigbee2mqtt/aqara1', payload '{"battery":100,"click":"","linkquality":102,"voltage":3015}'
Zigbee2MQTT:info  2021-01-29 17:37:21: MQTT publish: topic 'zigbee2mqtt/aqara1/action', payload 'single_left'
Zigbee2MQTT:info  2021-01-29 17:37:21: MQTT publish: topic 'zigbee2mqtt/aqara1/click', payload 'left'
Zigbee2MQTT:error 2021-01-29 17:37:27: Publish 'set' 'brightness' to 'hue6' failed: 'Error: Command 0x0017880108ab1077/11 genLevelCtrl.moveToLevelWithOnOff({"level":208,"transtime":600}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))'
Zigbee2MQTT:info  2021-01-29 17:37:27: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'brightness' to 'hue6' failed: 'Error: Command 0x0017880108ab1077/11 genLevelCtrl.moveToLevelWithOnOff({\"level\":208,\"transtime\":600}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null}) failed (Data request failed with error: 'No network route' (205))'","meta":{"friendly_name":"hue6"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:error 2021-01-29 17:37:27: Publish 'set' 'color_temp' to 'hue5' failed: 'Error: Command 0x0017880108ab1093/11 lightingColorCtrl.moveToColorTemp({"colortemp":400,"transtime":600}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))'
Zigbee2MQTT:info  2021-01-29 17:37:27: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'color_temp' to 'hue5' failed: 'Error: Command 0x0017880108ab1093/11 lightingColorCtrl.moveToColorTemp({\"colortemp\":400,\"transtime\":600}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null}) failed (Data request failed with error: 'No network route' (205))'","meta":{"friendly_name":"hue5"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:error 2021-01-29 17:37:41: Publish 'set' 'state' to 'hue1' failed: 'Error: Command 0x0017880104e821a0/11 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))'
Zigbee2MQTT:info  2021-01-29 17:37:41: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'hue1' failed: 'Error: Command 0x0017880104e821a0/11 genOnOff.off({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null}) failed (Data request failed with error: 'No network route' (205))'","meta":{"friendly_name":"hue1"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:error 2021-01-29 17:37:41: Publish 'set' 'state' to 'hue2' failed: 'Error: Command 0x0017880103aeb867/11 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))'
Zigbee2MQTT:info  2021-01-29 17:37:41: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'hue2' failed: 'Error: Command 0x0017880103aeb867/11 genOnOff.off({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null}) failed (Data request failed with error: 'No network route' (205))'","meta":{"friendly_name":"hue2"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:error 2021-01-29 17:37:46: Publish 'set' 'color_temp' to 'hue6' failed: 'Error: Command 0x0017880108ab1077/11 lightingColorCtrl.moveToColorTemp({"colortemp":400,"transtime":600}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))'
Zigbee2MQTT:info  2021-01-29 17:37:46: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'color_temp' to 'hue6' failed: 'Error: Command 0x0017880108ab1077/11 lightingColorCtrl.moveToColorTemp({\"colortemp\":400,\"transtime\":600}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null}) failed (Data request failed with error: 'No network route' (205))'","meta":{"friendly_name":"hue6"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:error 2021-01-29 17:37:46: Publish 'set' 'brightness' to 'hue5' failed: 'Error: Command 0x0017880108ab1093/11 genLevelCtrl.moveToLevelWithOnOff({"level":208,"transtime":600}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))'
Zigbee2MQTT:info  2021-01-29 17:37:46: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'brightness' to 'hue5' failed: 'Error: Command 0x0017880108ab1093/11 genLevelCtrl.moveToLevelWithOnOff({\"level\":208,\"transtime\":600}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null}) failed (Data request failed with error: 'No network route' (205))'","meta":{"friendly_name":"hue5"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:info  2021-01-29 17:38:07: MQTT publish: topic 'zigbee2mqtt/mijia_sensor3', payload '{"battery":100,"linkquality":162,"occupancy":true,"voltage":3005}'
Zigbee2MQTT:info  2021-01-29 17:38:55: MQTT publish: topic 'zigbee2mqtt/sonoff_basic1', payload '{"linkquality":108,"state":"OFF"}'
Zigbee2MQTT:info  2021-01-29 17:39:32: MQTT publish: topic 'zigbee2mqtt/mijia_sensor3', payload '{"battery":100,"linkquality":162,"occupancy":true,"voltage":3005}'
Zigbee2MQTT:info  2021-01-29 17:40:30: MQTT publish: topic 'zigbee2mqtt/blitzwolf_switch1', payload '{"current":0,"energy":15.59,"linkquality":39,"power":0,"state":"ON","voltage":220}'
Zigbee2MQTT:info  2021-01-29 17:40:30: MQTT publish: topic 'zigbee2mqtt/blitzwolf_switch1', payload '{"current":0,"energy":15.59,"linkquality":39,"power":0,"state":"ON","voltage":220}'
Zigbee2MQTT:info  2021-01-29 17:40:30: MQTT publish: topic 'zigbee2mqtt/blitzwolf_switch1', payload '{"current":0,"energy":15.59,"linkquality":36,"power":0,"state":"ON","voltage":220}'
Zigbee2MQTT:info  2021-01-29 17:40:40: MQTT publish: topic 'zigbee2mqtt/mijia_sensor3', payload '{"battery":100,"linkquality":159,"occupancy":true,"voltage":3005}'
Zigbee2MQTT:info  2021-01-29 17:40:43: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"hue1","ieee_address":"0x0017880104e821a0"},"type":"device_announce"}'
Zigbee2MQTT:info  2021-01-29 17:40:43: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"hue1"},"type":"device_announced"}'
Zigbee2MQTT:info  2021-01-29 17:40:43: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"hue2","ieee_address":"0x0017880103aeb867"},"type":"device_announce"}'
Zigbee2MQTT:info  2021-01-29 17:40:43: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"hue2"},"type":"device_announced"}'
Zigbee2MQTT:info  2021-01-29 17:40:48: MQTT publish: topic 'zigbee2mqtt/mijia_sensor2', payload '{"battery":100,"linkquality":60,"occupancy":true,"voltage":3015}'
Zigbee2MQTT:info  2021-01-29 17:40:49: MQTT publish: topic 'zigbee2mqtt/sonoff_motion1', payload '{"battery":65,"battery_low":false,"linkquality":69,"occupancy":true,"tamper":false,"voltage":2900}'
Zigbee2MQTT:info  2021-01-29 17:41:28: MQTT publish: topic 'zigbee2mqtt/mijia5', payload '{"battery":100,"linkquality":66,"voltage":3082}'
Zigbee2MQTT:info  2021-01-29 17:41:34: MQTT publish: topic 'zigbee2mqtt/aqara1', payload '{"action":"single_left","battery":100,"click":"left","linkquality":96,"voltage":3015}'
Zigbee2MQTT:info  2021-01-29 17:41:34: MQTT publish: topic 'zigbee2mqtt/aqara1', payload '{"action":"","battery":100,"linkquality":96,"voltage":3015}'
Zigbee2MQTT:info  2021-01-29 17:41:34: MQTT publish: topic 'zigbee2mqtt/aqara1', payload '{"battery":100,"click":"","linkquality":96,"voltage":3015}'
Zigbee2MQTT:info  2021-01-29 17:41:34: MQTT publish: topic 'zigbee2mqtt/aqara1/action', payload 'single_left'
Zigbee2MQTT:info  2021-01-29 17:41:34: MQTT publish: topic 'zigbee2mqtt/aqara1/click', payload 'left'
```

As you can see, it's trying to send the command, but ending up reporting the `No network route` error.

Here's the output in the logs, with `debug`-mode. Payload `left` are just the button, which are used to trigger the lamp through Home Assistant.

```
Zigbee2MQTT:info  2021-01-29 17:44:21: MQTT publish: topic 'zigbee2mqtt/aqara1/click', payload 'left'
Zigbee2MQTT:debug 2021-01-29 17:44:21: Received MQTT message on 'zigbee2mqtt/hue1/set' with data '{"state": "OFF"}'
Zigbee2MQTT:debug 2021-01-29 17:44:21: Publishing 'set' 'state' to 'hue1'
Zigbee2MQTT:debug 2021-01-29 17:44:21: Received MQTT message on 'zigbee2mqtt/hue2/set' with data '{"state": "OFF"}'
Zigbee2MQTT:debug 2021-01-29 17:44:21: Publishing 'set' 'state' to 'hue2'
Zigbee2MQTT:debug 2021-01-29 17:44:22: Received Zigbee message from 'mijia_sensor3', type 'attributeReport', cluster 'msOccupancySensing', data '{"occupancy":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-01-29 17:44:22: MQTT publish: topic 'zigbee2mqtt/mijia_sensor3', payload '{"battery":100,"linkquality":162,"occupancy":true,"voltage":3005}'
Zigbee2MQTT:error 2021-01-29 17:44:29: Publish 'set' 'state' to 'hue1' failed: 'Error: Command 0x0017880104e821a0/11 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'MAC channel access failure' (225))'
Zigbee2MQTT:debug 2021-01-29 17:44:29: Error: Command 0x0017880104e821a0/11 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'MAC channel access failure' (225))
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:339:27)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
Zigbee2MQTT:info  2021-01-29 17:44:29: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'hue1' failed: 'Error: Command 0x0017880104e821a0/11 genOnOff.off({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null}) failed (Data request failed with error: 'MAC channel access failure' (225))'","meta":{"friendly_name":"hue1"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:error 2021-01-29 17:44:29: Publish 'set' 'state' to 'hue2' failed: 'Error: Command 0x0017880103aeb867/11 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'MAC channel access failure' (225))'
Zigbee2MQTT:debug 2021-01-29 17:44:29: Error: Command 0x0017880103aeb867/11 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'MAC channel access failure' (225))
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:339:27)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
Zigbee2MQTT:info  2021-01-29 17:44:29: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'hue2' failed: 'Error: Command 0x0017880103aeb867/11 genOnOff.off({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null}) failed (Data request failed with error: 'MAC channel access failure' (225))'","meta":{"friendly_name":"hue2"},"type":"zigbee_publish_error"}'
```

My hue bulbs are not grouped right now. That's why you're seeing two hues (`hue1` and `hue2`) in the output.

## What did you expect to happen
The `hue1` and `hue2` should recieve the command, and turn on.

## How to reproduce it (minimal and precise)
It's not possible, cause I think it's related to a bug, which only are able to be reproduced right now, in my setup. But I'll do whatever it takes to help you our, if you need anything from my end.

I've a good amount of devices, but not anything near the limit for `LAUNCHXL-CC26X2R1`. I've also swapped it out, with another board, just to be sure. (_Mouser provided a replacement-unit, due to the instability-issues i had_)

## Extra details
It's like it's recieving every input, as it should. It's only a problem with "outgoing" messages to the devices, like "turn off/turn on". My ZigBee Switches and LED-strips are not working, too (like the `hue` bulbs).

## Debug info
Zigbee2MQTT version: `zigbee2mqtt@1.17.0 start /app`
Adapter hardware: `LAUNCHXL-CC26X2R1`
Adapter firmware version: `CC26X2R1_20201026`

**Comment by exetico** [comment]
Oh, wow. I just tried to replug my device to the VM, and nothing helped. But after restarted my VM a few times, i managed to get it to work again.

I've mentioned that my pass-through are not ideal, in my VM setup. Sometimes it's VERY hard to get the device to work. But after it's initiated properly, everything are working as expected.

Well... I'll close this one and get back, if things are not stable in the next couple of days.

And oh: Are there any new firmware on the way for the `CC26X2R1`?

**Comment by exetico** [comment]
For people finding this on Google, I've moved to a solution with S2E. You can find a guide in [this post](https://github.com/Koenkk/zigbee2mqtt/discussions/5266#discussioncomment-323703).
