### ISSUE TITLE
problems connecting to a Mosquitto V2 in early moments of the Z2M container boot.

### ISSUE THREAD

**Issue by netweaver1970** [Koenkk/zigbee2mqtt#6314]
errors when booting up the docker container.
Upgraded to Mosquitto V2 recently.
Sometimes the Z2M container stops with error 137.

Details:
```
Zigbee2MQTT version  1.17.1-dev commit: 9dd9f33
Coordinator type  zStack3x0
Coordinator revision  20201113
Frontend version  0.3.54
```

Below error is repeatable, when restarting the container.

```
Zigbee2MQTT:error 2021-02-15 22:32:37: Cannot send message: topic: 'zigbee2mqtt/Aqara PIR Office', payload: '{"battery":100,"elapsed":4,"illuminance":26,"illuminance_lux":26,"last_seen":"2021-02-15T22:32:36+00:00","linkquality":144,"occupancy":true,"temperature":24,"voltage":3015}
Zigbee2MQTT:error 2021-02-15 22:32:37: Not connected to MQTT server!
Zigbee2MQTT:error 2021-02-15 22:32:37: Cannot send message: topic: 'zigbee2mqtt/Aqara PIR Office', payload: '{"battery":100,"elapsed":6,"illuminance":30,"illuminance_lux":30,"last_seen":"2021-02-15T22:32:36+00:00","linkquality":144,"occupancy":true,"temperature":24,"voltage":3015}
Zigbee2MQTT:error 2021-02-15 22:32:37: Not connected to MQTT server!
Zigbee2MQTT:error 2021-02-15 22:32:37: Cannot send message: topic: 'zigbee2mqtt/Aqara PIR Office', payload: '{"battery":100,"elapsed":4,"illuminance":30,"illuminance_lux":30,"last_seen":"2021-02-15T22:32:36+00:00","linkquality":144,"occupancy":true,"temperature":24,"voltage":3015}
Zigbee2MQTT:error 2021-02-15 22:32:37: Not connected to MQTT server!
Zigbee2MQTT:error 2021-02-15 22:32:37: Cannot send message: topic: 'zigbee2mqtt/bridge/log', payload: '{"message":"announce","meta":{"friendly_name":"0x60a423fffe113527"},"type":"device_announced"}
Zigbee2MQTT:error 2021-02-15 22:32:38: Not connected to MQTT server!
Zigbee2MQTT:error 2021-02-15 22:32:38: Cannot send message: topic: 'zigbee2mqtt/TH_Fridge', payload: '{"battery":62,"elapsed":0,"humidity":66.67,"last_seen":"2021-02-15T22:32:36+00:00","linkquality":66,"pressure":1023,"temperature":7.85,"voltage":2935}
Zigbee2MQTT:info  2021-02-15 22:32:39: Connected to MQTT server
Zigbee2MQTT:info  2021-02-15 22:32:39: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'

```

after a while all 'falls through' and connects fine to the Mosquitto.

Can also happen in the middle of a 'good' section:
```
Zigbee2MQTT:info  2021-02-15 22:41:14: MQTT publish: topic 'zigbee2mqtt/Aqara PIR Office', payload '{"battery":100,"elapsed":6,"illuminance":26,"illuminance_lux":26,"last_seen":"2021-02-15T22:41:14+00:00","linkquality":87,"occupancy":true,"temperature":24,"voltage":3015}'
Zigbee2MQTT:info  2021-02-15 22:41:14: MQTT publish: topic 'zigbee2mqtt/MasterBedroomTV', payload '{"last_seen":"2021-02-15T22:41:14+00:00","linkquality":78,"power_on_behavior":"previous","state":"OFF","update":{"state":"idle"},"update_available":false}'
Zigbee2MQTT:error 2021-02-15 22:41:34: Not connected to MQTT server!
Zigbee2MQTT:error 2021-02-15 22:41:45: Cannot send message: topic: 'zigbee2mqtt/TH_Garage', payload: '{"battery":86,"elapsed":1,"humidity":43.17,"last_seen":"2021-02-15T22:41:13+00:00","linkquality":66,"pressure":1017,"temperature":17.5,"voltage":2975}
Zigbee2MQTT:error 2021-02-15 22:41:47: Not connected to MQTT server!
Zigbee2MQTT:error 2021-02-15 22:41:47: Cannot send message: topic: 'zigbee2mqtt/TH_Fridge', payload: '{"battery":62,"elapsed":0,"humidity":64.83,"last_seen":"2021-02-15T22:41:14+00:00","linkquality":69,"pressure":1023,"temperature":7.3,"voltage":2935}
(node:17) UnhandledPromiseRejectionWarning: Error: SRSP - ZDO - mgmtPermitJoinReq after 6000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
Zigbee2MQTT:error 2021-02-15 22:42:02: Not connected to MQTT server!
Zigbee2MQTT:error 2021-02-15 22:42:04: Not connected to MQTT server!
Zigbee2MQTT:error 2021-02-15 22:42:04: Cannot send message: topic: 'zigbee2mqtt/IKEA PIR Hall', payload: '{"battery":74,"last_seen":"2021-02-15T22:42:04+00:00","linkquality":99,"occupancy":true,"requested_brightness_level":76,"requested_brightness_percent":30,"update":{"state":"idle"},"update_available":false}
Zigbee2MQTT:error 2021-02-15 22:42:05: Not connected to MQTT server!
Zigbee2MQTT:error 2021-02-15 22:42:05: Cannot send message: topic: 'zigbee2mqtt/Aqara PIR Office', payload: '{"battery":100,"elapsed":50164,"illuminance":26,"illuminance_lux":26,"last_seen":"2021-02-15T22:42:04+00:00","linkquality":69,"occupancy":true,"temperature":24,"voltage":3015}
Zigbee2MQTT:error 2021-02-15 22:42:05: Not connected to MQTT server!
Zigbee2MQTT:error 2021-02-15 22:42:05: Cannot send message: topic: 'zigbee2mqtt/Aqara PIR Office', payload: '{"battery":100,"elapsed":703,"illuminance":26,"illuminance_lux":26,"last_seen":"2021-02-15T22:42:04+00:00","linkquality":69,"occupancy":true,"temperature":24,"voltage":3015}
```

Any idea?
Thanks.

**Comment by Koenkk** [comment]
Regarding startup, could it be that z2m starts faster than mosquitto?

**Comment by IngoHenning** [comment]
Starting with the release of Mosquitto version 2.0.0 the default config will only bind to localhost and will not accept external connections. More information can be found in the release notes https://mosquitto.org/blog/2020/12/version-2-0-0-released/

I had the same issue and downgraded to Mosquitto 1.63 for a quick fix.

**Comment by Pofilo** [comment]
@IngoHenning I suppose you talk about Mosquitto 1.6.13 !
But yeah, it works with a downgrade, thanks for the tip !

**Comment by IngoHenning** [comment]
You are right, I mean 1.6.13 sorry

**Comment by IngoHenning** [comment]
@Pofilo You are right, I mean 1.6.13 sorry

**Comment by netweaver1970** [comment]
I've got Mosquitto v2 running with this conf file (from Andreas Spiess IOTstack fork) : https://github.com/SensorsIot/IOTstack/blob/master/.templates/mosquitto/mosquitto.conf
and this docker-compose service file snippet :  https://github.com/SensorsIot/IOTstack/blob/master/.templates/mosquitto/service.yml

It kind of works fine now, only the booting up of z2m acts up and sometimes in the middle of a session it also stops connecting. And it recovers again later.

very weird.

**Comment by Pofilo** [comment]
I think this issue can be closed.
The problem was because the 2.0 version of Mosquitto binds to localhost.
A solution is to add `listener 1883` to the conf as explained in the documentation.
