### ISSUE TITLE
TypeError raised during bind from MQTT message

### ISSUE THREAD

**Issue by stwalkerster** [Koenkk/zigbee2mqtt#6651]
## What happened
I attempted to bind an IKEA Trafdri remote to an IKEA Tradfri bulb via an MQTT message `{"from":"ikearemote01", "device":"ikeabulb01"}` to the topic `automation/zigbee/bridge/request/device/bind` (where MQTT base topic is `automation/zigbee`)

Upon doing so, the following message appeared in the frontend:
![image](https://user-images.githubusercontent.com/722710/110681603-e8dede00-81d1-11eb-9a63-5af2c86f0e4c.png)

... and this was logged in the log:
```
Zigbee2MQTT:debug 2021-03-10 18:45:30: Received MQTT message on 'automation/zigbee/bridge/request/device/bind' with data '{"from":"ikearemote01", "device":"ikeabulb01"}'
Zigbee2MQTT:error 2021-03-10 18:45:30: Failed to call 'Bind' 'onMQTTMessage' (TypeError: Cannot read property 'constructor' of undefined
    at Zigbee.resolveEntity (/app/lib/zigbee.js:182:17)
    at Bind.onMQTTMessage (/app/lib/extension/bind.js:152:92)
    at Controller.callExtensionMethod (/app/lib/controller.js:380:44)
    at processTicksAndRejections (internal/process/task_queues.js:93:5))
```

## What did you expect to happen
I expected the remote to be bound to the device without error.

## How to reproduce it (minimal and precise)
1. Pair a "TRADFRI LED bulb E14/E26/E27 600 lumen, dimmable, color, opal white" and a "TRADFRI remote control" to a zigbee2mqtt instance.
2. Set the friendly name of the devices to something friendly, such as "ikeabulb01" and "ikearemote01"
3. Bind the remote to the bulb via an MQTT message as described above

## Debug info
Zigbee2MQTT version: 1.18.1 (docker)
Adapter hardware: CC2531
Adapter firmware version: zStack12 20201127
Full logs: https://gist.github.com/stwalkerster/7f9a3f394988cd9408232d61c3a0b88e

**Comment by stwalkerster** [comment]
Following update to 1.18.2, I'm not getting this error any longer, though binding appears to succeed from the log messages, it does not appear to do anything. I'll continue to investigate on my end, and if I find anything useful I'll raise it as a different issue.
