### ISSUE TITLE
Zigbee2mqtt won't connect to MQTT.

### ISSUE THREAD

**Issue by MastrUsr** [Koenkk/zigbee2mqtt#6955]
## What happened
Zigbee2mqtt won't connect to mqtt.

## What did you expect to happen
For it to connect and start.

## Debug info
Zigbee2MQTT version: latest but also tried 1.17.1
Adapter hardware: Conbee II
Adapter firmware version: Flashed this file - deCONZ_ConBeeII_0x26680700.bin.GCF

**Log from Portainer:**
`2021-04-04T12:44:34.150343296Z Zigbee2MQTT:error 2021-04-04 14:44:34: Not connected to MQTT server!
2021-04-04T12:44:34.151169209Z Zigbee2MQTT:error 2021-04-04 14:44:34: Cannot send message: topic: 'zigbee2mqtt/bridge/state', payload: 'offline
2021-04-04T12:44:34.151770327Z Zigbee2MQTT:info  2021-04-04 14:44:34: Disconnecting from MQTT server
2021-04-04T12:44:34.154482102Z (node:16) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'end' of undefined
2021-04-04T12:44:34.154519113Z     at MQTT.disconnect (/app/lib/mqtt.js:93:21)
2021-04-04T12:44:34.154531777Z     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-04-04T12:44:34.154544243Z     at async Controller.stop (/app/lib/controller.js:194:9)
2021-04-04T12:44:34.154586567Z (Use `node --trace-warnings ...` to show where the warning was created)
2021-04-04T12:44:34.154597095Z (node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
2021-04-04T12:44:34.154613973Z (node:16) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-04-04T12:44:45.411375454Z Using '/app/data' as data directory
2021-04-04T12:44:45.625849320Z 
2021-04-04T12:44:45.625869152Z > zigbee2mqtt@1.17.1 start /app
2021-04-04T12:44:45.625872447Z > node index.js
2021-04-04T12:44:45.625875128Z 
2021-04-04T12:44:46.184421603Z Zigbee2MQTT:debug 2021-04-04 14:44:46: Loaded state from file /app/data/state.json
2021-04-04T12:44:46.186336492Z Zigbee2MQTT:info  2021-04-04 14:44:46: Logging to console and directory: '/app/data/log/2021-04-04.14-44-45' filename: log.txt
2021-04-04T12:44:46.187382111Z Zigbee2MQTT:debug 2021-04-04 14:44:46: Removing old log directory '/app/data/log/2021-04-04.14-34-09'
2021-04-04T12:44:46.202724961Z Zigbee2MQTT:info  2021-04-04 14:44:46: Starting Zigbee2MQTT version 1.17.1 (commit #99274c7)
2021-04-04T12:44:46.203784293Z Zigbee2MQTT:info  2021-04-04 14:44:46: Starting zigbee-herdsman (0.13.59)
2021-04-04T12:44:46.204307891Z Zigbee2MQTT:debug 2021-04-04 14:44:46: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"deconz","path":"/dev/ttyACM0"}}'
2021-04-04T12:44:46.315141882Z CREATED DECONZ ADAPTER
2021-04-04T12:44:46.523040387Z Zigbee2MQTT:info  2021-04-04 14:44:46: zigbee-herdsman started
2021-04-04T12:44:46.621517301Z Zigbee2MQTT:info  2021-04-04 14:44:46: Coordinator firmware version: '{"meta":{"maintrel":0,"majorrel":38,"minorrel":74,"product":0,"revision":"0x264a0700","transportrev":0},"type":"ConBee2/RaspBee2"}'
2021-04-04T12:44:47.020277479Z Zigbee2MQTT:debug 2021-04-04 14:44:47: Zigbee network parameters: {"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754}
2021-04-04T12:44:47.022678158Z Zigbee2MQTT:info  2021-04-04 14:44:47: Currently 0 devices are joined:
2021-04-04T12:44:47.023603933Z Zigbee2MQTT:warn  2021-04-04 14:44:47: `permit_join` set to  `true` in configuration.yaml.
2021-04-04T12:44:47.023859785Z Zigbee2MQTT:warn  2021-04-04 14:44:47: Allowing new devices to join.
2021-04-04T12:44:47.024073261Z Zigbee2MQTT:warn  2021-04-04 14:44:47: Set `permit_join` to `false` once you joined all devices.
2021-04-04T12:44:47.024389636Z Zigbee2MQTT:info  2021-04-04 14:44:47: Zigbee: allowing new devices to join.
2021-04-04T12:44:47.026978160Z Zigbee2MQTT:info  2021-04-04 14:44:47: Started frontend on port 0.0.0.0:8099
`

I can connect to mqtt from Home Assitant and from MQTT Explorer (Widnows 10).

**zigbee2mqtt configuration file:**
`# Home Assistant integration (MQTT discovery)
homeassistant: true

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://192.168.1.59'
  # MQTT server authentication, uncomment if required:
  user: 'mastrusr'
  password: 'password'
  client_id: 'zigbee2mqtt'
  include_device_information: true
  reject_unauthorized: false

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  port: /dev/ttyACM0
  disable_led: false
  adapter: deconz

frontend:
  # Optional, default 8080
  port: 8099
  # Optional, default 0.0.0.0
  host: 0.0.0.0
  # Optional, enables authentication, disabled by default
  # auth_token: your-secret-token

experimental:
  new_api: true

advanced:
  log_level: debug`

part of docker-compose file:
`mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ~/iotstack/mqtt/config/:/mosquitto/config
      - ~/iotstack/mqtt/data/:/mosquitto/data
      - ~/iotstack/mqtt/log/:/mosquitto/log
    user: 1000:1000

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.17.1
    volumes:
     - ~/iotstack/zigbee2mqtt/data:/app/data
     - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2417234-if00:/dev/ttyACM0
     #- /dev/ttyACM0:/dev/ttyACM0
    ports:
      - '8092:8080'
      - '8099:8099'
    restart: unless-stopped
#    network_mode: host
#    privileged: true
    environment:
      - TZ=Europe/Stockholm`

**Comment by MastrUsr** [comment]
This issue put me on a wild goose chase. I thought i activated:

> advanced:
  log_level: debug

but I missed the docker part:

> -e DEBUG=zigbee-herdsman*

I looked through the logs and found that something probably was wrong with the adapter even though the initial logs seemed to tell me otherwise... After even more(!) googling i stumbled upon something about usb 2.0 and 3.0... Moved my Conbee II to a USB 2.0 port and MAGIC! This also explains why my z-wave dongle became unresponsive when i started the zigbee2mqtt container... Wow... I'm now running the latest containers of everything and so far it seems to work :)
