### ISSUE TITLE
DNCKAT_S001 has an error during control

### ISSUE THREAD

**Issue by Kanson4** [Koenkk/zigbee2mqtt#706]
I have a light module (DNCKAT_S001) that can receive the switch real-time switching status in HA, but an error occurs when sending a light switch command with MQTT. What went wrong? Thank you.

  zigbee2mqtt:debug 2018-12-15 13:14:20 Received MQTT message on 'zigbee2mqtt/0x00124b00042fd192/set' with data 'ON'
/opt/zigbee2mqtt/lib/extension/devicePublish.js:108
            const converter = model.toZigbee.find((c) => c.key === key);
                                                           ^

TypeError: Cannot read property 'key' of undefined
    at model.toZigbee.find (/opt/zigbee2mqtt/lib/extension/devicePublish.js:108:60)
    at Array.find (native)
    at Object.keys.forEach (/opt/zigbee2mqtt/lib/extension/devicePublish.js:108:46)
    at Array.forEach (<anonymous>)
    at DevicePublish.handleMQTTMessage (/opt/zigbee2mqtt/lib/extension/devicePublish.js:107:27)
    at results.extensions.filter.map (/opt/zigbee2mqtt/lib/controller.js:325:27)
    at Array.map (<anonymous>)
    at Controller.handleMQTTMessage (/opt/zigbee2mqtt/lib/controller.js:325:14)
    at MQTT.handleMessage (/opt/zigbee2mqtt/lib/mqtt.js:82:18)
    at emitThree (events.js:136:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@0.2.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-12-15T05_14_20_245Z-debug.log

**Comment by Kanson4** [comment]
The problem of reinstalling Z2M has been solved
