### ISSUE TITLE
Error: SRSP - SYS - ping after 6000ms after flashing CC2652R

### ISSUE THREAD

**Issue by pisaman2** [Koenkk/zigbee2mqtt#7250]
## What happened
After a long period of stability, I flashed a new coordinator firmware to my ZZH CC2652R, and restarting zigbee2mqtt fails to start due to `Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)`

I have tried rebooting the pi, verified my power supply is adequate and tried various different USB slots. 

## What did you expect to happen
Z2M to start
## How to reproduce it (minimal and precise)
Flash CC2652R firmware, and restart Z2M
## Debug info
Zigbee2MQTT version:#2b488cc (Docker)
Adapter hardware: CC2652R
Adapter firmware version: CC2652R_coordinator_20210120.zip

### Herdsmen log
```
Starting zigbee2mqtt ... done
Attaching to zigbee2mqtt
zigbee2mqtt      | Using '/app/data' as data directory
zigbee2mqtt      | Zigbee2MQTT:debug 2021-04-29 17:18:35: Loaded state from file /app/data/state.json
zigbee2mqtt      | Zigbee2MQTT:info  2021-04-29 17:18:35: Logging to console and directory: '/app/data/log/2021-04-29.17-18-33' filename: log.txt
zigbee2mqtt      | Zigbee2MQTT:debug 2021-04-29 17:18:35: Removing old log directory '/app/data/log/2021-04-29.16-56-58'
zigbee2mqtt      | Zigbee2MQTT:info  2021-04-29 17:18:35: Starting Zigbee2MQTT version 1.18.2-dev (commit #2b488cc)
zigbee2mqtt      | Zigbee2MQTT:info  2021-04-29 17:18:35: Starting zigbee-herdsman (0.13.92)
zigbee2mqtt      | Zigbee2MQTT:debug 2021-04-29 17:18:35: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null},"backupPath":"/app/data/coordinator_backup.json","databaseBackupPath":"/app/data/database.db.backup","databasePath":"/app/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyUSB0","rtscts":false}}'
zigbee2mqtt      | 2021-04-29T16:18:36.503Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"rtscts":false,"path":"/dev/ttyUSB0"},"databasePath":"/app/data/database.db","databaseBackupPath":"/app/data/database.db.backup","backupPath":"/app/data/coordinator_backup.json","adapter":{"concurrent":null,"delay":null}}'
zigbee2mqtt      | 2021-04-29T16:18:36.513Z zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /dev/ttyUSB0 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
zigbee2mqtt      | 2021-04-29T16:18:36.525Z zigbee-herdsman:adapter:zStack:znp:log Serialport opened
zigbee2mqtt      | 2021-04-29T16:18:36.993Z zigbee-herdsman:adapter:zStack:znp:log Writing skip bootloader payload
zigbee2mqtt      | 2021-04-29T16:18:36.993Z zigbee-herdsman:adapter:zStack:unpi:writer --> buffer [239]
zigbee2mqtt      | 2021-04-29T16:18:38.000Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
zigbee2mqtt      | 2021-04-29T16:18:38.004Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
zigbee2mqtt      | 2021-04-29T16:18:44.007Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
zigbee2mqtt      | 2021-04-29T16:18:44.008Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
zigbee2mqtt      | 2021-04-29T16:18:50.011Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
zigbee2mqtt      | 2021-04-29T16:18:50.012Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
zigbee2mqtt      | Zigbee2MQTT:error 2021-04-29 17:18:56: Error while starting zigbee-herdsman
zigbee2mqtt      | Zigbee2MQTT:error 2021-04-29 17:18:56: Failed to start zigbee
zigbee2mqtt      | Zigbee2MQTT:error 2021-04-29 17:18:56: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
zigbee2mqtt      | Zigbee2MQTT:error 2021-04-29 17:18:56: Exiting...
zigbee2mqtt      | Zigbee2MQTT:error 2021-04-29 17:18:56: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
zigbee2mqtt      |     at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
zigbee2mqtt      |     at Generator.throw (<anonymous>)
zigbee2mqtt      |     at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
zigbee2mqtt exited with code 1
```
### Flashing Log
```
root@pi4:~/cc2538-bsl-master# python3 cc2538-bsl.py -p  /dev/zigbee_0 -evw CC2652R_coordinator_20210120.zip
Opening port /dev/zigbee_0, baud 500000
Reading data from CC2652R_coordinator_20210120.zip
Cannot auto-detect firmware filetype: Assuming .bin
Connecting to target...
CC1350 PG2.0 (7x7mm): 352KB Flash, 20KB SRAM, CCFG.BL_CONFIG at 0x00057FD8
Primary IEEE Address: 00:12:4B:00:21:B7:7B:A5
    Performing mass erase
Erasing all main bank flash sectors
    Erase done
Writing 171020 bytes starting at address 0x00000000
Write 148 bytes at 0x00029B780
    Write done
Verifying by comparing CRC32 calculations.
    Verified (match: 0x6a270c43)
```

### Docker Compose Extract
```
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest-dev
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
        #restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - DEBUG=zigbee-herdsman*
      - TZ=Europe/London
```

### Making sure I have the right device ID
```
root@pi4:/home/pi/Docker/homeassistant# ls -l /dev/serial/by-id
total 0
lrwxrwxrwx 1 root root 13 Apr 29 17:17 usb-1a86_USB_Serial-if00-port0 -> ../../ttyUSB0
```
### Checking port permissions
```
root@pi4:/home/pi# docker exec -it zigbee2mqtt test -w  /dev/ttyUSB0 && echo success || echo failure
failed to resize tty, using default size
                                        success
```

**Comment by pisaman2** [comment]
You can file this one under user error and general stupidity.

I flashed the uncompressed ZIP file, and not the hex one!
