### ISSUE TITLE
KeyError on HomeAssistant

### ISSUE THREAD

**Issue by vdkeybus** [Koenkk/zigbee2mqtt#7306]
Hi,

I made a mistake, lost my configuration and had to re-pair all devices. However, I'm now facing a problem in HA. Is this something that's wrong in Z2M or HA ?

```
May 03 00:12:17 zacate hass[3333011]: 2021-05-03 00:12:17 ERROR (MainThread) [homeassistant.util.logging] Exception in state_received when handling msg on 'zigbee2mqtt/0x680ae2fffead62ea': '{"brightness":254,"color":{"x":0.4599,"y":0.41>
May 03 00:12:17 zacate hass[3333011]: Traceback (most recent call last):
May 03 00:12:17 zacate hass[3333011]:   File "/home/homeassistant/homeassistant/lib/python3.8/site-packages/homeassistant/components/mqtt/debug_info.py", line 32, in wrapper
May 03 00:12:17 zacate hass[3333011]:     msg_callback(msg)
May 03 00:12:17 zacate hass[3333011]:   File "/home/homeassistant/homeassistant/lib/python3.8/site-packages/homeassistant/components/mqtt/light/schema_json.py", line 306, in state_received
May 03 00:12:17 zacate hass[3333011]:     self._update_color(values)
May 03 00:12:17 zacate hass[3333011]:   File "/home/homeassistant/homeassistant/lib/python3.8/site-packages/homeassistant/components/mqtt/light/schema_json.py", line 245, in _update_color
May 03 00:12:17 zacate hass[3333011]:     color_mode = values["color_mode"]
May 03 00:12:17 zacate hass[3333011]: KeyError: 'color_mode'
```

Thanks,

**Comment by vdkeybus** [comment]
I see this is probably #7220.
