### ISSUE TITLE
Moes MS-104Z fails to configure

### ISSUE THREAD

**Issue by dvandonkelaar** [Koenkk/zigbee2mqtt#7562]
## What happened
After linking the [Moes MS-104Z](https://www.zigbee2mqtt.io/devices/MS-104Z.html#moes-ms-104z) to Z2M, the interview completes but fails to configure.
```
Zigbee2MQTT:info  2021-05-22 17:51:32: Device '0x60a423fffead6dc5' joined
Zigbee2MQTT:info  2021-05-22 17:51:32: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x60a423fffead6dc5","ieee_address":"0x60a423fffead6dc5"},"type":"device_joined"}'
Zigbee2MQTT:info  2021-05-22 17:51:32: Starting interview of '0x60a423fffead6dc5'
Zigbee2MQTT:info  2021-05-22 17:51:33: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x60a423fffead6dc5","ieee_address":"0x60a423fffead6dc5","status":"started"},"type":"device_interview"}'
Zigbee2MQTT:info  2021-05-22 17:51:33: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x60a423fffead6dc5"},"type":"device_connected"}'
Zigbee2MQTT:info  2021-05-22 17:51:33: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x60a423fffead6dc5"},"type":"pairing"}'
Zigbee2MQTT:debug 2021-05-22 17:52:15: Device '0x60a423fffead6dc5' announced itself
Zigbee2MQTT:info  2021-05-22 17:52:15: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x60a423fffead6dc5","ieee_address":"0x60a423fffead6dc5"},"type":"device_announce"}'
Zigbee2MQTT:info  2021-05-22 17:52:15: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x60a423fffead6dc5"},"type":"device_announced"}'
Zigbee2MQTT:debug 2021-05-22 17:52:15: Received Zigbee message from '0x60a423fffead6dc5', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:15: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-05-22 17:52:16: Received Zigbee message from '0x60a423fffead6dc5', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:16: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-05-22 17:52:16: Received Zigbee message from '0x60a423fffead6dc5', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:16: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-05-22 17:52:16: Received Zigbee message from '0x60a423fffead6dc5', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:16: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-05-22 17:52:16: Received Zigbee message from '0x60a423fffead6dc5', type 'attributeReport', cluster 'genOnOff', data '{"onOff":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:16: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-05-22 17:52:17: Received Zigbee message from '0x60a423fffead6dc5', type 'attributeReport', cluster 'genOnOff', data '{"moesStartUpOnOff":0,"offWaitTime":0,"onOff":1,"onTime":0,"tuyaBacklightMode":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:17: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-05-22 17:52:17: Received Zigbee message from '0x60a423fffead6dc5', type 'readResponse', cluster 'genBasic', data '{"modelId":"TS011F"}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:17: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-05-22 17:52:17: Received Zigbee message from '0x60a423fffead6dc5', type 'attributeReport', cluster 'genOnOff', data '{"moesStartUpOnOff":0,"offWaitTime":0,"onOff":1,"onTime":0,"tuyaBacklightMode":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:17: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-05-22 17:52:17: Received Zigbee message from '0x60a423fffead6dc5', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"_TZ3000_zmy1waw6"}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:17: Received Zigbee message from '0x60a423fffead6dc5', type 'readResponse', cluster 'genBasic', data '{"powerSource":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:18: Received Zigbee message from '0x60a423fffead6dc5', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:18: Received Zigbee message from '0x60a423fffead6dc5', type 'readResponse', cluster 'genBasic', data '{"appVersion":65}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:18: Received Zigbee message from '0x60a423fffead6dc5', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:21: Received Zigbee message from '0x60a423fffead6dc5', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:22: Received Zigbee message from '0x60a423fffead6dc5', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:22: Received Zigbee message from '0x60a423fffead6dc5', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:22: Received Zigbee message from '0x60a423fffead6dc5', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:22: Received Zigbee message from '0x60a423fffead6dc5', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:22: Received Zigbee message from '0x60a423fffead6dc5', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:22: Received Zigbee message from '0x60a423fffead6dc5', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:23: Received Zigbee message from '0x60a423fffead6dc5', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:23: Received Zigbee message from '0x60a423fffead6dc5', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:23: Received Zigbee message from '0x60a423fffead6dc5', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:23: Received Zigbee message from '0x60a423fffead6dc5', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:23: Received Zigbee message from '0x60a423fffead6dc5', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:24: Received Zigbee message from '0x60a423fffead6dc5', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:24: Received Zigbee message from '0x60a423fffead6dc5', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-05-22 17:52:24: Received Zigbee message from '0x60a423fffead6dc5', type 'read', cluster 'genTime', data '["localTime"]' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-05-22 17:53:27: Successfully interviewed '0x60a423fffead6dc5', device has successfully been paired
Zigbee2MQTT:info  2021-05-22 17:53:27: Device '0x60a423fffead6dc5' is supported, identified as: Moes Smart light switch module (1 gang) (MS-104Z)
Zigbee2MQTT:info  2021-05-22 17:53:27: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Smart light switch module (1 gang)","exposes":[{"features":[{"access":7,"description":"On/off state of the switch","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"}],"type":"switch"},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"MS-104Z","supports_ota":false,"vendor":"Moes"},"friendly_name":"0x60a423fffead6dc5","ieee_address":"0x60a423fffead6dc5","status":"successful","supported":true},"type":"device_interview"}'
Zigbee2MQTT:info  2021-05-22 17:53:27: Configuring '0x60a423fffead6dc5'
Zigbee2MQTT:info  2021-05-22 17:53:27: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"Smart light switch module (1 gang)","friendly_name":"0x60a423fffead6dc5","model":"MS-104Z","supported":true,"vendor":"Moes"},"type":"pairing"}'
Zigbee2MQTT:error 2021-05-22 17:53:37: Failed to configure '0x60a423fffead6dc5', attempt 1 (Error: Bind 0x60a423fffead6dc5/1 genOnOff from '0x00124b001cce2755/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout._onTimeout (C:\Users\Dirk\Desktop\zigbee2mqtt\node_modules\zigbee-herdsman\dist\utils\waitress.js:37:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7))
```

When I try to toggle the switch from the Z2M UI, I get the following log entries.

```
Zigbee2MQTT:debug 2021-05-22 17:59:30: Received MQTT message on 'zigbee2mqtt/0x60a423fffead6dc5/set' with data '{"state":"ON"}'
Zigbee2MQTT:debug 2021-05-22 17:59:30: Publishing 'set' 'state' to '0x60a423fffead6dc5'
Zigbee2MQTT:error 2021-05-22 17:59:53: Publish 'set' 'state' to '0x60a423fffead6dc5' failed: 'Error: Command 0x60a423fffead6dc5/1 genOnOff.on({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 57415 - 1 - 3 - 6 - 11 after 10000ms)'
Zigbee2MQTT:debug 2021-05-22 17:59:53: Error: Command 0x60a423fffead6dc5/1 genOnOff.on({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 57415 - 1 - 3 - 6 - 11 after 10000ms)
    at Timeout._onTimeout (C:\Users\Dirk\Desktop\zigbee2mqtt\node_modules\zigbee-herdsman\dist\utils\waitress.js:37:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

## What did you expect to happen
Toggling the switch within Z2M should switch the Moes MS-104Z.

## How to reproduce it (minimal and precise)
1. Connect the Moes ZM-104Z to Z2M.
2. Check the output log, it reports the fail
3. Switch the physical module and check the log, it reports the switch
4. Switch from Z2M and check the log, it reports the fail

## Debug info
Zigbee2MQTT version: 1.18.3-dev commit: 792883c3
Adapter hardware: CC2531
Adapter firmware version: zStack12 (20201128)

## data/database.db entry of the device
```
{
    "id": 2,
    "type": "Router",
    "ieeeAddr": "0x60a423fffead6dc5",
    "nwkAddr": 13752,
    "manufId": 4098,
    "manufName": "_TZ3000_zmy1waw6",
    "powerSource": "Mains (single phase)",
    "modelId": "TS011F",
    "epList": [1],
    "endpoints": {
        "1": {
            "profId": 260,
            "epId": 1,
            "devId": 9,
            "inClusterList": [0, 4, 5, 6],
            "outClusterList": [25, 10],
            "clusters": {
                "genOnOff": {
                    "attributes": {
                        "onOff": 1,
                        "onTime": 0,
                        "offWaitTime": 0,
                        "tuyaBacklightMode": 1,
                        "moesStartUpOnOff": 0
                    }
                },
                "genBasic": {
                    "attributes": {
                        "modelId": "TS011F",
                        "manufacturerName": "_TZ3000_zmy1waw6",
                        "powerSource": 1,
                        "zclVersion": 3,
                        "appVersion": 65,
                        "stackVersion": 0
                    }
                }
            },
            "binds": [],
            "configuredReportings": [],
            "meta": {}
        }
    },
    "appVersion": 65,
    "stackVersion": 0,
    "zclVersion": 3,
    "interviewCompleted": true,
    "meta": {},
    "lastSeen": 1621698744576
}
```

**Comment by dvandonkelaar** [comment]
Apparently, my CC2351 (my testing coordinator) is not working correct. I paired the device with my CC2652RB (my production coordinator) and it all works out of the box. I think I need to check my CC2351 firmware.
