### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Endpoint name 'left' is given but no endpoints defined

### ISSUE THREAD

**Issue by choyrack** [Koenkk/zigbee2mqtt#7565]
After update to the last version zigbee2mqtt does not start.

```
pi@iot:/opt/zigbee2mqtt$ npm start

> zigbee2mqtt@1.18.3 start
> node index.js

Zigbee2MQTT:info  2021-05-22 22:13:31: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2021-05-22.22-13-28' filename: log.txt
Zigbee2MQTT:info  2021-05-22 22:13:31: Starting Zigbee2MQTT version 1.18.3 (commit #669489fe)
Zigbee2MQTT:info  2021-05-22 22:13:31: Starting zigbee-herdsman (0.13.92)
Zigbee2MQTT:info  2021-05-22 22:13:34: zigbee-herdsman started
Zigbee2MQTT:info  2021-05-22 22:13:34: Coordinator firmware version: '{"meta":{"maintrel":3,"majorrel":2,"minorrel":6,"product":0,"revision":20190608,"transportrev":2},"type":"zStack12"}'
Zigbee2MQTT:info  2021-05-22 22:13:34: Currently 8 devices are joined:
Zigbee2MQTT:info  2021-05-22 22:13:34: 1 (0x00158d0004XXXXXX): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
Zigbee2MQTT:info  2021-05-22 22:13:34: 2 (0x00158d000XXXXXXX): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
Zigbee2MQTT:info  2021-05-22 22:13:34: 3 (0x60a423fffXXXXXXX): QS-Zigbee-S05-LN - Lonsonho 1 gang switch module with neutral wire (Router)
Zigbee2MQTT:info  2021-05-22 22:13:34: 4 (0xbc33acfffXXXXXXX): TS0001 - TuYa 1 gang switch (Router)
Zigbee2MQTT:info  2021-05-22 22:13:34: 5 (0x5c0272fffXXXXXXX): TS0001 - TuYa 1 gang switch (Router)
Zigbee2MQTT:info  2021-05-22 22:13:34: 6 (0x5c0272fffXXXXXXX): TS0001 - TuYa 1 gang switch (Router)
Zigbee2MQTT:info  2021-05-22 22:13:34: 7 (0x00124b002XXXXXXX): SNZB-04 - SONOFF Contact sensor (EndDevice)
Zigbee2MQTT:info  2021-05-22 22:13:34: 8 (0x00124b0022XXXXXX): ZB-SW02 - eWeLink Smart light switch - 2 gang (Router)
Zigbee2MQTT:info  2021-05-22 22:13:34: Zigbee: disabling joining new devices.
Zigbee2MQTT:info  2021-05-22 22:13:34: Connecting to MQTT server at mqtt://localhost
Zigbee2MQTT:info  2021-05-22 22:13:34: Connected to MQTT server
Zigbee2MQTT:info  2021-05-22 22:13:34: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
Zigbee2MQTT:info  2021-05-22 22:13:34: MQTT publish: topic 'zigbee2mqtt/1', payload '{"battery":100,"humidity":45.82,"pressure":993.1,"temperature":22.62,"voltage":3005}'
Zigbee2MQTT:info  2021-05-22 22:13:34: MQTT publish: topic 'zigbee2mqtt/2', payload '{"battery":86,"humidity":55.32,"pressure":1000,"temperature":14.56,"voltage":2975}'
Zigbee2MQTT:info  2021-05-22 22:13:34: MQTT publish: topic 'zigbee2mqtt/3', payload '{"state":"OFF","state_left":"OFF"}'
Zigbee2MQTT:info  2021-05-22 22:13:34: MQTT publish: topic 'zigbee2mqtt/4', payload '{"state":"OFF"}'
Zigbee2MQTT:info  2021-05-22 22:13:34: MQTT publish: topic 'zigbee2mqtt/5', payload '{"state":"OFF"}'
Zigbee2MQTT:info  2021-05-22 22:13:34: MQTT publish: topic 'zigbee2mqtt/6', payload '{"state":"OFF"}'
Zigbee2MQTT:info  2021-05-22 22:13:34: MQTT publish: topic 'zigbee2mqtt/7', payload '{"battery_low":false,"contact":true,"tamper":false}'
Zigbee2MQTT:info  2021-05-22 22:13:34: MQTT publish: topic 'zigbee2mqtt/8', payload '{"state_left":"OFF","state_right":"OFF"}'
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

AssertionError [ERR_ASSERTION]: Endpoint name 'left' is given but no endpoints defined
    at Zigbee.resolveEntity (/opt/zigbee2mqtt/lib/zigbee.js:241:25)
    at Groups.onStateChange (/opt/zigbee2mqtt/lib/extension/groups.js:102:48)
    at EventBus.emit (node:events:369:20)
    at EventBus.emit (/opt/zigbee2mqtt/lib/eventBus.js:23:15)
    at State.set (/opt/zigbee2mqtt/lib/state.js:90:23)
    at Controller.publishEntityState (/opt/zigbee2mqtt/lib/controller.js:285:37)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.js:149:26)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async start (/opt/zigbee2mqtt/index.js:43:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
pi@iot:/opt/zigbee2mqtt$
```

Zigbee2MQTT version:  1.18.3 (commit #669489fe)
Adapter hardware: CC2531
Adapter firmware version: 20190608

**Comment by choyrack** [comment]
commit 01af249 is OK.
d3fd3bc not OK.
