### ISSUE TITLE
Please add support for: OWON ZigBee 3-Phase Clamp Meter

### ISSUE THREAD

**Issue by GordonP79** [Koenkk/zigbee2mqtt#7587]
I need assistance in adding support for a new device please:
OWON ZigBee 3-Phase Clamp Meter (80A/120A/200A/300A) PC321

## Information about the device + link
The device is sold under a number of "white labeled" names, as well as OWON itself:
https://www.owon-smart.com/three-phase-clamp-measuring-equipment-energy-power-clamp-pc321-2-product/

I see that 'ZiGate' supports a white labeled version from CASA.ia:
https://zigbee.blakadder.com/CASA_IA_CPC-321-80.html

Zigbee2MQTT Version: 1.18.3

## data/database.db entry of the device
{"id":2,"type":"Router","ieeeAddr":"0x3c6a2cfffed08215","nwkAddr":1060,"manufId":4412,"manufName":"OWON Te","powerSource":"Unknown","modelId":"PC321","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":13,"inCluster
List":[0,3,1794],"outClusterList":[3,10,25],"clusters":{"genBasic":{"attributes":{"modelId":"PC321","manufacturerName":"OWON Te","powerSource":0,"zclVersion":1,"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"201904
2"}},"seMetering":{"attributes":{"8192":0,"8193":140,"8194":170,"8448":0,"8449":149,"8450":563,"8451":711,"12288":2320,"12289":2319,"12290":2319,"12544":0,"12545":882,"12546":2535,"12547":3417,"16384":[0,34101],"16385":[0,14
366],"16386":[0,43668],"16640":[0,31],"16641":[0,14210],"16642":[0,54534],"16643":[0,68775],"16644":0,"16645":69,"16646":29,"currentSummDelivered":[0,92135],"instantaneousDemand":310,"status":0}}},"binds":[],"configuredRepor
tings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"2019042","zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1621885508438}

## Converter file entry:
{
	zigbeeModel: ['PC321'],
	model: 'PC321',
	description: 'PC321-TY Single/3-phase Power Clamp',
	supports: 'power measurement',
	vendor: 'OWON Te',
	fromZigbee: [fz.electrical_measurement_power],
	toZigbee: [],
	meta: {configureKey: 1},
	configure: async (device, coordinatorEndpoint) => {
		const endpoint = device.getEndpoint(1);
		await bind(endpoint, coordinatorEndpoint, ['haElectricalMeasurement']);
		await readEletricalMeasurementPowerConverterAttributes(endpoint);
		await configureReporting.rmsVoltage(endpoint);
		await configureReporting.rmsCurrent(endpoint);
		await configureReporting.activePower(endpoint);
	}, 
	exposes: [e.power(), e.energy()],
};

## Errors after starting ZigBee2MQTT :
Zigbee2MQTT:info  2021-05-24 22:11:36: Configuring 'EnergyMonitor'
Zigbee2MQTT:error 2021-05-24 22:11:36: Failed to configure 'EnergyMonitor', attempt 1 (ReferenceError: bind is not defined
    at Object.configure (/opt/zigbee2mqtt/lib/util/externally-loaded.js:20:3)
    at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.js:136:45)
    at Configure.onZigbeeStarted (/opt/zigbee2mqtt/lib/extension/configure.js:104:28)
    at Controller.callExtensionMethod (/opt/zigbee2mqtt/lib/controller.js:384:44))

**Comment by GordonP79** [comment]
Anyone? If andditional info is required please let me know.

**Comment by GordonP79** [comment]
Please can someone assist - more than willing to provide any additional information if required.
