### ISSUE TITLE
Moving my Z2M HA Addon from old to a new NUC - wont start ...

### ISSUE THREAD

**Issue by TheStigh** [Koenkk/zigbee2mqtt#7658]
Hi,

I've started migrating my HA from an old to a new NUC. Using the Addon version of Z2M. After restoring the backup on the new NUC, I can't get the Z2M to start. I did a clean Z2M install, after this I copied the entire /data folder from the old `/share/zigbee2mqtt` folder to the new proposed folder `/config/zigbee2mqtt` but Z2M just start up as default. It doesn't bother about the existing `configuration.yaml` or the `coordinator_backup.json`.

Using 1352-P2 adapter.

How can I resolve this?

**Comment by Koenkk** [comment]
Could you provide the herdsman debug log when starting after the recovery?

**Comment by TheStigh** [comment]
The 'open line' might be some data/log missing, hard to capture the entire log during startup :)

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[15:45:05] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[15:45:06] INFO: MQTT available, fetching server detail ...
[15:45:06] INFO: Previous config file found, checking backup
[15:45:06] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[15:45:06] WARNING: No devices.js file found in data path, starting with default devices.js
[15:45:06] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:45:06] INFO: Zigbee Herdsman debug logging enabled
[15:45:06] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.3 start /app
> node index.js
Zigbee2MQTT:debug 01-06-2021 15:45:07: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  01-06-2021 15:45:07: Logging to console and directory: '/config/zigbee2mqtt/log/2021-06-01.15-45-06' filename: log.txt
Zigbee2MQTT:debug 01-06-2021 15:45:07: Removing old log directory '/config/zigbee2mqtt/log/2021-06-01.15-33-09'
Zigbee2MQTT:info  01-06-2021 15:45:07: Starting Zigbee2MQTT version 1.18.3 (commit #1.18.3)
Zigbee2MQTT:info  01-06-2021 15:45:07: Starting zigbee-herdsman (0.13.92)
Zigbee2MQTT:debug 01-06-2021 15:45:07: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyACM0"}}'
2021-06-01T13:45:07.227Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2021-06-01T13:45:07.228Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[9,12,13,6,1,13,2,13,8,15,13,5,0,11,4,3],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/ttyACM0"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"concurrent":null,"delay":null}}'
2021-06-01T13:45:07.229Z zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /dev/ttyACM0 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
2021-06-01T13:45:07.237Z zigbee-herdsman:adapter:zStack:znp:log Serialport opened
2021-06-01T13:45:07.692Z zigbee-herdsman:adapter:zStack:znp:log Writing skip bootloader payload
2021-06-01T13:45:07.693Z zigbee-herdsman:adapter:zStack:unpi:writer --> buffer [239]

2021-06-01T13:45:08.712Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":96,"offset":0,"len":1,"value":{"type":"Buffer","data":[85]}}
2021-06-01T13:45:08.713Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,96,0,0,74]
2021-06-01T13:45:08.729Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,97,8,0,1,85,62]
2021-06-01T13:45:08.729Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,97,8,0,1,85,62]
2021-06-01T13:45:08.729Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 3 - 1 - 8 - [0,1,85] - 62
2021-06-01T13:45:08.730Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":1,"value":{"type":"Buffer","data":[85]}}
2021-06-01T13:45:08.730Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-01T13:45:08.731Z zigbee-herdsman:adapter:zStack:startZnp Item 'hasConfigured' is valid
2021-06-01T13:45:08.732Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":96,"offset":0,"len":1,"value":{"type":"Buffer","data":[85]}}
2021-06-01T13:45:08.732Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,96,0,0,74]
2021-06-01T13:45:08.749Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,97,8,0,1,85,62]
2021-06-01T13:45:08.749Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,97,8,0,1,85,62]
2021-06-01T13:45:08.749Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 3 - 1 - 8 - [0,1,85] - 62
2021-06-01T13:45:08.749Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":1,"value":{"type":"Buffer","data":[85]}}
2021-06-01T13:45:08.750Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-01T13:45:08.750Z zigbee-herdsman:adapter:zStack:startZnp Item 'hasConfigured' is valid
2021-06-01T13:45:08.751Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":132,"len":4,"offset":0,"value":{"type":"Buffer","data":[0,8,0,0]}}
2021-06-01T13:45:08.751Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,132,0,0,174]
2021-06-01T13:45:08.758Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,6,97,8,0,4,0,8,0,0,99]
2021-06-01T13:45:08.759Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,6,97,8,0,4,0,8,0,0,99]
2021-06-01T13:45:08.759Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 6 - 3 - 1 - 8 - [0,4,0,8,0,0] - 99
2021-06-01T13:45:08.759Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":4,"value":{"type":"Buffer","data":[0,8,0,0]}}
2021-06-01T13:45:08.759Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-01T13:45:08.760Z zigbee-herdsman:adapter:zStack:startZnp Item 'channelList' is valid
2021-06-01T13:45:08.760Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":99,"len":1,"offset":0,"value":{"type":"Buffer","data":[0]}}
2021-06-01T13:45:08.761Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,99,0,0,73]
2021-06-01T13:45:08.768Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,97,8,0,1,0,107]
2021-06-01T13:45:08.768Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,97,8,0,1,0,107]
2021-06-01T13:45:08.768Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 3 - 1 - 8 - [0,1,0] - 107
2021-06-01T13:45:08.769Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":1,"value":{"type":"Buffer","data":[0]}}
2021-06-01T13:45:08.769Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-01T13:45:08.769Z zigbee-herdsman:adapter:zStack:startZnp Item 'networkKeyDistribute' is valid
2021-06-01T13:45:08.770Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":98,"configid":98,"len":16,"offset":0,"value":{"type":"Buffer","data":[9,12,13,6,1,13,2,13,8,15,13,5,0,11,4,3]}}
2021-06-01T13:45:08.770Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,98,0,0,72]
2021-06-01T13:45:08.777Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,18,97,8,0,16,9,12]
2021-06-01T13:45:08.778Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,18,97,8,0,16,9,12]
2021-06-01T13:45:08.778Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [13,6,1,13,2,13,8,15,13,5,0,11,4,3,101]
2021-06-01T13:45:08.779Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,18,97,8,0,16,9,12,13,6,1,13,2,13,8,15,13,5,0,11,4,3,101]
2021-06-01T13:45:08.779Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 18 - 3 - 1 - 8 - [0,16,9,12,13,6,1,13,2,13,8,15,13,5,0,11,4,3] - 101
2021-06-01T13:45:08.779Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":16,"value":{"type":"Buffer","data":[9,12,13,6,1,13,2,13,8,15,13,5,0,11,4,3]}}
2021-06-01T13:45:08.779Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-01T13:45:08.780Z zigbee-herdsman:adapter:zStack:startZnp Item 'networkKey' is valid
2021-06-01T13:45:08.780Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":131,"len":2,"offset":0,"value":{"type":"Buffer","data":[98,26]}}
2021-06-01T13:45:08.781Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,131,0,0,169]
2021-06-01T13:45:08.788Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,4,97,8,0,2,98,26,23]
2021-06-01T13:45:08.788Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,4,97,8,0,2,98,26,23]
2021-06-01T13:45:08.788Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 4 - 3 - 1 - 8 - [0,2,98,26] - 23
2021-06-01T13:45:08.788Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":2,"value":{"type":"Buffer","data":[98,26]}}
2021-06-01T13:45:08.789Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-01T13:45:08.789Z zigbee-herdsman:adapter:zStack:startZnp Item 'panID' is valid
2021-06-01T13:45:08.790Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":45,"len":8,"offset":0,"value":{"type":"Buffer","data":[221,221,221,221,221,221,221,221]}}
2021-06-01T13:45:08.790Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,45,0,0,7]
2021-06-01T13:45:08.797Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,10,97,8,0,8,221,221]
2021-06-01T13:45:08.797Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,10,97,8,0,8,221,221]
2021-06-01T13:45:08.798Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [221,221,221,221,221,221,107]
2021-06-01T13:45:08.798Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,10,97,8,0,8,221,221,221,221,221,221,221,221,107]
2021-06-01T13:45:08.798Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 10 - 3 - 1 - 8 - [0,8,221,221,221,221,221,221,221,221] - 107
2021-06-01T13:45:08.799Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":8,"value":{"type":"Buffer","data":[221,221,221,221,221,221,221,221]}}
2021-06-01T13:45:08.799Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-01T13:45:08.799Z zigbee-herdsman:adapter:zStack:startZnp Item 'extendedPanID' is valid
2021-06-01T13:45:08.800Z zigbee-herdsman:adapter:zStack:znp:SREQ --> UTIL - getDeviceInfo - {}
2021-06-01T13:45:08.800Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,39,0,39]
2021-06-01T13:45:08.810Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,14,103,0,0,11,191,161]
2021-06-01T13:45:08.810Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,14,103,0,0,11,191,161]
2021-06-01T13:45:08.811Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [28,0,75,18,0,254,255,7,0,0,63]
2021-06-01T13:45:08.811Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,14,103,0,0,11,191,161,28,0,75,18,0,254,255,7,0,0,63]
2021-06-01T13:45:08.811Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 14 - 3 - 7 - 0 - [0,11,191,161,28,0,75,18,0,254,255,7,0,0] - 63
2021-06-01T13:45:08.813Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- UTIL - getDeviceInfo - {"status":0,"ieeeaddr":"0x00124b001ca1bf0b","shortaddr":65534,"devicetype":7,"devicestate":0,"numassocdevices":0,"assocdeviceslist":[]}
2021-06-01T13:45:08.813Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-01T13:45:08.813Z zigbee-herdsman:adapter:zStack:startZnp Start ZNP as coordinator...
2021-06-01T13:45:08.814Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - startupFromApp - {"startdelay":100}
2021-06-01T13:45:08.814Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,2,37,64,100,0,3]
2021-06-01T13:45:11.348Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,64,0,36,254,3]
2021-06-01T13:45:11.348Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,64,0,36,254,3]
2021-06-01T13:45:11.348Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 64 - [0] - 36
2021-06-01T13:45:11.348Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - startupFromApp - {"status":0}
2021-06-01T13:45:11.349Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3]
2021-06-01T13:45:11.350Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [79,128,1,2,4,203]
2021-06-01T13:45:11.350Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,79,128,1,2,4,203]
2021-06-01T13:45:11.350Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 15 - 128 - [1,2,4] - 203
2021-06-01T13:45:11.350Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- APP_CNF - bdbComissioningNotifcation - {"status":1}
2021-06-01T13:45:11.350Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-01T13:45:11.616Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,69,192,8,140]
2021-06-01T13:45:11.616Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,69,192,8,140]
2021-06-01T13:45:11.616Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 2 - 5 - 192 - [8] - 140
2021-06-01T13:45:11.617Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - stateChangeInd - {"state":8}
2021-06-01T13:45:11.617Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-01T13:45:12.180Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,69,192,0,132,254,3]
2021-06-01T13:45:12.180Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,69,192,0,132,254,3]
2021-06-01T13:45:12.181Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 2 - 5 - 192 - [0] - 132
2021-06-01T13:45:12.181Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - stateChangeInd - {"state":0}
2021-06-01T13:45:12.181Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3]
2021-06-01T13:45:12.182Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [79,128,8,2,0,198,254,3,79,128,8,2,0,198]
2021-06-01T13:45:12.182Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,79,128,8,2,0,198,254,3,79,128,8,2,0,198]
2021-06-01T13:45:12.182Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 15 - 128 - [8,2,0] - 198
2021-06-01T13:45:12.183Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- APP_CNF - bdbComissioningNotifcation - {"status":8}
2021-06-01T13:45:12.183Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,79,128,8,2,0,198]
2021-06-01T13:45:12.183Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 15 - 128 - [8,2,0] - 198
2021-06-01T13:45:12.183Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- APP_CNF - bdbComissioningNotifcation - {"status":8}
2021-06-01T13:45:12.183Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
Zigbee2MQTT:error 01-06-2021 15:46:08: Error while starting zigbee-herdsman
Zigbee2MQTT:error 01-06-2021 15:46:08: Failed to start zigbee
Zigbee2MQTT:error 01-06-2021 15:46:08: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 01-06-2021 15:46:08: Exiting...
Zigbee2MQTT:error 01-06-2021 15:46:08: Error: AREQ - ZDO - stateChangeInd after 60000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:37:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.3 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-01T13_46_08_895Z-debug.log
[15:46:09] INFO: Zigbee Herdsman debug logging enabled
[15:46:09] INFO: Handing over control to Zigbee2mqtt Core ...
```

**Comment by TheStigh** [comment]
All good! Got it running again...!

Stopped Z2M
Disconnected ext antenna from 1352-P2
Moved backup back to new folder
Started Z2M
... failed for some time, after a few minutes it suddenly got 'contanct'
Stopped Z2M
Re-Connected antenna

Now devices are coming back to life!
