### ISSUE TITLE
I cannot switch on my Gledopto GU10 Bulb RGB+CCT anymore

### ISSUE THREAD

**Issue by rolfberkenbosch** [Koenkk/zigbee2mqtt#7717]
## What happened
I have upgraded the zigbee2mqtt to te latest version 1.19.1

## What did you expect to happen
I have switch on/off my lamps, it has worked before.

## How to reproduce it (minimal and precise)
I'm trying to switch on a Zigbee 5W GU10 Bulb RGB+CCT (GL-S-007Z) by Gledopto

## Debug info
Zigbee2MQTT version:
Adapter hardware: CC2530
Adapter firmware version: long time ago ;)

## Error message:
```
debug 2021-06-07 08:51:51: Received MQTT message on 'zigbee2mqtt/0x00124b001d406a62/set' with data '{"state": "OFF"}'
debug 2021-06-07 08:51:51: Publishing 'set' 'state' to '0x00124b001d406a62'
info  2021-06-07 08:51:54: MQTT publish: topic 'zigbee2mqtt/livingroom_motion', payload '{"battery":80,"illuminance":125,"illuminance_lux":125,"last_seen":"2021-06-07T08:50:24+02:00","linkquality":28,"occupancy":false,"temperature":30,"voltage":2965}'
info  2021-06-07 08:52:01: MQTT publish: topic 'zigbee2mqtt/hallway_motion', payload '{"battery":100,"illuminance":137,"illuminance_lux":137,"last_seen":"2021-06-07T08:50:31+02:00","linkquality":26,"occupancy":false,"temperature":23,"voltage":3035}'
debug 2021-06-07 08:52:06: Received MQTT message on 'zigbee2mqtt/0x00124b001d406a62/set' with data '{"state": "OFF"}'
debug 2021-06-07 08:52:06: Publishing 'set' 'state' to '0x00124b001d406a62'
error 2021-06-07 08:52:08: Publish 'set' 'state' to '0x00124b001d406a62' failed: 'Error: Command 0x00124b001d406a62/11 genOnOff.off({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> AF - dataRequest - {"dstaddr":2835,"destendpoint":11,"srcendpoint":1,"clusterid":6,"transid":5,"options":0,"radius":30,"len":3,"data":{"type":"Buffer","data":[1,3,0]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)'))'
debug 2021-06-07 08:52:08: Error: Command 0x00124b001d406a62/11 genOnOff.off({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SREQ '--> AF - dataRequest - {"dstaddr":2835,"destendpoint":11,"srcendpoint":1,"clusterid":6,"transid":5,"options":0,"radius":30,"len":3,"data":{"type":"Buffer","data":[1,3,0]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)'))
    at Znp.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:291:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:24:58)
info  2021-06-07 08:52:08: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x00124b001d406a62' failed: 'Error: Command 0x00124b001d406a62/11 genOnOff.off({}, {\"sendWhenActive\":false,\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (SREQ '--> AF - dataRequest - {\"dstaddr\":2835,\"destendpoint\":11,\"srcendpoint\":1,\"clusterid\":6,\"transid\":5,\"options\":0,\"radius\":30,\"len\":3,\"data\":{\"type\":\"Buffer\",\"data\":[1,3,0]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)'))'","meta":{"friendly_name":"0x00124b001d406a62"},"type":"zigbee_publish_error"}'
```

**Comment by Koenkk** [comment]
`(0x10: MEM_ERROR)` indicated your firmware on the CC2530 is crashing (unfortunately not uncommon). 

- Try switching to the source routing fw instead (since that provides more stability): https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/source_routing
- If you keep having these errors you need to upgrade to a more powerful coordinator: https://www.zigbee2mqtt.io/getting_started/what_do_i_need.html#supported-zigbee-adapter
