### ISSUE TITLE
Jetlun Appliance Module - RD75615

### ISSUE THREAD

**Issue by CullenJWebb** [Koenkk/zigbee2mqtt#7757]
I'm trying to follow the steps for adding support for a  new device but I'm getting stuck on "Step 1". My devices don't actually pair / interview with Zigbee2MQTT in the first place.

I get a failed to interview error: 
`Zigbee2MQTT:error 2021-06-11 11:59:33: Failed to interview '0xc8d2c100000000f6', device has not successfully been paired`

Brand: Jetlun
Model: RD75615
FCC ID: X5QRD75613
Manual: https://fccid.io/X5QRD75613/User-Manual/Users-Manual-1271251

Screenshots of the attempted interview / errors attached.

Should I try to move on to step 2, creating an external converter file, even though it doesn't interview?

I also tried pairing the device with ZHA and it failed to interview with that as well.
![unsupported device log](https://user-images.githubusercontent.com/2952787/121717283-01031980-caaf-11eb-9227-73eddfdd6f5a.png)
![unsupported device details](https://user-images.githubusercontent.com/2952787/121717284-019bb000-caaf-11eb-9bec-ad7438cf3360.png)
![unsupported device](https://user-images.githubusercontent.com/2952787/121717288-019bb000-caaf-11eb-8088-e81f3b7569f0.png)

**Comment by Koenkk** [comment]
Can you provide the herdsman debug log when pairing this device?

See https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging on how to enable the herdsman debug logging. Note that this is only logged to STDOUT and not to log files.

**Comment by CullenJWebb** [comment]
Thanks so much for your time. 

Here's the debug: 

2021-06-15T02:00:45.338Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2021-06-15T02:00:45.338Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2021-06-15T02:00:45.339Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2021-06-15T02:00:45.339Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:00:45.819Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,12,69,202,101,8,164,1,0,0,0,193,210,200,0,0,144]
2021-06-15T02:00:45.819Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,12,69,202,101,8,164,1,0,0,0,193,210,200,0,0,144]
2021-06-15T02:00:45.820Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 12 - 2 - 5 - 202 - [101,8,164,1,0,0,0,193,210,200,0,0] - 144
2021-06-15T02:00:45.820Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - tcDeviceInd - {"nwkaddr":2149,"extaddr":"0xc8d2c100000001a4","parentaddr":0}
2021-06-15T02:00:45.820Z zigbee-herdsman:controller:log Device '0xc8d2c100000001a4' joined
2021-06-15T02:00:45.820Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:00:45.821Z zigbee-herdsman:controller:log Device '0xc8d2c100000001a4' accepted by handler
2021-06-15T02:00:45.821Z zigbee-herdsman:controller:log Not interviewing '0xc8d2c100000001a4', completed 'false', in progress 'true'
2021-06-15T02:00:51.406Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,12,69,202,101,8,164,1,0,0,0,193,210,200,0,0,144]
2021-06-15T02:00:51.406Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,12,69,202,101,8,164,1,0,0,0,193,210,200,0,0,144]
2021-06-15T02:00:51.406Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 12 - 2 - 5 - 202 - [101,8,164,1,0,0,0,193,210,200,0,0] - 144
2021-06-15T02:00:51.407Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - tcDeviceInd - {"nwkaddr":2149,"extaddr":"0xc8d2c100000001a4","parentaddr":0}
2021-06-15T02:00:51.407Z zigbee-herdsman:controller:log Device '0xc8d2c100000001a4' joined
2021-06-15T02:00:51.407Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:00:51.407Z zigbee-herdsman:controller:log Device '0xc8d2c100000001a4' accepted by handler
2021-06-15T02:00:51.407Z zigbee-herdsman:controller:log Not interviewing '0xc8d2c100000001a4', completed 'false', in progress 'true'
2021-06-15T02:00:55.341Z zigbee-herdsman:adapter:zStack:adapter Node descriptor request for '2149' failed (Error: AREQ - ZDO - nodeDescRsp after 10000ms), retry
2021-06-15T02:00:55.342Z zigbee-herdsman:adapter:zStack:adapter Discovering route to 2149
2021-06-15T02:00:55.342Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - extRouteDisc - {"dstAddr":2149,"options":0,"radius":30}
2021-06-15T02:00:55.342Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,69,101,8,0,30,23]
2021-06-15T02:00:55.352Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,69,0,33]
2021-06-15T02:00:55.353Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,69,0,33]
2021-06-15T02:00:55.354Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 69 - [0] - 33
2021-06-15T02:00:55.354Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - extRouteDisc - {"status":0}
2021-06-15T02:00:55.355Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:00:55.683Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,12,69,202,101,8,164,1,0,0,0,193,210,200,0,0,144]
2021-06-15T02:00:55.683Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,12,69,202,101,8,164,1,0,0,0,193,210,200,0,0,144]
2021-06-15T02:00:55.684Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 12 - 2 - 5 - 202 - [101,8,164,1,0,0,0,193,210,200,0,0] - 144
2021-06-15T02:00:55.684Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - tcDeviceInd - {"nwkaddr":2149,"extaddr":"0xc8d2c100000001a4","parentaddr":0}
2021-06-15T02:00:55.684Z zigbee-herdsman:controller:log Device '0xc8d2c100000001a4' joined
2021-06-15T02:00:55.684Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:00:55.685Z zigbee-herdsman:controller:log Device '0xc8d2c100000001a4' accepted by handler
2021-06-15T02:00:55.685Z zigbee-herdsman:controller:log Not interviewing '0xc8d2c100000001a4', completed 'false', in progress 'true'
2021-06-15T02:00:58.357Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":2149,"nwkaddrofinterest":2149}
2021-06-15T02:00:58.358Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,101,8,101,8,35]
2021-06-15T02:00:58.368Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2021-06-15T02:00:58.368Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2021-06-15T02:00:58.369Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2021-06-15T02:00:58.369Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2021-06-15T02:00:58.370Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:01:01.239Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,12,69,202,101,8,164,1,0,0,0,193,210,200,0,0,144]
2021-06-15T02:01:01.240Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,12,69,202,101,8,164,1,0,0,0,193,210,200,0,0,144]
2021-06-15T02:01:01.240Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 12 - 2 - 5 - 202 - [101,8,164,1,0,0,0,193,210,200,0,0] - 144
2021-06-15T02:01:01.241Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - tcDeviceInd - {"nwkaddr":2149,"extaddr":"0xc8d2c100000001a4","parentaddr":0}
2021-06-15T02:01:01.241Z zigbee-herdsman:controller:log Device '0xc8d2c100000001a4' joined
2021-06-15T02:01:01.242Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:01:01.242Z zigbee-herdsman:controller:log Device '0xc8d2c100000001a4' accepted by handler
2021-06-15T02:01:01.242Z zigbee-herdsman:controller:log Not interviewing '0xc8d2c100000001a4', completed 'false', in progress 'true'
2021-06-15T02:01:05.519Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,12,69,202,101,8,164,1,0,0,0,193,210,200,0,0,144]
2021-06-15T02:01:05.519Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,12,69,202,101,8,164,1,0,0,0,193,210,200,0,0,144]
2021-06-15T02:01:05.519Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 12 - 2 - 5 - 202 - [101,8,164,1,0,0,0,193,210,200,0,0] - 144
2021-06-15T02:01:05.519Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - tcDeviceInd - {"nwkaddr":2149,"extaddr":"0xc8d2c100000001a4","parentaddr":0}
2021-06-15T02:01:05.520Z zigbee-herdsman:controller:log Device '0xc8d2c100000001a4' joined
2021-06-15T02:01:05.520Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:01:05.520Z zigbee-herdsman:controller:log Device '0xc8d2c100000001a4' accepted by handler
2021-06-15T02:01:05.520Z zigbee-herdsman:controller:log Not interviewing '0xc8d2c100000001a4', completed 'false', in progress 'true'
2021-06-15T02:01:08.371Z zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0xc8d2c100000001a4', attempt 2
2021-06-15T02:01:08.371Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":2149,"nwkaddrofinterest":2149}
2021-06-15T02:01:08.372Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,101,8,101,8,35]
2021-06-15T02:01:08.382Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2021-06-15T02:01:08.382Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2021-06-15T02:01:08.382Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2021-06-15T02:01:08.382Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2021-06-15T02:01:08.382Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:01:11.086Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,12,69,202,101,8,164,1,0,0,0,193,210,200,0,0,144]
2021-06-15T02:01:11.086Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,12,69,202,101,8,164,1,0,0,0,193,210,200,0,0,144]
2021-06-15T02:01:11.086Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 12 - 2 - 5 - 202 - [101,8,164,1,0,0,0,193,210,200,0,0] - 144
2021-06-15T02:01:11.086Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - tcDeviceInd - {"nwkaddr":2149,"extaddr":"0xc8d2c100000001a4","parentaddr":0}
2021-06-15T02:01:11.086Z zigbee-herdsman:controller:log Device '0xc8d2c100000001a4' joined
2021-06-15T02:01:11.087Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:01:11.087Z zigbee-herdsman:controller:log Device '0xc8d2c100000001a4' accepted by handler
2021-06-15T02:01:11.087Z zigbee-herdsman:controller:log Not interviewing '0xc8d2c100000001a4', completed 'false', in progress 'true'
2021-06-15T02:01:18.383Z zigbee-herdsman:adapter:zStack:adapter Node descriptor request for '2149' failed (Error: AREQ - ZDO - nodeDescRsp after 10000ms), retry
2021-06-15T02:01:18.383Z zigbee-herdsman:adapter:zStack:adapter Discovering route to 2149
2021-06-15T02:01:18.383Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - extRouteDisc - {"dstAddr":2149,"options":0,"radius":30}
2021-06-15T02:01:18.384Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,69,101,8,0,30,23]
2021-06-15T02:01:18.394Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,69,0,33]
2021-06-15T02:01:18.394Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,69,0,33]
2021-06-15T02:01:18.394Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 69 - [0] - 33
2021-06-15T02:01:18.394Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - extRouteDisc - {"status":0}
2021-06-15T02:01:18.394Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:01:21.394Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":2149,"nwkaddrofinterest":2149}
2021-06-15T02:01:21.394Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,101,8,101,8,35]
2021-06-15T02:01:21.404Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2021-06-15T02:01:21.404Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2021-06-15T02:01:21.404Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2021-06-15T02:01:21.404Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2021-06-15T02:01:21.404Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:01:31.404Z zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0xc8d2c100000001a4', attempt 3
2021-06-15T02:01:31.404Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":2149,"nwkaddrofinterest":2149}
2021-06-15T02:01:31.405Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,101,8,101,8,35]
2021-06-15T02:01:31.419Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2021-06-15T02:01:31.419Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2021-06-15T02:01:31.420Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2021-06-15T02:01:31.420Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2021-06-15T02:01:31.420Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:01:41.420Z zigbee-herdsman:adapter:zStack:adapter Node descriptor request for '2149' failed (Error: AREQ - ZDO - nodeDescRsp after 10000ms), retry
2021-06-15T02:01:41.420Z zigbee-herdsman:adapter:zStack:adapter Discovering route to 2149
2021-06-15T02:01:41.421Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - extRouteDisc - {"dstAddr":2149,"options":0,"radius":30}
2021-06-15T02:01:41.422Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,69,101,8,0,30,23]
2021-06-15T02:01:41.431Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,69,0,33]
2021-06-15T02:01:41.432Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,69,0,33]
2021-06-15T02:01:41.432Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 69 - [0] - 33
2021-06-15T02:01:41.432Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - extRouteDisc - {"status":0}
2021-06-15T02:01:41.432Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:01:44.434Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":2149,"nwkaddrofinterest":2149}
2021-06-15T02:01:44.437Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,101,8,101,8,35]
2021-06-15T02:01:44.444Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2021-06-15T02:01:44.444Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2021-06-15T02:01:44.444Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2021-06-15T02:01:44.444Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2021-06-15T02:01:44.444Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:01:54.445Z zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0xc8d2c100000001a4', attempt 4
2021-06-15T02:01:54.445Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":2149,"nwkaddrofinterest":2149}
2021-06-15T02:01:54.446Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,101,8,101,8,35]
2021-06-15T02:01:54.459Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2021-06-15T02:01:54.460Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2021-06-15T02:01:54.460Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2021-06-15T02:01:54.460Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2021-06-15T02:01:54.460Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:02:04.461Z zigbee-herdsman:adapter:zStack:adapter Node descriptor request for '2149' failed (Error: AREQ - ZDO - nodeDescRsp after 10000ms), retry
2021-06-15T02:02:04.461Z zigbee-herdsman:adapter:zStack:adapter Discovering route to 2149
2021-06-15T02:02:04.461Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - extRouteDisc - {"dstAddr":2149,"options":0,"radius":30}
2021-06-15T02:02:04.461Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,69,101,8,0,30,23]
2021-06-15T02:02:04.471Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,69,0,33]
2021-06-15T02:02:04.472Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,69,0,33]
2021-06-15T02:02:04.472Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 69 - [0] - 33
2021-06-15T02:02:04.472Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - extRouteDisc - {"status":0}
2021-06-15T02:02:04.472Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:02:07.474Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":2149,"nwkaddrofinterest":2149}
2021-06-15T02:02:07.474Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,101,8,101,8,35]
2021-06-15T02:02:07.482Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2021-06-15T02:02:07.482Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2021-06-15T02:02:07.482Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2021-06-15T02:02:07.482Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2021-06-15T02:02:07.483Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:02:17.484Z zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0xc8d2c100000001a4', attempt 5
2021-06-15T02:02:17.484Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":2149,"nwkaddrofinterest":2149}
2021-06-15T02:02:17.485Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,101,8,101,8,35]
2021-06-15T02:02:17.498Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2021-06-15T02:02:17.499Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2021-06-15T02:02:17.499Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2021-06-15T02:02:17.499Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2021-06-15T02:02:17.499Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:02:27.500Z zigbee-herdsman:adapter:zStack:adapter Node descriptor request for '2149' failed (Error: AREQ - ZDO - nodeDescRsp after 10000ms), retry
2021-06-15T02:02:27.500Z zigbee-herdsman:adapter:zStack:adapter Discovering route to 2149
2021-06-15T02:02:27.500Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - extRouteDisc - {"dstAddr":2149,"options":0,"radius":30}
2021-06-15T02:02:27.500Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,69,101,8,0,30,23]
2021-06-15T02:02:27.511Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,69,0,33]
2021-06-15T02:02:27.511Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,69,0,33]
2021-06-15T02:02:27.511Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 69 - [0] - 33
2021-06-15T02:02:27.511Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - extRouteDisc - {"status":0}
2021-06-15T02:02:27.511Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:02:30.512Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - nodeDescReq - {"dstaddr":2149,"nwkaddrofinterest":2149}
2021-06-15T02:02:30.513Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,2,101,8,101,8,35]
2021-06-15T02:02:30.520Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,2,0,102]
2021-06-15T02:02:30.520Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,2,0,102]
2021-06-15T02:02:30.520Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 2 - [0] - 102
2021-06-15T02:02:30.520Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - nodeDescReq - {"status":0}
2021-06-15T02:02:30.520Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-06-15T02:02:40.521Z zigbee-herdsman:controller:device:log Interview - node descriptor request failed for '0xc8d2c100000001a4', attempt 6
2021-06-15T02:02:40.522Z zigbee-herdsman:controller:device:log Interview - failed for device '0xc8d2c100000001a4' with error 'Error: Interview failed because can not get node descriptor ('0xc8d2c100000001a4')
    at Device.<anonymous> (/app/node_modules/zigbee-herdsman/dist/controller/model/device.js:358:23)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/controller/model/device.js:25:65)'
2021-06-15T02:02:40.523Z zigbee-herdsman:controller:error Interview failed for '0xc8d2c100000001a4 with error 'Error: Interview failed because can not get node descriptor ('0xc8d2c100000001a4')'
Zigbee2MQTT:error 2021-06-14 22:02:40: Failed to interview '0xc8d2c100000001a4', device has not successfully been paired

**Comment by Koenkk** [comment]
The node descriptor is the first request done, as can be seen in the log the device does not respond at all, 2 options:
- Try pairing the device closer to the coordinator, also make sure to keep it awake when pairing by pressing a button on it.
- If that doesn't help, sniff the traffic when pairing it with the original gateway + z2m and compare to figure out the difference: https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

**Comment by CullenJWebb** [comment]
The first suggestion (Being closer and keeping it awake) didn't make a difference, and I don't want to re-flash my CC2531 and lose my current Zigbee functionality while I debug, so I'll need to put this on the back burner until I can get my hands on a spare CC2531.

Thanks again for your time looking at this for me.
