### ISSUE TITLE
 YSR-MINI-01_rgbcct does not support color_temp_startup

### ISSUE THREAD

**Issue by davidstosik** [Koenkk/zigbee2mqtt#7848]
## What happened

I just bought a [Tuya Zigbee Smart RGBCCT LED Strip Lights](https://www.aliexpress.com/item/1005002658889767.html) and paired it to Zigbee2MQTT.

I had no problems pairing, and the basic controls seem to work well (on/off, brightness, color, white temperature). However, it looks like the profile is not a perfect match, as `color_temp_startup` does not seem to be supported.

<details><summary>Here are the logs on pairing.</summary>

```
Zigbee2MQTT:debug 2021-06-22 11:56:41: Received MQTT message on 'zigbee2mqtt/bridge/request/permit_join' with data '{"device":null,"time":254,"transaction":"o7fqj-1","value":true}'
Zigbee2MQTT:info  2021-06-22 11:56:41: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2021-06-22 11:56:41: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"time":254,"value":true},"status":"ok","transaction":"o7fqj-1"}'
Zigbee2MQTT:info  2021-06-22 11:56:44: Device '3D printer LEDs' joined
Zigbee2MQTT:info  2021-06-22 11:56:44: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"3D printer LEDs","ieee_address":"0x00124b0022ed56a0"},"type":"device_joined"}'
Zigbee2MQTT:info  2021-06-22 11:56:44: Starting interview of '3D printer LEDs'
Zigbee2MQTT:info  2021-06-22 11:56:44: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"3D printer LEDs","ieee_address":"0x00124b0022ed56a0","status":"started"},"type":"device_interview"}'
Zigbee2MQTT:info  2021-06-22 11:56:44: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"3D printer LEDs"},"type":"device_connected"}'
Zigbee2MQTT:info  2021-06-22 11:56:44: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"3D printer LEDs"},"type":"pairing"}'
Zigbee2MQTT:debug 2021-06-22 11:56:44: Device '3D printer LEDs' announced itself
Zigbee2MQTT:info  2021-06-22 11:56:45: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"3D printer LEDs","ieee_address":"0x00124b0022ed56a0"},"type":"device_announce"}'
Zigbee2MQTT:info  2021-06-22 11:56:45: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"3D printer LEDs"},"type":"device_announced"}'
Zigbee2MQTT:debug 2021-06-22 11:56:45: Device '3D printer LEDs' announced itself
Zigbee2MQTT:info  2021-06-22 11:56:45: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"3D printer LEDs","ieee_address":"0x00124b0022ed56a0"},"type":"device_announce"}'
Zigbee2MQTT:info  2021-06-22 11:56:45: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"3D printer LEDs"},"type":"device_announced"}'
Zigbee2MQTT:debug 2021-06-22 11:56:46: Received Zigbee message from '3D printer LEDs', type 'readResponse', cluster 'genBasic', data '{"modelId":"ZB-CL01"}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-06-22 11:56:46: Skipping message, definition is undefined and still interviewing
Zigbee2MQTT:debug 2021-06-22 11:56:46: Received Zigbee message from '3D printer LEDs', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"YSRSAI"}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-06-22 11:56:46: Received Zigbee message from '3D printer LEDs', type 'readResponse', cluster 'genBasic', data '{"powerSource":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-06-22 11:56:46: Received Zigbee message from '3D printer LEDs', type 'readResponse', cluster 'genBasic', data '{"zclVersion":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-06-22 11:56:46: Received Zigbee message from '3D printer LEDs', type 'readResponse', cluster 'genBasic', data '{"appVersion":7}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-06-22 11:56:46: Received Zigbee message from '3D printer LEDs', type 'readResponse', cluster 'genBasic', data '{"stackVersion":2}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-06-22 11:56:46: Received Zigbee message from '3D printer LEDs', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-06-22 11:56:46: Received Zigbee message from '3D printer LEDs', type 'readResponse', cluster 'genBasic', data '{"dateCode":"20200914"}' from endpoint 1 with groupID 0
Zigbee2MQTT:debug 2021-06-22 11:56:46: Received Zigbee message from '3D printer LEDs', type 'readResponse', cluster 'genBasic', data '{"swBuildId":"1.0.7"}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-06-22 11:56:46: Successfully interviewed '3D printer LEDs', device has successfully been paired
Zigbee2MQTT:info  2021-06-22 11:56:46: Device '3D printer LEDs' is supported, identified as: YSRSAI Zigbee LED controller (RGB+CCT) (YSR-MINI-01_rgbcct)
Zigbee2MQTT:info  2021-06-22 11:56:46: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Zigbee LED controller (RGB+CCT)","exposes":[{"features":[{"access":7,"description":"On/off state of this light","name":"state","property":"state","type":"binary","value_off":"OFF","value_on":"ON","value_toggle":"TOGGLE"},{"access":7,"description":"Brightness of this light","name":"brightness","property":"brightness","type":"numeric","value_max":254,"value_min":0},{"access":7,"description":"Color temperature of this light","name":"color_temp","presets":[{"description":"Coolest temperature supported","name":"coolest","value":150},{"description":"Cool temperature (250 mireds / 4000 Kelvin)","name":"cool","value":250},{"description":"Neutral temperature (370 mireds / 2700 Kelvin)","name":"neutral","value":370},{"description":"Warm temperature (454 mireds / 2200 Kelvin)","name":"warm","value":454},{"description":"Warmest temperature supported","name":"warmest","value":500}],"property":"color_temp","type":"numeric","unit":"mired","value_max":500,"value_min":150},{"access":7,"description":"Color temperature after cold power on of this light","name":"color_temp_startup","presets":[{"description":"Coolest temperature supported","name":"coolest","value":150},{"description":"Cool temperature (250 mireds / 4000 Kelvin)","name":"cool","value":250},{"description":"Neutral temperature (370 mireds / 2700 Kelvin)","name":"neutral","value":370},{"description":"Warm temperature (454 mireds / 2200 Kelvin)","name":"warm","value":454},{"description":"Warmest temperature supported","name":"warmest","value":500},{"description":"Restore previous color_temp on cold power on","name":"previous","value":65535}],"property":"color_temp_startup","type":"numeric","unit":"mired","value_max":500,"value_min":150},{"description":"Color of this light in the CIE 1931 color space (x/y)","features":[{"access":7,"name":"x","property":"x","type":"numeric"},{"access":7,"name":"y","property":"y","type":"numeric"}],"name":"color_xy","property":"color","type":"composite"}],"type":"light"},{"access":2,"description":"Triggers an effect on the light (e.g. make light blink for a few seconds)","name":"effect","property":"effect","type":"enum","values":["blink","breathe","okay","channel_change","finish_effect","stop_effect"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"YSR-MINI-01_rgbcct","supports_ota":false,"vendor":"YSRSAI"},"friendly_name":"3D printer LEDs","ieee_address":"0x00124b0022ed56a0","status":"successful","supported":true},"type":"device_interview"}'
Zigbee2MQTT:info  2021-06-22 11:56:46: Configuring '3D printer LEDs'
Zigbee2MQTT:info  2021-06-22 11:56:46: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"description":"Zigbee LED controller (RGB+CCT)","friendly_name":"3D printer LEDs","model":"YSR-MINI-01_rgbcct","supported":true,"vendor":"YSRSAI"},"type":"pairing"}'
Zigbee2MQTT:debug 2021-06-22 11:56:46: Received Zigbee message from '3D printer LEDs', type 'readResponse', cluster 'lightingColorCtrl', data '{"colorCapabilities":31}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-06-22 11:56:46: MQTT publish: topic 'zigbee2mqtt/3D printer LEDs', payload '{"color_mode":"xy","linkquality":70,"state":null}'
Zigbee2MQTT:debug 2021-06-22 11:56:47: Received Zigbee message from '3D printer LEDs', type 'readResponse', cluster 'lightingColorCtrl', data '{"colorTempPhysicalMax":370,"colorTempPhysicalMin":160}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-06-22 11:56:47: MQTT publish: topic 'zigbee2mqtt/3D printer LEDs', payload '{"color_mode":"xy","linkquality":70,"state":null}'
Zigbee2MQTT:info  2021-06-22 11:56:47: Successfully configured '3D printer LEDs'
Zigbee2MQTT:debug 2021-06-22 11:56:47: Saving state to file /config/zigbee2mqtt/state.json
```

</details>

<details><summary>And then the logs and errors I get when I try to get/set <code>color_temp_startup</code>.</summary>

```
Zigbee2MQTT:debug 2021-06-22 11:59:06: Received MQTT message on 'zigbee2mqtt/3D printer LEDs/get' with data '{"color_temp_startup":""}'
Zigbee2MQTT:debug 2021-06-22 11:59:06: Publishing get 'get' 'color_temp_startup' to '3D printer LEDs'
Zigbee2MQTT:debug 2021-06-22 11:59:07: Received Zigbee message from '3D printer LEDs', type 'readResponse', cluster 'lightingColorCtrl', data '{}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-06-22 11:59:07: MQTT publish: topic 'zigbee2mqtt/3D printer LEDs', payload '{"color_mode":"xy","linkquality":55,"state":null}'
Zigbee2MQTT:error 2021-06-22 11:59:07: Publish 'get' 'color_temp_startup' to '3D printer LEDs' failed: 'Error: Read 0x00124b0022ed56a0/1 lightingColorCtrl(["startUpColorTemperature"], {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Zigbee2MQTT:debug 2021-06-22 11:59:07: Error: Read 0x00124b0022ed56a0/1 lightingColorCtrl(["startUpColorTemperature"], {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:221:23)
    at Endpoint.<anonymous> (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:314:26)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58)
Zigbee2MQTT:info  2021-06-22 11:59:07: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'get' 'color_temp_startup' to '3D printer LEDs' failed: 'Error: Read 0x00124b0022ed56a0/1 lightingColorCtrl([\"startUpColorTemperature\"], {\"sendWhenActive\":false,\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'","meta":{"friendly_name":"3D printer LEDs"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:debug 2021-06-22 11:59:26: Received MQTT message on 'zigbee2mqtt/3D printer LEDs/get' with data '{"color_temp_startup":""}'
Zigbee2MQTT:debug 2021-06-22 11:59:26: Publishing get 'get' 'color_temp_startup' to '3D printer LEDs'
Zigbee2MQTT:debug 2021-06-22 11:59:26: Received Zigbee message from '3D printer LEDs', type 'readResponse', cluster 'lightingColorCtrl', data '{}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-06-22 11:59:26: MQTT publish: topic 'zigbee2mqtt/3D printer LEDs', payload '{"color_mode":"xy","linkquality":55,"state":null}'
Zigbee2MQTT:error 2021-06-22 11:59:26: Publish 'get' 'color_temp_startup' to '3D printer LEDs' failed: 'Error: Read 0x00124b0022ed56a0/1 lightingColorCtrl(["startUpColorTemperature"], {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Zigbee2MQTT:debug 2021-06-22 11:59:26: Error: Read 0x00124b0022ed56a0/1 lightingColorCtrl(["startUpColorTemperature"], {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:221:23)
    at Endpoint.<anonymous> (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:314:26)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58)
Zigbee2MQTT:info  2021-06-22 11:59:26: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'get' 'color_temp_startup' to '3D printer LEDs' failed: 'Error: Read 0x00124b0022ed56a0/1 lightingColorCtrl([\"startUpColorTemperature\"], {\"sendWhenActive\":false,\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'","meta":{"friendly_name":"3D printer LEDs"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:debug 2021-06-22 11:59:28: Received MQTT message on 'zigbee2mqtt/3D printer LEDs/set' with data '{"color_temp_startup":150}'
Zigbee2MQTT:debug 2021-06-22 11:59:28: Publishing 'set' 'color_temp_startup' to '3D printer LEDs'
Zigbee2MQTT:debug 2021-06-22 11:59:28: Requested color_temp 150 is lower than minimum supported 160, using minimum!
Zigbee2MQTT:error 2021-06-22 11:59:28: Publish 'set' 'color_temp_startup' to '3D printer LEDs' failed: 'Error: Write 0x00124b0022ed56a0/1 lightingColorCtrl({"startUpColorTemperature":160}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Zigbee2MQTT:debug 2021-06-22 11:59:28: Error: Write 0x00124b0022ed56a0/1 lightingColorCtrl({"startUpColorTemperature":160}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:221:23)
    at Endpoint.<anonymous> (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:286:26)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58)
Zigbee2MQTT:info  2021-06-22 11:59:28: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'color_temp_startup' to '3D printer LEDs' failed: 'Error: Write 0x00124b0022ed56a0/1 lightingColorCtrl({\"startUpColorTemperature\":160}, {\"sendWhenActive\":false,\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'","meta":{"friendly_name":"3D printer LEDs"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:debug 2021-06-22 11:59:30: Received MQTT message on 'zigbee2mqtt/3D printer LEDs/set' with data '{"color_temp_startup":65535}'
Zigbee2MQTT:debug 2021-06-22 11:59:30: Publishing 'set' 'color_temp_startup' to '3D printer LEDs'
Zigbee2MQTT:error 2021-06-22 11:59:30: Publish 'set' 'color_temp_startup' to '3D printer LEDs' failed: 'Error: Write 0x00124b0022ed56a0/1 lightingColorCtrl({"startUpColorTemperature":65535}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Zigbee2MQTT:debug 2021-06-22 11:59:30: Error: Write 0x00124b0022ed56a0/1 lightingColorCtrl({"startUpColorTemperature":65535}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:221:23)
    at Endpoint.<anonymous> (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:286:26)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58)
Zigbee2MQTT:info  2021-06-22 11:59:30: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'color_temp_startup' to '3D printer LEDs' failed: 'Error: Write 0x00124b0022ed56a0/1 lightingColorCtrl({\"startUpColorTemperature\":65535}, {\"sendWhenActive\":false,\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'","meta":{"friendly_name":"3D printer LEDs"},"type":"zigbee_publish_error"}'
```

</details>

## What did you expect to happen

Ideally, I would hope there is a way to set the controller's behaviour on power cycle, but if it does not support that feature, I'd rather not see the option nag me in the UI. 😬 

## How to reproduce it (minimal and precise)

1. Pair the device.
2. Go to its "Exposes" tab.
3. Click on a value for `color_temp_startup`.

## Debug info
Zigbee2MQTT version: `edge` (updated before my tests above).
Adapter hardware: CC2531.
Adapter firmware version: 20201128.

**Comment by Koenkk** [comment]
Device does not seem to support it, disabled it.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
