### ISSUE TITLE
Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.

### ISSUE THREAD

**Issue by JasonBSteele** [Koenkk/zigbee2mqtt#7875]
Hi,

Zigbee2mqtt has been running well for me over the last year. I wanted to move a device with model name WallDimmerMaster from a SmartThimgs v1 hub to Zigbee2mqtt. It paired successfully but the log showed that it was not supported. I searched the docs and source and found that it should be, so assumed I needed to update Zigbee2mqtt. I ran `npm update` which completed successfully, although there were a number of warnings for optional dependencies, and also 4 vulnerabilities reported.

When I ran `npm start` I got this error: 

```
> zigbee2mqtt@1.14.0 start /opt/zigbee2mqtt
> node index.js

/opt/zigbee2mqtt/lib/util/yaml.js:21
        throw error;
        ^

Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
    at Object.safeLoad (/opt/zigbee2mqtt/node_modules/js-yaml/index.js:10:11)
    at Object.read (/opt/zigbee2mqtt/lib/util/yaml.js:7:21)
    at read (/opt/zigbee2mqtt/lib/util/settings.js:364:20)
    at get (/opt/zigbee2mqtt/lib/util/settings.js:404:21)
    at Object.getWithDefaults [as get] (/opt/zigbee2mqtt/lib/util/settings.js:412:69)
    at Object.<anonymous> (/opt/zigbee2mqtt/lib/util/logger.js:12:25)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)

```

So it seems that Zigbee2mqtt is using `yaml.safeLoad` which has been deprecated?

Is this a known issue, or a misleading error message that I need to fix in some way?

**Comment by JasonBSteele** [comment]
I updated yaml.js to use `load` instead of `safeLoad` and that appeared to solve the problem.

**Comment by JasonBSteele** [comment]
I realise now that this is not the way to update Z2M. I should have followed the instructions at https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html#6-for-later-update-zigbee2mqtt-to-the-latest-version
