### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'dist/.hash'

### ISSUE THREAD

**Issue by araczkowski** [Koenkk/zigbee2mqtt#8214]
## What happened

after upgrade to 1.21.0 I have a error on start:

```
4|zigbee   | Building Zigbee2MQTT... (initial build)
4|zigbee   | , finished
4|zigbee   | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
4|zigbee   | Error: ENOENT: no such file or directory, open 'dist/.hash'
4|zigbee   |     at Object.openSync (fs.js:462:3)
4|zigbee   |     at Object.readFileSync (fs.js:364:35)
4|zigbee   |     at checkDist (/data/data/pl.sviete.dom/files/home/zigbee2mqtt/index.js:61:25)
4|zigbee   |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
4|zigbee   |     at async start (/data/data/pl.sviete.dom/files/home/zigbee2mqtt/index.js:69:5)
```

but in fact file ``dist/.hash`` exists:

```
~/zigbee2mqtt $ file dist/.hash 
dist/.hash: ASCII text, with no line terminators
```

so it is something with path, in this line:

https://github.com/Koenkk/zigbee2mqtt/blob/70891eec39018303a43349c875ad04d44b3b43cf/index.js#L12

when I changed it to:

```
const hashFile = path.join('./dist', '.hash');
```
it works OK - I'm providing a pull request for this

## What did you expect to happen

work without Error: ENOENT: no such file or directory, open 'dist/.hash' 

## Debug info
Zigbee2MQTT version: 1.21.0 
Adapter hardware: Conbee II

**Comment by araczkowski** [comment]
I figured out better way:

```
cd ~/zigbee2mqtt ;  pm2 start index.js
```

closing this
