### ISSUE TITLE
zigbee2mqtt crash on data request failed

### ISSUE THREAD

**Issue by flaviut** [Koenkk/zigbee2mqtt#8437]
## What happened

zigbee2mqtt crashed. There's nothing in the logs to indicate what went wrong before this crash, only the stack trace:

```
Error: Command 0x00124b0022fea35e/1 ssIasZone.enrollRsp({"enrollrspcode":0,"zoneid":23}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'MAC transaction expired' (240))
    at ZStackAdapter.sendZclFrameToEndpointInternal (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:389:23)
    at Queue.executeNext (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
```

## Debug info
Zigbee2MQTT version: 70891eec39018303a43349c875ad04d44b3b43cf
Adapter hardware: cc2652p
Adapter firmware version: [CC2652P_E72_20210813](https://github.com/egony/cc2652p_E72-2G4M20S1E/tree/master/firmware/coordinator)

**Comment by flaviut** [comment]
Hi, this is still an issue.

**Comment by flaviut** [comment]
Hi, this is still an issue.

Unfortunately issues don't get resolved by just closing them.

**Comment by flaviut** [comment]
Still an issue.

**Comment by flaviut** [comment]
hey, this is still an issue.

**Comment by flaviut** [comment]
Still an issue
