### ISSUE TITLE
Zigbee LED controller dimmer (GL-C-009) Gledopto 10-15s delay to switch off and unable to read states from Home assistant

### ISSUE THREAD

**Issue by mediaworld2007** [Koenkk/zigbee2mqtt#8734]
Zigbee LED controller dimmer (GL-C-009) Gledopto 10-15s delay to switch off and unable to read states from Home assistant .
I have two GL_C-009  with Hassio core-2021.9.6  and zigbee2mqtt Current version: 1.18.1-1 - cc2652rb_stick_-_slaesh_s Z-Stack 3.0

When i switch on/off  it spend 10-15 s to switch the led . Status is not read in home assistant. 

If i use it with philips hue hub, it works fine .

Zigbee2MQTT:info  2021-09-12 21:30:02: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'led salone' failed: 'Error: Command 0x00124b001ad71a70/11 genOnOff.on({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Timeout - 47951 - 11 - 13 - 6 - 11 after 10000ms)'","meta":{"friendly_name":"led salone"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:error 2021-09-12 21:30:25: Publish 'set' 'brightness' to 'led salone' failed: 'Error: Command 0x00124b001ad71a70/11 genLevelCtrl.moveToLevelWithOnOff({"level":155,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 47951 - 11 - 14 - 8 - 11 after 10000ms)'
Zigbee2MQTT:debug 2021-09-12 21:30:25: Error: Command 0x00124b001ad71a70/11 genLevelCtrl.moveToLevelWithOnOff({"level":155,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 47951 - 11 - 14 - 8 - 11 after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Zigbee2MQTT:info  2021-09-12 21:30:25: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'brightness' to 'led salone' failed: 'Error: Command 0x00124b001ad71a70/11 genLevelCtrl.moveToLevelWithOnOff({\"level\":155,\"transtime\":0}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Timeout - 47951 - 11 - 14 - 8 - 11 after 10000ms)'","meta":{"friendly_name":"led salone"},"type":"zigbee_publish_error"}'

Zigbee2MQTT:debug 2021-09-12 21:39:11: Received MQTT message on 'zigbee2mqtt/led salone/set' with data '{"state":"OFF"}'
Zigbee2MQTT:debug 2021-09-12 21:39:11: Publishing 'set' 'state' to 'led salone'
Zigbee2MQTT:error 2021-09-12 21:39:35: Publish 'set' 'state' to 'led salone' failed: 'Error: Command 0x00124b001ad71a70/11 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 47951 - 11 - 43 - 6 - 11 after 10000ms)'
Zigbee2MQTT:debug 2021-09-12 21:39:35: Error: Command 0x00124b001ad71a70/11 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 47951 - 11 - 43 - 6 - 11 after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Zigbee2MQTT:info  2021-09-12 21:39:35: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'led salone' failed: 'Error: Command 0x00124b001ad71a70/11 genOnOff.off({}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Timeout - 47951 - 11 - 43 - 6 - 11 after 10000ms)'","meta":{"friendly_name":"led salone"},"type":"zigbee_publish_error"}'

**Comment by mediaworld2007** [comment]
solved coordinator firmware 20210708
