### ISSUE TITLE
Every few hours Zigbee2MQTT crashes with: UnhandledPromiseRejectionWarning: Error: SRSP - ZDO - mgmtPermitJoinReq after 6000ms

### ISSUE THREAD

**Issue by wojciechczyz** [Koenkk/zigbee2mqtt#8870]
## What happened
Every few hours Zigbee2MQTT crashes with:
UnhandledPromiseRejectionWarning: Error: SRSP - ZDO - mgmtPermitJoinReq after 6000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

till I restart Zigbee2MQTT container, when it works again few hours till it starts again.

It may be related to recent change of the coordinator and router from 
CC2652 to cc2652p sticks. I changed them to get 20dbi signal.

## What did you expect to happen

Working stable as before :-)

## How to reproduce it (minimal and precise)

Not sure, the only change was upgrading sticks.

## Debug info
Zigbee2MQTT version:
Adapter hardware: CC2652p

Adapter firmware version:
newest 

I see following log when it started happening
Zigbee2MQTT:error 2021-09-24 19:29:02: Failed to execute LQI for '0x000d6f00143c087a'
Zigbee2MQTT:error 2021-09-24 19:29:14: Publish 'set' 'state' to '0x00124b001f79db6b' failed: 'Error: Command 0x00124b001f79db6b/15 genOnOff.on({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)'
Zigbee2MQTT:info  2021-09-24 19:29:14: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x00124b001f79db6b' failed: 'Error: Command 0x00124b001f79db6b/15 genOnOff.on({}, {\"sendWhenActive\":false,\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (SRSP - AF - dataRequest after 6000ms)'","meta":{"friendly_name":"0x00124b001f79db6b"},"type":"zigbee_publish_error"}'
Zigbee2MQTT:error 2021-09-24 19:29:56: Publish 'set' 'state' to '0x00124b001f79db6b' failed: 'Error: Command 0x00124b001f79db6b/15 genOnOff.off({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)'
Zigbee2MQTT:info  2021-09-24 19:29:56: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to '0x00124b001f79db6b' failed: 'Error: Command 0x00124b001f79db6b/15 genOnOff.off({}, {\"sendWhenActive\":false,\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (SRSP - AF - dataRequest after 6000ms)'","meta":{"friendly_name":"0x00124b001f79db6b"},"type":"zigbee_publish_error"}'
(node:407) UnhandledPromiseRejectionWarning: Error: SRSP - ZDO - mgmtPermitJoinReq after 6000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(node:407) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 22)
Zigbee2MQTT:error 2021-09-24 19:31:14: Failed to execute LQI for 'LightLeftBathroomBig'
Zigbee2MQTT:error 2021-09-24 19:32:50: Failed to execute LQI for '0x001788010804158f'

**Comment by wojciechczyz** [comment]
This happened when using Egony latest firmware. Moving back firmware to latest Koenkk stopped crashing Zigbee2Mqtt.
So root cause seems to be related to the coordinator firmware itself, yet Zigbee2Mqtt could have resiliency improved.
Zigbee2Mqtt would benefit from some fix not to crash completely under such conditions. Restarting Zigbee2Mqtt was alleviating for some time proving that actually Zigbee2Mqtt was being crashed.
