### ISSUE TITLE
Grouped LED strip provides no color_mode to Home Assistant

### ISSUE THREAD

**Issue by andreasbrett** [Koenkk/zigbee2mqtt#8970]
## What happened
Home Assistant logs are filled with error messages about missing color_mode in z2m state messages. This only happens for a somewhat atypical group with only 1 device. I have 3 LED strips in my living room - 1 in the front, 2 in the back. I created 2 groups: `lr_led_strip_front` and `lr_led_strip_back`. The front group containing only 1 LED strip (a `GLEDOPTO GL-C-007-2ID`) doesn't send a color_mode in its state (see error below about missing 'color_mode' key).

```
ERROR (MainThread) [homeassistant.util.logging] Exception in state_received when handling msg on 'zigbee2mqtt/lr_led_strip_front': '{"brightness":1,"color":{"h":330,"hsb":"214.588242,100.000000,100.000000","hue":null,"s":95,"saturation":null,"v":100,"x":null,"y":null},"state":"OFF"}'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 34, in wrapper
msg_callback(msg)
File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_json.py", line 308, in state_received
self._update_color(values)
File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_json.py", line 247, in _update_color
color_mode = values["color_mode"]
KeyError: 'color_mode'
```

The LED strip itself doesn't raise errors, nor do any other zigbee devices or groups. Only the `lr_led_strip_front` group where it is the only member causes this behaviour.

## Debug info
Zigbee2MQTT version: 1.21.2
Adapter hardware: CC2531
Adapter firmware version: 20190619

**Comment by andreasbrett** [comment]
Here's what the single LED strip will report via MQTT when changing color (fetched via z2m frontend):

```
Info MQTT publish: topic 'zigbee2mqtt/lr_led_strip1', payload '{"brightness":1,"brightness_rgb":203,"brightness_white":107,"color":{"h":null,"hsb":"214.588242,100.000000,100.000000","hue":null,"s":null,"saturation":null,"v":100,"x":null,"y":null},"color_mode_rgb":"xy","color_mode_white":"xy","color_rgb":{"h":330,"hue":346,"s":95,"saturation":100,"v":100,"x":0.571,"y":0.241},"color_temp_rgb":127,"color_temp_white":150,"color_white":{"hue":357,"saturation":100,"x":0.667,"y":0.284},"last_seen":"2021-10-03T11:24:23+02:00","linkquality":89,"state":"OFF","state_rgb":"ON","state_white":"OFF","white_value":-1}'
Info MQTT publish: topic 'zigbee2mqtt/lr_led_strip1/rgb', payload '{"brightness":203,"color":{"h":330,"hue":346,"s":95,"saturation":100,"v":100,"x":0.571,"y":0.241},"color_mode":"xy","color_temp":127,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/lr_led_strip1/white', payload '{"brightness":107,"color":{"hue":357,"saturation":100,"x":0.667,"y":0.284},"color_mode":"xy","color_temp":150,"state":"OFF"}'
```
