### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by strandbein** [Koenkk/zigbee2mqtt#9152]
I have a problem with Müller Licht smart power strip, [Modell 404017](Müller Licht smart power strip, Modell 404017
https://www.zigbee2mqtt.io/devices/404017.html#m%25C3%25BCller%2520licht-404017)
ConBee II latest firmware 26720700
Home Assistant AddOn

Zigbee2MQTT:error 2021-10-14 19:31:53: Failed to configure 'Serverschrank Steckerleiste', attempt 1 (TypeError: Cannot read property 'bind' of undefined
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:24)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/müller_licht.js:33:29)
    at Configure.configure (/app/lib/extension/configure.ts:119:37)
    at Configure.start (/app/lib/extension/configure.ts:73:24)
    at Controller.callExtensionMethod (/app/lib/controller.js:427:58)
    at Controller.start (/app/lib/controller.js:184:9)
    at start (/app/index.js:95:5))
Zigbee2MQTT:error 2021-10-14 19:31:53: Failed to configure 'Serverschrank Steckerleiste', attempt 2 (TypeError: Cannot read property 'bind' of undefined
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:24)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/müller_licht.js:33:29)
    at Configure.configure (/app/lib/extension/configure.ts:119:37)
    at EventEmitter.<anonymous> (/app/lib/extension/configure.ts:84:62)
    at EventEmitter.emit (events.js:400:28)
    at EventBus.emitLastSeenChanged (/app/lib/eventBus.ts:64:80)
    at Controller.<anonymous> (/app/lib/zigbee.ts:71:27)
    at Controller.emit (events.js:400:28)
    at Controller.onZclOrRawData (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:596:14)
    at DeconzAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:135:70))

What can I do?
Thanks!

**Comment by Koenkk** [comment]
This is caused by the report feature which is deprecated, see https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.17.1 how to migrate.

**Comment by strandbein** [comment]
Also in 1.22.0-2 there is no improvement.

**Comment by strandbein** [comment]
Hello,
also in version 1.23.0 there is no improvement for this problem: 

CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2022-02-03 21:47:14: Failed to configure 'Serverschrank Plug', attempt 1 (TypeError: Cannot read property 'bind' of undefined
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:24)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/müller_licht.js:33:29)
    at Configure.configure (/app/lib/extension/configure.ts:115:37)
    at Configure.start (/app/lib/extension/configure.ts:68:24)
    at Controller.callExtensions (/app/lib/controller.ts:315:17)
    at Controller.start (/app/lib/controller.ts:152:9)
    at start (/app/index.js:101:5))
Zigbee2MQTT:error 2022-02-03 21:51:48: Failed to configure 'Serverschrank Plug', attempt 2 (TypeError: Cannot read property 'bind' of undefined
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:24)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/müller_licht.js:33:29)
    at Configure.configure (/app/lib/extension/configure.ts:115:37)
    at EventEmitter.<anonymous> (/app/lib/extension/configure.ts:80:62)
    at EventEmitter.emit (events.js:412:35)
    at EventBus.emitLastSeenChanged (/app/lib/eventBus.ts:45:22)
    at Controller.<anonymous> (/app/lib/zigbee.ts:66:27)
    at Controller.emit (events.js:400:28)
    at Controller.selfAndDeviceEmit (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:481:14)
    at Controller.onZclOrRawData (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:692:18))
Zigbee2MQTT:error 2022-02-03 21:56:47: Failed to configure 'Serverschrank Plug', attempt 3 (TypeError: Cannot read property 'bind' of undefined
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:24)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/müller_licht.js:33:29)
    at Configure.configure (/app/lib/extension/configure.ts:115:37)
    at EventEmitter.<anonymous> (/app/lib/extension/configure.ts:80:62)
    at EventEmitter.emit (events.js:412:35)
    at EventBus.emitLastSeenChanged (/app/lib/eventBus.ts:45:22)
    at Controller.<anonymous> (/app/lib/zigbee.ts:66:27)
    at Controller.emit (events.js:400:28)
    at Controller.selfAndDeviceEmit (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:481:14)
    at Controller.onZclOrRawData (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:692:18))

**Comment by Koenkk** [comment]
Could you check if this is fixed in the latest dev?

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by strandbein** [comment]
No error message since 24 hours with newest dev branch, good work, thanks a lot!
