### ISSUE TITLE
Ubisys S1 momentary button configuration

### ISSUE THREAD

**Issue by theFork** [Koenkk/zigbee2mqtt#9350]
# Bug Report

I'm having problems to configure a Ubisys S1 to toggle its output every time I press a momentary switch connected to the input.

## What happened / How to reproduce

My approach is to publish

```
{
  "configure_device_setup" : {
    "input_action_templates": [ 
      {"type":"toggle"}
    ]
  }
}
```

to the topic `zigbee2mqtt/s1_steckdose_terrasse/set` but I get this in the log:

```
Zigbee2MQTT:warn  2021-10-26 19:49:19: ubisys: Using input(s) 0 and endpoint 2 for 'toggle'.
Zigbee2MQTT:error 2021-10-26 19:49:19: Publish 'set' 'configure_device_setup' to 's1_steckdose_terrasse' failed: 'Error: Write 0x001fee000000210f/232 manuSpecificUbisysDeviceSetup({"inputActions":{"elementType":"octetStr","elements":[[0,13,2,6,0,2]]}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4338,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
Zigbee2MQTT:info  2021-10-26 19:49:19: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'configure_device_setup' to 's1_steckdose_terrasse' failed: 'Error: Write 0x001fee000000210f/232 manuSpecificUbisysDeviceSetup({\"inputActions\":{\"elementType\":\"octetStr\",\"elements\":[[0,13,2,6,0,2]]}}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":4338,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'","meta":{"friendly_name":"s1_steckdose_terrasse"},"type":"zigbee_publish_error"}'
```

## What did you expect to happen

I expected a log entry more like `Info: Successfully configured input 0 of entity S1_steckdose_terrasse as 'toggle'` and being able to toggle the S1 using a momentary switch.

## Debug Info.
Zigbee2MQTT version: 1.18.1
Adapter hardware: CC2652R
Adapter firmware version: 1.2.7

Thanks in advance, Simon

**Comment by theFork** [comment]
Weird. Is there a was to ask Z2M to check for FW updates?

**Comment by sjorge** [comment]
You can hit the check button in the OTA tab on the frontend.

~ sjorge

**Comment by theFork** [comment]
I did this with the S1 I want to configured, getting, this log output:

```
info  2021-10-30 19:10:45: Checking if update available for 's1_steckdose_terrasse'
info  2021-10-30 19:10:45: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Checking if update available for 's1_steckdose_terrasse'","meta":{"device":"s1_steckdose_terrasse","status":"checking_if_available"},"type":"ota_update"}'
info  2021-10-30 19:10:46: MQTT publish: topic 'zigbee2mqtt/s2_licht_eg_az_bad', payload '{"linkquality":12,"power":13,"state_l1":"ON","state_l2":"OFF","update":{"state":"idle"},"update_available":false}'
info  2021-10-30 19:10:46: MQTT publish: topic 'zigbee2mqtt/s2_licht_eg_flur_signal', payload '{"linkquality":6,"power":0,"state_l1":"OFF","state_l2":"OFF","update":{"state":"idle"},"update_available":false}'
info  2021-10-30 19:10:53: No update available for 's1_steckdose_terrasse'
info  2021-10-30 19:10:53: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"No update available for 's1_steckdose_terrasse'","meta":{"device":"s1_steckdose_terrasse","status":"not_available"},"type":"ota_update"}'
info  2021-10-30 19:10:53: MQTT publish: topic 'zigbee2mqtt/s1_steckdose_terrasse', payload '{"linkquality":15,"power":0,"state":"OFF","update":{"state":"idle"},"update_available":false}'
info  2021-10-30 19:10:53: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"s1_steckdose_terrasse","updateAvailable":false},"status":"ok","transaction":"u5qet-1"}'
```

It appears as if somethings goes wrong here, doesn't it? The funny thing is, I have two more S1 in my setup, both with newer firmware versions (`20170522-DE-FB0` and `20190529-DE-FB0`).

When publishing to `zigbee2mqtt/FRIENDLY_NAME/get/configure_device_setup` all three show the same `UNSUPPORTED_ATTRIBUTE` status in the log file. Thus, from here it looks like the behaviour is unrelated to the firmware version.

**Comment by theFork** [comment]
For a little more information, I enabled debug logging (herdsman also) and tried to configure EP 232 again. This is what the log looks like:

```
debug 2021-11-05 20:47:27: Received MQTT message on 'zigbee2mqtt/s1_steckdose_terrasse/set' with data '{
  "configure_device_setup" : {
    "input_action_templates": [ 
      {"type":"toggle",
      "endpoint":232}
    ]
  }
}'
debug 2021-11-05 20:47:27: Publishing 'set' 'configure_device_setup' to 's1_steckdose_terrasse'
warn  2021-11-05 20:47:27: ubisys: Using input(s) 0 and endpoint 232 for 'toggle'.
debug 2021-11-05 20:47:27: ubisys: input_actions to be sent to 's1_steckdose_terrasse': [[0,13,232,6,0,2]]
error 2021-11-05 20:47:27: Publish 'set' 'configure_device_setup' to 's1_steckdose_terrasse' failed: 'Error: Write 0x001fee000000210f/232 manuSpecificUbisysDeviceSetup({"inputActions":{"elementType":"octetStr","elements":[[0,13,232,6,0,2]]}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4338,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
debug 2021-11-05 20:47:27: Error: Write 0x001fee000000210f/232 manuSpecificUbisysDeviceSetup({"inputActions":{"elementType":"octetStr","elements":[[0,13,232,6,0,2]]}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4338,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:196:23)
    at Endpoint.<anonymous> (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:225:26)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58)
info  2021-11-05 20:47:27: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'configure_device_setup' to 's1_steckdose_terrasse' failed: 'Error: Write 0x001fee000000210f/232 manuSpecificUbisysDeviceSetup({\"inputActions\":{\"elementType\":\"octetStr\",\"elements\":[[0,13,232,6,0,2]]}}, {\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":4338,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'","meta":{"friendly_name":"s1_steckdose_terrasse"},"type":"zigbee_publish_error"}'
debug 2021-11-05 20:47:39: Received Zigbee message from 'deckenlampe_tradfri_eg_az', type 'readResponse', cluster 'genBasic', data '{"zclVersion":3}' from endpoint 1 with groupID 0
```

Looks like it points to zigbee-herdsman. Should I close this one here and open a new one in the herdsman repo?

**Comment by sjorge** [comment]
UNSUPPORTED_ATTRIBUTE is a response coming back from the device though
@felixstorm any ideas? Maybe we can try without the manufacturer specific code or with... depending on whats it doing now?

**Comment by felixstorm** [comment]
Busy as usual :wink:, but I'll try to look into it within the next few days.

**Comment by felixstorm** [comment]
From looking at the logs provided here, I can see no obvious issues (endpoint 232 is hardcoded within the respective configuration code, so the endpoint targeted with the mqttt message most likely does not matter).  
I guess I need to setup a test environment and take a look at the zigbee bytes sent to the device for the write attribute command.

It will probably take a few days, but I‘ll get back to you…

**Comment by felixstorm** [comment]
Since z2m 1.18.1 is not current, I just tried to configure some inputs on a D1 that I have in my "production" network (z2m 1.22.0) and this seems to work without any problems. Therefore I think you should try again with a current version of z2m first.

**Comment by theFork** [comment]
After updating to 1.22.0, everything works as expected. Sorry for the inconvenience and thanks for your advice.
