### ISSUE TITLE
Salus VS20WRF/VS20BRF

### ISSUE THREAD

**Issue by deennoo** [Koenkk/zigbee2mqtt#938]
I'm a proud user of Salus Solutios, as other here,

I'm starting with Zigbee2Mqtt pair with Domoticz on a RPI3

I'm a middle player, as i'm using Domoticz since 6 year now, playing with RFlink, EasyESP, and Zigate (Zigbee2mqtt french competitor)

Bug report
I'm trying to had some Salus devices using Zigbee2mqtt, first of all a Battery room thermostat.

adding this device made Zigbee 2 mqtt crash : 

```
zigbee2mqtt:info 2019-1-25 22:14:14 New device with address 0x001e5e0902130636 connected!
  zigbee2mqtt:info 2019-1-25 22:14:14 MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connecte                                                                                                                        d","message":"0x001e5e0902130636"}'
  zigbee2mqtt:warn 2019-1-25 22:14:14 Device with modelID 'SAL6ET1' is not supported.
  zigbee2mqtt:warn 2019-1-25 22:14:14 Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_dev                                                                                                                        ices.html
  zigbee2mqtt:warn 2019-1-25 22:14:14 Device with modelID 'SAL6ET1' is not supported.
  zigbee2mqtt:warn 2019-1-25 22:14:14 Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_dev                                                                                                                        ices.html
/opt/zigbee2mqtt/node_modules/zcl-packet/lib/functional.js:27
        throw new Error('Unrecognized cluster');
        ^

Error: Unrecognized cluster
    at new FuncPayload (/opt/zigbee2mqtt/node_modules/zcl-packet/lib/functional.js:27:15)
    at /opt/zigbee2mqtt/node_modules/zcl-packet/lib/zcl.js:33:22
    at Dissolve.<anonymous> (/opt/zigbee2mqtt/node_modules/zcl-packet/lib/zcl.js:121:9)
    at Object.onceWrapper (events.js:273:13)
    at Dissolve.emit (events.js:182:13)
    at Dissolve.<anonymous> (/opt/zigbee2mqtt/node_modules/dissolve-chunks/index.js:73:29)
    at Dissolve.emit (events.js:182:13)
    at emitReadable_ (/opt/zigbee2mqtt/node_modules/dissolve/node_modules/readable-stream/lib/_stream_readable.js:456                                                                                                                        :10)
    at emitReadable (/opt/zigbee2mqtt/node_modules/dissolve/node_modules/readable-stream/lib/_stream_readable.js:450:                                                                                                                        7)
    at readableAddChunk (/opt/zigbee2mqtt/node_modules/dissolve/node_modules/readable-stream/lib/_stream_readable.js:                                                                                                                        206:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-01-25T21_14_15_163Z-debug.log
```
this result on the room thermostat a screen who stays on join status.

Did you think that i can use the same method as done for the Salus FC600 : https://github.com/Koenkk/zigbee2mqtt/issues/917

**Comment by deennoo** [comment]
After editing device.js with : 

```
    {
        zigbeeModel: ['SAL6ET1'],
        model: 'SAL6ET1',
        vendor: 'Salus',
        description: 'Thermostat, fan control, heat/cool',
        supports:'Measuring room temperature every 60s, setting room temperatyre, cooling/heating, 3 fan speed, programing schedule, temperature offset and etc.',
        fromZigbee: [],
        toZigbee: [],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 9);
            const actions = [
                (cb) => device.bind('genBasic', coordinator, cb),
                (cb) => device.bind('genPowerCfg', coordinator, cb),
                (cb) => device.bind('genIdentify', coordinator, cb),
                (cb) => device.bind('genTime', coordinator, cb),
                (cb) => device.bind('genPollCtrl', coordinator, cb),
                (cb) => device.bind('hvacThermostat', coordinator, cb),
                (cb) => device.bind('hvacUserInterfaceCfg', coordinator, cb),
                (cb) => device.report('hvacThermostat', 'localTemp', 300, 3600, 0, cb),
                (cb) => device.report('hvacThermostat', 'localTemperatureCalibration', 1, 0, 0, cb),
                (cb) => device.report('hvacThermostat', 'occupiedHeatingSetpoint', 1, 0, 1, cb),
                (cb) => device.report('hvacThermostat', 'runningState', 1, 0, 0, cb),
            ];
            execute(device, actions, callback);
        },
 
    },
```
I still have the same error, bad cluster id ; 

 ```
cc-znp:AREQ <-- AF:incomingMsg, { groupid: 0, clusterid: 64512, srcaddr: 34283, srcendpoint: 9, dstendpoint: 1, wasbroadcast: 0, linkquality: 118, securityuse: 0, timestamp: 12288277, transseqnumber: 0, len: 12, data: <Buffer 1d 78 10 05 10 ff 02 01 a4 50 9a 00> } +5ms
  zigbee-shepherd:af dispatchIncomingMsg(): type: incomingMsg, msg: [object Object] +1ms
/opt/zigbee2mqtt/node_modules/zcl-packet/lib/functional.js:27
        throw new Error('Unrecognized cluster');
        ^
```


Some variante with this one : it only works "online" i can't choose if he need an internet connection or not

As this is a battery device i'm not sure about "coordinator" status as it's look like a enddevice.

**Comment by Chrischi-** [comment]
look here: https://github.com/Koenkk/zigbee2mqtt/issues/917#issuecomment-456883921

you need to check out the salus branch to get past the cluster error.

**Comment by deennoo** [comment]
thx @Chrischi- for this.

How to check salus branch ?

sudo git checkout salus ?

**Comment by Taranoo2** [comment]
> thx @Chrischi- for this.
> 
> How to check salus branch ?
> 
> sudo git checkout salus ?

Did you manage it somehow and solve this problem? Have you configure it ?
