### ISSUE TITLE
Zigbee problem on HASS beta, after 3 days it failed.

### ISSUE THREAD

**Issue by malosaa** [Koenkk/zigbee2mqtt#9476]
## What happened

In Homeassistant,
In the working core version(2021.9.5) it did stay up for more than 1 month before updating to the beta.
It was just working till now, and i have the restart button enabled, so if it stops it restarts, but it did not work

It works again if i restart virtualbox itself.
If i just unplug the stick and put back in, it still gives the same error, so restart needed.

Using Home Assistant OS 2021.11.0b1

## How to reproduce it (minimal and precise)
I don't know, i think its an issue with the beta.
My system is a laptop, virtual box is running with the last HomeAssistant OS, and i use a powered USB device on the laptop and there i connected the zigbee2mqtt device.
I never had an issue running core 2021.9.5.

this is the screenshot of virtualbox.
![image](https://user-images.githubusercontent.com/13116501/140044030-b3bb9679-9cd7-4bdd-bb3d-39f33378bf8a.png)

## Debug info

```
Zigbee2MQTT:error 2021-11-03 10:44:19: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-11-03 10:44:19: Failed to start zigbee
Zigbee2MQTT:error 2021-11-03 10:44:19: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-11-03 10:44:19: Exiting...
Zigbee2MQTT:error 2021-11-03 10:44:19: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[10:44:20] INFO: Handing over control to Zigbee2mqtt Core ...
```

Zigbee2MQTT version:
Adapter hardware: CC2531

**Comment by malosaa** [comment]
After a restarting virtualbox without disconnecting and re-plugging the usb i get this and it eventually starts after some errors. 

```
[11:46:24] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.0 start
> node index.js
Zigbee2MQTT:error 2021-11-03 11:46:56: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-11-03 11:46:56: Failed to start zigbee
Zigbee2MQTT:error 2021-11-03 11:46:56: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-11-03 11:46:56: Exiting...
Zigbee2MQTT:error 2021-11-03 11:46:57: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:97:5)
[11:46:57] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.0 start
> node index.js
Zigbee2MQTT:error 2021-11-03 11:47:31: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-11-03 11:47:31: Failed to start zigbee
Zigbee2MQTT:error 2021-11-03 11:47:31: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-11-03 11:47:31: Exiting...
Zigbee2MQTT:error 2021-11-03 11:47:32: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:97:5)
[11:47:33] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.0 start
> node index.js
Zigbee2MQTT:warn  2021-11-03 11:48:08: `permit_join` set to  `true` in configuration.yaml.
Zigbee2MQTT:warn  2021-11-03 11:48:08: Allowing new devices to join.
Zigbee2MQTT:warn  2021-11-03 11:48:08: Set `permit_join` to `false` once you joined all devices.
Zigbee2MQTT:warn  2021-11-03 11:48:09: Using experimental new availability feature
```

**Comment by malosaa** [comment]
well the new update of the firmware did fix it
