### ISSUE TITLE
Adding NLG-RGBW to group fails, device requests OTA instead

### ISSUE THREAD

**Issue by redahb** [Koenkk/zigbee2mqtt#9510]
## What happened
I'm trying to add two NLG-RGBW lights (Paul Neuhaus Q-Flag) to a Zigbee Group via the Zigbee2MQTT dashboard in Home Assistant. The devices will not join the group, and (coincidence?) request OTA after trying to add them to a group.

## What did you expect to happen
Devices would join the group, just like Hue devices do.

## How to reproduce it (minimal and precise)
Create a Zigbee group in the interface. Add NLG-RGBW device. Leave 'endpoint' at the default '1' ('2' does not work either). Wait for error :)

## Debug info
Zigbee2MQTT version: 1.22.0-2 
Adapter hardware: Smartlight CC2652P
Adapter firmware version: 20210708

## Log
Device 1 (lamp_gang_beneden_spiegel):
```
[debug] Received MQTT message on 'zigbee2mqtt/bridge/request/group/members/add' with data '{"device":"0x00158d000268a5ae/1","group":"lamp_gang_beneden","transaction":"d5c8o-4"}'
[debug] Type[error]: Cannot read property '0' of undefined at Device.endpointName (/app/lib/model/device.ts:55:103) at Groups.onMQTTMessage (/app/lib/extension/groups.ts:302:64) at EventEmitter.emit (events.js:412:35) at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:95:22) at MQTT.onMessage (/app/lib/mqtt.ts:113:27) at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:92:27) at WebSocket.emit (events.js:400:28) at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1022:20) at Receiver.emit (events.js:400:28) at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:522:14)
[info] MQTT publish: topic 'zigbee2mqtt/bridge/response/group/members/add', payload '{"data":{"device":"0x00158d000268a5ae/1","group":"lamp_gang_beneden"},"[error]":"Failed to add from group (Cannot read property '0' of undefined)","status":"[error]","transaction":"d5c8o-4"}'
[error] Failed to add from group (Cannot read property '0' of undefined)
[debug] Received Zigbee message from 'lamp_gang_beneden_spiegel', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":2,"imageType":4624,"manufacturerCode":4151}' from endpoint 2 with groupID 0
[debug] Device 'lamp_gang_beneden_spiegel' requested OTA
```
Device 2 (lamp_gang_beneden_voordeur):
```
[debug] Received MQTT message on 'zigbee2mqtt/bridge/request/group/members/add' with data '{"device":"0x00158d0002681fb1/1","group":"lamp_gang_beneden","transaction":"d5c8o-5"}'
[debug] Type[error]: Cannot read property '0' of undefined at Device.endpointName (/app/lib/model/device.ts:55:103) at Groups.onMQTTMessage (/app/lib/extension/groups.ts:302:64) at EventEmitter.emit (events.js:412:35) at EventBus.emitMQTTMessage (/app/lib/eventBus.ts:95:22) at MQTT.onMessage (/app/lib/mqtt.ts:113:27) at WebSocket.<anonymous> (/app/lib/extension/frontend.ts:92:27) at WebSocket.emit (events.js:400:28) at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1022:20) at Receiver.emit (events.js:400:28) at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:522:14)
[info] MQTT publish: topic 'zigbee2mqtt/bridge/response/group/members/add', payload '{"data":{"device":"0x00158d0002681fb1/1","group":"lamp_gang_beneden"},"[error]":"Failed to add from group (Cannot read property '0' of undefined)","status":"[error]","transaction":"d5c8o-5"}'
[error] Failed to add from group (Cannot read property '0' of undefined)
[debug] Received Zigbee message from 'lamp_gang_beneden_voordeur', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":2,"imageType":4624,"manufacturerCode":4151}' from endpoint 2 with groupID 0
[debug] Device 'lamp_gang_beneden_voordeur' requested OTA
```

**Comment by Koenkk** [comment]
Could you provide me your data/database.db and configuration.yaml (with passwords/urls/usernames removed)?
