### ISSUE TITLE
Support for Dresden Elektronik FLS-H-lp

### ISSUE THREAD

**Issue by ilpantera** [Koenkk/zigbee2mqtt#9524]
Hi everyone, I have been trying to add the [Dresden Elektronik FLS-H-lp](https://zigbeealliance.org/zigbee_products/fls-h-lp/) for a while now, but am stuck. Hope you can help!

What I tried so far: I have created the FLS-H.js in the hassio/share/zigbee2mqtt folder with the following content:
```
fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['FLS-H3 '], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: 'FLS-H lp', // Vendor model number, look on the device for a model number
    vendor: 'dresden elektronik', // Vendor of the device (only used for documentation and startup logging)
    description: 'CWWW Light Switch', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    extend: extend.light_onoff_brightness_colortemp({colorTempRange: [153, 500]}),
    fromZigbee: [], // We will add this later
    toZigbee: [], // Should be empty, unless device can be controlled (e.g. lights, switches).
    exposes: [], // Defines what this device exposes, used for e.g. Home Assistant discovery and in the frontend
};
```

The space  behind the model (zigbeeModel: ['FLS-H3 ']) is intentional, it appears as if this is how it is named and it is the way it appears in the debugging/info window of the plugin. I have also added it to the configuration.yaml (and enabled the debug mode):

`{
  "external_converters": [
    "FLS-H.js"
  ],`

Unfortunately once I restart the plugin, the following error appears (from the plugin log):

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[18:40:49] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[18:40:50] INFO: MQTT available, fetching server detail ...
[18:40:51] INFO: Previous config file found, checking backup
[18:40:51] INFO: Creating backup config in '/share/zigbee2mqtt/.configuration.yaml.bk'
[18:40:51] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:40:53] INFO: Handing over control to Zigbee2mqtt Core ...

> zigbee2mqtt@1.18.1 start /app
> node index.js

(node:330) UnhandledPromiseRejectionWarning: internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'zigbee-herdsman-converters/lib/extend'
Require stack:
- /app/lib/util/utils.js
- /app/lib/util/settings.js
- /app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /app/lib/util/externally-loaded.js:5:16
    at Script.runInContext (vm.js:143:18)
    at Script.runInNewContext (vm.js:148:17)
    at Object.runInNewContext (vm.js:303:38)
    at loadModuleFromText (/app/lib/util/utils.js:156:8)
    at loadModuleFromFile (/app/lib/util/utils.js:162:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:330) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:330) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[18:41:00] INFO: Handing over control to Zigbee2mqtt Core ...

```
I ran update and upgrade, but the issue persists. Any ideas?! 
As soon as I either 
- delete the reference to my .js from the configuration.yaml 
- comment the const extend = ... and its use below

everything is starting up without a problem again. Thanks a lot for your support in advance!

## Information about the device + link
Zigbee Alliance Device Link: https://zigbeealliance.org/zigbee_products/fls-h-lp/
Datasheet: https://www.dresden-elektronik.de/download/datenblaetter.html?file=files/dresden-elektronik/content/downloads/datenblaetter/wireless%20light%20control/Datenblatt_FLS-H_lp.pdf

**Comment by ilpantera** [comment]
I finally realized that the latest version of zigbee2mqtt is in a different repository. with that it worked.
