### ISSUE TITLE
latency/delay. Again... :-(

### ISSUE THREAD

**Issue by bartplessers** [Koenkk/zigbee2mqtt#9528]
## What happened
State of light changes few seconds after command send

## What did you expect to happen
state changes immediatly

## How to reproduce it (minimal and precise)
Very hard to reproduce, sorry.

Right now, I'm running Z2M for long time (+2Y), and "sometimes" this occurs. 
Don't find the real reason, but I have the feeling that it occurs after one of my routers is disconnected from power and powered on again. Again, this only a subjective feeling as I can not reproduce this. However this is really frustratring, because after 2Y I still not dear to replace all my hardwired wall switches because sometimes the Z2M infrastructure becomes unresponsive. I love the zigbee mesh idea, but compared to my tasmota IP devices,the zigbee mesh is unfortunatly much more unstable.

See also
https://github.com/Koenkk/zigbee2mqtt/issues/7163

I noticed that also some other users are struggling with the same problem
https://github.com/Koenkk/zigbee2mqtt/issues/8460

some logs right now:
```
debug 2021-11-06 09:09:03: Received MQTT message on 'zigbee2mqtt/my/n01/p00/light/L06/hanglamp/set' with data '{"state": "ON"}'
debug 2021-11-06 09:09:03: Publishing 'set' 'state' to 'my/n01/p00/light/L06/hanglamp'
info  2021-11-06 09:09:16: MQTT publish: topic 'zigbee2mqtt/my/n01/p00/light/L06/hanglamp', payload '{"brightness":254,"linkquality":108,"power_on_behavior":null,"state":"ON","update":{"state":"idle"},"update_available":false}'
```
and

```
debug 2021-11-06 09:12:24: Received MQTT message on 'zigbee2mqtt/my/n01/p00/light/L06/hanglamp/set' with data '{"state": "OFF"}'
debug 2021-11-06 09:12:24: Publishing 'set' 'state' to 'my/n01/p00/light/L06/hanglamp'
error 2021-11-06 09:12:47: Publish 'set' 'state' to 'my/n01/p00/light/L06/hanglamp' failed: 'Error: Command 0x086bd7fffe210b20/1 genOnOff.off({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 584 - 1 - 216 - 6 - 11 after 10000ms)'
debug 2021-11-06 09:12:47: Error: Command 0x086bd7fffe210b20/1 genOnOff.off({}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 584 - 1 - 216 - 6 - 11 after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
info  2021-11-06 09:12:47: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'state' to 'my/n01/p00/light/L06/hanglamp' failed: 'Error: Command 0x086bd7fffe210b20/1 genOnOff.off({}, {\"sendWhenActive\":false,\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Timeout - 584 - 1 - 216 - 6 - 11 after 10000ms)'","meta":{"friendly_name":"my/n01/p00/light/L06/hanglamp"},"type":"zigbee_publish_error"}'
```

## Debug info
- Raspberry 4
- CC2652 (Electrolama zig-a-zig-ah! (zzh!)) (on USB extension cable of 2m)
- "optimized" my wifi: only channels 1,6 and 13, alternating over my floorlevels. Bandwidth 20Mhz.
- 81 devices of which 25 routers
- Docker version 20.10.10, build b485636
- Hass in Docker
  - core-2021.11.1
  - supervisor-2021.10.8
- Zigbee2mqtt add-on version: 1.22.0-2
- Z2M config:

```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://xxx.xxx.xxx.xxx
  user: xxxxxxxx
  password: xxxxxxxx
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: info
  pan_id: xxxx
  channel: xx
  network_key:
    - xxx
    - xxx

    - xxx
  availability_blocklist: []
  availability_passlist: []
device_options:
  legacy: false
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false

```

log

```
info  2021-11-06 10:14:37: Starting Zigbee2MQTT version 1.22.0 (commit #unknown)
info  2021-11-06 10:14:37: Starting zigbee-herdsman (0.13.164)
info  2021-11-06 10:14:38: zigbee-herdsman started (resumed)
info  2021-11-06 10:14:38: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210708,"transportrev":2},"type":"zStack3x0"}'
info  2021-11-06 10:14:38: Currently 81 devices are joined:
```

**Comment by rodrigoscoelho** [comment]
I'm having some delays after migrated to CC2652 too. Specially when I do a local command on an interruptor, and the z2m takes like 4 seconds to receive and update the state...
