### ISSUE TITLE
getting error cannot find module 'core-js/features/object/from-entries' after updating with git pull

### ISSUE THREAD

**Issue by pcfreak1** [Koenkk/zigbee2mqtt#9610]
hi, 
i upgraded my zigbee2mqtt raspberry pi wit git pull.
now when i start i get this error:
`pi@raspberrypi:/opt/zigbee2mqtt $ npm start

> zigbee2mqtt@1.22.0 start /opt/zigbee2mqtt
> node index.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'core-js/features/object/from-entries'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/zigbee2mqtt/index.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.22.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.22.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-11-11T21_23_32_053Z-debug.log
`

can anyone help me?

**Comment by pcfreak1** [comment]
fixed it myself,
i ran this command: npm install --save core-js@^3
following this article: https://stackoverflow.com/questions/55606841/how-to-update-core-js-to-core-js3-dependency
